### ISSUE TITLE
pg.mplviewer.drawModel to view data

### ISSUE THREAD

**Issue by Coastal0** [gimli-org/gimli#100]
Following from the mesh-interpolation tutorial, I am trying to display my meshed point cloud data through pygimli.

Attempting to view the data through **pg.mpl.drawModel** fails; however **pg.show** works fine.

```
import pygimli as pg
import numpy as np
import matplotlib.pyplot as plt


coords = np.random.rand(100,2)*10
coords = np.ndarray.tolist(coords)

data = np.random.rand(100)*100
#data = np.ndarray.tolist(data)

datamesh = pg.meshtools.createMesh(coords,quality = 32)

fig, ax = plt.subplots()
test = pg.mplviewer.drawModel(ax,mesh = datamesh, data = data)


pg.show(datamesh,data)
```

```
INFO: drawModel have wrong data length ..  indexing data from cellMarkers()
F:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\matplotlib\backend_bases.py:2453: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)
Traceback (most recent call last):

  File "<ipython-input-17-7f8d9301b30d>", line 1, in <module>
    lala = pg.mplviewer.drawModel(ax,mesh = datamesh, data = data)

  File "F:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\pygimli\mplviewer\meshview.py", line 282, in drawModel
    viewdata = data(mesh.cellMarkers())

TypeError: 'numpy.ndarray' object is not callable
```

**Comment by halbmy** [comment]
`drawModel` is for plotting cell-related quantities (typically a model) and `drawField` is for plotting point-related quantities (typically fields gained by some computation). So you should use the latter. `pg.show` just delegates. However, the error (from trying to map the vector using the cell markers) should not happen anyway or at least throw a meaningful exception.

Interestingly enough, drawModel works also fine using tri=True (the matplotlib triplot function that did not exist when drawModel was created).
