### ISSUE TITLE
Expanded mesh interpolation documentation?

### ISSUE THREAD

**Issue by Coastal0** [gimli-org/gimli#101]
I am struggling to implement the current mesh interpolation example.

For example, I have created a random point-cloud with random data and attempted to interpolate the values using the linear interpolation function.

When I try to interpolate it across the finer mesh, I get a runtime error;

> outmesh = linear_interpolation(datamesh, data, datamesh2)
> Traceback (most recent call last):
> 
>   File "<ipython-input-176-0e9a6ed8be31>", line 1, in <module>
>     outmesh = linear_interpolation(datamesh, data, datamesh2)
> 
>   File "<ipython-input-175-270c5d5fc30b>", line 8, in linear_interpolation
>     outdata = inmesh.interpolationMatrix(outmesh.cellCenters()) *               pg.cellDataToPointData(inmesh, indata)
> 
> RuntimeError:  vector size invalid mesh.cellCount 202 != 104

Obviously I will always have more cells in the finer mesh than the length of the data vector, but I thought this was the point of interpolation?

Could someone help me implement the problem below?

Thanks,

![figure_1-5](https://user-images.githubusercontent.com/25240257/31976257-facd1ba2-b968-11e7-9c28-8d9d0ebd90da.png)

![figure_2-1](https://user-images.githubusercontent.com/25240257/31976288-3421d064-b969-11e7-9d19-1f4ec6bdc93c.png)

```
import pygimli as pg
import numpy as np
import matplotlib.pyplot as plt


coords = np.random.rand(100,2)*10
coords = np.append(coords,([0,0],[0,10],[10,10],[10,0]),axis=0)
coords = np.ndarray.tolist(coords)

coords2 = np.random.rand(1000,2)*10
coords2 = np.append(coords2,([0,0],[0,10],[10,10],[10,0]),axis=0)
coords2 = np.ndarray.tolist(coords2)

data = np.random.rand(104)*100
data = np.ndarray.tolist(data)

datamesh = pg.meshtools.createMesh(coords,quality = 32)
print('Coarse grid has',datamesh.cellCount(), 'cells'.format(i,"string",1))
datamesh2 = pg.meshtools.createMesh(coords2,quality = 32)
print('Fine grid has', datamesh2.cellCount(), 'cells'.format(i,"string",1))

fig, ax = plt.subplots(2,1)
#test = pg.mplviewer.drawModel(ax[0],mesh = datamesh, data = data) # does not work
#test = pg.mplviewer.drawModel(ax[1],mesh = datamesh2, data = data) # does not work
pg.show(ax = ax[0],mesh = datamesh)
pg.show(ax = ax[1],mesh = datamesh2)

# %% Mesh Interp
def linear_interpolation(inmesh, indata, outmesh):
    """ Linear interpolation using `pg.interpolate()` """
    outdata = pg.RVector()  # empty
    pg.interpolate(srcMesh=inmesh, inVec=indata,
                   destPos=outmesh.cellCenters(), outVec=outdata)

    # alternatively you can use the interpolation matrix
    outdata = inmesh.interpolationMatrix(outmesh.cellCenters()) * \
              pg.cellDataToPointData(inmesh, indata)
    return outdata

outmesh = linear_interpolation(datamesh, data, datamesh2)

fig, ax = plt.subplots(2,1)
pg.show(ax = ax[0],mesh = datamesh, data = data)
pg.show(ax = ax[1],mesh = datamesh2, data = data)
```

**Comment by carsten-forty2** [comment]
Everything works as it supposed to be .. see the attached example.

You can only interpolate mesh data if they have the length of the amounts of mesh nodes or mesh cells. 
`createMesh` with a `quality>0` adds additional nodes to achieve the quality needs, so your data array was non valid for interpolation .. as the runtime exception says.

The same for the pg.drawXXX functions .. they have more strict data length needs compared to pg.show. 

```
import pygimli as pg
import numpy as np
import matplotlib.pyplot as plt

coords = np.random.rand(100,2)*10
coords = np.append(coords,([0,0],[0,10],[10,10],[10,0]),axis=0)
coords = np.ndarray.tolist(coords)

coords2 = np.random.rand(1000,2)*10
coords2 = np.append(coords2,([0,0],[0,10],[10,10],[10,0]),axis=0)
coords2 = np.ndarray.tolist(coords2)

data = np.random.rand(104) * 100.

datamesh = pg.meshtools.createMesh(coords, quality=0)
print(datamesh)
datamesh2 = pg.meshtools.createMesh(coords2, quality = 32)
print(datamesh2)

fig, ax = plt.subplots(2,2)
pg.show(ax=ax[0][0], mesh=datamesh, data=data)

#test = pg.mplviewer.drawModel(ax[0], mesh=datamesh, data=data) 
#can't work because draw model need data of length mesh.cellCount()
test = pg.mplviewer.drawField(ax[0][1], mesh=datamesh, data=data)
#works because draw field need data of length mesh.nodeCount()
#show only delegates regarding len(data)

pg.show(ax=ax[1][0], mesh=datamesh2,
        data=pg.interpolate(datamesh, data, datamesh2.cellCenter())) # interpolate to cellValues
pg.show(ax=ax[1][1], mesh=datamesh2,
        data=pg.interpolate(datamesh, data, datamesh2.positions())) # interpolate to nodeValues

pg.show(ax=ax[0][0], mesh=datamesh)
pg.show(ax=ax[0][1], mesh=datamesh)
pg.show(ax=ax[1][0], mesh=datamesh2)
pg.show(ax=ax[1][1], mesh=datamesh2)

pg.wait()
```

**Comment by Coastal0** [comment]
Thanks Carsten. That's perfect. I'll try to apply it to my other problem today.

My apologies for all the dumb questions lately.

I'll gladly give an example back whenever I actually manage to do what I'm trying to do. >_>

**Comment by Coastal0** [comment]
Incredible. It works!!!

Best results I've had all week! 👍 

![figure_3-1](https://user-images.githubusercontent.com/25240257/32030181-ecb40abc-ba2b-11e7-8718-73d234ec70e6.png)

**Comment by Coastal0** [comment]
Can I suggest this sort of example be included in the main examples section, as an additional example? 

I find it far easier to read than the first interpolation example, and it showcases some of the` pg.show()` options too.
