### ISSUE TITLE
A simple DC resistivity modelling case

### ISSUE THREAD

**Issue by Coastal0** [gimli-org/gimli#102]
Are there any examples where 2D DC resistivity has been applied, similar to the heat-equation example provided?

Without in-depth knowledge of the tools available, even this has proven to be an impossible task for me apparently...

**Comment by halbmy** [comment]
If you mean a modelling example like the heat equation example from the paper, I refer to

https://gitlab.com/resistivity-net/bert/blob/master/examples/modelling/2d-python-simple/simple.py

Remember, all the ERT stuff is contained in the BERT repository. As the API doc is not ready yet and modelling is not part of the tutorial, you will have to look through the example directories.

**Comment by Coastal0** [comment]
That looks like what I was after! 

Thankyou.
