### ISSUE TITLE
List of keywords arguments (**kwargs) for pg.show

### ISSUE THREAD

**Issue by Coastal0** [gimli-org/gimli#104]
Hi guys.

Is there a list of keyword arguments for pg.show available somewhere?

I'm trying to set the labels, colormap, title, etc.

```
fig, ax = pg.show(mesh = datamesh_pointcloud, data = dataInterp)
fig.cmap = 'jet'
fig.title = 'title'
etc.
```

**Comment by halbmy** [comment]
You are right in that the documentation of show is lacking as is only a proxy for other functions like showMesh
https://www.pygimli.org/pygimliapi/_generated/pygimli.viewer.html?highlight=show#pygimli.viewer.showMesh
which is (for 2D) internally delegating to the mplviewer functions documented under
https://www.pygimli.org/pygimliapi/_generated/pygimli.mplviewer.html?highlight=drawfield
We should at least make this clear and set appropriate links in the docu.

However, what you are looking for is out of pyGIMLi as fig and ax are matplotlib objects. Please have a look at the matplotlib documentation 
https://matplotlib.org/contents.html#
There is plenty of examples in the internet.

**Comment by Coastal0** [comment]
Ah. Thankyou :)
