### ISSUE TITLE
Argument Error in pg.RMatrix in winpython

### ISSUE THREAD

**Issue by Coastal0** [gimli-org/gimli#106]
I seem to be unable to use the pg.RMatrix() function.

pygimli-1.0.3-cp36-cp36m-win_amd64

Windows 10, using Spyder 3.2.4 , winpython 3.6.2.0Qt5

```
resis = pg.RMatrix(resBulk)
Traceback (most recent call last):

  File "<ipython-input-153-c586b8520799>", line 1, in <module>
    resis = pg.RMatrix(resBulk)

ArgumentError: Python argument types in
    RMatrix.__init__(RMatrix, RVector)
did not match C++ signature:
    __init__(_object*, GIMLI::Matrix<double> mat)
    __init__(_object*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > filename)
    __init__(_object*, std::vector<GIMLI::Vector<double>, std::allocator<GIMLI::Vector<double> > > mat)
    __init__(_object*, unsigned long long rows, unsigned long long cols)
    __init__(_object*, unsigned long long rows)
    __init__(_object*)
```

Works fine in ubuntu.

**Comment by halbmy** [comment]
Obviously you want to initialize an RMatrix by an RVector. Sometimes there are constructors not passed through boost on Windows correctly but I cannot see this constructor in the C++ source code. Anyway, if you want to create a matrix and add a vector (is this what you want?) you can use
```
resis = pg.RMatrix()
resis.push_back(resBulk)
```

**Comment by Coastal0** [comment]
That looks like it worked.... thank you.

Is that the push_back from c++?
 (e.g. http://www.cplusplus.com/reference/vector/vector/push_back/)

I know nothing about c++ yet! 😨

**Comment by carsten-forty2** [comment]
```
resis = pg.RMatrix()
resis.push_back(resBulk)
```
In the mentioned code snipped  `resBul` is supposed to be a two-dimensional matrix. 
There is no known conversion from for `resBul` to a `RMatrix` if `resBul` is a one-dimensional array like `RVector`. You can also construct your matrix from a np.array with ndim==2.

Its all about simulating time depending processes .. for each time step the Matrix got one resistivity row.

```
for i, rbI in enumerate(resBulk):
    resis[i] = 1. / ((1./rbI) + 1./rho0)
```
Is iterating through the time steps and sums the resistivity values for each cell of the mesh from background (rho0) and time varing resistivity (rbl).

If you only want to simulate one steady step you don't need the whole Matrix.

ert.simulate(...) accepts also one-dimenensional array with values for each cell of the simulation mesh.

**Comment by Coastal0** [comment]
Thanks Carsten.

I think I've missed a step somewhere, but why sum them?

**Comment by carsten-forty2** [comment]
Don't know exactly where the original code comes from, so its difficult to speculate from this little fragment.
However, assuming `rbI` is the resistivity for a given time depending brine change you need to add some fixed background to get a valid resistivity distribution.

**Comment by Coastal0** [comment]
ah. 

It's from florians flow modelling example.

Sorry for the questions, but I still don't quite understand. Why can't you just use the resistivity of the brine in formation, through archies law at different time slices?

Is there anywhere you can point me towards? I'll trawl Florians thesis in the meantime...

**Comment by carsten-forty2** [comment]
If you only use your brine values all regions without any brine would be undefined so you need to add some background.
