### ISSUE TITLE
ERT.Simulate -- AttributeError 'NoneType' object has no attribute 'N'

### ISSUE THREAD

**Issue by Coastal0** [gimli-org/gimli#108]
The result has to be close now...
I swear I must owe you all a few beers, at the very least. 
Our timezones seem to be polar opposites!

So, following on from #105, I've tried to simulate my model.

I've assigned everything above the water-table to be ~2000 Ohmm, and anything that doesn't have explicitly data to be 100 Ohmm. I suspect everything (at least in this instance, untill the parameter mesh is created) has values anyway.

...and when I put it all together into ert.simulate, I get an attribute error.

![capture](https://user-images.githubusercontent.com/25240257/32484003-49e8a6b4-c3d9-11e7-8d9b-98671f1ef2a3.PNG)

`rhoa = ERT.simulate(mesh = datamesh_pointcloud_border, res = resis,scheme = ertScheme, verbose=1, returnArray=True)`

```
rhoa = ERT.simulate(mesh = datamesh_pointcloud_border, res = resis,scheme = ertScheme, verbose=1, returnArray=True)
Calculate response for model: 1.671816 2000.0
Traceback (most recent call last):

  File "<ipython-input-278-b0e274b8404f>", line 1, in <module>
    rhoa = ERT.simulate(mesh = datamesh_pointcloud_border, res = resis,scheme = ertScheme, verbose=1, returnArray=True)

  File "F:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\Lib\pygimli\physics\ert\ert.py", line 346, in simulate
    rhoa[i] = fop.response(r)

  File "F:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\Lib\pygimli\physics\ert\ert.py", line 178, in response
    rhs = self.createRHS(mesh, self.electrodes)

  File "F:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\Lib\pygimli\physics\ert\ert.py", line 150, in createRHS
    rhs[i][c.ids()] = c.N(c.shape().rst(e))

AttributeError: 'NoneType' object has no attribute 'N'
```

Diving into it, we get;
```
    def createRHS(self, mesh, elecs):
        """Create right-hand side."""
        rhs = np.zeros((len(elecs), mesh.nodeCount()))
        for i, e in enumerate(elecs):
            c = mesh.findCell(e)
            rhs[i][c.ids()] = c.N(c.shape().rst(e))
        return rhs
```

Is this related to the mesh problems I'm having in #107, or is this a new problem?
I assume all of the sensors have nodes associated with them...but don't know for certain...

**Comment by carsten-forty2** [comment]
The error means that he can find a cell at the electrode position so I guess its a  mesh related problem. Might be a tolerance problem (what we need to fix) or maybe your sensors are aligned x and z coordinate instead of x and y?

Can you please provide the mesh `datamesh_pointcloud_border` and the scheme `ertScheme`

**Comment by Coastal0** [comment]
I don't *think* they're in (x,z) coordinates...!

The saved data file seems to have them in (x,y,_)

[pyGimli_files_new.zip](https://github.com/gimli-org/gimli/files/1449978/pyGimli_files_new.zip)

**Comment by carsten-forty2** [comment]
see #107

**Comment by Coastal0** [comment]
Looks like the issue was the mesh, #107 

The snippet below appears to work;
`rhoa = ERT.simulate(mesh = meshERT, res = resBulk3,scheme = ertScheme, verbose=1, returnArray=True)`

[data.zip](https://github.com/gimli-org/gimli/files/1452826/data.zip)

**Comment by florian-wagner** [comment]
That's good to hear. So I guess, #105 can be closed as well?
