### ISSUE TITLE
Trouble in installing pyBert

### ISSUE THREAD

**Issue by leoviking** [gimli-org/gimli#112]
Hello everybody

My platform is Ubuntu 14.0.4 LTS + Anaconda3-5.0.1_x86_64. running on the  VirtualBox5.1.6.  when I follow the steps on "anaconda.org/gimli/pybert" to install the pybert, it shows that 

"UnsatisfiableError: The following specifications were found to be in conflict:
- anaconda-navigator
-pybert
python 3.6*"

what's the problem? I can't install pygimli too and similar Error show up too.

P.S.
I can't visit  "https://gitlab.com/resistivity-net/bert". How can I get the permission? Thank you.

**Comment by florian-wagner** [comment]
Hi @leoviking,

when using Miniconda (the lightweight option) you only install what you need. When you use Anaconda, which already comes with a bunch of Python packages for Data Science, it is likely that upon installation of new packages, dependency errors will occur. Downgrading is not possible in your case, since the pygimli/pybert dependencies are conflicting with a part of anaconda itself.

If you're not using Miniconda, we recommend to create a separate environment for pygimli (and pybert):

``` bash
# Create a separate environment named bert (you can choose any name) with pybert and all its dependencies installed (pygimli, numpy, matplotlib, etc.)
conda create -n bert pybert # you only have to do this once

# Activate the new environment
source activate bert # you have to do this everytime you want to work with pygimli/pybert
```
I'll close this in favor of https://github.com/gimli-org/gimli/issues/67#issuecomment-313689395, however we need to recommend environments in the documentation.

With regard to your second question, we'll be happy to give you access if you tell us your GitLab username and will probably drop the restrictions anyway anytime soon.

Cheers,
Florian

**Comment by halbmy** [comment]
I also had a personal user feedback about the same issue, people obviously just read `conda`, install anaconda, try it (on Windows as well as Linux) and fail.

**Comment by leoviking** [comment]
OK, I understand. Thank you so much.

Best regards.

**Comment by leoviking** [comment]
@florian-wagner 

My GitLab username is "leoviking". Thanks for your permission.

**Comment by halbmy** [comment]
I added you as a reporter to the BERT project (you should have got an email), i.e. you can see the page, access codes and downloads, create issues and pull requests etc.

**Comment by fabianbt** [comment]
Hi everyone,

I'd like to start using BERT software on windows to invert time-lapse hydrogeophysical data. My Gitlab username and e-mail are Fabian and fbellmunt75@gmail.com, respectively. It would be possible you give me access to the Bert software?

Thank you so much, 
Best wishes

**Comment by itzimah** [comment]
Hello all,

Is it possible to install pybert using anaconda in Windows 10? Or what would be the best way to install/use BERT with pygimli (using Anaconda>>> Spyder)?

Thanks a lot for your help!

**Comment by halbmy** [comment]
Note that this repository is about pyGIMLi and not BERT, the BERT repo is on https://gitlab.com/resistivity-net/bert
There we provide a binary installer for any Windows version, but you can just checkout the code using git and additionally install the pyGIMLi installer using the given installers (wheel or MSI).

**Comment by itzimah** [comment]
Thanks a lot! Is just that I thought I could use pyBert and pyGIMLI without installing BERT, and then just call pyBert in spyder (Anaconda).

But I'll check the other repository, many thanks!!!

**Comment by halbmy** [comment]
Yes, you can use pyBERT on Windows without the BERT installer: by installing one of the pyGIMLi installers (those are still binary) and by downloading/cloning the bert code (and setting the PYTHONPATH in Spyder).

**Comment by Terranigmus** [comment]
Hi  there.

I got it working by just installing the Windows Installers and then adding
the installation directory to my PATH variables as well as to my PYTHONPATH
variable, though this is not really necessary I think.
That way your anaconda distro should pic it up.

Cheers.

2018-06-04 18:07 GMT+02:00 Itzel Isunza Manrique <notifications@github.com>:

**Comment by halbmy** [comment]
Well, as long as there is no conda package for Windows (it is on the todo list), you will need the PYTHONPATH at least to find pyBERT. If you install pygimli using the whl or msi installers into your Anaconda, you don't need to set the PYTHONPATH for it as it will be in the system site-packages.

**Comment by florian-wagner** [comment]
Just realized that one can to a

`pip install git+https://gitlab.com/resistivity-net/bert.git#subdirectory=python`

on every platform without setting a python path. But this is only possible since the gitlab repository is open. We should test it and add it to the documentation.

**Comment by itzimah** [comment]
Many thanks! At the end I cloned BERT code and then I saved the pyBert folder in the same location of pyGIMLI (which I had previously installed with Anaconda). 
Thanks a lot!
