### ISSUE TITLE
TypeError: '>' not supported between instances of 'DataContainer' and 'int'

### ISSUE THREAD

**Issue by Coastal0** [gimli-org/gimli#113]
Hi all,

When I set ` returnArray=False`, I get the aforementioned error when trying to view via `ERT.showData`. When I set it `returnArray=True`, I am able to view the data, but unable to save.

```
data = ERT.simulate(mesh = meshERT, res = resBulk,scheme = ertScheme, verbose=1, returnArray=False)
ERT.showData(data = ertScheme, vals = data)
```

> ERT.showData(data = ertScheme, vals = data)
> Traceback (most recent call last):
> 
>   File "<ipython-input-244-033f48cfe767>", line 1, in <module>
>     ERT.showData(data = ertScheme, vals = data)
> 
>   File "F:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\pygimli\physics\ert\ert.py", line 306, in showData
>     label=r'Apparent resistivity ($\Omega$m)')
> 
>   File "F:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\pygimli\mplviewer\dataview.py", line 96, in patchValMap
>     if logScale and cMin > 0:
> 
> TypeError: '>' not supported between instances of 'DataContainer' and 'int'

[data.zip](https://github.com/gimli-org/gimli/files/1538457/data.zip)

Have I missed something obvious...?

**Comment by carsten-forty2** [comment]
If you set `returnArray=True`, `data` is a Matrix for all entries of the input matrix `res`. To view them you need to choose which row of the Matrix you want to see:

`ERT.showData(data=ertScheme, vals=data[rowIndex])`

If you want to save it you need to save the matrix itself. Either with `data.save(fileName)` if data is of type `pg.RMatrix` or whatever save option you prefer if `data` is of type `numpy.ndarray`.

For `returnArray=False`, which is the default,  `data` is a `DataContainerERT` and you can view them without the vals argument.

`ERT.showData(data=data)`

or 

`ERT.showData(data=data, vals=data('rhoa'))`

and save them with `data.save(Filename, *args)`

**Comment by Coastal0** [comment]
Thanks Carsten. That makes sense now.

However, I seem to have broken the next step too:

`model = ERT.invert(data, paraDX=0.3, maxCellArea=10, lam=30, verbose = 1)`

> model = ERT.invert(data)
> Traceback (most recent call last):
> 
>   File "<ipython-input-265-26d5cd8b677a>", line 1, in <module>
>     model = ERT.invert(data)
> 
>   File "F:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\pygimli\manager\methodManager.py", line 329, in invert
>     paraDX=kwargs.pop('paraDX', 0.3))
> 
>   File "F:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\pygimli\manager\methodManager.py", line 194, in createMesh
>     raise implementme
> 
> NameError: name 'implementme' is not defined

Something to do with the mesh creation...!

I can feed my own mesh in (as opposed to the generated one), and it seems to work.

**Comment by Coastal0** [comment]
Something else seems to have cropped up: 

My `data = ERT.simulate(mesh = meshERT, res = resBulk, scheme = ertScheme, verbose=1, returnArray=False)` now returns the following data;

All of the parameters are in the *.zip file above - I'm not sure what's changed...!
```
# a b m n k valid 
1	2	3	4	-1.00000000000000e+000	1
1	2	4	5	-1.00000000000000e+000	1
1	2	5	6	-1.00000000000000e+000	1
...
42	43	45	46	-1.00000000000000e+000	1
43	44	45	46	-1.00000000000000e+000	1
```

**Comment by Coastal0** [comment]
I started a new issue for this recent problem;
