### ISSUE TITLE
Wheel files incorrectly linked from pyGimli installation page

### ISSUE THREAD

**Issue by BiggusDaveus** [gimli-org/gimli#116]
Hi there,

I'm new to pygimli and after going through the installation instructions I think that the links to the .whl files on this page are incorrect. I downloaded the full pygimli package via the .whl link and I can't find the necessary .whl file within the zip file that downloads.

Downloaded file after clicking on the "Python 3.6 wheel" link:  pygimli-1.0.3.win-amd64-py36.zip

Is this correct and if so could you point me to the required .whl file so I can complete installation of the pygimili.

Thanks very much,

Dave

**Comment by halbmy** [comment]
Hello,
thanks for pointing this out, although the links are completely ok.
While Firefox and Chrome browsers directly download the whl file, the Internet Explorer seems to analyze the file as a zip file (a wheel seems to be nothing else than a zip) and save it as such. Just rename it into whl and it works. Maybe you could even install it with the zip extension.

**Comment by halbmy** [comment]
As there is nothing we could change I am closing this issue.

**Comment by BiggusDaveus** [comment]
Hi there,

That's all cleared up. Thanks so much for the response!

Dave
