### ISSUE TITLE
numpy float64 not accepted as argument for "createMesh"

### ISSUE THREAD

**Issue by Moouuzi** [gimli-org/gimli#118]
The issue with "int" and "int64" format for pyGIMLi is already known, but now I discovered another issue regarding floats:

```
max_a = np.ones(n_layers) * 1e4
for j in range(n_layers):
    pg.meshtools.createMesh(
         poly_node_list,
         quality=34.,
         area=float(max_a[j]))
```

If one uses a np array to asign e.g. the maximum cell_size for triangle in a for loop,
one has to use an explicit float() conversion since the data format of max_a[j] is "numpy.float64" instead of "float". If not, in this case "triangle" (should be also valid for TetGen I think) does not work properly (creates a mesh only by simplest triangulation of the input nodes) without any warning or error.

**Comment by carsten-forty2** [comment]
There should no issue for int and int64 on 64bit system .. any examples for this?

This snipped looks a little weird .. why you create a mesh for every layer .. what do you want to achieve?

Can you please provide `poly_node_list` and `n_layers` that I can check this snipped?

**Comment by halbmy** [comment]
It is not a problem of float or float64.

If you provide a list of positions, `createMesh` goes into
```
    if isinstance(poly, list) or isinstance(poly, type(zip)):
        delPLC = pg.Mesh(2)
        for p in poly:
            delPLC.createNode(p[0], p[1], 0.0)
        return createMesh(delPLC, switches='-zeY')
```
and forgets about the area switch.

**Comment by carsten-forty2** [comment]
It does not forget the area switch. This is behaviour is supposed to be regarding api documentation.
"If poly is a list of coordinates a simple Delaunay mesh of the convex hull will be created."

**Comment by halbmy** [comment]
You're right but if people get used to conveniently passing lists of positions they will wonder about the outcome, so why not fixing it...

**Comment by carsten-forty2** [comment]
the preferred way for the mentioned case would be:
`createMesh(createPolygon(poly, area), quality)`

**Comment by halbmy** [comment]
sorry obviously just a headfake and some misunderstanding
