### ISSUE TITLE
how to check the number of nodes and the index of cells  in my mesh?

### ISSUE THREAD

**Issue by spvfly** [gimli-org/gimli#119]
### Problem description

when I create a mesh, like "mesh = mt.createCircle(star, end)",  I want to check the information of the nodes and cells in my mesh. I have tried "mesh.node", but the message shown in jupyter notebook is that <bound method node of <pygimli.core._pygimli_.Mesh object at 0x7f8e4a389990>>. So,  I want to know how can I get the information of the nodes and cells, like:
node number : 1,      cell's index : 1, 2, 3
node number : 2,      cell's index : 2, 1 ,3

### Your environment

**Operating system**:  Linux 
**Python version**: 3.6
**pyGIMLi version**: 1.0.5+0.gd26a8047
**Way of installation**: Conda package

**Comment by florian-wagner** [comment]
Copying mail from Thomas for the sake of completeness:
> Dear Supeng,
> as the documentation says, node is a function of the Mesh class (which is documented on https://www.pygimli.org/gimliapi/classGIMLI_1_1Mesh.html found under Documentation-CoreAPI): 

> Node & node (Index i)

> so that

> mynode = mesh.node(123) 

> provides the 123th node (also a class documented under https://www.pygimli.org/gimliapi/classGIMLI_1_1Node.html) and so on...
> best
> Thomas

**Comment by florian-wagner** [comment]
The tutorial on pygimli basics also describes how to iterate over cells for example (https://www.pygimli.org/_tutorials_auto/1_basics/plot_1-gimli_basics.html#sphx-glr-tutorials-auto-1-basics-plot-1-gimli-basics-py).

You can find the node indices like this:
``` python
>>> mesh = pg.createGrid(x=(1,2,3), y=(1,2,3))
>>> for cell in mesh.cells():
>>>     print("Cell", cell.id(), "has", cell.nodeCount(), "nodes. Node IDs:", [n.id() for n in cell.nodes()])
Cell 0 has 4 nodes. Node IDs: [0, 1, 4, 3]
Cell 1 has 4 nodes. Node IDs: [1, 2, 5, 4]
Cell 2 has 4 nodes. Node IDs: [3, 4, 7, 6]
Cell 3 has 4 nodes. Node IDs: [4, 5, 8, 7]
```

**Comment by spvfly** [comment]
I have known how to iterate over cells. Thanks!!!!!
