### ISSUE TITLE
FDEM dataset

### ISSUE THREAD

**Issue by LM-RealTime** [gimli-org/gimli#122]
Hello,
First of all I'd like to congratulate you about the paper published in Computers in Geoscience, I found it very well explained and very pedagogical examples. 

As labelled, my issue is rather a question relative to FDEM dataset.
Let me be clearer.

I have a dataset of 4 EM tools, having different coil spacing, different freqs... it does seem that my only option will be "importMaxminData". Correct?

Thanks for your answer.

best

e

**Comment by halbmy** [comment]
Both coil spacing and frequency can be vectors that can come from different instruments. 
You mean you have the individual data in individual files? There is not need to create a single file, instead you can use the direct importing functions to read in data and parameters, stack them together and put them in the FDEM manager directly. If you attach some files I can show you how to do that.

The FDEM manager was one of the first manager developed ever and it needs to be modernized and expanded.

**Comment by ELEGER** [comment]
Thanks for your quick answer,
let's make a small example then, thanks to you.

Enclosed are two file, EM31.csv, coil spacing at 3.66  and frequency 9800 Hz and CMD.csv coil spacing at 1.2 meter and Frequency at 31 kHz.

In advance, thank you.

[EM31.txt](https://github.com/gimli-org/gimli/files/1620310/EM31.txt)
[CMD.txt](https://github.com/gimli-org/gimli/files/1620311/CMD.txt)


I would not bring little help with a case study, if this is something you are looking for. Although I think you already have many dataset, just not the time to take care of it :)

Cheers
e

**Comment by halbmy** [comment]
Well it is easy to read those files with numpy.genfromtxt. Are the field values units percentages of the primary field or apparent resistivities/conductivities? I guess the latter? So there is only an out-of-phase component? I am also a bit puzzled by the x and y coordinates.

At the moment, the FDEM manager can only work with vertical magnetic dipoles (that's one of the things for the expansion), so with those two instruments you end up with only two data for each sounding, so even an inversion of a two-layer model (with 3 unknowns) does not make sense.

Note that FDEM was made for multifrequency EM instruments measuring both in-phase and out phase. So I guess it will not help you here...

**Comment by ELEGER** [comment]
Thanks for the answer Thomas,
I mis-asked then.

You don't have, or don't plan on coding V/H data coming form the same instrument? EM35/EM31 and so on?

Thank you
e

**Comment by halbmy** [comment]
Well, we should just better document. Actually it could be possible to invert those four inphase components for a simple (2-3 layer or smooth) model, but I am not sure whether it is worth investing time before we have restructured the FDEM class(es).

Yes, we will include both V and H components as e.g. the RESOLVE system that we use has both (of which the H is still neglected, what a shame). So stay tuned... Feel free to continue discussion in this issue even though I am now closing it as there is no todo right now (and there is a separate FDEM issue).

**Comment by ELEGER** [comment]
Thank you Thomas,

Best,

e
