### ISSUE TITLE
How doI see/extract coordinates of nodes from a mesh?

### ISSUE THREAD

**Issue by Coastal0** [gimli-org/gimli#128]
My mesh is currently in the `core._pygimli_Mesh` format. 

What command do I need to use to access the `x-y-z` position of the indexed node from `mesh.findNearestNode(i)`?

And more generally, is there some reference points for people to learn the particularities of the hybrid c++/python coding structure? I'd really like to see many of the things locked behind r3vectors and the like...!

**Comment by halbmy** [comment]
`j=mesh.findNearestNode(i)` finds the index of the nearest node, and consequently `n=mesh.node(j)` is the node itself, whose elements can be introspected by `dir(n)`. There is, e.g., `n.pos()` for the whole position, but there is also `n.x()` for the x position and so on. For help on these just type `help(n.x)`.

For the core API documentation you can have to look at https://www.pygimli.org/gimliapi/namespaceGIMLI.html (Documentation-Core API) but we understand that the C++ API is much harder to read than the Python API doc. We should try providing Python wrapper functions for the most important core functions, but also provide a Mesh example and a DataContainer example where the philosophy of meshes, nodes, positions and so on is explained didactically.

**Comment by Coastal0** [comment]
Thanks Thomas. It's easy when you know how! :P

**Comment by halbmy** [comment]
Absolutely, but it is also easy to forget about that it is not easy if you don't. As a community project, we would need more user stories from outside our filter bubble showing this learning process to other users.

**Comment by Coastal0** [comment]
Here's what I used it for, if you were curious;

```
newSensors = np.zeros(sensors.shape)
for pos in enumerate(ertScheme.sensorPositions()):
    print(pos[1])
    j = bPolyMesh.findNearestNode(pos[1])
    n = bPolyMesh.node(j)
    mx = n.x()
    my = n.y()
    print(mx,my)
    newSensors[pos[0]] = [mx,my]

newSensors == sensors
```
```
data = ert.ERTManager.simulate(mesh = bPolyMesh, res = dInterp, scheme = ertScheme, verbose=1, returnArray=False)
```

This code didn't originally work due to the same issue referenced in #108, so I thought that, maybe I should force the sensors to exist on nodes.

```
Calculate response for model: 199.99999999713333 35000.0
Resp:  nan nan
```
It still didn't work, but that wasn't the point! :P

**Comment by carsten-forty2** [comment]
Some very first and basic insights to the c++/python coding structure can be also found here:
https://www.pygimli.org/_tutorials_auto/1_basics/plot_1-gimli_basics.html#gimli-basics

We will improve the tutorials step by step.

In general we bind every part of the c++ core library to python so the api syntax remains the same. From the users point of view there should be no difference in usage between core-c++ and python parts beside the fact there is a different location for the core api-documentation: https://www.pygimli.org/gimliapi/namespaceGIMLI.html 

Currently we are looking for a way to merge these documentations.
