### ISSUE TITLE
Avoid static link to libgimli.so in _pygimli_.so

### ISSUE THREAD

**Issue by florian-wagner** [gimli-org/gimli#13]
If I copy a complete directory tree including gimli/trunk and gimli/build to a different location. GIMLi is not working anymore. It seems like libgimli.so is hardlinked to its old location when I call ```ldd _pygimli_.so```.

Can that be avoided?

**Comment by carsten-forty2** [comment]
I cannot reproduce this issue:

I removed all old libgimli.so and _pygimli_.so from the current paths and tried:

cp -r gimli gimli.test
cd gimli.test/trunk/python
export PYTHONPATH=/home/carsten/src/gimli.test/trunk/python/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/carsten/src/gimli.test/build/lib/
python -c 'import pygimli as pg; print(pg.versionStr())'
> libgimli-0.9.7

**Comment by florian-wagner** [comment]
Sorry, my mistake. Obviously forgot to reset the LD_LIBRARY_PATH.

**Comment by ladominguez** [comment]
I am having an issue with that library. 

[ 21%] Linking CXX shared module /Users/antonio/src/gimli/gimli/python/pygimli/core/_pygimli_.so
Undefined symbols for architecture x86_64:

Am I missing something?

**Comment by carsten-forty2** [comment]
Did your followed the steps here?:
https://www.pygimli.org/installation.html#installation-on-mac-os

We currently don't have access to any mac hardware so we can't  reproduce this problem.

**Comment by ladominguez** [comment]
I see, yes I am following those instructions. Everything worked fine until the command make pygimli

**Comment by diegozain** [comment]
Hi, I have the same problem as @ladominguez  on Mac. Everything goes ok until make pygimli:

```console
Undefined symbols for architecture x86_64:
  "boost::python::detail::init_module(PyModuleDef&, void (*)())", referenced from:
      _PyInit__pygimli_ in _pygimli_.main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
