### ISSUE TITLE
Iterating over cells

### ISSUE THREAD

**Issue by RandomForestGump** [gimli-org/gimli#139]
Hey this is a pygimli mesh **general query,** how do you iterate over cells and to assign different values of resistivity to each node point of different layers in mesh. I am attaching my mesh jpeg here for your better understanding. Can you please give some expertise on the same?

![capture](https://user-images.githubusercontent.com/20444857/38540496-fec0f4ac-3c50-11e8-9e5c-e87d4ee60ebf.PNG)

Thank You.

**Comment by florian-wagner** [comment]
Hi @RandomForestGump,

find a minimal working example attached. We will soon integrate such snippets in the tutorials or a dedicated snippet section:

``` python
import pygimli as pg
mesh = pg.createGrid(x=[-1.0, 0.0, 1.0, 4.0], y=(-1.0, 0.0, 1.0, 4.0)) # some mesh
res = [] # empty list
for cell in mesh.cells(): # iterating over all cells
    if cell.center().y() > 0: # check the y-position of the cell center
        res.append(10)
    else:
        res.append(1)
pg.show(mesh, res) # plot the result
```

You can also iterate over nodes in the mesh the same way `for node in mesh.nodes()`. If you want to use different values for the layers in your mesh, it would be better to use markers. You can add region markers to your geometry prior to mesh generation (`geom.addRegionMarker`) and then map values to each region using the `pg.solver.parseMapToCellArray` function.

**Comment by florian-wagner** [comment]
P.S.: Please close this issue if this answers your question.

**Comment by RandomForestGump** [comment]
Yes please can you close this? And thank you so much!
