### ISSUE TITLE
Question - ERROR: cannot import the library '_pygimli_'.

### ISSUE THREAD

**Issue by AngelieP** [gimli-org/gimli#140]
### Problem description
Installation final message error
I properly installed Anaconda ans msys command shell.
Then I followed the "Building pyGIMLI from source" procedure.
The following message error appeared. 

ERROR: cannot import the library '_pygimli_'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\msys64\home\portal\gimli\gimli\python\pygimli\__init__.py", line 57, in <module>
    from . import core
  File "C:\msys64\home\portal\gimli\gimli\python\pygimli\core\__init__.py", line 43, in <module>
    from .. _logger import *
  File "C:\msys64\home\portal\gimli\gimli\python\pygimli\_logger.py", line 44, in <module>
    setDebug(False)
  File "C:\msys64\home\portal\gimli\gimli\python\pygimli\_logger.py", line 31, in setDebug
    core._pygimli_.setDebug(False)
AttributeError: 'NoneType' object has no attribute 'setDebug'
No module named 'pygimli.core._pygimli_'
Traceback (most recent call last):
  File "C:\msys64\home\portal\gimli\gimli\python\pygimli\core\__init__.py", line 33, in <module>
    from . _pygimli_ import *
ModuleNotFoundError: No module named 'pygimli.core._pygimli_'

Finialize
Set the following setting to use pygimli, either locally
per session or permanently in your /home/portal/.bashrc

export PYTHONPATH=/home/portal/gimli/gimli/python
export PATH=/home/portal/gimli/gimli/python/apps:$PATH

I update de .bashrc file.
Is this a major problem and how to fix it?
Can I use pyGIMLi despite this?
Thank you!

### Your environment

**Operating system**: Window 10
**Python version**: 3.6
**pyGIMLi version : 0+untagged.1780.g86f2041
**Way of installation**:  curl script

**Comment by carsten-forty2** [comment]
Maybe there were some problems during the build. Can you give some build logs to identify any prior problems?

You could also try the prebuild windows binary packages,  they are usually quiet up to date.

**Comment by AngelieP** [comment]
I closed msys, restarted it and install again. Major components have been installed (good news) but the same error message appeared (bad news).
Folowing, the log (sorry for the lenght): 

Installing GIMLi for win64

~/gimli ~
~/gimli/build ~/gimli ~
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: C:/msys64/usr/bin/git.exe (found version "2.17.1")
STATUS,TRUE
STATUS,setting version from git description: v1.0.6-63-gf5068d4c
-- Target is 64 bits
-- ThirdParty set to: C:/msys64/home/portal/gimli/gimli/../thirdParty/
-- External set to: C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Found PythonInterp: C:/ProgramData/Anaconda/python.exe (found suitable version "3.6.5", minimum required is "3")
-- Trying to guess boost installation:
-- no BOOST_INCLUDE_DIR
-- reading C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/.boost-py3.dist
-- BOOST_ROOT from C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/.boost-py3.dist: C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/boost_1_61_0-gcc-7.3.0-64-py36
-- Boost_INCLUDE_DIR, C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/boost_1_61_0-gcc-7.3.0-64-py36/include
-- Boost version: 1.61.0
-- Boost is local False
-- Boost found
-- reading C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/.boost-py3.dist
-- BOOST_ROOT from C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/.boost-py3.dist: C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/boost_1_61_0-gcc-7.3.0-64-py36
-- Boost_INCLUDE_DIR, C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/boost_1_61_0-gcc-7.3.0-64-py36/include
-- BOOST_ROOT, C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/boost_1_61_0-gcc-7.3.0-64-py36
-- Boost_INCLUDE_DIR, C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/boost_1_61_0-gcc-7.3.0-64-py36/include
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   system
--   thread
--   chrono
-- boost include: C:/msys64/home_/portal/gimli/thirdParty/dist-GNU-7.3.0-64/boost_1_61_0-gcc-7.3.0-64-py36/include
-- Looking for C++ include boost/interprocess/managed_shared_memory.hpp
-- Looking for C++ include boost/interprocess/managed_shared_memory.hpp - found
-- Looking for C++ include boost/bind.hpp
-- Looking for C++ include boost/bind.hpp - found
-- HAVE_BOOST_INTERPROCESS_MANAGED_SHARED_MEMORY_HPP 1 C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/boost_1_61_0-gcc-7.3.0-64-py36/include
-- Checking for package 'TRIANGLE'
-- External dir: C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64
-- Triangle_INCLUDE_DIR = C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/include
-- Triangle_LIBRARIES = C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libtriangle.a
-- Found Triangle: C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libtriangle.a
-- Triangle is local True
-- Triangle found
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: C:/msys64/mingw64/lib/libopenblas.dll.a
-- BLAS is local False
-- BLAS found
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- LAPACK is local False
-- LAPACK found
-- Checking for package 'CHOLMOD'
-- adding LAPACK_LIBRARIES to CHOLMOD PATH: C:/msys64/mingw64/lib/libopenblas.dll.a;C:/msys64/mingw64/lib/libopenblas.dll.a
-- Found CHOLMOD: C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libcholmod.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libcamd.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libamd.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libcolamd.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libccolamd.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libsuitesparseconfig.a;C:/msys64/mingw64/lib/libopenblas.dll.a;C:/msys64/mingw64/lib/libopenblas.dll.a;C:/msys64/mingw64/lib/libopenblas.dll.a
-- CHOLMOD_LIBRARIES: C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libcholmod.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libcamd.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libamd.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libcolamd.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libccolamd.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libsuitesparseconfig.a;C:/msys64/mingw64/lib/libopenblas.dll.a;C:/msys64/mingw64/lib/libopenblas.dll.a;C:/msys64/mingw64/lib/libopenblas.dll.a
-- CHOLMOD is local False
-- CHOLMOD found
-- UMFPACK_LIBRARIES: C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libumfpack.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libcolamd.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libamd.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libsuitesparseconfig.a
-- Found UMFPACK: C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/include
-- ************** TRUE
-- openblas is used: C:/msys64/mingw64/lib/libopenblas.dll.a
-- openblas is used:
-- not found cppunit
-- Found PythonLibs: C:/ProgramData/Anaconda/libs/libpython36.a (found version "3.6.5")
-- Find python module numpy
-- Result: 0
-- Output: C:\ProgramData\Anaconda\lib\site-packages\numpy\
-- Found numpy: C:\ProgramData\Anaconda\lib\site-packages\numpy\
CMake Warning at C:/msys64/mingw64/share/cmake-3.11/Modules/FindBoost.cmake:1723 (message):
  No header defined for python-py36; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:331 (find_package)

-- Could NOT find Boost
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   python3
-- clang++ found : C:/msys64/mingw64/bin/clang.exe
-- Found castxml executable:
-- castxml is local True
-- castxml found
-- Found pygccxml path: C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64
-- pygccxml is local True
-- pygccxml found
-- Found pyplusplus path: C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64
-- pyplusplus is local True
-- pyplusplus found
-- **********************************************************************
-- ************************* Dependencies found *************************
-- **********************************************************************
-- THREADS            :TRUE
-- USE_BOOST_THREAD   :TRUE C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/boost_1_61_0-gcc-7.3.0-64-py36/lib/libboost_thread-mt.dll
-- CHOLMOD_LIBRARIES  :C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libcholmod.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libcamd.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libamd.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libcolamd.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libccolamd.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libsuitesparseconfig.a;C:/msys64/mingw64/lib/libopenblas.dll.a;C:/msys64/mingw64/lib/libopenblas.dll.a;C:/msys64/mingw64/lib/libopenblas.dll.a
-- UMFPACK_LIBRARIES  :C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libumfpack.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libcolamd.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libamd.a;C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libsuitesparseconfig.a
-- TRIANGLE_FOUND     :TRUE    Triangle_LIBRARIES: C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/lib/libtriangle.a
-- PYTHON_FOUND       :TRUE    PYTHON_EXECUTABLE: C:/ProgramData/Anaconda/python.exe
-- PYTHONLIBS_FOUND   :TRUE    PYTHON_LIBRARY: C:/ProgramData/Anaconda/libs/libpython36.a
-- PYTHON_INCLUDE_DIR :C:/ProgramData/Anaconda/include
-- Boost_PYTHON_FOUND :TRUE    Boost_PYTHON_LIBRARY: C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/boost_1_61_0-gcc-7.3.0-64-py36/lib/libboost_python3-mt.dll
-- numpy_FOUND        :TRUE    PY_NUMPY: C:\ProgramData\Anaconda\lib\site-packages\numpy\
-- CASTER_FOUND       :TRUE    Caster: C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64/bin/castxml.exe
-- PYGCCXML_FOUND     :TRUE    PYGCCXML: C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64
-- PYPLUSPLUS_FOUND   :TRUE    PYPLUSPLUS_PATH: C:/msys64/home/portal/gimli/thirdParty/dist-GNU-7.3.0-64
-- **********************************************************************
-- pygimli can be build. run: make pygimli
-- **********************************************************************

-- Found Doxygen: C:/msys64/mingw64/bin/doxygen.exe (found version "1.8.14") found components:  doxygen missing components:  dot
-- Failed to locate sphinx-build executable (missing: SPHINX_EXECUTABLE) (Required is at least version "1.5")
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Warning (dev) at python/CMakeLists.txt:86:
  Syntax Warning in cmake code at column 67

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by AngelieP** [comment]
I did...such a short coffee break :-) 

- Configuring done
-- Generating done
-- Build files have been written to: C:/msys64/home/portal/gimli/build
Scanning dependencies of target gimli
[  2%] Building CXX object src/CMakeFiles/gimli.dir/cholmodWrapper.cpp.obj
[  4%] Building CXX object src/CMakeFiles/gimli.dir/curvefitting.cpp.obj
[  6%] Building CXX object src/CMakeFiles/gimli.dir/datacontainer.cpp.obj
[  8%] Building CXX object src/CMakeFiles/gimli.dir/dc1dmodelling.cpp.obj
[ 10%] Building CXX object src/CMakeFiles/gimli.dir/elementmatrix.cpp.obj
[ 13%] Building CXX object src/CMakeFiles/gimli.dir/em1dmodelling.cpp.obj
[ 15%] Building CXX object src/CMakeFiles/gimli.dir/gimli.cpp.obj
[ 17%] Building CXX object src/CMakeFiles/gimli.dir/gravimetry.cpp.obj
[ 19%] Building CXX object src/CMakeFiles/gimli.dir/integration.cpp.obj
[ 21%] Building CXX object src/CMakeFiles/gimli.dir/interpolate.cpp.obj
[ 23%] Building CXX object src/CMakeFiles/gimli.dir/inversion.cpp.obj
[ 26%] Building CXX object src/CMakeFiles/gimli.dir/ipcClient.cpp.obj
[ 28%] Building CXX object src/CMakeFiles/gimli.dir/kdtreeWrapper.cpp.obj
[ 30%] Building CXX object src/CMakeFiles/gimli.dir/ldlWrapper.cpp.obj
[ 32%] Building CXX object src/CMakeFiles/gimli.dir/linSolver.cpp.obj
[ 34%] Building CXX object src/CMakeFiles/gimli.dir/line.cpp.obj
[ 36%] Building CXX object src/CMakeFiles/gimli.dir/memwatch.cpp.obj
[ 39%] Building CXX object src/CMakeFiles/gimli.dir/mesh.cpp.obj
[ 41%] Building CXX object src/CMakeFiles/gimli.dir/mesh_io.cpp.obj
[ 43%] Building CXX object src/CMakeFiles/gimli.dir/meshentities.cpp.obj
[ 45%] Building CXX object src/CMakeFiles/gimli.dir/meshgenerators.cpp.obj
[ 47%] Building CXX object src/CMakeFiles/gimli.dir/modellingbase.cpp.obj
[ 50%] Building CXX object src/CMakeFiles/gimli.dir/multimatrix.cpp.obj
[ 52%] Building CXX object src/CMakeFiles/gimli.dir/node.cpp.obj
[ 54%] Building CXX object src/CMakeFiles/gimli.dir/numericbase.cpp.obj
[ 56%] Building CXX object src/CMakeFiles/gimli.dir/optionmap.cpp.obj
[ 58%] Building CXX object src/CMakeFiles/gimli.dir/plane.cpp.obj
[ 60%] Building CXX object src/CMakeFiles/gimli.dir/platform.cpp.obj
[ 63%] Building CXX object src/CMakeFiles/gimli.dir/pos.cpp.obj
[ 65%] Building CXX object src/CMakeFiles/gimli.dir/quaternion.cpp.obj
[ 67%] Building CXX object src/CMakeFiles/gimli.dir/regionManager.cpp.obj
[ 69%] Building CXX object src/CMakeFiles/gimli.dir/shape.cpp.obj
[ 71%] Building CXX object src/CMakeFiles/gimli.dir/solverWrapper.cpp.obj
[ 73%] Building CXX object src/CMakeFiles/gimli.dir/spline.cpp.obj
[ 76%] Building CXX object src/CMakeFiles/gimli.dir/stopwatch.cpp.obj
[ 78%] Building CXX object src/CMakeFiles/gimli.dir/triangleWrapper.cpp.obj
[ 80%] Building CXX object src/CMakeFiles/gimli.dir/ttdijkstramodelling.cpp.obj
[ 82%] Building CXX object src/CMakeFiles/gimli.dir/vector.cpp.obj
[ 84%] Building CXX object src/CMakeFiles/gimli.dir/bert/bert.cpp.obj
[ 86%] Building CXX object src/CMakeFiles/gimli.dir/bert/bertDataContainer.cpp.obj
[ 89%] Building CXX object src/CMakeFiles/gimli.dir/bert/bertJacobian.cpp.obj
[ 91%] Building CXX object src/CMakeFiles/gimli.dir/bert/bertMisc.cpp.obj
[ 93%] Building CXX object src/CMakeFiles/gimli.dir/bert/datamap.cpp.obj
[ 95%] Building CXX object src/CMakeFiles/gimli.dir/bert/dcfemmodelling.cpp.obj
make[2]: ***  Aucune règle pour fabriquer la cible « C:/ProgramData/Anaconda/libs/libpython36.a », nécessaire pour « bin/libgiml                                                                          i.dll ». Arrêt.
make[2]: *** Attente des tâches non terminées....
[ 97%] Building CXX object src/CMakeFiles/gimli.dir/bert/electrode.cpp.obj
make[1]: *** [CMakeFiles/Makefile2:214: src/CMakeFiles/gimli.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
~/gimli ~
~
=========================================================================
TEST pyGIMLi installation
-------------------------------------------------------------------------

ERROR: cannot import the library '_pygimli_'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\msys64\home\portal\gimli\gimli\python\pygimli\__init__.py", line 57, in <module>
    from . import core
  File "C:\msys64\home\portal\gimli\gimli\python\pygimli\core\__init__.py", line 43, in <module>
    from .. _logger import *
  File "C:\msys64\home\portal\gimli\gimli\python\pygimli\_logger.py", line 44, in <module>
    setDebug(False)
  File "C:\msys64\home\portal\gimli\gimli\python\pygimli\_logger.py", line 31, in setDebug
    core._pygimli_.setDebug(False)
AttributeError: 'NoneType' object has no attribute 'setDebug'
No module named 'pygimli.core._pygimli_'
Traceback (most recent call last):
  File "C:\msys64\home\portal\gimli\gimli\python\pygimli\core\__init__.py", line 33, in <module>
    from . _pygimli_ import *
ModuleNotFoundError: No module named 'pygimli.core._pygimli_'
--- ------------------------------------------------------------------------
=========================================================================
Finialize
Set the following setting to use pygimli, either locally
per session or permanently in your /home/portal/.bashrc
-------------------------------------------------------------------------

export PYTHONPATH=/home/portal/gimli/gimli/python
export PATH=/home/portal/gimli/gimli/python/apps:$PATH

**Comment by carsten-forty2** [comment]
ohh .. the build stops before the big part is supposed to start:

> make[2]: *** Aucune règle pour fabriquer la cible « C:/ProgramData/Anaconda/libs/libpython36.a », nécessaire pour « bin/libgiml i.dll ». Arrêt.

Is there such a file "C:/ProgramData/Anaconda/libs/libpython36.a"?
or something similar?

I will take a look into the config script to try handle this .. I never tried with anaconda before.

**Comment by AngelieP** [comment]
There is a "C:/ProgramData/Anaconda/libs/libpython36.lib" file yes (just a different extension).
Anaconda is the usual python distribution we use but if necessary I can change to WinPython.

**Comment by halbmy** [comment]
No, it is not necessary to switch to WinPython (even different WinPython versions provide different files). Very strange indeed, my Anaconda version has a file libpython36.a and no libpython36.lib in the libs directory. Therefore building works on my Windows computer (which I used to create the binary versions).

By the way, why are you building pyGIMLi from the sources? The easier way is to install the binary versions provided on pygimli.org.

**Comment by AngelieP** [comment]
Sorry for my late reply.
I finally install BERT only which is necessary for my present work. And it works well now.
Thank you for you help.
Regards,
Angélie.

**Comment by carsten-forty2** [comment]
good .. then we can close this issue

**Comment by Coastal0** [comment]
[For your general information]

I've recently refreshed my Conda install (to v5.1) and get the same error.

In my '`\anaconda3\libs\' folder` I have
```
_tkinter.lib
python3.lib
python37.lib
```
I have no python36.lib

**Comment by florian-wagner** [comment]
Please do `conda install python=3.6` for now. 

Binary packages are not build against Python 3.7 yet.

**Comment by halbmy** [comment]
As Python 3.7 seems to be the default on both Linux and Windows now, we should really provide binary packages (conda, wheel/msi) for both Python 3.6 and 3.7 (while 3.5 can possibly be dropped? ). 
I am just downloading Anaconda 5.3 for Windows and start building.

**Comment by florian-wagner** [comment]
@Coastal0 Just released a new conda package. Could you please try if `conda -c gimli install pygimli=1.0.9` works for you now under linux (and installs python 3.7) ?

Thanks a lot.
