### ISSUE TITLE
QUESTION about petrophysical joint inversion

### ISSUE THREAD

**Issue by itzimah** [gimli-org/gimli#142]
Hello

### This is a doubt regarding the petrophysical joint inversion

I have read the example on the paper from 2017 but I'd appreciate some help... I have true ERT (64 electrodes) and TT (64 geophones) data. Then I'm using the transformations 

transInvArchiePhi()
transFwdWylliePhi()

instead of transform to saturation(rho) as in the  article's example (because I couldnt  find this function)

Then I use 

jointpet = JointPetroInversion([ERTManager(),Refraction()],[transInvArchiePhi(),transFwdWylliePhi()])

PHIjoint = jointpet.invert([data,dataTEST],mesh=pmesh)

where data = pg.DataContainerERT('DPDPn7.txt')  --->my ERT data
dataTEST = pg.DataContainer(sgtFile, 's g')   ----> my TT data

and pmesh is generated with createMesh based on the object Refraction or the ERTManager (I've tried with both). Then the following error appears after compiling:

_________________________________________________________________________________
  File "C:\Users\Itzel\Anaconda3\lib\site-packages\pygimli\physics\petro\modelling.py", line 182, in setData
    data[i]('err') / data[i](mgr.dataToken()))

RuntimeError: C:/msys64/home/Guenther.T/py36/gimli/gimli/src/datacontainer.cpp: 656		GIMLI::RVector* GIMLI::DataContainer::ref(const string&)  unknown token data for ref: err available are: SensorIdx: g s  Data: t valid
 
____________________________________________________________

But I dont understand if this is more related to pmesh, is it because ERT and TT data have not the same lenght? Should I first interpolate the data so that both sets of data have the same dimensions? Or this is done automatically in the JointPetroInversion object?

Thanks a lot for your help!!

**Operating system**: Windows
**Python version**:  3.6.4
**pyGIMLi version**: 0+untagged.1780.g86f2041
**Way of installation**:  Anaconda 64 bit

**Comment by florian-wagner** [comment]
Hi @itzimah, the error message is just stating that it is missing the `err` column in your data set. You can estimate it with https://www.pygimli.org/pygimliapi/_generated/pygimli.physics.html?highlight=estimateerror#pygimli.physics.Refraction.estimateError for example and add it to your data container with `data.set("err", YOURERROR)`.

Cheers
Florian

P.S.: The joint inversion does not require traveltime and electrical resistivity data to be of the same length.

**Comment by itzimah** [comment]
Thanks a lot for the help (and sorry again to ask) . I did this and this error no longer appears. However, I still dont understand the JointPetroInversion module. I have the same code:


res = pb.Resistivity('DPDPn7.txt')
ra = Refraction('merged.sgt')

PHIert = transInvArchiePhi()
PHItt = transFwdWylliePhi()
jointpet = JointPetroInversion([ERTManager(),Refraction()],[PHIert,PHItt])
PHIjoint = jointpet.invert([res,ra],mesh=pmesh)#,mesh=pmesh2)


and I have this error 
_____________________________________________________________________________________


  File "C:\Users\Itzel\Anaconda3\lib\site-packages\pygimli\physics\petro\modelling.py", line 29, in setData
    pg.ModellingBase.setData(self, data)

ArgumentError: Python argument types in
    ModellingBase.setData(PetroModelling, ERTManager)
did not match C++ signature:
    setData(GIMLI::ModellingBase {lvalue}, GIMLI::DataContainer {lvalue} data)
________________________________________________________________________________________

So, the input of this function may be wrong, but comparing with the input of the article's example I dont understand what could it be...

Many many thanks!!

Itzel

**Comment by florian-wagner** [comment]
In your first two lines, you initiate instances of the Resistivity and of the Refraction Manager and in line number 4 you give new instances to the JointPetroInversion Framework. It looks like you mix managers and data. See here for example:
https://github.com/gimli-org/gimli/blob/master/doc/paper/cg17/example-3_gimli_version.py#L129-L133

The manager instances `ERT` and `TT` are not the same as `ertData` and `ttData`.
