### ISSUE TITLE
"QUESTION"

### ISSUE THREAD

**Issue by itzimah** [gimli-org/gimli#145]
### Visualize a model with irregular grid

Hello,
I'm trying to visualize a model RVector, which is originated from a transformation of a resistivity model (coming from a inversion of real data), i.e.

data = pb.DataContainerERT('L1_RES.dat')
 res = pb.Resistivity('L1_RES.dat')
 pmesh2 = res.createMesh(quality=34.5,paraDX=0.5,depth=20)
ResAp = res.invert(mesh=pmesh2,lam=3,maxIter=25,robustData=1)
resTrans = ArchieInvSat(rFluid=20, phi=0.7, m=2, n=2)    #put resistivity model in saturation
satERT = resTrans(ResAp)
satERTNorm = satERT/max(satERT)
ttTrans = WyllieTrans(vm=350,phi=0.3,vw=1484)
slownessModel = ttTrans(satERTNorm)
velModel = 1./ttTrans(satERTNorm)

I've tried to use one of your functions showModel(None,velModel,pmesh2) and I got

```
File "C:\Users\Itzel\Anaconda3\lib\site-packages\pygimli\viewer\showmesh.py", line 256, in showMesh
    print("Exception occured: " + e)

TypeError: must be str, not AttributeError
```

And I dont understand what could it be, do I need to use a TT manager for the variable velModel and create a new mesh maybe?

Thanks a lot!!

**Comment by halbmy** [comment]
Well, first it is hard to reproduce your error without having the data file `L1_RES.dat`, please add it in such cases. However, the matter is quite clear: for resistivity inversion you need a mesh with an inner (inversion) region, and an outer region needed for the forward calculation (boundary conditions).

The resulting resistivity vector lives only on the inner mesh, which can be accessed by `res.paraDomain` and should be used to plot any model vector. Even easier, however, is to use the manager function `res.showModel(vals=velModel)` (followed by any **kwargs) instead.

**Comment by itzimah** [comment]
Oh thanks a lot, I understand.
Thanks.
