### ISSUE TITLE
Request of information about refraction tomography outputs

### ISSUE THREAD

**Issue by ksabor** [gimli-org/gimli#146]
### Problem description

Hello, 
I am using pygimli to do forward and inverse calculations of refraction tomography.

I have some questions concerning the output results obtained as described in the refraction example "plot_1_refraction_manager.py".

I followed the example and created a model as described in figure 1.
![image](https://user-images.githubusercontent.com/43140811/45301152-9f35af80-b510-11e8-87b3-6cb9accf2f2e.png)

After the inversion, I wanted to know why do we have "white" areas in the figure showing the inverted velocity profile obtained even if the value of the resistivity is within the range of the velocity map? (Figure 2 attached) 
![image](https://user-images.githubusercontent.com/43140811/45301554-7f52bb80-b511-11e8-930d-d6c413e14ea3.png)
Those white areas are not visible when results are plotted using the "showResultsAndFit" function:
![image](https://user-images.githubusercontent.com/43140811/45301757-dd7f9e80-b511-11e8-94ce-d79b36bcc672.png)

Thank you in advance for yor answer.
Best regards,
Kawtar

### Your environment

Operating system: Windows
Python version: 3.6
pyGIMLi version: 1.0.6
Way of installation:  Conda package

```python
# -*- coding: utf-8 -*-
"""
Created on Fri Sep  7 11:43:38 2018

@author: B10577
"""
import numpy as np

import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import Refraction

geom=mt.createWorld(start=[-0.25, 0], end=[63.25, -6.4],
                       worldMarker=True)
bloc=mt.createRectangle(start=[13,-0.5],end=[15,-2.155],marker=2)
world=mt.mergePLC([geom,bloc])


###############################################################################
# We start by creating a three-layered slope (The model is taken from the BSc
# thesis of Constanze Reinken (University of Bonn).

m=mt.createWorld(start=[-0.25, 0], end=[63.25, -6.4],
                       worldMarker=True)
bloc=mt.createRectangle(start=[13,-0.5],end=[15,-2.155],marker=2)
geom=mt.mergePLC([geom,bloc])

mesh = mt.createMesh(geom, quality=34.3, area=0.5)
pg.show(mesh)  # Figure 1

###############################################################################
# Next we define geophone positions and a measurement scheme, which consists of
# shot and receiver indices.

numberGeophones = 63
sensors = np.linspace(0., 63, numberGeophones)
scheme = pg.physics.traveltime.createRAData(sensors)


###############################################################################
# Now we initialize the refraction manager and asssign P-wave velocities to the
# layers. To this end, we create a map from cell markers 0 through 3 to
# velocities (in m/s) and generate a velocity vector.  To check whether the
# it is correct, we plot it # along with the sensor positions

ra = Refraction()
vp = np.array(mesh.cellMarkers())
vp[vp == 1] = 250
vp[vp == 2] = 500

pos = np.array(scheme.sensorPositions())
ax, _ = pg.show(mesh, vp, colorBar=True, logScale=False, label='v in m/s')   # Figure 2
ax.plot(pos[:, 0], pos[:, 1], 'w+')

###############################################################################
# We use this model to create noisified synthetic data and look at the
# traveltime curves showing three different slopes.

data = ra.simulate(mesh, 1.0 / vp, scheme, noiseLevel=0.001, noiseAbs=0.001,
                   verbose=True)
# ra.showData(data)  # can be used to show the data.

###############################################################################
# And invert the synthetic data on an independent mesh without # information on
# the layered structure we create a new instance of the class using the data.
# Instead of the data, a file name can be given. This is probably where most
# users with data start. See refraction class for supported formats.

ra = Refraction(data)
ra.showData()     # Figure 3
ra.createMesh(depth=7., paraMaxCellSize=0.5)  # can be omitted
vest = ra.invert()  # estimated velocity distribution

###############################################################################
# The method showResult is used to plot the result. Note that only covered
# cells are shown by default. For comparison we plot the geometry on top.

ax, cb = ra.showResult(label='v in m/s')  # Figure 4
pg.show(geom, ax=ax, fillRegion=False, regionMarker=False,label='v in m/s')  # lines on top



ra.showResultAndFit() # Figure 5

pg.wait()

**Comment by halbmy** [comment]
A refraction tomography with no velocity increase (except in a very very small part of the subsurface) does not make any sense. That's not what refraction is capable of. Basically the rays are all at the surface which is visible by the very thin ray coverage. Practically the model is homogeneous, i.e. a very high lambda value will be able to fit your data within errors (an almost homogeneous model, maybe with a slight anomaly). Please rethink your model.

**Comment by ksabor** [comment]
You are completely right, refraction tomography is not suitable  for the case study I posted. Thanks a lot for your insight and answer. 
Best regards,
Kawtar

**Comment by GGDRriedel** [comment]
To give an answer to the question at hand: The areas are "white" because they are not covered by rays since your model is homogeneous.
