### ISSUE TITLE
Make command error (elementmatrix.cpp)

### ISSUE THREAD

**Issue by asadefrango** [gimli-org/gimli#147]
### Problem description

 Compiler Error while run make command 

### Your environment
Linux: 	Ubuntu 16.04.5 LTS (armv7l)
**Python version**: 3.5 and 2.7 (I have tried in several ways)
**pyGIMLi version**: master (git clone)
**Way of installation**: script and manual installation (I have tried in several ways)
**GCC version** 4, 5 and 8 (I have tried in several ways)

### Steps to reproduce
on installation steps(cmake work, but the make not):
$ cmake ../gimli -DPYVERSION=3.5; make 
or
$ cmake ../gimli ; make

### OUTPUT: 
$ make
[  2%] Building CXX object src/CMakeFiles/gimli.dir/elementmatrix.cpp.o
 In file included from /home/alta/src/gimli/gimli/src/elementmatrix.h:23,
                 from /home/alta/src/gimli/gimli/src/elementmatrix.cpp:19:
/home/alta/src/gimli/gimli/src/vector.h: In instantiation of ‘class GIMLI::Vector<unsigned int>’:
/home/alta/src/gimli/gimli/src/vector.h:410:57:   required from here
/home/alta/src/gimli/gimli/src/vector.h:623:20: error: ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator<(const ValueType&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>]’ cannot be overloaded with ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator<(const uint&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>; uint = unsigned int]’
     inline BVector operator OP (const ValueType & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:630:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(<, std::less)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:617:20: note: previous declaration ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator<(const uint&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>; uint = unsigned int]’
     inline BVector operator OP (const uint & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:630:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(<, std::less)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:623:20: error: ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator<=(const ValueType&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>]’ cannot be overloaded with ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator<=(const uint&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>; uint = unsigned int]’
     inline BVector operator OP (const ValueType & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:631:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(<=, std::less_equal)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:617:20: note: previous declaration ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator<=(const uint&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>; uint = unsigned int]’
     inline BVector operator OP (const uint & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:631:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(<=, std::less_equal)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:623:20: error: ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator>=(const ValueType&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>]’ cannot be overloaded with ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator>=(const uint&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>; uint = unsigned int]’
     inline BVector operator OP (const ValueType & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:632:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(>=, std::greater_equal)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:617:20: note: previous declaration ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator>=(const uint&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>; uint = unsigned int]’
     inline BVector operator OP (const uint & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:632:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(>=, std::greater_equal)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:623:20: error: ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator==(const ValueType&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>]’ cannot be overloaded with ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator==(const uint&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>; uint = unsigned int]’
     inline BVector operator OP (const ValueType & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:633:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(==, std::equal_to)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:617:20: note: previous declaration ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator==(const uint&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>; uint = unsigned int]’
     inline BVector operator OP (const uint & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:633:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(==, std::equal_to)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:623:20: error: ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator!=(const ValueType&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>]’ cannot be overloaded with ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator!=(const uint&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>; uint = unsigned int]’
     inline BVector operator OP (const ValueType & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:634:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(!=, std::not_equal_to)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:617:20: note: previous declaration ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator!=(const uint&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>; uint = unsigned int]’
     inline BVector operator OP (const uint & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:634:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(!=, std::not_equal_to)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:623:20: error: ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator>(const ValueType&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>]’ cannot be overloaded with ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator>(const uint&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>; uint = unsigned int]’
     inline BVector operator OP (const ValueType & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:635:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(>, std::greater)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:617:20: note: previous declaration ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator>(const uint&) const [with ValueType = unsigned int; GIMLI::BVector = GIMLI::Vector<bool>; uint = unsigned int]’
     inline BVector operator OP (const uint & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:635:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(>, std::greater)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h: In instantiation of ‘class GIMLI::Vector<int>’:
/home/alta/src/gimli/gimli/src/vector.h:1406:29:   required from here
/home/alta/src/gimli/gimli/src/vector.h:623:20: error: ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator<(const ValueType&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’ cannot be overloaded with ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator<(const int&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’
     inline BVector operator OP (const ValueType & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:630:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(<, std::less)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:611:20: note: previous declaration ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator<(const int&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’
     inline BVector operator OP (const int & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:630:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(<, std::less)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:623:20: error: ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator<=(const ValueType&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’ cannot be overloaded with ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator<=(const int&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’
     inline BVector operator OP (const ValueType & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:631:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(<=, std::less_equal)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:611:20: note: previous declaration ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator<=(const int&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’
     inline BVector operator OP (const int & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:631:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(<=, std::less_equal)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:623:20: error: ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator>=(const ValueType&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’ cannot be overloaded with ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator>=(const int&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’
     inline BVector operator OP (const ValueType & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:632:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(>=, std::greater_equal)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:611:20: note: previous declaration ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator>=(const int&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’
     inline BVector operator OP (const int & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:632:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(>=, std::greater_equal)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:623:20: error: ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator==(const ValueType&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’ cannot be overloaded with ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator==(const int&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’
     inline BVector operator OP (const ValueType & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:633:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(==, std::equal_to)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:611:20: note: previous declaration ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator==(const int&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’
     inline BVector operator OP (const int & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:633:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(==, std::equal_to)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:623:20: error: ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator!=(const ValueType&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’ cannot be overloaded with ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator!=(const int&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’
     inline BVector operator OP (const ValueType & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:634:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(!=, std::not_equal_to)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:611:20: note: previous declaration ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator!=(const int&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’
     inline BVector operator OP (const int & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:634:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(!=, std::not_equal_to)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:623:20: error: ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator>(const ValueType&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’ cannot be overloaded with ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator>(const int&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’
     inline BVector operator OP (const ValueType & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:635:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(>, std::greater)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:611:20: note: previous declaration ‘GIMLI::BVector GIMLI::Vector<ValueType>::operator>(const int&) const [with ValueType = int; GIMLI::BVector = GIMLI::Vector<bool>]’
     inline BVector operator OP (const int & v) const { \
                    ^~~~~~~~
/home/alta/src/gimli/gimli/src/vector.h:635:1: note: in expansion of macro ‘DEFINE_COMPARE_OPERATOR__’
 DEFINE_COMPARE_OPERATOR__(>, std::greater)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
src/CMakeFiles/gimli.dir/build.make:86: recipe for target 'src/CMakeFiles/gimli.dir/elementmatrix.cpp.o' failed
make[2]: *** [src/CMakeFiles/gimli.dir/elementmatrix.cpp.o] Error 1
CMakeFiles/Makefile2:213: recipe for target 'src/CMakeFiles/gimli.dir/all' failed
make[1]: *** [src/CMakeFiles/gimli.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by carsten-forty2** [comment]
Your ARMv7 seems to be a 32-bit architecture which is not supported so far.

I don't have access to such hardware so I can't test or fix it at the moment.

**Comment by carsten-forty2** [comment]
I close this because of inactivity .. please open a new issue if 32bit support is really necessary so we can discuss it there.
