### ISSUE TITLE
Flexible Mesh Generation Example: Markers do not show

### ISSUE THREAD

**Issue by Coastal0** [gimli-org/gimli#148]
I've been playing with gmsh to generate some pygimli tests. Notably, creating a scenario similar to the example linked below.
https://www.pygimli.org/_examples_auto/1_meshing/plot_gmsh-example.html

I expected to generate a figure showing the marked zones (e.g. the example), but instead got just the mesh.

![figure_1](https://user-images.githubusercontent.com/25240257/46642627-b9fc5200-cbaa-11e8-9274-f8a8e0f145b1.png)

This is my first instance of creating a mesh in such a way, so perhaps there's a step I have missed. For new gmsh users, the example was very difficult to understand.

```python
import matplotlib.pyplot as plt

import pygimli as pg
from pygimli.meshtools import readGmsh

fig, ax = plt.subplots()
mesh = readGmsh(r"C:\Users\264401k\Downloads\gmsh-4.0.2-Windows64\gmsh-4.0.2-Windows64\PyGIMLI_CO2_Test.msh", verbose=True)
pg.show(mesh, ax=ax, markers=True)
ax.set_xlim(-100, 100)
ax.set_ylim(-550, -350)
```

Based on the example, I expected the code pasted above to show me the coloured region markers.

Thanks,

[gmsh-4.0.2-Windows64.zip](https://github.com/gimli-org/gimli/files/2458590/gmsh-4.0.2-Windows64.zip)

**Comment by florian-wagner** [comment]
Hi @Coastal0,

the output looks as expected on my computer:

![gmsh](https://user-images.githubusercontent.com/2799008/46646636-17a78480-cb40-11e8-85be-c88add1f3436.png)

What is your `pg.__version__`? The markers keyword was added in 1.0.6 (see release notes [here](https://github.com/gimli-org/gimli/releases/tag/v1.0.6)).

I assume that your version is too old. You have two options:

1. Update to the [latest release](https://github.com/gimli-org/gimli/releases/latest)
2. Do it by hand:
`pg.show(mesh, mesh.cellMarkers(), label="Cell markers", logScale=False, ax=ax, hold=True, nLevs=len(np.unique(mesh.cellMarkers())))`

Hope that helps.

Cheers
Florian

**Comment by florian-wagner** [comment]
PS: I am sorry to hear that the example was hard to understand, but please keep in mind that it is not intended to be a Gmsh tutorial. There much better resources for that. It's just a quick demonstration on how the Physical Entities of Gmsh are mapped to the pygimli region and boundary markers. Feel free to add information to the example that could be of help for others: https://github.com/gimli-org/gimli/edit/dev/doc/examples/1_meshing/plot_gmsh-example.py

**Comment by Coastal0** [comment]
Thanks Florian! 

My version is still in limbo (see below), but I will update it.
```
pg.__version__
Out[36]: '0+unknown'
```
I'd be happy to make a "Dummy's Guide" if that's useful. Given how user friendly the rest of pyGIMLI is (and it really is), I think it's probably worth a go. I'll give it a try! gmsh is pretty confronting, despite all of the available tutorials...

**Comment by Coastal0** [comment]
I was on 1.0.4 according to the 'conda list'

That explains a bit.
