### ISSUE TITLE
Question: What is the file type supported by the refraction module of pygimli

### ISSUE THREAD

**Issue by ksabor** [gimli-org/gimli#149]
Hello,

I want to use the Refraction module of pygimli to perform refraction tomography inversion and I would like to know what is the type of the file that can be loaded through the refraction module. 
Thank you in advance,
Kawtar

### Your environment

Operating system: Windows
Python version: 3.6
pyGIMLi version: 1.0.6
Way of installation: Win binary

**Comment by ksabor** [comment]
I just found the answer here:
https://github.com/gimli-org/gimli/tree/master/examples/traveltime
I have a .sg2 files. Can those files be converted to the supported files by refraction which are :
    .sgt  (shot-geophone-traveltime) unified data format
    .bms  (binary mesh) GIMLi::Mesh v.1
    .poly (piece-wise linear complex) triangle/tetgen input

Thank you in advance,
Kawtar

**Comment by florian-wagner** [comment]
Hey @ksabor,
since you closed the issue, I assume it worked? Let me know if this is not the case. We have improved the traveltime implementation and will soon provide additional usage examples with pygimli 1.1.
Cheers
Florian

**Comment by GGDRriedel** [comment]
Can you please document this somewhere

**Comment by carsten-forty2** [comment]
https://www.pygimli.org/gimliapi/classGIMLI_1_1DataContainer.html#a3d07be3931623a5ebef2bf14d06d4f50

Please use the search function before demanding things from a non commercial open source project that we maintain in our spare time.
