### ISSUE TITLE
Seismic refraction - source and sensor positions

### ISSUE THREAD

**Issue by Pbottelin** [gimli-org/gimli#150]
Hi everyone,
and first of all, thank you for the amount of work done there.

### Problem description

I am facing an issue trying to place my sensors and sources into different places. I have 4 shots located outside the seismic array (e.g. a far offset on the left, a left shot, a right (reverse) shot and the far offset right shot).
When I try to run my code, I get the following error:
>>>e/Guenther.T/src/gimli/gimli/src/vector.h: 555		const ValueType&  >>>GIMLI::Vector<ValueType>::getVal(GIMLI::Index) const [with ValueType = double; GIMLI::Index = long >>>long unsigned int]
because of:
>>> sx = np.array([px[int(s)] for s in data("s")])

Would that be possible to implement the equivalent of
px = pg.x(data.sensorPositions())
as:
sx = pg.x(data.sourcePositions())

Unfortunately, I don't knowif it is possible and would work as simple as that.

### Your environment

**Operating system**: Windows
**Python version**: 3.6
**pyGIMLi version**: 1.0.8+3.g50676bed
**Way of installation**: whl installation

### Steps to reproduce

# -*- coding: utf-8 -*-
"""
Test de Pygimli
Created on Fri Oct 19 16:21:19 2018

@author: p.bottelin
"""
from IPython import get_ipython
get_ipython().magic('reset -sf')

import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import Refraction

""" ****************************** FUNCTION *********************************  """
def createRAKdata(GEO_POS_LIST, SOURCE_POS_LIST):
	"""Create a refraction data container.
	Default data container for shot and geophon at every sensor position.
	Predefined sensor indices's 's' as shot position and 'g' as
	geophon position.
	Parameters
	----------
	sensors : ndarray | R3Vector
	Geophon and shot positions (same)
	Returns
	-------
	data : DataContainer
	Data container with predefined sensor indieces 's' and 'g' for
	"""
	data = pg.DataContainer()
	data.registerSensorIndex('s')
	data.registerSensorIndex('g')

	for geo_pos in GEO_POS_LIST:
		data.createSensor([geo_pos, 0.0, 0.0])

	S, G = [], []
	for src in SOURCE_POS_LIST:
		for g in range(data.sensorCount()):
			if src is not g:
				S.append(src)
				G.append(g)

	data.resize(len(S))
	data.set('s', S)
	data.set('g', G)
	data.set('valid', np.abs(np.sign(data('g') - data('s'))))
	return data

""" ***************************** MAIN ***********************************  """

layer1 = mt.createPolygon([[900.0, 0.0], [1150.0, 0.0], [1150.0, -5.0], [900.0, -5.0]],
                          isClosed=True, marker=1, area=1)
layer2 = mt.createPolygon([[900.0, -5.0], [1150.0, -5.0], [1150.0, -50.0], [900.0, -50.0]],
                          isClosed=True, marker=2)

geom = mt.mergePLC([layer1, layer2])
mesh = mt.createMesh(geom, quality=10.0, area=1, smooth=[1, 10])
pg.show(mesh)

numberGeophones = 61 (Actually, I have only 24 geophones but pygimli fails converting floats to int internally..)
position_of_geophones = np.linspace(1000.0, 1060.0, numberGeophones)
position_of_sources = np.array([985.0, 997.0, 1063.0, 1075.0])
scheme = createRAKdata(position_of_geophones, position_of_sources)

ra = Refraction()
vp = np.array(mesh.cellMarkers())
vp[vp == 1] = 400 #m/s
vp[vp == 2] = 2600 #m/s

ax, _ = pg.show(mesh, vp, colorBar=True, logScale=False, label='v in m/s')
ax.plot(position_of_geophones, np.zeros(len(position_of_geophones)), 'wv')
ax.plot(position_of_sources, np.zeros(len(position_of_sources)), 'k*')

data = ra.simulate(mesh, 1.0 / vp, scheme, noiseLevel=0.001, noiseAbs=0.001,
                   verbose=True)
ra.showData(data)  # can be used to show the data.

**Comment by Pbottelin** [comment]
Thank you for your help! Best regards

**Comment by florian-wagner** [comment]
Hi @Pbottelin,

both shots and receivers have to be defined as sensors. In the data section, the content of the `s` and `g` columns are indices for the sensor list. Have a look at the example file: https://github.com/gimli-org/gimli/blob/master/examples/traveltime/koenigsee.sgt

You can do `scheme.save("mydata.dat")` and have a look at your file. Your shots are not defined in terms of sensor indices but in terms of x position (which would not work in case of crosshole for example, where all sensors in one borehole have the same x position, so the index-notation is much more flexible).

I have slightly adapted your function. It also accounts for the case where a shot is located on a geophone position.

``` python
def createRAKdata(GEO_POS_LIST, SOURCE_POS_LIST):
    """Create a refraction data container.
    Default data container for shot and geophon at every sensor position.
    Predefined sensor indices's 's' as shot position and 'g' as
    geophon position.
    Parameters
    ----------
    sensors : ndarray | R3Vector
    Geophon and shot positions (same)
    Returns
    -------
    data : DataContainer
    Data container with predefined sensor indieces 's' and 'g' for
    """
    data = pg.DataContainer()
    data.registerSensorIndex('s')
    data.registerSensorIndex('g')
    
    receivers = []
    for geo_pos in GEO_POS_LIST:
        	receivers.append(data.createSensor([geo_pos, 0.0, 0.0]))
         
    shots = []
    for source_pos in SOURCE_POS_LIST:
        shots.append(data.createSensor([source_pos, 0.0, 0.0]))
    
    S, G = [], []
    for src in shots:
        for g in receivers:
            if src is not g:
                S.append(src)
                G.append(g)
    
    data.resize(len(S))
    data.set('s', S)
    data.set('g', G)
    data.set('valid', np.abs(np.sign(data('g') - data('s'))))
    return data
```

Hope this helps. Please close the issue, if this answers your question.

Best wishes
Florian

**Comment by Pbottelin** [comment]
Thank you very much Florian,
this is exactly what I was trying to do.

Best wishes,
and thanks for your work!

Pierre

**Comment by GGDRriedel** [comment]
> Hi @Pbottelin,
> 
> both shots and receivers have to be defined as sensors. In the data section, the content of the `s` and `g` columns are indices for the sensor list. Have a look at the example file: https://github.com/gimli-org/gimli/blob/master/examples/traveltime/koenigsee.sgt
> 
> You can do `scheme.save("mydata.dat")` and have a look at your file. Your shots are not defined in terms of sensor indices but in terms of x position (which would not work in case of crosshole for example, where all sensors in one borehole have the same x position, so the index-notation is much more flexible).
> 
> I have slightly adapted your function. It also accounts for the case where a shot is located on a geophone position.
> 
> ```python
> def createRAKdata(GEO_POS_LIST, SOURCE_POS_LIST):
>     """Create a refraction data container.
>     Default data container for shot and geophon at every sensor position.
>     Predefined sensor indices's 's' as shot position and 'g' as
>     geophon position.
>     Parameters
>     ----------
>     sensors : ndarray | R3Vector
>     Geophon and shot positions (same)
>     Returns
>     -------
>     data : DataContainer
>     Data container with predefined sensor indieces 's' and 'g' for
>     """
>     data = pg.DataContainer()
>     data.registerSensorIndex('s')
>     data.registerSensorIndex('g')
>     
>     receivers = []
>     for geo_pos in GEO_POS_LIST:
>         receivers.append(data.createSensor([geo_pos, 0.0, 0.0]))
>          
>     shots = []
>     for source_pos in SOURCE_POS_LIST:
>         shots.append(data.createSensor([source_pos, 0.0, 0.0]))
>     
>     S, G = [], []
>     for src in shots:
>         for g in receivers:
>             S.append(src)
>             G.append(g)
>     
>     data.resize(len(S))
>     data.set('s', S)
>     data.set('g', G)
>     data.set('valid', np.abs(np.sign(data('g') - data('s'))))
>     return data
> ```
> 
> Hope this helps. Please close the issue, if this answers your question.
> 
> Best wishes
> Florian

I am sort of in the same boat here and still having some issues as the Refraktionmanager seems to take issue with my data so I wanted to try your solution. 

A few questions I have: 

In the docstring there is a
"sensors : ndarray | R3Vector" that is not in your code or yor input of the function. What is it?
And secondly this doesn't seem to care for redundant positions, is this a problem for the inversion and mesh generation later on?
Cheers

**Comment by florian-wagner** [comment]
Hi @GGDRriedel,

I just modified @Pbottelin function, and yes, you are right the `sensors` argument is not used within the function and probably just an artifact of copy/pasting when he made this customized measurement geometry out of another function.

And yes, it does also not account for duplicates, which can create problems during mesh generation. So the easiest would be to clean the inputs accordingly before constructing the data container.

**Comment by GGDRriedel** [comment]
All right, thank you, this clears up my messy ideas.

After sorting out duplicates and sorting the #s g t after shots and geophones it works almost without a flaw.

**Comment by florian-wagner** [comment]
Glad to hear that.
