### ISSUE TITLE
Mesh creation: marker parameter not always honored

### ISSUE THREAD

**Issue by m-weigand** [gimli-org/gimli#152]
### Problem description

When attempting to create a simple 2D mesh consisting of two circles, the first circle marker is always set to 0, instead of the value provided by the *marker* parameter. If this is not a bug or a user error, perhaps a warning should be emitted if the user tries to change the first marker?

![plot_v1_markers](https://user-images.githubusercontent.com/6685391/48070501-49137e80-e1d8-11e8-85d0-5a02900306f7.png)

### Your environment

**Operating system**: Debian Linux
**Python version**: 3.6
**pyGIMLi version**: 1.0.9+0.g117c4466.with.local.changes.on
**Way of installation**: conda

### Steps to reproduce

```python
import pygimli as pg
import pygimli.meshtools as mt

circle1 = mt.createCircle(
    pos=[0.0, 0.0],
    radius=3.0,
    boundaryMarker=0,
    marker=1
)

circle2 = mt.createCircle(
    pos=[0.0, 0.0],
    radius=1.0,
    boundaryMarker=0,
    marker=2
)

plc = mt.mergePLC([circle1, circle2])

mesh = mt.createMesh(
    plc,
    quality=31,
    area=0.1,
)

pg.show(
    plc,
    boundaryMarker=True,
    savefig="plot_v1_plc_boundary_markers.png"
)

pg.show(
    mesh,
    markers=True,
    showMesh=True,
    savefig="plot_v1_markers.png"
)
```

### Expected behavior
I would expect to be able to assign arbitrary integer numbers to the markers.

### Actual behavior

First marker seems to always be zero.

**Comment by halbmy** [comment]
Dear Maxi,
as the code in
https://www.pygimli.org/_modules/pygimli/meshtools/polytools.html#createCircle
shows, is the marker of the circle always set into the midpoint, which is in your case exactly the same position, so the marker 1 in the origin is overwritten by the marker=2. As a fast solution you will have to set another marker somewhere close to the boundary by `plc.addRegionMarker`. We could add an optional argument that sets the marker somewhere on the line between the first point and the center, e.g. by specifying a radial distance, i.e. 0 is the center and 1 is the point, as an enhancement solution.
Thomas

**Comment by m-weigand** [comment]
If the marker is only replaced by the smaller circle, how is the marker 0 in the outer ring created (the original circles had markers 1 and 2, but not 0)?

**Comment by halbmy** [comment]
There is no marker 0 but any cell in a region without region marker gets the marker 0.

**Comment by m-weigand** [comment]
ahh, I see. What about introducing an optional argument **markerPosition**, defaulting to [0.0, 0.0]. This would be a simple change, and this would cover all possible use cases. 

https://github.com/gimli-org/gimli/blob/f09bd8b32e3c867a61d8e1a1b8436ea6d5e5561c/python/pygimli/meshtools/polytools.py#L298

Could be a possiblity for createRectangle, createPolygon, too.

**Comment by carsten-forty2** [comment]
The default positions are: 

- Circle at (0.0, 0.0), 
- Polygon at (center), 
- Rectangle at (start + epsilon*DirectionToEnd), 
- World for each layer (start + eps, depth + eps)

Unfortunately, there aren't any good defaults for any case. 

I will add your idea of the optional argument but this might not prevent users stumble in some edge cases. We maybe can additional pop a warning if there are zero cell markers or no cells with markers that should be exists regarding the PLC.

Eventually, we need more logic or some advanced techniques building the PLC.

Thanks for reporting,
Carsten

**Comment by carsten-forty2** [comment]
you are very welcome :)

**Comment by carsten-forty2** [comment]
Discussion moved to #157 so we can close this.
