### ISSUE TITLE
Questions about Sensitivity visualization and inversion in pybert 

### ISSUE THREAD

**Issue by ksabor** [gimli-org/gimli#154]
###Hello,

I have two new questions about ERT inversion using pybert:
- I was wondering if there already is a method or a function to visualize the sensitivity of ERTdata as for ra.showRayCoverage for the seismic calculations?
- I am using pybert to simulate and invert data of a double layer model with a conductive anomaly in the first layer. For the forward calculations I consider a background region for boundary conditions and I wanted to ask you about the suitable value of resistivity to consider for the background region which is in contact with both the first and the second layer? (layer 1= 200 Ohm.m, layer 2= 2000 Ohm.m and anomaly= 25 Ohm.m)
- For the inversion, I don't give a mesh. It is created by default. I wanted to know if a background is defined for the forward calculations during the inversion and what value of resistivity is assigned by default?

![image](https://user-images.githubusercontent.com/43140811/49084941-26154100-f251-11e8-80cc-b95f86d1ee59.png)

Thanks in advance,
Best regards,
Kawtar

**Comment by halbmy** [comment]
Although this is rather a pybert question, some quick answers:
1. good idea, I added this function `ert.showCoverage()`, in the meanwhile you can use
```
fig, ax = pb.pg.plt.subplots()
ert.showModel(ax=ax, vals=ert.coverageDC(), logScale=False)
```
2. If you do provide zero in the map for the background, it will be prolongated by default from the neighboring layers. However, in your case it is easier to make the layers wide enough.
3. This behaviour (prolongation from the inversion mesh to the outer mesh) is always done.

Note that the ERTmanager is still a playground for simple models that will be improved and better documented soon.

**Comment by ksabor** [comment]
Thanks a lot for your insights. 

Best regards,
Kawtar

**Comment by ksabor** [comment]
Please, can you tell me what does this transfom used un coverageDC method do (to make sur I am well interpreting my sensitivity plot)?

    covTrans = pg.coverageDCtrans(self.fop.jacobian(),
                                      1.0/self.inv.response(),
                                      1.0/self.inv.model())

**Comment by halbmy** [comment]
The original jacobian coming from the forward operator (`fop.jacobian()`) is the partial derivative of the apparent resistivity with respect to the subsurface resistivity. However, in the inversion we usually use the logarithm of both quantities as data and model, respectively. This scales the inverse problem favourably and ensures positive values. So the jacobian (d log rhoa/d log rho) needs to be scaled by the inner derivative of the logarithms, which is 1/rho and 1/rhoa.
