### ISSUE TITLE
Parameter check in createRectangle

### ISSUE THREAD

**Issue by m-weigand** [gimli-org/gimli#158]
Can I reactivate this check?

https://github.com/gimli-org/gimli/blob/d48387795852013568f5bd9afbfea98f03bfca41/python/pygimli/meshtools/polytools.py#L95

**Comment by florian-wagner** [comment]
Then the lines below should be removed. I would suggest adding a unit square as a default (i.e. if nothing is provided) and raising an exception `if len(start) + len(end) != 4`

**Comment by m-weigand** [comment]
Hi Florian, perhaps I was to unspecific:
The documentation states that you can only use "start/end" OR "pos/size", but this is not checked. At the moment you can specify your rectangle with "start/end", and then in addition scale the whole rectangle with "size".
I would like to check for this state and raise an Exception, and lines 95--97 do that. However, there probably is a reason why the check was disabled...

**Comment by carsten-forty2** [comment]
I found no reason why this check was disabled so I removed it while solving a merge conflict.

Feel free to raise this Exception .. alternatively you could only pull a warning that one of the given pairs will be ignored.
