### ISSUE TITLE
Allow user-defined fillValue in pg.interpolate

### ISSUE THREAD

**Issue by florian-wagner** [gimli-org/gimli#16]
`pg.interpolate()` fills cells with 0 by default if it can't find a corresponding counterpart. It would be beneficial to introduce a fillValue parameter to change this behavior if the interpolated quantity contains wanted zeros. And maybe something like `allowExtrapolation=True`?

**Comment by carsten-forty2** [comment]
add keyword argument `fillValue=0.0` to all core interpolate functions. 

Extrapolation might need a different approach with different methods, e.g., 
https://www.pygimli.org/pygimliapi/_generated/pygimli.meshtools.html?highlight=fill#pygimli.meshtools.fillEmptyToCellArray
