### ISSUE TITLE
Refraction in 3D

### ISSUE THREAD

**Issue by mariosgeo** [gimli-org/gimli#163]
I do not have any issue with the code. It works beautifully. 
I was wondering if you are considering refraction in 3D.
I have very long 2D lines. that are not "straight". Some sections of this 2D line, can have around 20 degree "slope". 
I project each geophone source in 2D line, to have the actual distance in 2D, but you could argue that the ray follow a different path from S to R. What do you recommend in those scenarios?

**Comment by florian-wagner** [comment]
@mariosgeo Hi Marios, the traveltime calculations are node-based and work in 3D as well. When you have a 3D mesh for your problem, usage of the refraction manager is similar to 2D (e.g., as in the crosshole example: https://www.pygimli.org/_examples_auto/seismics/plot_3_crosshole_tomography.html), just with a different `mesh` object.

You could create such a mesh relatively straightforward by extruding:

``` python
import pygimli as pg
import pygimli.meshtools as mt
import numpy as np

# Create some 2D mesh which should incorporate your sensor positions
poly = mt.createPolygon([[0.0, 0.0], [10.0, 0.0], [10.0, 10.0]], area=1, isClosed=True)
mesh2d = mt.createMesh(poly)
pg.show(mesh2d)

# Extrude to 3D with arbitrary depth vector (results in triangular prisms)
depth = -np.geomspace(0.1,10, 8)
mesh3d = pg.createMesh3D(mesh2d, depth)
mesh3d.exportVTK("mesh3d.vtk")
```
![image](https://user-images.githubusercontent.com/2799008/52480528-4a27c380-2bac-11e9-9e56-6c8cbf9d6927.png)

![image](https://user-images.githubusercontent.com/2799008/52480536-4f850e00-2bac-11e9-93ed-3d8988d985cb.png)

Best wishes
Florian

**Comment by mariosgeo** [comment]
That is great!!
Thanks Florian, I will look into it.

Best
