### ISSUE TITLE
Trying the Field data inversion (“Koenigsee”) example

### ISSUE THREAD

**Issue by soetpotet** [gimli-org/gimli#164]
Hi,

I'm using pygimli (1.0.10) with Spyder (python 3.6) installed using WinPython, and I'm trying to run your Field data inversion (“Koenigsee”) example (https://www.pygimli.org/_examples_auto/seismics/plot_5_koenigsee.html#sphx-glr-examples-auto-seismics-plot-5-koenigsee-py) but I get the following error: 

`module 'pygimli' has no attribute 'getExampleFile'`

What could be wrong?

Thank you!

**Comment by florian-wagner** [comment]
Hi @soetpotet,

I have added the example yesterday evening together with the new function `pg.getExampleFile`. So it is bleeding edge and not yet part of the binary installers.

We will provide new ones soon, but for now, you'll have to download the data file manually: https://raw.githubusercontent.com/gimli-org/example-data/master/traveltime/koenigsee.sgt
and avoid the `pg.getExampleFile` call.

Best wishes
Florian

**Comment by florian-wagner** [comment]
(or you can compile pygimli from source as detailed in the installation instructions to always be up-to-date)

**Comment by soetpotet** [comment]
Hi again,

Thanks for the quick reply!

Which call would you recommend? I tried pg.load but then I get an error saying that the directory doesn't exist `File or directory named traveltime/koenigsee.sgt does not exist.` even though I have a folder named _traveltime_ with the _koenigsee.sgt_ file in it in the working directory.

Cheers

**Comment by florian-wagner** [comment]
I would use `Refraction(filename)` as in the example. Are you sure it's in the current working directory? Try

``` python
import os
print(os.listdir(os.getcwd()))
```

**Comment by soetpotet** [comment]
Hi Florian,

Thanks! It did work, I just had to add _.txt_ in the file name.

Cheers
