### ISSUE TITLE
Examples Raypaths, Layered Example not working

### ISSUE THREAD

**Issue by Terranigmus** [gimli-org/gimli#167]
### Problem description

Layered Example analytical solution not working

### Your environment

**Operating system**: Win10
**Python version**:  3.6
**pyGIMLi version**: 19/02/19 - 13:14:36 - pyGIMLi - INFO - Version: 0+unknown core:libgimli-v1.0.10-10-g608a9f64
**Way of installation**: Wheel

### Steps to reproduce

Download and execute 
https://www.pygimli.org/_examples_auto/seismics/plot_4_rays_layered_and_gradient_models.html#sphx-glr-examples-auto-seismics-plot-4-rays-layered-and-gradient-models-py

```python
from math import asin, tan

import matplotlib.pyplot as plt
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.mplviewer import drawMesh
mesh_layered = mt.createGrid(
    np.arange(-20, 155, step=5), np.linspace(-60, 0, 13))
vel_layered = np.zeros(mesh_layered.cellCount())
for cell in mesh_layered.cells():
   
    if cell.center().y() < -25:
        vel = 3000.0
    else:
        vel = 1000.0
    vel_layered[cell.id()] = vel

pg.show(mesh_layered, label="Velocity (m/s)")
```

### Expected behavior

Show the layered data to the mesh

### Actual behavior

Only shows colorbar. Analytical soluton later fails, numeric solution works.

```
Nothing to show except empty graphs, can provide screenshot later
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
It works under Linux. Under Windows there is obviously a conversion problem from numpy array to pg.RVector if the data type is int and not float which happens for the x vector (arange). If you append a . to any of the values of the x vector or specify the data type by `dtype=float` all should be working well:
```
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt

x = np.arange(-20, 155, step=5, dtype=float)
y = np.linspace(-60, 0, 13)
mesh1 = mt.createGrid(x=x, y=y)
pg.show(mesh1)
mesh_layered = mt.createGrid(
    np.arange(-20, 155, step=5, dtype=float), np.linspace(-60, 0, 13))
vel_layered = np.zeros(mesh_layered.cellCount())
for cell in mesh_layered.cells():

    if cell.center().y() < -25:
        vel = 3000.0
    else:
        vel = 1000.0
    vel_layered[cell.id()] = vel

pg.show(mesh_layered, vel_layered, label="Velocity (m/s)")
```
![image](https://user-images.githubusercontent.com/7136401/53022637-e0d16b80-345b-11e9-94fe-286827835522.png)

We try to get rid of this problem. Thanks for reporting.

**Comment by halbmy** [comment]
Adapted the script by 38efa680ce807f789687836b90017655d13cec02.
However the conversion problem remains. For now be careful with np.arange that uses int if possible (contrary to np.linspace).
