### ISSUE TITLE
import filed data to joint inversion of EST and SRT

### ISSUE THREAD

**Issue by xichaoqiang** [gimli-org/gimli#168]
### Problem description
Recently, I study joint inversion of  cross-hole ERT and cross-hole SRT(Seismic traveltime tomography).

I want try some filed data of cross-hole traveltime tomography and ERT.

1 Can I import the picking firstbreak file and invert like below?
>>>#ttData = TT.simulate(mMesh, vel, ttScheme, noiseLevel=0.01, noiseAbs=4e-6) #Used in example-3.py

>>>ttData = pg.readTOMfile (filename) #import data from file.
>>>velInv = TT.invert(ttData, mesh=pMesh, lam=100, useGradient=0, zWeight=1)

2  Can I import the bert file and invert  like below?
 >>>#ertData = ERT.simulate(mMesh, res, ertScheme, noiseLevel=0.01) #Used in example-3.py

 >>>ertData = pg.DataContainerERT(filename) #import data from file.
 >>>resInv = ERT.invert(ertData, mesh=pMesh, zWeight=1, lam=20)

### Your environment

**Operating system**:  Windows
**Python version**: 3.6?
**Way of installation**:  Win binary

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
import pygimli as pg
...
```

### Expected behavior

Tell us what should happen or what you want to achieve.

### Actual behavior

Tell us what happens instead and/or provide the output of your script.

```
Paste output here.
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
Yes you can. Did you try already? Are there error messages?

Seems like you have your import for SRT ready. Depending on your ERT import file, the BERT package
https://gitlab.com/resistivity-net/bert
might be helpful to import instrument or other formats using `dataERT=pybert.importData(filename)`.

**Comment by xichaoqiang** [comment]
I haven't try.

Because I meet a error when try example-3.py

other example like "plot-4-dc1dsmooth.py" and "plot_3_crosshole_tomography.py" is OK.
![image](https://user-images.githubusercontent.com/30900789/55055351-aaf85600-509d-11e9-83cb-0d8fdb727375.png)

**Comment by halbmy** [comment]
Thanks for reporting. We will look into that. Can you please specify which pygimli version (and installation type) and which python distribution & version are you using?

In the meanwhile you can go ahead with your field data files.

**Comment by xichaoqiang** [comment]
OS version : Windows 10 64bit
Python version anaconda 3- 5.2.0 (Python 3.6)
Pygimli version :1.0.10
My data is not prepare yet. I want to perform a joint inversion of cross-hole tomography under a synthetic model for ERT and SRT.

**Comment by halbmy** [comment]
I can confirm the error on both Anaconda 5.2 (with Python 3.6) and Anaconda 5.3 (with Python 3.7), using the whl and msi installers. (By the way the Py 3.6 msi installer had a problem with a missing physics.SIP module). I will test this also with the Linux versions but I assume it is the same.

However, the example works with my dev version (1.0 branch). Therefore I suggest, even though we are working on a pygimli 1.1 version, to create a "final" version 1.0.11, where all examples and tutorials should be working which can be used as a "reference version" when testing v1.1. I start doing it on Windows.

**Comment by halbmy** [comment]
As far as I can see, example 3 is running with the 1.0.11 version so that we can close the issue. Importing data formats is another topic and there were no data files attached anyway.
