### ISSUE TITLE
custom rvalue converter from/to RMatrix

### ISSUE THREAD

**Issue by florian-wagner** [gimli-org/gimli#17]
Implement a more efficient way to convert between numpy.arrays and pg.RMatrix.

**Comment by carsten-forty2** [comment]
- [ ] A = pg.RMatrix(np.ones((4,4))
- [ ] A = np.array(pg.RMatrix(4,4))
- [ ] ...

**Comment by carsten-forty2** [comment]
rvalue conversion for ndarray of dtype=float via memcopy.
Works only for nonsegmented numpy arrays and throws exception for segmented data .. will implement the latter on demand if necessary

**Comment by carsten-forty2** [comment]
core -> numpy seems to work with default iterators.

Please report for problems or open a new ticket if there are significant performance issues.
