### ISSUE TITLE
meshtools.readHydrus2dMesh()

### ISSUE THREAD

**Issue by sarahgarre** [gimli-org/gimli#173]
### Failure import hydrus2d mesh

I am trying to reproduce the work Thibault Manhaeghe has done with help of Florian Wagner for his MSc thesis. However, when calling meshtools.readHydrus2dMesh() I directly get an error message.
### Your environment
**Operating system**: Windows10
**Python version**: 3.6
**pyGIMLi version**: 0+untagged.2328.g5e7d555
**Way of installation**: pip via windows command window

### Steps to reproduce
```
datadir = 'C:/Users/Admin/OneDrive/Documents/UBC/simul/'
scriptdir = 'C:/Users/Admin/OneDrive/Documents/UBC/scripts'
os.chdir(datadir)

meshHYDRUS = pg.meshtools.readHydrus2dMesh("FINAL_Mesh_20cm.txt")

#os.chdir(scriptdir)
```

### Expected behavior
Load the hydrus mesh

### Actual behavior

```---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-c74c8361ad61> in <module>()
      3 os.chdir(datadir)
      4 
----> 5 meshHYDRUS = pg.meshtools.readHydrus2dMesh("FINAL_Mesh_20cm.txt")
      6 
      7 #os.chdir(scriptdir)

~\Anaconda3\lib\site-packages\pygimli\meshtools\mesh.py in readHydrus2dMesh(fname)
    566     fid = open(fname)
    567     line = fid.readline().split()
--> 568     nnodes = int(line[1])
    569     ncells = int(line[3])
    570     mesh = pg.Mesh()

ValueError: invalid literal for int() with base 10: 'Program'```

**Comment by sarahgarre** [comment]
[FINAL_Mesh_20cm.txt](https://github.com/gimli-org/gimli/files/3081968/FINAL_Mesh_20cm.txt)

**Comment by carsten-forty2** [comment]
Thanks for reporting. 
It seems our importer is outdated for the current versions of hydrus .. I will update the importer.

**Comment by sarahgarre** [comment]
what is strange is that I just took over the files and the commands from my MSc student, so it should have worked before...

**Comment by carsten-forty2** [comment]
yes that's strange .. I can't imagine how this file could be read with the old GIMLi importer. 

I commited (35c034e1) a new importer for this format in the new pre 1.1 branch and attached the converted gimli mesh (needs to be unziped).

Also I noticed there is something wrong with the file. The number of 1D and 2D elements that are announced in the header of the file are different to the ammount of cells and boundaries in the file itself.

[FINAL_Mesh_20cm.bms.gz](https://github.com/gimli-org/gimli/files/3082464/FINAL_Mesh_20cm.bms.gz)  

```
import pygimli as pg
mesh = pg.load('FINAL_Mesh_20cm.bms')
pg.show(mesh, data=range(mesh.cellCount()))
pg.wait()
```

**Comment by sarahgarre** [comment]
Ok great. How can i update to a dev branch? Never did that before... Op 15 apr. 2019 17:00 schreef carsten-forty2 <notifications@github.com>:yes that's strange .. I can't imagine how this file could be read with the old GIMLi importer.
I commited (35c034e) a new importer for this format in the new pre 1.1 branch and attached the converted gimli mesh (needs to be unziped).
Also I noticed there is something wrong with the file. The number of 1D and 2D elements that are announced in the header of the file are different to the ammount of cells and boundaries in the file itself.
FINAL_Mesh_20cm.bms.gz
import pygimli as pg
mesh = pg.load('FINAL_Mesh_20cm.bms')
pg.show(mesh, data=range(mesh.cellCount()))
pg.wait()

**Comment by halbmy** [comment]
I don't think it makes sense to switch to the pre1.1 branch right now before other things are cleared up. However if you just need the new function `readHydrusMeshV3` you can copy it from the gitlab Code browser (where you can go through all files and switch to the branch fw_cleaning): https://github.com/gimli-org/gimli/blob/35c034e12e8ab865cc6c94cd94170e0800e22e84/python/pygimli/meshtools/mesh.py#L734

**Comment by carsten-forty2** [comment]
I assume the problem is solved now.
