### ISSUE TITLE
about JointPetroInversion

### ISSUE THREAD

**Issue by BoDoNgAhAi** [gimli-org/gimli#174]
### Problem description

Hello,
I am a novice in programming and have 2 questions and a problem.
I wanted to determine subsurface layers using ERT and TT. 
So, I got field data ERT (96 elecs 3m intervals) and TT (48 gps 5m intervals)  both but the first sensor and last sensor of layouts are not at the same coordinate. Topo is same as both. 
I have read the example of in the paper from 2017 as well as #142.  Mr. Florian-Wagner mentioned in the #142 that "P.S.: The joint inversion does not require traveltime and electrical resistivity data to be of the same length". Therefore, I followed the #142  and his note, got these results. 
(pMesh is created from ERT data)
ERT:
![Figure_1](https://user-images.githubusercontent.com/49978120/56727283-a54f6800-6750-11e9-87be-09af6257e9dc.png)
TT:
![Figure_2](https://user-images.githubusercontent.com/49978120/56727320-b9936500-6750-11e9-87ed-7a8f8a8af9ad.png)
Question 1:
How I put TT inversion in the middle of pMesh? 

Question 2:
I dont have information about rFluid, phi and velocity. So, I would be planning to use different parameters instead of these parameters. In other words, I replace WyllieTrans and ArchieTrans to new parameters. 
After this replace, would JointPetroInversion work?

### Your environment

**Operating system**: Windows 7?
**Python version**: 3.6
**pyGIMLi version**: 0+untagged.2363.g608a9f6
**Way of installation**: e.g. Anaconda 64 bit

### Steps to reproduce

Problem :
Anyway, I wanted to see the result of Petrophysical joint inversion using these code:
ERT.showData(ertData)
TT.showData(ttData)
and got this error for ERT:

>   File "C:\Users\Dell\Anaconda3\lib\site-packages\pygimli\mplviewer\dataview.py", line 158, in patchValMap
>     ax.set_xlim(min(xvec) - dx / 2, max(xvec) + dx / 2)
> 
> AttributeError: 'DataContainerERT' object has no attribute 'set_xlim'**

and for TT:

>  File "C:\Users\Dell\Anaconda3\lib\site-packages\pygimli\core\__init__.py", line 490, in __getVal
>     return self.getVal(int(idx))
> 
> IndexError:  48 [0..48)
> me/Guenther.T/src/gimli/gimli36/src/vector.h: 561		const ValueType& GIMLI::Vector<ValueType>::getVal(GIMLI::Index) const [with ValueType = double; GIMLI::Index = long long unsigned int] 

My script is below:

> #%% ERT data importing
> infile = 'DD_WS.dat'
> data_ert = pb.importData(infile, format='Res2dInv', verbose=True)
> ert = pb.ERTManager(data_ert)
> error_ert = ert.estimateError(data_ert, relativeError=0.013018) 
> data_ert.set('err',error_ert)
>         
> #%% SRT data importing
> data_srt = pg.DataContainer('Seism.txt')
> srt = Refraction(data_srt)
> srt.dataContainer.sortSensorsX()
> error_srt = srt.estimateError(data_srt, absoluteError=0.001, relativeError=0.001)
> data_srt.set('err', error_srt)
> 
> #%% Creating extra mesh
> pMesh = pg.meshtools.createParaMesh(data_ert,  area=0, paraDepth=60, boundary=0)           
> 
> #%% Invert ERT
> ERT = pb.ERTManager()
> resInv = ERT.invert(data_ert, mesh=pMesh)
> ERT.inv.echoStatus()
> 
> #%% Invert SRT
> SRT = Refraction()
> velInv = SRT.invert(data_srt, mesh=pMesh)
> SRT.inv.echoStatus()
> 
> #%% Trans functions
> Trans_ert = ArchieTrans(rFluid=20, phi=0.3)    #inversion porosity
> res = Trans_ert.fwd(10)                                     #did not use it
> 
> Trans_srt = WyllieTrans(vm=4000, phi=0.3)    #inversion slowness
> vel = 1.0/Trans_srt.fwd(10)                               #did not use it
> 
> #%% ERT PetroInversion
> invERTPetro = PetroInversion(ERT, Trans_ert)
> satERT = invERTPetro.invert(data_ert, mesh=pMesh, limits=[0, 1])
> invERTPetro.inv.echoStatus()
> 
> #%% SRT PetroInversion
> invSRTPetro = PetroInversion(SRT, Trans_srt)
> satSRT = invSRTPetro.invert(data_srt, mesh=pMesh, limits=[0, 1])
> invSRTPetro.inv.echoStatus()
> 
> #%%Joint Petro Inversion
> jointPetro = JointPetroInversion([ERT, SRT],[Trans_ert, Trans_srt])
> satJoint = jointPetro.invert([data_ert, data_srt], mesh=pMesh, limits=[0, 1])
> 
> # Show results
> ERT.showData(data_ert)
> SRT.showVA(data_srt)

I dont understand it is relating to import data or I am using wrong code to plot the joint inversion. When I check the last result to see there is information or not by writing 'print(satJoint) it contains info like this: 

> 1109 [0.7619877092849172,...,0.410760417003571]

I would be really appreciated If you respond as fast as you can. Thank you. 
Sorry for my English.

**Comment by halbmy** [comment]
Just a few quick answers:

> How I put TT inversion in the middle of pMesh?

It is not quite clear what you mean by this question. You are using the same mesh and consequently you have only a limited coverage but you have no choice if you want to go for (any kind of) joint inversion. 

> I dont have information about rFluid, phi and velocity. So, I would be planning to use different parameters instead of these parameters. In other words, I replace WyllieTrans and ArchieTrans to new parameters. After this replace, would JointPetroInversion work?

rFluid and phi are petrophysical parameters, but what do you mean with velocity? The velocity of air, water and rock? The first two are clear, the last one you usually get when penetrating into the undisturbed rock.

The codes are not interested in whether the petrophysics is correct or not. However, you will notice that you will not be able to fit both data to the same degree. Actually very interesting to see that. It might be helpful to do that with synthetic models first.

About "showing results of joint inversion", `showData` will not do that. Generally, we cannot reproduce your results without having the data files. Please have a look at https://www.pygimli.org/paper/cg17/ where the function `showModel` is used to plot the results.

**Comment by BoDoNgAhAi** [comment]
Hello, first of all, thanks for your previous comment.  I fixed my issues. 
But, another problem arose at the inversion of refraction. As I mentioned in the previous question, I made extra mesh for 2 methods (ERT and SRT), which is based on ERT geometry and this mesh length is longer than SRT. So, I shifted the first sensor distance of SRT to at 25m.  Then I got this result.
![Figure_1](https://user-images.githubusercontent.com/49978120/57143350-fa2d5700-6dbe-11e9-98a9-19abaa65d463.png)

As u can see, at the 0m, there is an additional ray created automatically and it gives very high velocity.  I want to remove this ray but I do not know how and where the problem is.
I have attached my data in this comment.
[Seism_NMO.txt](https://github.com/gimli-org/gimli/files/3142288/Seism_NMO.txt)
[DD_WS_data_filtered.txt](https://github.com/gimli-org/gimli/files/3142295/DD_WS_data_filtered.txt)
[ERT_Topo.txt](https://github.com/gimli-org/gimli/files/3142300/ERT_Topo.txt)

**Comment by halbmy** [comment]
As you did not provide a script, I created my own just to test whether SRT inversion with your data is running with the ERT mesh:
```
import pygimli as pg
from pygimli.physics import Refraction
ra = Refraction('Seism_NMO.txt')
ra.invert()
ra.showResult(rays=True)  # this works well

# %% load ert data
import pybert as pb
from pybert.importer import importRes2dInv
data = importRes2dInv('DD_WS_data_filtered.txt')
pb.show(data)
# %% read in topo and interpolate elevations
import numpy as np
x, z = np.loadtxt('ERT_Topo.txt', unpack=True, delimiter=',')
ex = pg.x(data)
ez = np.interp(ex, x, z)
for i in range(data.sensorCount()):
    data.setSensorPosition(i, [ex[i], ez[i]])
# %% do ERT inversion
ert = pb.Resistivity(data)
ert.invert()  # maxIter=0 to speed things up
# %% use ERT mesh for SRT inversion
pd = ert.paraDomain
for c in pd.cells():
    c.setMarker(1)
ra = Refraction('Seism_NMO.txt')
ra.setMesh(pd)
ra.invert()
ra.showResult(rays=True)
```
![image](https://user-images.githubusercontent.com/7136401/57147662-63659800-6dc8-11e9-8d5f-8bd2800aa04c.png)

So the SRT is running on the inversion mesh of the ERT so that you have the two results on the same mesh (as long as it has the same marker). Next step is the petrophysics, but it is not our job. I recommend starting to use the petrophysics to derive parameters and to see whether it makes sense.

**Comment by BoDoNgAhAi** [comment]
Thank you so much for your reply. 
I have doubt about if I use mesh, you provided above, in JointPetroInversion may it would be an inverse crime. In the paper published in 2017, it says that (avoiding an inverse crime) create a new mesh contains no prior information (no anomalies). So, I followed this information and got the image previous I showed.
Here is a code I used to create the new mesh:
> pMesh = pg.meshtools.createParaMesh(ertData,  area=0, paraDepth=60, boundary=0)  
and inverting:
> ttData = 'Seism_NMO.txt'
> ttManager = Refraction(ttData)
> ttManager.dataContainer.sortSensorsX()
> ttError = ttManager.estimateError(ttData, relativeError=0.008794)
> ttData.set('err', ttError)
> ttManager.invert(ttData, mesh=pMesh)
For doing this, I wanted to know that I am doing it correctly step by step. 
I am sorry for asking many questions.

**Comment by BoDoNgAhAi** [comment]
Hello,
I have found my problem and fixed it. It was in the data. Thank you very much for helping me and I am really appreciated for your work.

**Comment by butchi15** [comment]
Hello
I am new to this python programming and last few months i learned basic programming.
Now i want to execute joint inversion of ERT (48 ele with 3m interval) and SRT (24 geophones with 5m interval) field data with me. For this i have downloaded python 3.7, anaconda 3, spider 4.1.3 etc.
Now i am unable to download relevant joint inversion source code from github.
I have downloaded plot_petro_joint_inv.py from pygimli.org site and opened in spider but i am not able to modify according to my requirement.
kindly suggest the source code suitable to me.

**Comment by halbmy** [comment]
I have no idea which kind of joint inversion are you talking of, but I presume you mean structurally coupled cooperative inversion and not petrophysical inversion? Please have a look at the reference list and the underlying theory. 

We have once created one separat repositorye (or several) for this purpose, but it needs to be cleaned up to meet with pyGIMLi 1.1 standards. Furthermore, we want to provide an SCCI inversion framework in the examples.

**Comment by florian-wagner** [comment]
Side note: A special case of petrophysical joint inversion (water, ice, air, porosity) is available here: https://github.com/florian-wagner/four-phase-inversion/tree/pg1.1 
The `pg.1.1` branch is compatible with pygimli 1.1.0. The theory is documented here: https://doi.org/10.1093/gji/ggz402

**Comment by butchi15** [comment]
> 
> 
> I have no idea which kind of joint inversion are you talking of, but I presume you mean structurally coupled cooperative inversion and not petrophysical inversion? Please have a look at the reference list and the underlying theory.
> 
> We have once created one separat repositorye (or several) for this purpose, but it needs to be cleaned up to meet with pyGIMLi 1.1 standards. Furthermore, we want to provide an SCCI inversion framework in the examples.

Hello halbmy
Yes i need structurally coupled cooperative inversion because i have ERT and SRT field data along the same profile line. I don't have parameters like fluid saturation, phi to do petrophysical inversion.

 **We have once created one separat repositorye (or several) for this purpose, but it needs to be cleaned up to meet with pyGIMLi 1.1 standards. Furthermore, we want to provide an SCCI inversion framework in the examples.**
I am notable to understand what it means, pls give me some more information.

**Please have a look at the reference list and the underlying theory.**----- where it is available.

**Comment by halbmy** [comment]
As for the structurally coupled cooperative inversion (SCCI), we follow a procedure that is described by Hellmann et al. (2017), Ronczka et al. (2017) for 2D ERT and SRT, as well as Skibbe et al. (2018) for 1D VES and MRS. There is also a newer scheme based on cross-gradients (Jordi et al. 2020) but there is still work to do to get this running.

Hellman, K., Ronczka, M., Günther, T., Wennermark, M., Rücker, C. & Dahlin, T. (2017): Structurally coupled inversion of ERT and refraction seismic data combined with cluster-based model integration. Journal of Applied Geophysics 143, 169-181, doi:10.1016/j.jappgeo.2017.06.008.
Ronczka, M., Hellman, K., Günther, T., Wisen, R., Dahlin, T. (2017): Electric resistivity and seismic refraction tomography, a challenging joint underwater survey at Aspö hard rock laboratory. Solid Earth 8, 671-682. doi:10.5194/se-8-671-2017.
Skibbe, N., Günther, T. & Müller-Petke, M. (2018): Structurally coupled cooperative inversion of magnetic resonance with resistivity soundings. Geophysics, 83(6), JM51-JM63, doi:10.1190/geo2018-0046.1.
Jordi, C., Doetsch, J., Günther, T., Schmelzbach, C., Maurer, H. & Robertson, J. (2020):Structural Joint Inversion on Irregular Meshes. Geophys. J. Int., 220(3), 1995-2008, doi:10.1093/gji/ggz550.

See https://www.pygimli.org/publist.html for the list including DOI links.

The software used by Hellmann and Roncuka is located in a gitlab repository under https://gitlab.com/halbmy/DCRefraction but as I've said it is outdated and not compatible to pyGIMLi v1.1 anymore.

**Comment by butchi15** [comment]
> 
> 
> As for the structurally coupled cooperative inversion (SCCI), we follow a procedure that is described by Hellmann et al. (2017), Ronczka et al. (2017) for 2D ERT and SRT, as well as Skibbe et al. (2018) for 1D VES and MRS. There is also a newer scheme based on cross-gradients (Jordi et al. 2020) but there is still work to do to get this running.
> 
> Hellman, K., Ronczka, M., Günther, T., Wennermark, M., Rücker, C. & Dahlin, T. (2017): Structurally coupled inversion of ERT and refraction seismic data combined with cluster-based model integration. Journal of Applied Geophysics 143, 169-181, doi:10.1016/j.jappgeo.2017.06.008.
> Ronczka, M., Hellman, K., Günther, T., Wisen, R., Dahlin, T. (2017): Electric resistivity and seismic refraction tomography, a challenging joint underwater survey at Aspö hard rock laboratory. Solid Earth 8, 671-682. doi:10.5194/se-8-671-2017.
> Skibbe, N., Günther, T. & Müller-Petke, M. (2018): Structurally coupled cooperative inversion of magnetic resonance with resistivity soundings. Geophysics, 83(6), JM51-JM63, doi:10.1190/geo2018-0046.1.
> Jordi, C., Doetsch, J., Günther, T., Schmelzbach, C., Maurer, H. & Robertson, J. (2020):Structural Joint Inversion on Irregular Meshes. Geophys. J. Int., 220(3), 1995-2008, doi:10.1093/gji/ggz550.
> 
> See https://www.pygimli.org/publist.html for the list including DOI links.
> 
> The software used by Hellmann and Roncuka is located in a gitlab repository under https://gitlab.com/halbmy/DCRefraction but as I've said it is outdated and not compatible to pyGIMLi v1.1 anymore.

Thank you halbmy, i will go through this literature and come back to you.
once again thanks for your prompt response.

**Comment by butchi15** [comment]
> 
> 
> > As for the structurally coupled cooperative inversion (SCCI), we follow a procedure that is described by Hellmann et al. (2017), Ronczka et al. (2017) for 2D ERT and SRT, as well as Skibbe et al. (2018) for 1D VES and MRS. There is also a newer scheme based on cross-gradients (Jordi et al. 2020) but there is still work to do to get this running.
> > Hellman, K., Ronczka, M., Günther, T., Wennermark, M., Rücker, C. & Dahlin, T. (2017): Structurally coupled inversion of ERT and refraction seismic data combined with cluster-based model integration. Journal of Applied Geophysics 143, 169-181, doi:10.1016/j.jappgeo.2017.06.008.
> > Ronczka, M., Hellman, K., Günther, T., Wisen, R., Dahlin, T. (2017): Electric resistivity and seismic refraction tomography, a challenging joint underwater survey at Aspö hard rock laboratory. Solid Earth 8, 671-682. doi:10.5194/se-8-671-2017.
> > Skibbe, N., Günther, T. & Müller-Petke, M. (2018): Structurally coupled cooperative inversion of magnetic resonance with resistivity soundings. Geophysics, 83(6), JM51-JM63, doi:10.1190/geo2018-0046.1.
> > Jordi, C., Doetsch, J., Günther, T., Schmelzbach, C., Maurer, H. & Robertson, J. (2020):Structural Joint Inversion on Irregular Meshes. Geophys. J. Int., 220(3), 1995-2008, doi:10.1093/gji/ggz550.
> > See https://www.pygimli.org/publist.html for the list including DOI links.
> > The software used by Hellmann and Roncuka is located in a gitlab repository under https://gitlab.com/halbmy/DCRefraction but as I've said it is outdated and not compatible to pyGIMLi v1.1 anymore.
> 
> Thank you halbmy, i will go through this literature and come back to you.
> once again thanks for your prompt response.

Hi halbmy, I have gone through your suggested literature and Hellman, K., Ronczka, M., Günther, T., Wennermark, M., Rücker, C. & Dahlin, T. (2017) SCCI more suitable to my case. But you said their software is outdated and not compatible to pyGIMLi v1.1. Now how can i proceed further to do SCCI?.
Can you suggest any other similar python program which can be download and execute SCCI for my field data.

**Comment by butchi15** [comment]
> SCCI
Hello
Can you share python program written for SCCI.
It will be grate help for me.
