### ISSUE TITLE
Refraction inversion error

### ISSUE THREAD

**Issue by mariosgeo** [gimli-org/gimli#175]
### Problem description
I am trying to invert the following file. 
The steps I am using are the following
ra = Refraction('prd_01.txt')
ra.createMesh(depth=50., paraMaxCellSize=10, secNodes=1)
ra.showData()
vest = ra.invert()

Pygmli returns the following error

C:/msys64/home/Guenther.T/src/gimli/gimli37/src/meshentities.cpp: 34	 GIMLI::Boundary* GIMLI::findBoundary_(const std::set&) pls. check, this should not happen. There is more then one boundary defined.2
Boundary 0x22b7ecfd770 rtti: 22 id: 0	N: 0 1 marker: 1 
Boundary 0x22b7fa09980 rtti: 22 id: 148	N: 4 0 marker: 𔂫 
terminate called after throwing an instance of 'std::length_error'
what(): C:/msys64/home/Guenther.T/src/gimli/gimli37/src/ttdijkstramodelling.cpp: 99	 void GIMLI::Dijkstra::setStartNode(GIMLI::Index) Warning! Dijkstra graph invalid

[prd_01.txt](https://github.com/gimli-org/gimli/files/3141223/prd_01.txt)

What am I doing wrong?
### Your environment

**Operating system**: e.g. Windows
**Python version**: 3.7?
**pyGIMLi version**: Output of `print(pg.__version__)`
**Way of installation**:Win binary,

**Comment by halbmy** [comment]
Dear Marios,
in your data file you have 74 sensors (upper section) but in the data section you're trying to use number 75 (as the first shot).

**Comment by mariosgeo** [comment]
Fast and precise reply as always. 
Thanks Thomas.
