### ISSUE TITLE
Question about save data 

### ISSUE THREAD

**Issue by BoDoNgAhAi** [gimli-org/gimli#176]
### Problem description

Hello,
I wanted to get only specific region information like cell marker=2 from the inverted mesh that contains 'rho' or 'velocity' information. 
model:
![download](https://user-images.githubusercontent.com/49978120/57451343-49610500-7261-11e9-822c-2b10134b48fd.png)
inversion on model: 
![download (1)](https://user-images.githubusercontent.com/49978120/57451347-4bc35f00-7261-11e9-9b35-a2156a0ab0e8.png)

I tried this script to save the only information in the marker=2 but it saves the whole region's information.

> ert.saveResult(folder='name' , size=(16, 10), marker=2)

Do you have any suggestion for it? 

The idea is to get both information about ERT and SRT from the same region like cell marker 2. Then interpolate the information to plot scatters, and draw a regression line. For doing this, I wanted to change WyllieTrans and ArchieTrans and put my own function from the correlation between resistivity and velocity. 

### Your environment

**Operating system**: Windows
**Python version**:  3.6
**pyGIMLi version**: 0+untagged.2363.g608a9f6
**Way of installation**: e.g. Conda package, Win binary, curl script, manual compilation from source

**Comment by halbmy** [comment]
I see the point that one wants to couple (no matter whether strucurally or petrophysically) only a certain region to another inversion process. The line

```values2 = values[mesh.cellMarkers() == 2])```

extracts the the values with the cell marker 2 for a matching mesh. So one would like to use it as

```res2 = ert.resistivity[ert.paraDomain.cellMarkers() == 2])```

but unfortunately the cell markers in the inversion mesh (paraDomain) are renumbered uniquely in ascending order for each unknown.  We will consider this in the pyGIMLi v1.1.

As a workaround you could use something like
```
inner = pg.Mesh()
inner.createMeshByMarker(ert.mesh, 2)  # markers 2 upwards (everything except 1=background)
res2 = ert.resistivity[inner.cellMarkers() == 2]
```
SaveResult has nothing to do with that (we could actually also save the original cell markers along with the inversion result), so I better rename a issue a bit.

As you did not provide any code, I tested it with the BERT region example in https://gitlab.com/resistivity-net/bert/tree/master/examples/inversion/lake. There's my full code:
```
import pygimli as pg
import pybert as pb


data = pb.DataContainerERT('feldungel.ohm')
data.set('k', pb.geometricFactors(data))
data.set('rhoa', data('u')/data('i')*data('k'))
data.set('err', pg.RVector(data.size(), 0.02))

ert = pb.ERTManager(data)
plc = pg.meshtools.readPLC('mymesh.poly')
ert.createMesh(plc=plc)
ert.invert()
ert.showResult()
# %%
inner = pg.Mesh()
inner.createMeshByMarker(ert.mesh, 2)
print(inner)
res2 = ert.resistivity[inner.cellMarkers() == 2]
res3 = ert.resistivity[inner.cellMarkers() == 3]
print(min(res2), max(res2))
print(min(res3), max(res3))
```
yielding 20-197 Ohmm in region 2 (subsurface) and 3-23 Ohmm in region 3 (lake) matching the result
![image](https://user-images.githubusercontent.com/7136401/57510887-22a9d980-7308-11e9-8995-51a281754b49.png)
