### ISSUE TITLE
how to obtain RMS info in refraction inversion

### ISSUE THREAD

**Issue by edwin1706** [gimli-org/gimli#177]
### Problem description

Hi, I'm doing some refraction seismic modelling with your software, but I cannot find how to obtain rms of my inversions. Is there any function built-in to do so? or do I have to do it on my own after obtaining the theoretical travel times?.

### Your environment

**Operating system**: e.g. Windows, Linux or Mac?
**Python version**: e.g. 2.7,3.5,3.6?
**pyGIMLi version**: Output of `print(pg.__version__)`
**Way of installation**: e.g. Conda package, Win binary, curl script, manual compilation from source

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
import pygimli as pg
...
```

### Expected behavior

Tell us what should happen or what you want to achieve.

### Actual behavior

Tell us what happens instead and/or provide the output of your script.

```
Paste output here.
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by florian-wagner** [comment]
Hi @edwin1706, 

welcome to the pyGIMLi users. The instance of the refraction manager (assuming it is named `rst` here) holds an inversion object (`rst.inv`). From this you can query various terms of the objective function and data fit criteria. We shall list these somewhere in the documentation as a nice table, so I am leaving this open.

``` python
rst.inv.getChi2() # chi-squared error
rst.inv.getPhi() # Phi
rst.inv.getPhiD() # phi_d
rst.inv.getPhiM() # phi_m
rst.inv.relrms() # relative RMS
rst.inv.absrms() # Absolute RMS 
```

**Comment by edwin1706** [comment]
Thanks a lot Florian for your quick response!!!
