### ISSUE TITLE
Mesh generation with dense sensors

### ISSUE THREAD

**Issue by xichaoqiang** [gimli-org/gimli#180]
### Problem description

I have about 200 sensors for ambient noise traveltime tomography.(Fig 1),

And I have some question in mesh generation.

The distance between two sensor sometime is very close,and sometimes not.

How can I generat mesh in which all of sensors located in different cells? And the size cell of mesh varied with sensor distance.(Like Fig 2)

The attachment file is my sensor location.

Figure 1
![image](https://user-images.githubusercontent.com/30900789/57983567-fddf0000-7a85-11e9-82ee-54cc39de6e75.png)

Figure 2
![image](https://user-images.githubusercontent.com/30900789/57983880-14d32180-7a89-11e9-8c9b-7f4c59ced7ed.png)

Location data file
[sensor_locations.txt](https://github.com/gimli-org/gimli/files/3195186/sensor_locations.txt)

**Comment by florian-wagner** [comment]
Hi @xichaoqiang, since ray-tracing in pygimli is node-based, all sensors have to be placed on nodes of the mesh. This could be achieved with the following lines of code:

``` python
import pygimli as pg 
import pygimli.meshtools as mt
import numpy as np

sensors = np.loadtxt("sensor_locations.txt", skiprows=1)

bound = 50

x, y = sensors.T

rectangle = mt.createRectangle([x.min(), y.min()], [x.max(), y.max()])

for sensor in sensors:
    rectangle.createNode(pg.Pos(sensor))
    
mesh = mt.createMesh(rectangle, quality=34)
ax, _ = pg.show(mesh)
ax.plot(x, y, "r.")
```

**Comment by xichaoqiang** [comment]
Thank you.
 I try some simple modes prepare for field work.  

A cross-hole model show as Figure 1. Velocity of it is about 4000m/s 

I save travel time data into ".TOM" file.And I read TOM file with "readTOMfile" function.

The inversion mesh generated by your last reply code(Fig 2)

Is convergence of inversion results OK?The chi^2 is lager than 1.And the velocity is about 1300m/s

My code and TOM file is in the attachment.


'''
solve CGLSCDWWtrans with lambda = 1100
Linesearch tau = 1
3: Model: min = 0.000641388; max = 0.000641389
3: Response: min = 0.002309; max = 0.002309
3: rms/rrms(data, Response) = 0.00128867/80.716%
3: chi^2(data, Response, error, log) = 1.64947
3: Phi = 968.237+6.52599e-13*1100=968.237
Reached data fit criteria (delta phi < 2%). Stop.
chi^2 = 1.65
'''
 
![image](https://user-images.githubusercontent.com/30900789/57995007-724f8880-7af2-11e9-9f67-7477ba6b80a0.png)


[test_model.zip](https://github.com/gimli-org/gimli/files/3196213/test_model.zip)

![image](https://user-images.githubusercontent.com/30900789/57994997-65cb3000-7af2-11e9-8246-5186578a84ce.png)

**Comment by halbmy** [comment]
Actually, one can skip the rectangle by just calling
```
mesh = mt.createMesh(sensors, quality=34)
```
but it seems like `createMesh` ignores the quality argument:
![image](https://user-images.githubusercontent.com/7136401/57999836-1d524900-7ad7-11e9-9e4b-c3eacf497207.png)

One could do it in two steps
```
poly = mt.createMesh(sensors)
mesh = mt.createMesh(poly, quality=34)
```
but here the mesh becomes extremly fine (for whatever reason)
![image](https://user-images.githubusercontent.com/7136401/57999897-52f73200-7ad7-11e9-92f2-c198125c62b8.png)

**Comment by halbmy** [comment]
The data are fitted with an (absolute) RMS of 1.2ms which is close to the default error of 1ms (therefore chi^2 is close to 1), but your traveltimes are very small (between 0.8 and 6ms with a median of 2ms), so, in relative measures, there is no good data fit. You should try estimating your data error. If you add, e.g.,  `invert(...err=0.0001)` the velocities become larger (2100m/s) but still they do not approach the apparent velocities of about 4000-4400m/s. We should keep this as a test case for pg v1.1.

**Comment by xichaoqiang** [comment]
I try a field data.And also find a problem.

I invert the tom file with two commercial software get a similar results with same velocity range.

I can't get similar result with code. Can you try it?

![image](https://user-images.githubusercontent.com/30900789/58006052-b43ff500-7b19-11e9-88c7-d444ac83489f.png)
[field_tom.zip](https://github.com/gimli-org/gimli/files/3196884/field_tom.zip)

![image](https://user-images.githubusercontent.com/30900789/58006496-c9695380-7b1a-11e9-9c5c-1e6ce803b5fc.png)

**Comment by halbmy** [comment]
Probably the same problem about errors and fit. I used the following script:
```
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics.traveltime.importData import readTOMfile
from pygimli.physics.traveltime import Refraction


data = readTOMfile("field_tom.tom")
ex = pg.x(data)
ez = pg.y(data)
geom = mt.createRectangle(start=[min(ex), min(ez)], end=[max(ex), max(ez)])
for sensor in data.sensorPositions():
    geom.createNode(sensor)

mesh = mt.createMesh(geom, quality=33, area=0.25)

ttinv = Refraction(data)
error = ttinv.estimateError(data, absoluteError=0.0002, relativeError=0)
ttinv.setMesh(mesh, secNodes=5)
invmodel = ttinv.invert(lam=3000, vTop=4000, vBottom=4000, err=error)
print("chi^2 = %.2f" % ttinv.inv.getChi2())  # Look at the data fit
print("rrms = {:.2f}ms".format(ttinv.inv.absrms()*1000))  # absolute RMS
# %%
ax, cb = ttinv.showResult()
ax.set_ylim(ax.get_ylim()[::-1])
```
and fitted the data with an RMS value of 0.11ms. Looks quite similar to your results:
![image](https://user-images.githubusercontent.com/7136401/58013787-aa0cff00-7af7-11e9-8e6c-542f18906173.png)

**Comment by xichaoqiang** [comment]
Yes,It works.

 I found that the velocity of cell 182 is 1630 m/s ,but the minimum value of color scale is 1910. It maybe mislead to us.

How can I change the color scale ,if a rainbow type color scale is good to visualize the low velocity area.

Can I export inverted model into file.I need do some further processing with a set of inverted data.

![image](https://user-images.githubusercontent.com/30900789/58016215-a1381f80-7b2f-11e9-943c-c6ce90de6d0c.png)

**Comment by halbmy** [comment]
By default, the limits of the color scale are chosen at 3% and 97% of the values so that outliers will not spoil the whole picture. You can specify the limits as well as the color map by `pg.show()` (`pg.mplviewer.drawMesh`) keyword arguments that are also forwarded by the manager showResult functions, e.g. `ttinv.showResult(cMin=1900, cMax=2300, cMap='rainbow')` leads
![image](https://user-images.githubusercontent.com/7136401/58017859-95cdff80-7b01-11e9-9b01-ba0fa541c060.png)
See matplotlib colormaps: https://matplotlib.org/tutorials/colors/colormaps.html

**Comment by Coastal0** [comment]
Colorcet also has some really nice maps
