### ISSUE TITLE
pg.solver.solveFiniteElements(mesh, a=1.0, b=0...) does not work if b is set as a field

### ISSUE THREAD

**Issue by gockolori** [gimli-org/gimli#181]
### Problem description

pg.solver.solveFiniteElements(mesh, a=1.0, b=0...) does not work if b is set as a field (just like a)

because "if b!=0" does not work any more in python 3.7.3
 

### Your environment

**Operating system**: e.g. Windows, Linux 
**Python version**: 3.7.3
**pyGIMLi version**: Output of `print(pg.__version__)`
**Way of installation**: conda forge

### Expected behavior

I should be able to set a parameter field

### Actual behavior

>   File "<ipython-input-87-e8130278ac17>", line 17, in <module>
>     bc=bc, times=None, userData=None, verbose=True)# **kwargs
>   File "/home/veronika/miniconda3/lib/python3.7/site-packages/pygimli/solver/solver.py", line 1593, in solveFiniteElements
>     if b != 0:
> 
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
>

**Comment by carsten-forty2** [comment]
Thanks for reporting fixed in 8fa49647
