### ISSUE TITLE
Draw a colorbar in Converage Map

### ISSUE THREAD

**Issue by xichaoqiang** [gimli-org/gimli#182]
Hello, Is there any method draw colorbar in coverage map, or get the path number of each cell?

![image](https://user-images.githubusercontent.com/30900789/58033487-271b9100-7b57-11e9-81ea-46775c9517e3.png)

**Comment by halbmy** [comment]
Please take your time and have a look at the documentation
https://www.pygimli.org/pygimliapi/_generated/pygimli.physics.html?highlight=refraction#pygimli.physics.Refraction
You can add any `pg.show` keyword argument to `Refraction.showCoverage`, like `colorBar=True`.
And you can obtain the total ray length (definition of the coverage) by `Refraction.rayCoverage` but not the number of rays.
