### ISSUE TITLE
some unexcepted raypath 

### ISSUE THREAD

**Issue by xichaoqiang** [gimli-org/gimli#183]
Hello I try do some check board test in my sensors geometer.

The sensors geometer shown in Figure 1. 

And I make a velocity model for it,shown as in Figure2.

But after inversion some unexpected raypath exist in Figure3 and Figure 4.

It also shown in other model with different mesh.

The attachment is my code and files used in this example.
[test_checkboard.zip](https://github.com/gimli-org/gimli/files/3202316/test_checkboard.zip)

![image](https://user-images.githubusercontent.com/30900789/58091950-7fa56980-7bfd-11e9-8935-3fce62b01b62.png)

Figure 2
![image](https://user-images.githubusercontent.com/30900789/58091960-859b4a80-7bfd-11e9-9319-182e0804f02c.png)

Figure 3
![image](https://user-images.githubusercontent.com/30900789/58091997-96e45700-7bfd-11e9-8cec-9df0ecf78ec5.png)
Figure 4
![image](https://user-images.githubusercontent.com/30900789/58092192-06f2dd00-7bfe-11e9-8327-acc86d1de4a1.png)
![image](https://user-images.githubusercontent.com/30900789/58092286-4c170f00-7bfe-11e9-97ec-050251cf7672.png)
![image](https://user-images.githubusercontent.com/30900789/58092297-50dbc300-7bfe-11e9-9ba6-3bd8aafdc9d4.png)

**Comment by carsten-forty2** [comment]
Interesting example. 'Unexpected' because some rays are starting in the origin? 
Looks a little an issue with numbering from zero or one.

**Comment by xichaoqiang** [comment]
I  change the model start from (200,200), but the ray path still exist.

![image](https://user-images.githubusercontent.com/30900789/58095964-a0be8800-7c06-11e9-99c2-6562b8f215a6.png)
![image](https://user-images.githubusercontent.com/30900789/58095970-a4520f00-7c06-11e9-9c91-5ba793112cf6.png)
![image](https://user-images.githubusercontent.com/30900789/58095982-a916c300-7c06-11e9-80b3-cbdbefaf73b5.png)

**Comment by carsten-forty2** [comment]
Please try to change the index numbering from zero.

```
...
scheme.add("s", rays[:, 0]-1)
scheme.add("g", rays[:, 1]-1)
...
```

Sensor indices are numbered from zero internal, even when they are displayed in the scheme file from one (bad historical reasons). 

*Not to myself: Check why he does not throw an exception when using a receiver position beyond the sensor list.*

Btw., this is a very nice example .. can we use/adapt this for our example section?

**Comment by xichaoqiang** [comment]
I think you can use it with some adaption. 

Because my example is use for field work.It is not very suit for show.

I'm try the code following your reply.

**Comment by xichaoqiang** [comment]
Yes,it works.Thanks for your reply
