### ISSUE TITLE
Problem inverting TDIP data

### ISSUE THREAD

**Issue by aidamt** [gimli-org/gimli#184]
Previous info: Windows 10, py3.6 through conda, v1.0.10
%%%%
Hi, I have a problem inverting TDIP data. Here's what I do:

- I read in my raw datafile (.bin from syscal) using "importdata". Using "data.tokenlist" I see I only have one data point for ip (not all the ip windows). In this section I clean my data, I calculate an apparent resistivity, I add topography, etc. Then, I save this data as ".ohm", and I make sure I to save the column for "ip".

-Later, I read-in my saved data with TDIP.data('filename.ohm'). However, when I do a "showMa" I get this error:
%%%%%%%%%%%
IndexError                                Traceback (most recent call last)
<ipython-input-14-8746d5fa04d7> in <module>()
      1 data2.showRhoa()
----> 2 data2.showMa(nr=0)

C:\Software\BERT\pybert\tdip\tdipdata.py in showMa(self, nr, **kwargs)
    232         kwargs.setdefault('cMap', 'plasma')
    233         kwargs.setdefault('logScale', True)
--> 234         return pb.show(self.data, self.MA[nr], **kwargs)
    235 
    236     def generatePDF(self, rdict=None, mdict=None, **kwargs):

IndexError: index 0 is out of bounds for axis 0 with size 0
%%%%%%%%%%%%
-When reading in my raw datafile (.bin) I get the same error. 

-Now, we (someone else helped) changed your "tdipdata.py" file for it to stop looking for the multiple ip windows, and now I am able to rune my code and get a "showMa". I am even able to get a result for an inversion (data.invertRhoa and data.invertMa). I do get this message though:
%%%%
22/05/19 - 13:26:53 - pyGIMLi - INFO - fitted M0 not existing, taking first gate
%%%%
In concrete my questions are:

1. Is there a shorter way around this? Meaning, in the section where I clean and process my data is there any function I could use to invert directly Ma?? Is it mandatory to read-in my data through TDIPdata in order to do a TDIP inversion???

2. How does your TDIP inversion work? Is there a paper I could read? In concrete, do you use all of the multiple IP windows in your inversion? or do you only use the one chargeability value (result of the integral, I imagine)?

I just want to check if our tweaking of the code gives a physically correct result. If it matters, my results seem agreeable. 
Attached a copy of my code. 

[IPLINE1.pdf](https://github.com/gimli-org/gimli/files/3207354/IPLINE1.pdf)

Thanks! I apologize for the long question.

**Comment by halbmy** [comment]
`pybert.importData` only reads one IP parameter (mostly integral or mean chargeability) for each quadrupole as the resulting `dataContainerERT` is made for the `ERTManager` doing a resistivity inversion followed by a single IP inversion. If you're happy with this you can use this. The ERTManager is current not doing IP inversion and the once existing ERTIPManager seems outdated.

At any rate, the TDIPdata is what you should use as it
* allows filtering and exporting TDIP data more flexible
* can fit t=0 chargeability from the decays and invert this
* invert spectral chargeability of all time windows individually or simultaneously
* does a correct time-domain IP inversion using the Seigel approach
However you should initialize it with the bin file to keep all data. Loading a standard data file does not make sense. 

Is `tdip = pb.importTDIPdata('draix_NS_WS_96_025.bin')` not working? Of course in the bin file the layout is flat, but you can add the topography (like you did with `data`) with `tdip.data` and then doing resistivity inversion and chargeability inversion. I would need error messages and data file in case of problems.

**Comment by halbmy** [comment]
As to your second question concerning the TDIP inversion: After doing the DC inversion, the IP inversion takes the apparent chargeability as data and inverts for the chargeability using another FEM DC forward model and the Jacobian of the DC problems. There is no theoretical paper (you would have to look at Seigel, 1959), but some more description and applications by Bazin et al. (2018) and Rossi et al. (2018).

References:

Seigel, H. (1959) Mathematical Formulation and Type Curves for Induced Polarization. Geophysics, 24, 547-563. doi:10.1190/1.1438625

Bazin, S., Lysdahl, A.K., Viezzoli, A., Günther, T., Anschütz, H., Scheibz, J., Pfaffhuber, A.A., Radic, T. &
Fjermestad, H. (2018): Resistivity and chargeability survey for tunnel investigation: a case study on toxic black shale in Norway. Near Surface Geophysics 16(1), 1-11, doi:10.3997/1873-0604.2017036.

Rossi, M., Dahlin, T., Olsson, P.-I. & Günther, T. (2018): Data acquisition, processing and filtering for reliable 3D resistivity and time-domain induced polarization tomography in an urban area: field example of Vinsta, Stockholm, Near Surface Geophysics 16(3), 220-229, doi:10.3997/1873-0604.2018014.

**Comment by aidamt** [comment]
Hello,

Thanks for the quick and understandable answer. For the second question, it's good! As for the first question:

The use of "tdip = pb.importTDIPdata('draix_NS_WS_96_025.bin')" is not working for me, using it literally like that. However, if I use "tdip=pb.tdipdata('draix_NS_WS_96_025.bin')" it does import all of my windows now (I re-installed everything to your latest version available). The error I get for importTDIPdata is:
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-6198a536cd6f> in <module>()
      1 #Import data (automatically detects bin files)
----> 2 data=pb.importTDIPdata('draix_NS_WS_96_025.bin')
      3 print(data)
      4 #print(data.tokenList()) #see what's in the data

AttributeError: module 'pybert' has no attribute 'importTDIPdata'
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

New question:
When I used "importdata" I could clean my data using "markInvalid", is here "filter" the equivalent function to clean my data? How do you suggest to get rid of some bad data points of mean chargeability? 

Attached is the "tdipdata.py" file I'm using. Also attached my raw data file ('draix_NS_WS_96_025.bin'). 

Thanks!

**Comment by halbmy** [comment]
There is no file attached, neither the bin file nor a Python script.

**Comment by aidamt** [comment]
I'm sorry. 

[QuestionThomas0519.zip](https://github.com/gimli-org/gimli/files/3246842/QuestionThomas0519.zip)

**Comment by halbmy** [comment]
The Python script that you attached is no script but a copy of the TDIPdata class (no idea why). Anyway, you should make use of this class that internally uses the `importTDIPdata` function:
```
tdip = pb.TDIPdata('draix_NS_WS_96_025.bin')
```
`tdip.generateDataPDF()` just shows a binary image, so there is something wrong in the data. If you save the data by `tdip.data.save('out.dat')` you will see that there are a lot of invalid data (e.g. zero current or voltage), so it is better to get rid of it using the filter method:
```
tdip.filter(rmin=1, rmax=100000)
```
Now, `tdip.generateDataPDF()` provides much better pseudosections, however with large errors. I therefore recommend throwing away data with large errors by `tdip.filter(emax=100)`. Now `tdip.generateDataPDF()`generates a nicer images:
![image](https://user-images.githubusercontent.com/7136401/58799517-cb94dd00-8605-11e9-962c-7158e19a5b54.png)
![image](https://user-images.githubusercontent.com/7136401/58799546-dc455300-8605-11e9-9749-d226298ded07.png)
![image](https://user-images.githubusercontent.com/7136401/58799559-e6675180-8605-11e9-970a-ae44ccbee76b.png)

From here you can go into DC inversion (`tdip.invertRhoa()`), IP inversion (`tdip.invertMa(nr=2)`) and so on.

Gate 1 is a bit too high (also to be seen by `tdip.generateDecayPDF()`. I recommend using multiples of 20ms or 60ms as gate lengths to avoid effects from 50Hz powerline or 16.7Hz train.

**Comment by halbmy** [comment]
By the way, there was a problem reading in the gate and delay times from Syscal bin files. After fixing it shows correct decays
![image](https://user-images.githubusercontent.com/7136401/58861622-0ef75600-86af-11e9-9e08-b30c705b434a.png)
Note that the first gate (maybe also the second) is affected by the hardware lowpass filter (10Hz cutoff), so that you will not be able to use gates much before 100ms.

I am closing this issue as all seems solved and it is outside pyGIMLi anyway. If there are further problems, please open a new issue in the BERT repository on https://gitlab.com/resistivity-net/bert
