### ISSUE TITLE
Issues installing on MacOS

### ISSUE THREAD

**Issue by eclyne** [gimli-org/gimli#185]
### Problem description

Issue installing on MacOS

### Your environment

MacOS High Sierra 10.13.6
Python version 3.6.0 (but we've also tried with 3.7.3)

### Steps to reproduce

I followed the steps on the install page, however we seem to be having issues with installing boost. 

# Install python3
brew install python3
brew install boost --with-python3
brew install boost-python --with-python3

The --with-python3 flag is no longer necessary (nor functional), it seems, and installing boost and boost-python should work using "brew install boost-python" instead.

So we did this, and moving forward we get error messages during the cmake stage regarding boost:

input: 

cmake ../gimli -DPYTHON_EXECUTABLE=“/usr/local/bin/python3” -DPY_NUMPY=“/usr/local/lib/python3.7/site-packages/numpy” -DPYTHON_INCLUDE_DIR=“/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m” -DPYTHON_LIBRARY=“/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7.dylib”

result:

-- Could NOT find Boost
--  ... not found.
CMake Error at CMakeLists.txt:332 (find_boost_python_manual):
  find_boost_python_manual Function invoked with incorrect arguments for
  function named: find_boost_python_manual

--  ... searching for libboost_python-.
CMake Warning at /usr/local/Cellar/cmake/3.14.4/share/cmake/Modules/FindBoost.cmake:1822 (message):
  No header defined for python-.; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:292 (find_package)
  CMakeLists.txt:337 (find_boost_python_manual)

-- Could NOT find Boost
--  ... not found.
CMake Error at CMakeLists.txt:342 (find_boost_python_manual):
  find_boost_python_manual Function invoked with incorrect arguments for
  function named: find_boost_python_manual

-- Sorry but no boost-python found. Please search for any libboost_python* on your system and provide it to the authors so we can try to fix this here.
-- clang++ found : /usr/bin/clang
-- Found castxml executable: 
-- castxml is local True
-- castxml found
-- Found pygccxml path: /Users/erc25/src/gimli/thirdParty/dist-Clang-10.0.0.10001145-64
-- pygccxml is local True
-- pygccxml found
-- Found pyplusplus path: /Users/erc25/src/gimli/thirdParty/dist-Clang-10.0.0.10001145-64
-- pyplusplus is local True
-- pyplusplus found
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
________________________________________________________________________________________________

So we tried searching for libboost_python and found these:

/opt/passcal/other/lib/libboost_python-mt.dylib 
/opt/passcal/other/lib/libboost_python-mt.a 

We can get to a step where it says:

pygimli can be build. run: make pygimli

we try this, and the make process fails.

We've tried this on two different Macs and encounter more or less the same issues.

**Comment by carsten-forty2** [comment]
> we try this, and the make process fails.

can you please a bit more specific with some error messages or build logs.

**Comment by eclyne** [comment]
On the current mac, I do not even have

from the build folder we try running:

make -j 8
make: *** No targets specified and no makefile found.  Stop.
make pygimli
make: *** No rule to make target `pygimli'.  Stop.


the cmake step appears to not be creating a makefile?  We've been trouble shooting a lot today.  Sometimes we've gotten the make-j 8 step to work, others the make pygimli starts, but it ends up in some critical failure.  I do not have a log of those instances currently.

More from the output of the cmake step:

-- **********************************************************************
-- *************** Optional Dependencies found **************************
-- **********************************************************************
-- CPPUNIT            :    
-- Doxygen            :NO    
-- Sphinx             :TRUE    
-- **********************************************************************
-- 
-- pygimli can be build. run: make pygimli
-- **********************************************************************
-- 
-- 
-- Configuring incomplete, errors occurred!
See also "/Users/erc25/src/gimli/build/CMakeFiles/CMakeOutput.log".
See also "/Users/erc25/src/gimli/build/CMakeFiles/CMakeError.log".


From the CMakeErrorlog:

Determining if the function sgemm_ exists failed with the following output:
Change Dir: /Users/erc25/src/gimli/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_51100/fast 
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_51100.dir/build.make CMakeFiles/cmTC_51100.dir/build
Building C object CMakeFiles/cmTC_51100.dir/CheckFunctionExists.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=sgemm_   -o CMakeFiles/cmTC_51100.dir/CheckFunctionExists.c.o   -c /usr/local/Cellar/cmake/3.14.4/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_51100
/usr/local/Cellar/cmake/3.14.4/bin/cmake -E cmake_link_script CMakeFiles/cmTC_51100.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=sgemm_ -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_51100.dir/CheckFunctionExists.c.o  -o cmTC_51100 
Undefined symbols for architecture x86_64:
  "_sgemm_", referenced from:
      _main in CheckFunctionExists.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cmTC_51100] Error 1
make: *** [cmTC_51100/fast] Error 2

**Comment by carsten-forty2** [comment]
The output is weird, no plan which part asks for sgemm. 

I guess its a tool chain specific mac problem. 

Unfortunately we don't have any mac around to play and test.

**Comment by carsten-forty2** [comment]
closed due to inactivity. We can't fix it without more input or a mac at hand. Please open a new if there are new logs or additional infos that might help.
