### ISSUE TITLE
Question about timelapse seismic inversion

### ISSUE THREAD

**Issue by soetpotet** [gimli-org/gimli#186]
Hi!

I'm trying to do a timelapse seismic refraction inversion using pygimli but I'm not sure how to code it.

I got a timelapse ERT inversion code from a colleague that looks like this (see NSLine.py attachment) and then I have the seismic refraction code for my background acquisition (Det_Inv_NSBG.py).

I'm trying to translate the timelapse loop from the ERT code to make a loop for the seismic case but I'm stuck, so the loop looks like this:

```
 # Time-lapse 
for di in range(2, 12):
    data1 = pb.DataContainerERT( 'TL-data/ERT_NS_4bert_step%d.data' % di )
    INV2 = pg.RInversion( data('rhoa'), f, tData, tModel, True)
    m1_ref = f.createStartVector()
    for i in range(0,RM.region(2).endParameter()):
        m1_ref.setVal(model.getVal(i), i)
        
    INV2.setModel( m1_ref ) # set starting model to result of baseline inversion
    INV2.setReferenceModel( m1_ref ) # set reference model to result of baseline inversion
    INV2.setData( INV.response()/( data('rhoa') ) * data1('rhoa')) # apply ratio (difference) correction
    INV2.setRelativeError( data1('err') )
   
    INV2.blockyModel()
    INV2.setLambda(20000)
    INV2.setLambdaFactor(0.8)
   
   # RM.region(2).setConstraintType(10)
   # RM.region(2).setModelControl(5.)

    model1 = INV2.run()
    
    rat1 = (model1/( model ) - 1.0) * 100.0

    pd = f.regionManager().paraDomain() # extract inner mesh
    pd.addExportData('Resistivity/Ohmm',model1)
    pd.addExportData('Relativewchangeswppp',rat1)
    pd.exportVTK('models/res_%d' % di)
```

And what's mainly blocking me is the reference model definition and the also inside loop:

```
m1_ref = f.createStartVector()
for i in range(0,RM.region(2).endParameter()):
    m1_ref.setVal(model.getVal(i), i)
```

So _m1_ref_ is defined using the function _f_, and _f_ is defined as `f = pb.DCSRMultiElectrodeModelling( mesh, data )` using an ER/pybert operator so that wouldn't work for the seismic case.

I also don't really understand what that inside loop is doing, and what makes the variables `model` (outside the timelapse loop) and `m1_ref` different. 

If you have any suggestions on how to properly code the timelapse seismic inversion I would really appreciate it, thank you!

[NSLine.txt](https://github.com/gimli-org/gimli/files/3284856/NSLine.txt)

[Det_Inv_NSBG.txt](https://github.com/gimli-org/gimli/files/3284860/Det_Inv_NSBG.txt)

**Comment by florian-wagner** [comment]
Hi @soetpotet,

the inversion in pyGIMLi is physics-independent, so the approach is definitely applicable to the seismic problem as the `pg.RInversion` object is the same, just with a different forward operator. The ERT example you got there is a bit more involved as it deals with different regions and performs a ratio inversion, but you don't have to worry about that. You could start by using different starting and reference models (e.g., from the previous timestep).

You can extract both objects from the Refraction manager as a starting point. 

``` python
import pygimli as pg
from pygimli.physics import Refraction
filename = pg.getExampleFile("traveltime/koenigsee.sgt") # just some example data set
ra = Refraction(filename)

inv = ra.inv # Inversion object
type(inv)

fop = inv.fop() # Forward operator
type(fop)
```

When you have the inversion object, you set various things:

``` python
inv.setModel # Set model to start from
inv.setReferenceModel # Set a reference model, could be the same as above
inv.setData # Set a data vector (traveltimes from different timestep)
model = inv.run() # run the inversion
```

You can put that into a loop and adapt it to your problem. Depending on the data set it could also be exciting to go for full-time lapse inversion (i.e. estimate all timesteps simultaneously and regularize along the time-axis), but this is more involved.

Best wishes
Florian

PS: If you do not want to share you're data here, you could also contact me via email if you run into problems while trying the suggestions above.

**Comment by soetpotet** [comment]
Hi Florian,

Thanks a lot for your quick answer!

I tried to start from scratch and make it simpler following your suggestions and my code looks like this:

```
import numpy as np
import pygimli as pg
from pygimli.physics import Refraction

data   = pg.DataContainer('traveltime/file4pygimli1_xcorr_NS.txt')
mesh   = pg.Mesh('meshParaDomain.bms')
pos    = np.array(data.sensorPositions())
times  = np.array(data('t'))
m      = mesh.cellCount()
print(m, 'cells within the mesh')

ra     = Refraction(data)

inv = ra.inv
type(inv)

fop = inv.fop()
type(fop)

a = 20
b = 10

vel_gradient = []
for node in mesh.nodes():
    vel_gradient.append( a + (b * (abs(node.y()) ** 3)) )
vel_gradient = pg.meshtools.nodeDataToCellData(mesh,np.array(vel_gradient))
pg.show(mesh, vel_gradient, label="Velocity (m/s)")

inv.setModel(vel_gradient) # Set model to start from
inv.setReferenceModel(vel_gradient) # Set a reference model, could be the same as above
inv.setData(times) # Set a data vector (traveltimes from different timestep)
model = inv.run() # run the inversion
```

No timelapse here yet, just wanted to test it with the data from the background acquisition. When I run it I get the following error:

>     model = inv.run() # run the inversion
> 
> RuntimeError: ModellingBase has no mesh for ModellingBase::createMappedModel

From my code you can also see that I'm creating the starting model, but how could I extract the starting model that pygimli automatically defines? For example, in the first code I attached this morning (Det_Inv_NSBG.txt) I use `inv = ra.invert(data=data,err=error, useGradient=True, vtop=20,vbottom=1000,lam=200, zWeight=1, verbose=True)` how could I then extract the starting model from there? If that makes sense.

For the timelapse, I would eventually like to perform a ratio inversion too, but yes, I agree it's better to start with something simple and make it work from there.

I'm attaching you the mesh I'm using, the background acquisition, and then two more at other times, in case that helps. 

I'm really sorry for the questions, I feel they're silly and mostly related to my unfamiliarity with the process and syntax/commands to use.

Thanks again for your time and help!

[TLseismic.zip](https://github.com/gimli-org/gimli/files/3286945/TLseismic.zip)

**Comment by florian-wagner** [comment]
Hi @soetpotet,

it's good to start with such a minimal example. It's almost correct and just needs two more things:

1. Add one `ra.setMesh(mesh)` after initializing the `Refraction` object. This will set mesh properly and get rid of the current error message.
2. Remember that the actual inversion parameters are slownesses (although the show functions display velocity by convention). So it should read:
``` python
inv.setModel(1 / vel_gradient) # Set model to start from
inv.setReferenceModel(1 / vel_gradient) # Set a reference model, could be the same as above
```

Hope that helps.

Best wishes
Florian

**Comment by soetpotet** [comment]
Hi @florian-wagner,

Thanks for your reply, that did work. So now I'm doing the following:

```
import numpy as np
import pygimli as pg
from pygimli.physics import Refraction
import matplotlib

data   = pg.DataContainer('traveltime/file4pygimli1_xcorr.txt')
mesh   = pg.Mesh('meshParaDomain.bms')
pos    = np.array(data.sensorPositions())
times  = np.array(data('t'))
m      = mesh.cellCount()
print(m, 'cells within the mesh')

ra     = Refraction(data)
ra.setMesh(mesh)

inv = ra.inv
type(inv)

fop = inv.fop()
type(fop)

a = 100
b = 50

vel_gradient = []
for node in mesh.nodes():
    vel_gradient.append( a + (b * (abs(node.y()) ** 3)) )
vel_gradient = pg.meshtools.nodeDataToCellData(mesh,np.array(vel_gradient))
pg.show(mesh, vel_gradient, label="Velocity (m/s)", cMin=20, cMax=1000, logScale=False) 
```
![Vel_grad_model](https://user-images.githubusercontent.com/47670044/59669626-dbdab980-91ba-11e9-8850-b60ef5ee4269.png)
```
inv.setModel(1/vel_gradient) # Set model to start from
inv.setReferenceModel(1/vel_gradient) # Set a reference model, could be the same as above
inv.setData(times) # Set a data vector (traveltimes from different timestep)
inv.setLambda(200)
inv.setRelativeError(0.001)
model = inv.run() # run the inversion

matplotlib.colors.Normalize()
pg.show(mesh,1/model,cMin=20,cMax=1000,colorBar=True,logScale=False,sensor=data.sensorPositions(),label="Velocity (m/s)")
```
![Inv_result](https://user-images.githubusercontent.com/47670044/59670379-2446a700-91bc-11e9-9212-eab1606a29da.png)
However, the result is still not satisfactory. I get a better result when I use the first code I attached, that is, doing the following:

```
import numpy as np
import pygimli as pg
from pygimli.physics import Refraction

data   = pg.DataContainer('traveltime/file4pygimli1_xcorr.txt')
mesh   = pg.Mesh('meshParaDomain.bms')
pos    = np.array(data.sensorPositions())
m      = mesh.cellCount()
print(m, 'cells within the mesh')

ra     = Refraction()
ra.setDataContainer(data)
error  = ra.estimateError(data=data,absoluteError=0.001)
ra.setMesh(mesh, refine=False)
inv = ra.invert(data=data,err=error, useGradient=True, vtop=20,vbottom=1000,lam=200, zWeight=1, verbose=True)

ra.showResult(cMin=20,cMax=1000) 
```
![Inv_result_b](https://user-images.githubusercontent.com/47670044/59670612-7f789980-91bc-11e9-8149-17410b363e49.png)
`ra.saveResult(folder='Results_detInv_NSBG',cMin=20,cMax=1000)`
![Inv_result_b_saved](https://user-images.githubusercontent.com/47670044/59670772-c23a7180-91bc-11e9-91d5-95f0b23b472e.png)

I guess this is related to my starting model given that in the first case I define it myself and in the second case I'm doing `ra.invert(data=data,err=error, useGradient=True, vtop=20,vbottom=1000,lam=200, zWeight=1, verbose=True)`.

As you can see, in the first case I set my error and my lambda (I don't set the zWeight because I'm using 1 and I understand this is the default), but I'm not sure how to write the `useGradient=True, vtop=20,vbottom=1000` in the first case syntax.

Another thing I don't really understand is what is the difference between the showed results using `ra.showResult(cMin=20,cMax=1000)` and `ra.saveResult(folder='Results_detInv_NSBG',cMin=20,cMax=1000)` I would prefer to have the result plotted by `ra.showResult(cMin=20,cMax=1000)` (not having all the cells filled) but instead what it is stored is the result that I see after `ra.saveResult(folder='Results_detInv_NSBG',cMin=20,cMax=1000)`

Thanks again!

**Comment by florian-wagner** [comment]
- Note that you use a relative error in the first example and an absolute error of 1 ms for the second example. This is a huge difference. Absolute errors should generally be used for traveltime inversions.
- You can create, modify and save a figure to your liking:
``` python
fig, ax = plt.subplots()
rst.showResult(ax=ax, cMin=20, cMax=1000)
ax.set_title("my result")
fig.savefig("my_result.png", dpi=300)
```
- Other than that I can't identify any questions, so I am closing this issue.

**Comment by soetpotet** [comment]
Hi @florian-wagner,

Thanks for pointing out the error issue.

More than saving the figure I was wondering why one command is filling only some mesh cells while the other fills all the cells. Then, when I call `ra.saveResult(folder='Results_detInv_NSBG',cMin=20,cMax=1000)` the following files are created:

velocity.vector
velocity.vtk
velocity-cov.vector
velocity-mesh.bms
velocity-pd.bms
velocity-scov.vector

When I tried plotting the .vtk and .bms files, they would all give me a plot that looks like the last figure in my last comment (all the cells filled), so I was wondering if it's possible to get a file that would correspond to the data that is being plotted in the second last figure (not all the cells filled).

Thanks!

**Comment by florian-wagner** [comment]
Cells that are not traversed by any ray have a standardized coverage of zero, others of one. The coverage is saved as well and you can use it for plotting.

``` python
cov = pg.load("velocity-scov.vector")
mesh = pg.load("velocity-mesh.bms")
vel = pg.load("velocity.vector")
pg.show(mesh, vel, coverage=cov)
vel_with_coverage = vel[cov > 0]
```

**Comment by soetpotet** [comment]
Thanks a lot!

**Comment by soetpotet** [comment]
Hi again @florian-wagner,

I've been playing a bit with the script and some new questions popped up.

My input mesh for the seismic inversion is the inner mesh (parameter domain, meshParaDomain.bms) of a mesh I previously generated for the ert inversion (which had only two regions: background and parameter domain). 

While running the seismic inversion and checking the log I realized the code was counting every cell of the mesh as a different region:

> 2007 cells within the mesh
> Data: Sensors: 86 data: 1008
> Reset region parameter
> RegionManager copying mesh ...0.012 s
> create NeighbourInfos ... 0.001 s
> **analysing mesh ... 2007 regions.**
> **Info: More than 50 regions so we assume singles only regions.**
> Info: applying *:* interregion constraints.
> Recounted parameter: 2007
> creating para domain ... 0.011 s
> ModellingBase::setMesh() switch to regionmanager mesh
> ... looking for shot and receiver positions.
> FOP updating mesh dependencies ... 0.164 s
> ModellingBase::setMesh() copying new mesh ... ... looking for shot and receiver positions.
> *** no cells found C:/msys64/home/Guenther.T/src/gimli/gimli36/src/ttdijkstramodelling.cpp: 320
> *** no cells found C:/msys64/home/Guenther.T/src/gimli/gimli36/src/ttdijkstramodelling.cpp: 320
> *** no cells found C:/msys64/home/Guenther.T/src/gimli/gimli36/src/ttdijkstramodelling.cpp: 320
> *** no cells found C:/msys64/home/Guenther.T/src/gimli/gimli36/src/ttdijkstramodelling.cpp: 320
> *** no cells found C:/msys64/home/Guenther.T/src/gimli/gimli36/src/ttdijkstramodelling.cpp: 320
> *** no cells found C:/msys64/home/Guenther.T/src/gimli/gimli36/src/ttdijkstramodelling.cpp: 320
> *** no cells found C:/msys64/home/Guenther.T/src/gimli/gimli36/src/ttdijkstramodelling.cpp: 320
> *** no cells found C:/msys64/home/Guenther.T/src/gimli/gimli36/src/ttdijkstramodelling.cpp: 320
> *** no cells found C:/msys64/home/Guenther.T/src/gimli/gimli36/src/ttdijkstramodelling.cpp: 320
> *** no cells found C:/msys64/home/Guenther.T/src/gimli/gimli36/src/ttdijkstramodelling.cpp: 320
> *** no cells found C:/msys64/home/Guenther.T/src/gimli/gimli36/src/ttdijkstramodelling.cpp: 320
> *** no cells found C:/msys64/home/Guenther.T/src/gimli/gimli36/src/ttdijkstramodelling.cpp: 320
> 0.02 s
> FOP updating mesh dependencies ... 0 s
> min/max(dweight) = 1000/1000
> min/max(dweight) = 1000/1000
> Building constraints matrix
> apply inter region constraints
> constraint matrix of size(nBounds x nModel) 2879 x 2007
> apply inter region constraints weights
> calculating jacobian matrix ...J(4/4-std::mt) 0.038
> /0.237/0.02 ... 0.295 s
> min data = 9.9953e-005 max data = 0.0477999 (1008)
> min error = 0.0209205 max error = 10.0047 (1008)
> min response = 0.000892585 max response = 0.0574858 (1008)
> min reference model = 0.00104768 max reference model = 0.0099944 (2007)

So I was wondering if this could pose a problem.

Secondly, I would like to try different constraints when doing the timelapse and I'm not sure how to code this. For the ert case, I set different constraints using `RM.region(2).setConstraintType(10)` inside the timelapse loop, but in this case the region manager is previously defined as `RM = f.regionManager()` and f as `f = pb.DCSRMultiElectrodeModelling( mesh, data )`, with `mesh` being the 2-region mesh I generate using BERT. In my current seismic code I'm calling the forward operator as `fop = inv.fop()` (like you suggested), and I can define the region manager as `RM = fop.regionManager()` but then I have 2007 regions (following what I said above, the number of cells), so I'm not sure how to set the constraint type. I guess I could write a loop and set the constraint type to the value I want to test to all the 2007 "regions" but 1. I don't know if this would be correct, and 2. I guess there's a smarter way to overcome this.

Thanks again!
