### ISSUE TITLE
3D Tomography and simulation

### ISSUE THREAD

**Issue by hanafusman** [gimli-org/gimli#187]
### Problem description

Hi, I am working on a project using your package and we want to use the createMesh3D function, which we found documentation on the website. However, when we tried to run the function in the code, we got an error that the method does not exist. 

What we want to do is an extrude  a 2d tomography result into a 3d grid and perform simulations in 3d. 

Is there another way we can perform the simulations in 3d? 

Thank you so much!!

**Comment by florian-wagner** [comment]
Hi @hanafusman,

an example on the usage of `createMesh3D` can be found here: http://www2.geo.uni-bonn.de/~wagner/pg/_examples_auto/1_meshing/plot_extrude_2D_to_3D.html Note that `pg.show(mesh3d)` will only work upon the next release, but you can use the VTK export (`mesh.exportVTK`) and check the result with ParaView.

**Comment by carsten-forty2** [comment]
A little bit more information (a simplified script or the error itself) would be useful.

A fast check for the functions works for me:
```
import pygimli as pg

grid2d = pg.createGrid(3,3)
print(grid2d)

grid3d = pg.createMesh3D(grid2d, z=[0, 1, 2])
print(grid3d)
```

To run a 3D simulation from a 2D tomography result might need a little bit more work. 
After you created the 3D mesh with extrusion, you also need to map the model values from 2D to 3D using the 2D cell markers. Also, the mesh from the tomography result is usually to coarse and have no boundary to achieve a satisfying accuracy of the following simulation. But this also depends on the method you try to simulate (ERT, TT .. )

**Comment by hanafusman** [comment]
Thank you for your response! How do you do the mapping with the 2d cell
markers?

**Comment by carsten-forty2** [comment]
assuming your `model2d` size fits the 2d mesh cell count you can propagate the cell markers for this.
```
mesh2d.setCellMarkers(range(mesh2d.cellCount()))
mesh3d = pg.createMesh3d(mesh2d, z=[0, 1, 2])
model3d = model2d[mesh3d.cellMarkers()]
```

**Comment by hanafusman** [comment]
def _create_mesh(self, min_x, max_x, min_y, max_y):
   geom = mt.createRectangle(start=[min_x-self.dx, min_y-self.dx],
end=[max_x+self.dx, max_y+self.dx])
   mesh = mt.createMesh(geom, quality=32,
area=(max_x-min_x)*(max_y-min_y)/self.mesh_num_pieces)

   grid3d = pg.createMesh3D(mesh, z=[0, 1, 2])   <-----------

return mesh

When I try to run this method, I get an error that createMesh3D does
not exist. Any help to perform this function would be appreciated.
Thank you!

**Comment by carsten-forty2** [comment]
Please note that we prepare some api change in the fw_cleaning branch for the upcoming version 1.1. 

`pg.createMesh3D` will then be accessible through `pg.core.createMesh3D` or `pg.meshtools.createMesh3D`. We also add some more generic function `pg.meshtools.extrudeMesh`.

If you already on fw_cleaning then you need to change your script this way. 

If this doesn't help, we need a complete minimal script and a complete error message to identify the problem.

**Comment by hanafusman** [comment]
Is it possible to switch the z axis with a y axis (in createmesh3d to extrude on the y axis instead of the z axis)? Thank you for all your help!

**Comment by carsten-forty2** [comment]
not directly .. but you can always rotate all meshes with `mesh.rotate([x, y, z])` https://www.pygimli.org/gimliapi/classGIMLI_1_1Mesh.html#a4778692e22aa7b9c6fb96f9812ea0c97

**Comment by carsten-forty2** [comment]
I think we can close this due to inactivity. Please open a new issue if neeed.

BTW. Nearly all old bert.polyTools (and a few new) for 3D PLC generation are now migrated to fw_cleaning branch.
