### ISSUE TITLE
Problem using fatray

### ISSUE THREAD

**Issue by spasquet** [gimli-org/gimli#188]
Hi,

pygimli crashes when I try using the fatray in the refraction manager example

### Your environment

**Operating system**: Ubuntu 18.04
**Python version**: 3.7
**pyGIMLi version**: 1.0.11+0.g9e41a4a3 (with local changes)
**Way of installation**: Conda package

### Steps to reproduce

I basically just changed cell 7 in the example provided on the pygimli website into:

ra = Refraction(data,fatray=True,frequency=100)

Maybe it is not the correct way to use fatray, but right now I'm getting this error mesage
```
------------------------------------------------------------------------
RuntimeError                           Traceback (most recent call last)
<ipython-input-7-efbe75ce6549> in <module>
      4 # ra.fop.createJacobian(np.ones(ra.fop.regionManager().parameterCount()))
      5 # exit()
----> 6 vest = ra.invert()  # estimated velocity distribution

/opt/miniconda/lib/python3.7/site-packages/pygimli/physics/traveltime/refraction.py in invert(self, data, t, err, mesh, **kwargs)
    440         self.fop.jacobian().clear()
    441 
--> 442         slowness = self.inv.run()
    443         self.velocity = 1. / slowness
    444         self.response = self.inv.response()

/opt/miniconda/lib/python3.7/site-packages/pygimli/physics/traveltime/fatray.py in createJacobian(self, slowness)
     18             self.iMat.rows() != self.mesh().cellCount()):
     19             self.iMat = self.mesh().interpolationMatrix(
---> 20                     self.mesh().cellCenters())
     21         Di = self.dijkstra()
     22         slowPerCell = self.createMappedModel(slowness, 1e16)

RuntimeError: /home/wagner/miniconda3/conda-bld/pygimli_1554208602963/work/gimli/gimli/src/mesh.cpp: 645		GIMLI::Cell* GIMLI::Mesh::findCell(const RVector3&, size_t&, bool) const  no cells for this node. This is a corrupt mesh
```

Hope you can help.
Cheers
Sylvain

**Comment by halbmy** [comment]
Sorry for the late reply and thanks for reporting. It is currently not possible to use the fatray Jacobian along with secondary nodes (that improved the accuracy a lot). If you explicitly specify `ra.invert(secNodes=0)` it will work but I doubt it is work sacrificing accuracy by a slightly more robust Jacobian matrix. 

Currently, there are two variants of the fatray jacobian deviating mainly in how the traveltimes for each cell are computed: the one uses interpolation (which cannot make use of the secondary nodes) and the other finds the nearest node but this leads to a partially filled KDTree (which does also not support secondary nodes). An alternative would be to add the cell midpoints as secondary nodes which slighty slows down performance or to take the mean value of the corner points. We will keep this in mind.
