### ISSUE TITLE
Using multiple CPUs in Refraction.invert

### ISSUE THREAD

**Issue by raytracer123** [gimli-org/gimli#189]
Does there exist no way to preform the forward computation in Refraction.invert parallely (using multiple CPUs at once)? The variable "threadCount" is said in the code to be accepted for backward compatibility. Is that the only reason it exists?

My PC has 44 CPUs and when I set threadCount to be 10 or larger, python (or, after googeling, actually C++) returns the error "the application requested to be terminated in an unusual way". Chainging the value in the range 1-10 seems to not make any difference...

Does there exist any way at all to make use of my 44 CPUs to speed up the inversion (by speeding up the Jacobian/forward computation using FMM/Dijkstra)

Thanks.

### environment

**Operating system**:  Windows
**Python version**: 3.6.3
**pyGIMLi version**: 1.0.11
**Way of installation**: Conda package

**Comment by carsten-forty2** [comment]
Sorry for the late reply .. we rewrote the Dijkstra forward computation in v1.1 (aka fw_cleaning branch). The problem should solved there.
