### ISSUE TITLE
Model regularization and constraints in Refraction.inverse

### ISSUE THREAD

**Issue by raytracer123** [gimli-org/gimli#190]
I looked through the documentation but I couldn't find the place where one can input W_m, i.e., the model regularization/smoothness matrix. Also, I couldn't find where I can input minimal and maximal values for the velocity to be reconstructed. In the paper it said that one can define them. 

(this paper: http://www.sciencedirect.com/science/article/pii/S0098300417300584/pdfft?md5=44253eaacd5490e3fb32210671672496&pid=1-s2.0-S0098300417300584-main.pdf)

How do I input them?

**Comment by halbmy** [comment]
Sorry for the late reply.

The key to control inversion features of the whole parameter mesh or certain parts of it (regions) is the region manager, located in the forward operator 
```python
from pygimli.physics import Refraction
ra = Refraction('mydata.dat')
RM=ra.fop.regionManager()
# do something with RM
ra.invert(lam=200, zWeight=0.2, secNodes=5)  # or other global options
ra.showResult()
```
You can pass some options to RM like `RM.setConstraintType()` (to be 0,1,2 for 0th/1st/2nd order or 10/20 for mixed 1st/2nd with 0th order). You can set a Matrix directly by `ra.fop.setConstraints(mat)` but it must be a pygimli matrix (derived from the Matrix Base). More specifically, you can control the behaviour of individual regions, like the default inversion region `r2 = RM.region(2)`
```python
r2.setLowerBound(0.0002)  # note that it is slowness in s/m
r2.setUpperBound()  # note that it is slowness in s/m
```
In upcoming pygimli versions we will ease the way to pass global parameters like upper/lower bound or others directly in the invert call and also improve documentation of the classes that are up to now in the C++ core (see C++ core API on pygimli.org).
