### ISSUE TITLE
3D viewer feature requests

### ISSUE THREAD

**Issue by frodo4fingers** [gimli-org/gimli#191]
Since there is a light weight base for visualizations in 3D more convenience could be expected. I started it, but nevertheless I am not the only one with wishes... ;-)

please feel free to add:

- [x] plot wireframe on top of surface for better view (like paraview)
- [x] toggle wireframe 
- [ ] cache settings when closing and code is rerun (never repeat yourself.. `pg.show(3dMesh, cache=True)`
- [x] rename 'toggle grid' to 'toggle axes'
- [ ] toggle cell coloring per cell value / interpolated per point value
- [x] view point data
- [ ] toggle view for optional boundary markers 
- [ ] Discrete marker (de)selection maybe via checkbox
- [ ] coverage, i.e. with opacity?
- [ ] slider to look in volume
- [x] Syscall to open PV with the data (just in case the viewer is not sufficient and until all checkboxes ar filled here ;) )

[coming from #15 and #178]

**Comment by banesullivan** [comment]
I can help here... most of those items should be straightforward to implement using PyVista (this may not be apparent, but I can tackle most of those pretty quickly)

Perhaps we could get a branch going in this repo and I could gain push access to that branch so we can collaborate?

**Comment by banesullivan** [comment]
@frodo4fingers: @florian-wagner messaged me saying you had some questions about PyVista. I must have missed it if you reached out. Are you by chance in the SWUNG slack workspace?

**Comment by frodo4fingers** [comment]
hi @banesullivan :-) i  wrote to you on gitter but apparently that didn't reach you. i use slack as well.. you have to send me an invite right? i would like to write you my mail address for that occasion - how could i reach you?

**Comment by florian-wagner** [comment]
Hi @banesullivan, @frodo4fingers added a `fcb_pyvista` branch, to which you have write access. We would very much appreciate your input on the 3D viewing interface. Right now we save the VTK to a temp file, which is not super clean but works. Accessing all the mesh information in the C++ object (wrapped through boost-python) is currently not possible without loops and would require some additional changes. Saving the file does not hurt and we would first like to focus on functionality.

Here is a minimal example:

``` python
import pygimli as pg
import numpy as np
mesh = pg.createGrid(5,5,5)
data = np.random.randn(mesh.cellCount())
pg.show(mesh, data) # Opens a small GUI for interactive inspection of models
pg.show(mesh, data, notebook=True) # Returns a screenshot to work in Jupyter notebooks.
```

Consider joining the Gitter channel https://gitter.im/gimli-org/gimli to discuss details.

Best wishes
Florian

**Comment by banesullivan** [comment]
Thanks for setting up that branch @florian-wagner! I’ve been a bit busy lately but want to get back to this ASAP

I’ll join the gitter and get in touch with you @frodo4fingers

**Comment by halbmy** [comment]
As this issue became rather old we should close it. Most of the features are available but @frodo4fingers won't have the time to invest any more time in it. Thank you for your contribution!
