### ISSUE TITLE
Time to install conda install pygimli while installing this in ubuntu??

### ISSUE THREAD

**Issue by nishantra4** [gimli-org/gimli#192]
### Problem description

Please describe your issue here.

### Your environment

**Operating system**: e.g. Windows, Linux or Mac?
**Python version**: e.g. 2.7,3.5,3.6?
**pyGIMLi version**: Output of `print(pg.__version__)`
**Way of installation**: e.g. Conda package, Win binary, curl script, manual compilation from source

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
import pygimli as pg
...
```

### Expected behavior

Tell us what should happen or what you want to achieve.

### Actual behavior

Tell us what happens instead and/or provide the output of your script.

```
Paste output here.
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by nishantra4** [comment]
/home/nishant/Pictures/Screenshot from 2019-09-04 08-10-42.png

**Comment by nishantra4** [comment]
this pygimli installation is running from last 10 hours.

**Comment by florian-wagner** [comment]
> /home/nishant/Pictures/Screenshot from 2019-09-04 08-10-42.png

We cannot access a screenshot on your local harddrive. Please provide a complete error log and tell us what you are trying to do (which operating system, which Python version, etc.).

**Comment by nishantra4** [comment]
There is no error, i am getting. But the system is installing pygimli from
last 24 hrs by now.
Operating system Ubuntu 18.04.3 LTS
nishant@nishant-OptiPlex-9020:~$ python3
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)
[GCC 7.3.0] :: Anaconda, Inc. on linux

Regards

Nishant

**Comment by florian-wagner** [comment]
I just tried `conda install -c gimli -c conda-forge -y pygimli` on a fresh Ubuntu with conda, which successfully completes within two minutes.

**Comment by nishantra4** [comment]
PFA.
ya very true.  conda install -c gimli -c conda-forge -y pygimli
installation is very fast .

Add the gimli and conda-forge channel (only once):

conda config --add channels gimli --add channels conda-forge
conda update --all

Install pygimli (and its dependencies) and test if everything works
correctly via:

conda install pygimli
python -c "import pygimli; pygimli.test()"

i am installing conda install pygimli. and it is installing still now.

**Comment by carsten-forty2** [comment]
I think this is solved and we can close it.

**Comment by ux751439** [comment]
![pygimli](https://user-images.githubusercontent.com/63800524/80861661-403a2680-8c70-11ea-9ede-54bc9e1255d7.JPG)

print(pg.__version__)
with that code I can't see my pygimli Version
After runing the code I have that issue as showing on my screenshot

**Comment by carsten-forty2** [comment]
Thanks for reporting .. we aware of this and already fixed it for the next binary distribution.
