### ISSUE TITLE
error during cmake on ubuntu 18.04

### ISSUE THREAD

**Issue by kashkoulimohammad** [gimli-org/gimli#193]
Dear all,

I am trying install pyGIMLi on Ubuntu 18.04. In step cmake this error happened.(attached file)
In addition, I have used this script: CC=icc CXX=icc cmake ../gimli -DPYVERSION=3.6

Best regards,
Mohammad
[error.txt](https://github.com/gimli-org/gimli/files/3597351/error.txt)
[CMakeError.log](https://github.com/gimli-org/gimli/files/3597322/CMakeError.log)
[CMakeOutput.log](https://github.com/gimli-org/gimli/files/3597323/CMakeOutput.log)

**Comment by frodo4fingers** [comment]
hi @kashkoulimohammad ,

correct me if i'm wrong but in line 474 of your error.txt it says `-- PYPLUSPLUS_FOUND   :    PYPLUSPLUS_PATH: PYPLUSPLUS_PATH-NOTFOUND`. a few lines below that are some dependencies listed.. did you make sure you have all installed? :crossed_fingers: 

:-)

**Comment by kashkoulimohammad** [comment]
Hi @florian-wagner 
Thank you for replying.
I am not in anaconda and I followed up the Debian Stretch. During cmake I got error for lpthread and because of it I had to use icc.

**Comment by kashkoulimohammad** [comment]
Hi @frodo4fingers 
Thanks for replying.
Yes I installed all of dependencies and you can see between line 461 and 481. Between those lines only pyplusplus seems has not installed although I installed it by pip(pip install pyplusplus)
Regards,

**Comment by carsten-forty2** [comment]
Your are missing pyplusplus and this prevents pygimli to build.

I'm not sure if the pip version 1.8.1 is recent enought so we usually get them ourself in the first cmake run. And here is the problem .. your mercurial client complains:

```
----HG--https://bitbucket.org/ompl/pyplusplus -> /home/mohammad/src/gimli/thirdParty/src/pyplusplus : 666e4d03d462----------------
--------------------------------------------------
~/src/gimli/thirdParty/src ~/src/gimli/thirdParty
abort: error: bad HTTP status line: ''
```

I tested it recently and there is no problem here .. I have no clue what happens there.

Can you check your mercurial version `hg --version`, mine says 4.9

Can you try to get the pyplusplus sources manually into `thirdParty/src`?

```
hg --config ui.clonebundles=false clone https://bitbucket.org/ompl/pyplusplus
cd pyplusplus
hg checkout 666e4d03d462
```

btw. We don't have experiences with icc so there is no guarantee it will compile completely.

**Comment by kashkoulimohammad** [comment]
Hi @carsten-forty2 

Thanks for replying.
The version 4.5.3 is last version of mercurial in Ubuntu  sources.
`sudo aptitude install mercurial
mercurial is already installed at the requested version (4.5.3-1ubuntu2.1)
mercurial is already installed at the requested version (4.5.3-1ubuntu2.1)
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 465 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
`
For using icc I had to because during cmake I had error about lpthread and when I used icc this error solved.
The bitbucket source is not access in my country(I am from Iran) and I can not try manually for pyplusplus.

Regards,

**Comment by carsten-forty2** [comment]
First you need to use python3 as we do not support python version < 3.

Also you can also use the pip version of pygccxml:

`pip install pygccxml==1.9.2 --user`

My last changes were only for the branch `fc_cleaning` which I recommand to work with since it is closer to the new version 1.1 we are currently working on.

**Comment by carsten-forty2** [comment]
btw.: did you tried the prebuild conda package?

**Comment by kashkoulimohammad** [comment]
Hi @carsten-forty2 
I am so sorry for my delay for reply.
I installed Miniconda3 and after that I installed pygimli.
For test I got this warnings:
[error.txt](https://github.com/gimli-org/gimli/files/3703757/error.txt)
and when I tried to run Gravimetry in 2D part 1 I got this error:
`Traceback (most recent call last):
  File "plot_mod-gravimetry-2d.py", line 19, in <module>
    import pygimli as pg
ModuleNotFoundError: No module named 'pygimli'
` 
Thanks for your attention for my problem.

Best Regards,
Mohammad

**Comment by carsten-forty2** [comment]
The error.txt showed all test are passed so pygimli is successful installed. 

No idea why it can't imported in this example. How did you tried to run this example?

**Comment by halbmy** [comment]
Obviously all seemed well after you installed pygimli into the conda environment mypgenv. Did you forget to activate the environment (`conda activate mypgenv`) before running the gravimetry example?

**Comment by kashkoulimohammad** [comment]
Hi @halbmy
No, I did not forget to do it. I tried to reinstall it on new machine but again it had same error.
(mypgenv) mkash@ubuntu:~$ python3.7 -c "import pygimli; pygimli.test(show=False, onlydoctests=True)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pygimli'

**Comment by florian-wagner** [comment]
@kashkoulimohammad You installed pygimli for python3.6, so looking at your log file, it is located here `/home/mohammad/miniconda3/envs/mypgenv/lib/python3.6/site-packages/pygimli/`. But you try to run the scripts with Python 3.7. So either run it with the correct Python version (simply use `python`, which will link to the version of the environment) or, if you want or have to use py 3.7 for some reason, install pygimli explicity for py3.7 by running `conda install -c gimli -c conda-forge pygimli python=3.7`.

Cheers
Florian

**Comment by kashkoulimohammad** [comment]
Hello @florian-wagner
Thank you. My problem solved. 
Best Regards,
Mohammad
