### ISSUE TITLE
 How save results and fiugres at each iteration of tomography?

### ISSUE THREAD

**Issue by xichaoqiang** [gimli-org/gimli#194]
### Problem description

Sometimes I want break the inversion if the result is quite good, and I want compare the figure of results to initial model result? 
Can I save the results and figures at each iteration of tomography(like the  crosshole traveltime tomography example)?

**Comment by carsten-forty2** [comment]
You can initialize the inversion with debug and a the inversion saves a lot of stuff to hd, inclusive  model vectors for each iterations.

The inversion class itself hold all previous models and you can access them with `inv.modelHistory()`

In the upcoming v-1.1 (fw_cleaning branch) we reimplemented the inversion base class and added some pre/post iteration callbacks so you can do whatever you want during the inversion run before and after each iteration.

**Comment by xichaoqiang** [comment]
> You can initialize the inversion with debug and a the inversion saves a lot of stuff to hd, inclusive model vectors for each iterations.
> 
> The inversion class itself hold all previous models and you can access them with `inv.modelHistory()`
> 
> In the upcoming v-1.1 (fw_cleaning branch) we reimplemented the inversion base class and added some pre/post iteration callbacks so you can do whatever you want during the inversion run before and after each iteration.
Thank you.
