### ISSUE TITLE
"fatal error: openblas/cblas.h: No such file or directory" during make on Debian buster

### ISSUE THREAD

**Issue by bouvijea** [gimli-org/gimli#196]
Dear all,

I try to compile gimli-1.0.6 on Debian10 buster BUT I get the following error message during make

Scanning dependencies of target gimli
[  2%] Building CXX object src/CMakeFiles/gimli.dir/bert/bertDataContainer.cpp.o
[  4%] Building CXX object src/CMakeFiles/gimli.dir/bert/bert.cpp.o
[  6%] Building CXX object src/CMakeFiles/gimli.dir/bert/bertJacobian.cpp.o
[  8%] Building CXX object src/CMakeFiles/gimli.dir/bert/datamap.cpp.o
[ 10%] Building CXX object src/CMakeFiles/gimli.dir/bert/bertMisc.cpp.o
[ 12%] Building CXX object src/CMakeFiles/gimli.dir/bert/electrode.cpp.o
[ 14%] Building CXX object src/CMakeFiles/gimli.dir/cholmodWrapper.cpp.o
[ 17%] Building CXX object src/CMakeFiles/gimli.dir/bert/dcfemmodelling.cpp.o
[ 19%] Building CXX object src/CMakeFiles/gimli.dir/curvefitting.cpp.o
[ 21%] Building CXX object src/CMakeFiles/gimli.dir/datacontainer.cpp.o
[ 23%] Building CXX object src/CMakeFiles/gimli.dir/dc1dmodelling.cpp.o
[ 25%] Building CXX object src/CMakeFiles/gimli.dir/elementmatrix.cpp.o
[ 27%] Building CXX object src/CMakeFiles/gimli.dir/em1dmodelling.cpp.o
[ 29%] Building CXX object src/CMakeFiles/gimli.dir/gimli.cpp.o
/tmp/gimli/src/gimli.cpp:35:18: fatal error: openblas/cblas.h: No such file or directory
         #include <openblas/cblas.h>
                  ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/gimli.dir/build.make:232: src/CMakeFiles/gimli.dir/gimli.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:576: src/CMakeFiles/gimli.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Operating system**: Debian10 Buster
**Python version**: 3.7
**pyGIMLi version**: 1.0.6

**Way of installation**: manual compilation from source
$ cmake ../gimli -DCMAKE_INSTALL_PREFIX=/soft/x86_64/gcc_8.3.0/gimli_1.0.6 -DPYVERSION=3.7 -DPYTHON_EXECUTABLE=/usr/bin/python3.7
$ make -j8

Thanks for your help.
Yours,
JNB

**Comment by m-weigand** [comment]
without having tested it, have you installed libopenblas-dev ?
Also, it seems that cblas.h is located here on Debian Buster:
# find /usr -name "cblas.h"
/usr/include/x86_64-linux-gnu/cblas.h

you could try to "fix" it temporarily by creating a symlink there;
mkdir /usr/include/openblas
ln -s /usr/include/x86_64-linux-gnu/cblas.h /usr/include/openblas/cblas.h

Hope this helps, however, I did not test this....

**Comment by carsten-forty2** [comment]
thanks for reporting .. the symlink will work.

I will see if we train cmake to find this header itself.

**Comment by bouvijea** [comment]
Dear m-weigand and carsten-forty,

- Yes libopenblas-dev was already installed on my system
- So, I created the symlink as proposed
# ln -s /usr/include/x86_64-linux-gnu/cblas.h /usr/include/openblas/cblas.h
- the compilation is OK
# make -j8
- but installation fails
# make install
[...]
-- Installing: /soft/x86_64/gcc_8.3.0/gimli_1.0.6/include/gimli/vectortemplates.h
-- Installing: /soft/x86_64/gcc_8.3.0/gimli_1.0.6/include/gimli/wingetopt.h
CMake Error at src/cmake_install.cmake:64 (file):
  file INSTALL cannot find "/tmp/gimli/build/gimli_export.h".
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)
make: *** [Makefile:96: install] Error 1

Thanks again for your help. Yours,
JNB

**Comment by carsten-forty2** [comment]
I have no experiences with the install target and I'm not sure if it supposed to work correctly since there are still some difficulties with installing the python bindings.

I recommend setting paths to the build directory as described in the install description.

**Comment by bouvijea** [comment]
Dear carsten-forty2
OK, done, I "manually" installed the obtained files.
NB : I needed gimli to be able to compile bert !!!
=> libopenblas <- gimli <-bert
*** THANKS AGAIN FOR YOUR HELP ***
JNB
