### ISSUE TITLE
Resistivity image with vertical exaggeration (pg.show)

### ISSUE THREAD

**Issue by kathrins** [gimli-org/gimli#198]
I want to change the ratio of the axes in a resistivity image so that the y-axis has a different scale than the x-axis, for example with factor 2.
I tried
```
import pygimli as pg
pg.show(mes,res,coverage=cov,cMap='jet', colorBar = True, cMin=0,cMax=100,
        logScale=False,
        label='Resistivity [Ωm]',xlabel='Distance [m]',ylabel='Elevation [m]')
ax=pg.plt.gca()
ax.set_aspect(2)
```

But this only changes the ratio of the colorbar. How can I change the ratio of x and y axis?

**Comment by carsten-forty2** [comment]
try:

```
ax, cbar = pg.show(...)
ax.set_aspect(2)
````

**Comment by halbmy** [comment]
Obviously many people are used to overexaggerated images. Actually, show could be using such a keyword `pg.show(mesh, vals, aspect=2)`. I have already started doing that but ran into problems with proper placement of the colorbar. I don't remember, but we should look into that again.

**Comment by florian-wagner** [comment]
@halbmy I agree.
I think in this context (colorbar size etc.), it is worthwhile to check out the new "constrained layouts" introduced in mpl 3. We can leave this open as a reminder.

**Comment by kathrins** [comment]
> 
> try:
> 
> ```
> ax, cbar = pg.show(...)
> ax.set_aspect(2)
> ```
I tried this before but it also changes the ratio between colorbar and the main figure

**Comment by carsten-forty2** [comment]
does a `ax.figure.tight_layout()` help? or/and can you manually resize the resulting figure for a good image/colorbar ratio?

The subsequently change of the axes extends for a figure with a fixed size will allways lead to ugly results. Maybe you can try to create the figure with a suitable size first.

```
fig, ax = pg.plt.subplots(figsize=(x,y))
pg.show(..., ax=ax)
ax.set_aspect(2)
```

**Comment by florian-wagner** [comment]
If you want more fine-grained control, consider defintion of the axes and colorbar axes by hand.

As @carsten-forty2 mentions above, it is a mixture of figure size and aspect ratio. Either you set aspect to "auto" and choose the figure size. Or you choose a given asect ratio and adapt the figure size.

``` python
import pygimli as pg
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable
import numpy as np

# Create some mesh and data just for demo
mesh = pg.createGrid(20,5)
c = mesh.cellCenters()
data = np.sin(pg.x(c)) + pg.y(c)


fig, ax = plt.subplots(1, figsize=(6,4))
im = pg.mplviewer.drawModel(ax, mesh, data)
ax.set_aspect(2)
divider = make_axes_locatable(ax)
cax = divider.append_axes("right", size="5%", pad=0.05)
fig.colorbar(im, cax=cax)
fig.tight_layout()

fig, ax = plt.subplots(1, figsize=(6,4))
im = pg.mplviewer.drawModel(ax, mesh, data)
ax.set_aspect("auto")
divider = make_axes_locatable(ax)
cax = divider.append_axes("right", size="5%", pad=0.05)
fig.colorbar(im, cax=cax)
fig.tight_layout()
```
