### ISSUE TITLE
bin directory empty after make

### ISSUE THREAD

**Issue by bastinc** [gimli-org/gimli#20]
I followed the procedure for vanilla Debian found at [http://www.pygimli.org/installation.html] (http://www.pygimli.org/installation.html)

I run 
``` bash
cmake ../trunk -DCASTER='gccxml'
make 
make pygimli  
```
Config: 
Debian 8 64-bit 
cmake version 3.0.2

The library libgimli.so is created in /build/lib but the /build/bin directory is empty.

**Comment by florian-wagner** [comment]
You probably have to call `make apps` within the build directory to fill the bin folder with a few binary commandline applications. And there are a few apps written in python in `trunk/python/apps`, which are listed here: http://www.pygimli.org/tools.html#sec-tools. Yet the bulk functionality is not available within apps but rather contained in the (py)gimli library.

**Comment by bastinc** [comment]
Indeed it did the trick.
Thanks !
