### ISSUE TITLE
Reading .tom files fails

### ISSUE THREAD

**Issue by GGDRriedel** [gimli-org/gimli#203]
After reading in the data you can create a Refraction manager and do inversion
```
from pygimli.physics import Refraction
data = readTOMfile(filename)
ra = Refraction(data)
```
But before you can do the inversion you should create a mesh (as the automatic mesh generation is made for refraction data) e.g. a regular mesh using `pg.createMesh2D`. Just have a look at the [crosshole example](https://www.pygimli.org/_examples_auto/seismics/plot_3_crosshole_tomography.html).

_Originally posted by @halbmy in https://github.com/gimli-org/gimli/issues/166#issuecomment-464806900_

I tried this, however it can't determine the data format of Ra2dTomo files. 

file looks like this, I do not know what the respective columns are

        6.37           0        1.10        0.00      502.71        3.73        0.00      502.74
       10.49           0        1.10        0.00      502.71        3.61        0.00      502.69
       16.33           0        1.10        0.00      502.71        7.17        0.00      502.59
       19.58           0        1.10        0.00      502.71       11.21        0.00      502.68
       25.51           0        1.10        0.00      502.71       19.15        0.00      502.70

` C:/msys64/home/Guenther.T/src/gimli/gimli36/src/datacontainer.cpp: 205		virtual int GIMLI::DataContainer::load(const string&, bool, bool)  cannot determine data format. 8`

**Comment by halbmy** [comment]
> file looks like this, I do not know what the respective columns are

in #166 there is a description of the columns:

*with the first column being the traveltime, the 3rd/4th and 5th/6th are x/y or x/z coordinates of shot and geophone*

**Comment by halbmy** [comment]
`readTOMfile` should return a dataContainer, so I cannot understand why your script (in which the import of readTOMfile is missing) should evoke `DataContainer.load(filename)` (your error message).

For a reasonable answer we would need to see the data file and script attached.

**Comment by GGDRriedel** [comment]
In ther referencede issue you write 

> Actually, once there was a manager class Tomography (inherited from Refraction) that could be initialized by .TOM files directly (tomo = Tomography(filename))


I am referencing that.

**Comment by halbmy** [comment]
Yes I wrote, *once there was* and this means it is not and it is not necessary. As pointed out in #204, things are changing a lot in pygimli 1.1.

I still see no indication substantiating the title "Reading .tom file fails". Please provide a .tom file along with a script where this fails or close the issue (probably better called "Refraction cannot be initialized by .tom file"). See also #205 and #204.
