### ISSUE TITLE
Refraction Object  - Data-Access

### ISSUE THREAD

**Issue by GGDRriedel** [gimli-org/gimli#204]
### Problem description

can't find an attribute or method of the refraction object to give me back the data values

### Your environment

Windows python 3.6

**pyGIMLi version**: Output of `print(pg.__version__)`: 0+untagged.2392.gbc43dbc)  I believe it's .11
**Way of installation**: e.g. conda wheel

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
import pygimli as pg

from pygimli.physics import Refraction
filename = pg.getExampleFile("traveltime/koenigsee.sgt")
ra = Refraction(filename)
print(ra)
ra.dataVals()

```

### Expected behavior

Giving a numpy array of data values that are contained somewhere within the object

### Actual behavior

asks for a data object

```
dataVals() missing 1 required positional argument: 'data'
```

**Comment by GGDRriedel** [comment]
Followup to this: 
Reflex .tom files have t in Milliseconds
The readTOMfile function does not account for that. 
See https://github.com/gimli-org/gimli/issues/166#issuecomment-464806900


Since I can't find a way to access the values inside the container, I can't change that. 
Access on the datacontainer also does not work since
'''
data['t']=data['t']/1000.0
'''
yields > 'DataContainer' object does not support item assignment



Used code: 
'''
data=readTOMfile('test3.tom')
data.sortSensorsX()
ra = Refraction(data)
print(ra)
ra.createMesh(depth=100,quality=25)
ra.showMesh()
ra.invert(zWeight=0.2)
'''

**Comment by carsten-forty2** [comment]
Index access for the `DataContainer` is a new feature of the upcoming version 1.1. (fw_cleaning branch)

Please note that the `Refraction` class will be deprecated with 1.1 so we probably will not apply any changes to this old class.  

The successor in 1.1 will be the TravelTimeManager which is supposed to have a clearer design.

**Comment by halbmy** [comment]
Anyway, you should be able to use `data('t') = data('t') / 1000`

**Comment by halbmy** [comment]
I introduced reading the ReflexW .tom format when working with crosshole GPR data. For these data, the traveltimes in the file have been in nanoseconds. There I did not need any scaling as velocity is usually in m/ns.

Basically, there is no way of robustly guessing the unit (and therefore the measurement, could also be microseconds in ultrasonic). The same holds for the z position.

So what we (or you) could do is to add arguments to the function like `readTOMfile(scaleT=0.001, isHeight=True)` or similar. But it is not our focus to write and maintain import routines for all instruments and softwares. That's something that can be done in a script before. Furthermore, a method manager should only be initialized by a correct data container or the standard unified format.

P.S.: `data('t') *= 0.001` does unfortunately not work but in pg 1.1 `data['t']` will ease the matter.

**Comment by GGDRriedel** [comment]
I have modified your code to deal with the issues I am having.

However, it is kind of complicated since there is no documented (or easily findable at that) way of accessing the data in the data-container in a pythonic way.

Looking forward to 1.1.

**Comment by halbmy** [comment]
I agree that a rigorous documentation of the (C++ based) DataContainer class (which is an important class) is missing. Therefore I suggest that we will create a tutorial under basics (similar to the tutorial on the Mesh class) and leave it open as a reminder.

**Comment by carsten-forty2** [comment]
In 1.1. we try to move the c++ api doc from the core into the python object .. until then you can find the c++ api doc for the DataContainer here: 
https://www.pygimli.org/gimliapi/classGIMLI_1_1DataContainer.html

An additional tutorial for the DataContainer is also a good idea but of course need more afford.

**Comment by halbmy** [comment]
I don't expect any progress here and close the issue.

We showed ways to handle the problem in pg 1.0 and will have to check with pg 1.1 but the general solution is the same: first import your data and make sure all is set well and then go into the manager classes.

Merry christmas
