### ISSUE TITLE
Diffrent Height-Sense .tom vs .sgt

### ISSUE THREAD

**Issue by GGDRriedel** [gimli-org/gimli#205]
### Problem description

Importing same data yields different directional senses in z direction

### Your environment

**Operating system**: Win
**Python version**: 3.6
**pyGIMLi version**: 0.11
**Way of installation**: Wheel 

### Steps to reproduce

read .tom file and .sgt file of same data

[file.sgt.txt](https://github.com/gimli-org/gimli/files/3814748/file.sgt.txt)
[test3.tom.txt](https://github.com/gimli-org/gimli/files/3814749/test3.tom.txt)

Meshing it creates different directional senses. 

```python
import pygimli as pg
from pygimli.physics import Refraction
from pygimli.physics.traveltime.importData import readTOMfile


ras = Refraction('file.sgt')
## Tom file:
data=readTOMfile('test3.tom')
data.sortSensorsX()
ra = Refraction(data)



ra.showData()  
ras.showData()

ra.showVA()  # show data as apparent velocity image
ras.showVA()

ra.createMesh(depth=100,quality=25)
ra.showMesh()

ras.createMesh(depth=100,quality=25)
ras.showMesh()

...
```

### Expected behavior

Same mesh, same data
### Actual behavior

Different directional sense

```
See meshes
```

**Comment by halbmy** [comment]
First, your data are not really identical:
```Python
import numpy as np
import pygimli as pg
from pygimli.physics import Refraction
from pygimli.physics.traveltime.importData import readTOMfile

sgt = pg.DataContainer('file.sgt', 's g')
tom = readTOMfile('test3.tom')
tom.set('t', tom('t') * 0.001)
tom.sortSensorsX()
print(sgt, tom)  # data number is different!
xT = pg.x(sgt.sensorPositions())
xS = pg.x(tom.sensorPositions())
print(min(xT-xS), max(xT-xS))
```
shows that your positions are different by up to 1m. Even slight changes in the positions can lead to totally different triangulations.

Main point is, however, the interpretation of z as either height or depth. As I have seen the TOM format only for cross-hole tomography, I interpreted as depth and multiplied by -1 for the pygiml convention (positive upwards). But this can be easily corrected by `tom.scale([1, -1])`. 

Feel free to improve any import routines by creating a pull request.
