### ISSUE TITLE
Regional manager knows no mesh

### ISSUE THREAD

**Issue by GGDRriedel** [gimli-org/gimli#207]
### Problem description

Automatic mesh generation on inversion not working

### Your environment

**Operating system**: Win
**Python version**: 3.7
**pyGIMLi version**: 1.1
**Way of installation**: conda

### Steps to reproduce

Start Inversion without mesh

```python

import matplotlib as mpl
import pygimli as pg
from pygimli.physics.traveltime import TravelTimeManager as Refraction  # pg 1.1
# from pygimli.physics.traveltime import Refraction # pg1.0
mpl.rcParams['image.cmap'] = 'inferno_r'

data = pg.DataContainer('thefile.sgt', "s g")
mesh = pg.Mesh('themesh.bms')

ttinv = Refraction()
ttinv.setData(data)
#ttinv.setMesh(mesh, secNodes=5)
invmodel = ttinv.invert(usegradient=True, vtop=2, vbottom=4,
                        zWeight=1.0, maxIter=1, verbose=True)

```

### Expected behavior

See documentation on
https://www.pygimli.org/pygimliapi/_generated/pygimli.manager.html?highlight=zweight
"The meshes will be created if necessary."

### Actual behavior

Error

```
Traceback (most recent call last):

  File "<ipython-input-4-52996f816bee>", line 14, in <module>
    zWeight=1.0, maxIter=1, verbose=True)

  File "C:\ProgramData\Anaconda3\envs\pygimlinew\lib\site-packages\pygimli\physics\traveltime\TravelTimeManager.py", line 315, in invert
    slowness = super(TravelTimeManager, self).invert(data, **kwargs)

  File "C:\ProgramData\Anaconda3\envs\pygimlinew\lib\site-packages\pygimli\frameworks\methodManager.py", line 600, in invert
    if self.fop.mesh() is None:

  File "C:\ProgramData\Anaconda3\envs\pygimlinew\lib\site-packages\pygimli\frameworks\modelling.py", line 527, in mesh
    self.createFwdMesh_()

  File "C:\ProgramData\Anaconda3\envs\pygimlinew\lib\site-packages\pygimli\frameworks\modelling.py", line 505, in createFwdMesh_
    m = pg.Mesh(self.regionManager().mesh())

RuntimeError: RegionManager knows no mesh.
```

**Comment by carsten-forty2** [comment]
The Documentation is for `<pygimli-1.1.`

Currently we changed the behavior that the Manager create meshes. 
So either give the mesh to `ttinv` or set it as kwarg in `ttinv.invert`.

**Comment by GGDRriedel** [comment]
I am using V1.1

**Comment by carsten-forty2** [comment]
yes .. the documentation ist for the master branch, means lower pygimli-1.1.

The fw_cleaning branch will be V.1.1. in the end. When we rebase this to the new master then the html for the api-dokumention will be changed to. Until this time, you need to look in the code or use the python inline help.

**Comment by halbmy** [comment]
The documentation for the (still in development) 1.1 branch is on
http://www2.geo.uni-bonn.de/~wagner/pg/pygimliapi/index.html
