### ISSUE TITLE
Inversion ignores gradient, but doesn't, but does

### ISSUE THREAD

**Issue by GGDRriedel** [gimli-org/gimli#208]
### Problem description

Using gradient model on inversion not working

### Your environment

**Operating system**: Win7
**Python version**: 3.7
**pyGIMLi version**: 1.1
**Way of installation**: Conda

### Steps to reproduce

```python
invmodel = ttinv.invert(usegradient=True, vtop=2, vbottom=4,
                        zWeight=1.0, maxIter=1, verbose=True)
...
```

### Expected behavior

inversion with gradient model

### Actual behavior

Output:

```
11/11/19 - 15:41:55 - pyGIMLi - INFO - Creating forward mesh from region infos.
11/11/19 - 15:41:55 - pyGIMLi - INFO - Creating refined mesh (secnodes: 5) to solve forward task.
11/11/19 - 15:41:55 - pyGIMLi - INFO - Starting inversion.
11/11/19 - 15:41:55 - pyGIMLi - INFO - Create gradient starting model. 500: 5000
11/11/19 - 15:41:55 - pyGIMLi - INFO - Created startmodel from forward operator: [0.00032302 0.000254   0.00175735 ... 0.00028267 0.00027231 0.00027511]
fop: <pygimli.physics.traveltime.TravelTimeManager.TravelTimeDijkstraModelling object at 0x00000000146EF570>
Data transformation: <pygimli.core._pygimli_.RTransLog object at 0x00000000146EF650>
Model transformation: <pygimli.core._pygimli_.RTransLog object at 0x00000000146EF618>
min/max (data): 4.1/16.3
min/max (error): 3%/3%
min/max (start model): 2.0e-04/0.0020
--------------------------------------------------------------------------------
Warning! unused keyword arguments {'usegradient': True, 'vtop': 2, 'vbottom': 4}
```
Notice how it says it's creating a gradient model but in the end says that it ignores key words.

**Comment by carsten-forty2** [comment]
The code works as supposed to be. 
If you take a look at the api documentation it shows the argument is called `useGradient: bool [True]` (CamelShaped) and the default is True.

**Comment by GGDRriedel** [comment]
Then the output does not.

If you look at what Iw rote it reports 
'''
{'usegradient': True, 'vtop': 2, 'vbottom': 4}
'''

**Comment by carsten-forty2** [comment]
Your keyword arguments are not valid and hence not used. 
Regarding the api docu they called `useGradient`, `vTop` and `vBottom`. Note the CamelShape.

**Comment by GGDRriedel** [comment]
I just noticed. 

Code was copied here: 

https://www.pygimli.org/_examples_auto/seismics/plot_3_crosshole_tomography.html#sphx-glr-examples-auto-seismics-plot-3-crosshole-tomography-py

Where it's using the all lowercase arguments.

**Comment by carsten-forty2** [comment]
The travel time examples are already migrated to 1.1. 
You find them in the documentation path or here: https://github.com/gimli-org/gimli/tree/fw_cleaning/doc/examples/seismics

**Comment by florian-wagner** [comment]
Same as in #207. The documentation on pygimli.org is referring to the last stable version and pygimli 1.1, which you are using, is developed in parallel with a preliminary documentation here: http://www2.geo.uni-bonn.de/~wagner/pg/_examples_auto/seismics/plot_3_crosshole_tomography.html
