### ISSUE TITLE
readGmsh does not properly import Points

### ISSUE THREAD

**Issue by m-weigand** [gimli-org/gimli#210]
### Problem description

If physical points in a GMSH-mesh are not defined in consecutive order, starting with 1, imports are broken.

This is caused by using tags to determine node-indices, instead of node numbers.

Pull-request forthcoming

P.S. As a reference, attached mesh will break the import because Point(0) is defined in the physical group 99.

[mesh file and geo file.zip](https://github.com/gimli-org/gimli/files/3846075/mesh.file.and.geo.file.zip)

**Comment by florian-wagner** [comment]
Closed with #211.
