### ISSUE TITLE
How to obtain simulated traveltimes from an inversion result with the refraction manager

### ISSUE THREAD

**Issue by soetpotet** [gimli-org/gimli#213]
Hi!

I was wondering how can I get a variable that contains the simulated traveltimes for a given inversion result?

I saw you had an option called `simulate` (https://www.pygimli.org/pygimliapi/_generated/pygimli.physics.traveltime.html?highlight=refraction%20manager#pygimli.physics.traveltime.Refraction.simulate) and I guess I could input my mesh, the resulting model from the inversion and the acquisition scheme to obtain simulated traveltimes, but since the result is somewhere inside the inversion process already I thought there might be a smarter way to retrieve them (sorry if it's somewhere in the documentation and I missed it).

I might want to do some corrections for timelapse inversions, and since the data are picked traveltimes I understand I would need the modeled traveltimes for the correction. 

Thanks a lot!

**Comment by halbmy** [comment]
I guess you mean the model response, i.e. f(model), after the inversion? Like written in the code (https://www.pygimli.org/_modules/pygimli/physics/traveltime/refraction.html#Refraction.invert)
the refraction class holds a variable `self.response = self.inv.response()` being retrieved from the inversion class.

**Comment by soetpotet** [comment]
Yes! That's what I was looking for. Thanks :)
