### ISSUE TITLE
Python 3.6 Win64 1.0.12 Wheel missing

### ISSUE THREAD

**Issue by GGDRriedel** [gimli-org/gimli#214]
https://github.com/gimli-org/gimli/releases/download/v1.0.12/pygimli-1.0.12-cp36-cp36m-win_amd64.whl

Leads to an error

**Comment by halbmy** [comment]
What exactly is the error?

**Comment by GGDRriedel** [comment]
Good idea! 

It would be much apreciated if you kept up the files for legacy reasons though :)

**Comment by halbmy** [comment]
We are keeping all the files as they are stored in the releases (https://github.com/gimli-org/gimli/releases) and will rather link there instead of having tens of badges. For Python 3.6 this release never existed but it will.
