### ISSUE TITLE
[Question] Inversion Parameter context

### ISSUE THREAD

**Issue by GGDRriedel** [gimli-org/gimli#215]
I am experimenting with inversion parameters. 
Since it's pretty ineffective to just guess, here is my question: 

Can you give some context to zWeight and lam?

Like,  for zweight, what are the limits and the direction? 
Does it go from 0 to 1 or 0 to inf or negative to positive? 

Which "direction" is a more layered preference?

Same for lam. Setting it to 1100 obviously gives a smooth ride, but what is the mathematical/scientific value-definition for it? 

Cheers

**Comment by halbmy** [comment]
`lam` is the usual inversion parameter (total penalty factor for the model roughness) as explained in many papers and even inversion tutorials, but also in the BERT tutorial. The definition is provided by the BERT paper (Günther et al. 2006) and other papers from us or other colleagues.

zWeight is the relative weight in vertical direction compared to the horizontal direction. Any value can be passed but mostly it is between 0 (or 0.01 or so) and 1. A value <1 leads to more layered structures which are often the case. Therefore one can work with values between 0.1 and 1. Details on the formula are described by Coscia et al. (2011).

I agree that more tutorials on that matter would be helpful.

Günther, T., Rücker, C. & Spitzer, K. (2006): 3-D modeling and inversion of DC resistivity data incorporating topography – Part II: Inversion. Geophys. J. Int. 166, 506-517, doi:10.1111/j.1365-246X.2006.03011.x.

Coscia, I., Greenhalgh, S., Linde, N., Doetsch, J. A., Marescot, L., Günther, T., Vogt, T. & Green, A. (2011):
3D crosshole ERT for aquifer characterization and monitoring of infiltrating river water. Geophysics 76(2), G49-G59, doi:10.1190/1.3553003.

**Comment by GGDRriedel** [comment]
Thank your for this explaination, it helps a lot!
