### ISSUE TITLE
1D chi inversion fails to run

### ISSUE THREAD

**Issue by mariosgeo** [gimli-org/gimli#216]
### Problem description
The optimized inversion for 1D VES data, chi^2, retruns 
RuntimeError: C:/msys64/home/halbm/gimli/gimli/src/inversion.h: 638		double GIMLI::Inversion<ModelValType>::getPhiD(const Vec&) const [with ModelValType = double; GIMLI::Inversion<ModelValType>::Vec = GIMLI::Vector<double>]  getPhiD == nan

All other inversion, blocky, etc work fine. 

### Your environment

**Operating system**: e.g. Windows?
**Python version**: e.g. 3.7?
**pyGIMLi version**: Output of `print(pg.__version__)`
**Way of installation**: e.g. Conda package, Win binary, curl script, manual compilation from source
Conda
![Figure_2](https://user-images.githubusercontent.com/3422736/71245730-a3589b80-2315-11ea-8546-3a0ac3b97318.png)

**Comment by halbmy** [comment]
PhiD can be NaN if the data error is zero or if either data or model response is infinite, or <= 0 thus crossing the data transformation. 
Can you paste your script?

**Comment by mariosgeo** [comment]
Hi, I follow the tutorial https://www.pygimli.org/_tutorials_auto/3_inversion/plot-4-dc1dsmooth.html, I only have a different data set.


    thk_smooth = np.logspace(-0.5, 1.5, 30)
    f = pg.DC1dRhoModelling(thk_smooth, ab2, ab2/3)
    inv2 = pg.RInversion(rhoa, f, transRhoa, transRho, False)  # data vector, f, ...

    inv.setRelativeError(errPerc / 100.0)
    # Create a homogeneous starting model


    model = pg.RVector(len(thk)+1, np.median(rhoa))  # uniform values
    inv2.setModel(model)  #
    # Set pretty large regularization strength and run inversion

    print("inversion with lam=200")
    inv2.setLambda(100)
    res100 = inv2.run()  # result is a pg.RVector, but compatible to numpy array
    print('rrms={:.2f}%, chi^2={:.3f}'.format(inv.relrms(), inv.chi2()))
    # Decrease the regularization (smoothness) and start (from old result)
    print("inversion with lam=20")
    inv.setLambda(10)
    res10 = inv2.run()  # result is a pg.RVector, but compatible to numpy array
    print('rrms={:.2f}%, chi^2={:.3f}'.format(inv.relrms(), inv.chi2()))
    # We now optimize lambda such that data are fitted within noise (chi^2=1)
    print("chi^2=1 optimized inversion")
    resChi = inv2.runChi1()  # ends up in a lambda of about 3
    print("optimized lambda value:", inv.getLambda())
    print('rrms={:.2f}%, chi^2={:.3f}'.format(inv.relrms(), inv.chi2()))

**Comment by mariosgeo** [comment]
Hmm, you are right. I had
    inv.setRelativeError(errPerc / 100.0), 
instead of 
    inv2.setRelativeError(errPerc / 100.0)

**Comment by halbmy** [comment]
That's still strange, because by default a relative error of 1% is set. Anyway, we are redesigning the inversion class (pg 1.1) and should check all typical problems causing errors. In the meanwhile, in case of such errors you can have a look at the files being produced. Thanks for reporting and merry Christmas.
