### ISSUE TITLE
no modlue found pygimli

### ISSUE THREAD

**Issue by Khalilsqu** [gimli-org/gimli#219]
C:\Users\asalh>conda activate pygimli

(pygimli) C:\Users\asalh>conda install -c gimli pygimli
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Miniconda3\envs\pygimli

  added / updated specs:
    - pygimli

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pygimli-1.0.11.1           |           py36_0        27.6 MB  gimli
    ------------------------------------------------------------
                                           Total:        27.6 MB

The following NEW packages will be INSTALLED:

  pygimli            gimli/win-64::pygimli-1.0.11.1-py36_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
pygimli-1.0.11.1     | 27.6 MB   | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(pygimli) C:\Users\asalh>code .

(pygimli) C:\Users\asalh>jupyter notebook
[I 15:57:58.210 NotebookApp] The port 8888 is already in use, trying another port.
[I 15:57:58.210 NotebookApp] The port 8889 is already in use, trying another port.
[I 15:57:58.220 NotebookApp] Serving notebooks from local directory: C:\Users\asalh
[I 15:57:58.220 NotebookApp] The Jupyter Notebook is running at:
[I 15:57:58.220 NotebookApp] http://localhost:8890/?token=48b924a1ec3b8d21208c42293fb5fe838f07c5b66d3872f9
[I 15:57:58.222 NotebookApp]  or http://127.0.0.1:8890/?token=48b924a1ec3b8d21208c42293fb5fe838f07c5b66d3872f9
[I 15:57:58.222 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:57:58.232 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/asalh/AppData/Roaming/jupyter/runtime/nbserver-12652-open.html
    Or copy and paste one of these URLs:
        http://localhost:8890/?token=48b924a1ec3b8d21208c42293fb5fe838f07c5b66d3872f9
     or http://127.0.0.1:8890/?token=48b924a1ec3b8d21208c42293fb5fe838f07c5b66d3872f9
[I 15:58:13.235 NotebookApp] Interrupted...
[I 15:58:13.236 NotebookApp] Shutting down 0 kernels

(pygimli) C:\Users\asalh>conda list
# packages in environment at C:\Miniconda3\envs\pygimli:
#
# Name                    Version                   Build  Channel
attrs                     19.3.0                     py_0
backcall                  0.1.0                    py36_0
blas                      1.0                         mkl
bleach                    3.1.0                    py36_0
ca-certificates           2020.1.1                      0
certifi                   2019.11.28               py36_0
colorama                  0.4.3                      py_0
cycler                    0.10.0           py36h009560c_0
decorator                 4.4.1                      py_0
defusedxml                0.6.0                      py_0
entrypoints               0.3                      py36_0
freetype                  2.9.1                ha9979f8_1
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
importlib_metadata        1.5.0                    py36_0
inflect                   4.1.0                    py36_0
intel-openmp              2019.4                      245
ipykernel                 5.1.4            py36h39e3cac_0
ipython                   7.12.0           py36h5ca1d4c_0
ipython_genutils          0.2.0                    py36_0
jaraco.itertools          5.0.0                      py_0
jedi                      0.16.0                   py36_0
jinja2                    2.11.1                     py_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.2.0                    py36_0
jupyter_client            5.3.4                    py36_0
jupyter_core              4.6.1                    py36_0
kiwisolver                1.1.0            py36ha925a31_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py36he774522_0
matplotlib                3.1.3                    py36_0
matplotlib-base           3.1.3            py36h64f37c6_0
mistune                   0.8.4            py36he774522_0
mkl                       2019.4                      245
mkl-service               2.3.0            py36hb782905_0
mkl_fft                   1.0.15           py36h14836fe_0
mkl_random                1.1.0            py36h675688f_0
more-itertools            8.2.0                      py_0
msys2-conda-epoch         20160418                      1
nbconvert                 5.6.1                    py36_0
nbformat                  5.0.4                      py_0
notebook                  6.0.3                    py36_0
numpy                     1.18.1           py36h93ca92e_0
numpy-base                1.18.1           py36hc3f5095_1
openssl                   1.1.1d               he774522_3
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py36_1
parso                     0.6.0                      py_0
pickleshare               0.7.5                    py36_0
pip                       20.0.2                   py36_1
prometheus_client         0.7.1                      py_0
prompt_toolkit            3.0.3                      py_0
pygimli                   1.0.11.1                 py36_0    gimli
pygments                  2.5.2                      py_0
pyparsing                 2.4.6                      py_0
pyqt                      5.9.2            py36h6538335_2
pyrsistent                0.15.7           py36he774522_0
python                    3.6.10               h9f7ef89_0
python-dateutil           2.8.1                      py_0
pywin32                   227              py36he774522_1
pywinpty                  0.5.7                    py36_0
pyzmq                     18.1.1           py36ha925a31_0
qt                        5.9.7            vc14h73c81de_0
send2trash                1.5.0                    py36_0
setuptools                45.1.0                   py36_0
sip                       4.19.8           py36h6538335_0
six                       1.14.0                   py36_0
sqlite                    3.31.1               he774522_0
terminado                 0.8.3                    py36_0
testpath                  0.4.4                      py_0
tornado                   6.0.3            py36he774522_0
traitlets                 4.3.3                    py36_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
wcwidth                   0.1.8                      py_0
webencodings              0.5.1                    py36_1
wheel                     0.34.2                   py36_0
wincertstore              0.2              py36h7fe50ca_0
winpty                    0.4.3                         4
zeromq                    4.3.1                h33f27b4_3
zipp                      2.1.0                      py_0
zlib                      1.2.11               h62dcd97_3

(pygimli) C:\Users\asalh>

(pygimli) C:\Users\asalh>python
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:18:16) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygimli
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pygimli'
>>>

**Comment by halbmy** [comment]
That's strange. Can you try creating a new environment with python=3.7 which is going to install pygimli 1.0.12?

**Comment by Khalilsqu** [comment]
I tried with python 3.7.0 and 3.7.6 and it did not work.

Microsoft Windows [Version 10.0.19041.21]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\asalh>conda create -n pygim python==3.7
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Miniconda3\envs\pygim

  added / updated specs:
    - python==3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-3.7.0               |       hea74fb7_0        16.6 MB
    wheel-0.34.2               |           py37_0          66 KB
    ------------------------------------------------------------
                                           Total:        16.7 MB

The following NEW packages will be INSTALLED:

  certifi            pkgs/main/win-64::certifi-2019.11.28-py37_0
  pip                pkgs/main/win-64::pip-20.0.2-py37_1
  python             pkgs/main/win-64::python-3.7.0-hea74fb7_0
  setuptools         pkgs/main/win-64::setuptools-45.1.0-py37_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_1
  wheel              pkgs/main/win-64::wheel-0.34.2-py37_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
python-3.7.0         | 16.6 MB   | ############################################################################ | 100%
wheel-0.34.2         | 66 KB     | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate pygim
#
# To deactivate an active environment, use
#
#     $ conda deactivate


C:\Users\asalh>conda activate pygim

(pygim) C:\Users\asalh>conda install numpy matplotlib
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Miniconda3\envs\pygim

  added / updated specs:
    - matplotlib
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    matplotlib-3.1.3           |           py37_0          22 KB
    matplotlib-base-3.1.3      |   py37h64f37c6_0         4.9 MB
    ------------------------------------------------------------
                                           Total:         4.9 MB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/win-64::blas-1.0-mkl
  ca-certificates    pkgs/main/win-64::ca-certificates-2020.1.1-0
  cycler             pkgs/main/win-64::cycler-0.10.0-py37_0
  freetype           pkgs/main/win-64::freetype-2.9.1-ha9979f8_1
  icc_rt             pkgs/main/win-64::icc_rt-2019.0.0-h0cc432a_1
  icu                pkgs/main/win-64::icu-58.2-ha66f8fd_1
  intel-openmp       pkgs/main/win-64::intel-openmp-2019.4-245
  jpeg               pkgs/main/win-64::jpeg-9b-hb83a4c4_2
  kiwisolver         pkgs/main/win-64::kiwisolver-1.1.0-py37ha925a31_0
  libpng             pkgs/main/win-64::libpng-1.6.37-h2a8f88b_0
  matplotlib         pkgs/main/win-64::matplotlib-3.1.3-py37_0
  matplotlib-base    pkgs/main/win-64::matplotlib-base-3.1.3-py37h64f37c6_0
  mkl                pkgs/main/win-64::mkl-2019.4-245
  mkl-service        pkgs/main/win-64::mkl-service-2.3.0-py37hb782905_0
  mkl_fft            pkgs/main/win-64::mkl_fft-1.0.15-py37h14836fe_0
  mkl_random         pkgs/main/win-64::mkl_random-1.1.0-py37h675688f_0
  numpy              pkgs/main/win-64::numpy-1.18.1-py37h93ca92e_0
  numpy-base         pkgs/main/win-64::numpy-base-1.18.1-py37hc3f5095_1
  openssl            pkgs/main/win-64::openssl-1.1.1d-he774522_3
  pyparsing          pkgs/main/noarch::pyparsing-2.4.6-py_0
  pyqt               pkgs/main/win-64::pyqt-5.9.2-py37h6538335_2
  python-dateutil    pkgs/main/noarch::python-dateutil-2.8.1-py_0
  qt                 pkgs/main/win-64::qt-5.9.7-vc14h73c81de_0
  sip                pkgs/main/win-64::sip-4.19.8-py37h6538335_0
  six                pkgs/main/win-64::six-1.14.0-py37_0
  sqlite             pkgs/main/win-64::sqlite-3.31.1-he774522_0
  tornado            pkgs/main/win-64::tornado-6.0.3-py37he774522_0
  zlib               pkgs/main/win-64::zlib-1.2.11-h62dcd97_3


Proceed ([y]/n)? y


Downloading and Extracting Packages
matplotlib-base-3.1. | 4.9 MB    | ############################################################################ | 100%
matplotlib-3.1.3     | 22 KB     | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(pygim) C:\Users\asalh>conda install -c gimli pygimli
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Miniconda3\lib\site-packages\conda\cli\install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "C:\Miniconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\Miniconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\Miniconda3\lib\site-packages\conda\core\solve.py", line 275, in solve_final_state
        ssc = self._add_specs(ssc)
      File "C:\Miniconda3\lib\site-packages\conda\core\solve.py", line 696, in _add_specs
        raise UnsatisfiableError({})
    conda.exceptions.UnsatisfiableError:
    Did not find conflicting dependencies. If you would like to know which
    packages conflict ensure that you have enabled unsatisfiable hints.

    conda config --set unsatisfiable_hints True


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Miniconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "C:\Miniconda3\lib\site-packages\conda\cli\install.py", line 299, in install
        should_retry_solve=(repodata_fn != repodata_fns[-1]),
      File "C:\Miniconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\Miniconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\Miniconda3\lib\site-packages\conda\core\solve.py", line 275, in solve_final_state
        ssc = self._add_specs(ssc)
      File "C:\Miniconda3\lib\site-packages\conda\core\solve.py", line 694, in _add_specs
        ssc.r.find_conflicts(spec_set)
      File "C:\Miniconda3\lib\site-packages\conda\resolve.py", line 347, in find_conflicts
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "C:\Miniconda3\lib\site-packages\conda\resolve.py", line 507, in build_conflict_map
        root, search_node, dep_graph, num_occurances)
      File "C:\Miniconda3\lib\site-packages\conda\resolve.py", line 369, in breadth_first_search_for_dep_graph
        last_spec = MatchSpec.union((path[-1], target_paths[-1][-1]))[0]
      File "C:\Miniconda3\lib\site-packages\conda\models\match_spec.py", line 481, in union
        return cls.merge(match_specs, union=True)
      File "C:\Miniconda3\lib\site-packages\conda\models\match_spec.py", line 475, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "C:\Miniconda3\lib\site-packages\conda\models\match_spec.py", line 475, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "C:\Miniconda3\lib\site-packages\conda\models\match_spec.py", line 502, in _merge
        final = this_component.union(that_component)
      File "C:\Miniconda3\lib\site-packages\conda\models\match_spec.py", line 764, in union
        return '|'.join(options)
    TypeError: sequence item 0: expected str instance, Channel found

`$ C:\Miniconda3\Scripts\conda-script.py install -c gimli pygimli`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=pygim
                CONDA_EXE=C:\Miniconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Miniconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Miniconda3\envs\pygim
    CONDA_PROMPT_MODIFIER=(pygim)
         CONDA_PYTHON_EXE=C:\Miniconda3\python.exe
               CONDA_ROOT=C:\Miniconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\asalh
                     PATH=C:\Miniconda3;C:\Miniconda3\Library\mingw-w64\bin;C:\Miniconda3\Librar
                          y\usr\bin;C:\Miniconda3\Library\bin;C:\Miniconda3\Scripts;C:\Miniconda
                          3\bin;C:\Miniconda3\envs\pygim;C:\Miniconda3\envs\pygim\Library\mingw-
                          w64\bin;C:\Miniconda3\envs\pygim\Library\usr\bin;C:\Miniconda3\envs\py
                          gim\Library\bin;C:\Miniconda3\envs\pygim\Scripts;C:\Miniconda3\envs\py
                          gim\bin;C:\Miniconda3\condabin;C:\Miniconda3;C:\Miniconda3\Library\min
                          gw-w64\bin;C:\Miniconda3\Library\usr\bin;C:\Miniconda3\Library\bin;C:\
                          Miniconda3\Scripts;C:\Users\asalh\AppData\Local\Programs\Python\Python
                          37\Scripts;C:\Users\asalh\AppData\Local\Programs\Python\Python37;C:\Wi
                          ndows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32
                          \WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files
                          (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\WIND
                          OWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\W
                          indowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program
                          Files\Microsoft VS Code\bin;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Program Files\Dart\dart-sdk\bin;C:\Program Files\Dart\dart-
                          sdk\bin;C:\Users\asalh\AppData\Local\Microsoft\WindowsApps;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : pygim
    active env location : C:\Miniconda3\envs\pygim
            shell level : 1
       user config file : C:\Users\asalh\.condarc
 populated config files : C:\Users\asalh\.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.2
       base environment : C:\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/gimli/win-64
                          https://conda.anaconda.org/gimli/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda3\pkgs
                          C:\Users\asalh\.conda\pkgs
                          C:\Users\asalh\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda3\envs
                          C:\Users\asalh\.conda\envs
                          C:\Users\asalh\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true



(pygim) C:\Users\asalh>

**Comment by Khalilsqu** [comment]
However, I installed using 

`pip install pygimli-1.0.12-cp37-cp37m-win_amd64.whl`

This worked.

Thanks for this great package. I am using to teach a lab component in and undergraduate geophysics course. This packages runs the inversion way faster than SimPeg

**Comment by halbmy** [comment]
Nice it is working for you for with the pip package. However, it is not quite the best way to handle dependencies to other packages. We will therefore focus on conda and potentially drop whl/msi support. Concerning conda, I recommend creating a fresh new environment and installing pygimli at the same time. 

`conda create -n pg -c gimli -c conda-forge pygimli`

conda will automatically care for the dependencies like numpy or matplotlib. Installing those before and then trying to install pygimli in an existing system would only lead to dependency conflicts (because pg is build against a specific np version) or at least downgrades or upgrades of mpl & np.

**Comment by Khalilsqu** [comment]
> conda create -n pg -c gimli -c conda-forge pygimli

This works perfectly.
