### ISSUE TITLE
Inversion on closed geometry and implications

### ISSUE THREAD

**Issue by Pbottelin** [gimli-org/gimli#221]
Hello!
I tried to use Pygimli to invert seismic profiles acquired around limestone pillars (about 5m*8m) in an old underground quarry.

Here enclosed is a minimal working example. Shot/sensors coordinates and traveltimes are in the .sgt. Parameters are given in a separate text file.

I have a few concerns/remarks dealing with the processing, e.g.:

1. Error handling. Setting the "true" amount of error on the data seems crucial for the inversion. Too large errors may stop the inversion as soon as iteration 1. Too small errors yield chi² value without any sense.
Error estimation has to be made using Refraction.estimateError() routine, which takes an absolute error (in seconds) and a relative error (betw 0 and 1) as a fraction of traveltime.

2. Closed geometry: I had to re-order the shots/sensors manually, sorted by polar angle / center of the rectangle. The default X-sorting fails in this case. One can also sort by 'X along tape' if this field is added in the dataContainer.

3. Mesh quality: does this parameter correspond to the minimal allowed angle triangle during meshing?

4. paraDX: seems unused, triangle size does not grow with depth (contrary to BERT mesh on same pillar)

5. Starting model: this parameter seems unused. Is it possible to display the starting model? (maybe with the command that yields results from each iteration?)

6. verbose: it looks like the option does not work (it does not display much whatever True/False). I also tried ra.setVerbose(True)

7. zWeight: 0=layered, 1=isotropic? Is there a way to enhance vertical boundaries? (zWeight=2?) How does that work with closed geometries such as mine? (there is not surface/horizontality)

8. Inversion stats: is there a way to get the rms/abs error/chi² at each iteration? I have only the final value. I would like to draw a graph to check the inversion progress along iterations.

9. I had to write a few 'dirty' code lines to store geophones/shots in a panda dataframe and plot them on the figure. I think I can do it better, I mean in a 'pygimli-compatible' way. (is there a way to 'tag' the dataContainer with 's' or 'g' in a better way than what I did?

10. Coverage: raycoverage(): is there a way to smooth the results?

11. I also wrote some code to show the hodochrones picked vs. simulated for a closed geometry: it requires a 'x along tape' column because the 'x' value is not well suited. I also plotted a figure with rms as a function of traveltime, and anothe with rms as a function of shot id (helps if a shot has been mispicked).

Sorry for the length of my post, I hope it will bring me answers and may help the other pg users to get confortable with this amazing tool!
Cheers,

Pierre
[MWE_pygimli_tomography.zip](https://github.com/gimli-org/gimli/files/4244729/MWE_pygimli_tomography.zip)

**Comment by carsten-forty2** [comment]
Hello Pierre,

thank you for your feedback ..  I think some issues are already solved in pygimli-1.1-rcXX so I will focus on this version (available in conda) with my answers. I played a little with your file and added a short script which produce the following result.
[PS02v1_1.pdf](https://github.com/gimli-org/gimli/files/4246510/PS02v1_1.pdf)

To your questions:
1) there is no 'true' error in your data file.  If you don't know the error, guessing is the best way I think. I think a small absolute error is sufficient (see the attached script)

2) The mesh creation needs sorted input (see api documentation), its in the responsibility of the user. I thought about some good guessing .. but there are to many special cases so I gave up for now ;)

3) Yes .. see api documentation or Triangle doc for more infos.

4) paraDX will not work for circular (closed) geometry.. see the script or api doc for the `addNodes` option for `createParaMeshPLC`

5) Starting model should work now. Best would be to avoid a gradient model for closed surfaces. The logger will show which kind of model is used.

6) `verbose` should now be a little better for `tt.invert`. If you run your script on windows .. you should allow for buffering with -u option e.g. `python -u SCRIPT.py`

7) `zWeight` .. weights the constraints for the z-coordinate (depth or y-coordinate for 2D problems).
Smaller values than 1 will produces more horizontal structures, higher values will produce more vertical structures, However, the latter is also like an upscale of lambda too.

8) there is a `tt.inv.chi2History` and `tt.inv.modelHistory` .. see the script.

9) you can access all shot points like this: `sensors[pg.unique(data['s'])]` or see script

10) the rays show the "real" way used in the forward step .. they will be smoother with higher `secNode` number with the cost of run time

11) I'm unsure what you mean.. a kind of dataplot like in the script?

I hope my short answers are helping a bit.

[seismic_tomography_pygimli_v1.1.py.gz](https://github.com/gimli-org/gimli/files/4246768/seismic_tomography_pygimli_v1.1.py.gz)

**Comment by Pbottelin** [comment]
Hi, 
thanks very much for your superfast answers!

> I look forward downloading the next pg1.1 version for windows when available (1.0 only is available on conda for the moment). It seems Refraction class is deprecated and replaced by TravelTime.

> Concerning my previous questions:

1. You're right, I don't have any error measurement on my data (acquired with 'usual' refraction devices) so that I have to guess it. Tenths of ms seems a good guess, considering the t0 uncertainty for a sledgehammer trigger.

2. Okay, sensor sorting has to be ensured as pre-processing step by the user. I have to work a bit further on this, because I thought that the sgt should contain in the # shot/geophone points:
-first the sorted shots
-then the sorted geophones
But it seems shot or geophones are considered without distinction, so that I should order them all together.
In this case ('mixed' shots and geophones), how does pygmli manages to attribute a 's' or 'g' label to the data? Thanks to the #measurements section, with #s g t identifiers maybe?

3. ok, thanks for the confirmation
4. ok, thanks

5. I'll check that in the 1.1! I agree, homogeneous starting model seems ok for such closed geometry. Would you advise a specific starting velocity? (e.g. higher than expected model, lower, or same order of magnitude?)

6. Okay, I'll se in 1.1. For the moment, I don't have much information in the spyder console. I don't know how to configurate the buffer option in spyder, but I'll dig into it soon.

7. Thanks for the zWeight behavior explanation. Is is homogeneous with pybert/BERT zWeight/zPower behavior? (in case I have to make joint interpretations, I want to parametrize both inversions with similar constraints)

8. Perfect, I'll see that with tt manager in pg1.1

9 and 10. Thanks!

11. Please see attached images.
For the hodochrones, it is similar to showResultandFit function but it used the 'xalongtape' coordinate to sort the data in such closed geometry (instead of "x"). Simulated traveltimes are drawn with the continuous line. I did not succeed yet to make the line pass through (shot xtape, 0 ms), which explains the 'flat' segment close to the shot.
For the RMS, see other figure. It is a simple representation of RMS depending on traveltime (top row) or shot number (bottom row). It helps identifying shots that may cause high RMS values. Just for the record.

Best regards!

Pierre
![hodochrones_xtape](https://user-images.githubusercontent.com/34316345/75348489-3a584b80-58a3-11ea-8794-5cbd1070e082.png)
![rms_abs_error](https://user-images.githubusercontent.com/34316345/75348495-3d533c00-58a3-11ea-872d-e00bc9293703.png)
