### ISSUE TITLE
xyz values from seismic refraction tomography velocity model?

### ISSUE THREAD

**Issue by viictorjs** [gimli-org/gimli#224]
Hello! I just started learning on how to use pyGIMli. I wonder, is there a way to obtain xyz values from the velocity model calculated by your algorithm of seismic refraction tomography? 
It seems I can only access the velocity values of the mesh cells, but not their respective x and y positions, like:

ra = Refraction(pgFile)
m = ra.createMesh()
vest = ra.invert()
print(vest) #velocity values from cells?
print(m) #number of nodes, cells and boundaries from mesh

**Comment by florian-wagner** [comment]
Hi @viictorjs, 
welcome to the pyGIMLi users! We will release 1.1 in a couple of weeks, so stay tuned for more.

You can get the x/z coordinates of the cell midpoints as such 

``` python
x = pg.x(m.cellCenters())
z = pg.z(m.cellCenters()) # same works for y
```
These are pygimli Vectors which can be converted to numpy arrays by `np.array(x)` for example. Alternatively, `m.exportMidCellValue("mydata.xyz", vest)` will write a file with the x/z and the corresponding cell velocities.

If that answers your questions, please close this issue.

Cheers
Florian

**Comment by viictorjs** [comment]
Thank you for the quick response, @florian-wagner !
It's exactly what I was looking for.
