### ISSUE TITLE
Import field data

### ISSUE THREAD

**Issue by siam2015** [gimli-org/gimli#225]
### Problem description

I am trying to use the crosshole tomography method to invert my field data. I read the tutorial carefully. But I still do not find a proper way to input my field data into this inversion framework because the travel time in the tutorial is based on a forward simulation. I have tried to use the loadData function but it cannot read my .sgt data.

### Your environment

**Operating system**: Windows
**Python version**: 3.6?
**pyGIMLi version**: 1.0.12
**Way of installation**: Anaconda pacakge

### Data file

10 # shot/geophone points		
#x	y	
0	-5	
0	-10	
0	-15	
0	-20	
0	-25	
20	-5	
20	-10	
20	-15	
20	-20	
20	-25	
25 # measurements		
#s	g	t
1	6	10.44025772
1	7	8.807646155
1	8	10.48887922
1	9	11.01847599
1	10	15.0351704
2	6	6.460804013
2	7	4.798741571
2	8	6.463451445
2	9	7.016878839
2	10	11.05944
3	6	10.4730669
3	7	8.817134496
3	8	10.4569917
3	9	8.877432931
3	10	12.87806182
4	6	15.44600604
4	7	13.81133677
4	8	10.63736617
4	9	8.621823363
4	10	12.61316942
5	6	20.47362681
5	7	16.5403878
5	8	11.58681921
5	9	9.564234194
5	10	13.54829733

**Comment by halbmy** [comment]
Can you please try:
```
data = pg.DataContainer('example.sgt', 's g')
```
This will load the file and define the shot (s) and geophone (g) as sensor Indices (integers pointing into the sensor list above and not just data fields), also done step by step by using
```
data = pg.DataContainer()
data.registerSensorIndex('s')
data.registerSensorIndex('g')
data.load('example.sgt')
```
Actually it would be a good idea to define (derive from `DataContainer`) a class `DataContainerTraveltime` where the sensor indices are already set.

**Comment by siam2015** [comment]
Thank you! It perfectly solved my question!
Cheers!!
