### ISSUE TITLE
Seismic Anisotropy

### ISSUE THREAD

**Issue by nevesanjos** [gimli-org/gimli#226]
### Problem description

Hi!

I am inverting some seismic refraction data by using pyGIMLi, and I noticed that it is possible to play with the initial model (vtop and vbottom) and smoothness (lam) parameters, but I didn't find one for anisotropy. Does pyGIMli deal with anisotropy in the seismic refraction inversions?

Thanks,
Felipe   

### Your environment

**Operating system**: Linux
**Python version**: 3.7
**pyGIMLi version**: 1.0.11+0.g9e41a4a3
**Way of installation**: Conda package

### Steps to reproduce

Not applicable

```python


```

### Expected behavior

Not applicable

### Actual behavior

Not applicable

```

```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
Not yet. Our shortest path solver would have to be adapted. Furthermore, we would need some concepts how to invert for anisotropy in a meaningful way. Feel free to contribute ideas or code.

Anisotropic model parameters can be used in forward modelling of some PDEs (pg.solve) and that's probably going to develop in the future, also towards inversion.

**Comment by florian-wagner** [comment]
(and just in case you were simply referring to anisotropic regularization, this can be achieved with the `zWeight` parameter, which is also used in the crosshole example: https://www.pygimli.org/_examples_auto/seismics/plot_3_crosshole_tomography.html)

**Comment by nevesanjos** [comment]
Thank you @florian-wagner,
Yes, I was simply referring to anisotropic regularization for now. 

Thank you @halbmy. In the near future, I would like to contribute with ideas, and maybe with code (I am not so experienced).
