### ISSUE TITLE
Problem importing this field data for SRT?

### ISSUE THREAD

**Issue by viictorjs** [gimli-org/gimli#227]
Hello! 

I have been able to import several seismic refraction field datasets to run with pyGIMLis tomography algorithm. 
However, with this particular dataset I'm having problems, because the curves returned by the showData() method are different from the actual observed travel-time curves of the data. The parameters are: 5 source positions (0, 2, 22, 34 and 46 m), 24 geohpones, spacing between geophones of 2 m, first geophone at position 0 m and the last one at 46 m.

These are the actual observed time-travel curves from this dataset:

![image](https://user-images.githubusercontent.com/13758236/79671567-7ae88d00-81a1-11ea-9b69-f2e824efddfa.png)

Is there something wrong with the file below?

29 # shot/geophone points
#x y
0.00 0
0.00 0
2.00 0
2.00 0
4.00 0
6.00 0
8.00 0
10.00 0
12.00 0
14.00 0
16.00 0
18.00 0
20.00 0
22.00 0
22.00 0
24.00 0
26.00 0
28.00 0
30.00 0
32.00 0
34.00 0
34.00 0
36.00 0
38.00 0
40.00 0
42.00 0
44.00 0
46.00 0
46.00 0
120 # measurements
#s g t
1 2 0.010318
1 4 0.018192
1 5 0.026065
1 6 0.033939
1 7 0.041993
1 8 0.043183
1 9 0.044373
1 10 0.045563
1 11 0.046753
1 12 0.047943
1 13 0.049133
1 15 0.050323
1 16 0.051513
1 17 0.052703
1 18 0.053893
1 19 0.055083
1 20 0.056273
1 22 0.057464
1 23 0.058654
1 24 0.059844
1 25 0.061034
1 26 0.062224
1 27 0.063414
1 29 0.064604
14 2 0.047821
14 4 0.046578
14 5 0.044713
14 6 0.043781
14 7 0.042848
14 8 0.041605
14 9 0.034975
14 10 0.026894
14 11 0.019642
14 12 0.011599
14 13 0.004931
14 15 0.002445
14 16 0.008246
14 17 0.015705
14 18 0.022957
14 19 0.031660
14 20 0.040638
14 22 0.042019
14 23 0.043401
14 24 0.044782
14 25 0.046163
14 26 0.047545
14 27 0.048926
14 29 0.050307
21 2 0.055073
21 4 0.053886
21 5 0.052699
21 6 0.051513
21 7 0.050326
21 8 0.049139
21 9 0.047953
21 10 0.046766
21 11 0.045579
21 12 0.044393
21 13 0.043206
21 15 0.042019
21 16 0.037461
21 17 0.030002
21 18 0.022336
21 19 0.013841
21 20 0.006382
21 22 0.002031
21 23 0.006796
21 24 0.014877
21 25 0.022129
21 26 0.029795
21 27 0.037047
21 29 0.042227
3 2 0.003481
3 4 0.001823
3 5 0.008661
3 6 0.016741
3 7 0.024615
3 8 0.032903
3 9 0.042197
3 10 0.043381
3 11 0.044565
3 12 0.045749
3 13 0.046933
3 15 0.048117
3 16 0.049301
3 17 0.050485
3 18 0.051669
3 19 0.052853
3 20 0.054037
3 22 0.055221
3 23 0.056405
3 24 0.057589
3 25 0.058773
3 26 0.059957
3 27 0.061141
3 29 0.062325
28 2 0.060253
28 4 0.059217
28 5 0.058181
28 6 0.057145
28 7 0.056109
28 8 0.055073
28 9 0.054037
28 10 0.053001
28 11 0.051965
28 12 0.050929
28 13 0.049893
28 15 0.048857
28 16 0.047821
28 17 0.046785
28 18 0.045749
28 19 0.044713
28 20 0.043677
28 22 0.041191
28 23 0.035596
28 24 0.027930
28 25 0.019297
28 26 0.013219
28 27 0.005138
28 29 0.002859

**Comment by halbmy** [comment]
What's wrong in the file is that the sensor list on top does contain double positions at all shot points, which are obviously also used as geophones. It does probably not hurt when displaying the data, but I guess when it comes to generating meshes. Try avoiding them in the first place.

There are significant zero-offset traveltimes that cannot be explained by any model. Try fixing these. Particularly, the first shot is probably at some negative position and not at zero. Please attach some script code or output to explain you problem further.

**Comment by viictorjs** [comment]
[test_tomo.txt](https://github.com/gimli-org/gimli/files/4503449/test_tomo.txt)

from pygimli.physics import Refraction
import matplotlib.pyplot as plt

ra = Refraction("test_tomo.txt")
ra.showData()
plt.show()

![image](https://user-images.githubusercontent.com/13758236/79752069-14bb5180-82ea-11ea-8925-64539e6d0659.png)


With the showData() method I can see that the generated travel-times curves are different from the original curves of the data, an example is that I see only four source positions instead of the actual five.

**Comment by halbmy** [comment]
Yes, obviously we do not correct for double sensor positions. That's something the user should correct for. You can test it by displacing the shot positions just a little bit.

**Comment by viictorjs** [comment]
@halbmy displacing the shot positions just a little did the trick. Thank you for your time!

Closing now.
