### ISSUE TITLE
Loading file data to invert it

### ISSUE THREAD

**Issue by mmusalhi** [gimli-org/gimli#228]
### Problem description

I am trying to load the txt file (it has the same content as koenigsee.sgt file) form my PC, but I can not invert the data or show the result.

### Your environment

**Operating system**: Windows
**Python version**: 3.6?

```python
import pygimli as pg
from pygimli.physics import Refraction

filename = pg.load("test.txt")
ra = Refraction(filename)
print(ra)


ra.showData()
ra.showVA() 

ra.invert(zWeight=0.2)
ra.showResult()

...
```

It gives me this error:

```
IndexError:  63 [0..63)
me/halbm/gimli/gimli/src/vector.h: 561		const ValueType& GIMLI::Vector<ValueType>::getVal(GIMLI::Index) const [with ValueType = double; GIMLI::Index = long long unsigned int] 
```

**Comment by florian-wagner** [comment]
Dear @mmusalhi,

the pg.load function loads many different file formats (meshes, vectors, matrices, data sets, etc.), but its auto-detect is dependent on the file suffix, i.e. the file needs to end with `.sgt` (shot, geophone, traveltime).

**Comment by mmusalhi** [comment]
Dear @florian-wagner 

I tried to load (test.sgt), but still, give me the same error



return self.getVal(int(idx))

IndexError:  63 [0..63)
me/halbm/gimli/gimli/src/vector.h: 561		const ValueType& GIMLI::Vector<ValueType>::getVal(GIMLI::Index) const [with ValueType = double; GIMLI::Index = long long unsigned int] 
[test.txt](https://github.com/gimli-org/gimli/files/4583836/test.txt)

**Comment by florian-wagner** [comment]
Can you try `ra = Refraction('test.sgt')`?

**Comment by mmusalhi** [comment]
Perfect it is working now 
thanks @florian-wagner
