### ISSUE TITLE
TravelTimeManager in pg1.1

### ISSUE THREAD

**Issue by davidkusnirak** [gimli-org/gimli#230]
### Problem description

Hello,

I was just exploring a little bit the new 1.1 release of pyGimli and apart from many great improvements I found some missing functionality in the new TravelTimeManager compared to the old Refraction manager
1) I could not call the `ttm.saveResult()` from the manager. Was the function moved somewhere else into the framework? I could not find it.

2) the Fatray (`useFatray=True`) parameter is no more present in inversion parameters. Is the fatray not supported any more, or just needs to be called other way?

cheers

### Your environment

**Operating system**: Win10/Ubuntu
**Python version**: e3.7
**pyGIMLi version**: 1.1
**Way of installation**: Conda package

**Comment by halbmy** [comment]
1. Yes, the `saveResults` function from the old `Refraction` manager was indeed forgotten when redesigning the new `TravelTimeManager` (and it is nowhere else). Of course this can be added again easily, but we consider making it a method of the super class `MethodManager`.
2. The same holds for the `fatray` option (of computing a Jacobian with the footprint of the fresnel volume, but note that this does not change the forward computation). Of course we can add it again to the new manager to use one of the two variants. Would be interesting to see whether there are notable differences. Did you experience this?

**Comment by davidkusnirak** [comment]
1. OK, no problem, I try to adopt the `saveResults` function from previous releases. I just wanted to avoid to misuse the code and to avoid some other future issues. BTW - here I'd greatly welcome if you could enhance the VTK export options, enabling storing all iterations, not just the final one, similar as it is handled by BERT.

2. well, to be honest I haven't experienced any significant impact of the `fatray ` on the inversion. Sometimes it helps to improve the coverage within the model (closing 'gaps') but in principle the final models itself, do not seem to be much different to me.

**Comment by carsten-forty2** [comment]
add `saveResult` for TTManager in dev branch. Thanks for reporting.
