### ISSUE TITLE
pygimli.viewer.mpl not found

### ISSUE THREAD

**Issue by mmusalhi** [gimli-org/gimli#231]
I am trying to import drawMesh  (from pygimli.viewer.mpl import drawMesh) 

but it gives me (Module not found error)
ModuleNotFoundError: No module named 'pygimli.viewer.mpl'

**Comment by Peruz** [comment]
They will likely provide more information, meanwhile your import works for me (pg version 1.1).
Do other modules work as expected?

cheers

**Comment by florian-wagner** [comment]
@mmusalhi What does 
``` python
import pygimli as pg
print(pg.__version__)
print(pg.__file__)
```
give? I suspect you do not have pg 1.1 installed. Try again by explicitly using `pygimli=1.1.0` in the install command: https://www.pygimli.org/installation.html

**Comment by mmusalhi** [comment]
0+unknown
C:\Users\User\Anaconda3\lib\site-packages\pygimli\__init__.py

**Comment by mmusalhi** [comment]
@florian-wagner 
I re-install it again.

import pygimli as pg
print(pg.__version__)
print(pg.__file__)


out put 
C:\Users\User\Anaconda3\lib\site-packages\pygimli\__init__.py
0+unknown

**Comment by florian-wagner** [comment]
@mmusalhi How did you reinstall it? The version number should give 1.1.0. Please follow the steps in our installation guide for Windows: https://www.pygimli.org/_downloads/pygimli_win_install_guide.pdf

**Comment by mmusalhi** [comment]
@florian-wagner 

Thanks, it is working now.

**Comment by mmusalhi** [comment]
@florian-wagner 
I followed the steps your installation guide for Windows, (from pygimli.viewer.mpl import drawMesh) is working fine if I put Application (pg) in Anaconda but (drawTravelTimeData function) gives me an error 
' vals = data('t')

TypeError: 'NoneType' object is not callable '

so I have to put application as ( base root)

![error](https://user-images.githubusercontent.com/41855091/82263145-55eb6380-9973-11ea-8125-80bc3b3a4bee.png)
