### ISSUE TITLE
Refraction Result to pyqtgraph

### ISSUE THREAD

**Issue by mmusalhi** [gimli-org/gimli#233]
Can we plot refraction inversion into pyqtgraph ?

![out put](https://user-images.githubusercontent.com/41855091/82241184-bdda8380-994c-11ea-83fb-3088fe1653fe.png)

**Comment by florian-wagner** [comment]
Currently we have no viewing interface to pyqtgraph, but one reason for restructuring was also to have a place for new plotting backends.

For now we have

- `pg.viewer.mpl`: Matplotlib
- `pg.viewer.pv`: PyVista

But this coud be extended with `pg.viewer.bokeh`, `pg.viewer.pyqtgraph`, `pg.viewer.plotly` and others in the future. It's just a matter of time and resources. Meaning that we are currently happy with mpl and pv, but welcome and support pull requests towards the support of alternative backends.
