### ISSUE TITLE
Trivel-time / distance plot

### ISSUE THREAD

**Issue by mmusalhi** [gimli-org/gimli#234]
I just updated pygimli to 1.1.0, it is great and powerful, but I can not find some features like (Trivel-time / distance plot)

![PHOTO-2020-05-08-01-59-23](https://user-images.githubusercontent.com/41855091/82359815-78d05300-9a19-11ea-8c1c-d71152eae671.jpg)

**Comment by florian-wagner** [comment]
https://www.pygimli.org/pygimliapi/_generated/pygimli.physics.traveltime.html?highlight=drawtraveltime#drawtraveltimedata

**Comment by mmusalhi** [comment]
@florian-wagner 
I am trying to apply ```drawVA``` function as I understand from the function description.


```python
ra = TravelTimeManager("inv.txt")
ra.invert()
fig, mpl =ra.showData()

data=pg.load("inv.txt")
pg.physics.traveltime.drawVA(fig.axes ,data)

...
```

output error 
```
RuntimeError: C:/msys64/home/halbm/gimli/gimli/core/src/datacontainer.cpp: 670		
const IndexArray GIMLI::DataContainer::id(const string&) const  token: g is not an index list: SensorIdx: a b m n  Data: err g i ip iperr k r rhoa s t u valid 
...
```

**Comment by halbmy** [comment]
What you are looking for is the function `drawFirstPicks`:
```
fig, ax = pg.plt.subplots()
pg.physics.traveltime.drawFirstPicks(ax, data)
```
(e.g. for the Koenigsee example)
![image](https://user-images.githubusercontent.com/7136401/82416172-e57b3a00-9a79-11ea-9f27-2cfb5342a432.png)

**Comment by mmusalhi** [comment]
@halbmy 
The problem now I can't load my own data using `data =pg.load("inv.txt")` , I have to use `data =TravelTimeManager("inv.txt")`

**Comment by florian-wagner** [comment]
`data = pg.DataContainer("inv.txt", "s g")`

**Comment by halbmy** [comment]
Florian is right for correct loading of data, one needs to register the shot and geophone fields as sensor indices, i.e. integers pointing into the list of sensor positions above. This can be done by the additional "s g" command. `pg.load()` just checks the file extension and if it is `sgt` then it will do the same.

**Comment by mmusalhi** [comment]
I got it, thanks for your clarification and support.

**Comment by carsten-forty2** [comment]
Also a little note just for the archive. You can also try the specialiced load function that try autodetect between the, so far known, tt importer functions:

```
import pygimli.physics.traveltime
data = traveltime.load('inv.txt')
```
