### ISSUE TITLE
New to Git Hub: Issues with Update from 1.0 to 1.1

### ISSUE THREAD

**Issue by bflinchum** [gimli-org/gimli#235]
### Thank You

First let commend you on this amazing package! I have been using the refraction section for about 6-8 months now with great results. Hopefully it sneaks through review but I have published a paper in HESS using this code ([discussion paper here](https://www.hydrol-earth-syst-sci-discuss.net/hess-2019-576/)). I don't know how much I can contribute in terms of writing code but maybe I can provide some scripts and data for working examples.

### Issues with Update

1. There appears to be a new dependency in the new version. To successfully compile the update I had to download a new package: `pyplusplus`. Luckily the errors spit-out during compilation were strong enough for me to figure it out. Solution for me was simply:
`sudo port install py37-pyplusplus` and then re-compile.

2. You seem to have changed how you load error weights into the model. Previously I was using:
`ra.error.load('pickingErrors.txt')` where `ra` was created by` ra = Refraction(filename)` and refraction is from` pygimli.physics`.  My file is a 1D vector of errors (in ms) corresponding to each pick. This method does not exist any more. 

- In version 1.1 how do I assign errors to weight the inversion scheme? The inversion runs because it defaults to a 3% error on all picks.

-  It also seems like there has been a shift in units. Instead of expressing error in ms does it have to be expressed as a percent (0.03 = 3%) now? 

3. Is there a way to mask the final model by rays again? I loved that feature! I have tried to track it down through the code and get as far as `drawModel`.  The information is clearly still there because I can use `show` to see ray coverage.

4. Where does the rms value live in the data structure now? I used to call `ra.inv.absrms()` to get the RMS value. Now the print results is showing it in %? 

5. I agree with the last post, what happened to the `ra.saveResult()` method? I don't think I am as "code" savy as him to jimmy rig a previous version. I really liked having the .vtk files outputted to a a directory :) 

**Operating system**: Mac
**Python version**: 3.7 (I run the code through Spyder interface)
**pyGIMLi version**: 1.1.0 (updating from 1.0.12)
**Way of installation**: Compilation from source. I used Macports instead of Brew. I can provide instructions later if wanted.

### Code I am using
I have attached the Python Script and data that I am using. It still spits out errors and I am just trying to fit an error function of increasing error with offset.
[GimliInversion.zip](https://github.com/gimli-org/gimli/files/4668548/GimliInversion.zip)

**Comment by florian-wagner** [comment]
Hi Brady,

thanks a lot for your feedback! Much appreciated. We would also be interested in the compilation instructions using Brew. If you want, you can replace the old ones directly here: https://github.com/gimli-org/gimli/edit/dev/doc/BUILD_MAC.rst (uses RestructuredText Markup: https://github.com/ralsina/rst-cheatsheet/blob/master/rst-cheatsheet.rst). We encourage most users to install via conda, which is a simple one-liner, but your instructions are likely to be of help for power users and potential contributors just like yourself. And thanks for the referece to your upcoming HESS paper. We will make sure to add it to the new database: https://www.pygimli.org/publist.html

With regard to your points (@halbmy & @carsten-forty2, feel free to add):

1. Pyplusplus was always a dependency, but the build scripts downloaded that package automagically. Glad to hear that the brew version worked out for you.
2. Yes, we also have an ongoing discussion on how to store errors internally. In particular when you move to joint inversion and deal with different methods where the error is defined either in absolute or relative terms. The TravelTime Manager has a `checkError` method which sheds some light onto how it handled at the moment:

``` python
    def checkError(self, err, dataVals):
        """Return relative error."""
        if isinstance(err, pg.DataContainer):
            if not err.haveData('err'):
                pg.error('DataContainer has no "err" values. Fallback to 3%')
                return np.ones(err.size()) * 0.03
            return err['err'] / dataVals
```

So, if your dataContainer has a column named `err` with the **absolute** errors (which will be transformed into relative ones internally), than you're good to go. You could do something like this

``` python
from pygimli.physics.traveltime import load

filename ="NN_2014_0707_1_gimliInput.txt"
data = load(filename)

print(data)

#Search for Recipricals to build errors
srcs = np.array(data('s'))
geos = np.array(data('g'))
tts = np.array(data('t'))
xLocs = 0*tts
locs = np.array(data.sensorPositions())
index = 0
recips = 0*tts
offsets = 0*tts

#Assign a distance weight error to remaining values
indZeros = np.where(recips==0)[0]

# 235x = 8 ms
#Slope = 8/235 Puts 7 ms at maximum offset
srcs = np.array(data('s'))
geos = np.array(data('g'))
tts = np.array(data('t'))
for i in range(0,len(indZeros)):
    srcInd = int(srcs[indZeros[i]])
    geoInd = int(geos[indZeros[i]])
    offset = np.abs(locs[srcInd,0] - locs[geoInd,0])
    #print(offset) 
    recips[indZeros[i]] = offset*0.005/240 + 0.0005
np.savetxt('pickingErrors.txt',recips,fmt='%10.6f')

data["err"] = recips
print(data)

ra = TravelTimeManager(data)

....
```

3. Hm, did we deactivate that by default in the `showResult` method? Seems like it.

But you could do it like this:

``` python
fig, ax = plt.subplots(figsize=(14,8))
pg.show(ra.paraDomain, ra.velocity, coverage=ra.standardizedCoverage(), label=pg.unit("vel"), ax=ax)
pg.viewer.mpl.drawSensors(ax, data.sensorPositions(), diam=1, color="w")
```
![vel](https://user-images.githubusercontent.com/2799008/82681292-de0c8a00-9c4d-11ea-8b2c-b5e851866336.png)

4. Thank you for pointing that out. This is very hidden and not well documented at the moment. 
``` python
ra.inv.chi2() # error-weighted chi-square error
ra.inv.relrms() # relative RMS
ra.inv._inv.absrms() # absolute RMS (shouldn't be that hidden)
```
5. Yes, we will discuss a good way to store and load results and bring that method back in 1.2. For now you would have to do something like:

``` python
ra.paraDomain.save(name + "paraDomain.bms")
ra.paraDomain.addData("Vel", ra.velocity)
ra.paraDomain.addData("Cov", ra.coverage())
ra.paraDomain.exportVTK(name + "result.vtk")
```
Cheers
Florian

P.S.: We need more issues like that! Thanks.

**Comment by carsten-forty2** [comment]
I added `mgr.saveResult(..)` in dev branch. We simple forgot it to migrate. Thanks for pointing out.

If you compile your own, it is simple to switch to the dev branch.

Added `ra.inv.absrms()` as interface, let us know you miss more functionality.

Cheers,
Carsten

**Comment by bflinchum** [comment]
First and foremost thank you so much for the quick and helpful replies! 

@carsten-forty2. This is a really dumb question but I am new to git. I switched branches by getting to the directory where Gimli exists and then do the following:
`git checkout dev` 
`git pull` -- I can see some things have changes.
then I recompile. 

Is this how the flow is supposed to go? I think it worked because I now have the method saveResults() but get a new error: `NameError: name 'createPaths' is not defined` Since @florian-wagner has given me some workaround code above this is really not an issue anymore just though I would share my error.

Second, sorry guys I am definitely a user not a programmer.

@florian-wagner Thank you for this script those got everything working for me :)

Cheer,
Brady

**Comment by carsten-forty2** [comment]
oh yes .. sorry .. I fixed it on dev. That was a last-second-change-typo. Thanks for mention. The chance for such little bugs is a little higher on dev ;)

Little side note. You only need to recompile if you see changes in *.h or *.cpp files. For the latter a `make pg` is sufficient, while for the first a full rebuild needs to be done.

Cheers,
Carsten

**Comment by bflinchum** [comment]
@carsten-forty2  thank you for that tip because recompilation takes a long time! Like I said I am pretty new to Git and Python as well.
