### ISSUE TITLE
how to set b as a velocity field in the solveFiniteElements module

### ISSUE THREAD

**Issue by siam2015** [gimli-org/gimli#237]
### Problem description
i firstly simulate a darcy flow by using the _solveFiniteElements_function, and obtained the velocity vel = -pg.solver.grad(mesh,p)*np.asarray([K,K,K]).T. Now i would like to set this velocity field as an advection term in another PDE. Then i employed the solveFiniteElements function again and set the b=vel. it arises an error:
  File "D:\Anaconda3\envs\pg\lib\site-packages\pygimli\solver\solver.py", line 2072, in solveFiniteElements
    if b is not None and b != 0:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Could you give me some suggestions to solve this problem?
### Your environment

**Operating system**: Windows
**Python version**: 3.6?
**pyGIMLi version**: pygimli 1.1
**Way of installation**:  Conda package

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
import pygimli as pg
...
```

### Expected behavior

Tell us what should happen or what you want to achieve.

### Actual behavior

Tell us what happens instead and/or provide the output of your script.

```
Paste output here.
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by carsten-forty2** [comment]
The simulation of advection is currently only supported with the Finite Volume solver. See this example:
https://www.pygimli.org/_examples_auto/5_misc/plot_hydrogeophysical_modeling.html#sphx-glr-examples-auto-5-misc-plot-hydrogeophysical-modeling-py

We rework the finite element solver for increased usability .. but this will take some time.

**Comment by siam2015** [comment]
Thank you for your comments. I have tried to use the Finite column solver, but the boundary conditions is limited. I want to set a Dirichlet boundary on a cell. It doesn’t seem to be supported.

**Comment by siam2015** [comment]
in the Finite Volume solver, some boundary condition is not available
– bc : Boundary Conditions dictionary, see pg.solver
– uB : Dirichlet boundary conditions DEPRECATED
– duB : Neumann boundary conditions DEPRECATED
could you give me some example to set a Dirichlet boundary in this solver?

**Comment by carsten-forty2** [comment]
We changed the boundary conditions interface into a dictionary, same like for the Finite Element solver (see `pygimli.solver.solveFiniteElements`. 
e.g.
`bc={'Dirichlet': {boundaryMarker: Value}}`

**Comment by siam2015** [comment]
Based on the example you show me, I modified the f=S to a Dirichlet boundary condition (bc={"Dirichlet":{sourceCell.id():10}}) in the solverFiniteVolume module. But it seems not to work. 

import numpy as np
import pygimli as pg
import pygimli.meshtools as mt



world = mt.createWorld(start=[-20,0], end=[20,-16], layers=[-2, -8], 
                       worldMarker=False)
block = mt.createRectangle(start=[-6,-3.5], end=[6,-6], marker=4,
                           boundaryMarker=10, area=0.1)

geom = world + block
pg.show(geom, boundaryMarker=True)

mesh = mt.createMesh(geom, quality=32, area=0.2, smooth=[1,10])
pg.show(mesh)

kMap = [[1,1e-8],[2,5e-3],[3,1e-4],[4,8e-4]]

K = pg.solver.parseMapToCellArray(kMap, mesh)

pg.show(mesh,data=K,label="Hydraulic conductivity $K$ in m$/$s", cMin=1e-5,
        cMax=1e-2, logScale=True, grid=True)

left = 0.75
right = 0
pBound = {"Dirichlet":{1:left,2:left,3:left,5:right,6:right,7:right}}

p = pg.solver.solveFiniteElements(mesh, a=K, bc=pBound)
vel = -pg.solver.grad(mesh,p)*np.asarray([K,K,K]).T

ax,_ = pg.show(mesh, data=pg.abs(vel)*1000,cMin=0.05,cMax=0.15,
               label = "Velocity $v$ in mm$/$s", cMap="YlGnBu", hold=True)
ax,_ = pg.show(mesh, data=vel, ax=ax, color='k', linewidth=0.1, dropTol=1e-5,
              hold=True)

S = pg.Vector(mesh.cellCount(),0)

sourceCell = mesh.findCell([-19.1,-5.6])
S[sourceCell.id()] = 1.0/sourceCell.size()

t = pg.utils.grange(0,6*24*3600,n=800)

dispersion = pg.abs(vel)*1e-5

veln = mt.cellDataToNodeData(mesh, vel)
c = pg.solver.solveFiniteVolume(mesh, a=dispersion, f=0, 
                                 bc={"Dirichlet":{sourceCell.id():10}}, 
                                 vel=veln, times=t,
                                 scheme='PS', verbose=0)

for ci in c[1:][::200]:
    pg.show(mesh, data=ci*0.001, cMap="magma_r",
            label="concentration c in $g/l$")

**Comment by carsten-forty2** [comment]
Dirichlet boundary conditions should be set for the nodes on boundary elements .. if you want a source term cell vise .. you need to stay with the right hand side `f` argument

**Comment by siam2015** [comment]
Thank you! As your suggestion, I have tried to use the same Dirichlet boundary as in the solverFiniteElement module, e.g. {"Dirichlet":{2:0.75}. But it still causes an error:
ValueError: setting an array element with a sequence.
If there is a constant concentration (Dirichlet condition) on the boundary and no source in the study area, could you help to give some suggestions on how to assign this boundary in the solverFiniteVolume module? looking forward to your comments.

**Comment by siam2015** [comment]
Thank you for your reply!
