### ISSUE TITLE
Is it possible to use the c++ core in c++ programming

### ISSUE THREAD

**Issue by BaderTalal** [gimli-org/gimli#238]
Hi,
I wonder if it is possible to use Gimli core in c++ programming, 
I want to try Gimli in my c++ programming, 

right now I am developing my experience in c++ Qt and VTK for geophysical data processing, if I can add Gimli to the chain will be great.

thanks and regards
Talal

**Comment by carsten-forty2** [comment]
gimli was orginally designed for this purpose but we decided to move the user interface and most of the glue that holds to parts together over to to python. Of course you can try and all depends on your needs, but the major parts for any future development will be in python.

**Comment by carsten-forty2** [comment]
considered as answered
