### ISSUE TITLE
triangle build on MacOSX

### ISSUE THREAD

**Issue by florian-wagner** [gimli-org/gimli#24]
When building triangle via the thirdparty scripts on MacOSX, the following error occurs:
```
clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'
./triangle.c:354:10: fatal error: 'fpu_control.h' file not found
#include <fpu_control.h>
         ^
1 error generated.
make: *** [triangle.o] Error 1
```
I think we need a smilar patch like the one for WIN, where the -DLINUX flag is removed from the Makefile.

**Comment by lufrodriguezca** [comment]
Hi 

I want to know if you could solve it, I have the same problem here.

Thanks,
Luisa

**Comment by lufrodriguezca** [comment]
Problem solved, look at: https://groups.google.com/forum/#!topic/mainsar/A3PAhKPPrq8

**Comment by carsten-forty2** [comment]
thanks for reporting ..  should be solved now
