### ISSUE TITLE
[Question] ERT simulate - values in the data container 

### ISSUE THREAD

**Issue by jcombes738** [gimli-org/gimli#240]
### Your environment
**Operating system**: Windows
**Python version**: 3.7.6
**pyGIMLi version**: 1.1.0
**Way of installation**: Conda package

### Problem description
Hello everyone,
I have a couple of questions concerning ERT simulate using pybert ERTManager. I am currently working on the forward modelling of 2D simple cases (cavities in a homogeneous model). As for now, I am focusing on the relationship between the potential u and the error err obtained after the simulation. To do so, I have modified the example available: 2D ERT modeling and inversion. 

In the following code, my point is to extract the potential u and the error to plot it. But when I run: `data= ert.simulate(mesh, res=rhomap, scheme=scheme, noiseAbs=absolute_error, noiseLevel=relative_error)`
I only get in my data container the columns: err, rhoa, k, valid. The others column are filled with 0 (and so my u column). To retrieve the u values, the only solution I found is to use `CalcOnly=True`, but in this case, I can only retrieve u (rhoa, k, err, are filled with 0). 
My code is: 
``` import os
import pybert as pb
import pygimli as pg
import pygimli.meshtools as mt 
from pygimli.meshtools import polytools as plc
from scipy.stats import norm 
import matplotlib.pyplot as plt 
import numpy as np  

########################### GEOMETRY AND ACQUISITION SCHEME #################################
#Here I create my geometry, acquisition scheme, my mesh refinement and my model
world = mt.createWorld(start=[-50, 0], end=[200, -200],marker=1,   
                       worldMarker=True)


block1 = mt.createCircle(pos=[60, -7.5], radius=5.5, marker=2, boundaryMarker=10, #cavité intérieure = marker 3
                        area=1)
geom = mt.mergePLC([world, block1])

# Create a Dipole Dipole ('dd'), schlumberger ('slm'), Wenner a ('wa')
#Wenner b ('wb'), Pole pole ('pp'), Pole dipole ('pd'),Half Wenner ('hw'),
#Gradient ('gr') measuring scheme with 64 electrodes.

schemas='slm'
scheme = pb.createData(elecs=pg.utils.grange(start=0, end=126, n=64),
                       schemeName=schemas,inverse=False)

for points in scheme.sensorPositions():
    geom.createNode(points)
    geom.createNode(points + pg.RVector3(0, -0.1)) #convention standard = 10% espacement
 
mesh = mt.createMesh(geom, quality=32)

rhomap = [[1, 1000.],
          [2, 300000.]]

############################FORWARD MODELLING ##############################
# Initialize the ERTManager
ert = pb.ERTManager()

absolute_error=0.001 #10 mV = noiseAbs= absolute error voltage in V
relative_error=0.03 #3% = environnement noise

# to get the u colum -> CalcOnly=True
data= ert.simulate(mesh, res=rhomap, scheme=scheme, noiseAbs=absolute_error, noiseLevel=relative_error, calcOnly=True) 
u=np.array(data('u')) # I save u values in a array

#to get rhoa, k, err columns -> calcOnly=False
data= ert.simulate(mesh, res=rhomap, scheme=scheme, noiseAbs=absolute_error, noiseLevel=relative_error, calcOnly=False) 
#I save values in array
error=np.array(data('err'))
rhoa=np.array(data('rhoa'))
k=np.array(data('k'))
```

So my first question is: **does an other solution exist to retrieve at the same time, u and rhoa, k, err ?** 

Moreover, I also use an other way to retrieve u from rhoa, k and i: 
u =i * rhoa/k (with i = 1A)
Then I want to see the discrepancy between `u=np.array(data('u'))` originated from the data container (ert.simulate) and `u_formula = np.array(np.abs(data('rhoa') / data('k') * i))` retrieved with the formula. 
The code I use is: 
```#Second method: I retrieve u and err with formula
#and I calculate deviation with values contained in the data container
i=1  #by default pygimli use a current=1A in ert.simulate
u_formula = np.array(np.abs(data('rhoa') / data('k') * i))
dev_u_mean=np.mean((np.array((u-u_formula)/u)))*100 #mean deviation between u (data container) and u (formula)

error_formula=np.array((absolute_error/u_formula)+relative_error)
dev_error_mean=np.mean((np.array((error-error_formula)/error)))*100 #mean deviation between err (data container) and err (formula)

#plot of the deviation between u and u_formula
plt.figure()
plt.scatter(u, u_formula, c=((u-u_formula)/u)*100, cmap="RdBu_r", vmin=-10, vmax=10, edgecolor="None" )
plt.xlabel("Potential U calculte with ert.simulate (V)")
plt.ylabel("Potential U calculate from the formula i*rhoa/k (V)")
cbar=plt.colorbar()
cbar.set_label("Deviation")
cbar.set_clim(-10, 10)
plt.grid()
```
The result I get is the following chart with deviation = `c=((u-u_formula)/u)*100`
![image](https://user-images.githubusercontent.com/67000311/84773480-c1f5d180-afdc-11ea-851f-3f720db46eba.png)

So my 2nd question is: **why do I obtain a such important discrepancy between the two u values ?** The maximum deviation being approximately equal to +/-10%. It seems to be that the deviation is more important at high u values. 

My last question is about the i value. Because, as for u, the i colum is always filled with 0. But I saw that, by default, the i value is set to 1A. **Is there a way to modify that and to choose the i value ?** 

I put in attachement my code in zip format. 
Thanks in advance for your answer. 
Best regards, 
Jeanne. 

[Modelling.zip](https://github.com/gimli-org/gimli/files/4786598/Modelling.zip)

**Comment by halbmy** [comment]
The only discrepancy between the u values comes from the noise put on the data. If you set both noise values to zero, then the u values are identical. Note that the normal simulate (with calcOnly=False) does add noise, whereas calcOnly=True does not.

Regarding the current, it can be easily scaled after the simulation, it can be passed by `ert.simulate(..., absoluteCurrent=...)`

**Comment by jcombes738** [comment]
Thanks a lot @halbmy for your answer! 
Just a last question to be sure I understand. By using `CalcOnly=False`, it simulates by adding noise, but u values are not save in the data container? Thus, the only mean to retrieve them is to use the formula: u =i * rhoa/k  ?
Thanks again for your help.
Regards
Jeanne

**Comment by halbmy** [comment]
Yes, the u values are not stored in the data container but they can be easily computed. And the noise is put only on the apparent resistivity, that's just a convention...

**Comment by jcombes738** [comment]
Ok I understand, thanks a lot for your help!
Best regards
Jeanne
