### ISSUE TITLE
Missing Method in Update to 1.1

### ISSUE THREAD

**Issue by bflinchum** [gimli-org/gimli#244]
### Problem description

I upgraded to 1.1 and I am having issues with an old script.

I have written a bootstrapping algorithm that randomly removes some percentage of my travel-time picks. I run the inversion and store the values using the "saveResult" method. I then read in all the velocity values (from the "velocity.vector" file) and average the velocities at each mesh location. For the final result I run the inversion module through the averaged model to get the rays, RMS, and Chi^2 value. I used to achieve this with the following lines:

ra.inv.setModel(1./avgVel)
ra.invert(lam=400, maxIter=0,zWeight=0.1,useGradient=False)

After the update I am the ra.inv is missing the method "setModel". My guess is it has to do with the lack of dataContainer so that the object doesn't actually know the mesh size? In this case my variable avgVel is a 1D array of values that is the length of the total number of cells that I read in from the saveVTK.

I assume this is an easy fix but can't find the documentation. Any help would be greatly appreciated.

Operating system: Mac
Python version: 3.7 (I run the code through Spyder interface)
pyGIMLi version: 1.1.0 (updating from 1.0.12)
Way of installation: Compilation from source. I used Macports instead of Brew. I can provide instructions later if wanted.

**Operating system**: Mac
**Python version**: 3.7
**pyGIMLi version**: 1.1.0 (updating from 1.0.12) I am on the devel branch (though my last pull was a while ago...)
**Way of installation**: Compilation from source. I used Macports instead of Brew. I can provide instructions later if wanted.

**Comment by carsten-forty2** [comment]
Can't test it right now, but you can try the following ways:

Set the model vector for some post processing stuff:
`re.inv.model = 1./avgVel`

Or set the starting model for the next inversion run:
`ra.inv.setStartModel(1./avgVel)`

which should equivalent to:

`ra.invert(lam=400, maxIter=0,zWeight=0.1,useGradient=False, startmodel=1./avgVel)`

For your specific needs I would recommend something like:

```
#This will only work when 'ra' has been configured by a prior inversion run.
myModel = 1./avgVel

response = ra.fop.response(myModel)
chi2 = ra.chi2(response)
relrms = pg.utils.rrms(ra.dataVals, response) * 100.
absrms = pg.utils.rms(ra.dataVals, response)
ra.showRayPaths(model=myModel)
# ra.drawRayPaths(ax=anyAxe, model=myModel)
ra.showCoverage() ## will work after raypath was has been calculated
```


Sorry for the inconvenience due to the api change. I hope we can avoid them in the future but sometimes things need to be changed.

Bests,
Carsten

**Comment by bflinchum** [comment]
Hey @carsten-forty2,

No worries about the update. I am just super happy that you have a dedicated team and the code is being updated. I know that this stuff happens and its all for the improvement of the code! I just really appreciate you getting back to me so quickly.

So there is still an issue. I think that your fix will work, that is I see the logic in it and drilled all the way to the general `invert` method. There is something not working with the `ra.invert()` method. I noticed this before but didn't think anything of it. 

I re-pulled the devel (7/3/2020) git repository and recompiled and then tried again. These are still the things I am finding. How do I tell you what branch I am on? 

During my script I execute the following (is there an easy way to share my data and script on this forum?):
```
# THIS IS ALL WITHIN A LOOP. The example here is for one iteration of the bootstrap

start = time.time()
fileName = str(path2Runs+'/model_'+str(i+1))
resamplePicks(filename,errFile,fract2Rmv,resampPickFileName,resampErrFileName) #This is the bootstrapping function that removes picks.
data = load('resampledPicks.txt') #read in the resampled pygimli input file
recips = np.loadtxt('resampledErrors.txt') #read int he corresponding errors (from reciprocals)
ra = TravelTimeManager(data)
data['err'] = recips

# mesh was created earlier in the script using. I could have created
# mesh = ra.createMesh(data=ra.data,paraDepth=180)

startVel = 300
ra.invert(data=data,mesh=mesh,lam=400,maxIter=10,zWeight=0.1,useGradient=True,vtop=startVel,vbottom=4500)
velModels[:,i] = np.array(ra.velocity)
ra.saveResult(folder=fileName)
end = time.time()
print("\n\nCompleted Inversion {0:2d} of {1:2d}".format(i+1,int(nRuns)))
s1 = "Time Elapse (min): " + str("{:0.2f}".format((end - start)/60)) + " min\m"
s2 = "Chi^2 = " + str("{:0.4f}".format(ra.inv.chi2())) + "\n"
s3 = "RMS = " + str("{:0.4f}".format(ra.inv.absrms())) + " s\n\n\n"
print(s1)
print(s2)
print(s3)
```

What I noticed when I turned verbose on is that the invert command is not actually taking my top and bottom velocity. It's defaulting to 500 and 5000 m/s. Below is the output from the inversion of one of the files:
```
03/07/20 - 12:08:15 - pyGIMLi - INFO - Found 1 regions.
03/07/20 - 12:08:15 - pyGIMLi - INFO - Found 1 regions.
03/07/20 - 12:08:15 - pyGIMLi - INFO - Creating forward mesh from region infos.
03/07/20 - 12:08:15 - pyGIMLi - INFO - Creating forward mesh from region infos.
03/07/20 - 12:08:15 - pyGIMLi - INFO - Creating refined mesh (secnodes: 2) to solve forward task.
03/07/20 - 12:08:15 - pyGIMLi - INFO - Creating refined mesh (secnodes: 2) to solve forward task.
03/07/20 - 12:08:15 - pyGIMLi - INFO - Create gradient starting model. 500: 5000
03/07/20 - 12:08:15 - pyGIMLi - INFO - Create gradient starting model. 500: 5000
03/07/20 - 12:08:15 - pyGIMLi - INFO - Created startmodel from forward operator: [0.00100925 0.0016548  0.00182533 ... 0.00028523 0.0002658  0.00024952]
03/07/20 - 12:08:15 - pyGIMLi - INFO - Created startmodel from forward operator: [0.00100925 0.0016548  0.00182533 ... 0.00028523 0.0002658  0.00024952]


Completed Inversion  1 of  2
Time Elapse (min): 6.02 min\m
Chi^2 = 1.2716
RMS = 0.0032 s

```
**_Notice the 500: 5000??_** If the input arguments were used it should be 300 and 4500.

Thus when I try your fix weird things happen if I change the boolean. If I remove the `useGradient` flag then the inversion uses a constant velocity starting model; it does NOT take the argument of my starting model. 

I don't quite understand what **kwargs does but it appears that setting the flag `startmodel=1./avgVel` is having no effect on the inversion. It also means art I don't have rays traced through the final model.

**Comment by carsten-forty2** [comment]
Please try to "camelShape" the argument names, i.e. `vTop` instead of `vtop` and `vBottom` instead of `vbottom`. 

Some (not yet all) arguments can be found here and the links therein:
https://www.pygimli.org/pygimliapi/_generated/pygimli.physics.traveltime.html?highlight=invert#pygimli.physics.traveltime.TravelTimeManager.invert

Same naming rule is for `startModel` (. o Ops ..  I wrote it wrong in my message above .. was typed here without testing .. sorry)

`kwargs` is just a dictionary (name=value) of (k)e(w)ord (arg)ument(s) .. it is just for the lazy devs to keep the function calls short. We don't have a good idea how to handle wrong argument names .. so the case of misspelled args is not catched at the moment. 
`**kwrags` just unrolls all items of the dict inplace.

**Comment by bflinchum** [comment]
@carsten-forty2 that's the fix. WIth the **kwrargs how do I drill down to find it? A little case would have been a hard thing to find. I will try camel case always now. Once again thanks so much for your quick reply!
