### ISSUE TITLE
3D PLC within cube for ERT Invert 

### ISSUE THREAD

**Issue by anzhijiang** [gimli-org/gimli#245]
### Problem description
I made some changes to the '3D modeling in a closed geometry' example, and during the inversion, I found that the number of cells obtained was much less than during the simulate. So get the poor result.  
The command 'saveResult' can not work.

### Your environment

**Operating system**: Windows
**Python version**: 3.7
**pyGIMLi version**:1.1.0+31.g47c8d810
**Way of installation**:  Conda package

### Steps to reproduce

```python
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics.ert import simulate as simulateERT
import pygimli.physics.ert as ert

plc = mt.createCube(size=[12, 12, 5], pos=[6, 6, -2.5],boundaryMarker=1)
filename = "inlinedd.shm" 
name = "inlinedd"  
shm = pg.DataContainerERT(filename)
for s in shm.sensors():
      plc.createNode(s, marker=-99)
plc.createNode([6, 12, -2.5], marker=-999)
plc.createNode([6, 6 , -5], marker=-1000)
for s in plc.positions(pg.find(plc.nodeMarkers() == -99)):
      plc.createNode(s - [0.0, 0.0, 1e-3/2])
plc.createNode([6, 12, -2.5 - 1e-3/2])
cube = mt.createCube(size=[4, 4, 2], pos=[6, 6,-2], marker=2)  
geom = plc + cube
mesh = mt.createMesh(geom,quality=34)
res = [[1, 10.0], [2, 100.0]]
data = simulateERT(mesh, res=res, scheme=shm, sr=False,                                       
                   verbose=True, noiseLevel=1, noiseAbs=1e-6,seed=1337)
data.remove(data['rhoa'] < 0)
data.save(name+'.dat','a b m n rhoa k u i err')
mgr=ert.ERTManager()
inv=mgr.invert(data=data,mesh=mesh,lam=20, verbose=True)
invmesh=mgr.paraDomain
invmesh['result']=inv
invmesh.exportVTK('out.vtk') 
mgr.saveResult("my-results")
```

### Expected behavior
 The invert result number of cells is as same as simulate mesh.

### Actual behavior
Found 2 regions.
Region with smallest marker set to background (marker=1)
Creating forward mesh from region infos.
<class 'pygimli.physics.ert.ert.ERTManager'>.applyMesh(D:\software\anaconda3\envs\pg\lib\site-packages\pygimli\frameworks\methodManager.py:647) : Mesh: Nodes: 5575 Cells: 13442 Boundaries: 32174
Creating refined mesh (H2) to solve forward task.
Starting inversion.
Set default startmodel to median(data values)=10.747049507099657
Created startmodel from forward operator: 60            (I think something wrong here.)
AttributeError: 'ERTManager' object has no attribute 'saveResult'
```


```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
The reason for the behaviour is displayed in the message 
`Region with smallest marker set to background (marker=1)`
which is an automatism for typical ERT inversions with a background region around the inversion region, i.e. the region 1 is taken as background.

As you want to resolve the added cube it should not be present in the mesh as a different (decoupled) region. Actually you should create a new mesh for inversion based only on `plc` and not `geom`. The of course the number of cells will be different, but it is an inverse crime otherwise.

If you do want to use the same mesh, just set all cell markers to the same value before inversion:
```Python
for cell in mesh.cells():
    cell.setMarker(1)
```

**Comment by anzhijiang** [comment]
Thanks for your reply. I try to create the plc mesh and set all cell markers to the same value. Both of these ways can resolve it well.
The resolve cell number depends on my mesh which set before. 
Another question is the command 'saveResult' can not work.

**Comment by halbmy** [comment]
The missing function `saveResult` was added a month ago (aa28b84da3302819e0df26a19c7bb89ea1dab6d8) but you still have the release pyGIMLi v1.1 which is two months old. You could 
1. write your own function based on the code in the commit
2. checkout pygimli via git and switch to the git version (copy core binaries from conda version)
3. wait for the next release
I consider this issue finished. Thanks for reporting.
