### ISSUE TITLE
ERT inversion with geostatistical regularization

### ISSUE THREAD

**Issue by kaufmanno** [gimli-org/gimli#246]
### Problem description

I am trying to invert an ert dataset with geostatistical regularization. I keep getting an error message and I can not figure out where it comes from. I am actually not sure that I am using the ERTManager in the right way. 
Any help is appreciated ;-)

Olivier

### Your environment

**Operating system**: Ubuntu 18.04LTS
**Python version**: 3.7.6
**pyGIMLi version**: 1.1.0+0.g47c8d810 (with local changes)
**Way of installation**: Conda package

### Steps to reproduce
Here is a short script that produces the encountered error.

```python
import pygimli as pg

data=pg.DataContainerERT('Eugies_ERT.dat')
ert = pg.physics.ERTManager(sr=False, useBert=True, verbose=True, debug=False)
ert.applyMesh(ert.createMesh(data=data, paraDX=0.5, maxCellArea=100.0), ignoreRegionManager=False)
C = pg.matrix.GeostatisticConstraintsMatrix(mesh=ert.fop.mesh(), I=[25, 5], dip=-25)
ert.fop.setConstraints(C)
ert.invert(data=data, lam=10)
ert.showResultAndFit(cMap='jet')
```

### Expected behavior

I was expecting that ert.invert would run without returning this error message...

### Actual behavior
an error message is thrown by ert.invert :

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-4c1e12866b44> in <module>
----> 1 ert.invert(data=data, lam=10)
      2 ert.showResultAndFit(cMap='jet')

~/miniconda3/envs/pg/lib/python3.7/site-packages/pygimli/frameworks/methodManager.py in invert(self, data, mesh, zWeight, startModel, **kwargs)
    695         errorVals = self._ensureError(self.fop.data, dataVals)
    696 
--> 697         if self.fop.mesh() is None:
    698             pg.critical('Please provide a mesh')
    699         # inversion will call this itsself as default behaviour

~/miniconda3/envs/pg/lib/python3.7/site-packages/pygimli/frameworks/modelling.py in mesh(self)
    520         """"""
    521         if self._regionManagerInUse and self._regionChanged:
--> 522             self.createFwdMesh_()
    523 
    524         return super(Modelling, self).mesh()

~/miniconda3/envs/pg/lib/python3.7/site-packages/pygimli/frameworks/modelling.py in createFwdMesh_(self)
    515         self.setMeshPost(m)
    516         self._regionChanged = False
--> 517         super(Modelling, self).setMesh(m, ignoreRegionManager=True)
    518 
    519     def mesh(self):
RuntimeError: /home/wagner/miniconda3/conda-bld/pygimli_1589132014332/work/gimli/gimli/core/src/matrix.h: 181		virtual void GIMLI::MatrixBase::clear()  not yet implemented
 libgimli-v1.1.0
```

**Comment by halbmy** [comment]
Thank you for reporting this issue that helped us to sort out inconsistencies in the internal handling of meshes, region manager etc. After updating the code (via git and copying the core binaries from the 1.1 binary distribution, or waiting for the next version), the following code should be working
```Python
ert = pg.physics.ERTManager('gallery.data')  # sr=False, verbose=True, debug=False)
mesh = ert.createMesh(data=ert.data, paraDX=0.25, quality=34.4, maxCellArea=100)
ert.setMesh(mesh)  # important to do it explicitly as it avoids rebuilding region manager etc.
C = pg.matrix.GeostatisticConstraintsMatrix(mesh=ert.fop.paraDomain, I=[25, 5], dip=-25)
ert.fop.setConstraints(C)
ert.invert(lam=10)
ert.showResult() 
```

**Comment by kaufmanno** [comment]
Thank you Thomas. 

This solved the issue and seems to work as expected!

I just have to mention that I get this error message that might come from the way the geostatistical constraints are handled internally.  

18/07/20 - 18:59:33 - Core - ERROR - no cWeights defined. You should create constraints matrix first.

Despite this error message, the effect of changing the covariance parameters is obvious and consistent.

**Comment by halbmy** [comment]
Yes, after setting the constraint matrix from outside the inversion has to adapt the weighting vector (containing the weight of the individual lines of the matrix), but it is rather a warning since it defaults to one. A better way of setting geostatistical constraints (also per region) is needed, but this requires a redesign of the region manager planned for pyGIMLi 1.2.
