### ISSUE TITLE
[QUESTION] complex resistivity inversion

### ISSUE THREAD

**Issue by itzimah** [gimli-org/gimli#247]
###  
Hello!
Sorry for the simple question but is it possible to invert complex resistivity data using the ERTManager? I saw the example of "Complex-valued electrical modeling" but is it possible to invert these data?  Actually I want to model and invert ERT and time-domain IP data (would it be better to use pybert or BERT for this?), but I thought maybe I could work with complex resistivity. 
Many thanks!
Itzel

**Comment by halbmy** [comment]
I am not sure whether a complex IP inversion makes sense for TDIP data unless you have a specific model in the background. In the BERT project
https://gitlab.com/resistivity-net/bert
you will find specialized managing classes for FDIP and TDIP data, so I am referring to these. The TDIP class uses constrained inversion of single windows, however the forward solution is according to Seigels approach. Such 
```
tdip = TDIPdata(inputfile) # e.g. ABEM or Syscal TXT export
tdip.filter(...)
tdip.fitDecays()
tdip.generateDataPDF()
tdip.generateDecayPDF()
tdip.invertRhoa(show=True)
tdip.invertMa(nr=3, show=True)
tdip.simultaneousInversion()
tdip.fitModelDecays(show=True)
```
See https://gitlab.com/resistivity-net/bert/-/blob/master/python/pybert/tdip/tdipdata.py

I will also provide examples and documentation soon.

**Comment by itzimah** [comment]
Great!
Thanks a lot.
Itzel
