### ISSUE TITLE
Pygimli and seismic reflection

### ISSUE THREAD

**Issue by Pbottelin** [gimli-org/gimli#248]
Hi everyone,
and sorry for this -maybe- silly question:

I was wondering why it is possible to simulate seismic first arrival times with pygimli (direct waves, refracted waves) but it seems that there is no way to simulate reflected waves.

Is this because it requires a full waveform modeling core, whereas first arrivals may be simulated with other approaches? (e.g. wavefronts).

And if pertinent, do you intend to implement such feature in the future development of pygimli? (I am working now with fatiendo package, but I'm not very familiar with it).

Thanks for your answers,
best regards!

Pierre

**Comment by florian-wagner** [comment]
Dear Pierre,

the underlying algorithm is based on Moser (1991) now with secondary nodes (Giroux & Larouche, 2013). This algorithm just looks for the shortest (fastest) path through a given mesh from source to receiver indepenent of any physics. The fastest paths / first arrivals result in direct and refracted waves. 

There is a `solvePressureWave` function in pygimli, but this is not ready for scientific purposes and was only used for teaching a while ago: https://www.pygimli.org/videos/refraction.mp4

Devito is probably a good package for simulating seismic wave propagation and full-waveform inversion: https://www.devitoproject.org/

Cheers
Florian

**References**
- T. J. Moser, (1991), "Shortest path calculation of seismic rays," GEOPHYSICS 56: 59-67.
https://doi.org/10.1190/1.1442958
- Giroux B., Larouche B., 2013. Task-parallel implementation of 3D shortest path raytracing for geophysical applications, Comput. Geosci., 54, 130–141.
