### ISSUE TITLE
Jacobian matrix for homogeneous model in ERT

### ISSUE THREAD

**Issue by HenryWHR** [gimli-org/gimli#252]
### Problem description

Hello,

I am trying to produce Jacobian matrix using a homogeneous model. I think the Jacobian matrix should be the same for different homogeneous values. However, each value in the matrix when using a homogeneous model of 10 ohmm is 100 times the corresponding value using 1 ohmm. I wonder why this happens and how to fix it? 

Thank you very much!

### Your environment

**Operating system**:  Windows
**Python version**: 3.7
**pyGIMLi version**: 1.1.0+31.g47c8d810
**Way of installation**: Conda package

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
import pygimli as pg
import pygimli.physics.ert as ert
fop = ert.ERTModelling()
fop.setData(scheme)
fop.setMesh(mesh)
model = np.ones(mesh.cellCount())
#model = 10*np.ones(mesh.cellCount())
fop.createJacobian(model)
sens = fop.jacobian()
J = pg.utils.gmat2numpy(sens)
...
```

### Expected behavior

Tell us what should happen or what you want to achieve.

### Actual behavior

Tell us what happens instead and/or provide the output of your script.

```
Paste output here.
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by m-weigand** [comment]
Could you post a full (non-)working example?

At least for the current git the behavior is as expected for me.
`
#!/usr/bin/env python
import pygimli as pg
import pygimli.physics.ert as ert
import pygimli.meshtools as mt
import numpy as np

world = mt.createWorld(
    start=[-55, 0], end=[105, -80], worldMarker=True)

mesh_coarse = mt.createMesh(world, quality=33, area=5)

# additional refinements
# mesh = mesh_coarse.createH2()

# Create a P2-optimized mesh (quadratic shape functions)
mesh = mesh_coarse.createP2()

# pg.show(mesh)
for nr, c in enumerate(mesh.cells()):
    c.setMarker(nr)

scheme = ert.createERTData(
    elecs=np.linspace(start=0, stop=3, num=4),
    schemeName='dd'
)


def get_J(model):
    print('model mean', model.mean())
    fop = ert.ERTModelling()
    fop.setData(scheme)
    fop.setMesh(mesh, ignoreRegionManager=True)
    fop.createJacobian(model)
    sens = fop.jacobian()
    J = pg.utils.gmat2numpy(sens)
    return J


J_1 = get_J(np.ones(mesh.cellCount()))
J_10 = get_J(np.ones(mesh.cellCount()) * 10)
J_100 = get_J(np.ones(mesh.cellCount()) * 100)

assert np.allclose(J_1, J_100)
assert np.allclose(J_1, J_10)
`

Cheers

**Comment by HenryWHR** [comment]
Hi Maxi,

Thank you very much! I tried your example and it does work as expected.  
Here is the example in my case. 

```
import numpy as np
import pygimli as pg
import pygimli.physics.ert as ert
from pygimli.meshtools import createParaMesh2DGrid

scheme = ert.createERTData(
    elecs=np.linspace(start=0, stop=3, num=4),
    schemeName='dd'
)

mesh = createParaMesh2DGrid(sensors=pg.Vector(range(11)),paraBoundary=0,boundary=1,paraDX=1,paraDZ=1,paraDepth=7)

def get_J(model):
    print('model mean', model.mean())
    fop = ert.ERTModelling()
    fop.setData(scheme)
    fop.setMesh(mesh)
    fop.createJacobian(model)
    sens = fop.jacobian()
    J = pg.utils.gmat2numpy(sens)
    return J


J_1 = get_J(np.ones(mesh.cellCount()))
J_10 = get_J(np.ones(mesh.cellCount()) * 10)
J_100 = get_J(np.ones(mesh.cellCount()) * 100)
```
Kind regards
Henry

**Comment by halbmy** [comment]
Would be interesting to find out why it didn't work out in the first place. I guess it could be due to cell markers of the inner and outer model part, boundary conditions etc. For the Jacobian we need (as well as for the forward computation) to put boundaries far enough from the electrodes if the model is inhomogeneous (for a homogeneous model the BC are perfect).

**Comment by halbmy** [comment]
Any news on this? If all is solved we can close the issue.

**Comment by HenryWHR** [comment]
Hi Thomas,

My question has been solved. And you are right, it is due to the cell markers of the inner and outer model.
To test this, I use 'appendTriangleBoundary' instead of 'createParaMesh2DGrid'. The results present correct when the inner model has the same marker as the appended boundary.

Best
Henry
