### ISSUE TITLE
how to show value data ,  model response and display graph misfit

### ISSUE THREAD

**Issue by layufuji** [gimli-org/gimli#254]
### Problem description
Hi, I'm doing some ERT  with your software, how to show misfit graph in mgr.showResultAndFit in https://www.pygimli.org/_examples_auto/3_dc_and_ip/plot_01_ert_2d_mod_inv.html
, show value root mean square error, and i show value  data and model response??

### Your environment

**Operating system**: Linux
**Python version**: 3.7
**pyGIMLi version**: Output of `print(pg.__version1.1)`
**Way of installation**: e.g. Conda package, Win binary, curl script, manual compilation from source

### Steps to reproduce

mgr = ert.ERTManager('simple.dat')
inv = mgr.invert()
mgr.showResultAndFit()
mgr.showFit()

how to display the value of mgr.showFit and the misfit graph for a fit model..

### Actual behavior

```
Paste output here.
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
Hello, can you please edit the issue text by filling in the necessary information (OS, installation, version), most importantly how you got to this error, i.e. by specifying a script. The error message you filled in "Steps to reproduce" should be under "Actual bahaviour". We can only answer your question when we know how you obtained your error and try to reproduce it.

**Comment by halbmy** [comment]
What I can say from here, is that `pg.plt` is nothing else than `matplotlib.pyplot`, which can of course not know anything about pyGIMLi. So you should rather use `pg.show()` instead, which should work for `DataContainerERT`. Note however that for method managers there are already existing functions, documented in the examples by e.g. https://www.pygimli.org/_examples_auto/3_dc_and_ip/plot_01_ert_2d_mod_inv.html (second part):
```Python
mgr = ert.ERTManager('simple.dat')
inv = mgr.invert()
mgr.showResultAndFit()
```

**Comment by layufuji** [comment]
i done edit issue , thank you

**Comment by halbmy** [comment]
So this means your problem is solved? By the way, there is no version 1.2 yet.

**Comment by layufuji** [comment]
yes, that's what I haven't finished yet

**Comment by halbmy** [comment]
What exactly is not finished?

**Comment by layufuji** [comment]
I have displayed the model results from your software, and I want to know whether the model I plot is fit or not so I want to display a graph from synthetic data and observation data

**Comment by layufuji** [comment]
dan apakah benar untuk mengetahuui nilai error adalah 
ert.inv. chi() or ert.inv.relrms()

**Comment by halbmy** [comment]
> I have displayed the model results from your software, and I want to know whether the model I plot is fit or not so I want to display a graph from synthetic data and observation data

`mgr.showResultAndFit()`

shows both the observed data and the modelled forward response. Please read the linked example first.

**Comment by layufuji** [comment]
yes I have read and tried the example, what I mean by mgr.showResultAndFit () wants to display the observed and modeled data values, when I want to display the Rvector error result value

**Comment by halbmy** [comment]
Do you mean the error vector (i.e. of the same length as the data) or do you mean the misfit (i.e. difference between observed and modelled data)?

**Comment by layufuji** [comment]
no, but I want to display the misfit data from the result data and response

**Comment by halbmy** [comment]
```
misfit = mgr.inv.response / mgr.data['rhoa'] * 100 - 100
pg.show(mgr.data, misfit, cMap="bwr", cMin=-10, cMax=10, label="misfit (%)")
```

![image](https://user-images.githubusercontent.com/7136401/92131535-68948600-ee06-11ea-915e-ed0d43129df3.png)

**Comment by layufuji** [comment]
Thank you sir, very helpful, I want to ask again mgr.data ['rhoa'] for electrical resistivity, if for seismic mgr.data ['?'] is changed to what? thank you

**Comment by halbmy** [comment]
`mgr.data` holds the data container and has not to do with the model.

So `mgr.data['rhoa']` cannot be resistivity, but apparent resistivity. You can use `print(mgr.data)` to find out which other fields there are in the data. For the example gallery.dat the output is i.e.
```
Data: Sensors: 21 data: 116, nonzero entries: ['a', 'b', 'err', 'm', 'n', 'rhoa', 'valid']
```

For a seismic data container, the tokens are typically `'s'` (shot index), `'g'` (geophone index) and `'t'` (traveltime).
