### ISSUE TITLE
Setting region markers when creating elements across multiple layers.

### ISSUE THREAD

**Issue by yusuket** [gimli-org/gimli#255]
### Problem description
We are investigating the use of electrical methods to confirm the shape of the ground improvement body. In this context, pyGimLi is used to study the optimization of electrode placement.
In the multi-layer ground model, there is a region where the region markers are forced to zero during the creation of an improved body.
Is there any way to set these region markers arbitrarily?

### Your environment

**Operating system**:  Windows10
**Python version**: 3.7.6
**pyGIMLi version**: 1.1.0
**Way of installation**: Conda package, 

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

import numpy as np
import pygimli as pg
import pygimli.meshtools as mt

# Ground layers model
geom = mt.createWorld(start=[-10.0,0.0],end=[10.0, -20.0],layers = [-5.9,-8.2,-11.0,-14.75,-16.5],worldMarker=True)
pg.show(geom)

# Imprivement body
c0 = mt.createCircle(pos=(0.0,-13.75),radius=2.0,segment=25,marker=10,isClosed =True)
c1 = mt.createCircle(pos=(0.0,-9.75),radius=2.0,segment=25,marker=11,isClosed = True)
geom = geom + c0 + c1
pg.show(geom)

### Expected behavior

The region markers inside the circle are set to 10 and 11, and we want the area to the left of the circle to remain the same as it was before the circle was formed.

### Actual behavior
Region markers in the area that interfere with the layer specified by "createWorld" command are forced to be set to 0.

Paste output here.
![geom](https://user-images.githubusercontent.com/70733916/92195601-5ec35f00-eea8-11ea-9951-747e4e5bb1d6.png)

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
A region marker is a point in the mesh (that will not become a node) to fill all cells of a region with its marker value. By creating a PLC like a circle, such a point is created, typically in the middle, but can be also at other places. See also the tutorial about region marker
https://www.pygimli.org/_tutorials_auto/1_basics/plot_markers.html

In your case the circle cuts the layer boundary and prevents the layer or region markers to fill this region resulting in a zero region. Therefore you need to set a region marker by hand using `geom.addRegionMarker(position, marker=marker)`.
So in your case the script becomes (or a
```Python
import pygimli as pg
import pygimli.meshtools as mt

geom = mt.createWorld(start=[-10.0, 0.0], end=[10.0, -20.0],
                      layers = [-5.9, -8.2, -11.0, -14.75, -16.5],
                      worldMarker=True)
c0 = mt.createCircle(pos=(0.0, -13.75), radius=2.0,
                     segment=25, marker=10, isClosed =True)
c1 = mt.createCircle(pos=(0.0, -9.75), radius=2.0,
                     segment=25, marker=11, isClosed = True)
geom = geom + c0 + c1
geom.addRegionMarker([0, -8], marker=11)  # right part of cut layer
geom.addRegionMarker([0, -11.5], marker=11)  # upper circle, upper cut, marker could also be 2
geom.addRegionMarker([0, -15], marker=10)  # upper circle, lower cut, marker could also be 4
geom.addRegionMarker([5, -13], marker=4)  # lower circle, lower cut, marker could also be 5
pg.show(geom)
```
resulting in
![image](https://user-images.githubusercontent.com/7136401/92203086-a209d780-ee80-11ea-86ae-1abd933b64ce.png)
