### ISSUE TITLE
Save results of seismic tomography inversion

### ISSUE THREAD

**Issue by mcardenass** [gimli-org/gimli#264]
### Problem description

Is there any function that allows me to save in an array of ascii values (coordinates of cell centers and Velocity value) the seismic tomography inversion results? I modified the Crosshole traveltime tomography example to produce seismic noise tomography images. Now I need to save the results to create a 3D velocity model. I guess it won't be the same to save structured mesh results as an unstructured one. Thanks in advance for the support.

**Comment by halbmy** [comment]
The coordinates of cell centers can be retrieved by `mesh.cellCenters()`. For saving those along with the obtained velocity distribution, you should need to extract it from the inversion mesh `mgr.paraDomain` (where mgr is the traveltime manager instance), append the model vector and save it using numpy
```
out = np.column_stack((mgr.paraDomain.cellCenters(), mgr.model))
np.savetxt("out.xyzv", out)
```
To image slices etc. you will need some sort of gridding anyway, so consider using the interpolation functions of pygimli. Or use a 3D viewer like ParaView with the vtk file obtained by `mgr.saveResult("out")`.

**Comment by mcardenass** [comment]
Dear Tomas,

thank you!! It works very fine
