### ISSUE TITLE
tdem.invert

### ISSUE THREAD

**Issue by aminkhalil** [gimli-org/gimli#266]
### Problem description

I used the example provided with tdem class. When I tried to do inversion using the command
tem.invert(nr=0, nlay=10, thickness=None)
I got the following error
AttributeError: 'VMDTimeDomainModelling' object has no attribute 'setMaxIter'
### Your environment
spyder pg, python 3.7.8
**Operating system**: e.g. Windows, Linux or Mac? Ms Windows 10
**Python version**: e.g. 2.7,3.5,3.6? 3.7.8
**pyGIMLi version**: Output of `print(pg.__version__)`
**Way of installation**: e.g. Conda package, Win binary, curl script, manual compilation from source
conda
### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
import pygimli as pg
...
```

### Expected behavior

Tell us what should happen or what you want to achieve.

### Actual behavior

Tell us what happens instead and/or provide the output of your script.

```
Paste output here.
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
The TDEM class is one of the least cured classes in pygimli since currently nobody works with it actively. Furthermore, it is not covered by any of the examples. I guess it needs an update to pg 1.1 and some further improvement. I'll have a look.

**Comment by aminkhalil** [comment]
Dear Gunther,

The problem  for me is that when I try invert using the command:

Tem.invert()

And error is raised that VMDTimeDomainModelling doesn’t have attribute setmaker

I wonder whether this is right form to invoke invert.

 

regards

**Comment by halbmy** [comment]
Can you please attach your script and a datafile just to see the real problem?

**Comment by aminkhalil** [comment]
Dear Günther,

Thanks for reply. I used the script you provided in the TDEM class with minor amendment as follow:

"""

Created on Sun Oct 25 18:42:11 2020

 

@author: aminw

"""

 

import sys

from math import pi

import numpy as np

import matplotlib.pyplot as plt

import pygimli as pg

from pygimli.physics.em import VMDTimeDomainModelling

from pygimli.frameworks import Block1DModelling

from pygimli.physics.em import TDEM

 

 

 

if __name__ == '__main__':

    print("do some tests here")

    tem = TDEM(sys.argv[1])

    #print(tem)

    tem1=tem.stackAll()

    print(tem1.DATA)

    tem1.plotTransients()

    tem1.plotRhoa()

    #nr=0

    #tem1.fop=TDEM.getFOP(nr)

    model=tem1.invert()

    #model()

The data is usf file it is read and plot correctly. I tried stackAll() and it seems working properly with one issue that when the original data is in V/(I*m^2), the code read as V/I only. I may try to fix it. The major problem is when invert is invoked, it gives attribute error. I am attaching the data file herewith for your kind perusal.

 

Best regards

**Comment by DavidCima13** [comment]
@aminkhalil About the problem with data units (V/(I*m^2)) . You can change at  the root  function _plotTransients_  in tdem.py . By default, this function is normalized with RxArea on this mode  `u = data['VOLTAGE'] / RxArea(data)` .  As your data is mormalized by Rxarea  keep this  `u= data['VOLTAGE'] ` . You shoud change as well the function get_rhoa on this sense.

**Comment by thecraigoneill** [comment]
I have this problem too, here's a minimalist code example:

---

import numpy as np
import matplotlib.pyplot as plt
import pygimli as pg
import pygimli.meshtools as mt
import pygimli.physics.em.tdem as tdem
import pygimli.physics.em as em

self = tdem.TDEM()
tdem.TDEM.load(self,'305CLASS.usf')  
# This loads ok, and plots the recordings (transients, Rhoa) just fine

tdem2=self.stackAll() #Works
tdem2.plotRhoa() #Works
tdem2.invert()  #Fails

---

Full error stack:

    tdem2.invert()
  File "...tdem.py", line 441, in invert
    self.INV = pg.Inversion(rhoa, self.fop)
  File "/.../anaconda3/envs/gimli/lib/python3.7/site-packages/pygimli/frameworks/inversion.py", line 62, in __init__
    self.maxIter = kwargs.pop('maxIter', 20)
  File "/.../anaconda3/envs/gimli/lib/python3.7/site-packages/pygimli/frameworks/inversion.py", line 258, in maxIter
    self.inv.setMaxIter(v)
AttributeError: 'VMDTimeDomainModelling' object has no attribute 'setMaxIter'

**Comment by halbmy** [comment]
The `TDEM` module is apparently outdated and not compatible to pg 1.1 anymore (and not covered by tests and examples). We are planning to introduce codes for arbitrary loop or grounded dipole sources.

**Comment by thecraigoneill** [comment]
Ah, too bad. I look forward to seeing the new capabilities.

**Comment by mpessel** [comment]
Hello, 
I'm taking up this thread because it concerns the TDEM class and it seems to me that the invert function works but however it is not possible to modify the number of layers (4 by default).

I have also tried using the invert functions directly (pg.core.Inversion etc ...) and I get the same result.

Is there a way to modify this behavior because for VES or FEM data it works perfectly ;)
Cheers,
Marc

**Comment by mpessel** [comment]
Hi, no the pb isn't solve... and I don't use the usf-file but tem-datafile (from TEM-FAST)

**Comment by halbmy** [comment]
> Hi Marc, could you solve this issue? Could you run any inversion with your usf-file? I have problems to load the usf file. It is aquired with a Walk-TEM, I wonder if it has to do with the file format....

I've just tried it with some usf data that I acquired myself last week with the WalkTEM and it worked fine. Which pg version are you using? Can you attach an example file?

**Comment by halbmy** [comment]
I just happened to read and import some TEM data acquired with the WalkTEM and it worked. Also old TEM-FAST data. 

@affe73 and @mpessel can you provide sample data to test?

**Comment by affe73** [comment]
Hi @halbmy , here comes a file with sample data, with file ext txt, but exact same format usf: 
[20220517_165115_734_Station2.txt](https://github.com/gimli-org/gimli/files/10238947/20220517_165115_734_Station2.txt)

**Comment by halbmy** [comment]
Closing the issue since back then the inversion has been working after some fixes and still does. However, the whole TDEM stuff needs to be reimplemented if there is anyone out there doing TEM inversion with pyGIMLi. A topic for a new issue...
