### ISSUE TITLE
I want to remove cell.attribute()

### ISSUE THREAD

**Issue by carsten-forty2** [gimli-org/gimli#27]
I found cell.attribute() and mesh.cellAttributes() to limiting and I want to remove or replace it by something more flexible. This might touch something deep inside the basics .. who needs this absolutely? 

I think on replace it with the something like:
mesh.addData('attribute', rvector); 
rvector = mesh.data('attribute')
attr =  mesh.data('cellAttributes')[cell.id()]

cell.marker() and mesh.cellMarker() will stay.

**Comment by halbmy** [comment]
Totally agree. I always had problems mixing up the marker and the attribute.
Therefore it is good to have ONE unique property to control the meshes (i.e. the marker) and a list of freely defined properties. However, how do we distinguish whether the properties are associated to the nodes, to the cells (or boundaries?) or even the markers?
P.S.: Actually mesh.cellMarker() should be mesh.cellMarkers(), i.e. plural.
Thomas

**Comment by florian-wagner** [comment]
:+1:

**Comment by florian-wagner** [comment]
Can we leave `mesh.cellMarker()` with a deprecation warning for compatibility reasons?

**Comment by halbmy** [comment]
Of course we can, and we should do so in other cases as well.
However, main point of this issue was about holding only one fixed attribute (the marker) and to remove the attribute into the data map (which is still called dataExportMap).

**Comment by florian-wagner** [comment]
Yes fully agree. I just noticed that commit https://github.com/gimli-org/gimli/commit/587ae3bcd864bcaee2daf2d8433ccd1cabfb3696 broke two examples (and a lot of my local scripts), which unfortunately passed silently in CI.

**Comment by florian-wagner** [comment]
Perfect, thanks.
