### ISSUE TITLE
Pickling issue Pygimli + BERT

### ISSUE THREAD

**Issue by AleVin11** [gimli-org/gimli#270]
### Problem description
I want to implement a stochastic 2.5D ERT inversion using BERT forward modelling.
However due to the high number of iteration i need to parallelize the code, to do that i use the joblib library.

When i run the codes there is some pickling problem, the error is the following:

  File "<ipython-input-19-9cdb4cad23c3>", line 5, in <module>
    results=Parallel()((delayed(demcore))(j,k,0.5,chains,nx,ny,dct_mcurr,edited_model,mesh_coarse,mesh_fine) for k in range(chains))

  File "/home/ale/anaconda3/envs/pg/lib/python3.7/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()

  File "/home/ale/anaconda3/envs/pg/lib/python3.7/site-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))

  File "/home/ale/anaconda3/envs/pg/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value

  File "/home/ale/anaconda3/envs/pg/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)

  File "/home/ale/anaconda3/envs/pg/lib/python3.7/site-packages/joblib/pool.py", line 156, in send
    CustomizablePickler(buffer, self._reducers).dump(obj)

RuntimeError: Pickling of "pygimli.core._pygimli_.Mesh" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)

The libboost are installed, i think there is some problem with the defined Class but I don't know c++ language.
Or may be the mesh objects need to be define within the function to parallelize?
Did you ever parallelize using pygimli libraries?
Did you ever faced this type of problem?

This is the function (demcore) that I want to parallelize. Do you thing that the problem is about the mesh objects?

Parallel()((delayed(demcore))(j,k,0.5,chains,nx,ny,dct_mcurr,edited_model,mesh_coarse,mesh_fine) for k in range(chains))

**Operating system**:  Linux 
**Python version**: 3.7
**pyGIMLi version**: 1.1.1+0.gbb685a8c (with local changes)
**Way of installation**: e.g. Conda package

**Comment by carsten-forty2** [comment]
Hello,

Pickling of core objects (Mesh, DataContainer, Vector, Matrix, etc.) is currently not supported. We are aware of this and also that this would be very useful feature, but its a little bit tricky to implement with the current way how we create the python bindings for the c++ core. We have a different binding generator in mind, which potentially would allow for easier pickling generation, but we cannot plan atm. when we find time for it to test.

You can try to parallelize the job yourself with `Process` and `Array` from `multiprocessing` and collect/exchange results with a shared memory model. We use this to monkeypatch our multithreading response from c++ core to be usable in python. See: https://github.com/gimli-org/gimli/blob/c107727ad72df2f58343e2ab460f1dd3203d34e5/pygimli/core/__init__.py#L903 as an example. Maybe/probably there are some/much better ways, i.e.: dask.org. 

The topic parallelization is definitely something I will/need to dig in deeper in the not so far future, so hopefully I will have better news or any better examples then.

Bests,
Carsten
