### ISSUE TITLE
Interpolate polygon object into grid

### ISSUE THREAD

**Issue by BoDoNgAhAi** [gimli-org/gimli#280]

**Comment by halbmy** [comment]
Did you just create an issue and delete its content?

**Comment by halbmy** [comment]
You first have to mesh your PLC (physical domain with PLCs) into a triangular mesh. Then you can interpolate because only a mesh has shape functions and thus the ability for interpolation using FEM.

**Comment by BoDoNgAhAi** [comment]
I am sorry for creating this empty issue. I accidently did this but I can't delete it. I do not know why. May you please delete it if it possible? Thank you.
