### ISSUE TITLE
Error cross-hole inversion result 

### ISSUE THREAD

**Issue by xichaoqiang** [gimli-org/gimli#281]
I want invert an cross-hole tomography data.

The sensor geometer seems good.

But the inversion result make me confused.

My code and data is in the attachment.Can you help me to check it?
[py_inv.zip](https://github.com/gimli-org/gimli/files/5843375/py_inv.zip)

![Figure_1](https://user-images.githubusercontent.com/30900789/105194623-bff88000-5b74-11eb-82eb-ee549ee2b48b.png)
![Figure_2](https://user-images.githubusercontent.com/30900789/105194644-c38c0700-5b74-11eb-8f0a-3fabb8130798.png)

**Comment by halbmy** [comment]
In the TOM file, the z positions are positive and mean depth below the surface, whereas in pyGIMLi, z counts upwards and therefore the z positions are negative as can be seen in the file after data.save("bla.sgt"). If the sensors are outside of the mesh the result can't make any sense. So you will have to multiply the z from the TOM file with -1 or better use pg.z(data) directly.

**Comment by halbmy** [comment]
No idea whether the result
![image](https://user-images.githubusercontent.com/7136401/105243667-a274e780-5b6f-11eb-9e9f-ca3fba30a3fa.png)
makes sense but the data are fitted after 3 iterations (even below chi2=1).

**Comment by xichaoqiang** [comment]
How can I set the boundaries in the cross-hole inversion?

`invmodel = ttinv.invert(data,mesh=mesh,lam=1000, maxIter=10,modelTrans=pg.trans.TransLogLU(1.0/2600, 1.0/2450), zWeight=1.0, verbose=True)`

I try this way,but it seems dosn't work.
