### ISSUE TITLE
Reference book for the seismic refraction forward modelling

### ISSUE THREAD

**Issue by nevesanjos** [gimli-org/gimli#284]
Hi, I am wondering if there is a good reference book that explains how pygimli deals with the physics in order to obtain the forward model.

Thanks,
Felipe

**Comment by halbmy** [comment]
There is no reference book. pyGIMLi uses the Shortest Path (Dijkstras) method (Moser 1991) with secondary nodes as described by Giroux & Larouche (2013).

References
* Moser, TJ. Shortest path calculation of seismic rays. Geophysics, 56(1):59–67, 1991. doi:10.1190/1.1442958.
* Giroux, B. & Larouche, Task-parallel implementation of 3D shortest path raytracing for geophysical applications, Computers & Geosciences, 54, 130-141, 2013, doi: 10.1016/j.cageo.2012.12.005.

**Comment by nevesanjos** [comment]
Thank you, @halbmy
