### ISSUE TITLE
Question: Why do response() and jacobian()*model have a different result?

### ISSUE THREAD

**Issue by yudhastyawan** [gimli-org/gimli#286]
### Question

Hello for all contributors and users of pygimli,
Thank you for creating a useful package for geophysical problems.
I have an issue regarding the comparison between the result of `fop.response()` and `fop.jacobian()` multiplied by model. Both results have different values. I just wonder about what kind of method used for generating response() because I would like to modify the method for my problem. Thank you for your kind response.

For the example, I modify the example provided in pygimli.org

```python
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import traveltime

pyvista = pg.optImport("pyvista")

depth = 15
width = 30
plc = mt.createCube(size=[width, width, depth], pos=[0, 0, -depth/2], area=5)

n_sensors = 8
sensors = np.zeros((n_sensors, 3))
sensors[0, 0] = 15
sensors[0, 1] = -10
sensors[1:, 0] = -15
sensors[1:, 1] = np.linspace(-15, 15, n_sensors - 1)

for pos in sensors:
    plc.createNode(pos)
mesh = mt.createMesh(plc)
mesh.createSecondaryNodes(1)

vel = 300 + -pg.z(mesh.cellCenters()) * 100

data = traveltime.createRAData(sensors)
data.markInvalid(data("s") > 0)
data.set("t", np.zeros(data.size()))
data.removeInvalid()

fop = pg.core.TravelTimeDijkstraModelling(mesh, data)
fop.setThreadCount(1)

fop.createJacobian(1/vel)
print("t from response:", fop.response(1/vel))
print("t from jacobian * model:", fop.jacobian().mult(1/vel))

```

The output is
```
t from response: 7 [0.04746715743906823, 0.04654152878823256, 0.04641471046326046, 0.046946441594147195, 0.04851830868144241, 0.05040281477702353, 0.05231282475912783]
t from jacobian * model: 7 [0.0662219049026796, 0.0713589622292557, 0.06536985302338552, 0.07374660239164632, 0.07347846645937707, 0.08092178260696019, 0.08841853713808147]
```

### My environment

**Operating system**: Linux
**Python version**: 3.7.8
**pyGIMLi version**: 1.1.0+0.g47c8d810 (with local changes)
**Way of installation**: Conda package

**Comment by halbmy** [comment]
Thank you for reporting! 

Indeed, the model response computed by multiplying the Jacobian with the slowness should be identical to the normal response and approach the analytical solution for a sufficiently fine mesh with appropriate secondary nodes as pointed out in https://www.pygimli.org/_examples_auto/2_seismics/plot_03_rays_layered_and_gradient_models.html

In 2D, everything is fine (i checked a model similar to yours), but apparently not in 3d. My observations:
* The responses are identical for homogeneous velocity but not for a gradient model.
* The difference becomes smaller with increasing 
* There is no change if the nodes are not on the model boundary.
* The normal response is closer to the analytical solution, so it should be the Jacobian.

[issue286TG.py.zip](https://github.com/gimli-org/gimli/files/5979990/issue286TG.py.zip)

**Comment by yudhastyawan** [comment]
Thanks a lot for your quick response and suggestions. I was checking on 2D, especially on pygimli example, I just found that it has only a little bit of difference between `fop.response(model)` and `fop.jacobian().mult(model)` results. However, both results are not the same (not considering the secondary nodes in this case). Currently, I would plan to create my own jacobian for my problem based on the ray path that was created on the package. Thank you and gladly seeing pygimli will be better in the future.

An example of a 2D problem (gradient-based):
```python
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt

sensors = np.arange(131, step=10.0)
plc = mt.createWorld([-20, -60], [150, 0])
for pos in sensors:
    plc.createNode([pos, 0.0])
mesh_gradient = mt.createMesh(plc, quality=33, area=3)

a = 1000
b = 100

vel_gradient = []
for node in mesh_gradient.nodes():
    vel_gradient.append(a + b * abs(node.y()))
vel = pg.meshtools.nodeDataToCellData(mesh_gradient,
                                               np.array(
                                                   vel_gradient
                                               ))

for boundary in mesh_gradient.boundaries():
    boundary.setMarker(0)

xmin, xmax = mesh_gradient.xmin(), mesh_gradient.xmax()
mesh_gradient.createNeighbourInfos()

mx = pg.x(mesh_gradient)
my = pg.y(mesh_gradient)
px = np.sort(mx[my == 0.0])

data = pg.DataContainer()
data.registerSensorIndex('s')
data.registerSensorIndex('g')

for i, fii in enumerate(px):
    data.createSensor([fii, 0.0])
    if fii == 0:
        source = i

nData = len(px)
data.resize(nData)
data['s'] = [source]*nData
data['g'] = range(nData)

fop = pg.core.TravelTimeDijkstraModelling(mesh_gradient, data)
fop.setThreadCount(1)

fop.createJacobian(1/vel)
print("t from response:", fop.response(1/vel)[0:5])
print("t from jacobian * model:", fop.jacobian().mult(1/vel)[0:5])
```

result:
```
t from response: 5 [0.01764785601043821, 0.01589899395927743, 0.01400582810594455, 0.011831248152944292, 0.009465453230441623]
t from jacobian * model: 5 [0.013906357542799423, 0.011934220205701361, 0.010379085533699274, 0.007095123177577796, 0.005676098542062237]

```

**Comment by yudhastyawan** [comment]
Continuing the 2D example in my previous comment, this might be a consideration because I have roughly checked the ray coverage using the provided jacobian and seeing on the figure. This might have some wrong usages of my code (let me know if there have some issues in my code), but the figure representing the total of rays for each cell is not following the result has to be. Thank you for your consideration.

```python
import matplotlib.pyplot as plt

# getting the value of jacobian provided by the package
jacob = []
for i in range(fop.jacobian().nRows()):
    jacob.append(fop.jacobian().row(i).array())
jacob = np.array(jacob)

# checking the result if it has a different result with the previous ones; especially fop.jacobian().mult(model)
print("t from jacobian*model (outside the package)", pg.Matrix(jacob).mult(1/vel)[0:5])

# creating the ray coverage (based on the provided jacobian; only getting the total of rays for each cell)
jacob = np.sign(jacob)
ray_coverage = pg.Matrix(jacob).transMult(np.ones(fop.jacobian().nRows()))

# figuring it out
fig = plt.figure()
ax = plt.axes()
pg.show(mesh_gradient, ray_coverage, ax=ax)
plt.show()
```

the result (the color bar representing the total of rays):
![image](https://user-images.githubusercontent.com/39240883/108041393-6dc65400-7079-11eb-8602-0ad4c0ea943d.png)

**Comment by florian-wagner** [comment]
Dear @yudhastyawan,

thank you for the valuable issue. I made some tests as well. The difference seems to be independent of 2D vs. 3D, but rather due to a logarithmic transform. We will discuss this in our pygimli meeting later and provide you with a definite response and an update to the code afterwards.

Best wishes
Florian

**Comment by halbmy** [comment]
Florian, there is no transformation involved in the modelling, whatsoever. It comes only into play for inversion.

The term `J.transMult` means multiplication from the left side (or with the transposed matrix). 

The 2d code that I had attached (py.zip file) shows a perfect match (1e-16) between the two responses:

```Python
from math import asin, tan

import matplotlib.pyplot as plt
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.viewer.mpl import drawMesh

from pygimli.physics import TravelTimeManager

def analyticalSolutionGradient(x, a=1000, b=100):
    """Analytical solution for gradient model."""
    tdirect = np.abs(x) / a  # direct wave
    tmp = 1 + ((b**2 * np.abs(x)**2) / (2 * a**2))
    trefrac = np.abs(b**-1 * np.arccosh(tmp))
    return np.minimum(tdirect, trefrac)

sensors = np.arange(131, step=10.0)
plc = mt.createWorld([-20, -60], [150, 0], worldMarker=False)
for pos in sensors:
    plc.createNode([pos, 0.0])

mesh = mt.createMesh(plc, quality=34, area=3)

data = pg.DataContainer()
data.registerSensorIndex('s')
data.registerSensorIndex('g')

mx = pg.x(mesh)
my = pg.y(mesh)
px = np.sort(mx[my == 0.0])

for i, pxi in enumerate(px):
    data.createSensor([pxi, 0.0])
    if pxi == 0.0:
        source = i

nData = len(px)
data.resize(nData)
data['s'] = [source] * nData # only one shot at first sensor
data['g'] = range(nData)  # and all sensors are receiver geophones

a = 1000
b = 100

vel = 300 + -pg.z(mesh.cellCenters()) * 300
slo = 1.0 / vel

pg.show(mesh, vel, label="Velocity (m/s)")


fop = pg.core.TravelTimeDijkstraModelling(mesh, data)
fop.setThreadCount(1)

fop.createJacobian(slo)
resp = fop.response(slo)
respJ = fop.jacobian().mult(slo)
sx = pg.x(data)
x = pg.math.abs(sx[data["s"]] - sx[data["g"]])
respA = analyticalSolutionGradient(x, a, b)
print("t from response:", resp)
print("t from jacobian * model:", respJ)
print(pg.math.rms(resp, respJ), pg.math.rms(resp, respA))
```

**Comment by halbmy** [comment]
In inversion, the model cells are internally renumbered so that they will be treated as different unknowns (and not as cells of a unique model region). Then all will be ok. But your mesh has constant cell markers. If you renumber them by
```
mesh_gradient.setCellMarkers(np.arange(mesh_gradient.cellCount()))
```
then all is (almost) ok (in this case for 3 secondary nodes):
![image](https://user-images.githubusercontent.com/7136401/108106345-1e3e5300-708e-11eb-99b2-1a523d337381.png)
If you remove or decrease the secondary nodes, the deviations will increase. However, there is still a slight difference between the response and the Jacobian that we need to look into. 
[ex2d.zip](https://github.com/gimli-org/gimli/files/5990905/ex2d.zip)

**Comment by florian-wagner** [comment]
@yudhastyawan As an addition: Please note that this also solves your Jacobian plotting issue:

``` python
jacob = pg.utils.sparseMatrix2coo(fop.jacobian())

# creating the ray coverage (based on the provided jacobian; only getting the total of rays for each cell)
ray_coverage = jacob.sum(axis=0).A1 # see https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.matrix.A1.html

# figuring it out
fig = plt.figure()
ax = plt.axes()
pg.show(mesh_gradient, ray_coverage, ax=ax)
plt.show()
```
![jacobian](https://user-images.githubusercontent.com/2799008/108110732-fce06580-7093-11eb-8120-8d92384c05b9.jpg)

**Comment by halbmy** [comment]
As the original problem has been solved (and everything else is a bit more complex but we have it on the list) we can close the issue. Thank you all again for the discussion.
