### ISSUE TITLE
ert.inv.chi2() vs ert.inv._inv.chi2() with robustData = True

### ISSUE THREAD

**Issue by xwanner** [gimli-org/gimli#288]
### Problem description

I try to recover chi2 from an inversion with robustData = True, and I see that it's not the same chi2 that is computed from python binds and from the c++ inversion.

I suspect that the weighting vector is lost somewhere during the python binding, is that possible ?

Looking further into this, I spotted that the ert.inv.phiData() is different from the ert.inv._inv.getPhiD().

Actually, I could deal with ert.inv._inv.chi2(), but the fact is that I suspect that the value I get is 1 iteration after the inversion stop is that right ? How could I get the previous chi2 value ?

In the console output I see the last chi2 value for iteration 3 in the example of 0.861 and when I get it from ert.inv._inv.chi2() I get 0.578 and when I get it from ert.inv.chi2() it is 1.976

### Your environment

**Operating system**:Linux Ubuntu 18
**Python version**: 3.7.9
**pyGIMLi version**: 1.1.0+0.g47c8d810 (with local changes)
**Way of installation**: Conda package

### Steps to reproduce

here is a script that every one can try :

```python
import numpy as np
import pygimli as pg

from pygimli.physics.ert import ERTManager, createGeometricFactors

data = pg.getExampleFile('ert/slagdump.ohm', load=True, verbose=True)

data['k'] = createGeometricFactors(data, numerical=True)
ert = ERTManager(sr=False, useBert=True, verbose=True, debug=False)
ert.checkData(data)
data['err'] = ert.estimateError(data, absoluteError=0.001, relativeError=0.03)
mod = ert.invert(data, lam=10,robustData = True)

print("CHI2 with ert.inv._inv.chi2() : "+str(ert.inv._inv.chi2())) 
print("CHI2 with ert.inv.chi2() : "+str(ert.inv.chi2())) 
```

### Expected behavior

Should get the same chi2 with ert.inv._inv.chi2() and ert.inv.chi2() and the output chi2 of the console

### Actual behavior

ert.inv._inv.chi2() and ert.inv.chi2() output different values when robustData=True

### Output of the script (end only)
```
3: Model: min = 3.60387; max = 160.743
3: Response: min = 5.99709; max = 32.5235
3: rms/rrms(data, Response) = 0.772434/4.11138%
3: chi^2(data, Response, error, log) = 0.860984
3: Phi = 191.138+45.292*10=644.058
Robust reweighting 
min/max(dweight) = 5.95767/33.3002
inv.iter 3 ... chi² = 0.86 (dPhi = 10.49%) lam: 10.0


################################################################################
#                  Abort criterion reached: chi² <= 1 (0.86)                   #
################################################################################
CHI2 with ert.inv._inv.chi2() : 0.5784046965666629
CHI2 with ert.inv.chi2() : 1.9760247002820828

```

**Comment by halbmy** [comment]
Thank you for pointing out this inconsistency, which is actually a result of the transformation from C++ to Python. The inner (actual) inversion instance (`ert.inv._inv`) changes the error (in case of robustData) and thus the weighting, whereas the outer inversion handler (`ert.inv`) keeps the original, as easily seen by

```Python
outer = ert.inv.errorVals
inner = ert.inv._inv.error()
pg.plt.plot(outer, inner, ".")
```

So only `ert.inv._inv.chi2()` is correct and `ert.inv.chi2()` is the chi-squared value without any reweighting (also interesting). 
We will sort this out so that both the error is kept and the correct weighting is used for chi-square.

**Comment by xwanner** [comment]
Thanks for your answer. So I'll wait for the update ;)

Talking of weights, I also noticed that the RMS is not a weighted RMS. But not sure if this should be implemented or not. 
For now, I compute the weighted RMS with the error I get from `ert.inv._inv.error()`.

**Comment by halbmy** [comment]
I am not sure whether this will be corrected so soon as there is actually no error and you can retrieve all values. A consequent change might take some time.

The RMS is as the name says, a root mean square, i.e. unweighed. If you weight the misfit by the error, you'll end up in the chi-square (which is also kind of an RMS but would be confusing).

**Comment by brianhavk** [comment]
Hello! Sorry for commenting on an issue that was already closed. 

Testing the chi2 history with robustData=True, I can see that it saves well the chi2, so we could take the last element of the list and this would be the chi2 that we should be able to get from inv.chi2() or inv._inv.chi2().

This is a sample code:
```Python
import pygimli.physics.ert as ert

dataset = ert.load("simple.dat")

mgr = ert.ERTManager(dataset, verbose=True)
inversion = mgr.invert(robustData=True)
chi2 = (mgr.inv.chi2History)[-1]
print("Last Chi2 from chi2History: " + str(chi2))
``` 


and this is its console output:
```text
inv.iter 3 ... chi² = 0.55 (dPhi = 59.76%) lam: 20.0


################################################################################
#                  Abort criterion reached: chi² <= 1 (0.55)                                                                             #
################################################################################
Last Chi2 from chi2History: 0.5478402181833611
```
