### ISSUE TITLE
ImportError: dynamic module does not define init function (PyInit___pygimli_)

### ISSUE THREAD

**Issue by wilocw** [gimli-org/gimli#29]
Have installed and built gimli and pygimli as per installation instructions - no obvious CMake errors, and running make was fine. Now running python3 (same as for python[2.7]), the import fails with the following message:

    wcw@sage:~/src/gimli/build/bin$ python3 -c 'import pygimli as pg; print(pg.__version)'
    dynamic module does not define init function (PyInit__pygimli_)
    Traceback (most recent call last):
     File "/home/wcw/src/gimli/trunk/python/pygimli/__init__.py", line 25, in <module>
         from . _pygimli_ import *
    ImportError: dynamic module does not define init function (PyInit__pygimli_)
    ERROR: cannot import the library '_pygimli_'.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/wcw/src/gimli/trunk/python/pygimli/__init__.py", line 73, in <module>
      _pygimli_.load = None
      AttributeError: 'NoneType' object has no attribute 'load'

This is for Ubuntu Desktop 14.2 LTS. Cannot find root of issue, but similar error occurs in installation on Windows 7 (MinGW/MSYS2) build. Have removed and reinstalled but issue remains. Any suggestions?

**Comment by florian-wagner** [comment]
Hey Will,

it seems like the python versions boost_python and pygimli are linked to are not the same, as python2 is probably still the default on your Ubuntu.

Try this please:
``` bash
cd ~/src && rm -rf gimli
curl -Ls install.pygimli.org | bash
```

**Comment by wilocw** [comment]
I ran the commands; the same error occurs, though now pointing to library in python dist-packages:

    ============================================================================
    ------------------------  TEST pyGIMLi installation ------------------------
    No module named _pygimli_
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/pygimli-1.0rc-py2.7.egg/pygimli/__init__.py", line 25, in     <module>
        from . _pygimli_ import *
    ImportError: No module named _pygimli_
    ERROR: cannot import the library '_pygimli_'.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/pygimli-1.0rc-py2.7.egg/pygimli/__init__.py", line 73, in <module>
        _pygimli_.load = None
    AttributeError: 'NoneType' object has no attribute 'load'
    --- ------------------------------------------------------------------------
    ~/src/gimli
    ~/src
    
    ========================================================================
    Set the following setting to use pygimli, either locally
    per session or permanently in your /home/wcw/.bashrc
    ------------------------------------------------------------------------
    
    export PYTHONPATH=/home/wcw/src/gimli/gimli/python:$PYTHONPATH
    export PATH=/home/wcw/src/gimli/gimli/python/apps:$PATH

I notice this is still python 2.7, though python3 is installed (v3.4.3) with

    alias python=python3

**Comment by florian-wagner** [comment]
If you want to use pygimli with py3 then I would definitely remove older system-wide py2 versions.

The installer finds the right python executable, the right liboost_python and the right numpy, all pointing to py3. That looks good so far, but triangle is missing. Can you show me the output of the installer call?

**Comment by wilocw** [comment]
I purged all remaining pygimli versions, and called ```make``` in the ```thirdParty/build-Clang-3.6.0-64/triangle``` directory. The attached file gives the output of the installer.

[installer.log.zip](https://github.com/gimli-org/gimli/files/60191/installer.log.zip)

**Comment by florian-wagner** [comment]
You're almost there. The only thing missing is the python library. As py3 is not the system-default, you probably have to do:

``` bash
sudo apt-get install python3-dev
```
Make sure libpython3.so exists on your system (usually in /usr/lib). Other than that, the log looks good.

**Comment by wilocw** [comment]
No luck. There's no lib ```libpython.so```, only ```libpython3.4.so``` but presume that should be fine? Dependencies as above with triangle, umfpack and cholmod libraries found correctly.

**Comment by florian-wagner** [comment]
Yes, `libpython3.4.so` is just fine. Does that mean, it works now?

To test if your installation is working correctly, run:
``` bash
sudo pip3 install pytest
python3 -c "import pygimli; pygimli.test(show=True)"
```

**Comment by wilocw** [comment]
It works now, thanks a lot.

Some tests failed but the errors are all ```_tkinter.TclError: no display name and no $DISPLAY environment variable``` which may be a result of the fact I am connected via SSH with no X11 forwarding at the moment. I've attached the output in case there's something else. Will check tomorrow on the physical machine and report.

[pygimli.test.log.zip](https://github.com/gimli-org/gimli/files/60509/pygimli.test.log.zip)

**Comment by florian-wagner** [comment]
Same command with show=False will run the tests without any graphical output. Good to hear that everything works. Will close this issue now.
