### ISSUE TITLE
building of documentation fails for newer packages

### ISSUE THREAD

**Issue by m-weigand** [gimli-org/gimli#290]
**applies to dev version**

Some newer versions of dependency packages break the documentation:

* pyvista at version 0.25.x fails to completely build the documentation (0.24.2 works, versions in between not checked)
* sphinxcontrib-bibtex 2.1.4 (1.0.0 works, versions in between not checked)

**Comment by florian-wagner** [comment]
:+1: Yes, same issue here. Between 0.24 and 0.25 there seemed to be a change in the streamline function, which is why the darcy flow example fails.

**Comment by juniorlove** [comment]
Thanks for the question and the answer!
Run 'conda install pyvista==0.24' and 'conda install sphinxcontrib-bibtex==1.0.0', the "qt5 not installed" problem was solved. But it was reminded that "No module named 'pyvista'. You need to install this optional dependency to properly visualize 3D data" then. I'm sorry but how to deal with that?

**Comment by juniorlove** [comment]
> 👍 Yes, same issue here. Between 0.24 and 0.25 there seemed to be a change in the streamline function, which is why the darcy flow example fails.

Thanks for the question and the answer!
Run 'conda install pyvista==0.24' and 'conda install sphinxcontrib-bibtex==1.0.0', the "qt5 not installed" problem was solved. But it was reminded that "No module named 'pyvista'. You need to install this optional dependency to properly visualize 3D data" then. I'm sorry but how to deal with that?

**Comment by florian-wagner** [comment]
@juniorlove If you have conducted `conda install -c conda-forge pyvista==0.24` (in the same activated conda environment), then this error should not occur. You can check with `python -c "import pyvista"`. We are currently working on a description on how to contribute to the documentation (and pygimli in general) with conda. @andieie has conducted a first test using the new `pgcore` package. I'll leave this issue open until we have this in place (i.e. an environment.yml to build the docs).

Cheers
Florian

**Comment by halbmy** [comment]
obviously solved by new releases.
