### ISSUE TITLE
How to mask cells bellow raypaths?

### ISSUE THREAD

**Issue by ejchicaq-unal** [gimli-org/gimli#291]
Hi
I wonder how to mask cells bellow raypaths to get an image like this:

[
![Screen Shot 2021-03-11 at 3 13 04 PM](https://user-images.githubusercontent.com/47264121/110848691-60694780-827c-11eb-94e8-753baa5851bc.png)
](url)

**Comment by halbmy** [comment]
I guess you are talking of Refraction seismics ("ray paths")? I am referring to the refraction example on https://www.pygimli.org/_examples_auto/2_seismics/plot_01_refraction_manager.html

Whereas the model coverage in ERT is a smoothly decaying function, the traveltime coverage `mgr.showResult(mgr.coverage())` looks like
![image](https://user-images.githubusercontent.com/7136401/110909994-09618200-8311-11eb-8166-79b1ce940d6e.png)

and cannot so easily transferred into alpha shading. However, there is a binary coverage `mgr.standardizedCoverage()` for covered (1) or not (0), which can be used for masking out not-covered model cells:
```
ax, _ = mgr.showResult(cMin=min(vp), cMax=max(vp), logScale=False, coverage=mgr.standardizedCoverage())
```
![image](https://user-images.githubusercontent.com/7136401/110910311-6fe6a000-8311-11eb-9687-d1ee5066579b.png)


This should actually be the default (without specifying `coverage`), we'll gonna change it (old behavior `coverage=1`).

**Comment by ejchicaq-unal** [comment]
Dear Thomas, thank you for your answer, it's very clear. Can I fill the cells with `coverage=0` with the velocity of adjacent cells?

**Comment by halbmy** [comment]
`coverage=0` would mean a white image. `coverage=1` means all cells are showing without alpha-shading, usually the not-covered cells as a quasi-constant or very smooth transition.
