### ISSUE TITLE
#question The Jacobian matrix size does not match my model size

### ISSUE THREAD

**Issue by geohang** [gimli-org/gimli#293]
### Problem description

The Jacobian matrix size does not match my model size.  I want to use the Jacobian matrix from pyGIMLi to the inversion by myself. I try to follow the example _**Four-point sensitivities**_. However, it seems that in my codes, the Jacobian matrix does not match my model size, which confused me. For example, if my model size is 4796, and the observed data size 63, the Jacobian matrix should be 63*4796. But I got 63*4259.  I attached the codes I used. Looking forward to your reply.

### Your environment

**Operating system**: Windows
**Python version**: 3.8
**pyGIMLi version**: 1.1.1+5.gc107727a
**Way of installation**:  Conda package

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 14 17:18:19 2021

@author: Hang
"""

import matplotlib.pyplot as plt
import numpy as np

import pygimli as pg
# pg.setTestingMode(True)
import pygimli.meshtools as mt
import pygimli.physics.ert as ert

###############################################################################
# Create geometry definition for the modelling domain.
#
# worldMarker=True indicates the default boundary conditions for the ERT

#this codes can be used in creat layered model
world = mt.createWorld(start=[-50, -20], end=[50, 0], layers=[-1, -5],
                       worldMarker=True)

rec = mt.createRectangle(start=[-50, -20], end=[0, -10], marker=3)

###############################################################################
# Merge geometry definition into a Piecewise Linear Complex (PLC)
geom = world + rec

###############################################################################
# Optional: show the geometry
pg.show(geom)



# Create a Dipole Dipole ('dd') measuring scheme with 21 electrodes.
scheme = ert.createERTData(elecs=np.linspace(start=-30, stop=30, num=21),
                           schemeName='wa')

###############################################################################
# Put all electrode (aka sensors) positions into the PLC to enforce mesh
# refinement. Due to experience, its convenient to add further refinement
# nodes in a distance of 10% of electrode spacing to achieve sufficient
# numerical accuracy.
for p in scheme.sensors():
    geom.createNode(p)
    geom.createNode(p - [0, 0.1])

# Create a mesh for the finite element modelling with appropriate mesh quality.
mesh = mt.createMesh(geom, quality=34)

# Create a map to set resistivity values in the appropriate regions
# [[regionNumber, resistivity], [regionNumber, resistivity], [...]
rhomap = [[0, 100.],
          [1, 100.],
          [2, 100.],
          [3, 100.]]

# Take a look at the mesh and the resistivity distribution
pg.show(mesh, data=rhomap, label=pg.unit('res'), showMesh=True)

rhomodel = pg.solver.parseArgToArray(rhomap, mesh.cellCount(), mesh)

res=[]
for i, r in enumerate(rhomodel):
    # print(i)
    # print(' ')
    # print(r)
    res.append(r)
    
cc=np.asarray(res)

fob = ert.ERTModelling()

# fob=mgr.createForwardOperator()
fob.setData(scheme)
fob.setMesh(mesh)
resp = fob.response(cc)
fob.createJacobian(cc)

rhos=[]
for i, r in enumerate(resp):
    rhos.append(r)
    
J=[]    
Joc=fob.jacobian()
for i, sens in enumerate(fob.jacobian()):
    print(i)
    print(sens)
    
    
...
```

### Expected behavior

I want to obtain the Jacobian matrix from my synthetic model.  The Jacobian matrix size should be 63*4796.

### Actual behavior

The actual Jacobian matrix size is 63*4259.

```
Paste output here.
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
For ERT modelling you typically append a boundary to make sure that there a no effects from imperfect boundary conditions. Mostly we use the marker 0 or 1 for it and the DC forward operator takes the lowest marker as background which is not part of the inversion but filled with resistivity from the inversion part. `sum(mesh.cellMarkers()==0)` yields 537 and if you subtract this number from the mesh cell number 4796 you end up in 4259. So you could either
1. append a region with the lowest marker thus resulting in better values, or
2. explicitly set all markers to one `mesh.setCellMarkers(pg.Vector(mesh.cellCount(), 1))`

**Comment by geohang** [comment]
Got it. Thanks a lot!

Best,
Hang
