### ISSUE TITLE
Forward Model Calculation

### ISSUE THREAD

**Issue by bflinchum** [gimli-org/gimli#295]
### Problem description

I am tying to use PyGiMLi to invert some Sh wave data. The S-wave are WAY too fast. Essentially I am worried that I am picking S-wave to P-wave converted waves. What I want to do is take my P-wave model divide it by 3 and then re-traces the rays and use those travel-times as a guide to picking. For some reason this is not working as I think it is.

Essentially when I re-trace the rays I don't actually reproduce the velocity model that was created the rays. Here is the logic

1. Invert my P-wave travel times
2.  Extract the paraModel and divide it by 3
3. Set the inversion iterations to 0 and invert the data using the last inversion as a start model.
4. Write out the "response". 

The issue is that when I read in the response and invert the data it doesn't even come close to matching the oginal P-wave divided by three.  Any help is greatly appreciated.

### Your environment

**Operating system**: Mac
**Python version**: 3.7.9
**pyGIMLi version**: 1.1.0
**Way of installation**: manual compilation from source

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
import pygimli as pg
from pygimli.physics import TravelTimeManager
import matplotlib.pyplot as plt
import numpy as np
from pygimli.physics.traveltime import load as loadGimliTT


#INVERSION PARAMETERS**************************
inFile = 'BW_072613_PwavePicks_gimliInput.txt'
maxDepth = 80
meshDx = 0.5
maxTriArea = 20
smoothing = 100
vertWeight = 0.5
minVel = 500
maxVel = 4500
maxIterations = 20

#RREAD IN THE DATA
data = loadGimliTT(inFile)
ra = TravelTimeManager(data)

#CREATE THE MESH
mesh = ra.createMesh(data=ra.data,paraDepth=maxDepth,paraDX=meshDx,paraMaxCellSize=maxTriArea)

#INVERST the DATA
ra.invert(data=ra.data,mesh=mesh,lam=smoothing,zWeight=vertWeight,useGradient=True,vTop=minVel,vBottom=maxVel,verbose=True,maxIter=maxIterations)


#Print out important model Inversion results
print('***********P-WAVE RESULTS***********')
s2 = "Chi2 = " + str("{:0.4f}".format(ra.inv.chi2())) + "\n"
s3 = "RMS = " + str("{:0.4f}".format(1000*ra.inv._inv.absrms())) + " ms\n"
print(s2)
print(s3)

#PLot the data
vel = ra.paraModel()
fig1 = plt.figure('Model Results')
fig1.set_size_inches([8,2])
ax = fig1.add_subplot(211)
pg.show(mesh, vel, coverage=ra.standardizedCoverage(),cMin=100,cMax=4000,cmap='jet_r',ax=ax)
pg.viewer.mpl.drawSensors(ax, data.sensorPositions(), diam=0.5, color="k")
ax.set_xlabel('Distance (m)')
ax.set_ylabel('Elevation (m)')
ax.set_title('P-wave Velocity (m/s)')

#plot the data divided by 3 (this is what the rays should be traced through!)
ax = fig1.add_subplot(212)
pg.show(mesh, vel/3, coverage=ra.standardizedCoverage(),cMin=100,cMax=4000,cmap='jet_r',ax=ax)
pg.viewer.mpl.drawSensors(ax, data.sensorPositions(), diam=0.5, color="k")
ax.set_xlabel('Distance (m)')
ax.set_ylabel('Elevation (m)')
ax.set_title('P-wave Velocity (m/s)')



#THIS IS THE STEP THAT IS CONFUISNG TO ME
#This should calcualte the response to the start model
ra.invert(data=ra.data,mesh=mesh,lam=smoothing,zWeight=vertWeight,verbose=True,startModel=1/(vel/3),maxIter=0)
modTT2 = np.array(ra.inv.response)

#Repolot the data
#This should be vp/3 but it's not even close!!
vel = ra.paraModel()
fig1 = plt.figure('Model Results Changed Velocity')
fig1.set_size_inches([4,2])
ax = fig1.add_subplot(111)
pg.show(mesh, vel, coverage=ra.standardizedCoverage(),cMin=100,cMax=4000,cmap='jet_r',ax=ax)
pg.viewer.mpl.drawSensors(ax, data.sensorPositions(), diam=0.5, color="k")
ax.set_xlabel('Distance (m)')
ax.set_ylabel('Elevation (m)')
ax.set_title('P-wave Velocity (m/s)')


#WRite out the picks
# sensorPostions_x  =np.array(ra.data.sensorPositions())[:,0]
# #test = np.column_stack((ra.data('s'),ra.data('g'),modTT,(pickTT-modTT)*1000))
# test = np.column_stack((ra.data('s'),ra.data('g'),modTT2))
# for i in range(0,len(test)):
#     test[i,0] = sensorPostions_x[int(test[i,0])]
#     test[i,1] = sensorPostions_x[int(test[i,1])]
# np.savetxt('testFile.txt',test,fmt='%10.4f')
...
```

### Expected behavior

The second inversion should match the second subplot in the first figure. It's not EVEN CLOSE!

[BW_072613_PwavePicks_gimliInput.txt](https://github.com/gimli-org/gimli/files/6214177/BW_072613_PwavePicks_gimliInput.txt)

**Comment by halbmy** [comment]
Dear Brady,
sorry for the late response due to Easter holidays. 

Even if I don't get the point of inverting the same data again with `maxIter=0` except for technical reasons (something is done under the hood in inversion), you should obtain the starting model. We should dig why this is not the case and restructure the traveltime model a bit in general.

However, if you just want the forward response you can have it by
```
resp3 = ra.fop.response(1/(vel/3))
```
and plot it along with the data.
```
fig, ax = plt.subplots()
drawFirstPicks(ax, ra.data, marker="x")
drawFirstPicks(ax, ra.data, tt=resp3, marker="")
```
Or am I completely wrong?

**Comment by bflinchum** [comment]
Hey @halbmy

No worries on the reply, I am always shocked with how fast your team is at responding.

Using the method "simulate" fixed the problem.

The reason I was inverting with 0 iterations was because of how I did it in the past, you can see the thread here (https://github.com/gimli-org/gimli/issues/289).

Feel free to close this issue. Here is my code that works correctly now:


`import pygimli as pg
from pygimli.physics import TravelTimeManager
import matplotlib.pyplot as plt
import numpy as np
from pygimli.physics.traveltime import load as loadGimliTT


#INVERSION PARAMETERS**************************
inFile = 'CEF_2021_0315_Pwave_picks_after_v2_gimliInput.txt'
maxDepth = 80
meshDx = 0.5
maxTriArea = 20
smoothing = 100
vertWeight = 0.5
minVel = 500
maxVel = 4500
maxIterations = 20
vpvsRatio = 1.75
#RREAD IN THE DATA
data = loadGimliTT(inFile)
ra = TravelTimeManager(data)

#CREATE THE MESH
mesh = ra.createMesh(data=ra.data,paraDepth=maxDepth,paraDX=meshDx,paraMaxCellSize=maxTriArea)

#INVERST the DATA
ra.invert(data=ra.data,mesh=mesh,lam=smoothing,zWeight=vertWeight,useGradient=True,vTop=minVel,vBottom=maxVel,verbose=True,maxIter=maxIterations)


#Print out important model Inversion results
print('***********P-WAVE RESULTS***********')
s2 = "Chi2 = " + str("{:0.4f}".format(ra.inv.chi2())) + "\n"
s3 = "RMS = " + str("{:0.4f}".format(1000*ra.inv._inv.absrms())) + " ms\n"
print(s2)
print(s3)
    
#PLot the data
vel = ra.paraModel()
fig1 = plt.figure('Model Results')
fig1.set_size_inches([8,2])
ax = fig1.add_subplot(211)
pg.show(mesh, vel, coverage=ra.standardizedCoverage(),cMin=100,cMax=4000,cmap='jet_r',ax=ax)
pg.viewer.mpl.drawSensors(ax, data.sensorPositions(), diam=0.5, color="k")
ax.set_xlabel('Distance (m)')
ax.set_ylabel('Elevation (m)')
ax.set_title('P-wave Velocity (m/s)')

#plot the data divided by 3 (this is what the rays should be traced through!)
ax = fig1.add_subplot(212)
pg.show(mesh, vel/vpvsRatio, coverage=ra.standardizedCoverage(),cMin=100,cMax=4000,cmap='jet_r',ax=ax)
pg.viewer.mpl.drawSensors(ax, data.sensorPositions(), diam=0.5, color="k")
ax.set_xlabel('Distance (m)')
ax.set_ylabel('Elevation (m)')
ax.set_title('P-wave Velocity (m/s)')



#THIS IS THE STEP THAT IS CONFUISNG TO ME
#This should calcualte the response to the start model

data3 = ra.simulate(slowness=1/(vel/vpvsRatio),scheme=ra.data,mesh=mesh,verbos=True)
data3.save('simulatedData_1p4.dat')

#WRite out the picks
modTT2 = data3('t')
sensorPostions_x  =np.array(data3.sensorPositions())[:,0]
#test = np.column_stack((ra.data('s'),ra.data('g'),modTT,(pickTT-modTT)*1000))
test = np.column_stack((data3('s'),data3('g'),modTT2))
for i in range(0,len(test)):
    test[i,0] = sensorPostions_x[int(test[i,0])]
    test[i,1] = sensorPostions_x[int(test[i,1])]
np.savetxt('/Users/bflinch/Dropbox/Clemson/Research/ResearchProjects/SwaveRefraction/S-wavePicking/CEF_2021_0315_PwavePicks_div1p75.txt',test,fmt='%10.4f')

data2 = loadGimliTT('simulatedData.dat')
ra2 = TravelTimeManager(data2)
#ra2.invert(data=ra2.data,mesh=mesh,lam=smoothing,zWeight=vertWeight,verbose=True,startModel=1/(vel/3),maxIter=0)
ra2.invert(data=ra2.data,mesh=mesh,lam=smoothing,zWeight=vertWeight,useGradient=True,vTop=minVel,vBottom=maxVel,verbose=True,maxIter=maxIterations)


#PLot the data
vel2 = ra2.paraModel()
fig2 = plt.figure('Model Results 2')
#fig1.set_size_inches([8,2])
ax = fig2.add_subplot(211)
pg.show(mesh, vel2, coverage=ra2.standardizedCoverage(),cMin=100,cMax=4000,cmap='jet_r',ax=ax)
ax.set_xlabel('Distance (m)')
ax.set_ylabel('Elevation (m)')
ax.set_title('P-wave Velocity (m/s)')

#plot the data divided by 3 (this is what the rays should be traced through!)
ax = fig2.add_subplot(212)
pg.show(mesh, vel/3, coverage=ra2.standardizedCoverage(),cMin=100,cMax=4000,cmap='jet_r',ax=ax)
#pg.viewer.mpl.drawSensors(ax, data.sensorPositions(), diam=0.5, color="k")
ax.set_xlabel('Distance (m)')
ax.set_ylabel('Elevation (m)')
ax.set_title('P-wave Velocity (m/s)')


vpvs = np.linspace(1,10,100)
pr = 0.5*((vpvs**2-2)/(vpvs**2-1))
fig9 = plt.figure('PR')
ax = fig9.add_subplot(111)
ax.plot(vpvs,pr,'k')`
