### ISSUE TITLE
Different meshing result in different solution ERT 3D

### ISSUE THREAD

**Issue by GeorgeLiang3** [gimli-org/gimli#301]
### Problem description

In the [Example](https://www.pygimli.org/_examples_auto/3_dc_and_ip/plot_modTank3d.html#sphx-glr-examples-auto-3-dc-and-ip-plot-modtank3d-py) **3D modeling in a closed geometry**, if one change the resistivity for both facies to 10 
`res = [[1, 10.0], [2, 10.0]] .`
instead of 10 and 100 Ohm respectively to each facies, provided in the original example
`res = [[1, 10.0], [2, 100.0]]  # map markers 1 and 2 to 10 and 100 Ohmm, resp.`

### Your environment

**Operating system**: Mac
**Python version**: 3.7
**pyGIMLi version**: 1.1.0
**Way of installation**:  Conda 
### Steps to reproduce

Follow exactly as described in the 3D example:

```python
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics.ert import simulate as simulateERT

plc = mt.createCube(size=[0.99, 0.5, 1.0], pos=[0.495, 0.25], boundaryMarker=1)

filename = pg.getExampleFile("modeltank.shm")
shm = pg.DataContainerERT(filename)

for s in shm.sensors():
    plc.createNode(s, marker=-99)

plc.createNode([0.5, 0.5, -0.5], marker=-999)

plc.createNode([0.75, 0.25, 0.5], marker=-1000)

for s in plc.positions(pg.find(plc.nodeMarkers() == -99)):
    plc.createNode(s - [0.0, 0.0, 1e-3/2])

# Also refine the reference node
plc.createNode([0.5, 0.5, -0.5 - 1e-3/2])

mesh = mt.createMesh(plc, area = 1)

hom = simulateERT(mesh, res=1.0, scheme=shm, sr=False,
                  calcOnly=True, verbose=True)

hom.save('homogeneous.ohm', 'a b m n u')


cube = mt.createCube(size=[0.3, 0.2, 0.8], pos=[0.7, 0.2], boundaryMarker=2)
plc += cube

mesh = mt.createMesh(plc,area = 1)
print(mesh)


res = [[1, 10.0], [2, 10.0]]  # map markers 1 and 2 to 10 and 100 Ohmm, resp.
het = simulateERT(mesh, res=res, scheme=shm, sr=False,
                  calcOnly=True, verbose=True)
pg.show(mesh, notebook=True)

het.set('k', 1.0/ (hom('u') / hom('i')))
het.set('rhoa', het('k') * het('u') / het('i'))

het.save('simulated.dat', 'a b m n rhoa k u i')

np.testing.assert_approx_equal(het('rhoa')[0], 9.95, 2)

print(np.max(het('rhoa').array()))
...
```

### Expected behavior

The apparent resistivity is expected to be 10 as the model is homogenous 

### Actual behavior

output
```
8.956386691401086
```

A workaround I find is to calculate the geometry factor after creating the geobody.

```

res = [[1, 1.0], [2, 1.0]]
hom = simulateERT(mesh, res=res, scheme=shm, sr=False,
                  calcOnly=True, verbose=True)
```
output
```
9.999999999999224
```
However, the issue is with different meshing, the simulation field is different.

**Comment by halbmy** [comment]
Of course, the result of a numerical computation depends on the mesh quality. (Note that the simulate function does NOT do adaptive mesh refinement until the solution is perfectly accurate) For a sufficiently fine mesh, one would of course expect a constant apparent resistivity of 10 Ohmm. In our case we have a distribution
![image](https://user-images.githubusercontent.com/7136401/113856919-266b6280-97a2-11eb-8a04-3c6b74829562.png)
that shows a standard deviation of about 3% which is of course not quite sufficient. By decreasing the maximum cell size using the `area=` keyword. A value of 0.00001 (in both simulate runs) decreases the inaccuracy below 1% at the cost of increasing the node number from 10k to 25k.
![image](https://user-images.githubusercontent.com/7136401/113857988-7c8cd580-97a3-11eb-8e73-75556f4303de.png)
For improving accuracy even further, a quadratic refinement is more efficient (Rücker et al. 2006).

**Comment by halbmy** [comment]
Regarding quadratic refinement: if you replace the meshing procedure (both occurrences) by 
```
mesh1 = mt.createMesh(plc, quality=1.3)
mesh = mesh1.createP2()
```
you end up in a standard deviation (`np.std(het["rhoa"])/10*100`) of 0.15% with a node number of about 50k, something that you can hardly reach without extreme spatial refinement.

**Comment by halbmy** [comment]
Another note on your workaround: taking the same mesh for computing geometric factors as for doing the actual computation is meaningless as you end up with the correct solution but still the same wrong results. For simulating point electrodes (infinite 1/r potential) you need to do some effort unless you use secondary potentials. There is vast literature on that.

**Comment by GeorgeLiang3** [comment]
@halbmy Thanks very much for the detailed answer. Could you please explain what do you mean by '**you end up with the correct solution but still the same wrong results**'?

**Comment by halbmy** [comment]
I meant you end up with exactly 10 Ohmm but the result is not correct due to numerical inaccuracies. So there is no gain in using geometric factors based on the same mesh.
