### ISSUE TITLE
2.5D forward and inversion analysis

### ISSUE THREAD

**Issue by yusuket** [gimli-org/gimli#304]
### Problem description
I am trying to do forward and inverse analysis in 2.5D, and I thought I would use ERTModellingReference successfully, so I did a lot of trial and error, but it did not work.
The example below shows the syntax for computing in two dimensions.
Please let me know if you have any suggestions on how I can modify it to do the calculation in 2.5 dimensions.

Also, in my current calculation, when I do the forward analysis using the quadrupole method, I create dipoles only next to each other.
How can I select any combination of electrodes for the forward analysis?

### Your environment

**Operating system**: Windows
**Python version**: 3.7.6
**pyGIMLi version**: 1.1.0`
**Way of installation**:  Conda package

### Steps to reproduce

```python
import pygimli as pg
import matplotlib.pyplot as plt
import numpy as np
import pygimli.meshtools as mt
import pygimli.physics.ert as ert

#analytical model
#model for Forword modeling
geom = mt.createWorld(start=[0.0, 0.0],end=[30.0, -20.0],layers=[-1,-5], worldMarker=True)
pg.show(geom,boundaryMarker=True)

#sensors
_scheme = 'dd'
sens1 = np.arange( 8.0, 23.0, 1.0)
sensors = np.zeros((15,2))
sensors[:,0] = np.hstack([sens1])

#data container
f_name = 'issue00'

# create sensor array
scheme = ert.createERTData(elecs=sensors,schemeName=_scheme)

# Subdivide the mesh around the electrode.
for p in scheme.sensors():
    geom.createNode(p)
    geom.createNode(p - [0.0,0.1])

# Create a mesh for the finite element modelling with appropriate mesh quality.
mesh_1 = mt.createMesh(geom, area = 2, quality=34)

# Create a map to set resistivity values in the appropriate regions
# [[regionNumber, resistivity], [regionNumber, resistivity], [...]
rhomap_1 = [[1, 10],[2, 50],[3, 20]]

# Take a look at the mesh and the resistivity distribution
pg.show(mesh_1, data=rhomap_1, label=pg.unit('res'),
        showMesh=True,cMap = 'jet')
pg.show(mesh_1, boundaryMarker = True)

#Forward modeling 2D
ERT = pg.physics.ert.ERTManager(verbose=True, sr=True)

data_1 = ERT.simulate(mesh_1, scheme=scheme, res=rhomap_1,
                      noiseLevel=0.01,noiseAbs=0.0, seed=1337)
data_1.remove(data_1['rhoa'] < 0)
pg.info('Filtered rhoa (min/max)', min(data_1['rhoa']),
        max(data_1['rhoa']))

data_1.save(f_name+'_For.dat')

# import forward modeling data in ERTManager
mgr = ert.ERTManager(f_name+'_For.dat')

#Create grid model
grid_1 = pg.createGrid(x=np.arange(0.0, 30.5 , 0.5),
                       y=np.arange(0.0, -20.5, -0.5),
                       marker=2)
pg.show(grid_1)

# Add a mesh around the grid model for inverse analysis.
model_1 = mt.appendTriangleBoundary(grid_1, marker=1,xbound=50,
                                    ybound=40,area = 20,
                                    smooth=True,isSubSurface=True)
Invmodel = pg.show(model_1, markers=True, showMesh = True,
                   boundaryMarker=True )

# Inversion
model_1 = mgr.invert(data_1, mesh=model_1, lam=200, verbose=True)
model_1.save(f_name+'_Inv.dat')

```

**Comment by halbmy** [comment]
You're pretty close. The problem are the boundary markers. If they are not Neumann or Mixed type, the mesh is considered a general topography and thus total potential calculation where the electrodes cannot be found as nodes. When creating the grid, you should use the flag `worldBoundaryMarker=True` to account for this.
```
grid_1 = pg.createGrid(x=np.arange(0.0, 30.5 , 0.5),
                       y=np.arange(0.0, -20.5, -0.5),
                       marker=2, worldBoundaryMarker=True)
mesh_1 = mt.appendTriangleBoundary(grid_1, marker=1, xbound=50,
                                   ybound=40, area=20,
                                   smooth=True, isSubSurface=True)
```

You should better call the result `mesh_1` and not `model_1` which is later overwritten by the model vector, which in turn cannot be saved as data.

**Comment by halbmy** [comment]
However, when doing so I found a bug that must have been introduced recently:
```
grid_1 = pg.createGrid(x=np.arange(0.0, 30.5 , 0.5),
                       y=np.arange(0.0, -20.5, -0.5),
                       marker=2, worldBoundaryMarker=True)
# Add a mesh around the grid model for inverse analysis.
mesh_1 = mt.appendTriangleBoundary(grid_1, marker=1, xbound=50,
                                   ybound=40, area=20,
                                   smooth=True, isSubSurface=True)
pg.show(mesh_1, markers=True)
```
generates
![image](https://user-images.githubusercontent.com/7136401/114729108-fa228980-9d3f-11eb-88bd-318f8525467f.png)
whereas
```
grid_1 = pg.createGrid(x=np.arange(0.0, 30.5 , 0.5),
                       y=np.arange(-20, 0.01, 0.5),
                       marker=2, worldBoundaryMarker=True)
# Add a mesh around the grid model for inverse analysis.
mesh_1 = mt.appendTriangleBoundary(grid_1, marker=1, xbound=50,
                                   ybound=40, area=20,
                                   smooth=True, isSubSurface=True)
pg.show(mesh_1, markers=True)
```
(i.e. just the y vector in the other direction) generates
![image](https://user-images.githubusercontent.com/7136401/114729348-2f2edc00-9d40-11eb-80ea-98f0c1b85ede.png)
Both are wrong and the bug should be fixed so that the top boundary gets -1.

**Comment by halbmy** [comment]
As a workaround, the following will do:
```
grid_1 = pg.createGrid(y=np.arange(0.0, 30.5 , 0.5),
                       x=-np.arange(0.0, 20.5, 0.5),
                       marker=2, worldBoundaryMarker=True)
grid_1.swapCoordinates(0, 1)
mesh_1 = mt.appendTriangleBoundary(grid_1, marker=1, xbound=50,
                                   ybound=40, area=20,
                                   smooth=True, isSubSurface=True)
pg.show(mesh_1, markers=True)
```
![image](https://user-images.githubusercontent.com/7136401/114730277-02c78f80-9d41-11eb-94e0-e4c0787a5bd5.png)

**Comment by yusuket** [comment]
@halbmy 
Thank you for the quick solution.
I now understand that if I set `worldBoundaryMarker=True,` the boundary conditions appropriate for 2.5D analysis will be set.
Incidentally, a boundary marker of -2 means a mixed boundary condition, and -1 means a Neumann boundary condition with zero normal derivative, right?
Also, when I input `pg.show(mesh_1,markers=True),` the same picture is not output, is it because of the version difference?

**Comment by yusuket** [comment]
What should I do about the electrode selection for sequential analysis mentioned at the end of the first question?
The image I want to do is as follows.
![image](https://user-images.githubusercontent.com/70733916/114816621-7629d980-9df3-11eb-9d0b-bdb1e23424b5.png)

**Comment by halbmy** [comment]
> Incidentally, a boundary marker of -2 means a mixed boundary condition, and -1 means a Neumann boundary condition with zero normal derivative, right?

Exactly

> Also, when I input `pg.show(mesh_1,markers=True),` the same picture is not output, is it because of the version difference?

Well the image should be very similar. You can just copy the image (e.g. in Spyder) and paste it here (Ctrl+V).

**Comment by halbmy** [comment]
For the electrode array, you should just do some simple logical programming (that's not our business):
```
A, B, M, N = [], [], [], []
for a in range(nel):
    b = a + 2
    for n in range(a+1, nel, 2):
        m = n + 2
        A.append(a)
...
data = pg.DataContainerERT()
for i in range(nel):
   data.createSensor([i*5.0, 0, 0])

data.resize(len(A))
data["a"] = np.array(A)
...
```

**Comment by yusuket** [comment]
I tried it with both Spyder and jupyter, but neither of them produced the same picture as yours. The output is shown below:
`import numpy as npimport pygimli as pg`

**Comment by yusuket** [comment]
I tried with jupyter and Spyder, but it still didn't output the same picture as yours. The output results are as follows:

```
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt

grid_1 = pg.createGrid(y=np.arange(0.0, 30.5 , 0.5),
                       x=-np.arange(0.0, 20.5, 0.5),
                       marker=2, worldBoundaryMarker=True)
grid_1.swapCoordinates(0, 1)
mesh_1 = mt.appendTriangleBoundary(grid_1, marker=1, xbound=50,
                                   ybound=40, area=20,
                                   smooth=True, isSubSurface=True)
pg.show(mesh_1, markers=True)
```
![image](https://user-images.githubusercontent.com/70733916/114955132-ee95a680-9e96-11eb-97ca-a46c8d4f7c2a.png)


also

`pg.show(mesh_1,boundaryMarker=True)`

![image](https://user-images.githubusercontent.com/70733916/114955145-f6ede180-9e96-11eb-8f59-23b057a81ffe.png)




Thank you very much for the answer about the electrode array, I understood that I should input the electrode array to be used in a, b, m, and n of `Datacontainner.`

**Comment by yusuket** [comment]
For the electrode array, I am able to achieve the issue by using pybert.
`sensors = pb.createData(elecs,schemeName='dd',spacings=[1,2,3,4])`

**Comment by carsten-forty2** [comment]
We currently work on release 1.2, which will come in the next days. I rewrote the `appendTriangleBoundary method and fixed the bug in `create2DGrid`. The output should be also same after the update.

**Comment by yusuket** [comment]
@carsten-forty2 
Thank you for your reply. I'm looking forward to the release of version 1.2.

**Comment by carsten-forty2** [comment]
1.2.1 is  released now, `appendTriangleBoundary` no have a slight different behaviour but should now work as supposed to be.
