### ISSUE TITLE
ERT and GPR joint inversion, adding borehole constraints

### ISSUE THREAD

**Issue by anzhijiang** [gimli-org/gimli#309]
### Problem description

I would like to know whether the joint inversion of ERT and GPR can be performed through pygimli.

### Your environment

**Operating system**: Linux
**Python version**: 3.6
**pyGIMLi version**: 1.1.0
**Way of installation**: Conda package

We collected 3D ERT data and inverted it, and got very good results. In the survey area, we also have several GPR lines. 
1. How to  joint inversion of ERT and GPR by pygimli?
2. Or in ERT inversion, add these GPR constraints (like adding geostatistical information)?
3. Can I add borehole constraints (geostatistical information, such as resistivity, structure division, etc.) in ERT inversion using pygimli?

### code
We only complete the calculation of 3D ERT, and the codes run well.

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
1. What exacty do you mean with joint inversion? A joint inversion would mean to invert for the same or a related underlying property, e.g. water content or saturation. But I guess you're talking about some sort of coupling.
2. Under https://github.com/gimli-org/transform2021, you will find a jupyter notebook doing ERT inversion, at the end we introduce a straight line as an allowed interface. Have a look at notebook 1 on how to create a polygone.
3. For structural (lithological) changes you can insert small lines. For borehole resistivity, I would refer to the paper of Wunderlich et al. (2018).

Wunderlich, T., Fischer, P., Wilken, D., Hadler, H., Erkul, E., Mecking, R., Günther, T., Heinzelmann, M., Vött,
A. & Rabbel, W. (2018): Constraining Electric Resistivity Tomography by Direct Push Electric Conductivity logs and vibracores: An exemplary study of the Fiume Morto silted riverbed (Ostia Antica, Western Italy). Geophysics 83(3), B87-B103, doi:10.1190/geo2016-0660.1.

**Comment by anzhijiang** [comment]
Thank you for your reply. I will refer to the paper and jupyter notebook you mentioned.
