### ISSUE TITLE
pygimli.physics.ert issue 

### ISSUE THREAD

**Issue by danastritampubolon** [gimli-org/gimli#310]
Hi, I try to make 2D FEM Modelling with 1D VES. In this Part, I was stuck in creating data configuration. 

this is my code ( It's was similar with code from manual book)
```
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import ert
#from pygimli.physics.ert import simulate as simulateERT
from pygimli.physics.ert import VESModelling, VESCModelling
#from pygimli.physics.ert import createERTData
scheme = ert.createData(pg.utils.grange(start=1, end=24, dx=1, n=10, log=True),
                        sounding=True)
```
and this is the output 
```
  File "/Users/danastritampubolon/untitled0.py", line 16, in <module>
    scheme = ert.createData(pg.utils.grange(start=1, end=24, dx=1, n=10, log=True),

AttributeError: module 'pygimli.physics.ert' has no attribute 'createData'
```
My  environment

Operating system: Mac
Python version: Python 3.7
pyGIMLi version: 1.1.0+0.g47c8d810 (with local changes)
Way of installation: Conda package

**Comment by halbmy** [comment]
Note that the code is running with the current version 1.2.

The function was formerly called `createERTData` (but `ert.createData` makes more sense), so in pg 1.1 you can just replace the call but as pg 1.1 is half a year old, we encourage you to update pyGIMLi.

**Comment by danastritampubolon** [comment]
thank you !!
