### ISSUE TITLE
2D ERT modelation with topography, corrupt mesh error

### ISSUE THREAD

**Issue by Egon141** [gimli-org/gimli#315]
### Problem description

Starting the modeling process with priorly defined mesh (w topography) for ERT-Modelation/Inversion results in "corrupt mesh" error.

### Your environment

**Operating system**: Windows
**Python version**: Python 3.8.10 /Spyder 5.0.2
**pyGIMLi version**: 1.2.1

### Steps to reproduce

My approach is heavily based on the 2D ERT modeling and inversion tutorioal on pyGIMLY.org (https://www.pygimli.org/_examples_auto/3_dc_and_ip/plot_01_ert_2d_mod_inv.html#sphx-glr-examples-auto-3-dc-and-ip-plot-01-ert-2d-mod-inv-py), with the difference of the inclusion of topography into the model.

The main difference is that I try not to use a "createWorld" world-mesh (as I don't see how to build a non rectangular world from this base) but instead build a layered model, as seen in the Refraction Manager tutorial (https://www.pygimli.org/_examples_auto/2_seismics/plot_01_refraction_manager.html#sphx-glr-examples-auto-2-seismics-plot-01-refraction-manager-py).

```
import matplotlib.pyplot as plt
import numpy as np
import pygimli as pg
#pg.setTestingMode(True)
import pygimli.meshtools as mt
from pygimli.physics import ert

#create a new world
#world = mt.createWorld(start=[-5, 236], end=[25, 226], worldMarker=True) #just a try, tb ignored

#Create surface layer
surf = mt.createPolygon([[-5,236],[4, 235], [14, 235], [19,233], [25,233], [25,226], [-5,226]], addNodes=5, interpolate='linear', isSubSurface=False)
boundary = mt.createPolygon([[25,233], [25,226], [-5,226], [-5,236]], addNodes=5, interpolate='linear', isSubSurface=False)

#create some anomalies
top_layer = mt.createPolygon([[-5, 233], [-5,235.5],[4, 234.5], [14, 234.5], [19,232.5], [25,232.5], [25,230]], marker=1, interpolate='linear', isClosed=True, isSubSurface=True)
rock = mt.createPolygon([[-5,233],[25, 230], [25, 226], [-5,226]], marker=2, interpolate='linear', isClosed=True, isSubSurface=True)
block = mt.createCircle(pos=[10, 233], radius=[2, 1],  area=0.1, marker=3, isSubSurface=True, isClosed=True)




#merge anomalies with mesh, show geometry
geom = surf + boundary + top_layer + rock + block
#geom = world + surf + boundary + top_layer + rock + block #a try if the problem comes from non-rectangular/closed world? 
pg.show(geom, markers=False)


#(re-)calculate mesh & show it
mesh = mt.createMesh(geom, quality=32, area=0, smooth=None)
pg.show(mesh, markers=True)
```

Until here, no obvious problems arise (?), the layers  for which its necessary should be all closed, etc.

```
#Create a Dipole Dipole (‘dd’) measuring scheme with 21 electrodes.
scheme = ert.createData(elecs=np.linspace(start=0, stop=20, num=21),
                           schemeName='dd')
#**could the electrode positioning be a problem? I dont see how to fix them to my topo?**

#Put all electrode (aka sensors) positions into the PLC to enforce mesh refinement. Due to experience, its convenient to add further refinement nodes in a distance of 10% of electrode spacing to achieve sufficient numerical accuracy.

for p in scheme.sensors():
    geom.createNode(p)
    geom.createNode(p - [0, 0.1])
    
#Create a mesh for the finite element modelling with appropriate mesh quality.
mesh = mt.createMesh(geom, quality=34)

#Create a map to set resistivity values in the appropriate regions
#[[regionNumber, resistivity], [regionNumber, resistivity], [...]
rhomap = [
          [0, 0.],
          [1, 100.],
          [2, 150.],
          [3, 600.]]


#Take a look at the mesh and the resistivity distribution
pg.show(mesh, data=rhomap, label=pg.unit('res'), showMesh=True)
```

Again, until here, no obvious problems arise (?), I ask myself however, if the calculated sensor-nodes fit/are fit to the topography... again don't now how to check

```
#Perform the modeling with the mesh and the measuring scheme itself and return a data container with apparent resistivity values, geometric factors and estimated data errors specified by the noise setting. The noise is also added to the data. Here 1% plus 1µV. Note, we force a specific noise seed as we want reproducable results for testing purposes.

data = ert.simulate(mesh, scheme=scheme, res=rhomap, noiseLevel=1,
                    noiseAbs=1e-6, seed=1337)
```

This code results in the mentionend runtime error
RuntimeError: C:/msys64/home/halbm/gimli/gimli/core/src/mesh.cpp:788		GIMLI::Cell* GIMLI::Mesh::findCell(const RVector3&, size_t&, bool) **const  no cells for this node. This is a corrupt mesh**

Which tells me of some problem with my mesh, or better: some node in the mesh. I tried reducing the mesh to a simple rectangle/single layer, with the same result. So there might be something wrong from the very beginning? Also what I thought, maybe a problem with the nodes of the simulated probes, as these seem not to work/consider the elevation/topography?

**Comment by carsten-forty2** [comment]
The error means that the requested nodes are not part of the mesh, i.e. they have no assigned cells or boundary elements. This usually happens when a node lies outside the geometry definition so the mesh generator ignores these outside nodes.

In your case it looks like your geometry bounding box is about 226 m and 236 m in y direction but the default y coordinate for your sensors (from createData) is 0m and thus outside. 

You can add `showNodes=True` to the `show(geom)` command to see all nodes.

**Comment by Egon141** [comment]
Thank you! 
Although I think get what you're saying, I am not sure (or don't see) how/if this really applies here.
Isnt the createData refering to the x-axis? The 226-236 refer to x (?, see fig), so the sensors would be aligned vertically if createData referred to y?

![Figure 2021-05-25 142446](https://user-images.githubusercontent.com/84779476/119497594-12d18680-bd65-11eb-96a8-0271793bcbbc.png)

**Comment by carsten-forty2** [comment]
I see your point .. usually its in the different situation .. you have your electrode positions from the measurement and then interpolate the topography from it. You can create your surface polygon from these positions.

Alternatively you can use: https://www.pygimli.org/pygimliapi/_generated/pygimli.meshtools.html#pygimli.meshtools.interpolateAlongCurve
which is supposed to find points along a given curve (your surface),  more or less accurate to a given distance list.

**Comment by Egon141** [comment]
Thank you for that input. I (almost) got it working with the second approach. However, it seems to be pretty "picky" with the y values, which in the end resulted in the a "no node for electrode"-error. As it worked with the interpolate-approach on a flat plane, the approximation to the topography doesnt work like hoped, the interpolation seems to put some values above the actual surface/mesh which cannot be processed. 
Sorry for not showing code here... I ended up doing what I was trying to avoid in the beginning: manually give the m-wise y/z values for topo (-> and electrodes), which works perfectly:

```
#Create surface layer
topo=np.array([
               [0,235.7], 
               [1,235.6], 
               [2,235.3], 
               [3,235.1],
               [4,235],
               [5,235],
               [6,235],
               [7,235.1],
               [8,235],
               [9,235],
               [10,235],
               [11,235],
               [12,235],
               [13,235],
               [14,235],
               [15,234.8],
               [16,234.5],
               [17,234],
               [18,233.5],
               [19,233]
               ])
surf = mt.createPolygon(topo, addNodes=5, interpolate='linear', isSubSurface=False)


boundary = mt.createPolygon([[19,233], [19,226], [0,226], [0,235.7], [0,226]], addNodes=5, interpolate='linear', isSubSurface=False)

#create some anomalies
top_layer = mt.createPolygon([[0, 233], [0,235.5],[4, 234.5], [14, 234.5], [19,232.5], [19,232.5], [19,230]], marker=1, interpolate='linear', isClosed=True, isSubSurface=True)
rock = mt.createPolygon([[0,233],[19, 230], [19, 226], [0,226]], marker=2, interpolate='linear', isClosed=True, isSubSurface=True)
block = mt.createCircle(pos=[10, 233], radius=[1.5, 1],  area=0.1, marker=3, isSubSurface=True, isClosed=True)

#merge anomalies with mesh, show geometry
geom = surf + boundary + top_layer + rock + block
pg.show(geom, markers=False)


#(re-)calculate mesh & show it
mesh = mt.createMesh(geom, quality=32, area=0, smooth=None)
pg.show(mesh, markers=True)

#Create a Dipole Dipole (‘dd’) measuring scheme with 21 electrodes.
t=np.arange(20)
electrode_pos=mt.interpolateAlongCurve(topo, t, method='linear')
scheme = ert.createData(electrode_pos, schemeName='dd')

#Put all electrode (aka sensors) positions into the PLC to enforce mesh refinement. Due to experience, its convenient to add further refinement nodes in a distance of 10% of electrode spacing to achieve sufficient numerical accuracy.

# for p in scheme.sensors():
#     geom.createNode(p)
#     geom.createNode(p - [0, 0.1])

#Create a mesh for the finite element modelling with appropriate mesh quality.
mesh = mt.createMesh(geom, quality=34)

#Create a map to set resistivity values in the appropriate regions
rhomap = [
          [0, 50.],
          [1, 100.],
          [2, 150.],
          [3, 800.]]


# Take a look at the mesh and the resistivity distribution
pg.show(mesh, data=rhomap, label=pg.unit('res'), showNodes=True, showMesh=True)


#Perform the modeling with the mesh and the measuring scheme itself and return a data container with apparent resistivity values, geometric factors and estimated data errors specified by the noise setting. The noise is also added to the data. Here 1% plus 1µV. Note, we force a specific noise seed as we want reproducable results for testing purposes.

data = ert.simulate(mesh, scheme=scheme, res=rhomap, noiseLevel=1, noiseAbs=1e-6, seed=1337)
```


etc...


![ERT_2](https://user-images.githubusercontent.com/84779476/120196677-67bb4400-c220-11eb-9242-a7a913802ba5.png)

**Comment by halbmy** [comment]
Looks good to me. I consider the problem to be solved. Thanks to all for the discussion on this interesting subject.
