### ISSUE TITLE
Runing examples of Joint inversion

### ISSUE THREAD

**Issue by get1001** [gimli-org/gimli#318]
Dear Florian-Wagner (Dr.);

I am trying to run the four-phase-inversion example provided using pygimli as suggested in issue #174.
I thank you very much in advance for your time and attention.
For synthetic_case; the first step runs without any error, but I got the following error in the second step, and other steps are not working.

runfile('C:/Users/pingyuc/Desktop/Four_phase/four-phase-inversion/four-phase-inversion-pg1.1/code/scripts/synthetic_case/2_create_syn_data.py', wdir='C:/Users/pingyuc/Desktop/Four_phase/four-phase-inversion/four-phase-inversion-pg1.1/code/scripts/synthetic_case')
################################################################################

Simulate apparent resistivities
################################################################################
Warning! DataSchemeBase::create has unhandled arguments
{'spacings': [1, 2, 4]}
26/05/21 - 22:26:28 - pyGIMLi - INFO - Found 2 regions.
26/05/21 - 22:26:28 - pyGIMLi - INFO - Region with smallest marker (1) set to background
Traceback (most recent call last):

File "C:\Users\pingyuc\Desktop\Four_phase\four-phase-inversion\four-phase-inversion-pg1.1\code\scripts\synthetic_case\2_create_syn_data.py", line 40, in
ertData = ert.simulate(meshERTFWD, res, ertScheme, noiseLevel=0.01, noiseAbs=0.0)

File "C:\Users\pingyuc\anaconda3\envs\Pg_Bert\lib\site-packages\pygimli\physics\ert\ert.py", line 790, in simulate
elif hasattr(res[0], 'iter'): # ndim == 2

File "C:\Users\pingyuc\anaconda3\envs\Pg_Bert\lib\site-packages\pygimli\core\datacontainer.py", line 55, in __DC_getVal
if self.isSensorIndex(key):

ArgumentError: Python argument types in
None.isSensorIndex(DataContainerERT, int)
did not match C++ signature:
isSensorIndex(GIMLI::DataContainer {lvalue}, std::__cxx11::basic_string<char, std::char_traits, std::allocator > token)

For the Third step I found this:

runfile('C:/Users/pingyuc/Desktop/Four_phase/four-phase-inversion/four-phase-inversion-pg1.1/code/scripts/synthetic_case/3_conventional_inversion.py', wdir='C:/Users/pingyuc/Desktop/Four_phase/four-phase-inversion/four-phase-inversion-pg1.1/code/scripts/synthetic_case')
Traceback (most recent call last):

File "C:\Users\pingyuc\Desktop\Four_phase\four-phase-inversion\four-phase-inversion-pg1.1\code\scripts\synthetic_case\3_conventional_inversion.py", line 18, in
case = int(sys.argv[1])

IndexError: list index out of range

For information I used:

conda info

(pg_Bert) C:\Users\pingyuc\Desktop\Four_phase\four-phase-inversion\four-phase-inversion-pg1.1\code>conda info

 active environment : pg_Bert
active env location : C:\Users\pingyuc\anaconda3\envs\pg_Bert
        shell level : 2
   user config file : C:\Users\pingyuc\.condarc
populated config files : C:\Users\pingyuc.condarc
conda version : 4.8.2
conda-build version : 3.18.11
python version : 3.7.6.final.0
virtual packages :
base environment : C:\Users\pingyuc\anaconda3 (writable)
channel URLs : https://conda.anaconda.org/conda-forge/win-64
https://conda.anaconda.org/conda-forge/noarch
https://conda.anaconda.org/gimli/win-64
https://conda.anaconda.org/gimli/noarch
https://repo.anaconda.com/pkgs/main/win-64
https://repo.anaconda.com/pkgs/main/noarch
https://repo.anaconda.com/pkgs/r/win-64
https://repo.anaconda.com/pkgs/r/noarch
https://repo.anaconda.com/pkgs/msys2/win-64
https://repo.anaconda.com/pkgs/msys2/noarch
package cache : C:\Users\pingyuc\anaconda3\pkgs
C:\Users\pingyuc.conda\pkgs
C:\Users\pingyuc\AppData\Local\conda\conda\pkgs
envs directories : C:\Users\pingyuc\anaconda3\envs
C:\Users\pingyuc.conda\envs
C:\Users\pingyuc\AppData\Local\conda\conda\envs
platform : win-64
user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.19041
administrator : False
netrc file : None
offline mode : False

python -c "import pygimli; print(pygimli.version); import fpinv"

(pg_Bert) C:\Users\pingyuc\Desktop\Four_phase\four-phase-inversion\four-phase-inversion-pg1.1\code>python -c "import pygimli; print(pygimli.version); import fpinv"
<function version at 0x000001E60D51C048>

conda env update --file environment.yml

EnvironmentFileNotFound: 'C:\Users\pingyuc\Desktop\Four_phase\four-phase-inversion\four-phase-inversion-pg1.1\code\environment.yml' file not found

I used

Name Version Build Channel
pygimli 1.1.1 py37_0 gimli
pybert 2.3.1 py37_0 gimli

**Comment by florian-wagner** [comment]
You are conducting the "conde env update" command in the code subfolder. The error message states that the `environment.yml` cannot be found. This is because it is not in the subfolder but in the root folder of the git repo. This is where the conda command should be executed. Please try again in the main folder or follow the steps outlined in the four-phase-repo installation instructions closely in a new environment.

Best wishes
Florian

**Comment by get1001** [comment]
Thank you;
I changed to the main folder but still, I have got the following error:

runfile('C:/Users/pingyuc/Desktop/Four_phase/four-phase-inversion/four-phase-inversion-pg1.1/code/scripts/synthetic_case/2_create_syn_data.py', wdir='C:/Users/pingyuc/Desktop/Four_phase/four-phase-inversion/four-phase-inversion-pg1.1/code/scripts/synthetic_case')
################################################################################
#                       Simulate apparent resistivities                        #
################################################################################
02/06/21 - 21:05:29 - pyGIMLi - INFO - Found 2 regions.
02/06/21 - 21:05:29 - pyGIMLi - INFO - Region with smallest marker (1) set to background
Traceback (most recent call last):

  File "C:\Users\pingyuc\Desktop\Four_phase\four-phase-inversion\four-phase-inversion-pg1.1\code\scripts\synthetic_case\2_create_syn_data.py", line 41, in <module>
    ertData = ert.simulate(meshERTFWD, res, ertScheme, noiseLevel=0.01, noiseAbs=0.0)

  File "C:\Users\pingyuc\anaconda3\envs\Pg_Bert\lib\site-packages\pygimli\physics\ert\ert.py", line 790, in simulate
    elif hasattr(res[0], '__iter__'):  # ndim == 2

  File "C:\Users\pingyuc\anaconda3\envs\Pg_Bert\lib\site-packages\pygimli\core\datacontainer.py", line 55, in __DC_getVal
    if self.isSensorIndex(key):

ArgumentError: Python argument types in
    None.isSensorIndex(DataContainerERT, int)
did not match C++ signature:
    isSensorIndex(GIMLI::DataContainer {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > token)


runfile('C:/Users/pingyuc/Desktop/Four_phase/four-phase-inversion/four-phase-inversion-pg1.1/code/scripts/synthetic_case/3_conventional_inversion.py', wdir='C:/Users/pingyuc/Desktop/Four_phase/four-phase-inversion/four-phase-inversion-pg1.1/code/scripts/synthetic_case')
Traceback (most recent call last):

  File "C:\Users\pingyuc\Desktop\Four_phase\four-phase-inversion\four-phase-inversion-pg1.1\code\scripts\synthetic_case\3_conventional_inversion.py", line 22, in <module>
    case = int(sys.argv[1])

IndexError: list index out of range

**Comment by get1001** [comment]
Thank you very much, it properly works in Linux.
One question: When I modify the input values in Four_phase of _fpinve_=> _petro_, for  Archie parameters and water resistivity, it doesn't show any changes on my model. Please could you help me with how can I modify it?
Thanks!

**Comment by florian-wagner** [comment]
Can you please specify in which line you are changing which paramters? Are we talking about synthetic or field data?

**Comment by get1001** [comment]
Thank you for your reply.
It is working now.
