### ISSUE TITLE
ImportError: No module named _pygimli_

### ISSUE THREAD

**Issue by unknowingdisorder** [gimli-org/gimli#32]
Hello,

I am struggling to install pyGIMLi on an Ubuntu 15.10. 64bit-system.
I followed the instructions: [Installation](http://pygimli.org/installation.html)
So I installed first the stuff explained in installation instructions.
After that I run:
`curl -Ls install.pygimli.org | bash`
For some reason I always get the following problem: (I replaced the home directory with "~")

>
------------------------  TEST pyGIMLi installation ------------------------
No module named _pygimli_
Traceback (most recent call last):
  File "~/gimli/gimli/python/pygimli/__init__.py", line 25, in <module>
    from . _pygimli_ import *
ImportError: No module named _pygimli_
ERROR: cannot import the library '_pygimli_'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/gimli/gimli/python/pygimli/__init__.py", line 73, in <module>
    _pygimli_.load = None
AttributeError: 'NoneType' object has no attribute 'load'
No module named _pygimli_
Traceback (most recent call last):
  File "~/gimli/gimli/python/pygimli/__init__.py", line 25, in <module>
    from . _pygimli_ import *
ImportError: No module named _pygimli_
ERROR: cannot import the library '_pygimli_'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/gimli/gimli/python/pygimli/__init__.py", line 73, in <module>
    _pygimli_.load = None
AttributeError: 'NoneType' object has no attribute 'load'
<

The problems I get because of missing castXML, py++ and pygccxml. But I think that I have installed them.
Here are the dependencies:

>-- **********************************************************************
-- ************************* Dependencies found *************************
-- **********************************************************************
-- Triangle_LIBRARIES: ~/gimli/thirdParty/dist-GNU-5.2.1-64/lib/libtriangle.a
-- UMFPACK_LIBRARIES: ~/gimli/thirdParty/dist-GNU-5.2.1-64/lib/libumfpack.a;~/gimli/thirdParty/dist-GNU-5.2.1-64/lib/libcolamd.a;~/gimli/thirdParty/dist-GNU-5.2.1-64/lib/libamd.a;~/gimli/thirdParty/dist-GNU-5.2.1-64/lib/libsuitesparseconfig.a
-- CHOLMOD_LIBRARIES: ~/gimli/thirdParty/dist-GNU-5.2.1-64/lib/libcholmod.a;~/gimli/thirdParty/dist-GNU-5.2.1-64/lib/libcamd.a;~/gimli/thirdParty/dist-GNU-5.2.1-64/lib/libamd.a;~/gimli/thirdParty/dist-GNU-5.2.1-64/lib/libcolamd.a;~/gimli/thirdParty/dist-GNU-5.2.1-64/lib/libccolamd.a;~/gimli/thirdParty/dist-GNU-5.2.1-64/lib/libsuitesparseconfig.a;/usr/lib/liblapack.so;/usr/lib/libblas.so;/usr/lib/libblas.so;rt
-- PYTHON_EXECUTABLE: /usr/bin/python3
-- PYTHON_LIBRARY: /usr/lib/x86_64-linux-gnu/libpython3.4m.so.1.0
-- Boost_PYTHON_LIBRARIES: /usr/lib/x86_64-linux-gnu/libboost_python-py34.so
-- Caster: CASTXML_EXECUTABLE-NOTFOUND
-- PYGCCXML: PYGCCXML_PATH-NOTFOUND
-- PYPLUSPLUS: PYPLUSPLUS_PATH-NOTFOUND
-- PY_NUMPY: /usr/lib/python3/dist-packages/numpy/
-- **********************************************************************
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.9.1") 
-- Found Sphinx: /usr/bin/sphinx-build (Required is at least version "1.2.0") <

What can I try to get GIMLi installed?

Thanks for any help in advance.

**Comment by unknowingdisorder** [comment]
I missed to install [Python setuptools](https://pypi.python.org/pypi/setuptools)

so I solved

> -- PYGCCXML: ~/gimli/thirdParty/dist-GNU-5.2.1-64
-- PYPLUSPLUS: ~/gimli/thirdParty/dist-GNU-5.2.1-64

but I have still the problem with
> -- Caster: CASTXML_EXECUTABLE-NOTFOUND

This did not worked for me: [Link](https://github.com/gimli-org/gimli/issues/30)
> ok, it works with :
cmake ../../src/castXML/
make

**Comment by unknowingdisorder** [comment]
I solved the problem now.

The reason was an issue by making castXML
After running
`cmake ../../src/castXML/`
and
`make`
at .../thirdParty/build-XXX-XXX/castXML
while running "make" I got the following error message:
`usr/lib/ld cannot find -lz`

the missing package I reinstalled with
`sudo apt-get install libz-dev`

and I built castXML again.

Now the dependencies where complete and I could run:
`make`
and
`make pygimli`
at .../gimli/build

**Comment by carsten-forty2** [comment]
thanks for reporting .. we will add libz-dev and Python setuptools to the prerequisites list.
