### ISSUE TITLE
saveResult() with ERTManager plots blue box on top of result (possible issue with coverage?)

### ISSUE THREAD

**Issue by soetpotet** [gimli-org/gimli#325]
### Problem description

Hi! I'm running a simple 2D inversion for ERT data based on one of your examples and it works well, only issue is saving the result and displaying the result with coverage. Please see the code and output below.

### Your environment

**Operating system**: Windows
**Python version**: 3.8
**pyGIMLi version**: 1.2.1
**Way of installation**: Conda package

### Steps to reproduce

```python
import pygimli as pg

from pygimli.physics import ert
from pygimli.physics.ert import createGeometricFactors

# %% Load and show data
 
data = ert.load('110621.txt')
ert.show(data)

# %% Geometric factors and error

# data['k'] = createGeometricFactors(data, numerical=True)
data['err'] = ert.estimateError(data, absoluteError=0.001, relativeError=0.03)

print(data)

# %% Initialize ERT Manager

mgr = ert.ERTManager(data)

# %% Run Inversion and show result

inv = mgr.invert(verbose=True)
mgr.showResultAndFit()
mgr.showResult()
mgr.saveResult()

# %% Get ParaDomain mesh

meshPD = pg.Mesh(mgr.paraDomain)

# %% Coverage

cov = mgr.coverage()
stdcov = mgr.standardizedCoverage()

# %% Plot with pg

pg.show(meshPD, inv, coverage=cov, cMin=20, cMax=38000, cMap='Spectral_r', logScale=True, label='Resistivity ($\Omega$m)')
```

### Expected behavior

`mgr.showResult()` works fine, and ideally I would like to see something like this but taking into account the coverage (what I try to do with `pg.show(...)` in the last line of code)

![image](https://user-images.githubusercontent.com/47670044/125771156-e02e0dfe-dc2d-494e-9f36-3bb10a69323b.png)

### Actual behavior

Instead, I get this. This is also the result with `mgr.saveResult()` in the resistivity.pdf it creates

![image](https://user-images.githubusercontent.com/47670044/125771609-be18459e-9556-453c-916b-2e3cbc716486.png)

Any ideas what I might be doing wrong/causing the issue? Thanks a lot!

**Comment by florian-wagner** [comment]
Hi @soetpotet,

we had a similar issue recently: https://github.com/gimli-org/gimli/issues/314 You have to either change your mpl version or update to pygimli 1.2.2

Best wishes
Florian

**Comment by soetpotet** [comment]
Sorry, missed that one. Thanks for the reference and fix @florian-wagner!

**Comment by soetpotet** [comment]
Hi again,

Didn't want to open a new issue because maybe you've also ran into this, but I got this error when testing pygimli after installing the 1.2.2 version.

![image](https://user-images.githubusercontent.com/47670044/125787592-213d9738-91ee-4cf8-94d6-4f2681d0d6b3.png)

I went back to 1.2.1 and it works fine again.

**Comment by halbmy** [comment]
Yes, I have already noticed this problem and will solve it asap.
