### ISSUE TITLE
Introduction of 2 new submodules

### ISSUE THREAD

**Issue by florian-wagner** [gimli-org/gimli#33]
I would like to introduce two new submodules:

- `pygimli.core`
- `pygimli.inversion`

The first one is in analogy to `numpy.core` and should hold the core functionality (inlcuding `__pygimli__.so` and all the monkeypatching). This would clean up `__init__.py`, which should ideally only contain import statements, and would further introduce a more structured way to extend C++ classes with python methods.

The second one would lay the ground for new inverse solvers. I am also thinking about a few wrappers for some of the minimization methods in `scipy.optimize`.

Any thoughts or objections?

**Comment by halbmy** [comment]
Florian, as discussed personally last week, I consider both submodules a very good idea. 
A core module really cleans up a lot, I suggest you care for it. For the user it will not look different.
To the contrary, the inversion module will contain both typical inversion frameworks (classical inversion, petrophysical inversion), but also different approaches such as Bio-inspired algorithms (e.g. GA, PSO - I had already used inspyred into the MRS module) and also mesh-independent (pilot point) inversion. I guess we all will work on this and consider it a playground that shoult not be in the "production mode" (e.g. method managers) too early.
