### ISSUE TITLE
3D ERT on a cylinder

### ISSUE THREAD

**Issue by Giuliadepasquale-cz** [gimli-org/gimli#331]
### Problem description

Hello everyone, 
sorry to bother again but got into an issue I'm not sure how to resolve.
I'm trying to build up a 3D ERT forward (and potentially) inverse scheme-model over a cylinder. 

For the moment my idea was to have 12 electrodes equally spaced at some fixed z arund the cilinder and see the ERT response with an homogeneous resistivity distribution but I run in an  "isSensorIndex" error.

The code is this one (I was mainly following up the example from the webpage about the 3D ERT response simulation within a tank):
```
##############################################################################
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
import pybert as pb

# 1) Create the Geometry
nel        = 12                                                      #n° of electrodes
M          = 3                                                       #multiplier for n° of nSegments (see below)
center_pos = [0.0, 0.0, 0.0]
radius     = 2.
height     = 10.
nSegments  = M*nel                                              
#This creates the polygon
plc        = mt.createCylinder(radius, height, nSegments, center_pos, area=0.5, quality=33., boundaryMarker=1)

# 2) Set the ERT position (along the circumference and equally spaced) and create mesh
zel        = 0.                  #constant height for electrodes
el_pos   = np.empty([nel,3])

for i in range(nel):
    xel       = plc.node(M*i)[0]
    yel       = plc.node(M*i)[1]
    el_pos[i] = [xel,yel,zel]
    #add the electrodes as nodes with marker -99 to the geometry
    plc.createNode([xel,yel,zel],marker=-99)
    #For sufficient numerical accuracy refine the mesh in the vicinity of the electrodes positions.
    plc.createNode([xel,yel,zel-1e-3/2],marker=-99)

#Define a reference electrode position inside the PLC, with a marker -999, somewhere away from the electrodes (and refine it).
plc.createNode(center_pos, marker=-999)
plc.createNode([center_pos[0],center_pos[1],center_pos[2]-1e-3/2])

#Add calibration node with marker -1000 where the potential is fixed , somewhere on the boundary and far from the electrodes.
plc.createNode([0,radius,height/2], marker=-1000)

#create the 3D mesh
Cylinder   = mt.createMesh(plc)
pg.show(Cylinder)

# 3) Set the ERT scheme and simuate response from a uniform resistivity
scheme     = pb.createData(el_pos, schemeName='wa')   
Homogeneous= pb.simulate(Cylinder, res=1., scheme=scheme, sr=False, calcOnly=True, verbose=True)
```

###################################################################
THE error I get is the following:

 Homogeneous= pb.simulate(Cylinder, res=1., scheme=scheme, sr=False, calcOnly=True, verbose=True)
  File "C:\Users\alleg\anaconda3\envs\PG\lib\site-packages\pybert\manager\ertmanager.py", line 43, in simulate
    return ert.simulate(mesh, res, scheme, verbose=verbose, **kwargs)
  File "C:\Users\alleg\anaconda3\envs\PG\lib\site-packages\pygimli\physics\ert\ert.py", line 780, in simulate
    elif hasattr(res[0], '__iter__'):  # ndim == 2
  File "C:\Users\alleg\anaconda3\envs\PG\lib\site-packages\pygimli\core\datacontainer.py", line 55, in __DC_getVal
    if self.isSensorIndex(key):
Boost.Python.ArgumentError: Python argument types in
    None.isSensorIndex(DataContainerERT, int)
did not match C++ signature:
    isSensorIndex(GIMLI::DataContainer {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > token)
##############################################################################

Any idea about what am I doing wrong? 

Thank you in advance
Giulia

**Comment by halbmy** [comment]
Dear Giulia,
I just had a quick look. A few comments before I go into the code:
* when adding nodes, it is always good to use `plc.addNodeWithCheck()` instead of `addNode` in order to avoid a node where there is one already
* when refining electrodes, you should not provide a -99 marker (that is marking electrodes but more for historical reasons)
* for circular measurements I would always recommend dipole-dipole arrays over Wenner as they provide a complete set (if being made circularly)

**Comment by Giuliadepasquale-cz** [comment]
Dear Thomas,
thank you so much it does work now but I cannot use the function addNodeWithCheck ; when I tried I get the message
'Mesh' object has no attribute 'addNodeWithCheck'
I'm using the latest version of pygimli (1.2.2)

**Comment by halbmy** [comment]
sorry, I meant `createNodeWithCheck`

**Comment by halbmy** [comment]
sorry, I meant `createNodeWithCheck`

Here you cannot pass the marker directly but set it later.
But that's not the problem in your case. The attached script worked for me.
```
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import ert

nel = 12 #n° of electrodes
M = 3 #multiplier for n° of nSegments (see below)
center_pos = [0.0, 0.0, 0.0]
radius = 2.
height = 10.
nSegments = M*nel
#This creates the polygon
plc = mt.createCylinder(radius, height, nSegments, center_pos, area=0.5, quality=33., boundaryMarker=1)
pg.show(plc)
zel = 0. #constant height for electrodes
el_pos = np.empty([nel,3])

for i in range(nel):
    xel = plc.node(M*i)[0]
    yel = plc.node(M*i)[1]
    el_pos[i] = [xel,yel,zel]

    #add the electrodes as nodes with marker -99 to the geometry
    n = plc.createNodeWithCheck(pg.Pos(xel,yel,zel))#,marker=-99)
    n.setMarker(-99)
    #For sufficient numerical accuracy refine the mesh in the vicinity of the electrodes positions.
    plc.createNode([xel,yel,zel-1e-3/2])

#Define a reference electrode position inside the PLC, with a marker -999, somewhere away from the electrodes (and refine it).
plc.createNode(center_pos, marker=-999)
plc.createNode([center_pos[0],center_pos[1],center_pos[2]-1e-3/2])

#Add calibration node with marker -1000 where the potential is fixed , somewhere on the boundary and far from the electrodes.
plc.createNode([0,radius,height/2], marker=-1000)

#create the 3D mesh
Cylinder = mt.createMesh(plc)
pg.show(Cylinder)

scheme = ert.createData(el_pos, schemeName='dd')
res = pg.Vector(Cylinder.cellCount(), 1.0)
Homogeneous= ert.simulate(Cylinder, scheme=scheme, res=1.0, #res,
                         sr=False, calcOnly=True, verbose=True)
```

**Comment by Giuliadepasquale-cz** [comment]
Thank you so much!
Giulia

**Comment by halbmy** [comment]
Please use
```
from pygimli.physics import ert
data = ert.createData(...
```
