### ISSUE TITLE
Issue plotting using .addHoleMarker()

### ISSUE THREAD

**Issue by hdanque** [gimli-org/gimli#346]
### Problem description
I am getting some odd issues using the geo.addHoleMarker() function. It works fine for some regions but for others, it causes an error when pg.show() is calling "tricontour". What does this error mean and how to I fix it? If I comment out the geo.addHoleMarker() it plots fine. However, I want to use the the addHoleMarker(). 

Please describe your issue here.

### Your environment

**Operating system**: e.g. Windows, Linux or Mac?
Windows 10 Home 19043.1288
**Python version**: e.g. 2.7,3.5,3.6?
3.8.10
**pyGIMLi version**: Output of `print(pg.__version__)`
1.2.1
**Way of installation**: e.g. Conda package, Win binary, curl script, manual compilation from source
Conda
### Steps to reproduce
Run script below with and without commenting the .addHoleMarker() on line 31

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```
#TESTING Issues
import pygimli as pg
import pygimli.meshtools as mt
import matplotlib.pyplot as plt
%matplotlib inline

#boundaries of the the model world
left =   0.0
right=    60000.0
surface =  2000.0
depth=    -10000.0
num_layers = [2000, 0, -5000]
mesh_area = (right-left)*20

#temp and heat flux
PSR_t = 110 #temperature in K
surf_t= 210 #temperature in K
heat_flow = 0.010 # W/m^2 (10mW is 0.01W), 5mW is 0.005W) 


#Figure paramameters
fig_width = 10
fig_height=  8
fig_dpi   = 90

moon = mt.createWorld(start=[left, surface], end=[right, depth], layers=num_layers, worldMarker=True)

geom = moon

#ISSUE HERE ADDING THE HOLE MARKER
#geom.addHoleMarker([1, surface-1])

# Create matplotlib figure and set size
fig, ax = plt.subplots(figsize=(fig_width,fig_height), dpi=fig_dpi)
ax.set_title("Lunar 2D Model", fontweight="bold")

pg.show(geom, ax=ax, boundaryMarkers=True, showNodes=True);


mesh = mt.createMesh(geom, quality=32, area=mesh_area, smooth=[2, 10], verbose=True)

# Create matplotlib figure and set size
fig, ax = plt.subplots(figsize=(fig_width,fig_height), dpi=fig_dpi)
ax.set_title("Lunar 2D Model", fontweight="bold")

pg.show(mesh, ax=ax, boundaryMarkers=True)

# Lunar thermal diffusivity parameters. 
#Boundary Conditions of 210 K at illuminated edge of crater, 110K in crater, 
#and no flow boundary conditions at the side and lunar heat flow values at the bottom

dirichletBC = { 9: surf_t}

neumannBC = {11:  heat_flow }

T = pg.solver.solveFiniteElements(mesh, a={2: 10E-90, 3: 0.45, 4: 2}, bc={'Dirichlet': dirichletBC, 'Neumann' : neumannBC }, verbose=True)

# Create matplotlib figure and set size
fig, ax = plt.subplots(figsize=(fig_width,fig_height), dpi=fig_dpi)
ax.set_title("Lunar 2D Model", fontweight="bold")

pg.show(mesh,  data=T, ax=ax, label='Temperature $T$', cMap="Reds", nLevs=21 )

# just hold figure windows open if run outside from spyder, ipython or similar
pg.wait()

```

### Expected behavior

Tell us what should happen or what you want to achieve.

It should produce a plot of temperature without errors. 
![image](https://user-images.githubusercontent.com/42480758/139925943-6dbeb53a-bd8b-4c93-af75-c155bfe0b48b.png)

### Actual behavior

Tell us what happens instead and/or provide the output of your script.

```
  File "C:\Users\15124\anaconda3\envs\pg-transform\lib\site-packages\matplotlib\tri\tricontour.py", line 88, in _contour_args
    raise ValueError('z array must not contain non-finite values '
ValueError: z array must not contain non-finite values within the triangulation

![image](https://user-images.githubusercontent.com/42480758/139926438-2d83f7d1-5e16-4184-ab0f-896a107cf1e2.png)
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by carsten-forty2** [comment]
The hole marker works as expected .. you add it in region 2 and so this region 2 will not be meshed. 

However, there is a follow up error in the Finite Element Solver which says "CHOLMOD warning: not positive definite. file: t_cholmod_rowfac.c line: 430". I don't know yet where this error comes from but it leads to a zero Temperature distribution, which can't be shown and leads to the matplotlib error you experience.

What do you want to achieve with this hole marker .. I assume region 2 should not be deleted?

**Comment by hdanque** [comment]
Thanks for checking on this issue and for identifying a possible root cause in the Finite Element Solver. 

I want region 2 to be a hole in the model. This is the simplest model that consistently has the issue with add.HoleMarker() that I created specifically for troubleshooting. 

My use case is thermal modeling of lunar permanently shadowed craters on the Moon (see images below). When I use profiles over real craters and try to define the vacuum above the surface of the DTM as empty model space with the addHoleMarker, I get this issue. If I use some simple polygon models (as shown below) I can use the addHoleMarker() successfully. I don't know why it works for some models but not others. 
![image](https://user-images.githubusercontent.com/42480758/140179265-cf2cf843-ae8b-4ae2-9c21-b8082e54b973.png)
![image](https://user-images.githubusercontent.com/42480758/140179333-f54b48b2-3ee5-4692-8238-89e98dc972fa.png)

**Comment by hdanque** [comment]
@carsten-forty2 by the way, this is part of my PhD research and I would like to use some models and images from pygimli with attribution of course, in a Lunar and Planetary Science Conference presentation in the spring. I want to get these plotting issues sorted out before putting together the presentation. 
I appreciate your time to help figure this out.

**Comment by carsten-forty2** [comment]
A hole marker is just a "hack" to exclude specified regions from the resulting mesh since we don't have yet a proper difference operator for geometries. 

Region 2 is the top layer of the mesh .. if you set the whole region to be a hole with this marker, then this layer is not more part of the mesh and also not more part of the finite element modelling. Maybe this 3 layer case is not optimal for testing.  However I need to check about this singularity problem but this will take some days due to little lack of time currently. I reopen it to remember myself..

**Comment by hdanque** [comment]
@carsten-forty2 I hope your New Year is starting well. Following up, I am still unable to use hole markers as I need to. I am also having issues assigning some marker values to specific regions. For some regions, the marker value will not assign. I wonder if these issues are related? I am glad to share my full code if that will help with the troubleshooting or arrange a time to screen share and I can show you what the issues look like on my end. I am using the results of these models for publications so I want to make sure it is working properly.

**Comment by carsten-forty2** [comment]
Hello @hdanque, 

there is no known problem with the markers so it would be helpfull if you show the script and describe the behaviour do you expect. If you don't want to show your script here in public, we can discuss this issue in slack.

**Comment by florian-wagner** [comment]
I am closing this, since I assume the question was answered in the Slack channel. @hdanque Feel free to reopen, if this is not the case.
