### ISSUE TITLE
Problem with castxml

### ISSUE THREAD

**Issue by kodaz1** [gimli-org/gimli#35]
I'm trying to install pygimli. All things seems to be ok except the building o castxml .
I have the following message :
/home/arfang/gimli/thirdParty/src/castXML/src/Output.cxx:21:34: fatal error: clang/AST/ASTContext.h: Aucun fichier ou dossier de ce type
#include "clang/AST/ASTContext.h"
^
compilation terminated.
/home/arfang/gimli/thirdParty/src/castXML/src/RunClang.cxx:24:35: fatal error: clang/AST/ASTConsumer.h: Aucun fichier ou dossier de ce type
#include "clang/AST/ASTConsumer.h"
^
compilation terminated.
make[2]: *** [src/CMakeFiles/castxml.dir/Output.cxx.o] Erreur 1
make[2]: *** Attente des tâches non terminées....
make[2]: *** [src/CMakeFiles/castxml.dir/RunClang.cxx.o] Erreur 1
make[1]: *** [src/CMakeFiles/castxml.dir/all] Erreur 2
make: *** [all] Erreur 2
~/gimli/thirdParty
-- NOT Found castxml executable: cannot build pygimli.
I try to built castxml with gcc or with clang but i got the same error.
Thank you for your help cause i don't know how to deal with this issue.

**Comment by kodaz1** [comment]
The problem have been sold with the help of the castxml developper . Solution on ubuntu trusty /
Must install all the dependencies even the optionnal prerequesite as it is said
 http://www.pygimli.org/installation.html
and add libclang-3.7-dev in order to solve the problem with castxml

**Comment by carsten-forty2** [comment]
thanks for reporting back .. I adapt the docu
