### ISSUE TITLE
Question: why can we use Jacobian()*slowness to calculate travel times?

### ISSUE THREAD

**Issue by ShiLevy** [gimli-org/gimli#352]
Hi,
In this thread https://github.com/gimli-org/gimli/issues/286 Jacobian()*slowness_model is used to calculate travel times. How is it that we can use Jacobian()*slowness to calculate the travel times? Is there an assumption involved?
(After all the Jacobian contains gradients, why multiplying it by a slowness model give travel times?)
Thanks in advance for your answer :)

**Comment by florian-wagner** [comment]
Hi @ShiLevy,

here a picture from an exercise I am giving next Thursday:

![image](https://user-images.githubusercontent.com/2799008/144097041-23353475-85a9-4062-845e-467bff72a122.png)

In summary: In the ray-approximation, the Jacobian consists of the ray segments per model cell. Multiplying this with the slowness vector produces the total traveltime of the ray along each segment.

Hope this helps
Florian

**Comment by florian-wagner** [comment]
(and the ray segment in each model cell actually reflects the "sensitivity", as longer ray segments have a larger impact on the traveltime)

**Comment by ShiLevy** [comment]
Hi Florian,

Thank you for the quick response!
So does the Jacobian we get from createJacobian() gives a straight-ray path (between source and receiver) or does it take in account also a curved path as simulate() does?
I am asking because I found a difference in the travel times between Jacobian()*slowness_model and simulate().

**Comment by halbmy** [comment]
I consider the questions being solved.

**Comment by makeabhishek** [comment]
Where can I find the detailed description of above snippet in the comment by @florian-wagner ? Is it from some book or pygimli documentation/tutorial?

**Comment by halbmy** [comment]
I guess you will find it in any textbook on applied geophysics.
