### ISSUE TITLE
Porosity Inversion

### ISSUE THREAD

**Issue by 1902912604** [gimli-org/gimli#353]
Can this be used for porosity prediction？

**Comment by halbmy** [comment]
Are you expecting us to be able to provide an answer to this general question? We don't even know which methods are you referring to. Please have a look at the porosity (joint) inversion in the pyGIMLi paper, on https://www.pygimli.org/citation.html#sec-citation you will also find a link to the codes.

**Comment by halbmy** [comment]
I am afraid there will be no more activity.
