### ISSUE TITLE
Licensing concerns due to tetgen dependency

### ISSUE THREAD

**Issue by banesullivan** [gimli-org/gimli#358]
I am by **no means** an expert or authority on software licensing so take everything I have to say here with a few grains of salt. 

I have some concerns which were originally brought up in https://github.com/gimli-org/gimli/issues/178#issuecomment-507758533

Tetgen is under a GPL license, see: https://github.com/ufz/tetgen/blob/master/LICENSE

To my knowledge, the usage of Tetgen in Gimli constitutes a “dynamic link” under the GPLv3 license. According to the GPLv3 license - any work that has a “dynamic link” with work under a GPLv3 license must be relicensed under GPLv3. And thus if Gimli imports/uses TetGen to any degree it would have to relicense to GPL and any works that depend on Gimli would have to relicense to GPL.

I like to think of GPL licenses as a virus infecting any code they touch.

These conditions are incredibly restrictive in my opinion and are absolutely incompatible with the current Apache license of Gimli.

Furthermore, any commercial users of Gimli should be gravely concerned by this

**Comment by banesullivan** [comment]
Copying @carsten-forty2's comment here as it was a well thought out response: https://github.com/gimli-org/gimli/issues/178#issuecomment-508122460

>Thank you for your thought-provoking answer, indeed we are aware of TetGen's licence (AGPLv3) and had a couple internal discussions in the past.
> 
> With my interpretation of the GPL, we are on the safe side but I can be wrong since I'm no lawyer. We do not ship a modified copy of TetGen, we don't link TetGen in any form and we don't import any TetGen related wrapper. The only thing we do is creating a proper PLC and a command line to make a system call to the TetGen binary. Its in the users responsibility to provide the TetGen binary somewhere in the system path. It would be much nicer to communicate directly with the TetGen library, but like you say .. this would give us GPL problems.
> 
> With no linking, no usage of shared memory and no extensive data exchange, we interpret
#GPLPlugins in a way that pygimli and TetGen stays separate programs. But maybe its more easy since we do not distribute or convey TetGen.
#NoDistributionRequirements
>
> I didn't recognise the authorship of TetGen has been changed: http://wias-berlin.de/software/index.jsp?id=TetGen&lang=1#Introduction. He seems quite busy .. I tried a bug report some months ago but got no answer. Did you got any answer from the author?

**Comment by banesullivan** [comment]
In my experience, the ambiguity of GPL licensing's "dynamic link" clause can scare off commercial users. I'm raising this issue as a friendly warning because I would hate to see gimli find itself trapped in a hole where commercial users are hesitant to use it.

**Comment by halbmy** [comment]
To make it clear again: There is no dynamic link (as we do with triangle) to tetgen. We just generate input files, call tetgen (which can be installed as a conda package) and read in the resulting mesh. Although we are of course aware of the infection from GPL, I see no license issue here.

**Comment by banesullivan** [comment]
Thanks, @halbmy! After this and some discussions on the SWUNG Slack channel, I think this is resolved

**Comment by halbmy** [comment]
Good to hear that! Thanks for raising these thoughts and for developing such a great package.
