### ISSUE TITLE
Problem with pygimli installation

### ISSUE THREAD

**Issue by kodaz1** [gimli-org/gimli#36]
After solving the problem with casxml i run the script installation -
curl -Ls install.pygimli.org | bash

another error occured:
File "/home/arfang/gimli/thirdParty/dist-GNU-4.8.4-32/pyplusplus/file_writers/multiple_files.py", line 56, in write_file
    raise RuntimeError( os.linesep.join(msg) )
RuntimeError: `Py++` is going to write different content to the same file(./generated/ContainerType.pypp.hpp).
The following is a short list of possible explanations for this behaviour:
* `Py++` bug, in this case, please report it
* module_builder_t contains two or more classes with the same alias
* module_builder_t contains two or more classes with the same wrapper alias
Please carefully review `Py++` warning messages. It should contain an additional information.
make[3]: *** [pggen] Erreur 1
make[2]: *** [python/CMakeFiles/pggen.dir/all] Erreur 2
make[1]: *** [CMakeFiles/pygimli.dir/rule] Erreur 2
make: *** [pygimli] Erreur 2

[ContainerType.pypp-hpp.txt](https://github.com/gimli-org/gimli/files/186149/ContainerType.pypp-hpp.txt)
could you have a look if you have time please ?

Thanks

**Comment by carsten-forty2** [comment]
I tried right now with current castxml/pygccxml and pyplusplus without seeing this issue. Can you please try to start with an empty build directory and setting

 CLEAN=1 before the cmake command

or just delete the thirdparty directory.

**Comment by kodaz1** [comment]
I have delete all the src directory, reboot my computer and run a new install but the same error occured . 
What do you think is happening ? 
thanks

**Comment by carsten-forty2** [comment]
can you please provide a full log

CLEAN=1 cmake ../gimli 2>&1 | tee cmake.log
make pygimli  2>&1 | tee make.log

**Comment by kodaz1** [comment]
make.log and cmake.log 
Thank you for your help 
[cmake-log.txt](https://github.com/gimli-org/gimli/files/186316/cmake-log.txt)
[make-log.txt](https://github.com/gimli-org/gimli/files/186317/make-log.txt)

**Comment by carsten-forty2** [comment]
-- Target is 32 bits

Do you really have 32bit linux system? .. 

32bit Linux is not supported.

I think that might be the reason. I don't have any access to such hardware so I can't support or verify but the "write different content to the same" issue sounds plausible to me then.

**Comment by kodaz1** [comment]
yes  i'm using an  32 bit linux system. 
thank you , i have learn a lot by trying to install this software

**Comment by kodaz1** [comment]
Hi ,
I finally succeed in building pygimli after setting a 64 bit linux system (
Ubuntu trusty ) on another computer. Everything is ok and i'm able to load
the module with spyder and use it.
Thank you for your help and all the advices .


2016-03-23 16:49 GMT+01:00 carsten-forty2 <notifications@github.com>:

**Comment by carsten-forty2** [comment]
thanks for reporting back

closed #36
