### ISSUE TITLE
3D Flat Inversion

### ISSUE THREAD

**Issue by TheNablaOperator** [gimli-org/gimli#360]
### Problem description

Hello.
I have 3D Measurement Data, which I want to invert to a 3D soil model.
The different lines are detected and shown in the apparent plot, but the inversion result is 2D.
I am not sure if this has somwthing to do with the data, but in the result (inversion model) there is data above (z>0m) ground. 
I basically want to do the same as in the BERT Tutorial, but I don't find the way to make it 3D.
Thank you in advance!

### Your environment

**Operating system**: Ubuntu 20.04 LTS
**Python version**: 3.9.10
**pyGIMLi version**: 1.2.3
**Way of installation**: conda

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
import pygimli as pg
from pygimli.physics import ert

data = ert.load("ResBlocks_CIRED_inhom_3x3_UDF.dat")
pg.show(data)
print(data)

data['err'] = ert.estimateError(data)
ert.show(data, data['err']*100, label="Error in %")

mgr = ert.ERTManager(data)
inv = mgr.invert(verbose=True,
                 lam=20
                 )

mgr.showResult(cMin=100, cMax=1000, xlabel="x in m", ylabel="z in m")
```

Data is in UDF with x,y,z coordinates, where z=0 (always, so no topo).

### Expected behavior

3D inversion model with no result above ground

### Actual behavior

2D result with strange data above ground.

**Comment by halbmy** [comment]
The ERT manager is able to do 3D inversions but it does not yet do a fully automated mesh generation. Actually, from a mesh containing x and y coordinates it is not even clear whether it is 3D or 2D with buried electrodes. So you will have to do this for your own. I am attaching an example script using a regular grid that will appear on the website soon.
```
import numpy as np
import pygimli as pg
from pygimli.physics import ert


def createMixMesh(data, dx=None, verbose=True):
    """Create a triangle prism mesh."""
    dx = dx or data.sensor(0).distance(data.sensor(1))
    ex = pg.x(data)
    ey = pg.y(data)
    paraBoundary = dx
    boundary = dx * 20
    depth = 10
    x = np.arange(min(ex)-paraBoundary, max(ex)+paraBoundary+.01, dx)
    y = np.arange(min(ey)-paraBoundary, max(ey)+paraBoundary+.01, dx)
    grid = pg.createGrid(x, y)

    for c in grid.cells():
        c.setMarker(2)

    pg.show(grid, markers=True)

    mesh2 = pg.meshtools.appendTriangleBoundary(grid,
                                                xbound=boundary,
                                                ybound=boundary,
                                                quality=30,
                                                marker=1, isSubSurface=False)

    mesh2.smooth(True, False, 1, 2)

    for b in mesh2.boundaries():
        if b.marker() < 0:
            b.setMarker(pg.core.MARKER_BOUND_MIXED)

    pg.show(mesh2, markers=True)

    mesh3 = pg.meshtools.createMesh3D(
        mesh2,
        -pg.cat(np.arange(0, 12.6, 2.5/2),
                pg.utils.grange(2.5, boundary, n=10) + 12.5),
        pg.core.MARKER_BOUND_HOMOGEN_NEUMANN,
        pg.core.MARKER_BOUND_MIXED)

    for c in mesh3.cells():
        if c.marker() == 2:
            if c.center()[2] < -depth:
                c.setMarker(1)

    return mesh3

data = pg.getExampleData("ert/gallery3d.dat")
mesh = createMixMesh(data)
mesh.exportVTK("mesh.vtk")
data["err"] = ert.estimateError(data)
mgr = ert.ERTManager(data)
mgr.invert(mesh=mesh, verbose=True)
mgr.saveResult()
```

**Comment by TheNablaOperator** [comment]
Thank you for the code snippet!
I assume: `data = pg.getExampleFile("ert/gallery3d.dat", load=True, verbose=True)` ? 
Since I get the error: no attribute 'getExampleData'
The inversion started and finished properly.
How do I plot the inversion result? `pg.show(mgr)` shows only the markers.

**Comment by halbmy** [comment]
Absolutely. I'll correct it in the post and the upcomping example.

You can use `pg.show(mgr.paraDomain, mesh.model)` but depending on your pyvista version or where you run the script (VC, Spyder, Jupyter) might work or not. At any rate, you can look in the result directory that is created by `mgr.saveResult()` and find a file `resistivity.vtk` that you can visualize with Paraview.

**Comment by TheNablaOperator** [comment]
Thank you!
I am using Spyder, but as you thought it doesn't work. However, I am not sure if that has something to do with Spyder... 
AttributeError: 'Mesh' object has no attribute 'model'

**Comment by halbmy** [comment]
Sorry I meant `mgr.model`.

**Comment by TheNablaOperator** [comment]
Yes makes sense... Thank you!
