### ISSUE TITLE
Jacobian calculation

### ISSUE THREAD

**Issue by AleVin11** [gimli-org/gimli#361]
Hi, I have a question about Jacobian calculation for ERT data.
I know that there is no way to extract Jacobian matrix from each inversion step, so my idea was to use predicted data (data_pre) and estimated model (model_est) at each iteration in this way:

fob = ert.ERTModelling()

fob.setData(data_pre)
fob.setMesh(mesh)
fob.createJacobian(model_est)
Jac=fob.jacobian()
Jac = np.array(Jac)

Being jacobian calculated by partial derivative of the data over the model, is it right to pass predicted data using fob.setData(data_pre)?
Because I guess that the code to calculate Jacobian matrix is written in C++ and so for me this calculation is a sort of black box.

Regards,
Ale

**Comment by halbmy** [comment]
You can define a function
```
def saveJacobian(iter, inv):
    inv.fop.jacobian().save("jacobian{:d}.bmat".format(iter))
```
and set it to be called in every iteration
```
inv = pg.Inversion()
inv.setPostStep(saveJacobian)
```

**Comment by AleVin11** [comment]
Following your suggestion i write these lines:

import pygimli as pg
import pygimli.physics.ert as ert

fop = ert.ERTModelling()
inv = pg.Inversion()
inv.setPostStep(saveJacobian)
inv.setForwardOperator(fop)
inv.run(data_obs['rhoa'],data_obs['err'])

This error appears:
AttributeError: module 'pygimli' has no attribute 'fixZero'

I'm using pygimli 1.2.2

**Comment by halbmy** [comment]
This is indeed a bad bug that should not appear and catched by the tests. Can you try using the very recent pygimli version 1.2.4 just to make sure it is not already fixed?

**Comment by halbmy** [comment]
There is definitely a zero error (and therefore travel) value (see also #363). Actually we try to catch this but there was a bug that is solved. You should just remove zero-offset, plus use `tt.estimateError`.

**Comment by AleVin11** [comment]
Using pygimli version 1.2.4 the errors that appears is:

TypeError: createDefaultStartModel() missing 1 required positional argument: 'dataVals'

About tt.estimateError, is it not about traveltime? What does remove zero-offset in ERT case means?

It was right how i calculated Jacobian in my opening comment?

Thanks

**Comment by carsten-forty2** [comment]
Just an additional comment. You can take a look at the `ERTModellingReference` forward operator which is supposed to be a non optimized implementation of the ERT behavior in python without the ERT class from the core. It can be used for smaller 2D problems and maybe shows a little better how the response and Jacobian are calculated.

**Comment by halbmy** [comment]
> About tt.estimateError, is it not about traveltime? What does remove zero-offset in ERT case means?

Sorry, I mixed two issues up where `fixZero` ocurred.

> Using pygimli version 1.2.4 the errors that appears is:
`TypeError: createDefaultStartModel() missing 1 required positional argument: 'dataVals'`

The reason is the missing mesh in the forward operator. The following code worked nicely:
```Python
import pygimli as pg
import pygimli.physics.ert as ert
import pygimli.meshtools as mt

def saveJacobian(iter, inv):
    inv.fop.jacobian().save("jacobian{:d}.bmat".format(iter))

data = ert.load("gallery.dat")
fop = ert.ERTModelling()
fop.data = data
fop.setMesh(mt.createParaMesh(data))
inv = pg.Inversion(fop=fop)
inv.setPostStep(saveJacobian)
inv.run(data['rhoa'], data['err'], startModel=100)
```

**Comment by AleVin11** [comment]
With Pygimli version 1.2.4 the error is the following (using your code above but with my data):

 Input In [93] in <module>
    inv.run(data['rhoa'], data['err'], startModel=100)

  File ~/miniconda3/lib/python3.8/site-packages/pygimli/frameworks/inversion.py:452 in run
    self.errorVals = errorVals

  File ~/miniconda3/lib/python3.8/site-packages/pygimli/frameworks/inversion.py:286 in errorVals
    pg.fixZero(self._errorVals, 1)

AttributeError: module 'pygimli' has no attribute 'fixZero'

**Comment by AleVin11** [comment]
Sorry, I forgot to set data['err'] in my data. Now it works, thank you.

Alessandro

**Comment by halbmy** [comment]
Anyway, there should be a clearer message. However, the fixZero bug has already been fixed https://github.com/gimli-org/gimli/commit/848a10a9ce13f1af9ec3c63ed53cdbc41f0a6b1a
