### ISSUE TITLE
2D Refraction Modeling and Inversion

### ISSUE THREAD

**Issue by Don-Timmy** [gimli-org/gimli#365]
### Problem description
Hi, 

I am inverting forward-modeled seismic refraction travel times and discovered that multiple inversions of the same simulated dataset give me slightly different results (velocities). It seems that the variations are due to the forward operator called by TravelTimeManager.py that uses model parameters to simulate new datasets in the inversion. I wonder if there is some setting I can use to produce entirely deterministic inversion results?

### Your environment

**Operating system**: e.g. Windows, Linux or Mac?
**Python version**: e.g. 2.7,3.5,3.6?
**pyGIMLi version**: Output of `print(pg.__version__)`
**Way of installation**: e.g. Conda package, Win binary, curl script, manual compilation from source

### Steps to reproduce

The first function simulates traveltime measurements using the default forward operator in  Pygimli's TravelTimeManager module. The second function inverts the data:

```Python
def simulateData(name = 'simulateddata', numberGeophones = 99, drySoftVp = 830, dryStiffVp = 1920, wetSoftVp = 1850, wetStiffVp = 3130 , bedrockVp = 5000, noiseLevel = 0.05):
    """Simulate travel time data using  pygimli's traveltime manager module
    
    Parameters:
    
    name - str: name the data you want to output
    
    
    numberGeophones - int:  How many geophones to use in the scheme
    
    
    drySoftVp - int: Velocity of dry soft layer
    
    
    dryStiffVp - int: Velocity of dry stiff layer
    
    
    wetSoftVp - int: Velocity of wet soft layer
    
    
    wetStiffVp - int: Velocity of wet soft layer
    
    
    bedrockVp - int: Velocity of bedrock layer
    
    
    noiseLevel - float: noise percentage in decimals
    """
    
    import numpy as np
    import pygimli as pg
    import pygimli.meshtools as mt
    from pygimli.physics import TravelTimeManager
    mgr = TravelTimeManager()
    #create geometry
    drysoftlayer = mt.createPolygon([[0.0, 140],[0.0, 135],[35.0, 135],[35.0, 140],[80.0, 143], [99.0, 158],[99.0, 165]],
                              isClosed=True, marker = 1, area = 1)
    drystifflayer = mt.createPolygon([[80, 143],[80, 138],[99, 153],[99, 158]],
                              isClosed=True, marker=2)
    wetsoftlayer = mt.createPolygon([[35.0, 140],[35.0, 135],[80.0, 138],[80.0, 143]],
                              isClosed=True, marker=3)
    wetstifflayer = mt.createPolygon([[0, 135],[0, 110],[99, 110],[99, 153],[80, 138],[35, 135]],
                              isClosed=True, marker=4)
    bedrock = mt.createPolygon([[0.0, 110], [0.0, 106], [99.0, 106], [99.0, 110]],
                              isClosed=True, marker=5)
    geom = drysoftlayer +  drystifflayer + wetsoftlayer +  wetstifflayer + bedrock
    forwardMesh = mt.createMesh(geom, quality=34.3, area=3, smooth=[1, 10])
    #Define position of sources and recievers and the measurement scheme
    n = numberGeophones
    sensors = np.linspace(0., 99, n)
    scheme = pg.physics.traveltime.createRAData(sensors)
    # Adapt sensor positions to slope
    slope = (165 - 140) / 99
    pos = np.array(scheme.sensors())
    for x in pos[:, 0]:
        i = np.where(pos[:, 0] == x)
        new_y = x * slope + 140
        pos[i, 1] = new_y
    scheme.setSensors(pos)
    #Populate the subsurface with parameters and view the model
    mgr = TravelTimeManager()
    vp = np.array(forwardMesh.cellMarkers())
    vp[vp == 1] = drySoftVp
    vp[vp == 2] = dryStiffVp
    vp[vp == 3] = wetSoftVp
    vp[vp == 4] = wetStiffVp
    vp[vp == 5] = bedrockVp
    #Obtain traveltime data from forward simulation using model
    simdata = mgr.simulate(slowness=1.0 / vp, scheme=scheme, mesh=forwardMesh,
                        noiseLevel=noiseLevel, seed=1337,
                        verbose=True);
    pg.show(geom);
    pg.show(forwardMesh);
    ax, _ = pg.show(forwardMesh, vp, colorBar=True, logScale=False, label='v in m/s')
    pg.viewer.mpl.drawSensors(ax, scheme.sensors(), diam=1.0,
                             facecolor='white', edgecolor='black');
    mgr.showData(simdata);
    
    return simdata.save(name)


def invertData(folder, data = None, vTop = 500, vBottom = 5000, lam = 20, dPhi = 0.0, maxIter = None):
    """Invert travel time data using pygimli's travel time manager module
    
    Parameters:
    
    folder - str: name of folder to save inversion results
    
    
    data - str:  name of data to invert
    
    
    vTop - int: Assuming you set Gradient to True, velocity of top layer to be used in inversion
    
    
    vBottom - int: Assuming you set Gradient to True, velocity of bottom layer to be used in inversion
    
    
    lam - int: Regularization Strength
    
    
    dPhi - int: Minimum dPhi to use as convergence criteria
    
    
    maxIter - int: Maximum number of iterations for the inversion
    
    """
    import pygimli as pg
    from pygimli.physics import TravelTimeManager
    mgr = TravelTimeManager()
    import time
    data = mgr.load(data)
    inversionMesh = mgr.createMesh(data, area = 2)
    inversion_time = time.time()
    mgr.invert(data, mesh = inversionMesh, verbose=True, vTop = vTop, vBottom = vBottom, lam = lam, dPhi = dPhi, maxIter = maxIter, seed = 1337) 
    print("Inversion Estimated Time is %s seconds:" % (time.time() - inversion_time))
    mgr.saveResult(folder = folder);
    pg.show(inversionMesh);
    print(inversionMesh)
```

### Expected behavior

I expect that inverting the same dataset using the same inversion parameters should give entirely deterministic results.

### Actual behavior

Inverting the same simulated traveltime dataset yields different inversion results.

I have attached sample simulated and inverted files...

simulated dataset: 
[ttsim5noise0402-2.txt](https://github.com/gimli-org/gimli/files/8117836/ttsim5noise0402-2.txt)
Three instances of inverting the simulated file and getting different results:
[tt5254Cell5Noiseinvgimli0402-1.txt](https://github.com/gimli-org/gimli/files/8117852/tt5254Cell5Noiseinvgimli0402-1.txt)
[tt5254Cell5Noiseinvgimli0402-5.txt](https://github.com/gimli-org/gimli/files/8117853/tt5254Cell5Noiseinvgimli0402-5.txt)
[tt5254Cell5Noiseinvgimli0402-9.txt](https://github.com/gimli-org/gimli/files/8117854/tt5254Cell5Noiseinvgimli0402-9.txt)

Thank you for your help.

**Comment by carsten-forty2** [comment]
can confirm it .. very slight differences when calling `invertData` twice:

1. run:
```
6: Model: min = 0.000299366; max = 0.00161189
...
6: chi^2(data, Response, error, log) = 0.992411
```

2. run
```
6: Model: min = 0.000298402; max = 0.00162233
...
6: chi^2(data, Response, error, log) = 0.996892
```

Thanks for reporting .. we will try to find out what happens.

**Comment by Don-Timmy** [comment]
Thanks for your prompt response @carsten-forty2 .

**Comment by Don-Timmy** [comment]
Hi, 

I wanted to follow up on this.

Thank you,
E

**Comment by florian-wagner** [comment]
Dear @Don-Timmy,

sorry that we have been so quite on this the last couple of weeks. I looked into this in more detail today using your code above.

The forward simulation, as you probably noticed already, is completely deterministic/repeatable (if the same seed is set to noisify the data): 

``` python
import pygimli as pg
import numpy as np

simulateData(name="data1.sgt")
simulateData(name="data2.sgt")

data1 = pg.load("data1.sgt")
data2 = pg.load("data2.sgt")

pg.boxprint("pyGIMLi version = " + pg.__version__)

for column in ["s", "g", "t", "err"]:
    print(f"Column '{column}' is equal in both simulated data files:", (np.array(data1[column]) == np.array(data2[column])).all())
```

> pyGIMLi version 1.2.5+15.gc17ddda5 (dev)
> Column 's' is equal in both simulated data files: True
> Column 'g' is equal in both simulated data files: True
> Column 't' is equal in both simulated data files: True
> Column 'err' is equal in both simulated data files: True

So far, so good. As you noticed, and as @carsten-forty2 confirmed, the inversion results are slightly different. This is actually not pyGIMLi's fault, but turned out to be due to the external mesh generator `triangle`, which we call within the `mgr.createMesh` function. It produces almost the same meshes (same number of cells, same boundaries, same cell connections, look identical, etc. yet positions of the nodes deviate by $10^{-13}$ m.) This causes the different inversion results. If you repeat inversions, but specify the exact same mesh, the problem is not there anymore. For that purpose, I slightly changed your `invertData` function to allow for a mesh to be specified.

``` python
mesh1 = invertData("inversion1", data="data1.sgt", maxIter=10)
invertData("inversion2", data="data2.sgt", maxIter=10)
invertData("inversion3", data="data2.sgt", maxIter=10, inversionMesh=mesh1)

result1 = pg.load("inversion1/TravelTimeManager/velocity.vector")
result2 = pg.load("inversion2/TravelTimeManager/velocity.vector")
result3 = pg.load("inversion3/TravelTimeManager/velocity.vector")

print("Inversion results with individual mesh creation deviate by %.2f percent." % (pg.utils.rrms(result1, result2) * 100))
print("Inversion results with identical meshes deviate by %.2f percent." % (pg.utils.rrms(result1, result3) * 100))
```

> Inversion results with individual mesh creation deviate by 2.35 percent.
> Inversion results with identical meshes deviate by 0.00 percent.

Thank you for bringing this up, we were not aware of this before, but we think there is not much we can do about it. You could contact the `triangle` developers of course, but the quick workaround would be to use the same meshes when inverting the same data sets.

Best wishes
Florian

---

**Appendix (adapted mesh function)**:

``` python
def invertData(folder, data = None, vTop = 500, vBottom = 5000, lam = 20, dPhi = 0.0, maxIter = None, inversionMesh=None):
    import pygimli as pg
    from pygimli.physics import TravelTimeManager
    mgr = TravelTimeManager()
    import time
    data = mgr.load(data)
    if inversionMesh is None:
        inversionMesh = mgr.createMesh(data, area = 2)
    inversion_time = time.time()
    mgr.invert(data, mesh = inversionMesh, verbose=True, vTop = vTop, vBottom = vBottom, lam = lam, dPhi = dPhi, maxIter = maxIter, seed = 1337) 
    print("Inversion Estimated Time is %s seconds:" % (time.time() - inversion_time))
    mgr.saveResult(folder = folder);
    pg.show(inversionMesh);
    return inversionMesh
```

**Comment by florian-wagner** [comment]
**For later reference**: After submitting the answer and closing the issue, I wondered why the forward calculation is reproducible, while the inversion is not, although both create a mesh on the fly. It turns out that it depends on whether the mesh generator is called with or without the optional smoothing algorithm.

See minimal test here:

``` python
import pygimli.meshtools as mt

geom = mt.createCircle(area=0.01) + mt.createRectangle([-5,-5],[5,5])

for smooth in None, True:
    mesh1 = mt.createMesh(geom, smooth=smooth)
    mesh2 = mt.createMesh(geom, smooth=smooth)
    print("Smooth =", smooth, " --> Mesh identical =", (mesh1.positions().array() == mesh2.positions()).all())
```
> Smooth = None  --> Mesh identical = True
> Smooth = True  --> Mesh identical = False

Since `mt.createMesh` (which you used to create the mesh for forward simulations) has [`smooth=None` as the default](https://github.com/gimli-org/gimli/blob/master/pygimli/meshtools/mesh.py#L11), everything works fine. But the inversion uses `mt.createParaMesh`, which has [`smooth=[2,10]` as the default](https://github.com/gimli-org/gimli/blob/master/pygimli/meshtools/mesh.py#L1948)...

Again, thank you @Don-Timmy for bringing this to our attention!
