### ISSUE TITLE
Error importing .bin files from Prosys into .dat format for BERT

### ISSUE THREAD

**Issue by geoale90** [gimli-org/gimli#367]
Dear pygimli team, 

I need to read a .bin file that is output from some data collection using the Com Sys pro. For doing this, I am using the import module from pybert as follows:

```
import pybert as pb

data = pb.importData(data_address)

```

The data is read without errors, according to this message:

```
data = pb.importData(data_address, verbose = True)
23/02/22 - 17:50:26 - pyGIMLi - INFO - imported:  Data: Electrodes: 192 data: 1568
```

However, when I want to access the data fields as follows:

```
a = data['rhoa']
a = data['rhoa'].array()
a
Out[80]: array([0., 0., 0., ..., 0., 0., 0.])
```

 the data appear as all equal to zero.  The same happens to all the other fields or tokens (e.g., 'k', 'err', etc)

Just to clarify, this does not happen when I first transform the .bin files into .dat format and then read the latter as follows with the pygimli load module:

```
data=pg.load(data_address)
```

So there is probably a small issue that is preventing me to read the data in .bin format, although I am not sure what it is. I can provide the example data file if needed.

Thanks a lot in advance.
Best,
Alejandro

### Your environment

**Operating system**: Windows
**Python version**: 3.8
**pyGIMLi version**: 
print(pg.__version__)
0+unknown
print(pg.version)
<function version at 0x0000021196298E50>
**Way of installation**: Conda package

**Comment by carsten-forty2** [comment]
This seems to me this should be a pybert issue. https://gitlab.com/resistivity-net/bert

However, show `print(data['u'])` and `print(data['i'])` also zeros? Then it would be helpful to provide the bin file there.

**Comment by geoale90** [comment]
Hello Carsten-forty2,
Thanks for your reply. Finally, the mistake was mine. Both '''print(data['u'])''' and  '''print(data['i'])''' give non-zero values. I don't see any issue with the importer.

Thanks again and sorry for the inconvenient.

Cheers,
Alejandro
