### ISSUE TITLE
[question] Merging several ERT simulations

### ISSUE THREAD

**Issue by TheNablaOperator** [gimli-org/gimli#368]
### Problem description

Is it possible to merge several ERT simulations?
I want to make a pseudo-3D ERT measurement (6 survey lines on 3D geometry). I have done this before using Geotomo Software, but I want to do all my future tasks with pg. For learning and getting into pg I am re-programming old data...
I am also happy to provide this as an example if you want. 
But I got stuck at some points (this is one), which need to be cleared before.

Thank you in advance!

### Your environment

**Operating system**: Win10
**Python version**: 3.8.12
**pyGIMLi version**: 1.2.4
**Way of installation**: conda

### Steps to reproduce

This is just the code snippet from ERT simulation. It should give the idea, what I want to do...
I know that `sim0 + sim1` won't simply work...

```python
import pygimli.meshtools as mt
import numpy as np
import pygimli as pg
from pygimli.physics import ert

...

sim0 = ert.simulate(mesh, 
                    res=rhomap, 
                    scheme=shm0, 
                    verbose=True)

sim0.save('sim0.ohm', 'a b m n u rhoa')

sim1 = ert.simulate(mesh, 
                    res=rhomap, 
                    scheme=shm1, 
                    verbose=True)

pg.show(sim0)
pg.show(sim1)

# Combine survey lines ??
survey = sim0 + sim1;
```

**Comment by carsten-forty2** [comment]
You can merge `DataContainerERT` with the app 'dataMerge' and the python code within.

Its more or less the same like:
```
survey = pg.DataContainerERT(sim0)
survey.add(sim1)
```

It will reuse common sensor positions so if you want 3D geometry you need to set the `sim0.setSensors(...)` before merging. 
Note, there is not yet a convenience function for creating default 3D inversion meshes so you need to create a suitable 3D mesh yourself or use BERT command line tool chain for this.

**Comment by TheNablaOperator** [comment]
Thank you @carsten-forty2 
I stored the sensor positions for each measurement line in a separate Scheme-File.
I know about 3D meshing. @halbmy helped me already with that in the issue #360
