### ISSUE TITLE
3D ERT Boundaries

### ISSUE THREAD

**Issue by ChangJingRun1997** [gimli-org/gimli#377]
### Problem description
Hi,I am learing pygimli.
I want to use a structured hexahedral mesh, how do I set the boundary conditions?

### Your environment

**Operating system**:  Mac
**Python version**: 3.8
**pyGIMLi version**: 1.2.4
### Steps to reproduce
```python
import pygimli as pg
import numpy as np
x=np.arange(0,10,1)
y=np.arange(0,10,1)
z=np.arange(0,10,1)
grid = pg.createGrid(x=x,y=y,z=z)
for c in grid.cells():
    c.setMarker(2)
 for b in grid.boundaries():
        if b.marker() < 0:
            b.setMarker(pg.core.MARKER_BOUND_MIXED)
```

### Expected behavior
I want to give the same grid and electricity supply as my Matlab to calculate the Jacobi matrix and compare the differences.

**Comment by ChangJingRun1997** [comment]
Thanks！ Following your suggestion i write these lines:
`import pygimli.meshtools as mt
from pygimli.physics import ert
x=[0,3,5,6,7,8,9,10,10.5,11,11.5,12,12.5,13,13.5,14,15,17,20]
y=[0,2,4,4.5,5,5.5,6,6.5,7,7.5,8,9,10]
z=[0,-0.1,-0.3,-0.5,-1,-2,-3,-4,-5,-6,-7,-10]
grid=mt.createGrid(x=x,y=y,z=z, worldBoundaryMarker=True,marker=2)
data = ert.load("dfData.dat")
data["err"] = ert.estimateError(data)
data['k'] = ert.createGeometricFactors(data, numerical=True)
mgr=ert.ERTManager()
inv=mgr.invert(data=data,mesh=grid,lam=10)
mgr.saveResult()
`
Thank you again！
My start model is composed of two regions, how do I give it before the inversion?

**Comment by ChangJingRun1997** [comment]
Thanks！ Following your suggestion i write these lines:
`import pygimli.meshtools as mt
from pygimli.physics import ert
x=[0,3,5,6,7,8,9,10,10.5,11,11.5,12,12.5,13,13.5,14,15,17,20]
y=[0,2,4,4.5,5,5.5,6,6.5,7,7.5,8,9,10]
z=[0,-0.1,-0.3,-0.5,-1,-2,-3,-4,-5,-6,-7,-10]
grid=mt.createGrid(x=x,y=y,z=z, worldBoundaryMarker=True,marker=2)
data = ert.load("dfData.dat")
data["err"] = ert.estimateError(data)
data['k'] = ert.createGeometricFactors(data, numerical=True)
mgr=ert.ERTManager()
inv=mgr.invert(data=data,mesh=grid,lam=10)
mgr.saveResult()
`
Thank you again！
My start model is composed of two regions, how do I give it before the inversion?

**Comment by halbmy** [comment]
Are you working in a) a closed domain or b) an unbounded (half-space) domain?

If a) you should use other Neumann boundary conditions everywhere

If b) there is no need to compute the geometric factors numerically. And if you want to compute them numerically, you need to pass the mesh or the geometry, and you will need a much finer mesh.

**Comment by halbmy** [comment]
As to the starting model (I guess also a reference?), either you define two regions by setting different markers, e.g. according to the cell center positions, or you create a vector likewise (`[1 if cc.z() > 0.5 for cc in mesh.cellCenters() else 2]`)

**Comment by ChangJingRun1997** [comment]
My aim is to give different resistivities to the two regions in the starting model before the inversion.
I am working in an unbounded(half-space) domain.I'm not sure how do you make this vector work.
The resistivity of region 1 is 500 ohms and region 2 is 100 ohms
`grid=mt.createGrid(x=x,y=y,z=z, worldBoundaryMarker=True,marker=2)
for cc in grid.cellCenters():
    if cc.z() >=-10 and round(cc.y(),2)==6.55:
        v.append(1)
    else:
        v.append(2)
#resistivity
romap=[[1,500],[2,100]]
data = ert.load("dfData.dat")
data["err"] = ert.estimateError(data)
mgr=ert.ERTManager()
inv=mgr.invert(data=data,mesh=grid,lam=10,verbose=True,startModel=[])`

**Comment by ChangJingRun1997** [comment]
My aim is to give different resistivities to the two regions in the starting model before the inversion.
I am working in an unbounded(half-space) domain.I'm not sure how do you make this vector work.
The resistivity of region 1 is 500 ohms and region 2 is 100 ohms
`
grid=mt.createGrid(x=x,y=y,z=z, worldBoundaryMarker=True,marker=2)
v=[1 if cc.z() >=-10 and round(cc.y(),2)==6.55 else 2 for cc in grid.cellCenters()]
#resistivity
romap=[[1,500],[2,100]]
data = ert.load("dfData.dat")
data["err"] = ert.estimateError(data)
mgr=ert.ERTManager()
inv=mgr.invert(data=data,mesh=grid,lam=10,verbose=True,startModel=[])
`

**Comment by halbmy** [comment]
```
v = [0 if cc.z() >=-10 and round(cc.y(),2)==6.55 else 1 for cc in grid.cellCenters()]
rhomap = np.array([500, 100])
invert(..., startModel=rhomap[v])
```

**Comment by ChangJingRun1997** [comment]
Thank you so much, this is what I was looking for, it's running great now.
