### ISSUE TITLE
inverted parameters

### ISSUE THREAD

**Issue by stefanazzz** [gimli-org/gimli#378]
### Problem description

Not really a problem, but a question.

When inverting ERT or seismic data, the forward model is implemented on a relatively fine mesh.
I suppose that the values on such mesh are interpolated (or refined) from a smaller number of parameters which are actually inverted. 

For example,  I imagine something like a few number of positions (x_i, y_i) for sample points and values v_i at such points, and a the object of inversion (model) is an array (x_n, y_n, v_n)  with a total number of parameters 3 n. Where 3 n is much smaller than the number of polygons in the forward model mesh. 

I have not found reference to the underlying parameterisation of the model space. Can the model parameters be directly accessed rather than the refined mesh used for the forward model? 

Thanks,
SN

### Your environment
Linux 3.7.7 
pygimli 1.1.1+0.gbb685a8c (with local changes)
install as Conda package
Label as question

**Comment by halbmy** [comment]
In an ERT inversion, the resistivity is assumed piece-wise constant in every model cell, which you can assess directly by `mgr.paraDomain`. The forward mesh is typically a refined version of it with some boundary but what you get is a mesh and a resistivity vector for each CELL, not node or edge or whatsoever.

**Comment by stefanazzz** [comment]
thanks Thomas,
in one of my application examples, mgr.paraDomain returns:
"Mesh: Nodes: 541 Cells: 922 Boundaries: 1462"
So is it really minimising misfit for 922 values? that seems a lot of model parameters to invert!

**Comment by halbmy** [comment]
This means the number of cells (922) is the length of the model vector, quite a low number actually. But the data (and thus misfit) size is completely independent on it.

**Comment by halbmy** [comment]
This very general question can only be clarified by further examples but I guess there won't be any further discussion here.
