### ISSUE TITLE
Problem building pygimli with python3.5

### ISSUE THREAD

**Issue by kodaz1** [gimli-org/gimli#38]
hello, 
I'm trying to build pygimli with python3.5  cause i upgrade my system to ubuntu16.04 LTS which is using python3.5 instead of python3.4 on ubuntu14.04 on a 64 bits system . 

After installing all the dependencies the same error occurs when i use the build script
 curl -Ls install.pygimli.org | bash 
or when i run step buy step the building process as you explain it in the documentation. 
I mainly notice these lines:
CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:178 (include):
  include could not find load file:
    /usr/share/llvm/cmake/LLVMExports.cmake
Call Stack (most recent call first):
  CMakeLists.txt:64 (find_package)
CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:181 (include):
  include could not find load file:
    /usr/share/llvm/cmake/LLVM-Config.cmake
Call Stack (most recent call first):
  CMakeLists.txt:64 (find_package)
CMake Error at src/CMakeLists.txt:46 (llvm_map_components_to_libnames):
  Unknown CMake command "llvm_map_components_to_libnames".
 

*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'fadisaac@gnutrip.(none)')

~/gimli/thirdParty/src ~/gimli/thirdParty
abort: couldn't find mercurial libraries in [/usr/bin /usr/lib/python35.zip /usr/lib/python3.5 /usr/lib/python3.5/plat-x86_64-linux-gnu /usr/lib/python3.5/lib-dynload /home/fadisaac/.local/lib/python3.5/site-packages /usr/local/lib/python3.5/dist-packages /usr/lib/python3/dist-packages]
(check your install and PYTHONPATH)

Sorry to disturb you but do you have any idea on what is happening if you have a little time to look at the problem. 

Thank you for your help 
the logfile is in attachment. 
[log.txt](https://github.com/gimli-org/gimli/files/250199/log.txt)

**Comment by carsten-forty2** [comment]
hello,

there are 2 problems .. the first is that you cannot build castXML  
(which we need to generate the python bindings) due a possible wrong  
or uncomplete llvm installation on your ubuntu. Second seems that the  
git update fails to fetch pygccxml and pyplusplus.

The second problem seems easy to solve by removing the  
thirdParty/src/pygccxml and thirdParty/src/pyplusplus

The first is castXML or ubuntu related, you can either use an old  
castxml binary (if you still have) or take a look at there issuetracker:

https://github.com/CastXML/CastXML/issues/53

e.g.:
Please make sure the libclang-3.8-dev package is installed.

Hope this helps ..




Quoting kodaz1 <notifications@github.com>:

**Comment by kodaz1** [comment]
Hello , 
Thank you for your help . libclang3.8-dev was already installed but it doesn't work. I try to install all packages referring to clang3.8 or llvm3.8 but i still can't build castxml . 
Perhaps it's an idea to downgrade to clang3.7 and llvm 3.7.

**Comment by kodaz1** [comment]
Hello Carsten, 
castxml have been compiled and build after downgrading clang3.8 and llvm3.8 to clang3.7 and llvm 3.7 and changing the python priority (python2.7 to python3.5) using:
 update-alternatives --config python 
It seems that the problem was due to a Debian packaging bug in clang3.8 : https://github.com/CastXML/CastXML/issues/58
But pygccxml and pyplusplus still doesn't compile and the same error occurs even when i try with python3.4: 
abort: couldn't find mercurial libraries in /usr/bin /usr/lib/python35.zip /usr/lib/python3.5 /usr/lib/python3.5/plat-x86_64-linux-gnu /usr/lib/python3.5/lib-dynload /home/fadisaac/.local/lib/python3.5/site-packages /usr/local/lib/python3.5/dist-packages /usr/lib/python3/dist-packages

I have tried to add to the pythonpath, the path to the mercurial libs : 
/usr/lib/python2.7/dist-packages/mercurial
but it doesn't work 
I have copied the mercurial libs into /usr/lib/python3.5/mercurial before retrying  and i got the following error : 
Traceback (most recent call last):
  File "/usr/bin/hg", line 41, in <module>
    mercurial.util.setbinary(fp)
  File "/usr/lib/python3.5/mercurial/demandimport.py", line 130, in __getattribute__
    self._load()
  File "/usr/lib/python3.5/mercurial/demandimport.py", line 96, in _load
    mod = _hgextimport(_import, head, globals, locals, None, level)
  File "/usr/lib/python3.5/mercurial/demandimport.py", line 53, in _hgextimport
    return importfunc(name, globals, *args, **kwargs)
.....
You can find the complete logfile in attachment.
thank you for your help
[log1.txt](https://github.com/gimli-org/gimli/files/252039/log1.txt)

**Comment by carsten-forty2** [comment]
Do you have mercurial installed?

does a

hg --version

works?

pygccxml and pyplusplus does not need to be compiled .. both will just  
be cloned from there respective locations with git(pygccxml) and  
mercurial(pyplusplus



Quoting kodaz1 <notifications@github.com>:

**Comment by kodaz1** [comment]
hello 
Yes mercurial is already installed and the libraries are in , 
/usr/lib/python2.7/dist-packages/mercurial

**Comment by carsten-forty2** [comment]
I know nothing about mercurial and python .. the question is if

hg clone https://bitbucket.org/ompl/pyplusplus

works?

Quoting kodaz1 <notifications@github.com>:

**Comment by kodaz1** [comment]
Sorry i haven't seen your answer  
yes hg works fine

**Comment by carsten-forty2** [comment]
the latest log states that the hg command fails .. is your problem solved now?

**Comment by kodaz1** [comment]
Hello Carsten
I was  finally able to  install pygimli with the  anaconda suite  a few
days ago. That solved the problem.
Thank you for your support.
Sorry but i still need your help for BERT .
I 'm doing a master thesis at the university of Mons in Belgium about the
influence of temperature on resistivity modelling.
My professor and his assistant  suggested to use Bert
I wrote  mails in order to be allow to download and install it.
Please, can you help me for that.
I 'm on Xubuntu 16.04 / 64 bits

Best regards
A lost student


2016-05-09 14:34 GMT+02:00 carsten-forty2 <notifications@github.com>:

**Comment by carsten-forty2** [comment]
For BERT related question please see: https://gitlab.com/resistivity-net/bert

You probably need an account there so I can add you into the BERT user list.

Best regards,
Carsten

**Comment by florian-wagner** [comment]
We don't have a bert package in anaconda yet, but if @carsten-forty2 and @halbmy are okay with it, I can quickly compile one for you, so that you are able to do a quick ```conda install -c gimli bert```.

**Comment by kodaz1** [comment]
hello Carsten,
I'm waiting for there answer thank you very much for your proposition.
I'll give you the feedback as soon as they give me an answer.



2016-05-23 15:16 GMT+02:00 Florian Wagner <notifications@github.com>:

**Comment by kodaz1** [comment]
Sorry florian , I'm confused, I called you Carsten.


2016-05-23 15:38 GMT+02:00 Tenten Ten <mapuke@gmail.com>:

**Comment by kodaz1** [comment]
Hello Carsten and Florian


I'm  stressed now because of a lot of things to do and to study.
I have created an account on gitlab as you ask. What should i have to  do
else ?
Thank you all


2016-05-23 16:04 GMT+02:00 Tenten Ten <mapuke@gmail.com>:

**Comment by carsten-forty2** [comment]
This issue tracker here is only GIMLi related. 

There is a different location for the BERT Project. https://gitlab.com/resistivity-net/bert/

Until now you need to register at http://gitlab.com/ and we need to invite you to the BERT community. 

Please write me a PM or an email with your gitlab account name.
