### ISSUE TITLE
How to choose the method to solve the linear system of equations in "solveFiniteElements"?

### ISSUE THREAD

**Issue by geoale90** [gimli-org/gimli#381]
### Problem description

Hi, 

I wonder how can I choose the method (direct or conjugate-gradient) to solve the resulting system of linear equations when using  the "solveFiniteElements" module from pyGIMLi?
My computational grid is relatively small (250*250) and I need maximum accuracy so in case that the "solveFiniteElements" is using the conjugate-gradient method, I would like to switch it to some direct method.

Please see below a minimalistic version of my script in case is useful.

Thanks in advance.

```python
import pygimli as pg
import numpy as np

neumannBCHOR = {3: 0.0, 4: 0.0}
dirichletBCHOR = {1: 10.0, 2: 0.0}
bcHOR = {'Dirichlet': dirichletBCHOR,'Neumann': neumannBCHOR}   

mesh = pg.createGrid(x=np.linspace(0.0, 1.0, 250),y=np.linspace(0.0, 1.0, 250))
Cin =    np.ones((250,250))
Cin= Cin.reshape( ( 250*250, 1) )
u = pg.solver.solveFiniteElements( mesh, a=Cin, f=0.0, bc = bcHOR )

**Comment by carsten-forty2** [comment]
`solveFiniteElements` is using the direct solver `cholmod` for symmetric systems (usual default) or `umfpack` for complex valued systems. There is not yet any interface to a conjugate gradient solver implemented so far.

**Comment by halbmy** [comment]
As the question is answered and we are using direct solvers, the issue can be closed.
