### ISSUE TITLE
Fixing (constraining) parameter values in inverion of 1D models

### ISSUE THREAD

**Issue by whitmand** [gimli-org/gimli#383]
### Problem description
I have been modeling and inverting VES data using the procedures in the "VES inversion for a blocky model" tutorial. So far, everything is working great but I cannot figure out how to "fix" some of the parameter values (thickness or resistivity) to the starting model values in the inversion. Is there a method/attribute for f = pg.core.DC1dModelling or inv=pg.core.Inversion where I can fix particular parameters? Or, is it something that I set in the region properties?

Any suggestions? 

### Your environment

**Operating system**: Windows
**Python version**: 3.8.13
**pyGIMLi version**: 1.2.4
**Way of installation**: e.g. Conda package, Win binary, curl script, manual compilation from source

**Comment by halbmy** [comment]
The VES inversion example is really outdated and represents a state of pyGIMLi<1.0 using the core functionality which should not be used anymore. We will have to update this and add other examples for controlling regions or parameters.

**Comment by TheNablaOperator** [comment]
Hello.

> The VES inversion example is really outdated and represents a state of pyGIMLi<1.0 using the core functionality which should not be used anymore. We will have to update this and add other examples for controlling regions or parameters.

For Inversion can still the VESManager be used? 

```python
from pygimli.physics import VESManager
nlay = 3;
ves = VESManager()
inva = ves.invert(rhoa, 
                  nLayer=nlay, 
                  showProgress=0,
                  verbose=0)
res, thk = inva[nlay-1:nlay*2-1], inv[0:nlay-1]
...
```

And probably a silly question.... How do I create the RVector on my own? I have VES data (several values in a table), so I thought to type it is faster than converting into UDF...

Thanks!

**Comment by halbmy** [comment]
Yes you can use the `VESManager` for inverting your data. And you can just use a (1d) numpy array which is compatible with the RVector. Other ways are:
```
x = pg.Vector(10, 1.5) # vector of length 10 filled with 1.5
x[2] = 5
y = pg.Vector([1.0, 4, -10]) # converting a list
z = pg.Vector(np.arange(10))
```

**Comment by halbmy** [comment]
Coming back to the original question: it is generally possible to fix regions (see e.g. https://github.com/gimli-org/transform2022/blob/main/2_Lake.ipynb) by different ways:
* limiting the parameter range by `limits=`
* fixing it to a value and thus remove it from inversion using `fix=`
* using a starting model and a large local regularization (damping) with `cType=0`
If you want to fix one value (a single resistivity or thickness) you would need to define a 1D mesh and associate region markers and leave the standard 1d inversion frame.

In the future we will support any equations on the model parameters like presented in Wagner et al. (2019). For example to fix an interface depth as sum of thickness values.

Wagner, F.M., Mollaret, C., Günther, T., Kemna, A., Hauck, A. (2019): Quantitative imaging of water, ice, and air in permafrost systems through petrophysical joint inversion of seismic refraction and electrical resistivity data. Geophys. J. Int. 219, 1866-1875. doi:10.1093/gji/ggz402.

**Comment by halbmy** [comment]
There is a recent inversion framework LSQRInversion (in the dev branch) where you can state additional equations in a Matrix-vector form with an VES example at the end:
https://github.com/gimli-org/gimli/blob/dev/pygimli/frameworks/lsqrinversion.py

```
G = pg.Matrix(rows=1, cols=len(startModel))
for i in range(3):
    G.setVal(0, i, 1)

c = pg.Vector(1, pg.sum(synthk))
inv.setParameterConstraints(G, c, 100)
```

**Comment by halbmy** [comment]
I created a notebook for this illustrating the use of additional equations:
https://github.com/gimli-org/notebooks/blob/main/inversion/additionalConstraintsVES.ipynb

![image](https://user-images.githubusercontent.com/7136401/207446600-0153d60b-62cf-4ff0-abf1-9596a72b4e35.png)

**Comment by whitmand** [comment]
Thomas,
Thanks for sharing.

One thing, I am getting this error message as well:

“pyGIMLi - WARNING - Multiprocess jacobian currently unavailable for win build”

Is this something that I should be worrying about?

Thanks
Dean

**Comment by halbmy** [comment]
> Is this something that I should be worrying about?

No need to worry.
