### ISSUE TITLE
How to input arbitrary resistivity field into `data = ert.simulate(mesh, scheme=scheme, res=rhomap)` ?

### ISSUE THREAD

**Issue by geoale90** [gimli-org/gimli#384]
### Problem description

Hi,

I am working with this 2D modelling and inversion example of yours:

https://www.pygimli.org/_examples_auto/3_dc_and_ip/plot_01_ert_2d_mod_inv.html#sphx-glr-examples-auto-3-dc-and-ip-plot-01-ert-2d-mod-inv-py

In the example that you provided, you create the conductivity field by assigning each of the 5 regions created, a different conductivity. However, I would like to input an externally-generated and arbitrary conductivity (or resistivity) field where the conductivity varies on a cell- or pixel-basis.  For instance, a square-shaped 2-D multivariate-Gaussian conductivity field created on a regular mesh (grid) or a conductivity field created from a hydrogeological simulation (e.g., a MODFLOW/MT3DMS simulation). For these two cases I mention, the conductivity changes at each cell so I guess the approach of creating a map becomes less practical. In the past, for doing forward simulations, I have been using  `pg.solveFiniteElements` , which allows me to input directly any arbitrary conductivity field. 
However, I would like to be able to do the same but with the dedicated `ert.simulate` module now, as I need to invert the data later.
I guess there must be a simple way of doing this that avoids creating a map ?

Thank you in advance.
Best,
Alejandro

**Comment by carsten-forty2** [comment]
Hi, 

regarding to the api documentation(https://www.pygimli.org/pygimliapi/_generated/pygimli.physics.ert.html?highlight=simulate#pygimli.physics.ert.simulate), the argument `res` in `ert.simulate` should also accept an array of resistivity values for each cell of your mesh. 

(Not to myself: We need to check why the the doc is so poorly rendered)

**Comment by geoale90** [comment]
Hello Carsten,

Thanks for your reply. I thought I had replied before. The documentation may be at times not super easy to follow (at least for me) but this is largely counterbalanced by the prompt and useful responses that you always give so thanks. Also is up to the user to do some of the effort I guess. I am closing the issue although I may come back with some other related questions.

Cheers,
Alejandro
