### ISSUE TITLE
Problem with colorbar's ticklabels in logScale=True

### ISSUE THREAD

**Issue by brianhavk** [gimli-org/gimli#385]
### Problem description

Hello again, 

I don't know if this is just me, but the colorbar's ticklabels is showing up in powers of 10^n, as you can see in the image.
![Figure 2022-04-16 204631](https://user-images.githubusercontent.com/82900508/163697314-ac18df8c-9ec2-49c6-944b-1032f074dc37.png)

I changed the logScale=False to see if the same thing happens when the default linear scale of the Matplotlib library is activated and, as you can see below, the problem is only with the logScale=True.
![Figure 2022-04-16 204821](https://user-images.githubusercontent.com/82900508/163697397-b16582f5-4c38-4fa0-912a-25d559d71717.png)

This is happening on two different computers so I am ruling out hardware and driver problems. 
Also, I tried in Windows 10 and the same thing is happening, and I am currently running a completely clean install of the Windows 11 operating system. I really don't know what could be going on, as this is the first time this has happened.

The code that I downloaded and ran was the one in the example https://www.pygimli.org/_examples_auto/3_dc_and_ip/plot_01_ert_2d_mod_inv.html#sphx-glr-examples-auto-3-dc-and-ip-plot-01-ert-2d-mod-inv-py

I will be very attentive to your answers, thank you very much.

### Your environment

**Operating system**: Windows 11 Pro
**Python version**: 3.8.13
**pyGIMLi version**: 1.2.4
**Way of installation**: Conda package

**Comment by halbmy** [comment]
Hello, the problem occurs with matplotlib >=3.5 and has already been fixed:
https://github.com/gimli-org/gimli/commit/34be07c45795ed5bdad3b12393351a33921f80a3
however shortly after the release of pyGIMLi 1.2.4. For now, you can return the cbar and add this line:
```
from matplotlib import ticker
ax, cb = ert.showData()  # or any other show command
cb.ax.xaxis.set_major_formatter(ticker.ScalarFormatter())
```
We will release a version 1.2.5 by next week.

**Comment by brianhavk** [comment]
Great! Thank you very much for the temporary correction and the announcement of the new version.

I consider closed the issue.
