### ISSUE TITLE
How to solve the potential U

### ISSUE THREAD

**Issue by LiuQian19970208** [gimli-org/gimli#388]
### Problem description
Now there are two point current sources A and B, how to calculate the potential U on all mesh nodes and how to graph the distribution of the potential
`=ert.simulate(mesh, scheme=scheme, res=rhomap,returnFields=True)`

**Comment by halbmy** [comment]
The result of the `ert.simulate()` call is a Matrix of all potentials for every electrode. For two current electrodes you can combine them
```
fields = ert.simulate(...
pot = fields[1] - fields[0]
```
and show the potential difference using `pg.show(mesh, pot)` and draw current lines by (see example in https://www.pygimli.org/_examples_auto/3_dc_and_ip/plot_04_ert_2_5d_potential.html)
```
from pygimli.viewer.mpl import drawStreams
ax = pg.show(mesh, data=pot, cMap="RdBu_r", cMin=-1, cMax=1,
             orientation='horizontal', label='Potential $u$',
             nCols=16, nLevs=9, showMesh=True)[0]
drawStreams(ax, mesh, pot, color='Black')
```
