### ISSUE TITLE
Problem after installing newest version of pygimli, 1.2.5 

### ISSUE THREAD

**Issue by benbpete** [gimli-org/gimli#389]
### Problem description

Hi All,

First time posting here.

I am having an issue with pygimli after the newest update.  The install keeps failing the testing for the methodManager.fit and the VESManager.  See attached for the pytest log.

### Your environment

**Operating system**: Windows
**Python version**:3.8.13
**pyGIMLi version**: 1.2.5 
**Way of installation**: Anaconda

### Steps to reproduce
 
```in command prompt:
(pg) C:\Users\Benjamin Petersen>python -c "import pygimli; pygimli.test(show=False, onlydoctests=True)"
```

### Expected behavior

Previous 2D resistivity inversion files that worked prior to updating pygimli now error during the inversion.  I receive the same errors as I do in the pytest.

### Actual behavior

See attached file for the log.  I receive the same exception twice.

```
UNEXPECTED EXCEPTION: TypeError("int() argument must be a string, a bytes-like object or a number, not 'slice'")

```
Thank you!
[Testing report.txt](https://github.com/gimli-org/gimli/files/8700985/Testing.report.txt)

**Comment by halbmy** [comment]
This is a matplotlib incompatibility (`np.newaxis` cannot be used with `pg.Vector`). Which mpl version do you have?

**Comment by benbpete** [comment]
Looks like version 3.5.2

**Comment by halbmy** [comment]
This should be solved in the next version, if necessary, checkout the git version.

Thanks for reporting! Such feedback is very important.
