### ISSUE TITLE
Travel time inversion difference in different pg version

### ISSUE THREAD

**Issue by geohang** [gimli-org/gimli#392]
### Problem description

Please describe your issue here.

### Your environment

**Operating system**: Windows,
**Python version**: 3.8
**pyGIMLi version**: 1.2.3 and 1.2.5
**Way of installation**: Conda package

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

##The inversion part

mesh=mgr.createMesh(data,quality=32,paraDX=0.05,paraMaxCellSize=30, paraBoundary=0.2,
                    balanceDepth=True)
mgr.setMesh(mesh)

mgr.invert(data, vTop=500,vBottom=5000,lam=50, Weight=0.2,
          verbose=1,limits=[100., 6000.])

### Expected behavior

The two versions of pg should be the same.

### Actual behavior
I have processed several field data. They are all different, and I show two of them here. 

from 1.2.3
<img width="517" alt="image" src="https://user-images.githubusercontent.com/75149424/169556799-4b891de2-0aff-40b3-9237-ef60d36e96cc.png">

from 1.2.5
<img width="569" alt="image" src="https://user-images.githubusercontent.com/75149424/169557603-39daa7e0-cd00-497d-bb3e-279b43710c8a.png">

From 1.2.3
<img width="474" alt="image" src="https://user-images.githubusercontent.com/75149424/169557260-f62d0acf-c0a0-4301-962c-d151a2c98113.png">

From 1.2.5
<img width="475" alt="image" src="https://user-images.githubusercontent.com/75149424/169557510-080ddd3b-0970-417b-9108-3c9423b8ee54.png">

I have also attached one of the field data.
[TL0516 - Copy.txt](https://github.com/gimli-org/gimli/files/8741227/TL0516.-.Copy.txt)

Thank you for your time!

Best,
Hang

**Comment by halbmy** [comment]
They are not looking much different, for a direct comparison you should specify `cMin` and `cMax` arguments to `showResults`.

In the traveltime module, there was no change between v1.2.3 and v1.2.5. There is only one difference regarding the startingModel. In v1.2.3 it was by default used as reference model, whereas in v1.2.5 it is not by default. In other words, new the smoothness of the model is minimized, whereas formerly the smoothness of the difference to the gradient model was minimized. This makes no sense and is the reason for the difference of the models. I consider the 1.2.5 results more reliable.

P.S.: A velocity of 100m/s appears not meaningful to me as already the speed in the air is above 300m/s.

**Comment by halbmy** [comment]
For your case it makes sense to use anisotropic regularization, but the argument is `zWeight=0.2`, not `Weight=0.2`

**Comment by halbmy** [comment]
You should be able to reproduce the same image using `isReference=True` in the invert call. However, I do not recommend it in your case as your model will always stay like a gradient model but you would rather like to see some contrasts.

**Comment by geohang** [comment]
Thank you very much! I think it makes sense since the smoothness is minimized without a reference, the new version results seem to be shallow and slightly lower velocity. I agree with your point, the new version results seem more stable, and I was figuring out why the difference. Your answer is very helpful! 

> For your case it makes sense to use anisotropic regularization, but the argument is `zWeight=0.2`, not `Weight=0.2`

Thank you for the reminder. I did a typo there.

**Comment by halbmy** [comment]
Thanks for raising this issue, it might help other users.
