### ISSUE TITLE
Question about Transform 2022 ERTwithPrior

### ISSUE THREAD

**Issue by geohang** [gimli-org/gimli#395]
### Problem description

I reproduced the ERTwithPrior example from Transform 2022. I have a question about structural constraints. The structural constraints are achieved by relaxing the regularization matrix, but when I output the regularization matrix by _mgr.fop.constraints_, I don't see any term in the regularization matrix that has been removed. I am curious about how to get the right regularization matrix with structural constraints. Thank you!

### Your environment

**Operating system**:Windows
**Python version**: 3.7
**pyGIMLi version**: 1.2.6
**Way of installation**: Conda package

### Steps to reproduce

See attached Jupyter notebook structure constraint part.

The code that gets the regularization matrix:

C = mgr.fop.constraints()
mgr.fop.constraints
Wm_r = pg.utils.sparseMatrix2coo(C)
Wm_r = Wm_r.todense()
mgr.fop.regionProperties()

### Expected behavior

See some constraint in the regularization matrix has been removed.

### Actual behavior

no constraint in the regularization matrix has been removed.
![image](https://user-images.githubusercontent.com/75149424/173505915-a9b0502f-20fc-4db0-a168-4364dd2c5911.png)

**Comment by geohang** [comment]
The Jupyte Notebook file: https://drive.google.com/file/d/1yCMCz_wFb-MwDI8i4Cxr6fJazkmlF3Ec/view?usp=sharing

**Comment by halbmy** [comment]
First, there must be something wrong. There is no version v1.2.6 for Python 3.7 under Windows.

**Comment by halbmy** [comment]
The constraint matrix is always a full matrix, in case of smoothness with -1 and +1 values. Any weighting of the boundaries is done by a weighting vector that contains 1.0 values by defaults but lower values at defined boundaries or depending on the dip angle of the boundary. The following script illustrates this on a very simple model:
```
import numpy as np
import pygimli as pg
from pygimli.frameworks import PriorModelling

grid = pg.meshtools.createGrid([0, 1, 2, 3], [0, -0.5, -1])
grid.boundary(1).setMarker(1)
fop = PriorModelling(grid, [[0.5, -0.2], [2.5, -0.8]])
inv = pg.Inversion(fop=fop, mesh=grid)
inv.setRegularization(zWeight=0.3)
model = inv.run(np.array([1, 2]), np.array([0.1, 0.1]))
pg.show(grid, model)
C = fop.constraints()
print(C.rows(), C.cols())
cw = fop.regionManager().constraintWeights()
print(cw)
```
yielding `7 [0.0, 0.30000000000000004, 1.0, 0.30000000000000004, 0.30000000000000004, 1.0, 1.0]`. Of the seven internal boundaries (three vertical and four horizontal ones) one (between the upper left two cells) is marked with a marker and obtains a zero values (allowed interface). The others are defined either 1 (horizonal) or 0.3 (vertical) depending on the orientation according to the `zWeight=0.3` term.

**Comment by geohang** [comment]
> First, there must be something wrong. There is no version v1.2.6 for Python 3.7 under Windows.

Sorry. Thanks for pointing out. It is a typo. It is Python 3.8

**Comment by geohang** [comment]
> cw = fop.regionManager().constraintWeights()
> print(cw)

Got it! That's really helpful. Thank you!
