### ISSUE TITLE
Question about CGLS solver

### ISSUE THREAD

**Issue by geohang** [gimli-org/gimli#397]
### Problem description

I found the CGLS solver in Pygimli is pretty robust and quick compared to the lsqr from scipy. I wonder if it is possible to use the CGLS in Pygimli to solve other least square problems, for example. form as Ax =b. I know the CGLS in Pygimli is from C++ file, but I didn't find the place in Pygimli to call it.

### Your environment

**Operating system**: e.g. Windows
**Python version**: 3.8
**pyGIMLi version**: 1.2.6
**Way of installation**:Conda package,

**Comment by halbmy** [comment]
Actually the CGLS and LSQR are based on the same Krylov subspace iteration.

Don't know whether it makes sense to use the solver alone and not the whole inversion frame.
There is `pg.core.solveCGLSCDWWhtrans`:
```
solveCGLSCDWWhtrans( (object)S, (object)C, (object)dWeight, (object)b, (object)x, (object)wc, (object)wm, (object)tm, (object)td, (object)lambda, (object)roughness [, (object)maxIter=200 [, (object)tol=-1.0 [, (object)verbose=False]]]) -> object :

    C++ signature :
        int solveCGLSCDWWhtrans(GIMLI::MatrixBase,GIMLI::MatrixBase,GIMLI::Vector<double>,GIMLI::Vector<double>,GIMLI::Vector<double> {lvalue},GIMLI::Vector<double>,GIMLI::Vector<double>,GIMLI::Vector<double>,GIMLI::Vector<double>,double,GIMLI::Vector<double> [,int=200 [,double=-1.0 [,bool=False]]])
```
with the intrinsic sensitivity S, the constraint matrix C, the right-hand side vector b, weighting vectors for data, constraints and model, transformation derivatives for model and data etc.

**Comment by geohang** [comment]
Thank you for the quick reply. That's helpful. I will try if it can be used to solve other problems. Thank you!

**Comment by halbmy** [comment]
Closing the issue.

P.S.: In the dev branch there are Python versions of CGLS and LSQR inverse solvers (for which everything needs to be in one matrix, e.g. a block matrix with Jacobian and constraint matrices including weightings for data error and transformations.
They will replace the current solver
https://github.com/gimli-org/gimli/blob/dev/pygimli/solver/leastsquares.py
