### ISSUE TITLE
Timing of control output in solute transport

### ISSUE THREAD

**Issue by bravegr** [gimli-org/gimli#398]
### Problem description

Please describe your issue here.
Hello, teacher! I would like to ask: I will change this code to make the program injection time 1 year. The final output of concentration results in the form of monthly output, and a total of 1 year (12 months) output of concentration results, how to modify the code? Thank you very much for answering my questions

### Your environment

**Operating system**: Windows
**Python version**: 3.7
**pyGIMLi version**: 1.2.4
**Way of installation**:  Conda package

### Steps to reproduce

```python
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
import pygimli.physics.ert as ert
import pygimli.physics.petro as petro
from pygimli.physics import ERTManager

################################################################################
# Create geometry definition for the modeling domain
world = mt.createWorld(start=[-20, 0], end=[20, -16], layers=[-2, -8],
                       worldMarker=False)

# Create a heterogeneous block
block = mt.createRectangle(start=[-6, -3.5], end=[6, -6.0], marker=4,
                           boundaryMarker=10, area=0.1)
# Merge geometrical entities
geom = world + block
pg.show(geom, boundaryMarker=True)

################################################################################
# Create a mesh from the geometry definition
mesh = mt.createMesh(geom, quality=32, area=0.2, smooth=[1, 10])
pg.show(mesh)

################################################################################
# Fluid flow in a porous medium of slow non-viscous and non-frictional hydraulic
# movement is governed by Darcy's Law according to:
#
# We begin by defining isotropic values of hydraulic conductivity :math:`K` and
# mapping these to each mesh cell:

# Map regions to hydraulic conductivity in $m/s$
kMap = [[1, 1e-8], [2, 5e-3], [3, 1e-4], [4, 8e-4]]

# Map conductivity value per region to each cell in the given mesh
K = pg.solver.parseMapToCellArray(kMap, mesh)

pg.show(mesh, data=K, label='Hydraulic conductivity $K$ in m$/$s', cMin=1e-5,
        cMax=1e-2, logScale=True, grid=True)
################################################################################
# Dirichlet conditions for hydraulic potential
left = 0.75
right = 0.0
pBound = {"Dirichlet": {1: left, 2: left, 3: left, 5: right, 6: right, 7: right}}
################################################################################
# Solve for hydraulic potential
p = pg.solver.solveFiniteElements(mesh, a=K, bc=pBound)

# Solve velocity as gradient of hydraulic potential
vel = -pg.solver.grad(mesh, p) * np.asarray([K, K, K]).T

ax, _ = pg.show(mesh, data=pg.abs(vel) * 1000, cMin=0.05, cMax=0.15,
                label='Velocity $v$ in mm$/$s', cMap='YlGnBu', hold=True)
ax, _ = pg.show(mesh, data=vel, ax=ax, color='k', linewidth=0.8, dropTol=1e-5,
                hold=True)
S = pg.Vector(mesh.cellCount(), 0.0)
# Fill injection source vector for a fixed injection position
sourceCell = mesh.findCell([-19.1, -4.6])
S[sourceCell.id()] = 1.0 / sourceCell.size()  # g/(l s)
# Choose 800 time steps for 6 days in seconds
t = pg.utils.grange(0, 6 * 24 * 3600, n=800)

# Create dispersitivity, depending on the absolute velocity
dispersion = pg.abs(vel) * 1e-2

# Solve for injection time, but we need velocities on cell nodes
veln = mt.cellDataToNodeData(mesh, vel)
c1 = pg.solver.solveFiniteVolume(mesh, a=dispersion, f=S, vel=veln, times=t,
                                 scheme='PS', verbose=0)

# Solve without injection starting with last result
c2 = pg.solver.solveFiniteVolume(mesh, a=dispersion, f=0, vel=veln, u0=c1[-1],
                                 times=t, scheme='PS', verbose=0)
# Stack results together
c = np.vstack((c1, c2))

# We can now visualize the result:
for ci in c[1:][::200]:
    pg.show(mesh, data=ci * 0.001, cMin=0, cMax=3, cMap="magma_r",
            label="Concentration c in $g/l$")

...
```

### Expected behavior

Output the concentration results for one year, 12 months, and each month

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

[plot_hydrogeophysical_modeling (4).zip](https://github.com/gimli-org/gimli/files/8949777/plot_hydrogeophysical_modeling.4.zip)

**Comment by halbmy** [comment]
The final concentration is of `c.shape` (1600, 5637), i.e. you have 5637 mesh cells and 1600 time steps. The time array `t=pg.utils.grange(0, 6 * 24 * 3600, n=800)` goes over 6 days (in 11min steps) but it is used twice so that actually 12 days are covered in c. So you would have to use either a longer time vector or greater time steps to have the result at longer times. Note however that for the hydraulic conductivity given, the tracer will be long gone after a few months.

**Comment by halbmy** [comment]
Please read the paper for more details.

Rücker, C., Günther, T., Wagner, F.M. (2017): pyGIMLi: An open-source library for modelling and inversion in geophysics, Computers & Geosciences 109, 106-123, doi:10.1016/j.cageo.2017.07.011.

**Comment by bravegr** [comment]
> The final concentration is of `c.shape` (1600, 5637), i.e. you have 5637 mesh cells and 1600 time steps. The time array `t=pg.utils.grange(0, 6 * 24 * 3600, n=800)` goes over 6 days (in 11min steps) but it is used twice so that actually 12 days are covered in c. So you would have to use either a longer time vector or greater time steps to have the result at longer times. Note however that for the hydraulic conductivity given, the tracer will be long gone after a few months.

Thank you very much for your reply, I still don't quite understand: in the last for loop: for CI in C [1:][::200]: it outputs 8 concentration result graphs in total. T = pg.utils.grange(0, 6 * 24 * 3600, n=800)

I don't think the last for loop outputs 8 images by day. I wonder how to change the code so that it outputs by day?

2. How can I modify the code to output monthly when I change the injection time to T =365 * 24 * 3600

**Comment by carsten-forty2** [comment]
The injection time is in the unit of seconds, so if you want to view results every month you need something like `C[1:][::30*24*3600]` but note the hydrodynamic parameters are choosen for a kind of fast advection, so you need to slow them or you won't see anything usefull.

**Comment by halbmy** [comment]
> I don't think the last for loop outputs 8 images by day. I wonder how to change the code so that it outputs by day?

`c[::24*60*60, :]` will give you 12 slices, one for each day
