### ISSUE TITLE
Question about 3D mesh for Cylinder

### ISSUE THREAD

**Issue by geohang** [gimli-org/gimli#399]
### Problem description

I am trying to mesh two combined cylinders for ERT. It works well if I don't add electrode
 nodes and reference nodes. But after adding these nodes the mesh becomes super wield and cannot do the forward modeling correctly. I don't know if you have any suggestions for these. Thank you!

### Your environment

**Operating system**: Windows
**Python version**: 3.8
**pyGIMLi version**: 1.2.6
**Way of installation**: Conda package

### Steps to reproduce
I attach two figures. And the detailed files are attacted.
![image](https://user-images.githubusercontent.com/75149424/174906189-f2cba48e-24a5-4bd0-8df3-dbfbf212af1a.png)
![image](https://user-images.githubusercontent.com/75149424/174906209-2f404066-f6a0-44ea-ab6c-9a84e0834084.png)

### Expected behavior

The 3D mesh should be fine and normal.

### Actual behavior

The 3D mesh is very coarse and cannot do forward modeling. I change any parameters in the function which makes results still keep the same.

The codes
https://drive.google.com/drive/folders/1yWIyDPAytj06my4NHGju4eBQKbk2UiWC?usp=sharing

**Comment by carsten-forty2** [comment]
Also got a tetgen error when I add the -999 electrode (still need to search for the reason). In the meantime you can move this node a little inside the domain, which is okay for simulation.

```
plc3 = mt.readSTL('fromcomsol.stl', binary=True)
#pg.show(plc3, showMesh=True, filter={'clip':{}})

plc3.createNode([0.0, 0.0, 0.001], marker=-999)
plc3.createNode([0.0, 0.0, 0.4572], marker=-1000)

mesh = mt.createMesh(plc3, quality=1.2, area=0.00003)
pg.show(mesh, showMesh=True, filter={'clip':{}})

# this is makes the same like above
#pg.meshtools.exportPLC(plc3, 'TTemp')
#mesh = pg.meshtools.syscallTetgen('TTemp.poly', quality=1.2, area=0.0001)
```
Got this mesh with tetgen-1.5.1. Note the quality value should be not lower than 1.1 but much lower then 30.

![image](https://user-images.githubusercontent.com/6043771/175291894-b31ed886-e852-45c2-9b9e-52fcb65fffa4.png)

Visuals are from the current dev branch. You can use paraview and `exportVTK` until we push the new release.

**Comment by geohang** [comment]
Thank you very much! That's very helpful
