### ISSUE TITLE
Question about load mesh from other sources

### ISSUE THREAD

**Issue by geohang** [gimli-org/gimli#405]
### Problem description

I try to load the mesh (in stl format) generated by COMSOL. After loading the mesh in Pygimli, it shows there is no cell in the mesh but it does have nodes and boundaries.  I don't know if any way, we can have the cell from the loaded mesh. I have tried to use the mt.createMesh, but it will lose some features (e.g., borehole) from the original mesh. I will appreciate if you can give some suggestions. Thank you!

### Your environment

**Operating system**: Windows
**Python version**: 3.8
**pyGIMLi version**: 1.2.6
**Way of installation**: Conda package

### Steps to reproduce

See attached file

### Expected behavior
I want mesh like this
![image](https://user-images.githubusercontent.com/75149424/176984925-285fc973-71bb-4e1a-ad4b-645d56b38e7a.png)

### Actual behavior
The generated mesh from mt.createMesh loses a lot of information. 
![image](https://user-images.githubusercontent.com/75149424/176984936-6ec6e61c-8774-452a-827a-c56783ba58ba.png)

https://drive.google.com/drive/folders/1Eg6d6Zoh8gJ6IqjCWx-JE5SWyHQEqzfH?usp=sharing

**Comment by carsten-forty2** [comment]
I'm not sure if the stl dataformat even contains cell information. You can check it with https://github.com/nschloe/meshio and convert the result into a gimli mesh with `pg.meshtools.convert()`. The `pg`  converter for meshio instances might not yet be complete, but I can adapted it very easy on demand if you provide an example. If stl will not work, you can maybe export from comsol into other formats that meshio can read.

I think pg assumes that stl only contain surfaces, which can be used to create cells with `mt.createMesh`. However stl does not contain any marker information and thus no information which region is borehole or not. If you want to use the stl-surface approach, you need to define holes manually with `surfacemesh.createHoleMarker(Position_Inside_the_hole)`

**Comment by geohang** [comment]
Thank you for the quick reply. I have tried, and the pg.meshtools.convert() works! That's very helpful. I am still interested in if no marker information, how can we assign marker information to the borehole.  It seems I didn't find the function surfacemesh.createHoleMarker(Position_Inside_the_hole). Thank you!

**Comment by geohang** [comment]
Hi. It seems I found a way to assign the marker. I am facing another problem that I have assigned the marker and boundary condition in mesh from Comsol in Pygimili but the forward modeling is still not working. Could you help me see what's wrong with it? Thank you! The codes and data are in this link： https://drive.google.com/drive/folders/15XJGisbcx5plwGQQIoz73IhZM92GYCv6?usp=sharing

**Comment by geohang** [comment]
Oh, Sorry for that. I forgot to close this one. I have found the problem and it is from the electrodes' positions. Thank you for your time and effort!
