### ISSUE TITLE
paraDepth uses highest point of topo instead of lowest

### ISSUE THREAD

**Issue by GGDRriedel** [gimli-org/gimli#406]
### Problem description

Using paraDepth results in the depth beig calculated from sensors[0][iz] in polytools.py.

However, this is not always guaranteed to be the lowest point of the sensor list, as they are sorted by sensors[0][0], not by other values. 

Consequently, the line  about bd in polytools.py seems to be out of place, as it compares exactly the same values for a minimum. 
Seens like a bug. 

```python
    n1 = poly.createNode([xMin - paraBound, sensors[0][iz]])
    if balanceDepth:
#THIS ONE
        bD = min(sensors[0][iz] - paraDepth, sensors[0][iz] - paraDepth)
        n2 = poly.createNode([xMin - paraBound, bD])
        n3 = poly.createNode([xMax + paraBound, bD])
```

### Your environment
pg version 1.2.1, still exists in newest version though

For my topography and a paraDepth=50  this resulted in this grid: 

![grafik](https://user-images.githubusercontent.com/48824691/177137568-b5034a9d-463b-42d7-97e8-1482f4ff12a3.png)

It should be 50 below the rightmost depth though, not below the leftmost.

**Comment by halbmy** [comment]
Absolutely!
```
min(sensors[0][iz] - paraDepth, sensors[0][iz] - paraDepth)
```
does not make any sense. Corrected it to (eedf9441)
```
min(sensors[0][iz] - paraDepth, sensors[-1][iz] - paraDepth)
```
