### ISSUE TITLE
Some examples are broken due to API changes

### ISSUE THREAD

**Issue by florian-wagner** [gimli-org/gimli#41]
- http://www.pygimli.org/_examples_auto/modelling/plot_mod-dc-2d.html#sphx-glr-examples-auto-modelling-plot-mod-dc-2d-py
- http://www.pygimli.org/_examples_auto/modelling/plot_mod-gravimetry-2d.html#sphx-glr-examples-auto-modelling-plot-mod-gravimetry-2d-py

Jenkins should complain in these cases. We should use `abort_on_example_error=1` option. http://sphinx-gallery.readthedocs.io/en/latest/advanced_configuration.html#dealing-with-failing-gallery-example-scripts.

**Comment by carsten-forty2** [comment]
On Monday 04 July 2016 23:11:35 Florian Wagner wrote:
> - http://www.pygimli.org/_examples_auto/modelling/plot_mod-dc-2d.html#sphx-glr-examples-auto-modelling-plot-mod-dc-2d-py
> - http://www.pygimli.org/_examples_auto/modelling/plot_mod-gravimetry-2d.html#sphx-glr-examples-auto-modelling-plot-mod-gravimetry-2d-py
> 
> Jenkins should complain in these cases. We should use `abort_on_example_error=1` option. http://sphinx-gallery.readthedocs.io/en/latest/advanced_configuration.html#dealing-with-failing-gallery-example-scripts.
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gimli-org/gimli/issues/41

make pgtest or make checkall should complain first .. maybe there is an issue in the build queue

**Comment by carsten-forty2** [comment]
set abort_on_example_error=1 

make checkall complains now 

Examples fixed.
