### ISSUE TITLE
ERT mesh

### ISSUE THREAD

**Issue by Kaustav546** [gimli-org/gimli#410]
### Problem description

I have come across another problem: even after setting `showMesh=False`. I still have the mesh in my image background. I have attached two images first one is with showMesh=True and the second one with `showMesh= False`, in order to have a better understanding of my question. 

### Your environment

**Operating system**: Linux
**Python version**: 3.8
**pyGIMLi version**: 1.2.1
**Way of installation**: Conda package
![withMesh](https://user-images.githubusercontent.com/78998363/179459582-58882a68-b258-41eb-b176-be33c2d88bcf.png)
![withoutMesh](https://user-images.githubusercontent.com/78998363/179459621-776b019a-4658-4b19-9048-5e36dbedd7b1.png)

**Comment by halbmy** [comment]
pg v1.2.1 is pretty outdated. Can you please check with the newest version v1.2.6 and attach the script that generates your output?

I already modified the code and can test. There will be a new version 1.2.7 soon.

**Comment by Kaustav546** [comment]
Thanks, Prof.Thomas for your reply. I installed pg v1.2.6. But the plot remains the same. Here is my output.
![withMesh](https://user-images.githubusercontent.com/78998363/179826641-e5b1b514-4479-4254-9756-a153ae885cf0.png)
![without_mesh](https://user-images.githubusercontent.com/78998363/179826656-98991fc1-1865-4b02-8e89-d4175286649d.png)

**Comment by halbmy** [comment]
Please attach the script.

**Comment by Kaustav546** [comment]
Sorry! for the late reply. Here is the script.
`
import matplotlib.pyplot as plt
import os
from pygimli.viewer.mpl import generateMatrix
from PIL import Image
from numpy import asarray
import numpy as np
from pygimli.meshtools import quality
import random 
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import ert

side =8.0
world = mt.createWorld(start=[-150, 0], end=[150, -60],
                       worldMarker=True)


xr1 = random.randint(-70, 70)
xl1 = random.randint(-95, -5)
yl1 = random.randint(-40,-7)
yr1 = random.randint(-40,-7)
print(xr1, yr1)

circle_right =mt.createRectangle(pos=[xr1, yr1], size=[side, side],
               marker=0, area=0.1)


geom = world + circle_right

#pg.show(geom)
#the geometry
ax, fig = pg.show(geom)

scheme = ert.createData(elecs=np.linspace(start=-130, stop=130, num=53),
                           schemeName='dd')

for p in scheme.sensors():
    geom.createNode(p)
    geom.createNode(p - [0, 0.1])


mesh = mt.createMesh(geom, quality=33, area=10)

r_high = round(random.uniform(1000.00, 2000.00), 2)
r_low = round(random.uniform(10.00, 50.00), 2)
rhomap = [[0, r_high],
          [1, 500.]]
#figure with mesh
pg.show(mesh, data=rhomap, label=pg.unit('res'), showMesh=True, cMin=10.0, cMax= 2000.0)
#figure without mesh
pg.show(mesh, data=rhomap, label=pg.unit('res'), showMesh=False, cMin=10.0, cMax= 2000.0)

data = ert.simulate(mesh, scheme=scheme, res=rhomap, noiseLevel=1,
                    noiseAbs=1e-6, seed=1337)



data.remove(data['rhoa'] < 0)
data.remove(abs(data["k"])>35000) 
ert.show(data)`
[ERT.txt](https://github.com/gimli-org/gimli/files/9161436/ERT.txt)

**Comment by Kaustav546** [comment]
Sorry! for the late reply. Here is the script.
[ERT.txt](https://github.com/gimli-org/gimli/files/9161447/ERT.txt)

import matplotlib.pyplot as plt
import os
from pygimli.viewer.mpl import generateMatrix
from PIL import Image
from numpy import asarray
import numpy as np
from pygimli.meshtools import quality
import random 
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import ert

side =8.0
world = mt.createWorld(start=[-150, 0], end=[150, -60],
                       worldMarker=True)


xr1 = random.randint(-70, 70)
xl1 = random.randint(-95, -5)
yl1 = random.randint(-40,-7)
yr1 = random.randint(-40,-7)
print(xr1, yr1)

circle_right =mt.createRectangle(pos=[xr1, yr1], size=[side, side],
               marker=0, area=0.1)


geom = world + circle_right

#pg.show(geom)
#the geometry
ax, fig = pg.show(geom)

scheme = ert.createData(elecs=np.linspace(start=-130, stop=130, num=53),
                           schemeName='dd')

for p in scheme.sensors():
    geom.createNode(p)
    geom.createNode(p - [0, 0.1])


mesh = mt.createMesh(geom, quality=33, area=10)

r_high = round(random.uniform(1000.00, 2000.00), 2)
r_low = round(random.uniform(10.00, 50.00), 2)
rhomap = [[0, r_high],
          [1, 500.]]
#figure with mesh
pg.show(mesh, data=rhomap, label=pg.unit('res'), showMesh=True, cMin=10.0, cMax= 2000.0)
#figure without mesh
pg.show(mesh, data=rhomap, label=pg.unit('res'), showMesh=False, cMin=10.0, cMax= 2000.0)

data = ert.simulate(mesh, scheme=scheme, res=rhomap, noiseLevel=1,
                    noiseAbs=1e-6, seed=1337)



data.remove(data['rhoa'] < 0)
data.remove(abs(data["k"])>35000) 
ert.show(data)

**Comment by halbmy** [comment]
The gray edges in the plot are just a matter of the matplotlib backend as a result of antialiasing. If you export the figure to pdf 
```
ax, cb = pg.show(...)
ax.figure.savepdf("bla.pdf")
```
all should be fine (it can even occur depending on your pdf viewer, its anti-aliasing settings and the screen resolution).
![image](https://user-images.githubusercontent.com/7136401/180391225-f9dbabf7-4277-4168-a090-d7006872bc34.png)
(bad pdf viewer with full screen resolution)
![image](https://user-images.githubusercontent.com/7136401/180391365-9b26d54b-e7f3-480d-b1d0-b71be2b59d99.png)
(same viewer with half resolution)
