### ISSUE TITLE
No module named 'pygimli.mplviewer

### ISSUE THREAD

**Issue by Roshak1992** [gimli-org/gimli#414]
Hi. I wanted to run "DC1dSmooth" but an error appeared which was written that "No module named 'pygimli.mplviewer' ". So, I was looking for installing the mentioned package, but the more I sought, the less I found. May anyone help me how to tackle this issue?

**Comment by halbmy** [comment]
`mplviewer` was a subpackage of pyGIMLi that was moved to `viewer.mpl`. Which example or script are you referring to?

**Comment by Roshak1992** [comment]
My OS is Linux. so I went to anacoda3/bin/gimli/gimli directory, ran python after activating pg. I used "DC-EM Joint inversion" example, but when I executed it, I encountered the error, which is defined by the red rectangle in the attached image.

![Pygimlii](https://user-images.githubusercontent.com/109628758/179954686-7063fec3-4c33-4390-9a29-1e6906ce0c49.jpg)

**Comment by halbmy** [comment]
This is terribly outdated. Which version are you using?

**Comment by halbmy** [comment]
which pygimli version

**Comment by halbmy** [comment]
I am closing the issue as it is not relevant for pygimli versions >=1.1. `mplviewer` was moved to `viewer.mpl` before releasing v1.0 more than two years ago. So you just have to change the line into
```
from pygimli.viewer.mpl import drawModel1D
```
as done in https://www.pygimli.org/_tutorials_auto/3_inversion/plot_4-dc1dsmooth.html (nevertheless this example is also outdated from a style point of view).
