### ISSUE TITLE
Your RRMS seems to be RMSRE

### ISSUE THREAD

**Issue by GGDRriedel** [gimli-org/gimli#415]
### Problem description

Trying to look what the RRMS parameter is when I do a TT Tomography Inversion. 

The parameter prints: 
```mgr.inv.rrms()```

I looked for the math behind that function and it is only to be found in 
pygimli/utils/base.py

code: 
```python 
def rms(v, axis=None):
    """Compute the root mean square."""
    ### abs for complex values
    return np.sqrt(np.mean(np.abs(v)**2, axis))


def rrms(a, b, axis=None):
    """Compute the relative (regarding a) root mean square."""
    ### abs for complex values
    return rms(np.abs(a-b)/np.abs(a), axis)
```

So the RRMS function takes A-B and devides by A BEFORE shoving it into RMS. 

According to https://stats.stackexchange.com/questions/260615/what-is-the-difference-between-rrmse-and-rmsre/
![grafik](https://user-images.githubusercontent.com/48824691/181253071-34bb41c3-e95d-411b-b3b0-7986a8703642.png)

This is the RMSRE, not the RRMS. 

Am I missunderstanding something here?

**Comment by halbmy** [comment]
You're right. The pygimli function `rrms` (relative root mean square) is exactly what is referred to as RMSRE in this paper. However, I have never heard about a term RMSR(E) before and I have not seen this definition anywhere.

Often, e.g. in relation to the software res2dinv one uses the term RMS with the definition
![image](https://user-images.githubusercontent.com/7136401/181258819-5d7641fc-6c8a-49f9-a422-07044ed0ab68.png)
which is RMSRE in equation (59). I don't like this inaccuracy as one can only determine from the `%` sign that it is the relative one.

Note that the relative RRMS is de facto the RMS of the logarithmic values, as the difference in logarithms is the logarithm of the ratio and it makes sense for logarithmically distributed properties as (apparent) resistivity. For traveltime, where values approach zero, it does not make any sense and one should use the normal RMS (`rms` function in pygimli) along with a linear data transformation.

**Comment by GGDRriedel** [comment]
I guess this is because people are free to put whatever they want into the RMS so.... they do. 
Linguistically however, relative RMS is not correct, it's the RMS of the relatives..

I agree with your comments and would like to add that we determined for us, that the RMSRE puts a little more weight to errors in smaller value domains which is quite nice for TTtomography as picking quality and so on decreases with longer/larger TT, hence models are prone to not fit well. 

I need this for reporting so we'll probably just write the RMSRE definition for the RRMS pictures coming out of Refrapy/pyGimli but would be nice to find  a position here.

**Comment by halbmy** [comment]
Again, for traveltime, any relative RMS cannot make much sense. Imagine a zero or almost-zero traveltime for quasi-zero offset can never be perfectly fitted and will lead to quasi-infinite RRMS values, which then reports only about this one value. For any comparison, use an absolute value, e.g. in ms.

**Comment by halbmy** [comment]
Another note: actually we are minimizing an error-weighted misfit that we refer to as chi-square value. In many software this is reported as RMS. RMS is just a root-mean-square, it is up to you how you normalize it unless you say how.
