### ISSUE TITLE
doesn't this supposed to be half distance bewteen m and n?

### ISSUE THREAD

**Issue by Khalilsqu** [gimli-org/gimli#417]
https://github.com/gimli-org/gimli/blob/a854ca46c46563e46674e8a2c72e062fbe54ac11/pygimli/physics/ert/ves.py#L33

**Comment by GGDRriedel** [comment]
It is. See line 118. 
But the documentation is wrong indeed.

**Comment by halbmy** [comment]
Yes it does. A typical copy&paste mistake corrected by [f053471](https://github.com/gimli-org/gimli/commit/f053471e9d01068839880324bbd20c599a463e29). Thanks for reporting.
