### ISSUE TITLE
Extract surface mesh from 3D mesh

### ISSUE THREAD

**Issue by davidkusnirak** [gimli-org/gimli#418]
### Problem description

Hi!

I'm trying to extract the surface mesh from a 3D mesh, which is having just a single Marker values in all cells. 

My idea was to extract all faces, which do not have a neighboring cell, however, I got the same value (4) for all cells. Could you advise me some straightforward solution, extracting surface mesh from a 3D mesh?

### Your environment

**Operating system**: Windows
**Python version**: 3.8
**pyGIMLi version**: 1.2.6
**Way of installation**: Conda package

from pygimli import meshtools as mt
import pygimli as pg

```
plc = mt.createCylinder(radius=5, height=10, nSegments = 16, pos=[100, 100, 100], boundaryMarker=10, area=1)

# pg.show(plc)

mesh = mt.createMesh(plc, area = 1)

# pg.show(mesh)

a = []

for cid in mesh.cells():
    a.append(cid.neighborCellCount())

print(min(a), max(a))
```

**Comment by carsten-forty2** [comment]
Hi, 

We differentiate between cells and boundaries. For 3D .. cells fills the volume and boundary faces separete the cells. Every 'inside' boundary have two neighbours (left/right) where outside boundaries only have a right cell.

You can identifiy them by there neighbours or with the `outside()` shortcut:

```
for b in mesh.boundaries():
    if b.outside():
        print(b)
        print('right:', b.leftCell())
        print('left:', b.rightCell())
```

For visualisation you can create a new boundary mesh from it:

```
bMesh = mesh.createSubMesh(mesh.boundaries([b.id() for b in mesh.boundaries() if b.outside()]))
pg.show(bMesh, showMesh=True)
```

Boundaries are not necessarly given by imported meshs, if they are missing you can create them with
```
mesh.createNeighbourInfos()
```

**Comment by davidkusnirak** [comment]
Hi Carsten,

thanks a lot, this is very much solving my issue!

However, I hit another minor issue while using your code at this line: 

`pg.show(bMesh, showMesh=True)`

getting the following error:

line 37, in <module>
    pg.show(bMesh, showMesh=True)
  File "C:\Software\Anaconda3\envs\gimli_1.2\lib\site-packages\pygimli\viewer\showmesh.py", line 140, in show
    return showMesh3D(mesh, data, **kwargs)
  File "C:\Software\Anaconda3\envs\gimli_1.2\lib\site-packages\pygimli\viewer\vistaview.py", line 48, in showMesh3D
    return globals()[view3Dcallback](mesh, data, **kwargs)
  File "C:\Software\Anaconda3\envs\gimli_1.2\lib\site-packages\pygimli\viewer\vistaview.py", line 131, in showMesh3DVista
    plotter.show()
UnboundLocalError: local variable 'plotter' referenced before assignment

The pg.show works fine for me on 3D objects, unless I don't use any the _showMesh=True_ parameter. I tried to troubleshoot a bit with a new installation (on Windows, using new conda env.) and also by passing _gui=True_, but no success.

**Comment by carsten-forty2** [comment]
ah yes .. sorry .. the `showMesh` argument is from local dev branch and will come in 1.2.7 where we try to keep `pg.show` a little bit more compatible for 2d and 3d meshes.
