### ISSUE TITLE
reading mesh file from new gmsh versions

### ISSUE THREAD

**Issue by elgips** [gimli-org/gimli#419]
### Problem description

Hello, I'm interested in importing a mesh file (*.msh)  from gmsh (version 4.10.5).
The *.msh file is not in the `MSH ASCII file version 2 format, as required in pygimli mesh.py file, so the readgmsh(filename) function is unsuccessful in importing the mesh.

### Your environment

**Operating system**: Windows
**Python version**: 3.8.12
**pyGIMLi version**: 1.2.4
**Way of installation**: Conda package

### Steps to reproduce

```
    import pygimli as pg
    pg.meshtools.readGmsh('GFG.msh')
```
### Expected behavior

Import a gmsh 4.10.5 mesh file to pygimli mesh.

### Actual behavior

Tell us what happens instead and/or provide the output of your script.

```

  File ~\anaconda3\envs\pg\lib\site-packages\pygimli\meshtools\mesh.py:757 in readGmsh
    nodes[nCount, :] = node_coordinates

UnboundLocalError: local variable 'nodes' referenced before assignment
l

```

**Comment by florian-wagner** [comment]
Hi @elgips,

as written in the documentation of the `readGmsh` function, it is not yet compatible with the newer file formats. You have 3 options:

1. Save your Gmsh mesh in this version (http://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format-version-2-_0028Legacy_0029). You can specify this in the export dialog.
2. Use `meshio` to read your current mesh (with the newer Gmsh format): https://github.com/nschloe/meshio/issues and then use our `readMeshIO` function to load it from there: https://www.pygimli.org/pygimliapi/_generated/pygimli.meshtools.html?highlight=meshio#pygimli.meshtools.readMeshIO
3. Adapt the `readGmsh` function to support the newer (and the older!) format. We are happy to welcome pull requests as outlined here: https://www.pygimli.org/contrib.html#d-contribute-to-code

Let us know, which option you chose and how it worked out.

Best wishes
Florian

**Comment by elgips** [comment]
Hello @florian-wagner ,
Thank you very much (I'm would have been glad to help with updating the code, but I'm rather a primitive user)
I'll try the other options and inform you what worked.
Best regards, 
El'ad

**Comment by florian-wagner** [comment]
Any luck?
