### ISSUE TITLE
Strange aspect of pyGIMLi logo

### ISSUE THREAD

**Issue by halbmy** [gimli-org/gimli#42]
![pygimli-org](https://cloud.githubusercontent.com/assets/7136401/17132076/7a84521c-5320-11e6-8453-9e9b7b93a7f1.png)
I happened to look at the website with Internet Explorer (11) and saw the logo is strangely stretched vertically. Maybe the pdf (in doc/_static) can be created otherwise or pdf might not be a good idea for websites anyway.

**Comment by florian-wagner** [comment]
I will look into this. The pdf is for the downloadable documentation only (created with pdftex). The website uses a svg format, which is widely web compatible nowadays (http://caniuse.com/#feat=svg).

**Comment by halbmy** [comment]
still not working on my computer, but maybe this is not a problem as IE is dying and on Windows Edge it should look good (can check it tomorrow).

**Comment by florian-wagner** [comment]
CI Server was not running for a while, pygimli.org is up-to-date since 00:30 today. Did you try today or yesterday? Checking with www.browserling.com and MS dev tools, everything looks fine https://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots/#http://www.pygimli.org

**Comment by halbmy** [comment]
Of course I tried only when I saw that it was updated (on August 3) as I have my update checker set on this site.

**Comment by florian-wagner** [comment]
I see, I could reproduce it also with IE 9.

**Comment by halbmy** [comment]
all well, at least in IE 11.

**Comment by florian-wagner** [comment]
With IE10 and IE9 everything looks fine as well. IE8 and smaller cannot display SVGs, so there's no logo at all (and no status icons).

## IE10
![ie10](https://cloud.githubusercontent.com/assets/2799008/17403784/8126d5dc-5a59-11e6-86c9-9857679166c4.png)

## IE9
![ie9](https://cloud.githubusercontent.com/assets/2799008/17403785/81276e8e-5a59-11e6-86b6-5fd5207ad4e7.png)

## IE8
![ie8](https://cloud.githubusercontent.com/assets/2799008/17403783/8126081e-5a59-11e6-9be8-cee2a81069fa.png)
