### ISSUE TITLE
.2dm Invalid Data removal and error estimation 

### ISSUE THREAD

**Issue by jmcknight24** [gimli-org/gimli#420]
### Problem description

Loading a .2dm file while using TDIP. I keep getting notified of some invalid data. There is a way to remove these in ERTmanager, but there does not seem to be where I can remove these in TDIP. I also am getting an error when I try to invert .2dm files. My error is..."All error values need to be larger then 0. Either give and err argument or fill data Container  with a valid 'err'

### Your environment

**Operating system**: Windows
**Python version**:  3.8.13
**pyGIMLi version**: 1.2.6
**Way of installation**:  Conda package

### Steps to reproduce

[L2_dd_N.zip](https://github.com/gimli-org/gimli/files/9292437/L2_dd_N.zip)

#code is from previous example from developer. Found from another closed issue. Cite is link below...
#https://gitlab.com/resistivity-net/bert/-/issues/201

```
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import pygimli as pg
import pygimli.meshtools as mt
import pybert as pb


#%%
tdip = pb.TDIPdata(r"")
tdip.fitDecays()
# %% have a look at some decays for an example AB dipole
tdip.showDecay(ab=[5, 6], showFit=True)
tdip.basename += "_corr"
# %% throw away first gate as it seems not to be good (input filter?)
tdip.filter(tmin=0.03)
tdip.fitDecays()
# %% get rid of too low app. res outliers
print("Apparent resistivity")
tdip.filter(rmin=30, rmax=300)
tdip.showData()
# %% get rid of data with very high errors
print("Measured error")
tdip.filter(emax=10)
tdip.showData("err")
# %% get rig of strange decays (negative or implausible time constants)
print("Apparent time constant")
tdip.filter(taumin=0.1, taumax=10)
tdip.showData("tau")
# %% throw away data that cannot be fitted by a Debye roughly
print("Fit")
tdip.filter(fitmax=0.5)
tdip.showData("fit", logScale=False)
# %% remove negative or implausible initial (fitted) app. chargeabilities
print("Initial chargeability")
tdip.filter(m0min=0.1, m0max=1000)
tdip.showData("m0", logScale=False)
# %% check data again
if 0:
    tdip.showDecay(ab=[5, 6], showFit=True, invalid=True)
    tdip.generateDataPDF()
    tdip.generateDecayPDF(ylim=[1, 100], showFit=True)
# %% resistivity inversion
tdip.invertRhoa(paraDX=1)
tdip.showResistivity()
# %% chargeability inversion
tdip.invertMa()
tdip.showChargeability()
```

### Expected behavior

I want to invert my data to visualize the chargeability with a .2dm file.

### Actual behavior

When I load the data, the data loads without error but the data validity check states: "Data validity check: found 64 invalid data."
I am not sure how to remove these invalid data with TDIP as I cannot find any. Is there a way in TDIP to remove these values? Also, I am getting the error stated in the problem description. I cannot subscript the data as in ERT (ie. data['err'] = ert.estimateError()).
I have seen people use .2dm before with TDIP inversion, but why am I getting these errors?

```
09/08/22 - 10:41:03 - pyGIMLi - INFO - Found 2 regions.
09/08/22 - 10:41:03 - pyGIMLi - INFO - Region with smallest marker (1) set to background
09/08/22 - 10:41:03 - pyGIMLi - CRITICAL - <class 'pygimli.physics.ert.ertManager.ERTManager'>._ensureError(C:\Users\jgmck\Documents\miniconda\envs\pg\lib\site-packages\pygimli\frameworks\methodManager.py:365)
All error values need to be larger then 0. Either give and err argument or fill dataContainer  with a valid 'err'  0.0 0.098
Traceback (most recent call last):

  File "C:\Users\jgmck\Documents\miniconda\envs\pg\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\jgmck\onedrive - university of oklahoma\documents\pygimli_tdip_trial.py", line 51, in <module>
    tdip.invertRhoa(paraDX=1)

  File "C:\Users\jgmck\Documents\miniconda\envs\pg\lib\site-packages\pybert\tdip\tdipdata.py", line 696, in invertRhoa
    self.res = self.ERT.invert(data=self.data, **kwargs)

  File "C:\Users\jgmck\Documents\miniconda\envs\pg\lib\site-packages\pygimli\frameworks\methodManager.py", line 736, in invert
    errorVals = self._ensureError(self.fop.data, dataVals)

  File "C:\Users\jgmck\Documents\miniconda\envs\pg\lib\site-packages\pygimli\frameworks\methodManager.py", line 365, in _ensureError
    pg.critical("All error values need to be larger then 0. Either"

  File "C:\Users\jgmck\Documents\miniconda\envs\pg\lib\site-packages\pygimli\core\logger.py", line 301, in critical
    raise Exception(_msg(*args))

Exception: All error values need to be larger then 0. Either give and err argument or fill dataContainer  with a valid 'err'  0.0 0.098
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".
[L2_dd_N.zip](https://github.com/gimli-org/gimli/files/9292622/L2_dd_N.zip)

**Comment by halbmy** [comment]
As the TDIP class is not part of pyGIMLi, but BERT, can you please post this issue on the BERT gitlab page: https://gitlab.com/resistivity-net/bert

**Comment by jmcknight24** [comment]
Thank you. It has been one of those mornings...

**Comment by halbmy** [comment]
Closing as it belongs to BERT where a new issue was created:

https://gitlab.com/resistivity-net/bert/-/issues/276
