### ISSUE TITLE
How to edit forward operator to perform coupled inversion?

### ISSUE THREAD

**Issue by geoale90** [gimli-org/gimli#422]
### Problem description

Hello, 

I would like to obtain a 2-D distribution of water content using DC electrical data. That is, I would like to perform the coupled inversion of the electrical data where Archie's law, used to translate water content into electrical conductivity, is used WITHIN the forward operator. 

At the moment I have a very basic code, included below, that allows me to perform inversion of the DC electrical data:

```python
import pygimli as pg
from pygimli.physics import ert
import pybert as pb
import matplotlib.pyplot as plt
import numpy as np
import pygimli.meshtools as mt


## Create measurement scheme

## Create grid where both the input fields and the inversion is performed
Lx = 200
Ly = 20
nx_input_field = 400+1
ny_input_field = 40+1
nz_input_field = 200

# Create inversion domain  
inversionDomain1 = pg.createGrid(x=np.linspace(-Lx/2,Lx/2,nx_inversion),y=np.linspace(0,-Ly,ny_inversion), marker = 3 )

inversionDomain2 = pg.meshtools.appendTriangleBoundary(inversionDomain1, marker=1,
                                         xbound=1, ybound=1)    

# Create measurement scheme
scheme = ert.createData(elecs=np.linspace(start=-Lx/2 , stop=Lx/2 , num=51),
                           schemeName='dd')

# Initialize ERT manager
mgr = ert.ERTManager(scheme)

# Perform the inversion of the DC data

model = mgr.invert(data_simulated, mesh=inversionDomain2, lam=10, verbose=True)

```

### Expected behavior

I need to edit the forward operator by including a petrophysical transformation in order to invert directly for water content. I know the existence of modules such as ```createForwardOperator``` or the class ```PetroInversionManager``` included within the codes. However, I  don't understand how to use them and I haven't found so far any source of information (repository or official documentation) treating treating these modules.
Could you please indicate me some minimal steps to include a petrophysical transformation within a forward operator? Or, more generally, how to create my own forward operator? Or at least some documentation where I can learn it by myself? 

Thank you very much in advance.
Cheers,

**Comment by halbmy** [comment]
Sorry for not responding in time due to vacations.

As you closed the issue I can assume you find the petrophysical examples? I confess that since the pyGIMLi paper (where this was discussed) with v1.0 a lot of things have changed and there could be more examples. So any feedback is welcome.

**Comment by geoale90** [comment]
Hello,

Thanks for the reply. Indeed, I finally found an example here https://github.com/gimli-org/transform2021/blob/main/6_Inversion_with_any_forward_operator.ipynb that helped me to build my own forward operator. In order to make the code run I had to make some small syntax changes due to the different pygimli versions (my own v1.2.3 and the one from the example v1.0 I guess?).

**Comment by halbmy** [comment]
The example from the Transform 2021 conference is based on pyGIMLi v1.2.1 as the environment.yml says, but it should also work with newer versions. Which changes did you have to make? Note also that there is a new version 1.3.0

**Comment by geoale90** [comment]
Hello, 

I realize that in fact I had to make many changes not to the example I indicated above, which worked smoothly, but to this example that includes flow and transport modelling (https://github.com/gimli-org/gimli/blob/371a803ffa313fdcbe946da480a059439bdfa250/doc/paper/cg17/example-2.py).

Thanks for indicating the new version, I'll try to update this week.

Now that I have my little forward operator running, I am performing a numerical experiment where I want to see how is the relationship between input and ERT-inferred salinity fields as a function of the geostatistical properties of the input fields. Since I want to focus on the impact of the petrophysical uncertainty on such a relationship and nothing else, I would want to deal with as few errors as possible coming from the inversion. That is, I would like to have the "best" inversion possible without having to rely on MCMC-based inversion (not feasible for my experimental setup because I need relatively fast inversions). So I was thinking on equipping the '''pg.Inversion()''' with some global optimization scheme. However, I wonder if this is something that you have already implemented?

Thanks in advance

**Comment by halbmy** [comment]
You're right, the example 2 codes were really outdated from a syntax point of view (uB not existing anymore in favour of a different style of boundary conditions) and also not matching the paper. I first updated the synthetic modelling code (https://github.com/gimli-org/gimli/blob/dev/doc/paper/cg17/example-2_modelling.py) so that the paper figures are reproduced.

**Comment by geoale90** [comment]
Yes, just minor things, for instance, in 
line 117:  rhoa = ert.simulate(meshERT, resis, ertScheme, verbose=0, returnArray=True)

the arguments "resis" and "ertScheme" are input in a switched order, or between lines 369 and 375 some of the attributes of "inv = pg.Inversion()" have slightly different names in the new version I think and that's why are not found when trying to run.

**Comment by halbmy** [comment]
Thank you for pointing this out. I've made the most important changes to comply with the new API. We should break down this example to a minimalistic one that is included in the example collection and therefore automatically tested.
