### ISSUE TITLE
createParaMeshPLC3D problem

### ISSUE THREAD

**Issue by EungsangLee** [gimli-org/gimli#423]
### Problem description

Hi, I'm a student studying geophysics with ERT. I'm using the BERT for inversion, and I'm studying with the help of Thomas Günther @halbmy.
I'm trying to use pygimli because the Günther suggested a solution to my problem, but the createParaMeshPLC3D command doesn't work. I checked both mac and linux environments, and the same symptoms appeared. The installation was followed by pygimli installation guide, and since it was imported, the version check and other commands can be worked well.

### Your environment

**Operating system**:  Mac, Linux
**Python version**: 3.10.5(Mac), 3.8.13(Linux)
**pyGIMLi version**: 1.2.6
**Way of installation**: Conda package

### Steps to reproduce

```python
import pygimli as pg
from pygimli.physics import ert
import pygimli.meshtools as mt

# load data, generate geometric factor and estimate error
data = pg.getExampleData("ert/gallery3d.dat")
data["k"] = ert.createGeometricFactors(data)
data["err"] = ert.estimateError(data, relativeError=0.02)
print(data)
# create mesh
plc = mt.createParaMeshPLC3D(data, paraDX=.5, surfaceMeshQuality=34.4,paraMaxCellSize=10)
...
```

### Expected behavior

I don't know in detail how the results come out. It is certainly a script that runs properly.

### Actual behavior

```
Traceback (most recent call last):
  File "new3d.py", line 11, in <module>
    plc = mt.createParaMeshPLC3D(data, paraDX=.5, surfaceMeshQuality=34.4,paraMaxCellSize=10)
AttributeError: module 'pygimli.meshtools' has no attribute 'createParaMeshPLC3D'
```

**Comment by halbmy** [comment]
yes, the function is new and not yet in version 1.2.6

You will have to wait for the upcoming v1.3.0 or check out the current development branch by git

**Comment by EungsangLee** [comment]
Nice to see you here, Günther!

Thanks for reply again :D

**Comment by EungsangLee** [comment]
Dear, Günther.

I installed a new version(1.3.0) and ran the solution you suggested, but I'm asking because there are some problems.

1. May I know which of the few parameters or codes in your solution is the most important part? If I use my data, not the example data, the mesh is formed too tightly, so it takes a long time or it doesn't proceed. If the quality of the mesh is lowered, the mesh is formed well. I think the newly created command, createParaMeshPLC3D, is the most important point, so I think it is okay to adjust other parameters(paraDX, surfaceMeshQuality, paraMaxCellSize, ...), is this right?

2. After adjusting the size of the mesh, I tried to calculate it, but the error as below occurred. Is this also an error that occurs because the calculation is too big?
`
Data: Sensors: 444 data: 3450, nonzero entries: ['a', 'b', 'c', 'err', 'k', 'm', 'n', 'r', 'rhoa', 'u', 'valid']
Opening /tmp/tmpze4el0qe.poly.
  Segments are connected properly.
Mesh: Nodes: 78608 Cells: 459521 Boundaries: 926811
29/08/22 - 02:59:27 - pyGIMLi - INFO - Found 2 regions.
29/08/22 - 02:59:27 - pyGIMLi - INFO - Region with smallest marker (1) set to background
29/08/22 - 02:59:30 - pyGIMLi - INFO - Creating forward mesh from region infos.
29/08/22 - 03:00:17 - pyGIMLi - INFO - Creating refined mesh (H2) to solve forward task.
min/max(dweight) = 0.0338761/33.3277
29/08/22 - 03:02:23 - pyGIMLi - INFO - Use median(data values)=83.6160923905405
29/08/22 - 03:02:23 - pyGIMLi - INFO - Created startmodel from forward operator: 397929 [83.6160923905405,...,83.6160923905405]
29/08/22 - 03:02:23 - pyGIMLi - INFO - Starting inversion.
fop: <pygimli.physics.ert.ertModelling.ERTModelling object at 0x2ac4011e1400>
Data transformation: <pgcore._pygimli_.RTransLogLU object at 0x2ac40108c950>
Model transformation: <pgcore._pygimli_.RTransLog object at 0x2ac4002c4ef0>
min/max (data): 0.02/6409
min/max (error): 3%/2952%
min/max (start model): 83.62/83.62
--------------------------------------------------------------------------------
Calculating response for model: min = 83.6161 max = 83.6161
Allocating memory for primary potential...... 1.932

No primary potential for secondary field calculation with topography.
Creating P2-Primmesh:           Nodes: 4956253  Cells: 3676168  Boundaries: 7383412
ModellingBase::setMesh() copying new mesh ... Found topography for surface=11.2287 : 11.2071
Found datafile: 444 electrodes
Found: 444 free-electrodes
Found non-Neumann domain
124.604 s
FOP updating mesh dependencies ... 0 s
CHOLMOD error: problem too large. file: ../Supernodal/cholmod_super_symbolic.c line: 683
CHOLMOD error: argument missing. file: ../Cholesky/cholmod_factorize.c line: 121
 0 (528.511s)CHOLMOD error: argument missing. file: ../Cholesky/cholmod_solve.c line: 1062
`

3. When calculating, can I make a mesh using a new solution and use the created mesh to calculate at BERT?

**Comment by halbmy** [comment]
1. Yes, you're right in that the mesh generation, prepared by `createParaMeshPLC3D`, is the crucial part. So you need to find the optimum parameters which are always dependent on your layout.
2. A mesh containing 5 million nodes is definitely too fine to be solved directly (and it would take forever), so you need to improve your mesh (see 1.) or avoid quadratic shape functions if it is already fine enough for a total potential calculation.
3. I don't quite understand but of course you can pass any mesh to the inversion.

**Comment by EungsangLee** [comment]
What I want to say is, can I use the mesh made by pygimli to do inversion instead of BERT's mesh? It is because BERT is more familiar than pygimli to adjust the parameters of the inversion. Or, can I adjust the parameters similar to BERT(L1 or L2, error cutoff, etc)?

**Comment by halbmy** [comment]
you can use any mesh. Basically it is all the same, the parameters for `createParaMeshPLC3D` are exactly the same as in the BERT cfg file. This also holds for the inversion and its parameters.

**Comment by EungsangLee** [comment]
Thank your for reply.

The inversion was successful by reducing the number of cells. I have a question, the mesh is formed much deeper than the previous inversion, so is it `setRegularization(correlationLengths=[10, 4, 2])` to control it? Can you give me a brief description of the command?

**Comment by halbmy** [comment]
You can control the depth of the mesh by yourself. Of course, if you have a deeper mesh the deepest parts will be less resolved and rather controlled by the regularization. The geostatistic constraints are just an alternative to the usual smoothness constraints. See the paper of Jordi et al. (2018) for details: http://dx.doi.org/10.1093/gji/ggy055
