### ISSUE TITLE
ModuleNotFoundError: No module named 'pygimli'

### ISSUE THREAD

**Issue by Khalilsqu** [gimli-org/gimli#425]
### Problem description

Please describe your issue here.

### Your environment

**Operating system**: e.g. Windows, Linux or Mac?
**Python version**: e.g. 2.7,3.5,3.6?
**pyGIMLi version**: Output of `print(pg.__version__)`
**Way of installation**: e.g. Conda package, Win binary, curl script, manual compilation from source

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
import pygimli as pg
...
```

### Expected behavior

Tell us what should happen or what you want to achieve.

### Actual behavior

Tell us what happens instead and/or provide the output of your script.

![image](https://user-images.githubusercontent.com/22060413/187126210-397860a8-ad78-4bb1-bf2b-9cfb4cc6f028.png)

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
Does closing the issue mean the problem was already solved? If so, how, (just a cach issue?) and if not, which platform did you use?

**Comment by Khalilsqu** [comment]
Thanks for the follow-up.

Yes. I managed to import pygimili in vscode jupyter notebook extension.

Thanks a lot.
