### ISSUE TITLE
Refraction inversion

### ISSUE THREAD

**Issue by Khalilsqu** [gimli-org/gimli#426]
This is a question rather than an issue,

First of all, thanks for this amazing module.

I would like to ask about the refraction method. Does it only support tomographic inversion? Can data be inverted into a layered velocity model where each layer has somehow a constant velocity and a unique thickness? 

Cheers,

Khalil

**Comment by halbmy** [comment]
The `TravelTimeManager` class is for tomographic inversion of first-arrival traveltime. One could of course implement a structure-based inversion with varying layer thickness and velocity variation along the profile on pilot points. This is subject of ongoing research and will be available here.

For simple 1D layered subsurface, there is a class `RefractionNLayer` that can be used like other 1D methods.

**Comment by Khalilsqu** [comment]
Thanks, 

If you font mind I have another up question.


I want to have sensors' positions as real coordinates of UTM (x, y, z).

data.sensorPositions()

each element is an `RVector3`. which of one is x, y, and z in this vector

this is what I get when having varying x, and y coordinates and z is always zero. RVector3(x, y, z)

![image](https://user-images.githubusercontent.com/22060413/187622042-c5b447f0-d9a8-40b3-96da-6120565e8eec.png)

**Comment by halbmy** [comment]
Seems like you have a profile in 3D space. For a 2D inversion, you need to reduce the x and y values to a profile length:
```
sx, sy = pg.x(data), pg.y(data)
st = np.hstack((0., np.cumsum(np.sqrt(np.diff(sx)**2+np.diff(sy)**2))))  # tape measure
for i in range(data.sensorCount()):
    data.setSensorPosition(i, [st, 0, 0])
```
before you can go into inversion.

**Comment by GGDRriedel** [comment]
There is a graphical GUI for ivnersion called Refrapy that does layered inversion. You can use the public one or my fork which added some quality of life functions

**Comment by Khalilsqu** [comment]
Apologies for bothering you.

is there a simple way to have a limit for min and max distance values? for example, I want to limit the inversion within the x range from -0 to 115 meters only. These are the locations of the first and last geophones!

![image](https://user-images.githubusercontent.com/22060413/188413584-058f9c62-f9be-4c31-9c4e-cae8b114ca40.png)

**Comment by halbmy** [comment]
All shots and geophones need to be in the mesh but there is no need for a boundary outside of their spread. You can either pass `paraBoundary=0` or adjust the (matplotlib) axes of the tomogram:
```
ax, cb = mgr.showResult()
ax.set_xlim(-10, 125)
```

**Comment by Khalilsqu** [comment]
Thanks a ton. `paraBoundary=0` worked well.

**Comment by halbmy** [comment]
I keep checking this but I see no reason why this shouldn't be the default.
