### ISSUE TITLE
Using mt.createGrid, marker=0, how to attach a velocity value to each grid;

### ISSUE THREAD

**Issue by 728236958** [gimli-org/gimli#429]
#example
```
import pygimli as pg
import pygimli.meshtools as mt
import math
import matplotlib.pyplot as plt
import numpy as np
from pygimli.physics import TravelTimeManager
from pygimli.physics.traveltime import createGradientModel2D
import pygimli.physics.traveltime as tt
#generate 20X20 grid
c = mt.createGrid(x=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20], y=[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-17,-18,-19,-20])
_= pg.show(c, markers=True, showMesh=True)
print(c)

numberGeophones = 21
sensors = np.linspace(0, 20, numberGeophones)
scheme = pg.physics.traveltime.createRAData(sensors)
pos = np.array(scheme.sensors())
slope = 0
for x in pos[:,0]:
    i = np.where(pos[:,0] == x)
    new_y = x*slope
    pos[i, 1] = new_y
scheme.setSensors(pos)
# How to attach this vp vector to each grid. 
vp=[2000,2000,2000,2000,2000,2000,2000,2000,2000,2100,2100,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2200,2200,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2300,2300,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2400,2400,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2400,2400,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2300,2500,2500,2500,2500,2300,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2300,4000,4000,4000,4000,2300,2200,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2300,2000,2000,4000,4000,2000,2300,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2300,2000,2000,2000,2000,2000,2300,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2100,2200,2000,2000,2000,2000,2000,2200,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2200,2000,2000,2100,2200,2200,2200,2200,2200,2100,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2200,2000,2000,2200,4000,4000,4000,4000,4000,2200,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2200,2000,2000,2100,2000,4000,4000,4000,2000,2200,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2100,2000,2100,2000,2000,4000,2000,2000,2100,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2100,2000,2000,2000,2000,2000,2100,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2100,2000,2100,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2100,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2100,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000]
vp = np.asarray(vp)
mgr = TravelTimeManager()
ax, _ = pg.show(c, vp, colorBar=True, logScale=False, label='v in m/s')
pg.viewer.mpl.drawSensors(ax, scheme.sensors(), diam=1.0,
                         facecolor='white', edgecolor='black')
# Perform forward modeling to obtain data. And how to set the noiselevel and noiseAbs value?
data = mgr.simulate(slowness=1.0 / vp, scheme=scheme,mesh=c,
                    noiseLevel=0, noiseAbs=0, seed=1337,
                    verbose=True)
mgr.showData(data)
print(data)
```

**Comment by 728236958** [comment]
#We refer to the example process, use mt.createPolygon to generate 20*20 squares, then mesh, and finally assign values to each polygon. When performing forward simulation, how to give noiseLevel and noiseAbs, which leads to frequent error reports during subsequent inversion, like RuntimeError or Assertion.

import pygimli as pg
import pygimli.meshtools as mt
import math
import matplotlib.pyplot as plt
import numpy as np
from pygimli.physics import TravelTimeManager
from pygimli.physics.traveltime import createGradientModel2D
import pygimli.physics.traveltime as tt
# createpolygon 20*20
z=1
c="c"
geom=mt.createPolygon([[0.0, 0.0], [0.0, -1.0], [1.0, -1.0], [1.0, 0.0]],isClosed=True, marker=1, area=0.1)

for j in range(1,20):
    a=mt.createPolygon([[j, 0], [j, -1], [j+1.0,-1], [j+1.0, 0]],isClosed=True, marker=j+1, area=0.1)
    geom = geom+a 

z=21
for i in range(1,20):
    for j in range(0,20):
        a=mt.createPolygon([[j,0-i], [j, -1-i], [j+1.0, -1-i], [j+1.0, 0-i]],isClosed=True, marker=z, area=0.1)
        z=z+1
        geom = geom+a 
_ = pg.show(geom, markers=True, showMesh=True)

# Mesh
from pygimli.viewer import showMesh
mesh = mt.createMesh(geom, 
                     area=5.0,
                     quality=33,
                     smooth=[2, 4] # [0:no smoothing or 1:node center or 2:weighted node center, # of iter]
                    )
print(mesh)
showMesh(mesh, markers=True, showMesh=True); 

# Assign vp value to each grid.
numberGeophones = 21
sensors = np.linspace(0, 20, numberGeophones)
scheme = pg.physics.traveltime.createRAData(sensors)
pos = np.array(scheme.sensors())
slope = 0
for x in pos[:,0]:
    i = np.where(pos[:,0] == x)
    new_y = x*slope
    pos[i, 1] = new_y
scheme.setSensors(pos)
mgr = TravelTimeManager()
vp = np.array(mesh.cellMarkers())
V=[2000,2000,2000,2000,2000,2000,2000,2000,2000,2100,2100,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2200,2200,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2300,2300,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2400,2400,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2400,2400,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2300,2500,2500,2500,2500,2300,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2300,4000,4000,4000,4000,2300,2200,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2300,2000,2000,4000,4000,2000,2300,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2300,2000,2000,2000,2000,2000,2300,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2100,2200,2000,2000,2000,2000,2000,2200,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2200,2000,2000,2100,2200,2200,2200,2200,2200,2100,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2200,2000,2000,2200,4000,4000,4000,4000,4000,2200,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2200,2000,2000,2100,2000,4000,4000,4000,2000,2200,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2100,2000,2100,2000,2000,4000,2000,2000,2100,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2100,2000,2000,2000,2000,2000,2100,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2100,2000,2100,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2100,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2100,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000]
for a in range(1,401):
    vp[vp == a] = V[a-1]
ax, _ = pg.show(mesh, vp, colorBar=True, logScale=False, label='v in m/s')
pg.viewer.mpl.drawSensors(ax, scheme.sensors(), diam=1.0,
                         facecolor='white', edgecolor='black')
# Perform forward modeling to obtain data.
data = mgr.simulate(slowness=1.0 / vp, scheme=scheme, mesh=mesh,
                    noiseLevel=0.0001, noiseAbs=0.000005, seed=1337,
                    verbose=True)
mgr.showData(data)
print(data)
# Runtime error occurs during inversion
vest = mgr.invert(data, secNodes=2, paraMaxCellSize=5.0,
                  maxIter=10, verbose=True)
np.testing.assert_array_less(mgr.inv.inv.chi2(), 1.1)

**Comment by halbmy** [comment]
The mesh generation with `mt.createGrid` and the forward simulation works as expected. 
![image](https://user-images.githubusercontent.com/7136401/188608727-7ce5ac40-95d4-439a-8f0e-a04103bf3924.png)
![image](https://user-images.githubusercontent.com/7136401/188608744-288dfe7c-65cd-4e80-b433-defdea54e4b8.png)


However, with a 20m long seismic line you will not be able to resolve structures beyond 6-7m depth. You already see in the apparent velocity plot that the contrast is very weak. If you're adding just a little noise all information is gone and therefore the inversion result is crab. So either create a longer profile or consider using a crosshole survey design (see other examples).
