### ISSUE TITLE
pg.test() writes files in current working directory

### ISSUE THREAD

**Issue by florian-wagner** [gimli-org/gimli#43]
Calling `pg.test()` writes a file named `jacobian.way` into the current directory (originating from src/ttdijkstramodelling.cpp line 359). This should be removed after testing or preferably not clutter the current working directory by making use of temporary files like this test: https://github.com/gimli-org/gimli/blob/master/python/pygimli/meshtools/mesh.py#L197

**Comment by halbmy** [comment]
of course, there is no need to keep this debugging anymore by default (I guess it goes back to the times when some joint inversion was still done in Matlab)
