### ISSUE TITLE
Forward modeling of complex irregularity

### ISSUE THREAD

**Issue by Finn1997** [gimli-org/gimli#431]
Hello,
《A geoelectrical pre-study of Älvkarleby test embankment dam: 3D forward modelling and effects of structural constraints on the 3D inversion model of zoned embankment dams》
Pygimli is used in this article.
<img width="770" alt="image" src="https://user-images.githubusercontent.com/99867753/189266022-c75d5408-cfc6-4ac0-91cf-edaa0df8203a.png">
Similar to this irregular model, given different resistivity distributions.
For now, using Pygimli, I will only create simple cubes such as mt. CreateCube (size=, pos=,marker=...)
How should I realize the irregular 3D model? Looking forward to your reply! Thank you!

**Comment by halbmy** [comment]
I don't understand your question. Do you want to know how the model in the paper was generated? I will create an example for this.

**Comment by ChangJingRun1997** [comment]
Yes, thank you！

**Comment by ChangJingRun1997** [comment]
How do you get these two cubes to be next to each other？
`
geo=mt.createWorld(start=[0, 0,0], end=[65,20,-40],worldMarker=True,marker=1)
cube1=mt.createCube(size=[63,0.5,30],pos=[63/2+0.5,10.25,-15],marker=2,)
cube2=mt.createCube(size=[63,8,25],pos=[63/2+0.5,6,-25/2],marker=3)
plc=geo+cube1+cube2
mesh=mt.createMesh(plc,quality=1.3)
pg.show(mesh,mesh.cellMarkers())
`
The following error occurred：
GIMLI::Boundary* GIMLI::findBoundary_(const std::set<GIMLI::Boundary*>&)  pls. check, this should not happen.  There is more then one boundary defined.2
Boundary 0x24b376f2ba0 rtti: 28 id: 11	N: 16 17 18 19  marker: 0 
Boundary 0x24b376f81b0 rtti: 28 id: 9	N: 11 10 17 13 15 16  marker: 0 
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dell\\AppData\\Local\\Temp\\tmp5gb6faxa-1.node'
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/99867753/190392088-ccb0c41c-ae1d-4f8d-a374-7d21bcdf9c9b.png">

**Comment by halbmy** [comment]
In the dam example, I first created a 2D model and then I extruded it into 3D, so I did not have any problem with intersecting facets etc.

**Comment by halbmy** [comment]
You're trying to add two touching cubes with different side faces due to their different depth? I recommend splitting the deeper into two parts below each other so that the first one has the same side face as cube2 and both share a horizontal shape.

```
cube1a=mt.createCube(size=[63,0.5,25],pos=[63/2+0.5,10.25,-25/2],marker=2)
cube1b=mt.createCube(size=[63,0.5,5],pos=[63/2+0.5,10.25,-27.5],marker=2)
cube2=mt.createCube(size=[63,8,25],pos=[63/2+0.5,6,-25/2],marker=3)
```

**Comment by halbmy** [comment]
Any progress? If people spend time helping you, a short feedback would be appropriate.

**Comment by Finn1997** [comment]
Sorry for my late reply!  I solved the problem by traversing the grid cells

for c in grid.cells():
       if c.center().y()>10+0.25:
               s.setMarker(3)
...


<img width="621" alt="image" src="https://user-images.githubusercontent.com/99867753/196448082-22039284-1b5e-4116-858f-25a15279c544.png">

**Comment by halbmy** [comment]
The specific issue has been solved by setting markers.

For the initial question about the dam, there is a notebook on the mesh generation:

https://github.com/gimli-org/notebooks/blob/main/meshing/dam/DamModeling.ipynb
