### ISSUE TITLE
Can this package support fast marching method for tomography?

### ISSUE THREAD

**Issue by xichaoqiang** [gimli-org/gimli#433]
From paper reading, I think fast marching method may be more accuracy than Dijkstra method.

Can this package support fast marching method for travel time tomography？

**Comment by halbmy** [comment]
pyGIMLi does not support Fast Marching Method as I am not aware of any implementation on irregular meshes. 

However, the Dijsktra method is inaccurate if you restrict rays to triangle boundaries only.

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.
