### ISSUE TITLE
A question about ERT Pole-Dipole scheme

### ISSUE THREAD

**Issue by xichaoqiang** [gimli-org/gimli#436]
I am new to ert. Can I use pygimli forward Pole-Dipole scheme. na=a.

![1d31896cc7e8a01be97281993b784d8](https://user-images.githubusercontent.com/30900789/190846660-b628410f-dc1e-4b9f-8c54-55e631b3a9e1.jpg)

The distance between A and M equal to the distance between M and N.

**Comment by halbmy** [comment]
Yes you can use any possible (also non-conventional) array.
