### ISSUE TITLE
Bug on the website with the tutorials and examples sections

### ISSUE THREAD

**Issue by prisae** [gimli-org/gimli#437]
### https://www.pygimli.org => Tutorials and Examples

The titles of the examples on the tutorials and examples pages are currently duplicated. I suspect it is related to recent changes in sphinx-gallery, but I am not sure.

Below a screenshot.
![2022-09-17-01](https://user-images.githubusercontent.com/8020943/190859941-76a6a68f-fd9e-41d8-b849-6f85abfe519e.png)

**Comment by florian-wagner** [comment]
This actually was a more deep-rooted problem. In the pyGIMLi Sphinx theme (which I set up in September 2015 with limited HTML/CSS knowledge...), the CSS files by external Sphinx extensions were disregarded. Hence, any style changes through updating the `sphinx-gallery` package on our jenkins server never made it to the website. [Now external CSS files are included](https://github.com/gimli-org/gimli/commit/cb95c85befa50d2ccb5266329ad8a46cc8c775c0#diff-a7ca464c259eb571a0980cdc395b7ecca338d8a4244d80bfd702637058e78f4d), I could remove a lot of unnecessary manual tweeks from the `gimli.css` and everything looks fine again (currently on http://dev.pygimli.org only until the next release).

Thanks for reporting @prisae!
