### ISSUE TITLE
Update issue, ert.estimateError(), and ert.showData()

### ISSUE THREAD

**Issue by HoseinFereydooni** [gimli-org/gimli#439]
### Cant update to the latest version

**Operating system**: Mac
**Python version**: Python 3.9.7
**pyGIMLi version**:  1.1.1+0.gbb685a8c (with local changes)
**Way of installation**: Conda package

I wanted to run some codes in the ERT field data with topography example: 
```
import pygimli as pg
import pygimli.meshtools as mt
import numpy as np
import matplotlib.pyplot as plt
from pygimli.meshtools import polytools as plc
from pygimli.physics import ert

ert.showData(data, vals=k0/data['k'], label='Topography effect')
```
Response:  module 'pygimli.physics.ert' has no attribute 'showData'

```
data['err'] = ert.estimateError(data, absoluteUError=5e-5, relativeError=0.03)
```
Response: module 'pygimli.physics.ert' has no attribute 'errorEstimate'

Also I tried many ways to update pyGIMLi but I couldn't. 

1- so do we have the alternative code for the older version!
2- How can I update it!

**Comment by halbmy** [comment]
pyGIMLi 1.1 is very old (almost 2 years), so you should update to a newer version. As we are currently facing problems building v1.3 on the Mac, you should at least install v1.2.6 (a few months old) which should be easy on Mac. Better create a new environment than updating an existing one:
```
conda create -n pg -c gimli -c conda-forge pygimli=1.2.6
```

We restructured pyGIMLi to better work on the module level:

In v1.1, `ert.showData()` was still `ert.showERTData()`. For error estimation, you need to create an ERTManager (`mgr=ert.ERTManager()` ) and use `mgr.estimateError()` in v1.1.

**Comment by halbmy** [comment]
1. Have you been successful using the provided code lines in v1.1.1?
2. Did you try installing v1.2.6 and use the original code on that?

**Comment by HoseinFereydooni** [comment]
Thank you for the response,
I updated it to 1.2.6 and the problem solved

**Comment by halbmy** [comment]
great to hear, so we can close the issue. Hope to have a version 1.3 for Mac soon.
