### ISSUE TITLE
Issue with gimli installation

### ISSUE THREAD

**Issue by dhhien** [gimli-org/gimli#44]
Hi there,

I tried to install gimli libraries as instructed from the package. However, the configuration by cmake gave me an error as the follows

-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Target is 64 bits
-- ThirdParty set to: /share_home/vpi.hien/tmp/gimli/gimli/../thirdParty/
-- External set to: /share_home/vpi.hien/tmp/gimli/thirdParty/dist-GNU-4.4.7-64
-- Found PythonInterp: /share_home/vpi.hien/anaconda3/bin/python (found version "3.5.2") 
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   system
--   thread
-- Boost version: 1.60.0
-- Boost is local False
-- Boost found
-- BOOST_ROOT does not exist: 
-- BOOST_ROOT, 
-- Boost_INCLUDE_DIR, /share_home/vpi.hien/anaconda3/include
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   system
--   thread
-- boost include: /share_home/vpi.hien/anaconda3/include
-- Looking for C++ include boost/interprocess/managed_shared_memory.hpp
-- Looking for C++ include boost/interprocess/managed_shared_memory.hpp - found
-- Looking for C++ include boost/bind.hpp
-- Looking for C++ include boost/bind.hpp - found
-- HAVE_BOOST_INTERPROCESS_MANAGED_SHARED_MEMORY_HPP 1 /share_home/vpi.hien/anaconda3/include
-- Checking for package 'TRIANGLE'
-- External dir: /share_home/vpi.hien/tmp/gimli/thirdParty/dist-GNU-4.4.7-64
-- Triangle_INCLUDE_DIR = Triangle_INCLUDE_DIR-NOTFOUND
-- Triangle_LIBRARIES = Triangle_LIBRARIES-NOTFOUND
-- Triangle could not be found. (missing:  Triangle_LIBRARIES Triangle_INCLUDE_DIR) 
-- Triangle is local True
-- Found Wget: /usr/bin/wget  
-- Found Subversion: /usr/bin/svn (found version "1.6.11") 
-- Found Git: /usr/bin/git (found version "1.7.1") 
CMake Error at /share_home/vpi.hien/cmake/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Hg (missing: HG_EXECUTABLE)
Call Stack (most recent call first):
  /share_home/vpi.hien/cmake/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /share_home/vpi.hien/cmake/share/cmake-3.4/Modules/FindHg.cmake:108 (find_package_handle_standard_args)
  cmake/GIMLImacros.cmake:152 (find_package)
  cmake/GIMLImacros.cmake:193 (findBuildTools)
  cmake/GIMLImacros.cmake:169 (find_or_build_package_check)
  CMakeLists.txt:202 (find_or_build_package)

-- Configuring incomplete, errors occurred!
See also "/share_home/vpi.hien/tmp/gimli/build/CMakeFiles/CMakeOutput.log"

Can you please help to figure this issue.

Kind regards,
Hien

**Comment by carsten-forty2** [comment]
"Could NOT find Hg (missing: HG_EXECUTABLE)"

You need to install the 'mercurial' package for some third party dependencies.
(http://www.pygimli.org/installation.html)

Kind regards,
Carsten

Quoting dhhien <notifications@github.com>:

**Comment by WilstheLazerKiwi** [comment]
I am having trouble installing pygimli on my machine. I am running Ubuntu 14.04 with python3.4 and am following the example Ubuntu installation. 

Pygimli appears to install fine but when I import pygimli using python3.4 idle I get the error:

> File "/home/wilsonthom3/.local/lib/python3.4/site-packages/pygimli-1.0rc-py3.4.egg/pygimli/core/__init__.py",
line 33, in <module>

I have double checked and appear to have all of the dependencies and correct python paths. 
Can you please help me.

kind regards,
Tom

**Comment by florian-wagner** [comment]
Hi Tom, although the error message is not complete, it looks like the bindings for the C++ code were not probably built or not copied to your site-packages path. Did you call `python setup.py --install` at the beginning or did you follow the other steps on www.pygimli.org/installation.html first?

Using the Anaconda (or Miniconda) might also be an option for you. Then you just need to type `conda install -c gimli pygimli`.

**Comment by WilstheLazerKiwi** [comment]
Hi Florian,

I followed the installation steps on
http://www.pygimli.org/installation.html before calling python setup.py
--install. Do you think this is my issue? I download anaconda and try
installing pygimli with that.

Thank you for your help.

**Comment by carsten-forty2** [comment]
We need the complete output from your run to find the issue.

You can try Anaconda .. or you can try the curl script.

Did you tried without installation by only setting PYTHONPATH appropriate?


Quoting WilstheLazerKiwi <notifications@github.com>:

**Comment by WilstheLazerKiwi** [comment]
See attached for the full error report. I am currently installing miniconda
and trying the curl script.
I am not sure I understand your last question, could you please elaborate?

**Comment by WilstheLazerKiwi** [comment]
Also, I have installed pygimli via the curl script and get the same error.

**Comment by carsten-forty2** [comment]
miniconda and the curl script are two different approaches.

I meant that you can simple set the following environmental variables  
to run pygimli.

export PYTHONPATH=$PYTHONPATH:$HOME/src/gimli/gimli/python
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/src/gimli/build/lib
export PATH=$PATH:$HOME/src/gimli/build/bin


p.s. there is no attached file


Quoting WilstheLazerKiwi <notifications@github.com>:

**Comment by WilstheLazerKiwi** [comment]
That's odd It appears attached from my end. Did it come through this time?

**Comment by WilstheLazerKiwi** [comment]
Yes I added:

export PYTHONPATH=$PYTHONPATH:$HOME/src/gimli/gimli/python
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/src/gimli/build/lib
export PATH=$PATH:$HOME/src/gimli/build/bin

To my .bashrc then saved the file and restarted my computer before trying:
'import pygimli'

**Comment by florian-wagner** [comment]
I think attaching files to the mail does not work. But you can make attachments in the [GitHub issue](https://github.com/gimli-org/gimli/issues/44).

In your case I would recommend to prepend the paths, i.e.:

``` bash
export PYTHONPATH=$HOME/src/gimli/gimli/python:$PYTHONPATH
export LD_LIBRARY_PATH=$HOME/src/gimli/build/lib:$LD_LIBRARY_PATH
export PATH=$HOME/src/gimli/build/bin:$PATH
```

otherwise it will use the pygimli version in `/home/wilsonthom3/.local/lib/python3.4/site-packages/` that you already copied there by calling `python setup.py --install`. The latter is not wrong (it circumvents the need for setting the paths manually), but I guess it was too early, i.e. something went wrong during the building process before.

**Comment by WilstheLazerKiwi** [comment]
Hi Florian,

Here is the full error report:

In [1]: import pygimli
No module named _pygimli_
Traceback (most recent call last):
  File
"/home/wilsonthom3/build/gimli/gimli/python/pygimli/core/__init__.py", line
33, in <module>
    from . _pygimli_ import *
ImportError: No module named _pygimli_
ERROR: cannot import the library '_pygimli_'.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-2135e2a919ec> in <module>()
----> 1 import pygimli

/home/wilsonthom3/build/gimli/gimli/python/pygimli/__init__.py in <module>()
     13 import os
     14
---> 15 from . import core
     16 from ._version import get_versions
     17 from .core import *

/home/wilsonthom3/build/gimli/gimli/python/pygimli/core/__init__.py in
<module>()
     41 ###########################
     42
---> 43 _pygimli_.load = None
     44
     45 from pygimli.io import load

AttributeError: 'NoneType' object has no attribute 'load'

I hope this is useful to you.

cheers,
Tom

**Comment by carsten-forty2** [comment]
is there the following file?

/home/wilsonthom3/build/gimli/gimli/python/pygimli/core/_pygimli_.so

If not, I assume your pygimli compilation went wrong.

Can you in case please provide the full output from:

make pygimli





Quoting WilstheLazerKiwi <notifications@github.com>:

**Comment by florian-wagner** [comment]
@dhhien In your situation the install picks up an old system-wide gcc compiler together with newer packages from anaconda. Have you tried to install the conda package directly? (`conda install -c gimli pygimli`)

**Comment by florian-wagner** [comment]
@WilstheLazerKiwi Same for holds for you. If you use the anaconda distribution anyways, I would recommend to install pygimli as a conda package, too.
