### ISSUE TITLE
Doubt for analysis with discrepancy principle

### ISSUE THREAD

**Issue by brianhavk** [gimli-org/gimli#440]
### Doubt description

Hello once again.

Is there any way to be able to return the $m^{true}$ and the $m$? 
![Screenshot 2022-09-25 174623](https://user-images.githubusercontent.com/82900508/192169030-1371b6ba-d023-4a4b-acb8-31d0297c686d.png)

I would like to obtain the error $e$ or "Gaussian vector" to calculate the $\epsilon$ / $\delta$ of Morozov's discrepancy principle. 

I still have doubts that the relative measurement error $err$ is this error $e$.

> **_Bibliography_**
>
> Cornelis, J., Schenkels, N. & Vanroose, W. (2020, 30 abril). Projected Newton method for noise constrained Tikhonov regularization. Inverse Problems, 36(5), 055002. https://doi.org/10.1088/1361-6420/ab7d2b
>
> Hofmann, B. & Hofmann, C. (2020, 3 marzo). The Impact of the Discrepancy Principle on the Tikhonov-Regularized Solutions with Oversmoothing Penalties. Mathematics, 8(3), 331. https://doi.org/10.3390/math8030331
>
> Jordi, C., Doetsch, J., Günther, T., Schmelzbach, C. & Robertsson, J. O. (2018, 9 febrero). Geostatistical regularization operators for geophysical inverse problems on irregular meshes. Geophysical Journal International, 213(2), 1374-1386. https://doi.org/10.1093/gji/ggy055
>
>Whitney, MaryGeorge L., "Theoretical and Numerical Study of Tikhonov's Regularization and Morozov's 
Discrepancy Principle." Thesis, Georgia State University, 2009.

**Comment by halbmy** [comment]
In reality (e.g. field data), you don't know the true model $m_{true}$. Only in synthetic experiments you know it.

Likewise, you don't know the real noise as it is result of a Gaussian process. But you know (in the best case) the error model vector, which is the standard deviation of the Gaussian noise. 
This is used to weight the misfit function and also to determine the regularization strength according to the discrepance principle. 

The error model has the unit of the data, so you would have to transform the relative error into an absolute one. Errors are often rather relative than absolute.
In geophysics, you often use a data (and model) transformation to improve the singular value spectrum. For instance the logarithm is widely used which has an transformed error vector of relative errors. In pyGIMLi you can freely use this transformation and the error is transformed when solving the inverse subproblem.

**Comment by brianhavk** [comment]
I see, my initial premise would only be addressing the forward problem.

Starting then from the transformation you mention, can I then define the relative error $err=log(1+\frac{X_{m}}{X_e})$ to solve the inverse subproblem of the absolute error? where $X_{m}$ would then be an approximate measurement (our data) such as induced polarization, apparent resistivity, and self-potencial. And $X_e$ the "exact" value of that measurement.

I hope I am not too far wrong...

**Comment by halbmy** [comment]
I have no idea what you're talking about. There is only (incorrect) data and no such thing as "exact measurement". That's what inversion is about assuming a Gaussian distribution of errors.

The error of logarithmized data computes to
$\delta log d = log(1+\frac{\delta d}{d})$
but that's automatically done in the inverse solver.

**Comment by brianhavk** [comment]
I suspected, quite a lot, that it would have quite a few errors. 

Thank you very much for all the help, I believe that with this I have a better context and definitions for the work with this method.

**Comment by brianhavk** [comment]
To close this issue, I would like to ask one last question.

The $\chi^2$ is after all a selection of $\lambda$ by means of a discrepancy criterion with a tolerance value equal to 1, right?

**Comment by halbmy** [comment]
Correct, ideally, e.g. for synthetic experiment with known error model, the regularization should be chosen so that the chi-square is close to 1 according to the discrepancy principle. In other words, the smoothest (or simplest) model is chosen that fits the data. And the misfit distribution is uncorrelated Gaussian.

In real life the errors are not known perfectly, not necessarily Gaussian, and there are systematic effects. Plus there is an error from the forward calculation (also for synthetic experiments).

**Comment by brianhavk** [comment]
Great, I can now understand how the calculations I have obtained make much more sense and value.

Thank you very much for all the explanations and clarifications provided, they are very important.
