### ISSUE TITLE
Question: How to do 3D Inversion of 2D ERT lines?

### ISSUE THREAD

**Issue by mariacarrizo** [gimli-org/gimli#441]
### Problem description

Hello!
I'm trying to run the ert.ERTManager.invert() function for a file that contains several 2D lines.
I've loaded the 2D lines in a single file to the data container. The file that contains the ERT lines is in the pybert format, including topography values. 
I think the problem is that the ert.ERTManager.invert() function does not generate a 3D mesh in this case, instead it is creating a strange 2D mesh

Am I missing a step? Thanks!

### Your environment

**Operating system**: Windows
**Python version**: 3.9.12
**pyGIMLi version**: 1.3.0`
**Way of installation**: Conda package

### Steps to reproduce

```import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import ert

scheme = pg.DataContainerERT()
scheme = ert.load('AllLines.dat')
scheme.remove(scheme['rhoa'] < 0.01)
pg.info('Filtered rhoa (min/max)', min(scheme['rhoa']), max(scheme['rhoa']))
scheme["k"] = ert.createGeometricFactors(scheme, numerical=True)
scheme['err'] = ert.estimateError(scheme, absoluteError=0.001, relativeError=0.03)
mgr = ert.ERTManager(scheme)
mod = mgr.invert(scheme)
...
```

[AllLines.txt](https://github.com/gimli-org/gimli/files/9672392/AllLines.txt)

**Comment by halbmy** [comment]
While for 2D surface ERT data mesh generation is straightforward with some easy default arguments, it is not yet hardwired in 3D, particularly not when involving topography. This means you have to create your own mesh and pass it to `mgr.invert(mesh=mesh...)`. 

I will start with the easier case without topography and will also provide this as an example:
```
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import ert

data = pg.getExampleData("ert/gallery3d.dat")
data["k"] = ert.createGeometricFactors(data)
data['err'] = ert.estimateError(data, absoluteError=0, relativeError=0.03)

plc = mt.createParaMeshPLC3D(data)
mesh = mt.createMesh(plc)

mgr = ert.ERTManager(data)
mod = mgr.invert(mesh=mesh, verbose=True)
```

This should of course be the default behaviour if not passing a mesh.

**Comment by halbmy** [comment]
In principle this should also work for your data. I suggest using `numerical=False` for the geometric factors if the topography is not extremely strong, finally it is just a factor that helps scaling your data.

Note that `mgr.showResult()` or `mgr.showModel()` does not yet work but you can use `pg.show(mgr.paraDomain, mgr.model)` for a quick look and export the results
```
pd = mgr.paraDomain
pd["resistivity"] = mgr.model
pd.exportVTK("result.vtk")
```
for visualization with ParaView.

**Comment by mariacarrizo** [comment]
Thank you for your reply! 
Yes, it works now. I thought that the geometric factor was a necessary parameter, but now is more clear.
I will continue experimenting with pygimli

**Comment by GGDRriedel** [comment]
In case you want a less experimental and more straight to results approach I would recommend ResIPy for 3D inversion of 2D lines. 
It really depends on where your priority is. 

I think it even has the ability to export the generated mesh, so if you're after "just get stuff done" load your data with ResIPy, export results and re-use the mesh with pygimly for way way mightier inversion algos.

**Comment by GGDRriedel** [comment]
I just checkd this. You ca import several 2D lines into 3D and save a generated mesh from ResIPy. I don't know how good PyGmli is able to load that mesh but it's a way to skip the troublesome 3D workflow of pygimli with meshes and imports and whatnot.

**Comment by carsten-forty2** [comment]
If your data contains correct 3d coordinates you can also try: 
https://www.pygimli.org/pygimliapi/_generated/pygimli.meshtools.html#createparameshplc3d

Which is quiet new and will be the default for 3d cases with and without topography, when we find a good automatic way to decide if a file contains 3d data.

```
plc = pg.meshtools.createParaMeshPLC3d(data) # play with parameter until the geometry/mesh fits your needs.
pg.show(plc, regions=True) # or export VTK for viewing in paraview
mesh = pg.meshtools.createMesh(plc)
pg.show(mesh, markers=True, filter={'clip':{'origin':(0, 0, 0)},},) # or export VTK for viewing in paraview
```

**Comment by mariacarrizo** [comment]
> In case you want a less experimental and more straight to results approach I would recommend ResIPy for 3D inversion of 2D lines. It really depends on where your priority is.
> 
> I think it even has the ability to export the generated mesh, so if you're after "just get stuff done" load your data with ResIPy, export results and re-use the mesh with pygimly for way way mightier inversion algos.

Thanksfor your suggestion! I've tried with ResIPy but for the amount of measurements and electrodes I have it needs quite a large amount of memory. Additionally, when trying to use it in a supercomputer ResIPy uses compilers that are not compatible with the supercomputer requirements (it uses a compiler called "wine", that I have not been able to install in a local environment).

I'm trying with SimPEG as well just to see the difference in meshes and results of the inversion

**Comment by GGDRriedel** [comment]
Not sure what compiler you are talking about, Wine is the compability layer for Windows programs on Linux hosts.

**Comment by mariacarrizo** [comment]
Yes, Thank you. Please close the issue
