### ISSUE TITLE
Question: 2D ERT modelling on a homogeneous 3D body

### ISSUE THREAD

**Issue by marco9387** [gimli-org/gimli#443]
### Problem description
Dear GIMLi Development Team,

 We need to use 3D modelling because we want to assess the influence of a shifted 3D body on 2D ERT. 

As a first test, we use a 2D probe array (48 electrodes separated by 0.1 m, no gaussian noise added) on a homogeneous body with a resistivity value of 100 ohms but we get a very noised 2D section.

We try to refine the mesh around the probe position but it does not improve the answer. The probe spacing is small according to the body dimension, are we in a limiting case of the use of the code?

In addition, we are not sure about the use of calibration and reference electrodes,  are they well positioned or necessary? (we think that not, but apparently, they are needed for the computation to be done so the default choice may not be the better choice for us).

Thank you in advance for your help.

### Your environment

**Operating system**: Windows
**Python version**: 3.7.10
**pyGIMLi version**: 1.1.1+5.gc107727a
**Way of installation**: Conda package

### Steps to reproduce

```python
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import ert

#PLC Geometry
size_plc= [25,25,15]

#electrodes
n_elec = 48
sep_elec = 0.1
sensors = np.zeros((n_elec,3))
sensors[:,0]= np.linspace(10,14.7,n_elec)
sensors[:,1]=[12.5]

#Creating the schema
shm =  ert.createERTData(elecs=sensors,schemeName='wa')
data_k = ert.createGeometricFactors(shm)
#Creating the PLC
plc = mt.createCube(size=size_plc, pos=[12.5,12.5,-7.5], area=1, boundaryMarker=1)
pg.show(plc)

#Creating nodes in each electrode
for s in shm.sensors():
    plc.createNode(s,marker = -99)

# positioning reference electrode (should be labelled -999)
plc.createNode([0,12.5,-11.25],marker=-999)

# positioning calibration electrode (should be labelled -1000)
plc.createNode([12.5,12.5,0], marker=-1000)

#Refining mesh around electrodes
for s in plc.positions(pg.find(plc.nodeMarkers() == -99)):
     plc.createNode(s-[0,0,-0.1*sep_elec])

#Creating mesh
mesh = mt.createMesh(plc, smooth=True  )
pg.show(mesh)

#Simulating homogeneous
hom = ert.simulate(mesh, res=100.0, scheme=shm, sr=False,
                   calcOnly=True, verbose=True)
hom.save('homogeneous.ohm', 'a b m n u')
hom.set('rhoa', data_k * hom('u') / hom('i'))
hom.set('k',data_k)
pg.show(hom)
...
```

### Expected behavior
We expect to get a 100 ohm.m homogeneous picture.

### Actual behavior
```

![2D_send](https://user-images.githubusercontent.com/81471958/193538457-ff2efb79-6e3b-46af-8486-cb8077e34869.png)

```

**Comment by halbmy** [comment]
Just to make sure: you are working on a closed geometry (of physical size 25x25x15m), correct? If not, i.e. if working in an ubounded domain, you should create such a mesh and use `sr=True`.

You try to refine your electrodes by 1/10 of the electrode separation, but the line
```
plc.createNode(s-[0,0,-0.1*sep_elec])
```
leads to refinement points 0.01m ABOVE the cube, i.e. they are not used in the mesh. If replacing one of the - by a + you'll coming closer:
![image](https://user-images.githubusercontent.com/7136401/193787386-3cf9562a-4100-45f2-87cc-e78aef5418a8.png)

If modelling without singularity removal (`sr=False`), you should use either a finer discretization, or, more efficiently, quadratic shape functions to accurately model the potential in the vicinity of the electrodes (Rücker et al. 2006, 2011). This can be achieved by 
```
meshP2 = mesh.createP2()
ert.simulate(meshP2, ...
```

With this you'll reach the targeted values within 0.5% accuracy:
![image](https://user-images.githubusercontent.com/7136401/193787652-e7d96af3-beb3-4e61-9cce-0a22835dead0.png)

**Comment by marco9387** [comment]
Thank you so much for your answer!!
