### ISSUE TITLE
Structural constraint invert runtimeError

### ISSUE THREAD

**Issue by 728236958** [gimli-org/gimli#446]
Hello, thanks for your guidance and help many times. 
I wonder invert the ERT data by the method of structural constraints. The reference is from [https://github.com/gimli-org/transform2021/blob/main/5_ERT_field_data_inversion.ipynb](https://github.com/gimli-org/transform2021/blob/main/5_ERT_field_data_inversion.ipynb). But there is always an error indicating that the resistivity has a value of 0 or a negative value. Is there a problem in the calculation when rebuilding the structural inversion grid,
![image](https://user-images.githubusercontent.com/69100178/195644595-fc5092f5-2acb-444c-b536-e20378ade5ff.png)
Here is the test script I used. Thanks in advance!
[code & data.zip](https://github.com/gimli-org/gimli/files/9778439/code.data.zip)

**Comment by halbmy** [comment]
First, you should use the switch `worldBoundaryMarkers` for creating the grid to make clear that you are at the Earth's surface with no-flow conditions on top and mixed boundary conditions elsewhere:
```
mesh = mt.createGrid(x=np.arange(200.1),
                     y=-np.arange(100.1),
                     worldBoundaryMarker=True)
```
This will speed up computations as the primary potential can be computed analytically.

I would further recommend to use a (relative) noise level of at least 0.01 (1%), maybe more to be realistic. In ERT there is always a relative noise contribution.

**Comment by halbmy** [comment]
```
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
import matplotlib.pyplot as plt
from pygimli.viewer import showMesh
from pygimli.physics import ert
import pygimli.physics.traveltime as tt
import pandas as pd

#createGrid regular mesh
mesh = mt.createGrid(x=np.arange(200.1),
                     y=-np.arange(100.1),
                     worldBoundaryMarker=True)
_= pg.show(mesh, markers=True, showMesh=True)
print(mesh)

#createborehole sensors
n = 20   # number of sources and receivers per borehole
borehole = np.ones((n, 2))*50   # borehole at x = 50 m
borehole_ = np.ones((n, 2))*100
borehole[:,1] = np.linspace(-0, -50, n)
borehole_[:,1] = np.linspace(-0, -50, n)
sensors = np.vstack([borehole,borehole_])
ax, _ = pg.show(mesh, markers=True, showMesh=True)
ax.plot(sensors[:,0], sensors[:,1], "mo")

# %% input data
test_path="testdert2.csv"
f=open(test_path,encoding="utf-8")
test=pd.read_csv(f,low_memory=False,header=None)
test=np.array(test).reshape(1,-1).squeeze(0)
rhomap = test

# Take a look at the mesh and the resistivity distribution
pg.show(mesh, data=rhomap, label=pg.unit('res'), showMesh=True)
# %%
scheme = ert.createERTData(sensors,schemeName='wa')
print(scheme)
print(scheme.sensor(0))
np.column_stack((pg.x(scheme), pg.y(scheme)))
print(scheme["valid"])

data = ert.simulate(mesh, scheme=scheme, res=rhomap, noiseLevel=0.01,
                    noiseAbs=1e-6, seed=1337)
pg.info(np.linalg.norm(data['err']), np.linalg.norm(data['rhoa']))
pg.info('Simulated data', data)
pg.info('The data contains:', data.dataMap().keys())
pg.info('Simulated rhoa (min/max)', min(data['rhoa']), max(data['rhoa']))
pg.info('Selected data noise %(min/max)', min(data['err'])*100, max(data['err'])*100)
ert.show(data)
# %%
data.remove(data['rhoa'] < 0)
pg.info('Filtered rhoa (min/max)', min(data['rhoa']), max(data['rhoa']))
#Save the data
data.save('dcgzys.dat')
ert.show(data)
```
[testdert2.csv](https://github.com/gimli-org/gimli/files/9784021/testdert2.csv)

**Comment by halbmy** [comment]
The normal inversion
```
mgr = ert.ERTManager('dcgzys.dat')
inv = mgr.invert(data, mesh, lam=20,verbose=True)
ax = mgr.showResult(cMin=100 , cMax=500 , colorBar=True,logScale=True)
pg.show(ax=ax, fillRegion=False, regionMarker=False)
```
runs normally converging with a chi-square of 1. 

![image](https://user-images.githubusercontent.com/7136401/195829094-019faf46-2b97-4fef-8b51-18e3e22fdb9a.png)

So far so good.

**Comment by 728236958** [comment]
Yeah! Thank you for your quick reply! According to your improved code, it runs smoothly.

**Comment by halbmy** [comment]
However, I don't know what you want to do with the other mesh:
```
c1 = mt.createPolygon([[0,0], [0, -31], [14, -31], [68,-48], [100, -48], [100, 0]],
                         isClosed=True, marker = 1, area=1)
c2 = mt.createPolygon([[0,-31], [0, -50], [100, -50], [100,-48], [68, -48], [14, -31]],
                         isClosed=True, marker = 2, area=1)
line1 = mt.createLine(start=[0,-31],end=[14,-31],marker= 99)
line2 = mt.createLine(start=[14,-31],end=[68,-48],marker= 98)
line3 = mt.createLine(start=[68,-48],end=[100,-48],marker= 97)
world0 = mt.createWorld(start=[0, 0], end=[100, -50],marker=96)
world = mt.createWorld(start=[-50, 0], end=[150, -100],marker=0)
geom = line1+line2+line3+world+world0
ax,_ = pg.show(geom)
ax.set_xlim(-30, 120);
ax.set_ylim(-100, 5);
```

![image](https://user-images.githubusercontent.com/7136401/195856575-b1b5fdde-f45d-4ace-a9ea-44f90bb2e752.png)

The line markers do not make sense to me, they should be omitted. Important are the region markers. If you have two, you need to control your regions by `mgr.inv.setRegularization('*', background=False)` because otherwise the lower will be treated as background. Actually it makes sense so introduce a background inversion for models parts without resolution. See also Transform2022 examples https://github.com/gimli-org/transform2022 on how to control regions.

**Comment by 728236958** [comment]
Actually, I wonder obtain the underground interface through the surface seismic travel time as the constraint boundary. However, on the one hand, the seismic travel time needs to run for a long time in the regular grid inversion process; On the other hand, the inversion result is not good enough or even worse than the ERT inversion result in depicting the subsurface.

Code and data of surface seismic and cross-hole seismic are attached here. Thank you！
[surface-seismic code&data.zip](https://github.com/gimli-org/gimli/files/9852379/surface-seismic.code.data.zip)
[crosshole-seismic code&data.zip](https://github.com/gimli-org/gimli/files/9852380/crosshole-seismic.code.data.zip)

**Comment by halbmy** [comment]
I still don't understand your problem. 

If you want to implement a structural constraint (e.g. from a seismic reflection) you just have to add the line with a marker > 0.

What's wrong with your code? Are there any errors? I am afraid that we will not have the time to revise your code. If there is a specific problem, create a new issue with code snippets and images instead of uploading your work in the hope that somebody will do your work. If possible, try to break it down to a simple example.

**Comment by 728236958** [comment]
OK, I'm sorry to upload the code in this form. I'll modify it and consult next time. Thank you！
