### ISSUE TITLE
How to run the inversion with apparent negative resistivity?

### ISSUE THREAD

**Issue by FedericaMaeliFerrari** [gimli-org/gimli#447]
### Problem description
Hi! 
I am having a problem using pyGIMLI in my master thesis. I am testing nanostructured materials which  shows a Resistive Switching behavior when the current pass by.
Long story short,  the current cracks the material in localized areas and I  am trying to use the ERT technique for detect them.
The problem is that these cracks cause some  apparent resistivity measurements to be negative,  due to the fact that the current is non linear through them.

Of course I can't reject the  negative data, and I don't know a priori where the crack is, so I cannot draw specific regions marker on the mesh.
****
I tried to use a complex value electrical inversion, but I didn't succeed. 
Copy  part of the code below

### Steps to reproduce
```
import pygimli as pg
from pygimli.physics import ert
import pygimli.meshtools as mt


world=mt.createWorld(start=[0,0], end=[coord_mesh[0],coord_mesh[1]], area=[0.01, 100], marker=0)
scheme=ert.createData(elecs=(pos_el),schemeName='wb')
for electrode in scheme.sensors():
    world.createNode(electrode)
    world.createNode(electrode- [0, 0.1])
mesh=mt.createMesh(world, quality=24)


data = ert.load(namefile)
k = ert.createGeometricFactors(data,numerical=False)
data["k"]=k

rhoa=np.asarray(data["u"]/data["i"]*data["k"])
rhomap=pg.utils.complex.toComplex(rhoa,  phase)
data["rhoa"]=rhomap
```
ecc.ecc.

### Actual behavior
Even if rhoa is a complex vector, when I try to "load"  it on my data file data["rhoa"] becames a vector full of 6.9521986777696e-310.
Probably complex value doesn't match with ert data type, have you any suggestion for avoid this problem? 
Is there another way to run the inversion with negative resistivity data?

Thanks in advance (and forgive me if I made english mistekes)

### Your environment

****Operating system****: Linux
**Python version**:  3.8.8
**pyGIMLi version**: 1.2.5
**Way of installation**:manual compilation from source

**Comment by halbmy** [comment]
Apparent resistivity is just a concept to bring signed resistance data with a large range of magnitude to a compact form that can be better viewed. There are examples of negative apparent resistivity in geophysics, mostly for strong resistivity contrasts in the vicinity of the electrodes. As they need to follow a specific scheme, single ones are still mostly just crab. I don't quite understand your background to judge whether this is true in your case. At any rate, you can choose any geometric factor, e.g. constantly 1.0. The only change you have to make is to use a linear data transformation and everything should run well.

**Comment by FedericaMaeliFerrari** [comment]
Ok I'll try this, thank you very much for the quick answer!

**Comment by halbmy** [comment]
Any news on that? Generally we can do inversion using `pg.Inversion` also with linear data transformation (which is the default behaviour). If there's reason and examples for it, we could probably trigger this by a keyword argument to `ERTManager.invert()`
