### ISSUE TITLE
Problem with dependencies to libpython3.4m.so, libpython3.4m.so.1.0 and libboost_python-py34.so while making pygimli under python3.5

### ISSUE THREAD

**Issue by kaufmanno** [gimli-org/gimli#45]
Hi,

I was trying to install pygimli on a fresh ubuntu 16.04LTS using curl (in ~/src).

After solving an initial problem with llvm ( [see Issue#40 ](https://github.com/gimli-org/gimli/issues/40)), I encountered an other difficulty to make pygimli : 
 
make[7]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libpython3.4m.so.1.0', needed by '/home/su530201/src/gimli/gimli/python/pygimli/core/_pygimli_.so'.  Stop.

The default python on the system is python3.5.
I didn't find a simple and elegant fix but tried brute force to find a workaround :
cd ~/src/gimli
find ./ -type f -readable -writable -exec sed -i "s/python3.4/python3.5/g" {} \;
find ./ -type f -readable -writable -exec sed -i "s/py34/py35/g" {} \;

cd ~/src/gimli/build
CLEAN=1 cmake ../gimli
make pygimli
make apps 

It is not nice (but I could make pygimli an apps and it seems to work OK...)

Olivier

**Comment by carsten-forty2** [comment]
Thanks for reporting.

The curl script still forces python3.4 on ubuntu .. I will fix this asap.

A call of cmake on a fresh build path should work.

Alternatively you can set the python library with:

cmake -DPYTHON_LIBRARY=/usr/lib64/libpython3.5.so

Cheers,
Carsten
