### ISSUE TITLE
Surface traveltime regular/irregular mesh inversion velocity field: depth limitation and error reporting

### ISSUE THREAD

**Issue by 728236958** [gimli-org/gimli#450]
### Problem description
Surface travel time regular/irregular mesh inversion velocity field: depth limitation and error reporting.

1. We have tried surface traveltime inversion on regular/irregular grid. The inversion results on regular grid show that the ray can only be measured in the range of - 10m; If I expand the range, for example, adjust the grid range to 200 × 100. Due to the increase of the number of grids, the calculation time is very long.

2. We believe that the surface traveltime is sensitive to the identification of deeper subsurface interface. Is it necessary to replace the surface travel time with crosshole traveltime method?

3. I see whether gradient can help to improve the calculation efficiency and resolution with startmodel.
![image](https://user-images.githubusercontent.com/69100178/197929604-9c425434-4d7f-4b6e-aa31-4ad158c5da17.png)
![image](https://user-images.githubusercontent.com/69100178/197929807-2211437d-5e05-49e1-a232-d1aef3d3b727.png)

### Your environment

**Operating system**: Windows
**pyGIMLi version**: 1.3.0
**Way of installation**: e.g. Conda package

### Steps to reproduce
[testd01.csv](https://github.com/gimli-org/gimli/files/9865642/testd01.csv)
```
#2D cross-borehole seismic forward and inversion
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
import matplotlib.pyplot as plt
from pygimli.physics import TravelTimeManager
from pygimli.viewer import showMesh
import pygimli.physics.traveltime as tt
import pandas as pd
#create mesh
mesh = mt.createGrid(x=np.arange(100.1),y=-np.arange(50.1),worldBoundaryMarker=True)
_= pg.show(mesh, markers=True, showMesh=True)
print(mesh)
#import velocity value
test_path="C:/Users/Dell/Desktop/testd01.csv"
f=open(test_path,encoding="utf-8")
test=pd.read_csv(f,low_memory=False,header=None)
test=np.array(test).reshape(1,-1).squeeze(0)
print(test)
vp = test
print(len(test))
pg.show(mesh, data=vp, label='v in m/s', showMesh=True)

#set surface seismic sensors
numberGeophones = 51
sensors = np.linspace(0, 100, numberGeophones)
scheme = pg.physics.traveltime.createRAData(sensors)
pos = np.array(scheme.sensors())
for x in pos[:,0]:
    i = np.where(pos[:,0] == x)
scheme.setSensors(pos)

mgr = TravelTimeManager()
ax, _ = pg.show(mesh, vp, colorBar=True, logScale=False, label='v in m/s')
pg.viewer.mpl.drawSensors(ax, scheme.sensors(), diam=2.0,
                         facecolor='white', edgecolor='black')
#simulate
data = mgr.simulate(slowness=1.0 / vp, scheme=scheme, mesh=mesh,
                    noiseLevel=0.01, noiseAbs=1e-7, seed=1337,
                    verbose=True)
mgr.showData(data)
print(data)
#invert
vest = mgr.invert(data,mesh=mesh, secNodes=4,lam=100, 
                  useGradient=True,vTop=2000, vBot=4000,
                  verbose=True)
#output show
ax, _ = mgr.showResult(cMin=min(vp), cMax=max(vp), logScale=False)
pg.show(ax=ax, fillRegion=False, regionMarker=False)
```

**Comment by 728236958** [comment]
In addition, we tried irregular grids and reported errors during inversion. The results are as follows:.
![image](https://user-images.githubusercontent.com/69100178/197924768-ecb1f10e-5fc2-44f3-90de-996ce4620183.png)

```
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
import matplotlib.pyplot as plt
from pygimli.physics import TravelTimeManager
from pygimli.viewer import showMesh
import pygimli.physics.traveltime as tt
c1 = mt.createPolygon([[0,0], [0, -30], [16, -30], [66,-48], [100, -48], [100, 0]],
                         isClosed=True, marker = 1, area=5)
c2 = mt.createPolygon([[0,-30], [0, -50], [100, -50], [100,-48], [66, -48], [16, -30]],
                         isClosed=True, marker = 2, area=5)
geom = c1+c2  
pg.show(geom)
mesh = mt.createMesh(geom, 
                         area=10.0,
                         quality=33,
                         smooth=[2, 4]  )
showMesh(mesh, markers=True, showMesh=True);
numberGeophones = 51
sensors = np.linspace(0, 100, numberGeophones)
scheme = pg.physics.traveltime.createRAData(sensors)

pos = np.array(scheme.sensors())
for x in pos[:,0]:
    i = np.where(pos[:,0] == x)
scheme.setSensors(pos)

mgr = TravelTimeManager()
vp = np.array(mesh.cellMarkers())
vp[vp == 1] = 2000
vp[vp == 2] = 4000

ax, _ = pg.show(mesh, vp, colorBar=True, logScale=False, label='v in m/s')
pg.viewer.mpl.drawSensors(ax, scheme.sensors(), diam=2.0,
                         facecolor='white', edgecolor='black')
data = mgr.simulate(slowness=1.0 / vp, scheme=scheme, mesh=mesh,
                    noiseLevel=0.01, noiseAbs=1e-6, seed=1337,
                    verbose=True)
mgr.showData(data)
print(data)
vest = mgr.invert(data, mesh=mesh,useGradient=True, 
                  secNodes=4,vTop=2000, vBot=4000,
                  lam=50, verbose=True)
ax, _ = mgr.showResult(cMin=min(vp), cMax=max(vp), logScale=False)
pg.show(ax=ax, fillRegion=False, regionMarker=False)
```

**Comment by halbmy** [comment]
First about the general problem: Looking at the apparent velocity
![image](https://user-images.githubusercontent.com/7136401/197951648-db0013b7-2336-432e-9816-f774fc25f3f8.png)
or to make it even clearer you can set the noise level to zero and all low vp to 2000 by `vp[vp<4000]=2000`
![image](https://user-images.githubusercontent.com/7136401/197952303-fffd7805-9354-4c20-8c64-2ed1874b1603.png)

So the interface is just too deep to let the rays reach the high-velocity layer.

**Comment by halbmy** [comment]
About the second problem: First you should add the sensors as nodes to the mesh (this requires creating the scheme before)
```
for po in pos:
    geom.createNode(po)
```

Next, you should not use the same mesh that you have used for synthetic data for inversion.

At least you have to set all cell markers to a single value:
```
mesh.setCellMarkers(pg.IVector(mesh.cellCount(), 1))
```

resulting in 
![image](https://user-images.githubusercontent.com/7136401/197954239-c7a17ea6-b894-4197-b205-69fcb29ceac0.png)

In this case you already used the interface as structural constraints, better would be to create a new mesh using the outer box only.  By setting vBot to 4000 and the constraint you end up with a model close to the synthetic one, but just by chance (see above).

**Comment by 728236958** [comment]
Thank you！
