### ISSUE TITLE
Load ERT data

### ISSUE THREAD

**Issue by HoseinFereydooni** [gimli-org/gimli#451]
### Problem description

I tried to load ERT data which has a b m n r, and topo data
I have an EXCEL file ( also I saved it in other formats like *.dat, ...) but could not load it by different load commands.  
I paste my data (not real) here as I used as *.dat, hope you help me to load these data. 

45# Number of sensors
#x y z
0	0	0										
0.5	0	-0.083665027										
1	0	0.059696536										
1.5	0	-0.023968491										
2	0	-0.006509394										
2.5	0	-0.023968491										
3	0	0.100685952										
3.5	0	0.017020925										
4	0	-0.035527294										
4.5	0	0.052629569										
5	0	0.07445843										
5.5	0	0.043879378										
6	0	0.008918556										
6.5	0	-0.0172834										
7	0	0.000175698										
7.5	0	0.026377654										
8	0	0.05257961										
8.5	0	0.087540432										
9	0	0.184723249										
9.5	0	0.092060708										
10	0	0.171246998										
10.5	0	0.171246998										
11	0	0.064976779										
11.5	0	0.308822386										
12	0	0.326281483										
12.5	0	0.414438346										
13	0	0.383859294										
13.5	0	0.383859294										
14	0	0.485577746										
14.5	0	0.351613484										
15	0	0.212961941										
15.5	0	0.283227114										
16	0	0.204040824										
16.5	0	0.23024278										
17	0	0.256444736										
17.5	0	0.122480474										
18	0	0.096278518										
18.5	0	0.096278518										
19	0	0.105005407										
19.5	0	0.188670434										
20	0	0.214872391										
20.5	0	0.188670434										
21	0	0.188670434										
21.5	0	0.214872391										
22	0	0.32114261										
244# Number of data
#a	b	m	n	R
1	0	4	6	1.200782
1	0	7	9	0.6005359
1	0	10	12	0.234111
1	0	14	16	0.1889838
2	0	4	6	1.611943
2	0	7	9	0.5366979
2	0	10	12	0.3874661
2	0	14	16	0.2997173
3	0	4	6	9.044648
3	0	7	9	1.183178
3	0	10	12	0.7753688
3	0	14	16	0.584275
3	1	4	6	7.782592
3	1	7	9	0.9008894
3	1	10	12	0.5606569
3	1	14	16	0.4145229
3	2	4	6	7.350894
3	2	7	9	0.6778779
3	2	10	12	0.3782301
3	2	14	16	0.2774615
4	2	17	19	0.3174469
4	2	7	9	2.107139
4	2	10	12	0.9429343
4	2	14	16	0.6562073
5	2	17	19	0.4210139
5	2	7	9	4.426798
5	2	10	12	1.332935
5	2	14	16	0.8818494
5	3	17	19	0.2796183
5	3	7	9	3.733312
5	3	10	12	0.9226184
5	3	14	16	0.5810685
5	4	17	19	0.1011775
5	4	7	9	2.252166
5	4	10	12	0.378726
5	4	14	16	0.2156802
6	4	17	19	0.2295501
6	4	7	9	20.08439
6	4	10	12	0.9752611
6	4	14	16	0.4920283
7	4	17	19	0.3349347
7	4	20	22	0.2510397
7	4	10	12	1.693378
7	4	14	16	0.7195431
7	5	17	19	0.2423308
7	5	20	22	0.165269
7	5	10	12	1.321454
7	5	14	16	0.5057329
7	6	17	19	0.1262866
7	6	20	22	0.06000914
7	6	10	12	0.7370632
7	6	14	16	0.2385716
8	6	17	19	0.4551617
8	6	20	22	0.3434814
8	6	10	12	4.595689
8	6	14	16	1.118261
9	6	17	19	0.7468866
9	6	20	22	0.5540801
9	6	10	12	17.93418
9	6	14	16	1.917565
9	7	17	19	0.6186705
9	7	20	22	0.4833377
9	7	10	12	16.43134
9	7	14	16	1.67998
9	8	17	19	0.2891336
9	8	20	22	0.2186083
9	8	10	12	12.52469
9	8	14	16	0.8213082
10	8	17	19	0.8201409
10	8	20	22	0.5908721
10	8	23	25	0.5394046
10	8	14	16	2.514945
11	8	17	19	1.411208
11	8	20	22	0.9741488
11	8	23	25	0.8717507
11	8	14	16	4.699256
11	9	17	19	1.141228
11	9	20	22	0.7694471
11	9	23	25	0.6870048
11	9	14	16	3.944018
11	10	17	19	0.6144846
11	10	20	22	0.4004081
11	10	23	25	0.34623
11	10	14	16	2.259124
12	10	17	19	1.42281
12	10	20	22	0.9032956
12	10	23	25	0.7646374
12	10	14	16	5.905745
13	10	17	19	3.058655
13	10	20	22	1.782098
13	10	23	25	1.442941
13	10	14	16	21.16898
13	11	17	19	2.473089
13	11	20	22	1.400471
13	11	23	25	1.11549
13	11	14	16	19.10162
13	12	17	19	1.63859
13	12	20	22	0.8791825
13	12	23	25	0.680087
13	12	14	16	15.29887
14	12	17	19	3.572859
14	12	20	22	1.666137
14	12	23	25	1.22284
14	12	26	28	0.3948039
15	12	17	19	7.20917
15	12	20	22	2.827088
15	12	23	25	1.948215
15	12	26	28	0.6078657
15	13	17	19	5.639271
15	13	20	22	1.985728
15	13	23	25	1.29842
15	13	26	28	0.3920321
15	14	17	19	3.642634
15	14	20	22	1.162811
15	14	23	25	0.7213665
15	14	26	28	0.2106276
16	14	17	19	14.51045
16	14	20	22	3.398685
16	14	23	25	1.973019
16	14	26	28	0.5577214
17	14	29	31	0.4296301
17	14	20	22	6.159899
17	14	23	25	3.139557
17	14	26	28	0.8403285
17	15	29	31	0.3130315
17	15	20	22	4.978237
17	15	23	25	2.403652
17	15	26	28	0.6246022
17	16	29	31	0.1374194
17	16	20	22	2.758706
17	16	23	25	1.167806
17	16	26	28	0.2838698
18	16	29	31	0.2614126
18	16	20	22	6.760321
18	16	23	25	2.397766
18	16	26	28	0.5536135
19	16	29	31	0.3948016
19	16	20	22	54.65763
19	16	23	25	3.860853
19	16	26	28	0.8509526
19	17	29	31	0.2546013
19	17	20	22	51.80728
19	17	23	25	2.682696
19	17	26	28	0.5642982
19	18	29	31	0.1424034
19	18	20	22	50.0174
19	18	23	25	1.548811
19	18	26	28	0.3159553
20	18	29	31	0.2957331
20	18	32	34	0.3230334
20	18	23	25	3.6902
20	18	26	28	0.6972263
21	18	29	31	0.5296221
21	18	32	34	0.5451943
21	18	23	25	9.090275
21	18	26	28	1.368809
21	19	29	31	0.4120695
21	19	32	34	0.4140102
21	19	23	25	7.781963
21	19	26	28	1.10229
21	20	29	31	0.2476965
21	20	32	34	0.2432121
21	20	23	25	5.443326
21	20	26	28	0.692702
22	20	29	31	0.8115621
22	20	32	34	0.7615122
22	20	23	25	35.71079
22	20	26	28	2.455512
22	21	29	31	0.5827486
22	21	32	34	0.5651553
22	21	23	25	30.134
22	21	26	28	1.780319
23	21	29	31	1.463782
23	21	32	34	1.294084
23	21	35	37	0.7146586
23	21	26	28	5.13611
24	21	29	31	2.511476
24	21	32	34	2.127389
24	21	35	37	1.152369
24	21	26	28	10.3794
24	22	29	31	1.905689
24	22	32	34	1.572106
24	22	35	37	0.839676
24	22	26	28	8.435337
24	23	29	31	1.044596
24	23	32	34	0.8344834
24	23	35	37	0.4396269
24	23	26	28	5.199023
25	23	29	31	2.422219
25	23	32	34	1.830295
25	23	35	37	0.9448867
25	23	26	28	19.61915
26	23	29	31	21.96659
26	23	32	34	17.41816
26	23	35	37	9.355118
26	23	0	4	8.185628
27	23	29	31	32.60434
27	23	32	34	22.60658
27	23	35	37	11.72261
27	23	0	4	8.967839
27	24	29	31	32.53951
27	24	32	34	22.59878
27	24	35	37	11.73361
27	24	0	4	8.958515
27	25	29	31	34.48387
27	25	32	34	23.89925
27	25	35	37	12.39241
27	25	0	4	9.441218
28	25	29	31	48.80498
28	25	32	34	26.51678
28	25	35	37	13.28304
28	25	0	4	9.216763
29	25	8	12	0.8976688
29	25	32	34	4.832644
29	25	35	37	1.917925
29	25	0	4	0.3165634
29	26	8	12	0.629586
29	26	32	34	3.985933
29	26	35	37	1.515473
29	26	0	4	0.2193225
29	27	8	12	0.2860738
29	27	32	34	2.825646
29	27	35	37	1.001768
29	27	0	4	0.1050606
30	27	8	12	0.3985888
30	27	32	34	5.607878
30	27	35	37	1.760087
30	27	0	4	0.1493094
31	27	8	12	0.5080096
31	27	32	34	12.91014
31	27	35	37	3.055329
31	27	0	4	0.191025
31	28	8	12	0.3785594
31	28	32	34	11.95332
31	28	35	37	2.676541
31	28	0	4	0.1434563
31	29	8	12	0.2211379
31	29	32	34	10.07538
31	29	35	37	2.047674
31	29	0	4	0.08571641
16	20	8	12	4.438658
16	20	0	4	0.8673121
20	24	8	12	3.645552
20	24	0	4	1.056822

### Your environment

**Operating system**: Mac
**Python version**: Python 3.9.7
**pyGIMLi version**: 1.2.6
**Way of installation**: Conda package

...
```

**Comment by halbmy** [comment]
I copied the content into a file 
[data.csv](https://github.com/gimli-org/gimli/files/9868821/data.csv)
and could load it easily. Note that for historical reasons, 0 means infinite electrode and real electrodes count from 1. As I suspect you counted from zero, I added 1:
```
from pygimli.physics import ert

data = ert.load("data.csv")
for t in "abmn":
    data[t] = data[t] + 1
```

As the data just contains resistances, geometric factors need to be computed to yield the apparent resistivity
```
data["k"] = ert.geometricFactors(data)
data["rhoa"] = data["r"] * data["k"]
data.remove(data["rhoa"] < 0)
ert.show(data)
```
![image](https://user-images.githubusercontent.com/7136401/198011000-49cb895a-0a10-46f5-a64a-380029b7cace.png)

**Comment by HoseinFereydooni** [comment]
It worked,
Thank you
