### ISSUE TITLE
Naive complex-valued electrical inversion

### ISSUE THREAD

**Issue by HoseinFereydooni** [gimli-org/gimli#454]
[SIP.csv](https://github.com/gimli-org/gimli/files/9872124/SIP.csv)
### Problem description
I have some complex resistivity data (resistivity with phase angle) and tried to invert them by pygimli. but it's not clear how I can insert the real measurements and invert them ( I mean getting resistivity and phase angle), I attached the data (containing a b m n r pha(phase angle). 
Also is it possible to insert the data in different frequencies and invert them all in one process?

### Your environment

**Operating system**:  Mac
**Python version**: Python 3.9.7
**pyGIMLi version**: 1.2.6
**Way of installation**: e.g. Conda package

**Comment by HoseinFereydooni** [comment]
Dear @halbmy It would be my pleasure if you could help me. I read your article "Spectral Inversion of SIP field data using pyGIMLi/BERT" but I couldn't find an appropriate example guide for SIP inversion on the website. like the article, I have resistivity data in different frequencies (with phase) (The SIP section on the website just discusses SIP spectra), and want to get the resistivity and phase plot at those frequencies. 

for example, these codes (from the article) haven't been explained well, for instance, the format of the 'example.txt' file,...
are there any examples of what I'm looking for in pyGIMLi documentation?

from pygimli.physics import SIP
sip = SIP(‘example.txt’) # read data
sip.showData(norm=True, KramersKronig=True)
sip.removeEM(epsilon=True)
sip.fitColeCole()
sip.showAll(savePDF=True) 


Thank you for your time

**Comment by halbmy** [comment]
Yes, the class `SIPSpectrum` (formerly `SIP`) from `pygimli.physics.SIP` is for SIP spectra only and not for field SIP data.

For field-scale (ERT) resistivity/IP data in the frequency domain, there is a dedicated class in the pyBERT module hosted in a separate repository https://gitlab.com/resistivity-net/bert

For examples, you might have a look at the notebooks in https://github.com/gimli-org/notebooks/tree/main/IP or the
data and scripts documented in https://zenodo.org/record/4419736 accompagnying the paper of Martin et al. (2022).

The developments shown on the pyGIMLi website are for didactic reasons and are either already in or being integrated in the dedicated repositories.

I am closing this issue as it is outside of coverage for pyGIMLi

Martin, T., Günther, T., Orozco, A.F. & Dahlin, T. (2020): Evaluation of spectral induced polarization field measurements in time and frequency domain, J. Appl. Geophys. 180, 104141, doi:10.1016/j.jappgeo.2020.104141.
