### ISSUE TITLE
i have .udf data file with 667 data points, but when i upload it and print data file it shows only 190 data points,I have attached the data file,

### ISSUE THREAD

**Issue by nbillybgkv** [gimli-org/gimli#455]
i have .udf data file with 667 data points, but when i upload it and print data file it shows only 190 data points,I have attached the data file.
32 # Number of electrodes
# X Y Z
0.0737	0.0000	0.1530
0.0521	0.0521	0.1530
0.0000	0.0737	0.1530
-0.0521	0.0521	0.1530
-0.0737	0.0000	0.1530
-0.0521	-0.0521	0.1530
-0.0000	-0.0737	0.1530
0.0521	-0.0521	0.1530
0.0722	0.0000	0.1030
0.0511	0.0511	0.1030
0.0000	0.0722	0.1030
-0.0511	0.0511	0.1030
-0.0722	0.0000	0.1030
-0.0511	-0.0511	0.1030
-0.0000	-0.0722	0.1030
0.0511	-0.0511	0.1030
0.0707	0.0000	0.0530
0.0500	0.0500	0.0530
0.0000	0.0707	0.0530
-0.0500	0.0500	0.0530
-0.0707	0.0000	0.0530
-0.0500	-0.0500	0.0530
-0.0000	-0.0707	0.0530
0.0500	-0.0500	0.0530
0.0692	0.0000	0.0030
0.0489	0.0489	0.0030
0.0000	0.0692	0.0030
-0.0489	0.0489	0.0030
-0.0692	0.0000	0.0030
-0.0489	-0.0489	0.0030
-0.0000	-0.0692	0.0030
0.0489	-0.0489	0.0030
667 #Number of data
# A B M N R
2	1	3	4	726.0863
2	1	5	6	227.2035
2	1	4	5	274.4279
2	1	6	7	276.8524
2	1	7	8	645.7063
3	2	8	1	688.2991
3	2	6	7	182.8204
3	2	7	8	234.6704
3	2	5	6	280.9563
3	2	4	5	650.1766
4	3	1	2	724.8328
4	3	8	1	282.7567
4	3	7	8	196.8195
4	3	5	6	818.3123
4	3	6	7	261.7894
5	4	2	3	659.6601
5	4	1	2	272.3180
5	4	7	8	279.5074
5	4	8	1	210.8883
5	4	6	7	688.0737
6	5	3	4	805.7431
6	5	8	1	326.5076
6	5	2	3	273.0321
6	5	7	8	834.0438
6	5	1	2	217.3065
7	6	4	5	717.8232
7	6	1	2	271.3842
7	6	3	4	265.9411
7	6	8	1	813.7032
7	6	2	3	181.6991
8	7	1	2	669.0902
8	7	3	4	196.7029
8	7	2	3	236.3855
8	7	4	5	281.4503
8	7	5	6	857.3534
1	8	2	3	667.3057
1	8	4	5	208.3251
1	8	3	4	270.9782
1	8	5	6	307.5916
1	8	6	7	792.6632
2	1	3	4	508.5162
2	1	5	6	125.2015
2	1	4	5	163.6001
2	1	6	7	171.1232
2	1	7	8	518.5717
3	2	8	1	427.6534
3	2	6	7	115.1746
3	2	7	8	162.5963
3	2	5	6	154.2568
3	2	4	5	426.7807
4	3	1	2	508.5479
4	3	8	1	166.3898
4	3	7	8	132.6189
4	3	5	6	505.3396
4	3	6	7	176.8481
5	4	2	3	429.3226
5	4	1	2	161.0909
5	4	7	8	170.5892
5	4	8	1	112.8435
5	4	6	7	467.6198
6	5	3	4	499.0262
6	5	8	1	162.5969
6	5	2	3	154.0478
6	5	7	8	509.2116
6	5	1	2	122.4556
7	6	4	5	479.9858
7	6	1	2	166.0186
7	6	3	4	177.2675
7	6	8	1	450.1826
7	6	2	3	114.8509
8	7	1	2	528.9469
8	7	3	4	131.4368
8	7	2	3	163.7013
8	7	4	5	170.5858
8	7	5	6	518.4453
1	8	2	3	422.2740
1	8	4	5	112.9868
1	8	3	4	162.8794
1	8	5	6	157.1865
1	8	6	7	448.9347
2	1	3	4	472.9604
2	1	5	6	125.9616
2	1	4	5	174.1506
2	1	6	7	149.7999
2	1	7	8	468.5507
3	2	8	1	422.7274
3	2	6	7	105.3334
3	2	7	8	158.7637
3	2	5	6	151.4792
3	2	4	5	445.5109
4	3	1	2	472.8008
4	3	8	1	164.4134
4	3	7	8	125.2395
4	3	5	6	427.2825
4	3	6	7	154.8428
5	4	2	3	448.3291
5	4	1	2	172.2167
5	4	7	8	179.7078
5	4	8	1	118.0137
5	4	6	7	442.8138
6	5	3	4	427.0589
6	5	8	1	163.1104
6	5	2	3	154.1065
6	5	7	8	528.2669
6	5	1	2	126.7422
7	6	4	5	443.2368
7	6	1	2	145.7575
7	6	3	4	151.7808
7	6	8	1	371.3227
7	6	2	3	104.3321
8	7	1	2	469.4758
8	7	3	4	124.4889
8	7	2	3	156.1531
8	7	4	5	178.0158
8	7	5	6	519.7017
1	8	2	3	421.6169
1	8	4	5	115.5465
1	8	3	4	157.8164
1	8	5	6	153.6555
1	8	6	7	368.8226
2	1	3	4	866.0306
2	1	5	6	214.2057
2	1	4	5	304.7859
2	1	6	7	282.9107
2	1	7	8	852.2073
3	2	8	1	896.9552
3	2	6	7	185.5680
3	2	7	8	259.0851
3	2	5	6	288.9545
3	2	4	5	854.9449
4	3	1	2	845.1122
4	3	8	1	284.1229
4	3	7	8	184.5727
4	3	5	6	856.7166
4	3	6	7	259.6515
5	4	2	3	853.5138
5	4	1	2	301.4476
5	4	7	8	274.1344
5	4	8	1	212.4383
5	4	6	7	774.6500
6	5	3	4	848.1957
6	5	8	1	319.1553
6	5	2	3	288.7538
6	5	7	8	872.8863
6	5	1	2	214.5240
7	6	4	5	769.2239
7	6	1	2	280.3554
7	6	3	4	254.8254
7	6	8	1	937.7016
7	6	2	3	182.3680
8	7	1	2	841.4129
8	7	3	4	183.5581
8	7	2	3	259.2039
8	7	4	5	273.0324
8	7	5	6	859.3406
1	8	2	3	906.4141
1	8	4	5	209.6750
1	8	3	4	280.8896
1	8	5	6	311.6143
1	8	6	7	928.4278
1	1	2	2	1996.7530
1	1	3	3	856.1027
1	1	4	4	588.2102
1	1	5	5	577.1010
1	1	2	3	-1263.9390
1	1	3	4	-653.1019
1	1	4	5	-565.9842
1	1	6	5	-561.1897
1	1	7	6	-725.2181
1	1	6	6	617.2463
1	1	7	7	940.1119
1	1	8	8	2038.4752
1	1	8	7	-1356.1042
2	2	1	1	2008.7369
2	2	8	8	890.5890
2	2	7	7	673.5395
2	2	5	6	-597.9942
2	2	1	8	-1269.5280
2	2	8	7	-741.8493
2	2	7	6	-617.5435
2	2	3	3	2105.4264
2	2	4	4	887.4489
2	2	3	4	-1312.6020
2	2	4	5	-710.1478
2	2	5	5	669.5808
2	2	6	6	574.6677
3	3	2	2	2097.6191
3	3	1	1	860.3953
3	3	8	8	604.1889
3	3	6	7	-543.7802
3	3	2	1	-1286.7269
3	3	1	8	-674.1642
3	3	8	7	-588.7577
3	3	4	4	1888.1784
3	3	5	5	877.9839
3	3	4	5	-1199.8790
3	3	5	6	-659.8356
3	3	6	6	577.5683
3	3	7	7	573.5711
4	4	5	5	2085.6774
4	4	6	6	814.8944
4	4	5	6	-1241.6484
4	4	6	7	-637.5396
4	4	7	7	617.4302
4	4	8	8	533.2430
5	5	4	4	2099.9978
5	5	3	3	870.2670
5	5	2	2	656.7393
5	5	8	1	-579.2515
5	5	4	3	-1273.0114
5	5	3	2	-694.4954
5	5	2	1	-582.3644
5	5	6	6	2031.2592
5	5	7	7	951.4761
5	5	6	7	-1257.9649
5	5	7	8	-703.2772
5	5	8	8	638.5232
5	5	1	1	565.3249
6	6	5	5	2035.3506
6	6	4	4	831.5854
6	6	3	3	582.2492
6	6	1	2	-575.0337
6	6	5	4	-1253.4542
6	6	4	3	-654.7976
6	6	3	2	-565.1937
6	6	7	7	2233.9167
6	6	8	8	903.6383
6	6	7	8	-1320.6101
6	6	8	1	-663.2397
6	6	1	1	607.0984
6	6	2	2	564.9860
7	7	6	6	2260.4527
7	7	5	5	957.8822
7	7	4	4	634.5996
7	7	2	3	-609.4941
7	7	6	5	-1308.8014
7	7	5	4	-713.9319
7	7	4	3	-587.0429
7	7	8	8	2208.4638
7	7	1	1	927.4615
7	7	8	1	-1302.4490
7	7	1	2	-734.2705
7	7	2	2	671.4007
7	7	3	3	571.7492
8	8	1	1	1979.3451
8	8	2	2	876.6590
8	8	3	3	592.1142
8	8	4	4	533.5576
8	8	1	2	-1288.5824
8	8	2	3	-684.9071
8	8	3	4	-550.3236
8	8	5	4	-554.7956
8	8	6	5	-644.6095
8	8	5	5	635.4705
8	8	6	6	885.7835
8	8	7	7	2182.9843
8	8	7	6	-1293.7066
1	1	2	2	1484.9419
1	1	3	3	634.0931
1	1	4	4	422.3982
1	1	5	5	380.4408
1	1	2	3	-1091.8638
1	1	3	4	-531.2748
1	1	4	5	-392.8449
1	1	6	5	-386.7408
1	1	7	6	-522.0344
1	1	6	6	428.5972
1	1	7	7	588.7325
1	1	8	8	1540.7650
1	1	8	7	-1021.7659
2	2	1	1	1479.4662
2	2	8	8	606.0158
2	2	7	7	404.4132
2	2	5	6	-423.9478
2	2	1	8	-1042.2468
2	2	8	7	-492.5246
2	2	7	6	-413.1083
2	2	3	3	1591.7557
2	2	4	4	625.6165
2	2	3	4	-1085.0629
2	2	4	5	-516.5182
2	2	5	5	427.4460
2	2	6	6	386.0927
3	3	2	2	1594.3311
3	3	1	1	640.4709
3	3	8	8	427.6610
3	3	6	7	-380.5081
3	3	2	1	-1126.6385
3	3	1	8	-544.3680
3	3	8	7	-398.6528
3	3	4	4	1457.7123
3	3	5	5	605.4020
3	3	4	5	-1025.9119
3	3	5	6	-538.5062
3	3	6	6	428.6421
3	3	7	7	377.0440
4	4	3	3	1455.2885
4	4	2	2	630.2400
4	4	1	1	427.9479
4	4	7	8	-390.1488
4	4	3	2	-1046.4143
4	4	2	1	-550.8709
4	4	1	8	-410.4595
4	4	5	5	1458.5835
4	4	6	6	606.9026
4	4	5	6	-1028.3637
4	4	6	7	-473.7340
4	4	7	7	409.7111
4	4	8	8	371.6994
5	5	4	4	1461.0459
5	5	3	3	608.0536
5	5	2	2	433.5365
5	5	8	1	-393.3283
5	5	4	3	-971.8635
5	5	3	2	-499.9193
5	5	2	1	-412.1028
5	5	6	6	1461.1300
5	5	7	7	596.3546
5	5	6	7	-963.2179
5	5	7	8	-507.3869
5	5	8	8	406.0904
5	5	1	1	385.6446
6	6	5	5	1464.1742
6	6	4	4	604.5915
6	6	3	3	425.1161
6	6	1	2	-415.4863
6	6	5	4	-1039.1116
6	6	4	3	-498.6051
6	6	3	2	-384.9467
6	6	7	7	1562.8924
6	6	8	8	590.0303
6	6	7	8	-1105.5444
6	6	8	1	-516.9190
6	6	1	1	431.6946
6	6	2	2	388.9771
7	7	6	6	1552.9421
7	7	5	5	585.3925
7	7	4	4	399.2678
7	7	2	3	-399.7886
7	7	6	5	-1028.4416
7	7	5	4	-504.3105
7	7	4	3	-376.1631
7	7	8	8	1321.7520
7	7	1	1	581.9417
7	7	8	1	-911.9435
7	7	1	2	-485.7962
7	7	2	2	401.7815
7	7	3	3	365.1017
8	8	1	1	1539.8480
8	8	2	2	607.9419
8	8	3	3	419.2936
8	8	4	4	362.7021
8	8	1	2	-1040.8784
8	8	2	3	-534.3515
8	8	3	4	-395.3033
8	8	5	4	-385.7780
8	8	6	5	-462.5613
8	8	5	5	395.3829
8	8	6	6	579.3387
8	8	7	7	1315.8042
8	8	7	6	-925.9338
1	1	2	2	1647.4094
1	1	3	3	472.1870
1	1	5	5	194.3708
1	1	2	3	-1398.8731
1	1	3	4	-441.8255
1	1	4	5	-238.1769
1	1	4	4	253.5967
1	1	6	5	-241.6398
1	1	7	6	-440.5865
1	1	6	6	254.8859
1	1	7	7	459.2198
1	1	8	8	1618.6950
1	1	8	7	-1303.3680
2	2	1	1	1630.8361
2	2	8	8	433.0882
2	2	5	6	-242.9450
2	2	1	8	-1356.3283
2	2	8	7	-408.4941
2	2	7	6	-244.5706
2	2	7	7	234.5093
2	2	3	3	1709.5223
2	2	4	4	496.3637
2	2	3	4	-1359.5774
2	2	4	5	-431.7507
2	2	5	5	238.8968
2	2	6	6	206.0798
3	3	2	2	1702.7806
3	3	1	1	472.5927
3	3	6	7	-259.2974
3	3	2	1	-1392.2260
3	3	1	8	-464.5403
3	3	8	7	-262.2188
3	3	8	8	259.8964
3	3	4	4	1771.6634
3	3	5	5	482.1897
3	3	4	5	-1385.8467
3	3	5	6	-465.3968
3	3	6	6	273.0066
3	3	7	7	219.0589
4	4	3	3	1771.1322
4	4	2	2	497.6414
4	4	7	8	-251.5565
4	4	3	2	-1393.1102
4	4	2	1	-480.7308
4	4	1	8	-273.1144
4	4	1	1	255.5327
4	4	5	5	1596.4509
4	4	6	6	482.7515
4	4	5	6	-1346.6108
4	4	6	7	-431.1562
4	4	7	7	261.7814
4	4	8	8	220.0995
5	5	4	4	1593.3830
5	5	3	3	484.7242
5	5	8	1	-235.1575
5	5	4	3	-1300.7170
5	5	3	2	-430.4618
5	5	2	1	-249.0450
5	5	2	2	241.4237
5	5	6	6	1599.8326
5	5	7	7	475.0878
5	5	6	7	-1244.8981
5	5	7	8	-424.5869
5	5	8	8	254.1536
5	5	1	1	196.4537
6	6	5	5	1588.8741
6	6	4	4	476.1338
6	6	1	2	-247.8601
6	6	5	4	-1285.8868
6	6	4	3	-433.5168
6	6	3	2	-241.3532
6	6	3	3	269.3197
6	6	7	7	1820.7876
6	6	8	8	524.7166
6	6	7	8	-1414.4432
6	6	8	1	-474.0184
6	6	1	1	253.7410
6	6	2	2	205.3863
7	7	6	6	1814.1290
7	7	5	5	472.2405
7	7	2	3	-260.5118
7	7	6	5	-1396.5264
7	7	5	4	-444.4748
7	7	4	3	-244.7183
7	7	4	4	258.0173
7	7	8	8	1749.2536
7	7	1	1	456.1325
7	7	8	1	-1463.5289
7	7	1	2	-436.2028
7	7	2	2	234.6964
7	7	3	3	215.3655
8	8	1	1	1609.7223
8	8	2	2	435.2894
8	8	4	4	215.3275
8	8	1	2	-1297.6178
8	8	2	3	-431.1340
8	8	3	4	-253.2890
8	8	3	3	255.6799
8	8	5	4	-264.2631
8	8	6	5	-480.7769
8	8	5	5	249.1273
8	8	6	6	522.2561
8	8	7	7	1749.2276
8	8	7	6	-1497.8133
1	1	2	2	3953.3456
1	1	3	3	2303.6397
1	1	4	4	1769.9489
1	1	5	5	1696.7989
1	1	2	3	-2946.4284
1	1	3	4	-1975.4185
1	1	4	5	-1722.8478
1	1	6	5	-1725.1662
1	1	7	6	-2006.3975
1	1	6	6	1811.0203
1	1	7	7	2346.2683
1	1	8	8	3895.2670
1	1	8	7	-2977.1472
2	2	1	1	3712.4070
2	2	8	8	2126.0116
2	2	7	7	1710.2012
2	2	5	6	-1627.4766
2	2	1	8	-2731.2419
2	2	8	7	-1878.1468
2	2	7	6	-1619.7012
2	2	3	3	3878.2716
2	2	4	4	2192.7373
2	2	3	4	-2845.4152
2	2	4	5	-1911.2244
2	2	5	5	1738.2287
2	2	6	6	1585.1767
3	3	2	2	3914.5699
3	3	1	1	2152.0207
3	3	8	8	1648.7666
3	3	6	7	-1578.9574
3	3	2	1	-2808.8500
3	3	1	8	-1840.3747
3	3	8	7	-1608.6473
3	3	4	4	3698.5681
3	3	5	5	2152.6210
3	3	4	5	-2766.6218
3	3	5	6	-1820.8028
3	3	6	6	1634.7414
3	3	7	7	1564.5161
4	4	3	3	3866.9243
4	4	2	2	2320.3374
4	4	1	1	1745.0870
4	4	7	8	-1653.5311
4	4	3	2	-2909.7377
4	4	2	1	-1951.6760
4	4	1	8	-1677.0808
4	4	5	5	3929.4072
4	4	6	6	2190.0536
4	4	5	6	-2795.7933
4	4	6	7	-1904.0173
4	4	7	7	1770.4720
4	4	8	8	1611.2540
5	5	4	4	3815.9633
5	5	3	3	2155.6054
5	5	2	2	1728.9493
5	5	8	1	-1575.1873
5	5	4	3	-2711.4076
5	5	3	2	-1867.1673
5	5	2	1	-1604.8365
5	5	6	6	3806.4108
5	5	7	7	2220.3884
5	5	6	7	-2776.3233
5	5	7	8	-1854.3396
5	5	8	8	1671.1819
5	5	1	1	1551.9054
6	6	5	5	3799.5774
6	6	4	4	2090.5730
6	6	3	3	1635.2762
6	6	1	2	-1619.4205
6	6	5	4	-2711.0899
6	6	4	3	-1781.9535
6	6	3	2	-1586.2739
6	6	7	7	4094.4704
6	6	8	8	2187.2112
6	6	7	8	-2882.5361
6	6	8	1	-1815.2229
6	6	1	1	1669.8109
6	6	2	2	1575.0414
7	7	6	6	4093.9684
7	7	5	5	2221.9960
7	7	4	4	1657.0777
7	7	2	3	-1614.6727
7	7	6	5	-2873.9127
7	7	5	4	-1851.0497
7	7	4	3	-1577.5208
7	7	8	8	3831.1077
7	7	1	1	2158.4470
7	7	8	1	-2652.1088
7	7	1	2	-1865.0617
7	7	2	2	1711.2670
7	7	3	3	1550.3724
8	8	1	1	3679.6247
8	8	2	2	2111.8848
8	8	3	3	1617.4232
8	8	4	4	1479.4462
8	8	1	2	-2718.3104
8	8	2	3	-1808.8730
8	8	3	4	-1539.6991
1	1	2	2	3217.1839
1	1	3	3	1496.6940
1	1	4	4	1009.6384
1	1	5	5	877.9536
1	1	2	3	-2674.9518
1	1	3	4	-1329.7230
1	1	4	5	-963.0680
1	1	6	5	-958.9941
1	1	7	6	-1314.3788
1	1	6	6	1013.7597
1	1	7	7	1426.9908
1	1	8	8	3241.8060
1	1	8	7	-2548.1034
2	2	1	1	3206.6139
2	2	8	8	1424.7963
2	2	7	7	959.7496
2	2	5	6	-986.2358
2	2	1	8	-2627.0552
2	2	8	7	-1246.8209
2	2	7	6	-966.6311
2	2	3	3	3344.1120
2	2	4	4	1521.5251
2	2	3	4	-2677.6853
2	2	4	5	-1349.5591
2	2	5	5	1007.7143
2	2	6	6	906.7432
3	3	2	2	3342.0091
3	3	1	1	1507.0894
3	3	8	8	1015.3119
3	3	6	7	-968.7609
3	3	2	1	-2691.1058
3	3	1	8	-1342.9990
3	3	8	7	-961.7775
3	3	4	4	3280.9045
3	3	5	5	1504.2637
3	3	4	5	-2686.1924
3	3	5	6	-1368.4400
3	3	6	6	1043.1037
3	3	7	7	891.1792
4	4	3	3	3279.3102
4	4	2	2	1527.4400
4	4	1	1	1020.5614
4	4	7	8	-963.1030
4	4	3	2	-2682.1144
4	4	2	1	-1373.0186
4	4	1	8	-984.5122
4	4	5	5	3272.6724
4	4	6	6	1495.8073
4	4	5	6	-2652.1292
4	4	6	7	-1282.9482
4	4	7	7	994.3202
4	4	8	8	896.4750
5	5	4	4	3274.1315
5	5	3	3	1511.4924
5	5	2	2	1018.6178
5	5	8	1	-964.1044
5	5	4	3	-2609.0578
5	5	3	2	-1335.4778
5	5	2	1	-982.3492
5	5	6	6	3160.1486
5	5	7	7	1445.6764
5	5	6	7	-2480.5411
5	5	7	8	-1288.1982
5	5	8	8	991.9699
5	5	1	1	891.7149
6	6	5	5	3161.8566
6	6	4	4	1493.2691
6	6	3	3	1040.1826
6	6	1	2	-987.0923
6	6	5	4	-2538.8752
6	6	4	3	-1309.8484
6	6	3	2	-975.8512
6	6	7	7	3312.4097
6	6	8	8	1504.7317
6	6	7	8	-2652.9743
6	6	8	1	-1359.1995
6	6	1	1	1022.8254
6	6	2	2	909.8482
7	7	6	6	3319.1064
7	7	5	5	1434.8475
7	7	4	4	984.9404
7	7	2	3	-951.8298
7	7	6	5	-2627.1743
7	7	5	4	-1284.7195
7	7	4	3	-942.0945
7	7	8	8	3250.6874
7	7	1	1	1435.7854
7	7	8	1	-2671.0884
7	7	1	2	-1270.7700
7	7	2	2	960.4781
7	7	3	3	884.0578
8	8	1	1	3250.0846
8	8	2	2	1429.1919
8	8	3	3	1006.8667
8	8	4	4	885.0969
8	8	1	2	-2563.7810
8	8	2	3	-1292.4065
8	8	3	4	-960.3733
8	8	5	4	-957.5749
8	8	6	5	-1324.3319
8	8	5	5	978.1002
8	8	6	6	1501.5010
8	8	7	7	3248.4627
8	8	7	6	-2702.1140
filename = 'task1.udf' 
data = pg.DataContainerERT(filename)
print(data)
Data: Sensors: 32 data: 190, nonzero entries: ['a', 'b', 'm', 'n', 'r', 'valid']

**Comment by halbmy** [comment]
There is clearly something wrong with the file from a certain point on:
```
1 1 2 2 1996.7530
1 1 3 3 856.1027
1 1 4 4 588.2102
1 1 5 5 577.1010
1 1 2 3 -1263.9390
```
Here A and B are identical just like M and N. These data are invalid and removed on loading.

**Comment by nbillybgkv** [comment]
Thank you.its solved now.
