### ISSUE TITLE
Abnormality and removed value in ERT structural constraint inversion.

### ISSUE THREAD

**Issue by 728236958** [gimli-org/gimli#457]
### Problem description
Hello, I tried an inversion example based on structural constraints,  and the questions are as follows：

 I wonder know what the white null value in ERT inversion means?
![image](https://user-images.githubusercontent.com/69100178/198970282-a4833083-20f7-420f-b797-7905ff4a6d3b.png)

Sorry for asking so many questions, but I'm still a layman in this field. Thank you very much for your advice！

**Comment by halbmy** [comment]
The alpha shading is defined by the model coverage (sum of absolute sensitivite values) and shows regions of poorer resolution. In your case in the middle of the area and in high resistivity.

**Comment by halbmy** [comment]
Whereas coverage shading is mostly helpful for surface arrays, it does probably make less sense for crosshole geometries. You can turn it off by `xx.showYYY(coverage=1)`.

**Comment by halbmy** [comment]
As your *problem* does not have to do anything with abnormality, removed value or structural constraints, can you please change the title or elaborate further?

**Comment by 728236958** [comment]
Thank you very much for your reply. When retrieving other questions, we have solved the above problem,  closed this issue.
