### ISSUE TITLE
`shotReceiverDistances` is not crosshole compatible

### ISSUE THREAD

**Issue by florian-wagner** [gimli-org/gimli#460]
Should use shot and receiver coordinates rather than sensor numbers.

**Comment by halbmy** [comment]
`shotReceiverDistances(data)` always uses coordinates and not numbers. Furthermore, it has a keyword argument `full` (currently False by default) that works also for crosshole geometries. I see no reason why it should not be True by default, so I will change and check.

**Comment by halbmy** [comment]
the default is now `full=True` and it seems to make no difference in the covered examples, e.g. http://dev.pygimli.org/_examples_auto/2_seismics/plot_04_koenigsee.html.

However, there was a bug in `traveltime.drawVA` always taking x coordinates, which is now corrected. One should use `usePos=False` for show/drawVA in case of crosshole geometry. See example http://dev.pygimli.org/_examples_auto/2_seismics/plot_02_crosshole_tomography.html

Actually this argument should be deduced by the manager or by `traveltime.show`.
