### ISSUE TITLE
in pygimli/frameworks/methodManager.py, line 769 in the current version: Pass along **kwargs to self.setMesh(mesh)

### ISSUE THREAD

**Issue by AlainPlattner** [gimli-org/gimli#467]
### Problem description

When setting regularization for specific regions, these regularizations get overwritten by the methodManager, when it sets the mesh.

In pygimli/frameworks/methodManager.py on line 769 in the current version, if you replace

`self.setMesh(mesh)`
with
`self.setMesh(mesh, **kwargs)` 

then it is possible to keep the region-specific regularizations set with, e.g. `fop.setRegionProperties(3,fix=80)`, by passing ` ignoreRegionManager=True` to the inversion call.

There may be other places, where it could be useful to pass the **kwargs along to setMesh, because you so wonderfully implemented the `ignoreRegionManager` flag that is used by applyMesh.

I could have created a pull request instead, but it is really just a single line to edit.

Please let me know if this is confusing. It's late Friday night and I rushed a bit writing this to get some more calculations done.

Cheers, 
Alain
amplattner@ua.edu

**Comment by AlainPlattner** [comment]
Actually, I noticed that providing `ignoreRegionManager=True` will prevent the `blockyModel` and `robustData` flags to be accepted.

I now additionally propose for line 768 to change from:
`if mesh is not None:`
to
`if mesh is not None and kwargs.pop('keepRegionRegularization') is False:`
and keep the passing on of the `**kwargs` from the previous comment. So I propose a new flag that avoids overwriting of the region regularization (such as e.g. fixing a region to a value), but still allows other regularization to work.

**Comment by carsten-forty2** [comment]
Hi Alain,

we can make these changes but keep in mind potential weird side effects. The current implementation of the `RegionManager` (we plan a complete overhaul) needs to be in sync with the associated mesh. I you set a new mesh with a different amount of cells or regions or even with a different internal order of numbering, then all stored regularizations aren't valid anymore. In the best case this will lead to segmentation faults of the core, or even worse would be unnoticed completely wrong calculation results. 

The 'ignoreRegionManager' flag is intented to use with care if you know what you do ;). However, the idea of storing the regularization settings in a dictionary was to minimize the needed coding without loosing 'control' on the RegionManager. Most of the time we implement for our needs while we try to anticipate what might be useful for others or be useful for more generalized cases. Maybe you can coarsely sketch what you want to achieve and how you approach it so far. Maybe we find an easy and safer way.

'blockyModel' and 'robustData' aren't directly related to the mesh or the 'RegionManager'  but to the generalized inversion framework. If you give a sketch how you use or call them, I will check what we missed to implement.

Cheers,
Carsten

**Comment by AlainPlattner** [comment]
Hi Carsten,

You are right, I think the changes I propose are a bit dangerous. The reason why I proposed them was because I couldn't figure our how to set the region-specific regularizations using a dictionary. Do you have an example of how to set up the dictionary of regularizations and how to pass it on to the inversion call?

Thanks and all the best, 
Alain

**Comment by halbmy** [comment]
Have a look at the Transform 2022 tutorials: https://github.com/gimli-org/transform2022

**Comment by carsten-forty2** [comment]
True, the inversion instance itself could ask the fop for the mandatory data and error values. However, we would like to keep the inversion framework itself more clean and solely focused on the inversion job. Its the idea behind the method managers to provide some convenience, e.g.:

```
mgr = ERTManager()
mgr.setMesh(mesh)
mgr.fop.setRegionProperties(3, fix=80)
mgr.invert(data)
```



Seems all questions are answered so we can close this issue.
