### ISSUE TITLE
Ratio inversion

### ISSUE THREAD

**Issue by Abby123455r** [gimli-org/gimli#468]
### Ratio inversion

Hi, i am new in gimli platform. and working on ration inversion, am i using the right strategy. i did not find any variation between simple inversion and ratio inversion for data2.

```
data = ert.load ("lr00034.DAT")
print(data)
data["k"] = ert.geometricFactors(data)
data["err"] = ert.estimateError(data, relativeError=0.02, absoluteUError=50e-6)
ert.show(data, data["err"]*100, label="error (%)");
mgr = ert.ERTManager(data, verbose=True)
d= mgr.invert(paraDepth=30, quality=34.6, paraMaxCellSize=100)

previous_rho = np.array(mgr.model)

data2 = ert.load("lr00035.DAT")
print(data2)
data2["k"] = ert.geometricFactors(data2)
data2["err"] = ert.estimateError(data2, relativeError=0.02, absoluteUError=50e-6)
ert.show(data2, data2["err"]*100, label="error (%)");
mgr = ert.ERTManager(data2, verbose=True)
e= mgr.invert(paraDepth=30, quality=34.6,startModel=previous_rho, paraMaxCellSize=100)
mgr.showResult();
```

**Comment by Abby123455r** [comment]
Thankyou for your reply,what i understand is that to invert the baseline i need to add,
Step1:
baseline= mgr.invert(data, isReference=True,paraDepth=30, quality=34.6, paraMaxCellSize=100).
Step2:
Then after inverting the baseline,i need to invert the Time1 like,

Time1= mgr.invert (data1, startModel=baseline, paraDepth=30, quality=34.6, paraMaxCellSize=100) 
Step3:
Further i am not sure i can i plot the ratio of two models,
it would be nice if you guied me.

**Comment by halbmy** [comment]
No, the other way round: The baseline inversion is done without any starting model (or rather a constant one) and therefore NOT with `isReference`. But the timestep inversion is done with `isReference=True`;
```
baseline= mgr.invert(data, paraDepth=30, quality=34.6, paraMaxCellSize=100)
timestep1= mgr.invert (data1, startModel=baseline, isReference=True)
ratio = timestep1 / baseline * 100 - 100
mgr.showResult(ratio)
```

**Comment by Abby123455r** [comment]
Thankyou. I got the final image like this.is it possible to chnage the scale?
how can save the results of ratio in .vtk file.
Thankyou
![image](https://user-images.githubusercontent.com/119299976/204516114-5a86fb6f-0c21-4f4a-be0a-632c1a06000e.png)

**Comment by halbmy** [comment]
Actually the ratio is just `ratio = timestep1 / baseline`.

Maybe it is better to use `pg.show` directly to avoid the strange coverage map:
```
pg.show(mgr.paraDomain, ratio, cMin=0.5, cMax=2, cMap="bwr", logScale=True)
```

You can use the usual commands for any show/draw command: cMin, cMax, colorBar, logScale, cMap,

**Comment by Abby123455r** [comment]
Thank you. if we have a 3d case and after ratio inversion,how can we save the results of ratio in .vtk file for better visualization?
as for independent inversion we use mgr.saveResult() to get .vtk file.

**Comment by Abby123455r** [comment]
Thankyou. 
For ratio inversion, i inverted the time1 as baseline and then inverted the same time1 as timestep1.and calculate the ratio,
I was expecting that value of ratio=1 for the final section,but it is not 1 in my case.
![image](https://user-images.githubusercontent.com/119299976/206479949-773d4ab1-bc99-42c7-96d9-1d7f59d683d6.png)

**Comment by halbmy** [comment]
This is the same as inverting data from a homogeneous halfspace where a normal regularization parameter produces far too many artifacts. You could try that with a high lam value and it will of course fit the data and have constant ratio of 1.

**Comment by Abby123455r** [comment]
Thank you for your reply.The results are satisfactory

 For time-lapse inversion (difference) all the process will be same except
difference=timestep1-baseline.
or we have to do some thing else as well?

**Comment by Abby123455r** [comment]
thankyou. i am just asking for ratio inversion we use the formula as 
ratio = timestep1 / baseline.
if we want to perform the difference inversion then will we use the formula as'
difference=timestep1-baseline
and to see the percentage difference 
Percentage difference = (timestep1-baseline/baseline)*100

**Comment by halbmy** [comment]
The very general (and method-independent) term *difference inversion* after LaBrecque&Yang (2001) means to fit the data difference. If the data are the logarithms of the apparent resistivity, the difference (between baseline and timestep) of the log rhoa equals the log of the ratio of the two rhoa. The same holds for the model, where the difference of the log resistivity is regularized, which is the log of the ratio. The latter holds also for a standard reference-based inversion. The only difference is that the data are "corrected" by the misfit of the baseline, i.e. in log sense multiplied by the ratio of forward response and baseline data.

I will create an example where all the necessary definitions are written down.

**Comment by Abby123455r** [comment]
Thank you so much.i am new here in pygimli, but because of your response my learning graph is moving upward. once again thank you so much

**Comment by halbmy** [comment]
You're welcome
