### ISSUE TITLE
Question about ERT coverage and Jacobian with the mesh size [Question]

### ISSUE THREAD

**Issue by geohang** [gimli-org/gimli#470]
### Problem description

I am trying to invert the ERT data using the Pygimili ERT forward modeling. I add the structure boundary to the inverted mesh and the mesh size near the boundary is very small, thus the Jacobian value near these meshes is also very small (like the figure below (log Jacobian)).
![image](https://user-images.githubusercontent.com/75149424/205557548-b87b9a42-3d80-47b0-a49a-4db5e3b86ff3.png)
and I got an inverted resistivity model like this one
![image](https://user-images.githubusercontent.com/75149424/205557633-4b909d41-6a2a-4834-9f25-a47373af295b.png)

It seems the resistivity value around the boundary is not changed and I am thinking it may be due to the small Jacobian value. Then I check the calculation of coverage in Pygimili, it seems the sensitivity is normalized by the mesh size. 
![image](https://user-images.githubusercontent.com/75149424/205557912-1b1a5953-479c-4776-8e33-c88816ba955f.png)

I don't know if I use the Jacobian in my own inversion, do I need to normalize it by mesh size? Since I check the example of  Naive complex-valued electrical inversion (https://www.pygimli.org/_examples_auto/3_dc_and_ip/plot_07_simple_complex_inversion.html#sphx-glr-examples-auto-3-dc-and-ip-plot-07-simple-complex-inversion-py), in this one, the Jocabian value is not normalized by mesh size and is used in inversion directly. 
![image](https://user-images.githubusercontent.com/75149424/205558558-017f0327-e6cf-4ce1-a9d8-f1436fc5bb1c.png)

 

### Your environment

**Operating system**:  Windows
**Python version**: 3.8
**pyGIMLi version**: 1.2.6
**Way of installation**:  Conda package

### Steps to reproduce

As in the question description

### Expected behavior

The boundary resistivity value should be changed.

### Actual behavior

![image](https://user-images.githubusercontent.com/75149424/205558825-3de74856-5ccf-49e0-b8d1-d9fd7c51c60b.png)

```
Paste output here.
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
The Jacobian matrix itself is, as it is being used in inversion, NOT scaled by mesh size. However, if people visualize the coverage as a cheap measure for overall sensitivity (e.g. depth penetration) and resolution properties, this should be independent on the discretization. That's why we normalize it.

Indee it is strange that you have large gradients in the area of the structural constraints but not directly at the boundary itself. Which regularization scheme do you use? If it was second order, it would make perfect sense to me. Can you paste your inversion script?

**Comment by geohang** [comment]
> The Jacobian matrix itself is, as it is being used in inversion, NOT scaled by mesh size. However, if people visualize the coverage as a cheap measure for overall sensitivity (e.g. depth penetration) and resolution properties, this should be independent on the discretization. That's why we normalize it.
> 
> Indee it is strange that you have large gradients in the area of the structural constraints but not directly at the boundary itself. Which regularization scheme do you use? If it was second order, it would make perfect sense to me. Can you paste your inversion script?

Thank you so much! That's the regularization that leads to this problem! Thank you!
