### ISSUE TITLE
IndexError   

### ISSUE THREAD

**Issue by Abby123455r** [gimli-org/gimli#472]
I am practcing some solved exemples from transformation 2022.but when i try to plot the data by using command.
```
plt.plot(pg.x(data), pg.z(data), "x-")
plt.grid();
```

it gives the error:
tuple index out of range

**Comment by halbmy** [comment]
You're talking about https://github.com/gimli-org/transform2022/blob/main/2_Lake.ipynb ?

Note that this example is now available as tutorial on pygimli.org: https://www.pygimli.org/_tutorials_auto/3_inversion/plot_8-regionWise.html

**Comment by halbmy** [comment]
I have rerun them with the fresh pyGIMLi 1.3.1 and pushed my notebooks to https://github.com/gimli-org/transform2022

**Comment by Abby123455r** [comment]
Yes reading of data is successful, i am using 1.2.6

**Comment by halbmy** [comment]
Can you please paste the complete code (maybe of the original Lake example) up to the point where it crashes and the complete output?

**Comment by Abby123455r** [comment]
import matplotlib.pyplot as plt
plt.style.use("seaborn-notebook")
%config InlineBackend.figure_format='svg' # Setting figure format for this notebook
import numpy as np
import pygimli as pg
from pygimli.physics import ert
print(pg.__version__)
import pygimli as pg
from pygimli.physics import ert
import pygimli.meshtools as mt

data = ert.load("lake.ohm")
print(data)
Data: Sensors: 48 data: 658, nonzero entries: ['a', 'b', 'err', 'i', 'm', 'n', 'r', 'u', 'valid']

pg.plt.plot(pg.x(data), pg.z(data), "o-")
pg.plt.grid();
output:
IndexError                                Traceback (most recent call last)
Input In [29], in <cell line: 1>()
----> 1 pg.plt.plot(pg.x(data), pg.z(data), "o-")
      2 pg.plt.grid()

File C:\ProgramData\Anaconda3\envs\Conda_environments\lib\site-packages\matplotlib\pyplot.py:2769, in plot(scalex, scaley, data, *args, **kwargs)
   2767 @_copy_docstring_and_deprecators(Axes.plot)
   2768 def plot(*args, scalex=True, scaley=True, data=None, **kwargs):
-> 2769     return gca().plot(
   2770         *args, scalex=scalex, scaley=scaley,
   2771         **({"data": data} if data is not None else {}), **kwargs)

File C:\ProgramData\Anaconda3\envs\Conda_environments\lib\site-packages\matplotlib\axes\_axes.py:1632, in Axes.plot(self, scalex, scaley, data, *args, **kwargs)
   1390 """
   1391 Plot y versus x as lines and/or markers.
   1392 
   (...)
   1629 (``'green'``) or hex strings (``'#008000'``).
   1630 """
   1631 kwargs = cbook.normalize_kwargs(kwargs, mlines.Line2D)
-> 1632 lines = [*self._get_lines(*args, data=data, **kwargs)]
   1633 for line in lines:
   1634     self.add_line(line)

File C:\ProgramData\Anaconda3\envs\Conda_environments\lib\site-packages\matplotlib\axes\_base.py:312, in _process_plot_var_args.__call__(self, data, *args, **kwargs)
    310     this += args[0],
    311     args = args[1:]
--> 312 yield from self._plot_args(this, kwargs)

File C:\ProgramData\Anaconda3\envs\Conda_environments\lib\site-packages\matplotlib\axes\_base.py:514, in _process_plot_var_args._plot_args(self, tup, kwargs, return_kwargs)
    511     kw['closed'] = kwargs.get('closed', True)
    512     make_artist = self._makefill
--> 514 ncx, ncy = x.shape[1], y.shape[1]
    515 if ncx > 1 and ncy > 1 and ncx != ncy:
    516     raise ValueError(f"x has {ncx} columns but y has {ncy} columns")

IndexError: tuple index out of range

<Figure size 576x396 with 1 Axes>

I obseved that during youtube streaming of [Transform 2022 pygimli] at 1 hr 22 min, they also show some error.
https://www.youtube.com/watch?v=2Hu4gDnRzlU&t=4976s

**Comment by halbmy** [comment]
Interesting! This is rather a matplotlib or numpy array problem, I have in mind that we have fixed something.

Which mpl and numpy versions do you have?

Can you try update to the recent version v1.3.1 and see whether the problem persists?

**Comment by Abby123455r** [comment]
I updated the pygimli.now it is working fine.thank you.
and kindly also include the import scipy in exemple.
