### ISSUE TITLE
why not supporting python without conda

### ISSUE THREAD

**Issue by BaderTalal** [gimli-org/gimli#474]
### Problem description
I am  trying to use pygimli with python4delphi, I would like to use python directly without Conda, anaconda or Maniconda

thanks

**Comment by carsten-forty2** [comment]
Sorry but we are not familiar with python4delphi and thus can't provide support for it. Since we know nothing about python4delphi, we can't say if a manual installation of pygimli (https://www.pygimli.org/compilation.html#sec-build) might help or not.

**Comment by BaderTalal** [comment]
I am sorry for not being clear with my question, my main question why not supporting python directly without conda ? 
in all cases, thank you for the great work you did with pygimli and I hope I can find away not to be forced to use Conda or anaconds.
I will have a look at the link you provided. 
thanks again .
regards

**Comment by halbmy** [comment]
As Carsten already commented, you can build (i.e. compile the C++ sources) pyGIMLi against your own Python as described in the link above.
