### ISSUE TITLE
Inversion - stopAtChi1-Flag not working

### ISSUE THREAD

**Issue by TheNablaOperator** [gimli-org/gimli#479]
### Problem description

When I run the Inversion and don't want to stop at Chi²=1 I set the flag `stopAtchi1=False` as described in the Manual.
But it is ignored... Reason is, that I already have a Chi<1, but the dPhi is still high. I guess that the result is getting better after some iterations....

Thanks in advance.

### Your environment

**Operating system**: Win10
**pyGIMLi version**: 1.3.1
**Way of installation**: conda

### Steps to reproduce

```python
mgr2 = ert.ERTManager()
mgr2.invert(data=het, mesh=mesh2, verbose=True, lam=20, zWeight=0.5, paraMaxCellSize=1, stopAtChi1=False); #**inv_kw)
mgr2.showResult(**print_kw, xlabel="x in m", ylabel="z in m")
```

### Expected behavior

Ignore Chi²=1 limit and perform inverion until dPhi or maxIter is reached.

### Actual behavior

Stop inversion, since Chi² <= 1.

```
11/01/23 - 13:22:43 - pyGIMLi - INFO - Found 2 regions.
11/01/23 - 13:22:43 - pyGIMLi - INFO - Region with smallest marker (1) set to background
11/01/23 - 13:22:43 - pyGIMLi - INFO - Creating forward mesh from region infos.
11/01/23 - 13:22:43 - pyGIMLi - INFO - Creating refined mesh (P2) to solve forward task.
11/01/23 - 13:22:44 - pyGIMLi - INFO - Use median(data values)=95.2794182514416
11/01/23 - 13:22:44 - pyGIMLi - INFO - Created startmodel from forward operator: 4103 [95.2794182514416,...,95.2794182514416]
11/01/23 - 13:22:44 - pyGIMLi - INFO - Starting inversion.

fop: <pygimli.physics.ert.ertModelling.ERTModelling object at 0x00000266B07158B0>
Data transformation: <pgcore._pygimli_.RTransLogLU object at 0x00000266A01D9D30>
Model transformation (cumulative):
	 0 <pgcore._pygimli_.RTransLogLU object at 0x00000266B45A51C0>
min/max (data): 58.04/113
min/max (error): 3.01%/3.07%
min/max (start model): 95.28/95.28
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
inv.iter 2 ... chi² = 0.28 (dPhi = 26.88%) lam: 20


################################################################################
#                  Abort criterion reached: chi² <= 1 (0.28)                   #
################################################################################

```

**Comment by halbmy** [comment]
You're right, `stopAtChi1` was not yet passed from the managers to the inversion instances
```
mgr2.fw._stopAtChi1 = kwargs["stopAtChi1"]
```

I made a change (#41dc7de) so that it can be passed to both `mgr.inver()` and any (manager-less) `inv.run()`

**Comment by halbmy** [comment]
In the meanwhile you can use
```
mgr2 = ert.ERTManager()
mgr2.fw._stopChi1 = False
mgr2.invert(data=het, mesh=mesh2, verbose=True, lam=20, zWeight=0.5, paraMaxCellSize=1, stopAtChi1=False); #**inv_kw)
mgr2.showResult(**print_kw, xlabel="x in m", ylabel="z in m")
```

**Comment by TheNablaOperator** [comment]
Is it possible that also for the `VESManager` the `stopAtChi1`-Flag is not passed?

When I run: 
``` Python
mgr1 = VESManager();
ves1 = mgr1.invert(wenner1["rhoa"], wenner1["err"], ab2=wenner1["ab2"], 
                              mn2=wenner1["mn2"], nLayers=2, showProgress=1, 
                              verbose=1, stopAtChi1=1)
```
the inversion stops at Chi=95 and dPhi=0,08%

Pg-Version: 1.4.3

Thanks in advance

**Comment by halbmy** [comment]
`stopAtChi1` is True by default and means that the inversion stops once the chi-square value goes below 1. It can't be turned off to see whether the data can be much better fitted (probably the error model was too pessimistic).

Besides chi-square, there are two other criteria
* maximum iteration number (`maxIter`) reached (by default 20)
* improvement of objective function Phi is below 1%, i.e. stagnation

The latter was it in your case. Please check whether your error model makes sense.

**Comment by halbmy** [comment]
If the ERT data can be fitted with the same error it can only be 2D effects that prevent a better convergence. Hard to speculate without having a look at the data. Maybe you can show the data-and-fit image?

**Comment by TheNablaOperator** [comment]
Thanks for your reply. I tried some things... The high value of the chi^2 is due to the unsorted ERT-data which I used for VES inversion. If I sort the data in a VES manner, chi^2=12...

**Comment by halbmy** [comment]
Sorting the data should of course not make any difference. If you measured a 2D Wenner profile I can imagine that you cannot easily fit all the data by a 2-layer model. You should display data, model response and misfit using `ert.show`.

**Comment by TheNablaOperator** [comment]
hmmm. Yes I know that it would be hard to fit the model, since there are changes in the direction of the survey line in resistivity. However, I tried some different things with the data... ERT vs. VES and so on.

Unsorted Apparent resistivity (directly from the ERT data):
![grafik](https://github.com/gimli-org/gimli/assets/62592621/ea4f504f-bfd9-492f-a471-5fed3a3e5d83)

Sorted ERT data:
![grafik](https://github.com/gimli-org/gimli/assets/62592621/291fe77e-9117-4785-a757-626cc3e1862e)

Thanks!

**Comment by halbmy** [comment]
Sorting the order of the data should not change the dots but only the lines between them. To me it looks like you took the lowest 16 apparent for the lowest AB/2 and so on but this does not reflect the measurements (but can be fitted as the curve is smoother). I suggest extracting a single sounding only for a limited midpoint.
