### ISSUE TITLE
Can i process GPR using pyGIMLi?

### ISSUE THREAD

**Issue by JabOussama** [gimli-org/gimli#480]
### Problem description

I have some GPR files and i want to do the processing with pyGIMLi, is there any example existing to help during the process?
the files have (.RAD) or (.RD3) format.
Thanks

**Comment by halbmy** [comment]
pyGIMLi is not suited for processing GPR data, i.e. recorded traces. The only thing you can do is first-arrival traveltime tomography, e.g. in crosshole geometry. This works exactly like in the examples on seismic tomography.
