### ISSUE TITLE
Comparing ERT inversion results using pyGIMLi/BERT

### ISSUE THREAD

**Issue by JabOussama** [gimli-org/gimli#484]
Hello
I am working on synthetic models for ERT inversion using pyGIMLi and BERT and the inversion results using the different tools give different results even with the same inversion parameters, is it normal?
Thank you

BERT exemple code: 
```
import pybert as pb
import pygimli as pg
import pygimli.meshtools as mt  
left = -48
right = 48
depth = 25 
world = mt.createWorld(start=[left, 0], 
                    end=[right, -depth], 
                    layers=[-3])

line = mt.createLine(start=[left, -3], end=[right, -25])

block = mt.createCircle(pos=[30, -13.], radius=[6, 1.3], marker=3,
                        boundaryMarker=10, area=0.1, interpolate="spline")

geometry = world + line + block
pg.show(geometry);
```

pyGIMLi exemple code:
```
import matplotlib.pyplot as plt
import numpy as np

import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import ert
world = mt.createWorld(start=[-48, 0], end=[48, -20],
                       worldMarker=True)
block  = mt.createCircle(pos=[-30, -10.], radius=[4, 4], marker=2, boundaryMarker=10,
                        area=0.1)
blockc = mt.createCircle(pos=[30, -10.], radius=[4, 4], marker=3, boundaryMarker=10,
                        area=0.1)
geom = mt.mergePLC([world, block , blockc])
pg.show(geom)
scheme = ert.createData(elecs=np.linspace(start=-48, stop=48, num=48),
                           schemeName='dd')
for p in scheme.sensors():
    geom.createNode(p)
    geom.createNode(p - [0, 0.1])

mesh = mt.createMesh(geom, quality=34)
rhomap = [[1, 50.],
          [2, 10.],
          [3, 100.],]
pg.show(mesh, data=rhomap, label=pg.unit('res'), showMesh=True)
data = ert.simulate(mesh, scheme=scheme, res=rhomap, noiseLevel=1,
                    noiseAbs=1e-6, seed=1337)

pg.info(np.linalg.norm(data['err']), np.linalg.norm(data['rhoa']))
pg.info('Simulated data', data)
pg.info('The data contains:', data.dataMap().keys())

pg.info('Simulated rhoa (min/max)', min(data['rhoa']), max(data['rhoa']))
pg.info('Selected data noise %(min/max)', min(data['err'])*100, max(data['err'])*100)
pg.show(data)
data.remove(data['rhoa'] < 0)
pg.info('Filtered rhoa (min/max)', min(data['rhoa']), max(data['rhoa']))
data.save('simple.dat')
ert.show(data)
mgr.showResult(cMin=15, cMax=100, xlabel="x (m)", ylabel="z (m)");
mgr.showFit()
```

**Comment by halbmy** [comment]
I don't quite understand, your anomalies in the two codes are different, so of course any results will be likewise.
Furthermore, I don't understand what you mean with BERT code as pybert is not used at all. 
The first code is just a geometry definition. Please make your point clear.

**Comment by JabOussama** [comment]
Sorry for the misunderstanding, i mean i do proceed with inversion for the same geometry using a BERT code and pyGIMLi code with the same parameters and the results are different. It was just an example.

**Comment by JabOussama** [comment]
This is BERT code:


import pybert as pb
import pygimli as pg
import pygimli.meshtools as mt

world = mt.createWorld(start=[-48, 0], end=[48, -20],
                       worldMarker=True)
circleL  = mt.createCircle(pos=[-30, -10.], radius=[4, 4], marker=2, boundaryMarker=10,
                        area=0.1)
circleH = mt.createCircle(pos=[30, -10.], radius=[4, 4], marker=3, boundaryMarker=10,
                        area=0.1)
geom = mt.mergePLC([world, circleL , circleH])
pg.show(geom)

scheme = pb.createData(elecs=pg.utils.grange(start=-48, end=48, n=48),
                       schemeName='dd')

for pos in scheme.sensorPositions():
    geom.createNode(pos)
    geom.createNode(pos + pg.RVector3(0, -0.1))
mesh = mt.createMesh(geom, quality = 33.5, area= 1, smooth=True)
pg.show(mesh);
rhomap = [[1, 50.],
          [2, 10.],
          [3, 100.],]
pg.show(mesh, data=rhomap, label='Resistivity $(\Omega$m)', showMesh=True)
ert = pb.ERTManager()
data = ert.simulate(mesh, res=rhomap, scheme=scheme, noiseLevel=1,
                    noiseAbs=1e-6)
print('Simulated rhoa', data('rhoa'), max(data('rhoa')))
data.markInvalid(data('rhoa') < 0)
print('Filtered rhoa', data('rhoa'), max(data('rhoa')))
data.removeInvalid()
data.save('simple.dat')
pb.show(data)
model = ert.invert(data, paraDepth=25, lam=2, paraMaxCellSize=2,
paraBoundary=0, verbose=True)
ert.showResult()
ert.showResultAndFit()

**Comment by halbmy** [comment]
The `pybert` code is outdated as it was all moved to the `pygimli.physics.ert` module. Differences can be in changed default values, e.g. for the mesh discretization. Don't use `pybert` for standard ERT inversion anymore.

**Comment by JabOussama** [comment]
Ok, thanks for clarifying, because i wanted to compare the results from the two packages, but now as you answered there is only one module.

**Comment by JabOussama** [comment]
The BERT code was based on this code :
http://resistivity.net/bert/_examples/plot_2D_simple.html#sphx-glr-examples-plot-2d-simple-py
is it still ok to process inversion for the geometry and compare it with pyGIMLi package or not?

**Comment by halbmy** [comment]
This documentation is really outdated and needs to be removed. Just rely on pyGIMLi.
