### ISSUE TITLE
extract resistivity 

### ISSUE THREAD

**Issue by Abby123455r** [gimli-org/gimli#486]
After inversion i save the results by using the command mgr.saveResults(). and saves the results (mesh, resistivity, vtk) in a folder.Is it possible to extract the true resistivity values for the exact combination define in input file. for example
A       b      m      n    Resistivity     True resistivity
30	32	20	14      231                  ?
30    32    24     18      204                 ?
............

**Comment by halbmy** [comment]
You are clearly mixing up data and model space.

The quadrupoles, A B M N, define the data space, and are associated to current, voltage, apparent resistivity, geometric factor and error estimates. The data space is NOT model-related.

On the other hand, the subsurface (we never know the true) resistivity, is the result of the inversion and defines its distribution in the subsurface, so it is related to positions like x and y (and/or z).  This model space is not related to the data space like ABMN.

**Comment by Abby123455r** [comment]
Got it..Thankyou.
