### ISSUE TITLE
Seismic tomography: filter data by apparent velocity [QUESTION]

### ISSUE THREAD

**Issue by kerim371** [gimli-org/gimli#488]
### Problem description

Hi,

I'm trying to calculate seismic tomography based on first arrivals.
It seems that some points are inaccurate picked and the apparent velocity max val is about 31000 m/s.
I'm wondering is there a way to somehow filter picks where apparent velocity is above say 10000 m/s?
Because of such large apparent velocity the calculated model has depth about 7000 m, instead of about 500 m.

Apparent velocity:
![image](https://user-images.githubusercontent.com/43808863/217764846-ccf46f3d-c48a-4406-9caa-0a704bd6b606.png)

Inversion result:
![image](https://user-images.githubusercontent.com/43808863/217765038-36bc63ee-0719-41ad-990c-c9fbef758c55.png)

**Operating system**: Linux, Ubuntu 20.04
**Python version**: 3.9

**Comment by halbmy** [comment]
Nothing easier than that 
```
offset = shotReceiverDistances(data)
vApp = offset / data["t"]
data.remove(vApp > 10000)
# further filters with min/max t, offset etc.
```

**Comment by kerim371** [comment]
@halbmy thank you very much! 
that helped
