### ISSUE TITLE
Seismic tomography: restrict model depth [QUESTION]

### ISSUE THREAD

**Issue by kerim371** [gimli-org/gimli#489]
### Problem description

Using `Koenigsee` as an example I'm trying to invert my data.
The problem is that the model I get is too deep, it is more than 7000 m depth even the raypath all lay around 1000 m at max.
Is there a way to restrict the model depth while inverting the data?
And also is there a way to set min/max velocities the inverted model to have?

Apparent velocities:
![image](https://user-images.githubusercontent.com/43808863/217799087-06677f45-13b5-4836-8098-44da9f9b1efe.png)

The code used to invert the model:
```python
mgr.invert(secNodes=3, paraMaxCellSize=5000,
           zWeight=0.2, vTop=500, vBottom=6000, verbose=1)
```

Resulted raypaths:
![image](https://user-images.githubusercontent.com/43808863/217799322-68b68b3c-f493-40a5-95aa-ed5ad7f295c5.png)

### Your environment

**Operating system**: Linux Ubuntu 20.04
**Python version**: 3.9
**pyGIMLi version**: 1.3.1
**Way of installation**: e.g. Conda package

**Comment by halbmy** [comment]
Just add `paraDepth` to the keywords in the inversion call: `mgr.invert(..., paraDepth=1000, ...`

**Comment by kerim371** [comment]
@halbmy thank you!
That was exactly what I was looking for
