### ISSUE TITLE
Seismic tomography: return misfit norm from each iteration [QUESTION]

### ISSUE THREAD

**Issue by kerim371** [gimli-org/gimli#490]
### Problem description

Hi,

Is there a way to return misfit at each iteration (as an array or list or as any container)?
I would like to plot the convergence function where `x`-> is the iteration number, `y`-> misfit norm between registered and modeled traveltimes.

The inversion is done using:
```python
mgr.invert(secNodes=3, paraMaxCellSize=5000,
           zWeight=0.2, vTop=500, vBottom=6000, paraDepth=1200, verbose=1)
```

**Comment by halbmy** [comment]
`mgr.inv.chi2History`

**Comment by kerim371** [comment]
@halbmy thank you very much!
