### ISSUE TITLE
Interpolate mesh on grid [QUESTION]

### ISSUE THREAD

**Issue by kerim371** [gimli-org/gimli#491]
### Problem description

Hi,

I'm playing around with seismic tomography and interpolation.
Once I got velocity model using travel time inversion I would like to interpolate velocity model on rectangular grid and then save it to file (hdf5 is preferrable).

Here is snippet that I use to do interpolation. I get an error on the last line: `AttributeError: can't set attribute`

```python
# Generate rectangular grid
x0 = mgr.mesh.xMin()
dx = 12.5
x1 = mgr.mesh.xMax()
y0 = mgr.mesh.yMin()
dy = 12.5
y1 = mgr.mesh.yMax()

x = np.arange(start=x0,stop=x1,step=dx)
y = np.arange(start=y0,stop=y1,step=dy)
grid = mt.createGrid(x,y)

# Create grid mgr and Interpolate velocities
grid_mgr = tt.TravelTimeManager(data)
grid_mgr.setMesh(grid)
grid_mgr.velocity = pg.interpolate(grid, mgr.mesh, mgr.velocity)  # here I get an error: AttributeError: can't set attribute
```

I believe there should be another way of setting velocities to the manager.

**Operating system**: Linux, Ubuntu 20.04?
**Python version**: 3.9
**pyGIMLi version**: 1.3.1
**Way of installation**: Conda

**Comment by halbmy** [comment]
1. Note that there is always a loss of information by using interpolation. If you want to have the results on a regular grid, then you should do the inversion directly on it.
2. I don't see why you should set up another manager just for interpolation. Setting an inversion result from outside without inversion does not make much sense. You can directly set the mesh properties by `grid["velocity"]=pg.interpolate(...` and save it under any format like `grid.exportVTK(filename)`
3. `velocity` is already a function (returning the velocity) that can't be overwritten.

**Comment by halbmy** [comment]
Here's the definition:
```
class TravelTimeManager()
    ....
    @property
    def velocity(self):
        return self.fw.model
```
Due to the property decorator, `mgr.velocity` RETURNS a vector and can be used as one (e.g. for plotting) but it IS not a vector that can be overwritten.

**Comment by kerim371** [comment]
@halbmy thank you for response.

I just started using `pygimli` and mostly rely on the examples. Thus for now I use unstructured mesh for inversion like in the examples but then I will try using rectangular grid instead.

`grid["velocity"]=pg.interpolate(...` I didn't know that. That make sense, thank you!
