### ISSUE TITLE
Minor color scale issue with showMisfit function

### ISSUE THREAD

**Issue by benbpete** [gimli-org/gimli#500]
### Problem description

A minor display difference. The default color scale cMin and cMax defaults to the largest misfit value greater than 0, ignoring values < 0. This can result in misfit values where the larger-magnitude negative misfit values will be lower than default cMin.

### Your environment
--------------------------------------------------------------------------------
  Date: Fri Mar 03 06:55:51 2023 Eastern Standard Time

                OS : Windows
            CPU(s) : 4
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.9 GiB
       Environment : Jupyter

  Python 3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)]

           pygimli : 1.3.1
            pgcore : 1.2.3
             numpy : 1.19.5
        matplotlib : 3.5.1
             scipy : 1.9.1
              tqdm : 4.64.1
           IPython : 7.31.1
           pyvista : 0.34.2
--------------------------------------------------------------------------------

### Steps to reproduce
Use showMisfit where the max(abs(misfit)) > max(misfit).

Default kwargs for showMisfit:

```
        kwargs.setdefault("cMax", np.max(misfit))
        kwargs.setdefault("cMin", -kwargs["cMax"])
        kwargs.setdefault("cMap", "bwr")
        kwargs.setdefault("logScale", False)
```

### Expected behavior

showMisfit will set cMin to the maximum magnitude misfit value.

### Actual behavior

cMin is set to the maximum positive misfit value.

Suggest changing kwargs to:

```
        kwargs.setdefault("cMax", np.max(abs(misfit)))
        kwargs.setdefault("cMin", -kwargs["cMax"])
        kwargs.setdefault("cMap", "bwr")
        kwargs.setdefault("logScale", False)
```

Thanks!

**Comment by halbmy** [comment]
You're absolutely right.

Corrected by 40ce68c9 (dev branch).
