### ISSUE TITLE
MemoryError when creating P2 Mesh - Question (or Possible Problem)

### ISSUE THREAD

**Issue by benbpete** [gimli-org/gimli#501]
### Problem description

My first time trying to invert some simulated 3D data that involves a fairly complex mesh.  When attempting to invert the data, I run into a memory error.

### Your environment

  Date: Fri Mar 03 13:58:52 2023 Eastern Standard Time

                OS : Windows
            CPU(s) : 20
           Machine : AMD64
      Architecture : 64bit
               RAM : 31.7 GiB
       Environment : Jupyter

  Python 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 15:53:35)
  [MSC v.1929 64 bit (AMD64)]

           pygimli : 1.3.1
            pgcore : 1.2.3
             numpy : 1.19.5
        matplotlib : 3.5.1
             scipy : 1.9.1
              tqdm : 4.64.1
           IPython : 8.9.0
           pyvista : 0.34.2

### Steps to reproduce

I've attached the data file and the ipynb (the extension was changed to .txt so it could be attached).

### Expected behavior

Inversion of simulated data with a 3D mesh.

### Actual behavior

I receive the error below. I've tried it on two different machines (this current error occurred on a computer with decent memory and processing) and received the error twice.

I'm guessing the problem may be with the complexity of the mesh.  I have reduced the mesh complexity some and am not sure how to reduce it more if complexity is the problem.

Any help or advice is appreciated!

```
03/03/23 - 13:36:35 - pyGIMLi - INFO - Found 3 regions.
03/03/23 - 13:36:35 - pyGIMLi - INFO - Region with smallest marker (1) set to background
03/03/23 - 13:36:40 - pyGIMLi - INFO - Creating forward mesh from region infos.
03/03/23 - 13:37:58 - pyGIMLi - INFO - Creating refined mesh (P2) to solve forward task.

---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
Cell In[15], line 6
      1 # 3D INVERSION
      2 # kwargs: paraMaxCellSize, paraDX, paraDepth, optLambda??, zWeight, blockyModel =1, robustData = True, quality, mesh (ok to leave out)
      3 #ert.inv.setRegularization(2, correlationLengths=[,])
      4 #ert.inv.setRegularization(3, limits=[, ], trans="log")
      5 ert.inv.setRegularization(3,  fix = 0.0000001)
----> 6 mod3d = ert.invert(data, mesh=mesh, zWeight=1, lam = 20, verbose=True, robustData = False) #, startModel = [[1,100],[2,100]]
      7 # show model, misfit

File ~\Anaconda3\envs\pg\lib\site-packages\pygimli\frameworks\methodManager.py:777, in MeshMethodManager.invert(self, data, mesh, startModel, **kwargs)
    774 dataVals = self._ensureData(self.fop.data)
    775 errorVals = self._ensureError(self.fop.data, dataVals)
--> 777 if self.fop.mesh() is None:
    778     pg.critical('Please provide a mesh')
    780 kwargs['startModel'] = startModel

File ~\Anaconda3\envs\pg\lib\site-packages\pygimli\frameworks\modelling.py:674, in MeshModelling.mesh(self)
    671 self._applyRegionProperties()
    673 if self._regionManagerInUse and self._regionChanged is True:
--> 674     self.createFwdMesh_()
    676 return super().mesh()

File ~\Anaconda3\envs\pg\lib\site-packages\pygimli\frameworks\modelling.py:663, in MeshModelling.createFwdMesh_(self)
    653 for iId in regionIds:
    654     pg.verbose("\tRegion: {0}, Parameter: {1}, PD: {2},"
    655                " Single: {3}, Background: {4}, Fixed: {5}".format(
    656                    iId,
   (...)
    660                    self.regionManager().region(iId).isBackground(),
    661                    self.regionManager().region(iId).fixValue()))
--> 663 m = self.createRefinedFwdMesh(m)
    664 self.setMeshPost(m)
    666 self._regionChanged = False

File ~\Anaconda3\envs\pg\lib\site-packages\pygimli\frameworks\modelling.py:638, in MeshModelling.createRefinedFwdMesh(self, mesh)
    636 if self._refineH2:
    637     pg.info("Creating refined mesh (P2) to solve forward task.")
--> 638     m = m.createH2()
    640 if self._refineP2:
    641     pg.info("Creating refined mesh (P2) to solve forward task.")

MemoryError: 
```

[Utility_Inversion_3D.txt](https://github.com/gimli-org/gimli/files/10885457/Utility_Inversion_3D.txt)
[inho_p0000001_pr0.08_r100_e2_l98_d12.5_DD.txt](https://github.com/gimli-org/gimli/files/10885466/inho_p0000001_pr0.08_r100_e2_l98_d12.5_DD.txt)

**Comment by halbmy** [comment]
```
       pygimli : 1.3.1
        pgcore : 1.2.3
```
There is something wrong as pygimli 1.3.1 should require pgcore 1.3.0. How did you install it?

**Comment by benbpete** [comment]
Through Anaconda.  I just did a fresh install of Anaconda/Pygimli, same results:

  Date: Sun Mar 05 20:58:26 2023 Eastern Standard Time

                OS : Windows
            CPU(s) : 4
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.9 GiB
       Environment : Jupyter

  Python 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 15:53:35)
  [MSC v.1929 64 bit (AMD64)]

           pygimli : 1.3.1
            pgcore : 1.2.3
             numpy : 1.19.5
        matplotlib : 3.5.1
             scipy : 1.9.1
           IPython : 8.11.0
           pyvista : 0.34.2

**Comment by halbmy** [comment]
Can you update pgcore by `conda install -c gimli pgcore=1.3` and try again?

**Comment by benbpete** [comment]
This is pretty odd.  I attempted to install pgcore 1.3 on two different computers.  A small update was made on each, but pgcore 1.2.3 is still installed on both.  For what its worth, the same memory error occurs after the update (still pgcore 1.2.3).

**Comment by benbpete** [comment]
In my code there is a region 3, which is a long, small diameter cylinder.  When that is removed from the PLC/mesh, the inversion runs fine.  I am going to see if I can find a way to include the region three without causing this error.

**Comment by benbpete** [comment]
The more I look at the meshing, the more I'm convinced the problem is complexity of the P2 mesh.  I was able to create a P2 mesh with this:

`mesh_coarse = mt.createMesh(plc, smooth = True)
meshP2 = mesh_coarse.createP2()
` 

Before that, I attempted to create the P2 mesh from an intermediate H2 mesh and received a memory error, using the code below:
`
mesh_coarse = mt.createMesh(plc, smooth = True)
mesh = mesh_coarse.createH2()
meshP2 = mesh_coarse.createP2()
`

As a work around, can I directly set the P2 mesh used in forward modeling for the inversion? The "meshP2" looks adequate.  I wasn't able to find if one is able to set the P2 mesh in the documentation (I could have missed it).

Thanks again!

**Comment by halbmy** [comment]
I guess in the last snippet you meant `mesh.createP2()`?

Well, there should be no problem in refining an existing and valid mesh unless it is already huge. A small cylinder could probably lead to a mesh with a large number of cells. Try keeping the number of segments (`nSegments`) for the cylinder low, e.g. 4 or even 3.

**Comment by benbpete** [comment]
Yes, mesh.createP2(). Thanks again halbmy.  I think the mesh I am creating is just too complex in/around the cylinder, and reducing the nSegments doesn't have an effect on the memory error.

I have one more question regarding the H2 and P2 meshes.  Can they be set prior to starting the inversion, and if so, can it be set so that H2=P2?  I admit I don't fully grasp the triple-grid scheme, so I don't intuitively know if that would  violate certain assumptions/calculations. Creating an H2 mesh is doable with the current setup, but additional refinement to create the P2 mesh is where the memory errors occur.

**Comment by carsten-forty2** [comment]
how do you create the 'plc'?  Could you please provide the PLC or even better the script with associated data? I would like to reproduce the memory error to see whats the issue here. Thanks in advance.

**Comment by benbpete** [comment]
Sure thing.  Attached is the ipynb (Utility_Inversion_3D.txt - extension changed so it could be attached) and the data file inho_... (no headers, but headers are "a b m n k rhoa", and are assigned in the script).  Thank you all again!
[Utility_Inversion_3D.txt](https://github.com/gimli-org/gimli/files/10904279/Utility_Inversion_3D.txt)
[inho_p0000001_pr0.08_r100_e2_l98_d12.5_DD.txt](https://github.com/gimli-org/gimli/files/10904280/inho_p0000001_pr0.08_r100_e2_l98_d12.5_DD.txt)

**Comment by carsten-forty2** [comment]
I could reproduce the memory error only once running your notebook. Since it only appeared one time, its hard to address at the moment. However, I assume its kind of weird combination of jupyter and large meshes, while the latter  aren't efficiently implemented in pygimli currently.

For this case I think, you can safely skip the refinement of the forward mesh. You don't have topography and you already refined your sensor positions, so the accuracy of the secondary potential calculation should accurate enough. 'Tripple grid' is only needed if you have topography where the needed primary potential can't be calculated analytical.

just add:
```
ert.fop._refineH2=False
```
somewhere before you call 'invert'. You will notice the missing info:

```
- pyGIMLi - INFO - Creating refined mesh (P2) to solve forward task.
```
(Note, it wrongly says P2 here instead of H2)

You could keep (or test with) the refinement for the forward calculation if you reduce the initial mesh size. 
You could do this by skipping the local refinement in the vicinity of the sensors. Or by adding 'nSegments=4' to 'mt.createCylinder'. 

You add some noise to your data, so I assume the data where simulated. Best would then to skip the `ert.estimateError` step and set your data error with your known noise values directly.

```
data['err'] = abs(noise_magnitude/data['rhoa'])
```

Also you could think about some voltage related relative error. This would be more realistic for your Dipol Dipol data set with larger Dipole distances.

Last thought or question.
What do you expect as resulting model? A homogeneous resistivity distribution of 100 Ohmm where the effect of the high conductive pipe is vanished?

**Comment by benbpete** [comment]
Thanks Carsten, I will give this a shot. Your help and advice is immensely appreciated.

This modeling started out as a way to come up with some comprehensive and practical guidance for practitioners to avoid/reduce interference caused by buried metallic pipes/wells, e.g., how close can you survey without interference? In the process I realized how large an effect the resistivity contrast between the subsurface and the "utility" has on the magnitude of interference.  Large enough contrast (>= 7 orders of magnitude, based on my modeling), and the error plateaus towards that of an infinite conductor, less than that, and the utility effect is highly variable.  So far, I've done all forward modeling and varied pipe/well diameters, distance to pipe/well, pipe/well resistivity, pipe length, etc.  There are a millions ways to continue on with this, but right now the goal is to simulate different scenarios when trying to correct for the presence of say a metallic cased well/horizontal pipe in the inversion process.  How "wrong" can one be about the assumed conductivity of a metal well/pipe and still arrive and a reasonable model?  Given that I'm just getting started on the inversion portion of this, I don't know that answer yet. Based on the forward modeling I've done, it seems like you would need a really good estimate of that metal resistivity (not even thinking about contact resistances, etc!)  to appropriately correct for it during inversion.  

This is all in my free time (I'm a consultant, so I don't get paid for it!), but if you or Thomas are interested in teaming up, that would be great!

Thanks again for the help.  Pygimli (and BERT) are an amazing asset to the geophysics community!

**Comment by benbpete** [comment]
With your suggestions, the inversion ran with no problems. Thanks again!  Marking as closed.
