### ISSUE TITLE
How to modify the objective function?

### ISSUE THREAD

**Issue by LiuQian19970208** [gimli-org/gimli#502]
Hello, I want to modify the default objective function of Gauss-Newton inversion, but I don't know how to do it ?
<img width="508" alt="a684cbab76d54ba21993200accfd276" src="https://user-images.githubusercontent.com/105376338/223010080-db37de5c-f625-4cc9-b76d-7616e391843c.png">
My objective function is as follows
![baa1b9e66b13099e6cc6bb7cc49f26b](https://user-images.githubusercontent.com/105376338/223011145-c44fd6d2-1907-4fba-a29f-562b9059649b.png)
` 
data=ert.load('diploe190d.dat')
data["err"] = ert.estimateError(data)
mgr = ert.ERTManager()
inv = mgr.invert(data=data,lam=10,verbose=True)
mgr.saveResult()
mgr.showResult()
`

**Comment by halbmy** [comment]
What are the $$p_i$$ and $$r_i$$? Do they depend on the m?

**Comment by halbmy** [comment]
And what's the relation between $m_1$ and $m_2$?

**Comment by halbmy** [comment]
Closing as I don't expect any activity now. Adding examples and tutorials for cross-gradients is on the list.
