### ISSUE TITLE
Plotting pseudosection like ert.show() but with matplotlib

### ISSUE THREAD

**Issue by Morriiiss** [gimli-org/gimli#503]
### Problem description

On my server I am running Python backend with Pygimli, however I want to export the datacontainer with all the info to the frontend where I can plot the pseudosection. This yields than that I need to recreate the nice ert.show() in another language. For now Im just trying to plot the pseudosection  in matplotlib, but I  cant get it right

### Your environment

--------------------------------------------------------------------------------
  Date: Tue Mar 07 12:35:09 2023 CET

                OS : Linux
            CPU(s) : 4
           Machine : x86_64
      Architecture : 64bit
               RAM : 12.4 GiB
       Environment : Jupyter
       File system : ext4

  Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03)
  [GCC 11.3.0]

           pygimli : 1.3.1
            pgcore : 1.3.0
             numpy : 1.23.4
        matplotlib : 3.6.2
             scipy : 1.9.3
              tqdm : 4.64.1
           IPython : 8.7.0
            meshio : 5.3.4
           pyvista : 0.34.2
--------------------------------------------------------------------------------

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
import matplotlib.pyplot as plt
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import ert
import pandas as pd
import numpy as np

data = pg.getExampleFile('ert/slagdump.ohm', load=True, verbose=True)
data['k'] = ert.createGeometricFactors(data, numerical=True)
mgr = ert.ERTManager(sr=False)
data['err'] = ert.estimateError(data, absoluteUError=5e-5, relativeError=0.03)
print(data)
mgr.checkData(data)
print(data)

resistivity = data['rhoa']

# Reshape the resistivity array to a 2D grid
# Plot the pseudosection
elecs = data.sensorPositions()
nElecs = elecs.shape[0]

# Compute pseudosection coordinates
nElecs = data.sensorPositions().shape[0]
nLevels = int(len(resistivity) / nElecs) * nElecs
resistivity = resistivity[:nLevels]
resistivity = np.reshape(resistivity,(nElecs, -1))


# Plot the pseudosection
plt.imshow(resistivity, aspect = 'auto',origin='upper', cmap='jet',extent=[0,70,0,5])
plt.colorbar(label='Resistivity (Ohm-m)')
plt.xlabel('X [m]')
plt.ylabel('No idea what to put here')
plt.xlim([0,70])
plt.ylim([0,5])
plt.show()
ert.show(data)
```

### Expected behavior

![image](https://user-images.githubusercontent.com/32489725/223411221-88b27af3-5208-4032-9510-d7c743f09121.png)
### Actual behavior

![image](https://user-images.githubusercontent.com/32489725/223411293-899c5abd-70f0-4bd2-878f-732f70afd04b.png)

**Comment by halbmy** [comment]
I don't quite know what to answer. You want to rewrite parts of the code (a quite complex one) in another language? A pseudosection is not quite expressed as a matrix. Why not using Python to generate the image for the web? What's the purpose?

**Comment by Morriiiss** [comment]
Now I'm generating the plot in python, saving it and sending it to the
frontend where I display it. My idea was to let the user filter out
different data depending on error, negative value and so on when they see
the plot. However if I generate the plot on the backend, everytime the user
change something the whole plot needs to be generated and takes a bit of
time, therefore I wanted to generate the plot in the frontend

Den tis 7 mars 2023 kl 13:53 skrev Thomas Günther ***@***.***

**Comment by halbmy** [comment]
For any web interface, the backend generates images to be shown in the frontend, so that's normal and straightforward as long as you can run pyGIMLi on the web server (Python is great for the web). Reimplementations do almost never make sense.

To summarize again, answering to the title "Plotting pseudosection like ert.show() but with matplotlib": `ert.show()` uses matplotlib, but in form of patches as a pseudosection cannot easily plotted as matrix (the above Wenner image is no matrix either), particularly if different kinds of arrays are combined.
