### ISSUE TITLE
Importing crosshole data and making an inversion

### ISSUE THREAD

**Issue by simondehout** [gimli-org/gimli#504]
### Problem description
Dear Thomas or github helper :), 

I have received ERT measurement data from a borehole to borehole (crosshole) injection test. 
I have processed my data and I am now running a inversion of my data. Only problem I have is that my mesh is following the order of my electrode sequence. Thus I get a wrong illustration of my results. Would you have any suggestions on how i can improve this following code with this .dat file? 

Thanks in advance! Simon
[crosshole_data_inver.zip](https://github.com/gimli-org/gimli/files/10917993/crosshole_data_inver.zip)
![ert4_5_46e_corr](https://user-images.githubusercontent.com/123652293/223641256-75d62937-27d7-4e5a-95f2-606058ea6172.png)

**Comment by halbmy** [comment]
We definitely need an example for 2D crosshole data, I will add one from the BERT tutorial.

The ERT manager uses the meshtools `createParaMesh`/`createParaMeshPLC` to generate the meshes. However, this is only suited for surface layouts. You will have to create the mesh by yourself and pass it to
```
import pygimli.meshtools as mt
ex = pg.x(data)
ez = pg.z(data)
bnd = 2
rect = mt.createRectangle([min(ex)-bnd, min(ez)-bnd], [max(ex)+bnd, 0], marker=2)
for i in range(len(ex)):
    rect.createNode([ex[i], ez[i]])

para = mt.createMesh(rect, quality=34.5, area=.3)
mesh= mt.appendTriangleBoundary(para, marker=1, quality=34)
ax, cb = pg.show(mesh, markers=True, showMesh=True)
ax.plot(ex, ez, "mx") 
```
![image](https://user-images.githubusercontent.com/7136401/223654321-424d9980-3c20-4970-b067-89e655f6dc33.png)

```
mgr = ert.Manager(data)
mgr.invert(mesh=mesh)
mgr.showResult()
```
![image](https://user-images.githubusercontent.com/7136401/223655241-08bb4a5f-44e8-434f-90c1-d9027a7a9dc8.png)

**Comment by halbmy** [comment]
Have you been successful with your data?

Note that there is a 2d crosshole ERT example at
http://dev.pygimli.org/_examples_auto/3_dc_and_ip/plot_06_crosshole2d.html

**Comment by simondehout** [comment]
Hi Thomas, 
Thanks a lot for the clarification and the example!

Apologies for the late reply, i was away on leave with limited access to my computer. 
I have ran the inversion and refined my mesh a bit. 
![image](https://user-images.githubusercontent.com/123652293/228513926-d8752ebd-8e9f-4be7-9a84-9748fe72f23a.png)

I have two small questions: 
- what would be the best to download this inverted dataset into a coordinate file with a value for (x,y,z, rho)
- for time lapse readings, what would be the best for crosshole data? substract rho data before inversion or substract inversions from each other? 

Thanks in advance and looking forward to discuss, 

Simon

**Comment by halbmy** [comment]
1. I mean `mgr.model`. For visualizing in 3D, I rather suggest exporting it as vtk file directly from pyGIMLi so that the triangles are preseved. Rotation (`mesh.rotate`) and translation (`mesh.translate`)  should be easy.
2. There are a couple of timelapse notebooks under https://github.com/gimli-org/notebooks/tree/main/ERT/timelapse , specifically a new one with 2d crosshole field data: https://github.com/gimli-org/notebooks/blob/main/ERT/timelapse/2dxh/timelapseALERT.ipynb

**Comment by halbmy** [comment]
Seems like you're missing an argument: `np.savetxt("blabla.dat", X)`

**Comment by halbmy** [comment]
I guess all has been solved. Reopen if problems persist.
