### ISSUE TITLE
Crosshole ERT inversion and structure constraint inversion question

### ISSUE THREAD

**Issue by 728236958** [gimli-org/gimli#505]
### Problem description

Hello Thomas, I would like to ask you about cross-hole ERT inversion. There is a resistivity compensation problem; a simple example shows that the anomaly body’s surroundings will affect the increase of resistivity, but as the range expands, there will be a counterintuitive change of resistivity compensation (the outermost layer of low resistivity becomes higher, and the outermost layer of high resistivity becomes lower). As shown in the figure: 
![N{3H V86%~PQV{FYF8XFV9](https://user-images.githubusercontent.com/69100178/224075488-f151ee12-e014-47cf-a10f-fee371d55cae.png)

2. Is it possible to use only one line boundary as a structural constraint? Here I reconstruct the mesh by enclosing two rectangular cells to achieve structural constraints, but there are anomalous values at both ends. The cells are well represented, but the resistivity around them is greatly influenced.(chi2>100, difficult to converge)
![image](https://user-images.githubusercontent.com/69100178/224076498-e437a2f0-0ea5-4246-a317-55f08577915b.png)

**Comment by halbmy** [comment]
First, I can't deduce the resistivity values in the synthetic model. You should use the same (logarithmic color scale) for both.

The second question is rather a matter of the regularization parameter. As you decouple the smoothness across the boundaries, you should use a way higher regularization parameter leading to a more homogeneous background model, and it should be easy to fit the data. Right now you are just overfitting your data. I guess the high chi-square is from the strong contrasts or from an inappropriate model discretization (you need less cells left and right but more on the bottom, and a background for outer space sensitivities). 

Of course you can use any type of constraints as you won't know the exact position of your anomalies.

**Comment by halbmy** [comment]
Closing after no response.
