### ISSUE TITLE
There is a requested electrode that does not match the given mesh

### ISSUE THREAD

**Issue by Abby123455r** [gimli-org/gimli#510]
#I want to delineat the behaviour of spacific region (top 2m which is contaminated).i want to decouple both zones top 2m and buttom,to look in detail at the at contaminated zone and corelate it with available soil chemistry. For this purpose i creat a geometry and devided it in to two region.
```
world = mt.createWorld(start=[-160, 0], end=[50, -50], layers=[-2],
                       worldMarker=True)
#creat mesh and add the electrodes
for s in data.sensors():
    world.createNode(s)
    world.createNode(s - [0, 0.1])
mesh = mt.createMesh (world)
pg.show(mesh, markers=True, showMesh=True);
mgr.invert(data,mesh=mesh,lam=20)
but when i perform inversion it shows There is a requested electrode that does not match the given mesh.
```
Could you please guide me where i am doing wrong.

**Comment by halbmy** [comment]
I would need to see the data to check this. I guess the sensors are out of the modelling domain.

**Comment by halbmy** [comment]
Your model goes from x=-160 to +50, whereas your electrodes go from 0 to 160, so they are outside.

**Comment by Abby123455r** [comment]
When i read the data file that i sent you before it shows the following statment. 

17/03/23 - 09:58:49 - pyGIMLi - INFO - could not read unified data format for ERT ... try res2dinv

**Comment by halbmy** [comment]
The info message is normal as pyGIMLi has to guess the format. The data are nicely read:
![image](https://user-images.githubusercontent.com/7136401/225901799-53609e3b-8a34-444d-8517-80560d010a6d.png)

But the electrodes are outside of the model as explained above (model goes from -160 to +50 and electrodes go from 0 to 160).

**Comment by Abby123455r** [comment]
world = mt.createWorld(start=[0, 0], end=[160, -40], layers=[-2],
                       worldMarker=True)
                        pg.show(world)
for s in data.sensors():
    world.createNode(s)
    world.createNode(s - [0, 0.1])

mesh = mt.createMesh (world)
pg.show(mesh, markers=True, showMesh=True)
data["k"] = pg.Vector(data.size(), 1.0)
out1 = ert.simulate(mesh=mesh, scheme=data, res=1.0, calcOnly=True)
print(out1)
data["err"] = ert.estimateError(data, relativeError=0.02, absoluteUError=0)
mgr = ert.ERTManager(data, sr=False)
mgr.inv.setRegularization(1, background=False)
mgr.invert()
mgr.showResult(**kw);
then i get the final section.
Actully i want to decouple two zones as you did it in lake example and then want to see the top zone (2m) in more detail where i soil geochemistry data.as in lake example they delineate the water cells by extracting the water body to see the zone for more detail.
![image](https://user-images.githubusercontent.com/119299976/226265530-aad1956b-a7c2-4347-b1d1-da487cb86d43.png)
