### ISSUE TITLE
3D creatMesh error

### ISSUE THREAD

**Issue by ishuihan** [gimli-org/gimli#513]
### Problem description

Hello, when I created a 3D mesh using creatMesh, the following error occurred. Please help me. thank you very mush.

### Your environment

Please provide the output of `print(pygimli.Report())` here. If that does not
work, please give provide some additional information on your:

**Operating system**: e.g. Windows, Linux or Mac?
**Python version**: e.g. 3.8, 3.9, etc.?
**pyGIMLi version**: Output of `print(pygimli.__version__)`
**Way of installation**: e.g. Conda package, manual compilation from source, etc.

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
plc = mt.createParaMeshPLC3D(data)
pg.show(plc)
mesh = mt.createMesh(plc)
pg.show(mesh)
```

### Expected behavior

Tell us what should happen or what you want to achieve.

### Actual behavior

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[6], line 1
----> 1 mesh = mt.createMesh(plc)
      2 pg.show(mesh)

File D:\program\anaconda3\envs\pg\lib\site-packages\pygimli\meshtools\mesh.py:148, in createMesh(poly, quality, area, smooth, switches, verbose, **kwargs)
    145 pg.meshtools.exportPLC(poly, namePLC)
    146 os.close(fd)  # needed for win32 to free the file for closing
--> 148 mesh = pg.meshtools.syscallTetgen(namePLC, quality, area,
    149                                   verbose=verbose, **kwargs)
    151 return mesh

File D:\program\anaconda3\envs\pg\lib\site-packages\pygimli\meshtools\polytools.py:1891, in syscallTetgen(filename, quality, area, preserveBoundary, verbose, tetgen)
   1888         print(e)
   1889 else:
   1890     # system('meshconvert -it -BD -o ' + filebody + ' ' + filebody + '-1')
-> 1891     mesh = pg.meshtools.readTetgen(filebody + '-1')
   1892     try:
   1893         os.remove(filebody + '-1.node')

File D:\program\anaconda3\envs\pg\lib\site-packages\pygimli\meshtools\mesh.py:963, in readTetgen(fName, comment, verbose, defaultCellMarker, loadFaces, quadratic)
    960 mesh = pg.Mesh(3)
    962 # Part 1/3: Nodes, essential
--> 963 with open(fName + '.node', 'r') as node_in:
    964     node_lines = pg.utils.filterLinesByCommentStr(node_in.readlines(),
    965                                                   comment)
    966 node_1 = node_lines[0].split()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\shd\\AppData\\Local\\Temp\\tmpq9s0ohj7-1.node'

```
Paste output here.
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
Please, fill in the information as requested:

> Operating system: e.g. Windows, Linux or Mac?
> Python version: e.g. 3.8, 3.9, etc.?
> pyGIMLi version: Output of print(pygimli.__version__)
> Way of installation: e.g. Conda package, manual compilation from source, etc.

Can you attach your data file so that we can test it?

**Comment by ishuihan** [comment]
Operating system: Windows
Python version: 3.8.16
pyGIMLi version: <function version at 0x00000275F47F3B80>
Way of installation: conda create -n pg -c gimli -c conda-forge pygimli=1.3.1

**Comment by carsten-forty2** [comment]
We cannot say more without your data file and we only need the sensor section of this file.

**Comment by ishuihan** [comment]
Data: Sensors: 126 data: 753, nonzero entries: ['a', 'b', 'k', 'm', 'n', 'rhoa', 'valid']
Mesh: Nodes: 596 Cells: 0 Boundaries: 1157
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[3], line 19
     17 print(plc)
     18 # mesh = mt.createMesh(plc, quality=1.3)
---> 19 mesh = mt.createMesh(plc)
     20 print(mesh)

File D:\program\anaconda3\envs\pg\lib\site-packages\pygimli\meshtools\mesh.py:148, in createMesh(poly, quality, area, smooth, switches, verbose, **kwargs)
    145 pg.meshtools.exportPLC(poly, namePLC)
    146 os.close(fd)  # needed for win32 to free the file for closing
--> 148 mesh = pg.meshtools.syscallTetgen(namePLC, quality, area,
    149                                   verbose=verbose, **kwargs)
    151 return mesh

File D:\program\anaconda3\envs\pg\lib\site-packages\pygimli\meshtools\polytools.py:1891, in syscallTetgen(filename, quality, area, preserveBoundary, verbose, tetgen)
   1888         print(e)
   1889 else:
   1890     # system('meshconvert -it -BD -o ' + filebody + ' ' + filebody + '-1')
-> 1891     mesh = pg.meshtools.readTetgen(filebody + '-1')
   1892     try:
   1893         os.remove(filebody + '-1.node')

File D:\program\anaconda3\envs\pg\lib\site-packages\pygimli\meshtools\mesh.py:963, in readTetgen(fName, comment, verbose, defaultCellMarker, loadFaces, quadratic)
    960 mesh = pg.Mesh(3)
    962 # Part 1/3: Nodes, essential
--> 963 with open(fName + '.node', 'r') as node_in:
    964     node_lines = pg.utils.filterLinesByCommentStr(node_in.readlines(),
    965                                                   comment)
    966 node_1 = node_lines[0].split()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\shd\\AppData\\Local\\Temp\\tmpe5x3at0a-1.node'

**Comment by ishuihan** [comment]
FileNotFoundError is different every time it runs, it seems to be temporarily generated.

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\shd\\AppData\\Local\\Temp\\tmpz933js0c-1.node'
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\shd\\AppData\\Local\\Temp\\tmpqt2me1j6-1.node'
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\shd\\AppData\\Local\\Temp\\tmpsb7ngz9h-1.node'
..........

Looking forward to your reply. Thank you very much.

**Comment by carsten-forty2** [comment]
Assuming  'data/gallery3d.dat.txt' is the same like `data = pg.getExampleFile('ert/gallery3d.dat', load=True)` I cannot reproduce the problem. Please verify your tetgen installation:

```
import pygimli as pg
import pygimli.meshtools as mt
plc = mt.createCube()
mesh = mt.createMesh(plc, quality=1.3)
# optional you can try:
# mesh = mt.createMesh(plc, quality=1.3, tetgen='path to your tetgen binary')
print(mesh)
#pg.show(mesh)
```

**Comment by ishuihan** [comment]
Thank you for your help, I have already solved it.
