### ISSUE TITLE
MarquardtInversion error?

### ISSUE THREAD

**Issue by ishuihan** [gimli-org/gimli#515]
### Problem description

Hello, when I tried to use Marquardt Inversion, nlay=4 was correct, while nlay=3 or nlay=5 was incorrect. Please help me, thank you.

### Your environment

Please provide the output of `print(pygimli.Report())` here. If that does not
work, please give provide some additional information on your:

**Operating system**: e.g. Windows, Linux or Mac?
Windows
**Python version**: e.g. 3.8, 3.9, etc.?
3.8.16
**pyGIMLi version**: Output of `print(pygimli.__version__)`
**Way of installation**: e.g. Conda package, manual compilation from source, etc.
conda create -n pg -c gimli -c conda-forge pygimli=1.3.1
### Steps to reproduce

```python

import matplotlib.pyplot as plt
import numpy as np
import pygimli as pg
from pygimli.viewer.mpl import drawModel1D
from pygimli.physics.ves import VESModelling
from pygimli.frameworks import MarquardtInversion

**************The code is only modified here, others remain unchanged.***********************

###nlay=4 is correct
synThk = [5, 15, 15]
synRes = [1000, 100, 500, 20]
nlay = len(synRes)  # number of layers

###nlay=3 is incorrect
synThk = [5, 15]
synRes = [1000, 100, 500]
nlay = len(synRes)  # number of layers

###nlay=5 is correct
synThk = [5, 15, 15, 10]
synRes = [1000, 100, 500, 20, 100]
nlay = len(synRes)  # number of layers
********************************************************************
errorDCrel = 3.  # in per cent

startModel = [10]*(nlay-1) + [100]*nlay
print(startModel)
#####
ab2 = 1.3**np.arange(20) * 3.  # logarithmically equidistance starting with 3m
na = len(ab2)
fDC = VESModelling(ab2=ab2, mn2=np.ones_like(ab2))
dataDC = fDC(synThk+synRes)
errorDC = np.ones_like(dataDC) * errorDCrel / 100.
dataDC *= 1. + pg.randn(len(dataDC), seed=1234) * errorDC
######
invDC = MarquardtInversion(fop=fDC, verbose=False)
modelDC = invDC.run(dataDC, errorDC, startModel=startModel)
...
```

### Expected behavior

Tell us what should happen or what you want to achieve.

### Actual behavior
###nlay=3 is incorrect
28/03/23 - 17:30:42 - pyGIMLi - ERROR - <class 'pygimli.frameworks.inversion.MarquardtInversion'>.convertStartModel(D:\program\anaconda3\envs\pg\lib\site-packages\pygimli\frameworks\inversion.py:224)
Starting model size invalid 5 != 7.
28/03/23 - 17:30:42 - pyGIMLi - INFO - Created startmodel from forward operator: 7 [0.5, 6.122507735840206, 81.0927096866866, 389.2323902402095, 389.2323902402095, 389.2323902402095, 389.2323902402095]

###nlay=4 is correct

###nlay=5 is incorrect
28/03/23 - 17:32:17 - pyGIMLi - ERROR - <class 'pygimli.frameworks.inversion.MarquardtInversion'>.convertStartModel(D:\program\anaconda3\envs\pg\lib\site-packages\pygimli\frameworks\inversion.py:224)
Starting model size invalid 9 != 7.
28/03/23 - 17:32:17 - pyGIMLi - INFO - Created startmodel from forward operator: 7 [0.5, 6.122507735840206, 81.0927096866866, 165.2465038117207, 165.2465038117207, 165.2465038117207, 165.2465038117207]

```
Paste output here.
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
For block 1d type of inversions, you should rather use the dedicated framework and pass the number of layers:
```
from pygimli.frameworks import Block1DInversion
...
invDC = Block1DInversion(fop=fDC, verbose=False)
modelDC = invDC.run(dataDC, errorDC, nLayers=nlay, startModel=startModel)
```

**Comment by halbmy** [comment]
The point is, it also has to work without a starting model and in this case the inversion needs to know the number of layers. We decided not to fix it in the forward class so that one can easily run inversions without reinitializing the fop.

However, I changed the code (9e645bc7) so that it retrieves the number of layers in case a starting model is provided.
