### ISSUE TITLE
3D crosshole inversion with surface electrodes

### ISSUE THREAD

**Issue by simondehout** [gimli-org/gimli#518]
### Problem description

Hi Thomas or gimli helper
I followed your tutorial for 3D crosshole inversion.  (http://dev.pygimli.org/_examples_auto/3_dc_and_ip/plot_08_crosshole3d.html)
I needed to adapt it a bit to my data and used pb.importData instead of  pg.getExampleData. 

However i get the error for line 108 where:
`AttributeError: module 'pygimli.meshtools' has no attribute 'extract2dSlice'`
for the line `sli = mt.extract2dSlice(mesh)`. 

I understand that this is to create a background region. But later for the inversion, this region isn't used if i understand correctly. 
pygimli then pybert (version 1.3.1 and 2.4.0, respectively) and running them via python 3.8.15.
[crosshole_3d_inver.zip](https://github.com/gimli-org/gimli/files/11147537/crosshole_3d_inver.zip)

Thanks in advance,
Simon

**Comment by halbmy** [comment]
The function `extract2dSlice` is just used for plotting purposes and the slice is not used thereafter.

If you upgrade to pyGIMLi v1.4.0 (just appeared today) this and other functions will be available. Check it out!

**Comment by simondehout** [comment]
Okay great thanks ! 
I managed to get my code to run. Somehow the import file had trouble to read my rhoa values. 
Sadly my computer has not enough memory to run the 3D inversion, so i need to look into ways to make it run smoother. 
[crosshole_3d_inver.zip](https://github.com/gimli-org/gimli/files/11149931/crosshole_3d_inver.zip)

I have another question. I have tried to run the timelapse inversion, from ERT field data using some of the instructions you mentioned on : https://github.com/gimli-org/notebooks/blob/main/ERT/timelapse/2dxh/timelapseALERT.ipynb 
However I notice the technicians that took the readings recorded one more electrode (after injection of the tracer fluid) than before injection. So when I do mesh1/mesh, both mesh don't have the same size hence I can't run my timelapse. 
Do you have a recommendation regarding omitting one or more electrodes and their associated readings from the data file ? 
[03_invert_rightmesh_withdiff.zip](https://github.com/gimli-org/gimli/files/11150099/03_invert_rightmesh_withdiff.zip)
Like if it was electrode nr3 than all the readings from a b m n with : 1 2 3 4, 2 3 4 5, 3 4 5 6, ....

Thanks !

Simon

**Comment by halbmy** [comment]
To the timelapse ERT: the first inversion strategies (e.g. the recommended reference model inversion) in the provided example only requires to be run on the same mesh, the data containers can be different. If there are different electrodes, better make sure to include all electrodes of all datasets in the mesh. In the modelling they are identified by their position.

Only for the difference scheme you need identical quadrupoles for the misfit correction. There are tools to bring all data to a common scheme where non-existing data just get large errors.

**Comment by halbmy** [comment]
However, I am not sure about the first point, I guess it is mainly about mesh generation. Maybe you should create a new issue illustrating the problem? 

Uploading the codes would require investing time without having a benefit for other users that could learn from your case.

**Comment by halbmy** [comment]
Dear Simon, I forgot to answer the last point about missing electrode. You can (besides removing single measurements like with `data.remove(data["a"] == 12)` also remove a complete electrode by `data.removeSensorIdx(12)`.

**Comment by halbmy** [comment]
When reading in the bin file with `data = pb.importData("ert1_2_46e.bin")`, I get a lot of errors of the form
```
GIMLI::DataContainerERT::createFourPointData(GIMLI::Index, GIMLI::SIndex, GIMLI::SIndex, GIMLI::SIndex, GIMLI::SIndex)  Error:  Electrode config wrong data: 3545 ; a = 23 b = 35 m = 24 n = 23
```
so there is something wrong with your bin file (or our import routine).
However, you are right that `data_orig.removeSensorIdx(n)` always removes the first sensor regardless of n. This needs to be corrected. 

Thank you for reporting. The following code should work:
```
for tok in "abmn":
    data.remove(data_orig[tok] == n)

data.removeUnusedSensors()
```

**Comment by simondehout** [comment]
Hi, Thank for the following code. It seems to work perfectly with my data. 

Regarding the errors from the `data = pb.importData("ert1_2_46e.bin")`, I figured out why it kept on happening. I had something wrong in my original sequence file where some abmn value were the same. I think that in this case the import function is preventing the importing of lines with  a or b or m or n being the same. Thanks for pointing it out.
