### ISSUE TITLE
Use castxml binaries to avoid clang and llvm related issues

### ISSUE THREAD

**Issue by florian-wagner** [gimli-org/gimli#52]
I found that there are quite up-to-date castxml binaries for all major platforms available at: https://midas3.kitware.com/midas/folder/13152 Compiling gimli with it worked out of the box on 2 different systems that I tried. Maybe this is a way to circumvent recent issues with llvm and clang (3.8). @gimli-org/gimli-developers What do you think?

**Comment by halbmy** [comment]
I'm gonna try it under Windows, somebody should volunteer for MacOS.
At least we can provide a link to this page in the installation instruction and make sure it will work once it is found on the path. After observing it a while we could avoid the clang 3.8 (and 3.9?) problems.

**Comment by carsten-forty2** [comment]
You can add a castXML binary to the build process

http://www.pygimli.org/installation.html#castxml

I let cmake check this for us.
