### ISSUE TITLE
Export Inversion Result to Software Modelling

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#520]
Excuse Me,
 Is there a feature or command which can export inversion results to XYZ Format? Or another format that can export my inversion ERT result to Software Modelling like Voxler and Oasis Montaj?

I have tried using the results with a VTK file, but unfortunately, there are many irregularities, such as the Y and Z data are reversed and the data resistivity does not appear.

**Comment by halbmy** [comment]
As to the VTK ("the data resistivity does not appear."), you first have to put any property into the mesh before exporting, e.g.
```
mesh = mgr.paraDomain
mesh["resistivity"] = mgr.model
mesh.exportVTK("out.vtk")
```
