### ISSUE TITLE
3D Refraction Modeling and Inversion

### ISSUE THREAD

**Issue by Wanglihui2000** [gimli-org/gimli#524]
### Problem description

Hello, I am trying to use a hexahedral mesh for 3D refraction inversion of a simple velocity layered model, but the inversion results are poor. I'm not sure which step went wrong.
### Your environment

Please provide the output of `print(pygimli.Report())` here. If that does not
work, please give provide some additional information on your:

**Operating system**:Windows
**Python version**: 3.8
**pyGIMLi version**: 1.3.0
**Way of installation**: Conda package

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import traveltime
from pygimli.viewer.pv import drawSensors,drawSlice
from pygimli.physics import TravelTimeManager

pyvista = pg.optImport("pyvista")
x=np.arange(-300.,301.,50)
y=np.arange(-300.,301.,50)
z=np.arange(-300.,1.,50)
mesh=mt.createMesh3D(x=x,y=y,z=z)

vel3=np.zeros(len(pg.z(mesh.cellCenters())))
pg_z=pg.z(mesh.cellCenters())

for i,j in enumerate(pg_z):
    if j >= -200. and j <= -100. :
        vel3[i] = 2000.
    else:
        vel3[i] = 1000.

pg.show(mesh, vel3, showMesh=True,filter={'clip':{}},alpha=0.8)
numberGeophones = 7
paodian= 7
lst2=np.linspace(-300.,301., numberGeophones)
lst1=np.linspace(-300.,301.,paodian)
sensors=[]
for i in lst1:
    sensors.append([i,-250.,0.])
for j in lst2:
    sensors.append([j, 250., 0.])
scheme = pg.physics.traveltime.createRAData(sensors)
mgr = TravelTimeManager()
plotter, _ = pg.show(mesh, style='wireframe', line_width=0.1,
                          hold=True)
drawSensors(plotter,sensors[0:7], diam=20, color='red')
drawSensors(plotter,sensors[7:], diam=20, color='green')
plotter.show()

data = mgr.simulate(slowness=1.0 / vel3, scheme=scheme, mesh=mesh,
                     noiseLevel=0.001, noiseAbs=0.001, seed=1337,
                     verbose=True)
vest = mgr.invert(data,mesh=mesh,verbose=True,maxIter=50)
ax, _ = pg.show(mesh, alpha=0., hold=True, colorBar=False)
drawSlice(ax,mesh,normal=[1,0,0], data=pg.abs(vest), label="Absolute velocity")
ax.show()
ax1, _ = pg.show(mesh, alpha=0., hold=True, colorBar=False)
drawSlice(ax1,mesh,normal=[0,1,0], data=pg.abs(vest), label="Absolute velocity")
ax1.show()
```

### Expected behavior

I want to get good 3D inversion results for refracted waves.
### Actual behavior

Although chi2 is a bit large, this result is also very abnormal, with no layered structure at all.

```
--------------------------------------------------------------------------------
inv.iter 16 ... calculating jacobian matrix (forced=1)...... 65.028 s
solve CGLSCDWWtrans with lambda = 20
tau = 0. Trying parabolic line search with step length 0.3 ==> tau = -0.0226957
 tau < 0.03 ==> tau = 0.03
16: LS newModel: min = 0.000534551; max = 0.00157908
16: LS newResponse: min = 0.090348; max = 0.565804
16: rms/rrms(data, LS newResponse) = 0.00894348/2.65146%
16: chi^2(data, LS newResponse, error, log) = 40.58
16: Phi = 7385.56+17.4425*20=7734.41
Linesearch tau = 0.03
16: Model: min = 0.000569959; max = 0.00127944
16: Response: min = 0.0950029; max = 0.567162
16: rms/rrms(data, Response) = 0.00421092/1.39972%
16: chi^2(data, Response, error, log) = 9.33978
16: Phi = 1699.84+14.167*20=1983.18
chi² = 9.34 (dPhi = 0.7%) lam: 20.0
################################################################################
#                 Abort criteria reached: dPhi = 0.7 (< 2.0%)                  #
################################################################################


![503b29be6f6b4440a9166a12c59c27a](https://user-images.githubusercontent.com/94602751/232417820-e9da6477-1632-4c15-9c62-d5fb9cc0b3cf.png)


```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
As the geometrical dimensions are rather large, the traveltimes are in the range of 100 to 550 ms. For these, the error of 1ms (<1%) is unrealistically small and modelling errors come into play which is why chi-square=1 is not reached. 

Your result
![image](https://user-images.githubusercontent.com/7136401/232711285-da1314c8-48be-4c1f-9d8c-7ec3d51ade75.png)
is not too bad. It shows increased velocity only the middle. Considering your survey geometry (very limited offsets and very sparse coverage), you just have a very limited ray coverage in the middle of your high-velocity layer.

**Comment by Wanglihui2000** [comment]
> 由于几何尺寸相当大，因此行程时间在 100 到 550 毫秒的范围内。对于这些，1ms（<1%）的误差非常小，建模误差开始发挥作用，这就是为什么没有达到卡方= 1的原因。
> 
> 你的结果![image](https://user-images.githubusercontent.com/7136401/232711285-da1314c8-48be-4c1f-9d8c-7ec3d51ade75.png)还不错。它仅显示中间速度增加。考虑到您的测量几何（非常有限的偏移和非常稀疏的覆盖范围），您在高速图层中间的光线覆盖范围非常有限。



> 由于几何尺寸相当大，因此行程时间在 100 到 550 毫秒的范围内。对于这些，1ms（<1%）的误差非常小，建模误差开始发挥作用，这就是为什么没有达到卡方= 1的原因。
> 
> 你的结果![image](https://user-images.githubusercontent.com/7136401/232711285-da1314c8-48be-4c1f-9d8c-7ec3d51ade75.png)还不错。它仅显示中间速度增加。考虑到您的测量几何（非常有限的偏移和非常稀疏的覆盖范围），您在高速图层中间的光线覆盖范围非常有限。

Thank you very much for your reply. I tried to reduce the geometrical dimensions, and the grid size also decreased. But for 3D inversion, this can lead to new problems: 'memory errors', and the program runs slowly. How to make this program run faster?

**Comment by Wanglihui2000** [comment]
@halbmy thank you very much!
