### ISSUE TITLE
How to post process the inverted data?

### ISSUE THREAD

**Issue by makeabhishek** [gimli-org/gimli#528]
### Problem description

I performed refraction inversion using example "Field data inversion (“Koenigsee”)" and plotted it using pygimli. I saved the data and read it using pyvista. How can I post process the inverted velocity at each point? Example: how to get the inverted values for each co-ordinate [x,y,z,vel] 

### Steps to reproduce
```
# Field data inversion (“Koenigsee”) example
velInv = mgr.invert(secNodes=3, paraMaxCellSize=5.0, zWeight=0.2, vTop=500, vBottom=5000, verbose=1)

# reading vtk file and plotting
import pyvista as pv

# read the data
grid = pv.read('velocity.vtk')

# plot the data with an automatically created Plotter
grid.plot(show_scalar_bar=True, show_axes=True)

cells = gridPts.cells
boundary = gridPts.bounds
center = gridPts.center
pt = gridPts.points
plt.plot(pt[:,0],pt[:,1],'ok')
```
I have the `x,y,z, `coordinates in the `pt` array. But I'm not sure how can I obtain the inverted velocity and do post processing.  For example if I want to multiply the inverted velocity by random number for each cells, which data structure to utilize?

**Comment by halbmy** [comment]
I don't quite see the point. The example is a 2D profile. Visualization in 3D makes sense if it is with other data that are 3D distributed. Reducing the inverted triangles (or tetrahedra) to points is never a good idea as we have a filled volume. And it is not a grid anyway.

Independent of this, your question seems to be purely pyVista-related as you already load a vtk file and it is not important whether it comes from pyGIMLi or somewhere else. Or are you interested in transforming the pyGIMLi meshes and vectors into pyVista? In this case, one could use something like
```
pgmesh = mgr.paraDomain
pgmesh["velocity"] = mgr.velocity
pvmesh = pg.viewer.pv.pgMesh2pvMesh(pgmesh)
...
```

**Comment by makeabhishek** [comment]
Thanks for the explanation and apologies for my unclear question. 
I wanted to know, which datastructure consist the `inverted velocity` and corresponding `x` and `y` coordinates. So I can plot the results externally, may be by using matplotlib. 

Or, is there a way to perform any operation on inverted velocity (say, multiply it by some number) and use pygimli to plot result.

**Comment by halbmy** [comment]
The velocity vector `mgr.velocity` lives on the mesh `mgr.paraDomain`, i.e. its length equals the number of cells. Of course you can do any operation with the vector or to do operations with the mesh like translating, rotating or scaling to work in 3D. And yes, you can extract the cell centers `mgr.paraDomain.cellCenters()` for to have a point attribution.

**Comment by makeabhishek** [comment]
How to extract a the inverted velocity vector in a 1D slice passing throgh center?

**Comment by carsten-forty2** [comment]
```
pnts = [[0.0, 0.0], ] # list of probe points for your 1D slice through the center
vLine = pg.interpolate(mgr.paraDomain, mgr.velocity, pnts)
```

**Comment by makeabhishek** [comment]
I'm not sure why defining the probes using `linspace` is giving weird result however, defining individually its correct. 
This code seems like sorting automatically. 
```
pnts = np.linspace((-0.06,0.0),(0.06,0.0),15)
pnts = np.array(pnts)
pnts = np.round(pnts,3)
vLine = pg.interpolate(mgr.paraDomain, np.array(mgr.velocity), pnts)
plt.plot(pnts[:,0],vLine,'*k', markersize=8)
```

Defining this way works well.
```
pnts = [[-0.06, 0.00],[-0.055, 0.00],[-0.058, 0.00],[-0.05, 0.00], [-0.04, 0.00],[-0.03, 0.00],[-0.02, 0.00],[-0.01, 0.00],[0.0, 0.0],
        [0.01, 0.00],[0.02, 0.00],[0.03, 0.00], [0.04, 0.00],[0.045, 0.00],[0.05, 0.00],[0.055, 0.00],[0.058, 0.00],
        [0.059, 0.00],[0.06, 0.00]] # list of probe points for your 1D slice through the center
vLine = pg.interpolate(mgr.paraDomain, mgr.velocity, pnts)
pnts=np.array(pnts)

```

Any Idea?

**Comment by carsten-forty2** [comment]
Thanks for pointing this out. 
The `pnts` arguments were wrongly interpreted in case of beeing a numpy array. Fixed it in dev branch and added a test for it.

**Comment by makeabhishek** [comment]
Does `(mgr.paraDomain`) not work with region wise regularization? As pointed out in #738.
