### ISSUE TITLE
Compilation of Gimli breaks when compiling `gimli/gimli/core/src/matrix.cpp`, because on line 275, the variable `retTrans` is not defined. 

### ISSUE THREAD

**Issue by AlainPlattner** [gimli-org/gimli#531]
### Problem description

Compilation of Gimli breaks when compiling `gimli/gimli/core/src/matrix.cpp`, because on line 275, the variable `retTrans` is not defined. This is likely because of the commenting out of `retTrans` on lines 207 and 228. Florian had commented these out on March 30 or so. 

For now I just uncommented lines 207 and 228 of `gimli/gimli/core/src/matrix.cpp`

**Comment by carsten-forty2** [comment]
yes you are right .. thanks for pointing this out. 

This only occurs if you don't use openblas. We strongly recommend openblas and use it on all platforms so we did not stumble into this bug before. However, these code fragments are for some further developing's and not used in the current master or dev branch.

**Comment by AlainPlattner** [comment]
Klasse, danke. Ich probier's mal mit OpenBLAS.
