### ISSUE TITLE
Output of Jacobian matrix（TravelTimeDijkstraModelling）

### ISSUE THREAD

**Issue by zzerror** [gimli-org/gimli#533]
### Problem description

Hi, I have a question about Jacobian calculation for TravelTime data.
 I am trying to obtain the Jacobian matrix using the following code：

fop=traveltime.modelling.TravelTimeDijkstraModelling()
fop.setData(scheme)
fop.setMesh(mesh)
fop.createJacobian(vel)
jacobian=fop.jacobian()
print(jacobian)

But its output is as follows:

<pgcore._pygimli_.RSparseMapMatrix object at 0x000001ECFA6CAFA0>

Not a matrix.I want to know how to obtain a matrix.I tried running other examples as follows:

fob = ert.ERTModelling()
fob.setData(scheme)
fob.setMesh(mesh)
fob.createJacobian(model)
Jacobian=fob.jacobian()
print(np.array(Jacobian))

It can effectively obtain a matrix.

### Your environment

Please provide the output of `print(pygimli.Report())` here. If that does not
work, please give provide some additional information on your:

**Operating system**:Windows
**Python version**:  3.8
**pyGIMLi version**: 1.3.0
**Way of installation**: Conda package

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```fop=traveltime.modelling.TravelTimeDijkstraModelling()
fop.setData(scheme)
fop.setMesh(mesh)
fop.createJacobian(vel)
jacobian=fop.jacobian()
print(jacobian)
...
```

### Expected behavior

A list or numpy array.

### Actual behavior

```
<pgcore._pygimli_.RSparseMapMatrix object at 0x000001ECFA6CAFA0>
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by carsten-forty2** [comment]
`RSparseMapMatrix` is an internal type of a coo sparse matrix you can convert them into scipy.sparse matrix object with: `pygimli.utils.toCOO`

**Comment by zzerror** [comment]
@carsten-forty2 Thank you very much for your reply.I have another question about inversion.
I am trying to find a function in Pygimli that takes the derivative of phiD（data objective function ） in the total objective function, but I cannot find it. So what do I need to do?

**Comment by halbmy** [comment]
The gradient of phiD is the (left-handed) dot product of the Jacobian matrix and the misfit function (d-f(m)), additionally the data weighting comes into play, plus data and model transformations. I agree that it would make sense to provide such a function and will implement it.

By the way, the Jacobian in traveltime inversion takes the slowness vector and not the velocity. Usually, we invert for the logarithms.

**Comment by zzerror** [comment]
@halbmy Thank you very much.
