### ISSUE TITLE
Unable to install pybert to load an existing ERT scheme

### ISSUE THREAD

**Issue by andreapalacios01** [gimli-org/gimli#535]
### Problem description

Hello,
I want to simulate a 2D ERT model, with a borehole at each side. Each borehole has sensors, and so I have a scheme that was created externally (not by Pygimli). I would like to load this ".dat" file, but I'm unable to do it using only pygimli. You suggest to install pybert, but this has been impossible. Either an error to connect to the server, or incompatibility between packages. 
Do you know of a way to make it work? Alternatively, do you know how I can create an ERT scheme with a crosshole configuration? 

Thank you very much in advance for your help! 

Best,
Andrea Palacios

### Your environment
**Operating system**: Windows
**Python version**: 3.9
**pyGIMLi version**: 1.4.0
**Way of installation**: Anaconda

**Comment by andreapalacios01** [comment]
Yes, of course. I attach the file. 
[scheme.txt](https://github.com/gimli-org/gimli/files/11514823/scheme.txt)

**Comment by halbmy** [comment]
This is a standard pyGIMLi data format, so you don't need pyBERT for it. 
```
# Number of electrodes
40
# x z
0.000 0.005 
0.000 0.015 
...
0.200 0.185 
0.200 0.195 
# a b m n rhoa
1 21 2 220
1 21 2 230
```
It just has a bunch of errors in it:
* the number of data points is missing, i.e. a line 21692 before the token line
* the token line `# a b m n rhoa` defines the meaning of the data column, in your file you have just a b m n but no rhoa
* the last column contains values outside the list of the 40 electrodes, I guess you have to split the 0 at the end?
This should work well:
```
40 # Number of electrodes
# x z
0.000 0.005 
0.000 0.015 
...
0.200 0.185 
0.200 0.195 
21692  # number of data
# a b m n
1 21 2 22
1 21 2 23
```

**Comment by andreapalacios01** [comment]
Great! That was simple to solve :)
Thank you very much. 
Andrea
