### ISSUE TITLE
Subject: Question regarding PyGimli seismic travel time calculation

### ISSUE THREAD

**Issue by zzerror** [gimli-org/gimli#538]
### Problem description

 @halbmy @carsten-forty2 ,I'm sorry to bother you again.
I have been using both "pg.core.TravelTimeDijkstraModelling" and "traveltime.modelling.TravelTimeDijkstraModelling" with the same mesh, scheme, and model inputs. However, I have noticed some discrepancies that I am hoping you can shed some light on:

1.When I output the forward responses, I notice that the travel times are different. Are these discrepancies due to the different modules, and which one should I trust?

2.Similarly, when I output the Jacobian matrices, I notice that there are significant differences. How can I interpret these differences?

3.I expect the Jacobian matrix to be of size m x n (where m is the number of data points and n is the number of model parameters). However, in "pg.core.TravelTimeDijkstraModelling", this is not the case. I suspect that each row represents the length of the travel path of the refracted wave. In "traveltime.modelling.TravelTimeDijkstraModelling", the Jacobian matrix size is correct, but the transpose matrix has many rows with zero values. This has caused problems when I used the transpose matrix to calculate the data gradient of the objective function. Could you please point out where I may have gone wrong?

I would appreciate any insights you can provide on these issues. Thank you for your time and attention.

### Your environment

Please provide the output of `print(pygimli.Report())` here. If that does not
work, please give provide some additional information on your:

**Operating system**: Windows
**Python version**: 3.8
**pyGIMLi version**: 1.3.0
**Way of installation**: Conda package

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import traveltime

pyvista = pg.optImport("pyvista")
x=np.arange(-50.,51.,10)
y=np.arange(-50,51.,10)
z=np.arange(-50.,1.,10)
mesh=mt.createGrid(x=x,y=y,z=z)

vel=np.zeros(len(pg.x(mesh.cellCenters())))
pg_z=pg.z(mesh.cellCenters())
for i,j in enumerate(pg_z):
    if j >= -10.:
        vel[i]=200.
    elif j >= -20 and j<-10:
        vel[i]=400.
    else:
        vel[i]=650.

yy = np.arange(-50, 51, 20)
sensors = []
sensors.append([10, -50., 0.])
for i in yy:
            sensors.append([i, 50., 0.])
scheme = pg.physics.traveltime.createRAData(sensors)
scheme.markInvalid(scheme("s") > 0)
scheme.set("t", np.zeros(scheme.size()))
scheme.removeInvalid()

fop=pg.core.TravelTimeDijkstraModelling(mesh, scheme)
fop.createJacobian(vel)
jacobian=fop.jacobian()
print(fop.response(1/vel))

fop1=traveltime.modelling.TravelTimeDijkstraModelling()
fop1.setData(scheme)
fop1.setMesh(mesh)
fop1.createJacobian(vel)
jacobian1=fop1.jacobian()
print(fop1.response(1/vel))

print(pg.utils.toCOO(jacobian))
print(pg.utils.toCOO(jacobian1))
```

### Expected behavior

Tell us what should happen or what you want to achieve.

### Actual behavior

Tell us what happens instead and/or provide the output of your script.

```
[0.33202269926078665, 0.3192776665723837, 0.3065326338839808, 0.29378760119557784, 0.3065326338839808, 0.3192776665723837]
[0.3150452531517691, 0.3017347191035545, 0.2924424291209849, 0.2886545637173643, 0.2924424291209849, 0.3017347191035545]
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
Sorry for responding so late. Actuallly, there is only one modelling operator in the core (C++), but the Python implementation automatically adds some secondary nodes to improve quality before calling the core operator. See the example
https://www.pygimli.org/_examples_auto/2_seismics/plot_03_rays_layered_and_gradient_models.html
for discussion on secondary nodes and a corresponding reference. You can easily see this by
```
print(fop.mesh())
print(fop1.mesh())
```
yielding
```
Mesh: Nodes: 726 Cells: 500 Boundaries: 1700
Mesh: Nodes: 726 Cells: 500 Boundaries: 1700 secNodes: 21075
```
So the latter one has improved accuracy due to secondary nodes, that's it.

**Comment by halbmy** [comment]
One should only use the Python implementation. The core is just for internal use and most relevant C++ operators have Python wrappers with simplified and robust behaviour.
