### ISSUE TITLE
Easy python access to c++ inversion framework

### ISSUE THREAD

**Issue by NicoSkibbe** [gimli-org/gimli#54]
I have a request for the easier interception of an inversion run.
I would like to recalculate certain things (e.g. my NMR kernel) after each iteration of the inversion process.

For now its 'just' possible to run the inversion with maxIter=1, do some stuff, and again run for 1 Iteration...

My suggestion is a simple little function in the c++ InversionBase or the inversion framework which is called between the iterations by default.
Something like the c++ equivalent to:
```python
def betweenIterations(self):
    pass
```
It would be just an empty dummy.
It would not alter the default inversion process !, but allow for a python interface to intercept the inversion without aborting the process.
The recalculation of my kernel would be as simple as:
```python
class INV(RInversion):
    def __init__(self, **kwargs):
        super(INV, self).__init__(**kwargs)  # INV as simple Wrapper for RInversion
    def betweenIterations(self):  # override the default dummy class_function
        self.FOP.recalculateKernel(self.actualResitivityDistribution)
        # or more general: recalculate something each iteration
        return
INV.run()  # normal run of inversion, like always
```

**Comment by florian-wagner** [comment]
:+1: I like the idea to have something like `betweenIterations` that the user can fill for various purposes. But if you mean the sensitivity kernel, i.e. Jacobian matrix, this is already possible by:

``` python
class ForwardOperator(pg.ModellingBase):
    ...
    def createJacobian(model):
        """Create Jacobian matrix for a given model."""
        ...
        return J
```
As the sensitvity is recalculated between iterations with the current `model` (`= self.actualResitivityDistribution`) by default.

**Comment by halbmy** [comment]
Well, the kernel calculation is a bad example as it is actually the Jacobian matrix and should go into the function createJacobian. However, one might want to make changes to the regularization, e.g. recalculating the constraint matrix (e.g. in a geostatistically based inversion) or the constraint weight (e.g. in the structurally coupled cooperative inversion). Of course this could for now also be done in the jacobian calculation even if it does not strictly belong here (but it is computed in every iteration and this is what counts). However the problem might be to pass something into this function, e.g. the resistivity from a cooperatively running resistivity inversion.
I would suggest putting it into the inversion frameworks and probably we will drop the C++ inversion class anyway in favour of a pure Python inversion.

**Comment by NicoSkibbe** [comment]
Thanks for the fast response(). I will add the modifications i had in mind to the createJacobian() function, like you suggested Florian and for more interactive communications in a joint approach a maxIter = 1 will do fine for my purpose.

**Comment by carsten-forty2** [comment]
We plan to rewrite the basic inversion framework as pure python method. There we can add such pre/postStep() interfaces.

Until then, maxIter=1 will work .. at the best with ```inv.oneStep()```

Currently inv.run() works like this: (inversion.h:915++)
```
run():
    initialize stuff
    repeat until abort criteria reached:
           oneStep()
           do some post process and store results
           recalc abort criteria
```

So best run once with maxiter=1 and follow up with oneStep() to avoid the reinitialising

**Comment by halbmy** [comment]
I am closing this as there is no fast solution now (before we switch the inversion to Python) and after it things will be different anyway (and easy to be changed by developers)
