### ISSUE TITLE
Error using regionwise regularisation

### ISSUE THREAD

**Issue by makeabhishek** [gimli-org/gimli#542]
### Problem description
I'm trying to set a region at a particular slowness and perform traveltime inversion, geometry shown below.
![geom](https://github.com/gimli-org/gimli/assets/47937684/378a09c6-9e47-44c5-a62b-888c81276e7b)

 
Please describe your issue here.
While setting the region to a constant slowness. It is giving the error. 

### Your environment

Please provide the output of `print(pygimli.Report())` here. If that does not
work, please give provide some additional information on your:

OS : Linux
            CPU(s) : 40
           Machine : x86_64
      Architecture : 64bit
               RAM : 62.5 GiB
       Environment : Jupyter
       File system : ext4

  Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03)
  [GCC 11.3.0]

           pygimli : 1.3.1
            pgcore : 1.3.0
             numpy : 1.20.3
        matplotlib : 3.5.1
             scipy : 1.10.1
           IPython : 8.11.0
           pyvista : 0.34.2

**Operating system**: e.g. Windows, Linux or Mac?
**Python version**: e.g. 3.8, 3.9, etc.?
**pyGIMLi version**: Output of `print(pygimli.__version__)`
**Way of installation**: e.g. Conda package, manual compilation from source, etc.

### Steps to reproduce
```
import matplotlib.pyplot as plt
import numpy as np
import pygimli as pg
from pygimli.physics import TravelTimeManager
import pygimli.physics.traveltime as tt
import pygimli.meshtools as mt

from pygimli.meshtools import quality
import pyvista as pv
import pygimli.viewer.pv
from scipy.io import loadmat
import matplotlib as mpl 
from pygimli.viewer.mpl import showVecMatrix
# For displaying data we define a function
def showData(data, vals, **kwargs):
    d = pg.y(data)  # sensor depth
    ds = d[data["s"]]  # shot depth
    dg = d[data["g"]]  # geophone depth
    ax, cb = showVecMatrix(ds, dg, vals, label="apparent velocity (m/s)", **kwargs);
    ax.set_xlabel("Source depth");
    ax.set_ylabel("Receiver depth");

filename = "traveltimeSynthetic.dat"

data = tt.load(filename)
mgr = tt.TravelTimeManager(data, verbose=True)
print(data)

# visualise data
tt.showVA(data, usePos=True)
ax, cbar = mgr.showData()
fig, ax = pg.plt.subplots()
tt.drawFirstPicks(ax, data)

print('Data-container cosnsist',data)
mgr = tt.TravelTimeManager(data, verbose=True)

Dout = 0.20
Din = 0.16

circle_outer = mt.createCircle(
    pos=[0.0, 0.0],
    radius=Dout,
    nSegments=64,
    marker=1,
    markerPosition=[Dout*0.995, 0.0],
)

circle_inner = mt.createCircle(
    pos=[0.0, 0.0],
    radius=Din,
    nSegments=64,
    boundaryMarker=0,
    marker=2,
    markerPosition=[Din*0.995, 0.0],
)

geom = circle_outer + circle_inner

ax, cb = pg.show(geom, markers=True, regionMarkers=True)

fig = ax.get_figure();
for nr, marker in enumerate(geom.regionMarkers()):
    print('Position marker number {}:'.format(nr + 1), marker.x(), marker.y(), marker.z());
    ax.scatter(marker.x(), marker.y(), s=(2 - nr) * 30, color='k');
    ax.plot(pg.x(data), pg.y(data), "r^");
ax.set_title('marker positions - working example');
fig.show();

mesh = mt.createMesh(geom, quality=34.4)
for b in mesh.boundaries():
    if b.marker() == -1 and not b.outside():
        b.setMarker(2)

print(mesh)
pg.show(mesh, markers=True, showMesh=True);

# import pygimli.physics.traveltime as tt
mgr = tt.TravelTimeManager(data, verbose=True)
mgr.setMesh(mesh)
mgr.inv.setRegularization(1, background=True, fix=1/2500 )
velInv = mgr.invert(lam=50, useGradient=False, secNodes=2, verbose=True) 

ax, _ = mgr.showResult(cMin=min(velInv), cMax=max(velInv), logScale=False)
pg.show(geom, ax=ax, fillRegion=False, regionMarker=False)
```

### Expected behavior

Perform a traveltime inversion to obtain the velocity map inside the circular geometry. Outside layer shown in the above image should have almost consatnat slowness, howver for yellow region (2), there is a change in velocity.

### Actual behavior

Tell us what happens instead and/or provide the output of your script.

```
`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[6], line 5
      3 mgr.setMesh(mesh)
      4 mgr.inv.setRegularization(1, background=True, fix=1/2500 )
----> 5 velInv = mgr.invert(lam=50, useGradient=False, secNodes=2, verbose=True) 
      7 ax, _ = mgr.showResult(cMin=min(velInv), cMax=max(velInv), logScale=False)
      8 pg.show(geom, ax=ax, fillRegion=False, regionMarker=False)

File ~/anaconda3/envs/pg/lib/python3.9/site-packages/pygimli/physics/traveltime/TravelTimeManager.py:247, in TravelTimeManager.invert(self, data, useGradient, vTop, vBottom, secNodes, **kwargs)
    244 else:
    245     self.fop._useGradient = None
--> 247 slowness = super().invert(data, mesh, **kwargs)
    248 velocity = 1.0 / slowness
    249 self.fw.model = velocity

File ~/anaconda3/envs/pg/lib/python3.9/site-packages/pygimli/frameworks/methodManager.py:793, in MeshMethodManager.invert(self, data, mesh, startModel, **kwargs)
    790     self.fw.blockyModel = kwargs["blockyModel"]
    792 self.preRun(**kwargs)
--> 793 self.fw.run(dataVals, errorVals, **kwargs)
    794 self.postRun(**kwargs)
    795 return self.paraModel(self.fw.model)

File ~/anaconda3/envs/pg/lib/python3.9/site-packages/pygimli/frameworks/inversion.py:587, in Inversion.run(self, dataVals, errorVals, **kwargs)
    584 if self._preStep and callable(self._preStep):
    585     self._preStep(0, self)
--> 587 self.inv.start()
    588 self.maxIter = maxIterTmp
    590 if self._postStep and callable(self._postStep):

File ~/anaconda3/envs/pg/lib/python3.9/site-packages/pygimli/physics/traveltime/modelling.py:84, in TravelTimeDijkstraModelling.createJacobian(self, par)
     81 if not self.mesh():
     82     pg.critical("no mesh")
---> 84 return self._core.createJacobian(par)

RuntimeError: /home/carsten/miniconda3/envs/build/conda-bld/pgcore_1661190390662/work/gimli/core/src/sparsematrix.h:342		GIMLI::SparseMapMatrix<ValueType, IndexType>::MatElement GIMLI::SparseMapMatrix<ValueType, IndexType>::Aux::operator[](IndexType) [with ValueType = double; IndexType = long unsigned int; GIMLI::SparseMapMatrix<ValueType, IndexType>::MatElement = GIMLI::MatrixElement<double, long unsigned int, std::map<std::pair<long unsigned int, long unsigned int>, double, std::less<std::pair<long unsigned int, long unsigned int> >, std::allocator<std::pair<const std::pair<long unsigned int, long unsigned int>, double> > > >]  idx = 18446744073708551615, 0 maxcol = 394 stype: 0
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

Here is the data file. 
[traveltimeSynthetic.txt](https://github.com/gimli-org/gimli/files/11628839/traveltimeSynthetic.txt)

**Comment by halbmy** [comment]
OK, I have the same problem also for v1.4.1, meaning that region 1 is background by default and needs to set by `mgr.inv.setRegularization(background=False)`. Fixing the slowness leads to the same problem, so the only choice I see now is to narrow the limits by `mgr.inv.setRegularization(1, limits=[1/2600, 1/2400])` and a starting model of 1/2500. However, the data does not show such an influence
![image](https://github.com/gimli-org/gimli/assets/7136401/b7d4f24a-4c50-497c-b5a9-09690951b23e)
It looks rather erratic and is not at all symmetric (as it should be), so I doubt you can make much of it.

**Comment by makeabhishek** [comment]
I also tried with the latest version and have the same issue. Now tried by setting regularization as  suggested,
```
mgr.inv.setRegularization(background=False)
mgr.inv.setRegularization(1, limits=[1/2600, 1/2400])
```
Do you have any suggestion to make further improvements in any?


Furthermore, how can I force the chi^2 value to go a given limit, because currently the inversion stop automatically reaching at some value.

Thanks

**Comment by halbmy** [comment]
I guess you're missing an `e-3` in the `Din = 123/2` definition?

**Comment by makeabhishek** [comment]
> I guess you're missing an `e-3` in the `Din = 123/2` definition?

Yeah, sorry that was a typo, `Din = 123e-3/2`

**Comment by halbmy** [comment]
The smoothness looks like a synthetic example and not measured one? From the apparent velocity

![image](https://github.com/gimli-org/gimli/assets/7136401/08cb6631-9712-4899-bc90-7204738bcd59)

It looks like the outer ring could have something like 500m/s and the inner like 2000.

**Comment by makeabhishek** [comment]
The data is obtained from the measured one. It should be ranging as you described. But the outer ring should have the velocity of around 6000 m/s, which is not in the data. Therefore, I want to fix the outer ring to the given slowness in region wise regularization.

**Comment by halbmy** [comment]
I don't see it in the data. The rays between the smallest distances should mainly go through the outer ring and the apparent velocity is rather 500 m/s.

**Comment by makeabhishek** [comment]
yeah, that is not in the data, because it is not considered in calculating travel time. This is the reason I was thinking to fix the outer region to a particular velocity and just invert the inner region. But, fixing the slowness at particular value (say around 6000 m/s) is throwing error. 

Is it possible to consider multiple arrival time for same shot and gather points? For example using different arrival time for outer ring and other travel time for inner ring. This is because of different waves traveling in different regions(inside and outside).

**Comment by halbmy** [comment]
The first-arrival time for a fixed shot-geophone combination is uniquely defined by the velocity distribution. Other waves might take different ways but will be slower. So I don't get your point.

Again: this data (I doubt that these have been measured) does not indicate a high-velocity outer ring. Please run a synthetic model and have a look at it.

**Comment by makeabhishek** [comment]
Hi @halbmy,
Thanks for patiently answering my queries. 

Outside layer shown in the model is a metallic layer, where the velocity is higher and inside medium is fluid with lower velocity. Measured data contains guided waves, bulk waves and other mode converted waves. However, the travel-time for a particular shot-geophone in the text file contains the traveltime based on bulk waves (P-wave), no guided wave data is considered. The objective is to invert the fluid velocity while keeping the outside layer (metal) velocity keeping constant. 

The first data I shared in the starting of this problem is from synthetic but with different dimensions.
