### ISSUE TITLE
Attenuation tomography using pygimli.

### ISSUE THREAD

**Issue by makeabhishek** [gimli-org/gimli#546]
Hi,
Looking for an example to perform attenuation tomography using pygimli.

What kind of data is required, and is there forward and inverse operator available?

**Comment by halbmy** [comment]
You can just insert another data column into the DataContainer so that every traveltime is accompagnied by an amplitude (which should ideally be source-normalized). If taking log-amplitude, the forward operator is just a linear operator using the jacobian of the traveltime problem. For inversion we use the usual frameworks. If you have some data, I can generate an example.

**Comment by halbmy** [comment]
Note that there has already been a discussion about attenuation tomography: https://github.com/gimli-org/gimli/discussions/311

**Comment by makeabhishek** [comment]
Thanks @halbmy for referring the link. I' looking that and see what can be done. Does amplitude in data file needs to be in log scale?  Does it need to be in damping coefficient in dB/m?

**Comment by halbmy** [comment]
In the data file, the amplitude should not be logarithmic, because later the log is taken.

As the issue is two years old, the script is outdated and the new (pg>1.2) inversions cannot be used with old (pg 1.0) modellings. We have to implement LinearModelling based on `pg.Modelling` but that is super easy.

**Comment by halbmy** [comment]
> Does it need to be in damping coefficient in dB/m?

No, the data should be amplitude (in whatever unit), if possible normalized to initial amplitude.

The model will contain the damping coefficient.

**Comment by makeabhishek** [comment]
I tried following with the given data in #311.

```
import pygimli as pg
import pygimli.meshtools as mt
import pygimli.physics.traveltime as tt
import numpy as np
import matplotlib.pyplot as plt
import pickle

bh_spacing = 500
bh_length = 500
sensor_spacing = 10
world = mt.createRectangle(start=[0, (bh_length + 0.01)],
                           end=[bh_spacing, 0.0],
                           marker=0)

data = pg.DataContainer("data.txt", "s g")

mgr = tt.TravelTimeManager()
mgr.applyData(data)
refinement = 1
x = np.arange(0, bh_spacing + refinement, sensor_spacing * refinement)
y = np.arange(0.0, bh_length + 3, sensor_spacing * refinement)
mesh = pg.meshtools.createGrid(x, y)

# ax, _ = pg.show(mesh, hold=True)
# mgr.inv.inv.setRecalcJacobian(False)  # with RAY BENDING
invmodel = mgr.invert(data, mesh=mesh, secNodes=3, lam=800, zWeight=1,
                      useGradient=False, verbose=False)

fig, ax2 = plt.subplots(1, 1, figsize=(8, 7), sharex=True, sharey=True)

mgr.showResult(ax=ax2, logScale=False, nLevs=3)
mgr.drawRayPaths(ax=ax2, color="0.8", alpha=0.3)
fig.tight_layout()

dist = tt.shotReceiverDistances(data, full=True)
ax, cb = pg.viewer.mpl.showDataContainerAsMatrix(data, "g", "s", "a",
                                                 label="amplitude")
ax.set_xlabel("Geophone index")
ax.set_ylabel("Shot index")
```

For forward modelling of attenuation, I followed the below code. But as you mentioned that it need to be changed as per the new pygimli version. 

```
# %%
# %%
J = mgr.fop.jacobian()
amp = np.exp(-J.mult(np.ones(mesh.cellCount())*0.005))
print(min(amp), max(amp))
appAtt = - np.log(data["a"]) / dist
ax, cb = pg.viewer.mpl.showDataContainerAsMatrix(data, "g", "s",
                                                 # appAtt, label="app att")
                                                 amp, label="amplitude")
ax.set_xlabel("Geophone index")
ax.set_ylabel("Shot index")
# %%
fAtt=pg.core.LinearModelling(J, -1)  #Get jacobian from Travel Time
fAtt.setMesh(mesh)
att = pg.Vector(mesh.cellCount(), 0.01)
tLog = pg.trans.TransLog()
fAtt.modelTrans = tLog
inv = pg.Inversion(fop=fAtt)
inv.transModel = tLog
dataVec = - np.log(data["a"])
error = np.ones_like(dataVec) * 0.01
```

# Perform inversion
```
model = inv.run(dataVec, error, startModel=att)
pg.show(mesh, model)
# %%
resp = np.log(fAtt(att))
ax, cb = pg.viewer.mpl.showDataContainerAsMatrix(data, "g", "s", resp)
```

May I seek your guidance to modify it based on `pg>1.2`
[data.zip](https://github.com/gimli-org/gimli/files/11828908/data.zip)


Attached is the data.

**Comment by halbmy** [comment]
you basically have to replace `pg.core.LinearModelling` by 
```
fAtt=pg.frameworks.LinearModelling(J)
```
Then you instantly get a meaningful result:
![image](https://github.com/gimli-org/gimli/assets/7136401/9f81370b-dbc3-4e8f-be63-9ff0edb9d452)

**Comment by halbmy** [comment]
Added a notebook at https://github.com/gimli-org/notebooks/blob/main/issues/546/issue546.ipynb
