### ISSUE TITLE
Spyder incompatibility with pygimli 1.4.1

### ISSUE THREAD

**Issue by whitmand** [gimli-org/gimli#550]
### Problem description
I recently updated Anaconda and pygimli to take advantage of the new tutorials and examples (Thanks!) . Unfortunately, there appears to be an incompatibility with Spyder (and probably Jupiter Notebooks as well)

In the base environment Spyder 5.4.3 installs but in the pg environment that version is incompatible and v 5.2.2 installs instead. When I launch Spyder 5.2.2, I get the following error:

Traceback (most recent call last):
File "C:\Users\deanw\anaconda3\envs\pg\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 29, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\deanw\anaconda3\envs\pg\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\deanw\anaconda3\envs\pg\lib\site-packages\spyder\app\start.py", line 233, in main
from spyder.app import mainwindow
File "C:\Users\deanw\anaconda3\envs\pg\lib\site-packages\spyder\app\mainwindow.py", line 57, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "C:\Users\deanw\anaconda3\envs\pg\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 37, in 
raise QtModuleNotInstalledError(
qtpy.QtModuleNotInstalledError: The QtWebEngineWidgets module was not found. It must be installed separately as PyQtWebEngine.

I tried this with version 1.4.2 and get the same problem.
### Your environment
--------------------------------------------------------------------------------
  Date: Fri Jun 30 12:25:53 2023 Eastern Daylight Time

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.9 GiB
       Environment : Python

  Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:28:38) [MSC
  v.1929 64 bit (AMD64)]

           pygimli : 1.4.1
            pgcore : 1.4.0
             numpy : 1.21.6
        matplotlib : 3.7.1
             scipy : 1.11.1
           IPython : 7.31.1
           pyvista : 0.39.1
--------------------------------------------------------------------------------
Please provide the output of `print(pygimli.Report())` here. If that does not
work, please give provide some additional information on your:

**Operating system**: Windows 11

**Way of installation**:  Conda package, 
### Steps to reproduce
(base) C:\Users\deanw> conda create -n pg -c gimli -c conda-forge pygimli=1.4.1
(base) C:\Users\deanw>conda activate pg
(pg) C:\Users\deanw>conda install -c conda-forge spyder
(pg) C:\Users\deanw> spyder

### Expected behavior

Tell us what should happen or what you want to achieve.

### Actual behavior

Tell us what happens instead and/or provide the output of your script.

```
Traceback (most recent call last):
File "C:\Users\deanw\anaconda3\envs\pg\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 29, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\deanw\anaconda3\envs\pg\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\deanw\anaconda3\envs\pg\lib\site-packages\spyder\app\start.py", line 233, in main
from spyder.app import mainwindow
File "C:\Users\deanw\anaconda3\envs\pg\lib\site-packages\spyder\app\mainwindow.py", line 57, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "C:\Users\deanw\anaconda3\envs\pg\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 37, in 
raise QtModuleNotInstalledError(
qtpy.QtModuleNotInstalledError: The QtWebEngineWidgets module was not found. It must be installed separately as PyQtWebEngine.

```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".
installation

**Comment by halbmy** [comment]
This is not really related to pyGIMLi, but a pure Spyder issue with missing dependencies. I remember having similar problems. I guess you have to install PyQTWebEngine by `conda install pyqtwebengine -c conda-forge`

**Comment by whitmand** [comment]
Your suggestion worked. I had tried this earlier but I didn't include the "-c conda-forge" It also allowed me to install the most recent version of spyder=5.4.3
thanks

**Comment by halbmy** [comment]
Great to hear. There seems to be problems when mixing default channels with the conda-forge channel. Plus, conda is super-slow. I guess, mambaforge, the fast alternative mamba plus everything pre-configured for conda-forge only, could be a clean solution.
