### ISSUE TITLE
some questions about 2d crosshole ert based on # 169

### ISSUE THREAD

**Issue by shdlovezxm** [gimli-org/gimli#555]
### Problem description

hello, I want to calculate the forward simulation of cross-hole ERT, but I don't know how to generate ABMN.

####The #169 code contains the following code

####read the scheme for borehole from agi software
read_scheme = np.loadtxt('schemedata.dat')  # created by AGI software
scheme.resize(read_scheme.shape[0])
for i, tok in enumerate(['a', 'b', 'm', 'n']):
    scheme.set(tok, read_scheme[:, i]-1)

####How to generate ABMN using pygimli instead of using AGI software?

scheme = ert.createData(elecs=pg.utils.grange(start=0, end=63, dx=1.0),
                       schemeName='dd')

####change the electrodes position
pos = np.array(scheme.sensorPositions())  # get xyz coor for electrodes

####borehole 1
pos[0:32, 0] = 0

for i in range(1, 33, 1):
    pos[i-1, 2] = -i
    
####borehole 2
pos[32:64, 0] = 12
for i in range(1, 33, 1):
    pos[i+31, 2] = -i
    
scheme.setSensorPositions(pos)  # reset the position for electrodes
print(scheme)
print(pos)

I generated electrode positions, how do I generate ABMN?

Thank you and look forward to your reply.

**Comment by halbmy** [comment]
There is no such thing as standard crosshole arrays like it is for surface ERT. So there is no generator like `ert.createData` for crosshole geometries. You will have to think about such arrays by yourself. The following notebook 
https://github.com/gimli-org/notebooks/blob/main/ERT/crosshole/CrossholeERTArrays.ipynb
may help to get some methodology, differentiating between the following array types:
* inhole (ABMN-) 
* cross-dipoles (AB-MN)
* cross-bipoles (AM-BN)
* cross-pole-dipole (AMN-B)

So one could write some loops to generate a full set for each of the four types.

**Comment by shdlovezxm** [comment]
thank you very mush.

**Comment by halbmy** [comment]
I am closing as it seems to be answered. Note that since the referred issue a lot of things have developed like the 2D (or also 3D) crosshole ERT example https://www.pygimli.org/_examples_auto/3_dc_and_ip/plot_06_crosshole2d.html or notebooks like this here https://github.com/gimli-org/notebooks/blob/main/ERT/crosshole/CrossholeERTArrays.ipynb
