### ISSUE TITLE
ERT data configuration filter

### ISSUE THREAD

**Issue by tabdivider** [gimli-org/gimli#556]
Date: Wed Jul 05 15:08:55 2023 

                OS : Windows
            CPU(s) : 20
           Machine : AMD64
      Architecture : 64bit
       Environment : Python

  Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:45)
  [MSC v.1929 64 bit (AMD64)]

           pygimli : 1.3.1
            pgcore : Version unknown
             numpy : 1.22.3
        matplotlib : 3.5.1
             scipy : 1.8.0
            meshio : 5.3.4
           pyvista : 0.34.2

Dear gimli team and users.

I have an ERT data file measured on the same line using multiple configurations (DD, WS, WA) into one measurement file. If i import the data into pygimli and plot the raw data by `emgr.showData(data)` the data are nicely sorted based on the configurations and depth. I would like to make an inversion of all measurements together, but also individually for each configuration, e.g. WA. Sure I can filter the data manually, but I wonder if there is some smart code implementation on how to filter ERT data based on the configuration?

Thanks in advance!

**Comment by halbmy** [comment]
Sure you can filter them. By `data['a']`, `data['b']`, `data['m']`, `data['n']` you can access the electrode indices, so you can use logical operators like `data.remove(data['b'] - data['a'] > data['n'] - data['m'])` to filter out non-DD data etc.

**Comment by tabdivider** [comment]
OK, this is a good inspiration how to handle and filter the arrays. Thanks for your support!
