### ISSUE TITLE
How to create apparent resistivity data for diffusing resistive structure ?

### ISSUE THREAD

**Issue by Kaustav546** [gimli-org/gimli#557]
### Problem description
I have a resistivity model containing diffusive resistivity bodies, as depicted in the attached image. My objective is to calculate the apparent resistivity for this specific resistivity distribution. I would greatly appreciate any assistance or insights regarding this matter.
### Your environment

Please provide the output of `print(pygimli.Report())` here. If that does not
work, please give provide some additional information on your:

**Operating system**: Linux
**Python version**: 3.9
**pyGIMLi version**: 1.2.6
**Way of installation**: Conda package

### Steps to reproduce

```
import matplotlib.pyplot as plt
import numpy as np
import os
import cv2
import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import ert

path = "/home/user/Documents/ert_data_gen/GRF/00003.npy"
model = np.load(path)
plt.imshow(model)
model1 = cv2.resize(model, (18020,1), interpolation = cv2.INTER_NEAREST)
xmin, xmax = 0., 300.
zmin, zmax = 0., -60.

xreg = np.linspace(xmin, xmax, 300)
zreg = np.linspace(zmin, zmax, 60)
world = mt.createWorld(start=[0, 0], end=[300, -60],
                       worldMarker=True)
#mesh1 = mt.createGrid(xreg, zreg)

# mesh1.setCellMarkers([2]*mesh1.cellCount())



num_elec = 53   # number of electrodes
scheme = ert.createData(elecs=np.linspace(start=25, stop=275, num=50),
                            schemeName='dd')
for p in scheme.sensors():
    world.createNode(p)
    world.createNode(p - [0, 0.1])
mesh1 = mt.createMesh(world, quality=33, area=2.1444)
print(mesh1.cellCount(), len(model1.reshape(-1)))
pg.show(mesh1)
# area = 10
# while True:
#     mesh1 = mt.createMesh(world, quality=33, area=area)
#     if mesh1.cellCount() == len(model.reshape(-1)):
#         break
#     else:
#         area = area/2
# pg.show(mesh1)

#res = pg.meshtools.nodeDataToCellData(mesh1, model1.reshape(-1))
#print(res)
# changing the log values 
res = np.power(10,model1.reshape(-1))
#res = model1.reshape(-1)
data = ert.simulate(mesh1, scheme=scheme, res=res, noiseLevel=1,
                    noiseAbs=1e-6, seed=1337)
# Removing all negative values from the data
data.remove(data['rhoa'] < 0)
# Limiting the data to K less than 35000 because after certain depth it start capturing noise instead of signal
#data.remove(abs(data["k"])>100000)

ert.show(data)
plt.imshow(model)


```

### Expected behavior

The expected apparent apparent resistivity section is shown in figure 1

### Actual behavior

The actual apparent resistivity section is shown in figure 2

![diffusive resistivity model](https://github.com/gimli-org/gimli/assets/78998363/69216319-9b49-47a1-8eae-16edd7005d3e)
![1](https://github.com/gimli-org/gimli/assets/78998363/866595e6-3628-483d-afe3-5fa01053bd9f)
![2](https://github.com/gimli-org/gimli/assets/78998363/fb9ef739-e023-4457-a10e-28a964b013c3)

**Comment by halbmy** [comment]
A noise level of 1 means 100% error, this is the reason for negative values.

**Comment by Kaustav546** [comment]
so after I remove the noise level 1. The result is not close to the expected output. The result is in the attachment.
![3](https://github.com/gimli-org/gimli/assets/78998363/93e22179-81d7-48c5-8c1b-0bdbd784bb38)

However, if I am using a grid mesh with the same number of nodes as the number of elements in the matrix. Then I am getting an output like this 
![pygimli_0001](https://github.com/gimli-org/gimli/assets/78998363/d7743530-d4d4-4cfe-97f3-29fd4cc33995)
I am unsure of how to validate my results. Any input or suggestions regarding this matter would be greatly appreciated.

**Comment by halbmy** [comment]
Any news on that? I suggested to plot the models using grid/mesh approaches and compare these. I guess there is something wrong, but we cannot reproduce it without the model vector.

**Comment by halbmy** [comment]
Closing the issue due to inactivity and lack of information.
