### ISSUE TITLE
VESRhoModelling produces error when specifying an,am,bm,bn for data space

### ISSUE THREAD

**Issue by whitmand** [gimli-org/gimli#558]
### Problem description

I am trying to model and invert 1-d dipole-dipole soundings with VESRhoModeling by specifying arrays of am, an, bn, and bm in the data space. 
`f = VESRhoModelling(thk=thk, am=am,an=an,bm=bm, bn=bn)`. 
It returns an error when passing the parameters to `pg.core.DC1dRhoModelling` 

### Your environment

--------------------------------------------------------------------------------
  Date: Mon Jul 17 14:02:46 2023 Eastern Daylight Time

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.9 GiB
       Environment : Jupyter

  Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:28:38) [MSC
  v.1929 64 bit (AMD64)]

           pygimli : 1.4.2
            pgcore : 1.4.0
             numpy : 1.21.6
        matplotlib : 3.7.1
             scipy : 1.11.1
           IPython : 8.14.0
           pyvista : 0.40.0
--------------------------------------------------------------------------------
### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```
import numpy as np
import pygimli as pg
from pygimli.physics.ves import VESRhoModelling, VESManager

synRes = [0.445, 4.32]  # synthetic resistivity
synThk = [1.45]  # synthetic thickness (lay layer is infinite)
ves = VESManager()
# Dipole Dipole Sounding n= 1-->11
am=np.array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
an= np.array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.])
bm=np.array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
bn=np.array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
ves.fop.setDataSpace(am=am, an=an, bm=bm, bn=bn)
rhoa, error = ves.simulate(synThk+synRes, noiseLevel=0.03, seed=1337)
#Set up the forward operator
thk =[1.43]
f = VESRhoModelling(thk=thk, am=am,an=an,bm=bm, bn=bn)
```

### Expected behavior

Proceed to inversion

### Actual behavior

Tell us what happens instead and/or provide the output of your script.

```
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
Cell In[37], line 3
      1 #Set up the forward operator
      2 thk =[1.43]
----> 3 f = VESRhoModelling(thk=thk, am=am,an=an,bm=bm, bn=bn)

File ~\anaconda3\envs\pg\lib\site-packages\pygimli\physics\ves\vesModelling.py:420, in VESRhoModelling.__init__(self, thk, verbose, **kwargs)
    418 self.bfop = VESModelling(**kwargs)  # just to sort out AM, AN etc.
    419 self.thk = thk
--> 420 self.fwd = pg.core.DC1dRhoModelling(thk, self.bfop.am, self.bfop.bm,
    421                                     self.bfop.an, self.bfop.bn,
    422                                     verbose=verbose)
    423 self.mesh_ = pg.meshtools.createMesh1D(len(thk)+1)
    424 self.setMesh(self.mesh_)

ArgumentError: Python argument types in
    DC1dRhoModelling.__init__(DC1dRhoModelling, list, NoneType, NoneType, NoneType, NoneType)
did not match C++ signature:
    __init__(_object*, GIMLI::Vector<double> thk, GIMLI::DataContainer {lvalue} data)
    __init__(_object*, GIMLI::Vector<double> thk, GIMLI::DataContainer {lvalue} data, bool verbose=False)
    __init__(_object*, GIMLI::Vector<double> thk, GIMLI::Vector<double> ab2, GIMLI::Vector<double> mn2)
    __init__(_object*, GIMLI::Vector<double> thk, GIMLI::Vector<double> ab2, GIMLI::Vector<double> mn2, bool verbose=False)
    __init__(_object*, GIMLI::Vector<double> thk, GIMLI::Vector<double> am, GIMLI::Vector<double> an, GIMLI::Vector<double> bm, GIMLI::Vector<double> bn)
    __init__(_object*, GIMLI::Vector<double> thk, GIMLI::Vector<double> am, GIMLI::Vector<double> an, GIMLI::Vector<double> bm, GIMLI::Vector<double> bn, bool  #verbose=False)
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
Yes, this was indeed a silly bug not covered by a test because it did not occur for standard VES with AB/2 and MN/2 instead. I fixed it in the dev branch (60b3b057a81ddd69ce6d17032cf30e34cba1a756).

**Comment by halbmy** [comment]
To use it, you would have to check out the dev branch of pyGIMLi and override the conda installation via `conda develop` or PYTHONPATH, see also https://www.pygimli.org/installation.html#staying-up-to-date

**Comment by whitmand** [comment]
Can test the fix in by modifying the source code in anaconda3\envs\pg\Lib\site-packages\pygimli\physics\ves or will this "break" the installation? I am a little unsure about the procedures for setting up the develop branch

**Comment by halbmy** [comment]
Of course you can. A later update to a newer version will overwrite these changes.
