### ISSUE TITLE
Finite Difference and Different Grid in Different Layer

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#559]
Excuse Me, Sir

Is there a feature in Pygmili that allows us to set a different Grid resolution on each layer?
I want to try the Finite Difference Method and make each layer have a different grid.
I tried to model the following soil layers with the hope that each Marker 1 - 6 has a different Grid resolution. 

```
import numpy as np

import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import ert

world = mt.createWorld(start=[0, 0], end=[50, -10], layers=[-2, -6, -10],
                       worldMarker=True) #membuat lapisan bumi
anomaly = mt.createPolygon([[10,-3],[10,-5],[20,-5], [20,-3]],
                           isClosed=True, marker=5)
anomaly2= mt.createPolygon([[30,-3],[30,-5],[40,-5], [40,-3]],
                           isClosed=True, marker=6)
penampang = anomaly +anomaly2+ world
pg.show(penampang)

mesh1 = mt.createMesh(penampang, quality=32, area=10) #membuat mesh
pg.show(mesh1)
```

Thank you very much in advance

**Comment by carsten-forty2** [comment]
I don't think I get your question completely. 

1. You can control the mesh density with the `area` keyword for each polygon, which sets the maximum cell size.
2. To my knowledge you need some regular structured grids for Finite Difference (FD) calculations so an unstructured triangulation from `createMesh` based on a geometry PLC will not work at all for you.

Of course you can create a grid with `pg.meshtools.createGrid()` (https://www.pygimli.org/pygimliapi/_generated/pygimli.meshtools.html#pygimli.meshtools.createGrid), iterate over all cells and set a cell marker regarding the cell center position. In the end you get a mesh instance that might look like a FD grid but I have no idea if this might help you for custom FD calculations.
