### ISSUE TITLE
Is it possible to change the orientation of the region markers?

### ISSUE THREAD

**Issue by brianhavk** [gimli-org/gimli#560]
Hello again, I hope everything goes very well.

### Doubt description

I'm working on a model and want to know if it's possible to change the orientation of the region markers bar. By default, is horizontal, but I'll like a vertical orientation. I tried with color bar commands, but I see that region markers are different to a color bar.

### Steps to reproduce

Run in a Python notebook. The output image is as normally expected, but I expect to be able to have the horizontal orientation of the region markers:

```python
import matplotlib.pyplot as plt
import pygimli as pg
import pygimli.meshtools as mt

surface = mt.createPolygon([[833,2750], [941,2750], [1041,2739], [1500,2739], [1500,2572], [833,2572]],
                           isClosed=True, worldMarker=True)

bedrock = mt.createPolygon([[833,2750], [982,2702], [1195,2638], [1225,2572], [833,2572]], 
                            marker=1, isClosed=True)

sandAndClay1 = mt.createPolygon([[833,2750], [941,2750], [1041,2739], [1119,2715], [1301,2701], [1326,2692], [1301,2680], [1175,2677], [982,2702]], 
                                marker=2, isClosed=True)

sandAndClay2 = mt.createPolygon([[1341,2739], [1500,2739], [1500,2729], [1341,2729]], 
                                marker=2, isClosed=True)

bouldersAndGravel = mt.createPolygon([[1500,2637], [1500,2572], [1423,2572]], 
                                       marker=3, isClosed=True)

world = surface + bedrock + sandAndClay1 + sandAndClay2 + bouldersAndGravel

fig, ax = plt.subplots(figsize=(10,10))
ax, _ = pg.show(world, ax=ax, markers=False, regionMarker=True)
ax.set_xlim(832, 1500)
ax.set_ylim(2572, 2800)
ax.set_aspect(6)
```

### Output image
![World](https://github.com/gimli-org/gimli/assets/82900508/b265019b-3ce6-4609-ab60-59794df41068)

**Comment by carsten-forty2** [comment]
Thanks for pointing out. We missed to forward the colorbar orientation to the PLC drawing function. I fixed this right now.

`pg.show(world, ax=ax, markers=False, regionMarker=True, orientation='vertical')` now works for model, field, and plc view. 

Easiest workarround (until these changes become available with the next release) you can create a mesh from the plc and use the working model view.

```
mesh = mt.createMesh(world)

ax, cbar = pg.show(mesh, ax=ax, markers=True, regionMarker=False, boundaryMarkers=False, 
                orientation='vertical')
cbar.set_label('Region markers')
```

**Comment by brianhavk** [comment]
Thank you very much, in the end it was a color bar. I will be very attentive to the next update.

I leave the result of the view using the mesh, and the adjustment I used when using ax.set_aspect. Technically, a new color bar is created, but the base properties are those of the original color bar:

```python
mesh = mt.createMesh(world)

fig, ax = plt.subplots(figsize=(15,10))
ax, cbar = pg.show(mesh, ax=ax, markers=True, showMesh=False, boundaryMarkers=False, orientation="vertical")
ax.set_xlim(832, 1500)
ax.set_ylim(2572, 2800)
ax.set_aspect(6)
cbar.remove()

pos = ax.get_position()
cax = fig.add_axes([pos.x1-0.328, pos.y0+0.192, 0.013, pos.y1-pos.y0-0.384])
cbar = fig.colorbar(ax.collections[0], cax=cax)
cbar.set_ticks([0, 1, 2, 3])
cbar.set_label("Region markers")
```

## Output
![New world](https://github.com/gimli-org/gimli/assets/82900508/7c7d3966-1b95-4be0-ad6e-f2dbf0e54547)

**Comment by carsten-forty2** [comment]
good solution .. thanks for the reply.
