### ISSUE TITLE
Ray coverage for single shot in traveltime manager?

### ISSUE THREAD

**Issue by makeabhishek** [gimli-org/gimli#565]
Hi
How can we plot ray coverage for single shot in traveltime manager?
I performed traveltime inversion `velInv = mgr.invert(data, mesh=mesh, lam=2, useGradient=0, zWeight=1.0, secNodes=2)` and want to plot the ray coverage from the inverted results. I tried 
```
jacob = pg.utils.sparseMatrix2coo(mgr.fop.jacobian())
ray_coverage = jacob.sum(axis=0).A1 

fig = plt.figure()
ax = plt.axes()
pg.show(mesh, ray_coverage, ax=ax)
plt.show()
```

How to plot ray coverage from a single source?

**Comment by halbmy** [comment]
If you have only one shot in your data, then the ray coverage is only for that. Or do you mean a single shot-receiver combination? Then you can take a row of the Jacobian: `mgr.fop.jacobian().row(0)`

**Comment by makeabhishek** [comment]
I have multiple shots, but I want plot it for different shot-geophone combinations.

**Comment by halbmy** [comment]
As I explained before, one row of the Jacobian matrix corresponds to one shot-geophone combination. The vector has the length of the model, so you can plot it like a model, e.g. by `pg.show(mgr.paraDomain, mgr.fop.jacobian().row(i))`. It is basically showing the distances the ray travels through the individual cells, so it is closely related to `mgr.drawRayPaths`.

**Comment by makeabhishek** [comment]
Is it possible to plot the Jacobian of whole mesh as an image? I'm not sure fi I need to consider a single shot-geophone combination for such kind of plot or it can be combined for all shots?

**Comment by halbmy** [comment]
Each row of the Jacobianis for the whole mesh. If you mean the whole data (all rows summed up), then this is exactly the coverage `mgr.coverage()`. And any `mgr.showResult` forwards to `pg.show` where you can specify `showMesh=True` to plot the mesh boundaries.
