### ISSUE TITLE
issue in forward operator and set model in refraction inversion

### ISSUE THREAD

**Issue by makeabhishek** [gimli-org/gimli#566]
### Problem description

Please describe your issue here.

### Your environment

Please provide the output of `print(pygimli.Report())` here. If that does not
work, please give provide some additional information on your:

**Operating system**: Linux 
**Python version**: 3.9
**pyGIMLi version**: 1.4.1

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
import numpy as np
import pygimli as pg
from pygimli.physics import Refraction
import matplotlib
import pygimli.meshtools as mt

data   = pg.DataContainer("testData.txt")

geom = mt.createPolygon(data.sensors(), isClosed=True, addNodes=10, marker=1)
ax, cb = pg.show(geom, markers=True)
mesh = mt.createMesh(geom, quality=32.0, area=0.011e-3, smooth=[1, 10])
ax, _ = pg.show(mesh,showMesh=True, markers=True, hold=True)
# pg.show(mesh, data=data, label=pg.unit('vel'), showMesh=True, markers=True)

pos    = np.array(data.sensorPositions())
times  = np.array(data('t'))
m      = mesh.cellCount()
print(m, 'cells within the mesh')

ra     = Refraction(data)
ra.setMesh(mesh)

inv = ra.inv
type(inv)

fop = inv.fop()
type(fop)

vel_gradient = []
for node in mesh.nodes():
    vel_gradient.append( 1000 + (3000 * (abs(node.y()) ** 3)))

vel_gradient = pg.meshtools.nodeDataToCellData(mesh,np.array(vel_gradient))
pg.show(mesh, vel_gradient, label="Velocity (m/s)", cMin=1000, cMax=3000, logScale=False) 

inv.setModel(1/vel_gradient) # Set model to start from
inv.setReferenceModel(1/vel_gradient) 
inv.setData(times)
inv.setLambda(200)
inv.setRelativeError(0.001) #defining relative error
model = inv.run() # run the inversion

matplotlib.colors.Normalize()
pg.show(mesh,1/model,cMin=20,cMax=1000,colorBar=True,logScale=False,
        sensor=data.sensorPositions(),label="Velocity (m/s)")

fig, ax = plt.subplots()
rst.showResult(ax=ax, cMin=20, cMax=1000)
...
```

[testData.txt](https://github.com/gimli-org/gimli/files/12285769/testData.txt)

### Actual behavior

`TypeError: TravelTimeDijkstraModelling.response() missing 1 required positional argument: 'par'`

If I comment forward operator, first section runs successfully but issue with inversion operator
`AttributeError: 'Inversion' object has no attribute 'setModel'`

`ra.setDataContainer(data)` is also giving error

**Comment by halbmy** [comment]
I have no idea where you found this code that is clearly outdated (pg<1.1). 

`inv.fop` is the forward operator. If you add parentheses (`inv.fop()`), you call `inv.fop.response()` but without passing a model. So this does not make any sense, just like all subsequent calls using the old (C++) inversion.

Please have a look at the pygimli examples on how to use the inversion and manager classes properly.

**Comment by halbmy** [comment]
The code is far too complicating. A modern style looks like
```
import pygimli.physics.traveltime as tt

data   = tt.load("testData.txt")
mesh = ...
mgr = tt.TravelTimeManager(data)
model = mgr.invert(mesh=mesh, lam=200, relativeError=0.001)
mgr.showResult()
```
Gradient models are typically used for refraction but not for such a circular tomography. Of course you can do that, but it is easier by just adding `vBottom` and `vTop` keywords to `mgr.invert`.

**Comment by makeabhishek** [comment]
Thanks, yeah i took a look of the old issue #186. I want to check if it is not possible to implement refraction model to circular geometry? 
Furthermore, I realized that adding `vBottom `and `vTop` keywords to `mgr.invert`. doesn't influence the starting model in circular case.
