### ISSUE TITLE
Installation takes way too much time

### ISSUE THREAD

**Issue by kerim371** [gimli-org/gimli#569]
### Problem description

`conda create -n pg -c gimli -c conda-forge pygimli=1.4.3` is already running for about 20 minutes...
![image](https://github.com/gimli-org/gimli/assets/43808863/acc22550-46d9-4dbc-99dc-c46dc277eb35)

### Your environment

**Operating system**:  Linux Ubuntu 20.04
**Python version**: conda creates by itself, I think it is 3.9

### Steps to reproduce

**Comment by halbmy** [comment]
I know, `conda` is extremely slow in resolving the dependency tree. You can try replacing it by mamba (`conda install mamba`) or install mamba-forge, a preconfigured mamba with conda-forge as prority channel.

**Comment by kerim371** [comment]
Thank you for response!
I left it installing for the night and this morning it has been installed :)

I hope your recommendations work as well, I will come back to this when I have to reinstall pygimli.
