### ISSUE TITLE
Issue with setting regionwise regularization in the traveltime manager

### ISSUE THREAD

**Issue by benbpete** [gimli-org/gimli#571]
### Problem description

I am unable to set various regularization parameters for a given region when using the traveltime manager.
Related to #542 

### Your environment

--------------------------------------------------------------------------------
  Date: Thu Aug 17 09:01:38 2023 Eastern Daylight Time

                OS : Windows
            CPU(s) : 20
           Machine : AMD64
      Architecture : 64bit
               RAM : 31.7 GiB
       Environment : Jupyter

  Python 3.9.17 | packaged by conda-forge | (main, Aug 10 2023, 06:55:58) [MSC
  v.1929 64 bit (AMD64)]

           pygimli : 1.4.3
            pgcore : 1.4.0
             numpy : 1.21.6
        matplotlib : 3.7.1
             scipy : 1.11.1
           IPython : 8.14.0
           pyvista : 0.41.1
--------------------------------------------------------------------------------

Windows installation via Anaconda

Attached is the data file. 

I have created a 2 region mesh for the inversion, which the inversion manager seems to incorporate correctly. 

The second "region" is a very homogeneous and hard bedrock, so I am attempting to put limits on its parameters using setRegularization, placed in cell 5. I am wondering if all of these problems are the result of the same problem. The three settings I am currently having problems with are:

mgr.inv.setRegularization(2, limits = [1/11000,1/8000], trans = 'log')
mgr.inv.setRegularization(2, single=True)
mgr.inv.setRegularization(2, correlationLengths=[50,3])

I have tried each individually, and none seem to affect the final inversion result. All are currently commented out in cell number 5.

```python
####### Import packages #######
import numpy as np
import pygimli as pg
import pygimli.physics.traveltime as tt
import pygimli.meshtools as mt
from pygimli.physics import TravelTimeManager
print(pg.Report())
print(pg.__version__)

data = pg.load('Line4_test.sgt', verbose=True)
print(data)

####### Plot FirstBreaks #######

#fig, ax = pg.plt.subplots();
#tt.drawFirstPicks(ax, data);

####### Initialize the Refraction Manager #######

mgr = tt.TravelTimeManager(data)
ax, cbar = mgr.showData()

#######  Create World and Mesh #######
L4file = "Line4_poly.txt"
L4points = np.genfromtxt(L4file)
print(L4points[0:5])

world = mt.createPolygon(L4points, isClosed = True, marker = 1, area = 100, markerPosition=[1000,770])
#pg.show(world)

shale_pts = [[810, 757.1], [880, 757.1], [940.0, 756.7], [1154, 757.8], [1444, 757.1], [1609, 757.1], [1609, 700], [810,700]] # Polygon
bedrock = mt.createPolygon(shale_pts, isClosed = True, markerPosition = [820, 710], marker = 2) #for a polygon
#shale_pts = [[820, 757.1], [880, 757.1], [940.0, 756.7], [1154, 757.8], [1444, 757.1], [1599, 757.1]]  # Line/Boundary
#bedrock = mt.createPolygon(shale_pts, isClosed = False)   #for a line/boundary
world += bedrock

ax, _ = pg.show(world, markers = True, regionMarker = True)
ax.set_xlim(left = 790 ,right = 1700)
ax.set_ylim(680,805);

mesh1 = mt.createMesh([world])
#pg.show(mesh1, markers = True, showMesh = True, regionMarker = True, paraBoundary = 0)

######  Set Regularization Parameters   ######
mgr.checkData(data)

#####  I am not able to get the following regularization settings to work properly  #####

#mgr.inv.setRegularization(2, limits = [1/11000, 1/8000])   # Does not work in current script
#mgr.inv.setRegularization(2, single=True)   #Does not work in current script
#mgr.inv.setRegularization(correlationLengths=[50,3]) #Does not work in current script

###### Assigning mesh for inversion   ######

mgr.setMesh(mesh1) # This must be called prior to setting the inversion if using your own mesh
mgr.inv.setRegularization(1, background = False)   # If using your own mesh, this must be called after .setMesh, or .setMesh will set the region with the smallest marker to background

######   Inversion   ######
mod = mgr.invert(data, lam=200, lambdaFactor = 0.85, verbose = True, robustData = True, secNodes = 5) #, blockyModel = True

######   Plot response and measured traveltimes   ######

ax, cbar = mgr.showData(firstPicks=True, linewidth=0);
tt.drawFirstPicks(ax, data, mgr.inv.response, marker=None);

######   Show Model Results and Fit   ######

mgr.showResultAndFit(paraBoundary = 0);
mgr.showModel(mod,showMesh = True)
```

### Expected behavior

I would like to be able to set a range of values, allow for only a single value, or use geostatistical regularization for a specific region.

### Actual behavior

the .setRegularization() does not appear to work for this current mesh.

```
17/08/23 - 09:31:41 - pyGIMLi - INFO - Found 2 regions.
17/08/23 - 09:31:41 - pyGIMLi - INFO - Region with smallest marker set to background (marker=1)

17/08/23 - 09:31:42 - pyGIMLi - ERROR - <class 'pygimli.physics.traveltime.TravelTimeManager.TravelTimeManager'>.checkError(C:\Users\AdminSSPA\anaconda3\envs\pg\lib\site-packages\pygimli\physics\traveltime\TravelTimeManager.py:96)
DataContainer has no "err" values. Fallback to 3%
17/08/23 - 09:31:42 - pyGIMLi - INFO - Creating forward mesh from region infos.
17/08/23 - 09:31:42 - pyGIMLi - INFO - Creating refined mesh (secnodes: 2) to solve forward task.
17/08/23 - 09:31:42 - pyGIMLi - INFO - Create gradient starting model. 500: 5000
17/08/23 - 09:31:42 - pyGIMLi - INFO - Created startmodel from forward operator: [0.00033722 0.00189947 0.00066692 ... 0.00020333 0.00024795 0.00025975]
17/08/23 - 09:31:42 - pyGIMLi - INFO - Starting inversion.

fop: <pygimli.physics.traveltime.modelling.TravelTimeDijkstraModelling object at 0x0000026B2BC1D180>
Data transformation: <pgcore._pygimli_.RTrans object at 0x0000026B2BC1D3B0>
Model transformation (cumulative):
	 0 <pgcore._pygimli_.RTransLogLU object at 0x0000026B2F170A00>
	 1 <pgcore._pygimli_.RTransLogLU object at 0x0000026B2F170A00>
min/max (data): 6.6e-04/0.06
min/max (error): 3%/3%
min/max (start model): 2.0e-04/0.002
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
inv.iter 1 ... chi² = 88.48 (dPhi = 95.08%) lam: 200
--------------------------------------------------------------------------------
inv.iter 2 ... chi² = 2.74 (dPhi = 89.32%) lam: 170.0
--------------------------------------------------------------------------------
inv.iter 3 ... chi² = 1.38 (dPhi = 1.13%) lam: 144.5
--------------------------------------------------------------------------------
inv.iter 4 ... chi² = 0.9 (dPhi = -12.55%) lam: 122.825


################################################################################
#                  Abort criterion reached: chi² <= 1 (0.90)                   #
################################################################################

```

NOTE: i changed the extension on "Line4_test.txt" from a .sgt to a .txt file so that it would attach

Thanks for any help you can provide!
[Line4_test.txt](https://github.com/gimli-org/gimli/files/12370011/Line4_test.txt)

[Line4_poly.txt](https://github.com/gimli-org/gimli/files/12370027/Line4_poly.txt)

**Comment by carsten-forty2** [comment]
short notice: `mgr.inv.setRegularization(2, single=True)`  means your whole region number 2 is assumed as one single parameter so any  additional structural constraint for this region is meaningless and might lead to unplanned behaviour.

**Comment by benbpete** [comment]
Thanks @makeabhishek . 

An update, I found if set regularization for a "single" value  _after_ calling the mesh, I would get a single velocity value of "1 m/s" for all region 2 cells.  
```
mgr.setMesh(mesh1)
mgr.inv.setRegularization(1, background = False)
mgr.inv.setRegularization(2, single = True)
```
![image](https://github.com/gimli-org/gimli/assets/105517351/8760e86e-ea62-443c-89a0-b584ae4972df)

**Comment by carsten-forty2** [comment]
maybe try a high (or low in slowness) start model for region2. It could be, that if the start value is to low then no ray path pass this region, which effectively exclude it from inversion.

**Comment by benbpete** [comment]
Thanks @carsten-forty2, I was able to set a single velocity for the "region 2" by setting limits for the range, e.g.:
```
mgr.inv.setRegularization(2, single = True, limits = [1/12000, 1/7000])
```

I don't have a need for it right now, but so that it is documented :
1) Setting a "fix" value for"region 2" was ignored by the manager. (Maybe that has something to do with not assigning correct boundary values when creating the 2 region mesh).
2) trying to use correlation lengths (which may not make much sense given refraction sensitivity distributions?) results in nonsensical velocity models.

Thanks for all of the help!

**Comment by makeabhishek** [comment]
Hi @benbpete, Are you able to resolve the issue for the region-wise regularisation?

Abhi
makeabhishek@gmail.com
