### ISSUE TITLE
module 'pybert' has no attribute 'ERTManager'

### ISSUE THREAD

**Issue by kafahabibullah1453** [gimli-org/gimli#572]
hello, I tried to run an example script on Bert's website [link](http://resistivity.net/bert/_examples/plot_2D_simple.html#sphx-glr-examples-plot-2d-simple-py) and I found this problem
 `ert = pb.ERTManager()

data = ert.simulate(mesh, res=rhomap, scheme=scheme, noiseLevel=1,
                    noiseAbs=1e-6)

print('Simulated rhoa', data('rhoa'), max(data('rhoa')))

data.markInvalid(data('rhoa') < 0)
print('Filtered rhoa', data('rhoa'), max(data('rhoa')))
data.removeInvalid()

data.save('simple.dat')

pb.show(data)`

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 ert = pb.ERTManager()
      3 # Perform the modeling with the mesh and the measuring scheme itself
      4 # and return a data container with apparent resistivity values,
      5 # geometric factors and estimated data errors specified by the noise setting.
      6 # The noise is also added to the data.
      7 data = ert.simulate(mesh, res=rhomap, scheme=scheme, noiseLevel=1,
      8                     noiseAbs=1e-6)

AttributeError: module 'pybert' has no attribute 'ERTManager'

**Operating system**: Windows
**Python version**: 3.9.13
**pybert                    2.4.2
**pygimli                   1.4.1
use miniconda3

Thanks in advance!
Bests,
kafa

Appreciate any help!

**Comment by halbmy** [comment]
The `ERTManager` from `pybert` (this is where the issue should be created) is outdated and entirely moved to pyGIMLi. Actually, `pb.ERTManager` should not exist anymore and direct to the ERT manager in the ERT module of pygimli.

**Comment by kafahabibullah1453** [comment]
Thanks for your suggestions! I have tried and it works.

**Comment by kafahabibullah1453** [comment]
sorry sir, I have a second question, in the tutorial [link](http://resistivity.net/bert/_examples/plot_2D_simple.html#sphx-glr-examples-plot-2d-simple-py). i have another problem at the end. when I try to run

`grid = pg.createGrid(x=pg.utils.grange(start=-12, end=12, n=33),
                     y=-pg.utils.grange(0.5, 8, n=8, log=True))

mesh = pg.meshtools.appendTriangleBoundary(grid, xbound=50, ybound=50)

model = mgr.invert(data, mesh=mesh, lam=20)
mgr.showResultAndFit()

chi2 = mgr.inv.getChi2()

print(chi2)

pg.wait()`

--------------------------------------------------------------------

21/08/23 - 06:33:30 - pyGIMLi - INFO - Found 2 regions.
21/08/23 - 06:33:30 - pyGIMLi - INFO - (ERTModelling) Region with smallest marker (0) set to background.
21/08/23 - 06:33:30 - pyGIMLi - INFO - Creating forward mesh from region infos.
21/08/23 - 06:33:31 - pyGIMLi - INFO - Creating refined mesh (H2) to solve forward task.
21/08/23 - 06:33:31 - pyGIMLi - INFO - Mesh for forward task: Mesh: Nodes: 1576 Cells: 2108 Boundaries: 1878
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[17], line 6
      1 grid = pg.createGrid(x=pg.utils.grange(start=-12, end=12, n=33),
      2                      y=-pg.utils.grange(0.5, 8, n=8, log=True))
      4 mesh = pg.meshtools.appendTriangleBoundary(grid, xbound=50, ybound=50)
----> 6 model = mgr.invert(data, mesh=mesh, lam=20)
      7 mgr.showResultAndFit()
      9 chi2 = mgr.inv.getChi2()

File ~\Miniconda3\envs\pg\lib\site-packages\pygimli\frameworks\methodManager.py:820, in MeshMethodManager.invert(self, data, mesh, startModel, **kwargs)
    817 dataVals = self._ensureData(self.fop.data)
    818 errorVals = self._ensureError(self.fop.data, dataVals)
--> 820 if self.fop.mesh() is None:
    821     pg.critical('Please provide a mesh')
    823 kwargs['startModel'] = startModel

File ~\Miniconda3\envs\pg\lib\site-packages\pygimli\frameworks\modelling.py:697, in MeshModelling.mesh(self)
    694 self._applyRegionProperties()
    696 if self._regionManagerInUse and self._regionChanged is True:
--> 697     self.createFwdMesh_()
    699 return super().mesh()

File ~\Miniconda3\envs\pg\lib\site-packages\pygimli\frameworks\modelling.py:687, in MeshModelling.createFwdMesh_(self)
    677     pg.verbose("\tRegion: {0}, Parameter: {1}, PD: {2},"
    678                " Single: {3}, Background: {4}, Fixed: {5}".format(
    679                    iId,
   (...)
    683                    self.regionManager().region(iId).isBackground(),
    684                    self.regionManager().region(iId).fixValue()))
    686 m = self.createRefinedFwdMesh(m)
--> 687 self.setMeshPost(m)
    689 self._regionChanged = False
    690 super().setMesh(m, ignoreRegionManager=True)

File ~\Miniconda3\envs\pg\lib\site-packages\pygimli\physics\ert\ertModelling.py:211, in ERTModelling.setMeshPost(self, mesh)
    209 def setMeshPost(self, mesh):
    210     """Set mesh (at a later stage)."""
--> 211     self._core.setMesh(mesh, ignoreRegionManager=True)

RuntimeError: There is a requested electrode that does not match the given mesh. 

have you solution for it?

**Comment by halbmy** [comment]
A `pg.show(mesh, markers=True)` 

![image](https://github.com/gimli-org/gimli/assets/7136401/65e333da-14cf-40d5-97d4-b03b970eab72)

shows that the grid does not match. You should include a zero and use increasing y values plus a marker>1:
```
grid = pg.createGrid(x=pg.utils.grange(start=-12, end=12, n=33),
                     y=-pg.cat([0], pg.utils.grange(0.5, 8, n=8, log=True))[::-1], marker=2)
```
Then all works well (change `getChi2` into `chi2`).

**Comment by kafahabibullah1453** [comment]
thank u sir for your solution. sorry sir, I have a question, maybe it basic question. if the library or function of BERT is outdated and entirely moved to pyGIMLi, and maybe many do not exist anymore.  and then what are the differences in the results of BERT and pyGIMLI in processing or 2D ERT modeling and inversion?

**Comment by kafahabibullah1453** [comment]
thank u sir for your solution. sorry sir, I have a question, maybe it basic question. if the library or function of BERT is outdated and entirely moved to pyGIMLi, and maybe many do not exist anymore.  and then what are the differences in the results of BERT and pyGIMLI in processing or 2D ERT modeling and inversion?

**Comment by kafahabibullah1453** [comment]
Thank u very much for your explanation
