### ISSUE TITLE
Problem with draw1DColumn

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#573]
I have a problem when trying to plot inverted ERT result and borehole resistivity data (as prior data).
I followed the instruction for draw1DCoulomn function and got an error 

Input In [15] in <cell line: 7>
    draw1DColumn(ax, x=x[0], val=r[iz], thk=thk, width=4, **kw)

TypeError: draw1DColumn() got an unexpected keyword argument 'cMin'

how can i solve this?

**Comment by halbmy** [comment]
Which version of pyGIMLi are you using? 

The website https://pygimli.org has been created with v1.4.3 and in the example
https://www.pygimli.org/_examples_auto/6_inversion/plot_5_ert_with_priors.html
there is the code 
```
kw = dict(cMin=20, cMax=500, logScale=True, cMap="Spectral_r",
          xlabel="x (m)", ylabel="y (m)")
ax, cb = mgr.showResult(**kw)
zz = np.abs(z)
iz = np.argsort(zz)
thk = np.hstack([0, np.diff(zz[iz])])
draw1DColumn(ax, x=x[0], val=r[iz], thk=thk, width=4, **kw)
ax.grid(True)
```
which works well also in my development version.

So I suspect it is a matter of the version or from where you import the function. Can you provide the whole script?

**Comment by halbmy** [comment]
I see the point. In a recent commit 
https://github.com/gimli-org/gimli/commit/3c876486a0632bb64e3d38952170d3b7bb15bcef

just before the v1.4.3 release, the keyword arguments `cmin`/`cmax`/`cmap` were renamed to `cMin`/`cMax`/`cMap` to be compatible to those of `pg.show`. So either update pyGIMLi or use small `m` instead.

**Comment by tonapawilliam** [comment]
I solved the problem.

Thank you very much, Thomas Gunther !.
