### ISSUE TITLE
pg.show(geom) error on complex geometries

### ISSUE THREAD

**Issue by jcmefra** [gimli-org/gimli#574]
### Problem description

I'm trying to do a modelling using 3 complex shapes and everything is ok, but when I do pg.show(geom3) It takes forever and then just crashes, the script is killed. If I don't add "deposit" to the geom3 variable, it shows the figure without any issues.

### Your environment

--------------------------------------------------------------------------------
  Date: Fri Aug 25 23:54:59 2023 -05

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 15.6 GiB
       Environment : Jupyter
       File system : ext4

  Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32)
  [GCC 12.3.0]

           pygimli : 1.4.3
            pgcore : 1.4.0
             numpy : 1.25.0
        matplotlib : 3.7.2
             scipy : 1.11.2
           IPython : 8.14.0
           pyvista : 0.41.1
--------------------------------------------------------------------------------

### Steps to reproduce

Here's the full code:

```python
import matplotlib.pyplot as plt
import numpy as np

import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import ert

#Quaternary
x = np.linspace(-350, 350, 100)
y = -150 + 50 * np.sin((x-300) / 200)
top_layer1 = [[-350, 0], [350, 0]]
bottom_layer1 = np.column_stack((x, y))[::-1]
deposit_shape = np.vstack((bottom_layer1, top_layer1))
deposit = mt.createPolygon(deposit_shape, isClosed=True, marker=1)
pg.show(deposit)

#Fault Position

x1 = -125
y2 = -250

#Find y1 and x2 so fault intersects with first layer base and it has dip = 60°

def f(p):
    x2, y1 = p
    eq1 = y1 - (-150 + 50 * np.sin((x1-300) / 200))
    eq2 = x2 - (x1 + (y2 - y1) / np.tan(np.radians(60)))
    return [eq1, eq2]

from scipy.optimize import fsolve

x2, y1 = fsolve(f, [-100, -200])

#Floresta fm
x_top = np.linspace(-350, x1, 100)
y_top = -150 + 50 * np.sin((x_top-300) / 200)

Floresta_top = np.column_stack((x_top,y_top))[::-1]
Floresta_bottom = [[-350, y2], [x2, y2]]
Floresta_verts = np.vstack((Floresta_bottom, Floresta_top))
Floresta_fm = mt.createPolygon(Floresta_verts, isClosed = True, marker = 2)
pg.show(Floresta_fm)

#Cretacic Rocks
x_top2 = np.linspace(x1, 350, 100)
y_top2 = -150 + 50 * np.sin((x_top2-300) / 200)

Cretacic_top = np.column_stack((x_top2,y_top2))[::-1]
Cretacic_bottom = [[x2, y2], [350, y2]]
Cretacic_verts = np.vstack((Cretacic_bottom, Cretacic_top))
Cretacic_rocks = mt.createPolygon(Cretacic_verts, isClosed = True, marker = 3)
pg.show(Cretacic_rocks)

#It shows every shape without issues

geom3 = deposit + Floresta_fm + Cretacic_rocks
pg.show(geom3) #The issue goes here, it just doesn't work and crashes
...
```

### Expected behavior

The "geom3" figure showing without issues, like the 3 shapes did.

### Actual behavior

It crashes and the script is killed.

```
killed
```

**Comment by carsten-forty2** [comment]
The script does not work `NameError: name 'x1' is not defined.` So I can only guess.

It maybe sounds like a tolerance problemem somehow. 

The last `show` calls internal `pg.createMesh(geom3)` to simple draw the geometry as mesh with hidden mesh cells. If this hangs, its sounds to me the meshgenerator failed. This could be non connected geometry parts. 

You could draw all 3 parts together in one axe to see if there is any overlappings. Check if all parts can be meshed on there own. Reduce the number of initial nodes to start with a smaller problem.

**Comment by jcmefra** [comment]
> The script does not work `NameError: name 'x1' is not defined.` So I can only guess.
> 
> It maybe sounds like a tolerance problemem somehow.
> 
> The last `show` calls internal `pg.createMesh(geom3)` to simple draw the geometry as mesh with hidden mesh cells. If this hangs, its sounds to me the meshgenerator failed. This could be non connected geometry parts.
> 
> You could draw all 3 parts together in one axe to see if there is any overlappings. Check if all parts can be meshed on there own. Reduce the number of initial nodes to start with a smaller problem.

Hello! I forgot to add x1, y1, x2, y2 values here. The code is edited now, can you please try again? Thanks!

**Comment by carsten-forty2** [comment]
before I will dig deeper,  you might check the geometries ...

You can draw single parts into one axe without the mesh generator to check the geometries: 
```
ax, _ = pg.show(deposit, fillRegion=False, alpha=.3)
pg.show(Floresta_fm, fillRegion=False, ax=ax)
pg.show(Cretacic_rocks, fillRegion=False, ax=ax)
```

which leads to : 
![image](https://github.com/gimli-org/gimli/assets/6043771/225bdb14-130f-495f-968f-0c12f10a062f)

There are sharp angles and interesecting edges that might not covered by the current version of the geometry merge. If you wan't exactly this geometry .. I could search for a fix or you could give gmsh a try.

**Comment by jcmefra** [comment]
> before I will dig deeper, you might check the geometries ...
> 
> You can draw single parts into one axe without the mesh generator to check the geometries:
> 
> ```
> ax, _ = pg.show(deposit, fillRegion=False, alpha=.3)
> pg.show(Floresta_fm, fillRegion=False, ax=ax)
> pg.show(Cretacic_rocks, fillRegion=False, ax=ax)
> ```
> 
> which leads to : ![image](https://user-images.githubusercontent.com/6043771/263564517-225bdb14-130f-495f-968f-0c12f10a062f.png)
> 
> There are sharp angles and interesecting edges that might not covered by the current version of the geometry merge. If you wan't exactly this geometry .. I could search for a fix or you could give gmsh a try.

Thanks for the help! I already fixed the intersecting form so now they look like this:
![image](https://github.com/gimli-org/gimli/assets/64992303/b7ab6799-a145-4e35-ac31-1fb2ef1522ad)
![image](https://github.com/gimli-org/gimli/assets/64992303/04426e64-3687-4330-ae28-ae16ba108a38)
![image](https://github.com/gimli-org/gimli/assets/64992303/2e6f015f-376d-4a02-a353-4bfbb6d938fd)

When I do:

` geom3 = Floresta_fm + Cretacic_rocks
pg.show(geom3)`

It shows like this:
![image](https://github.com/gimli-org/gimli/assets/64992303/d77401ee-bd74-40f1-9787-277e5b2def11)

But when I add "deposit" to "geom3", it still crashes.

I need those 3 figures into a mesh to do the synthetic data generation. Thanks!

**Comment by carsten-forty2** [comment]
consider this as solved ... see #575
