### ISSUE TITLE
Maximum Data Point and How to Display all datum point position

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#577]
How much data can Pygimli manage and display?

I have data with a total of 6000 datums, and when I try to import it into pygimli and display it with ert.show(data), it only shows part of the data.
this is a comparison of pygimli view with Res2Dinv 5
![Figure_1](https://github.com/gimli-org/gimli/assets/126912836/d12556aa-b6ba-4643-a2f5-1840654c9e5f)
![Screenshot 2023-08-30 133923](https://github.com/gimli-org/gimli/assets/126912836/e0914c1e-99de-4f45-9138-0951e83a2739)

Is there a special command so that all data can be displayed? This data uses an edge gradient configuration with a track length of 350 meters.

**Comment by halbmy** [comment]
pyGIMLi is always using (e.g. inverting) all data. The display depends on the array but I guess all data are actually shown but with a different scheme, i.e. the x point is between potential dipole. You would have to attach the data to check that.

**Comment by tonapawilliam** [comment]
I have tried to do an inversion, and you are right that the results of the inversion that I did are similar to the results of the inversion on Res2DInv, but is there a function so I can display all of these datum points? I am attaching the data along with the image of the inversion result
![fit and Result](https://github.com/gimli-org/gimli/assets/126912836/b64b19d0-71c5-4371-97fa-97a4ae5cd329)
![Res2d_e01a_Left](https://github.com/gimli-org/gimli/assets/126912836/53c40f93-b371-4ca0-bffd-cb2c6d310a6d)
I attach the data
[GeneralEdGr.txt](https://github.com/gimli-org/gimli/files/12482044/GeneralEdGr.txt)

**Comment by halbmy** [comment]
Yes, not all data points are represented in the data image as this array type is not covered yet. 

Calling `showDataContainer("b", "m", "rhoa")` prints that more than 3000 of the data are not shown. 

However, you can group the indices and call

```
from pygimli.viewer.mpl import showDataContainerAsMatrix
showDataContainerAsMatrix(data, ["b", "a"], "m", "rhoa", cMin=100, cMax=500, cMap="Spectral_r")
```

which shows all data:

![image](https://github.com/gimli-org/gimli/assets/7136401/7a1aafd2-cb4e-4a06-b147-0d97c851525c)

**Comment by tonapawilliam** [comment]
But, isn't there a way for all of this measurement data to appear in a generic form? Like a trapezoid or an inverted triangle?

**Comment by halbmy** [comment]
The individual data are NOT associated to inversion results. Of course one could use a different representation for the data (main point being the midpoint). I put it on the list but consider it an edge case and you can plot the data as shown above.

More important is the inversion which is somehow running but part of the data are not fitted well (top-data, bottom-response)

![image](https://github.com/gimli-org/gimli/assets/7136401/41fe6690-eae2-40e5-a996-07815d707ab3)

so I think there might be some systematic effect although the main features are the same

![image](https://github.com/gimli-org/gimli/assets/7136401/40047994-0d78-4cbd-a1b5-77313fae03fa)
