### ISSUE TITLE
ERT Inversion with 3 or 4 prior data

### ISSUE THREAD

**Issue by TRafie** [gimli-org/gimli#579]
Is it possible to do ERT inversion with more than 1 prior data using pygimli ?
I am planning to do ERT inversion using prior data example, but I have several Direct Push data in one ERT line. I hope function 'JointModelling', or 'fopDP' can do such a thing.

**Comment by halbmy** [comment]
Of course it does as also done in the paper of Grünenbaum et al. (2023). The example data file has x, z and resistivity values, so you can just append several DP in one file. The only thing to be changed is the plotting.

Grünenbaum, N., Günther, T., Greskowiak, J., Vienken, T., Müller-Petke, M. & Massmann, G. (2023): Salinity distribution in the subterranean estuary of a meso-tidal high-energy beach characterized by Electrical Resistivity Tomography and Direct Push technology. J. of Hydrol. 617, 129074, doi:10.1016/j.jhydrol.2023.129074.

**Comment by TRafie** [comment]
Thank you for your documentation.
I might need your help more since my research team is currently focusing to collect the data.
I hope it is possible to discuss with you more on how to do the simultaneous inversion with several DP data.

**Comment by halbmy** [comment]
To clarify this once more:

In the mentioned example, we used the example file
https://github.com/gimli-org/example-data/blob/master/ert/bedrock.txt

consisting of 62 lines with single DP data. In this case, they are all from one drilling (constant x coordinate), but of course it could also include several drillings at variable positions. The only thing to change is just the plotting, e.g.
```
for xpos in ...
    plot(res[x==xpos], z[x==xpos], ...
```

**Comment by TRafie** [comment]
Hi Gunther,
I would like to ask you some questions regarding the inversion results. I have tried to make synthetic model (see Figure 1) and run the inversion (Figure 2a). However, I noticed inconsistency model with inversion when I tried to run the inversion with 5 prior data (Figure 2b) where I used the same parameter and regularization of Figure 2a. Could you please assist me in understanding how this occurred?, I attach the codes for your convenience.
Second question, after I executed the joint inversion process with 5 prior data, I noticed several noise artifacts (?) generated from the inversion. When I used bigger cell/mesh size, it looks OK, however, when I tried to use smaller size with the attempt to make it much smoother, it produces some anomalies. What is your suggestion for this, should I just keep the bigger cell size instead of small cell size. Also, how can I save all the inversion results (X, Z, and final inverted resistivity value)?, I tried to use rhoData.saveResult for the joint inversion, it tells that it did not have the function saveResult.
Thanks in advance and I hope to hear from you soon.
![discussion](https://github.com/gimli-org/gimli/assets/144016480/eb035733-23be-4d23-93a1-f050b1edc32a)

[synthetic_body.txt](https://github.com/gimli-org/gimli/files/12709085/synthetic_body.txt)
[testing_ert_logging.txt](https://github.com/gimli-org/gimli/files/12709086/testing_ert_logging.txt)

**Comment by halbmy** [comment]
The normal inversion shows the exptected behaviour which could be improved by playing with `lam` and `zWeight`.

For the geostatistical regularization you should use higher correlation lengths, particularly in the vertical direction. For your synthetic model I would rather use 100 and 10 or even above.

Note also that the noise level of 10% (everything below 0.5 is considered NOT to be in percent) is rather high leading to the artifacts you observe. Furthermore, the default of the voltage error (`noiseAbs=1e-4`) is usually too high (use values in the range of ~10µV, i.e. 1e-5 or maybe 0 to make it easier for now). Have a look at `ert.show(data, data["err"]*100, label="error model (%)")`.

**Comment by halbmy** [comment]
#585 might help you

**Comment by TRafie** [comment]
Dear Gunther,

I encountered an error when attempting to execute the following code snippet:
np.savetxt("out.txt", np.column_stack([pg.x(mgr.paraDomain), pg.y(mgr.paraDomain), mgr.paraModel]))
The error message I received is as follows:
ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 662 and the array at index 2 has size 1
Could you please provide guidance on how to resolve this issue?

Additionally, I am curious whether this code exports the final joint-inversion result or the normal ERT inversion result? For your convenience, I have attached the script and the data.

Best,
[testing_ert_logging.txt](https://github.com/gimli-org/gimli/files/12728425/testing_ert_logging.txt)
[synthetic_body.txt](https://github.com/gimli-org/gimli/files/12728444/synthetic_body.txt)
[LR.txt](https://github.com/gimli-org/gimli/files/12728446/LR.txt)

**Comment by carsten-forty2** [comment]
try pg.x(mgr.paraDomain.cellCenters()) and the same for the y coordinate.

**Comment by TRafie** [comment]
I have tried the code below:
np.savetxt("out.txt", np.column_stack([pg.x(mgr.paraDomain.cellCenters()), pg.y(mgr.paraDomain.cellCenters()), 
                                       mgr.paraModel]))
and still got the same error.

**Comment by halbmy** [comment]
Please have a look at `mgr.model` (the raw model vector) or `mgr.paraModel` (the mapped model). In your case both should have a length of the inversion mesh cell number.

**Comment by TRafie** [comment]
Hi Gunther,
I have tried to change the last cell separator code as follows:

inv.setRegularization(2, correlationLengths=[100, 10])
model = inv.run(dataVec, errorVec, startModel=model, lam=100.0)
ax, cb = pg.show(para, model, **kw)
draw1DColumn(ax, x=x1[0], val=r1[iz1], thk=thk1, width=4, **kw)
draw1DColumn(ax, x=x5[0], val=r5[iz5], thk=thk5, width=4, **kw)
draw1DColumn(ax, x=x3[0], val=r3[iz3], thk=thk3, width=4, **kw)
draw1DColumn(ax, x=x2[0], val=r2[iz2], thk=thk2, width=4, **kw)
draw1DColumn(ax, x=x4[0], val=r4[iz4], thk=thk4, width=4, **kw)
**np.savetxt("out1.txt", np.column_stack([pg.x(mgr.paraDomain.cellCenters()), pg.y(mgr.paraDomain.cellCenters()), 
                                       mgr.paraModel()]))**

and it exports the all the values. When I tried to plot the x and z coordinates it represents all the point in the mesh center. However, the resistivity values not really represent the final joint inversion results (where there should be resistivity values > 1000 ohm-m portraying the previous figure before), in fact, it resembles the inverted model with geostatistical approach (see figures below). How can I solve this?, I am hoping to export the final joint-inversion with prior data files. 
please have a look at the exported txt file in the attachment
![example_1](https://github.com/gimli-org/gimli/assets/144016480/f12c0aba-3e30-4cc0-9209-0a17be7391e4)
![example_2](https://github.com/gimli-org/gimli/assets/144016480/b2e04ae1-11aa-4beb-8293-e4012da6b211)

**Comment by halbmy** [comment]
Of course you have to take `model` instead:
```
np.savetxt("out1.txt", np.column_stack([pg.x(mgr.paraDomain.cellCenters()), pg.y(mgr.paraDomain.cellCenters()), model]))
```

**Comment by TRafie** [comment]
OK, thank you, Gunther.
It works fine now.

**Comment by TRafie** [comment]
Hi Gunther,

I have tried the code for joint-inversion of logging and ERT data.
The case is for nickel laterite where some boulders are proven to occur, but the joint-inversion results seem difficult to constrain the layer above bedrock (see figure below for high resistivity value below).
What parameterization or regularization particularly in geostatistical approach should I implement?.
I have read your paper (Jordi et al., 2018 in GJI) where you actually input the dipping/rotation parameter in your modeling, can you help me in detail to apply that. Please have a look at code and final inversion results for your convenience 
Thank you in advance.
 
![all_results_E01](https://github.com/gimli-org/gimli/assets/144016480/29c25c93-d453-44d5-9d31-0fdd30a1b96d)
[code_E_01.txt](https://github.com/gimli-org/gimli/files/12798333/code_E_01.txt)

**Comment by halbmy** [comment]
Geostatistical regularization in combination with prior data is the way to go. It seems like you should estimate the dip from your drillings and also use a variogram analysis to determine the vertical correlation length. The horizontal one is harder to retrieve, so you will have to play. Just like with the prior data error.

**Comment by halbmy** [comment]
I am closing this issue as many different things have turned up here. For a new or persisting problem, please raise a new issue.
