### ISSUE TITLE
visualize the current distribution in the presence of anomalies in the subsurface.

### ISSUE THREAD

**Issue by zhichaoluan** [gimli-org/gimli#581]
Hi, I would like to visualize the current distribution in the presence of anomalies in the subsurface.

**Comment by halbmy** [comment]
Please have a look for the function `drawStreams` and its use in examples like
https://www.pygimli.org/_tutorials_auto/2_modelling/plot_3-mod-fem-BC.html
or
https://www.pygimli.org/_examples_auto/3_dc_and_ip/plot_04_ert_2_5d_potential.html

For modelling electric current flow, this example might help as well
https://github.com/gimli-org/notebooks/blob/main/ERT/fault/Faultzone.ipynb
