### ISSUE TITLE
pygimli Could not read unified data format for ERT 

### ISSUE THREAD

**Issue by kafahabibullah1453** [gimli-org/gimli#582]
hello, I tried to run my data and i get a problem.
<img width="584" alt="Capture" src="https://github.com/gimli-org/gimli/assets/128029937/d2a027c2-04c4-47f8-a909-f78cef4da117">
11/09/23 - 13:04:11 - pyGIMLi - INFO - could not read unified data format for ERT ... try res2dinv

Appreciate any help!

**Comment by halbmy** [comment]
This message is no error message but just a comment that it tried to read in a res2dinv file format which apparently worked well. So there is no error. And you probably don't need pybert for it.

As you have already read in the data before, you should rather work with the data directly.
```
data = ert.load("...
mgr = ert.ERTManager(data)
...
```

**Comment by kafahabibullah1453** [comment]
i try directly, and Data contains no geometric factors data['k'].
<img width="587" alt="1" src="https://github.com/gimli-org/gimli/assets/128029937/741e7ad2-2fc4-4214-af64-d3d2fd923bd8">
<img width="552" alt="2" src="https://github.com/gimli-org/gimli/assets/128029937/a4756963-d9fd-419e-aa5b-f2017efd4ce9">

what is solution?

**Comment by halbmy** [comment]
To calculate them using functions in the ERT module. For simple geometries (flat topography) it might be simple like in 
https://www.pygimli.org/_examples_auto/3_dc_and_ip/plot_06_crosshole2d.html
using
```
data["k"]=ert.geometricFactors(data)
```
or even more simply
```
data.createGeometricFactors()
```

In cases of non-trivial geometry, this might require a numerical computation like in
https://www.pygimli.org/_examples_auto/3_dc_and_ip/plot_02_ert_field_data.html

I agree that in case of simple surface arrays we could set the geometric factor when loading the file.

**Comment by kafahabibullah1453** [comment]
okay.  i tried your solution and get something
<img width="587" alt="3" src="https://github.com/gimli-org/gimli/assets/128029937/1bcb153c-2d14-4875-ab58-3c0d7cbcb351">
<img width="525" alt="4" src="https://github.com/gimli-org/gimli/assets/128029937/ff4bab38-39e6-4a32-8f83-8494a904cf8e">
<img width="546" alt="5" src="https://github.com/gimli-org/gimli/assets/128029937/1ea21326-6f1d-4b8d-b38d-5881674ce2b5">

AssertionError: 
Items are not equal to 1 significant digits:
 ACTUAL: 1.8608266993009344
 DESIRED: 0.7

any solution?

**Comment by kafahabibullah1453** [comment]
i tried your solution and i got something like this
<img width="587" alt="3" src="https://github.com/gimli-org/gimli/assets/128029937/fbab9890-51a0-4267-b739-b40b54335aa9">
<img width="525" alt="4" src="https://github.com/gimli-org/gimli/assets/128029937/b0429a70-9899-43f6-8c6c-d5240d633b60">
<img width="546" alt="5" src="https://github.com/gimli-org/gimli/assets/128029937/6a8fd026-30b5-4ab0-9468-cf9ddc406c02">
AssertionError: 
Items are not equal to 1 significant digits:
 ACTUAL: 1.8608266993009344
 DESIRED: 0.7

any solution?

**Comment by halbmy** [comment]
The inversion runs well converging to a chi-square value of 1.8, i.e. the data fit is 40% worse that what you expected (but still very good). So you could increase your data error or decrease the `lam` value to improve this but there is nothing wrong.

The `np.testing` command is just for internal testing purposes to check whether all runs as before.

**Comment by halbmy** [comment]
Looks nice.

What do you mean with *depth limits*? Depth of investigation, resolution or coverage? It is already indicated by the alpha shading in the model image. And no idea what's meant with *layer* as we don't have layers. Please try to formulate your questions or problems a bit more specific having in mind that anyone responding has only limited knowledge of your case.

**Comment by kafahabibullah1453** [comment]
> The inversion runs well converging to a chi-square value of 1.8, i.e. the data fit is 40% worse that what you expected (but still very good). So you could increase your data error or decrease the `lam` value to improve this but there is nothing wrong.
> 
> The `np.testing` command is just for internal testing purposes to check whether all runs as before. Remove this line as it does not make sense for you.

excuse me sir, for dPhi. what is a good dphi value from the inversion results?

**Comment by halbmy** [comment]
There is no such thing as a "good dphi". The objective function should decrease unless convergence is reached. The chi-square fit is what you should look at.
