### ISSUE TITLE
 field not in data container:  rhoa

### ISSUE THREAD

**Issue by kafahabibullah1453** [gimli-org/gimli#583]
excuse me, i tried to run my data and there is something
<img width="434" alt="1_2" src="https://github.com/gimli-org/gimli/assets/128029937/fcff2ccc-8ef5-40d8-8cd2-dc974372c393">
field not in data container:  rhoa

Appreciate any help!

**Comment by halbmy** [comment]
The message is quite clear: there is no apparent resistivity in the data, so you have to compute it using the geometric factors, which in turn can be computed either analytically or numerically depending on the geometry. Can you tell a bit more about the data and the underlying geometry?

The field ERT example will help you doing that:
https://www.pygimli.org/_examples_auto/3_dc_and_ip/plot_02_ert_field_data.html

We should indeed enable the ERT manager to do this automatically for
* surface ERT without topography (analytical geometric factor)
* crosshole ERT without topography (analytical geometric factor)
* surface ERT with topography (numerical geometric factor)
but in general it is not straightforward to distinguish the last cases. For crosshole ERT with topography the topo cannot be determined from the data alone. Surface-borehole and non-trivial 3D arrays are also not straightforward.

**Comment by kafahabibullah1453** [comment]
excuse me sir, this is my data [https://drive.google.com/file/d/1ap-ErnIrYJYA0fCKRfw2wzs6Lhtqf4yj/view?usp=drive_link](url)

**Comment by kafahabibullah1453** [comment]
excuse me sir, this is my data

1
5.00
1
135
1
0
7.500 5.000 15.550
12.500 5.000 15.644
17.500 5.000 15.731
22.500 5.000 15.281
27.500 5.000 14.863
32.500 5.000 12.731
37.500 5.000 12.442
42.500 5.000 12.854
47.500 5.000 11.976
52.500 5.000 14.865
57.500 5.000 14.468
62.500 5.000 16.076
67.500 5.000 15.428
72.500 5.000 13.578
77.500 5.000 14.798
82.500 5.000 14.746
87.500 5.000 15.533
92.500 5.000 15.741
97.500 5.000 16.726
102.500 5.000 16.100
107.500 5.000 15.316
112.500 5.000 16.626
117.500 5.000 16.222
122.500 5.000 17.028
127.500 5.000 16.175
132.500 5.000 17.008
137.500 5.000 18.123
15.000 10.000 20.792
20.000 10.000 6.775
25.000 10.000 19.618
30.000 10.000 18.396
35.000 10.000 17.747
40.000 10.000 18.647
45.000 10.000 19.626
50.000 10.000 19.975
55.000 10.000 19.588
60.000 10.000 20.435
65.000 10.000 21.316
70.000 10.000 19.491
75.000 10.000 20.784
80.000 10.000 21.904
85.000 10.000 21.637
90.000 10.000 21.674
95.000 10.000 24.392
100.000 10.000 24.679
105.000 10.000 23.108
110.000 10.000 23.446
115.000 10.000 24.515
120.000 10.000 24.993
125.000 10.000 24.890
130.000 10.000 25.098
22.500 15.000 27.444
27.500 15.000 25.967
32.500 15.000 24.430
37.500 15.000 24.309
42.500 15.000 25.043
47.500 15.000 25.746
52.500 15.000 25.910
57.500 15.000 26.639
62.500 15.000 26.641
67.500 15.000 26.055
72.500 15.000 26.693
77.500 15.000 27.139
82.500 15.000 27.467
87.500 15.000 29.499
92.500 15.000 29.946
97.500 15.000 30.506
102.500 15.000 30.258
107.500 15.000 30.317
112.500 15.000 30.361
117.500 15.000 31.901
122.500 15.000 32.245
30.000 20.000 26.680
35.000 20.000 30.014
40.000 20.000 29.179
45.000 20.000 30.706
50.000 20.000 31.876
55.000 20.000 32.537
60.000 20.000 32.935
65.000 20.000 31.029
70.000 20.000 31.382
75.000 20.000 31.881
80.000 20.000 32.248
85.000 20.000 34.454
90.000 20.000 36.176
95.000 20.000 36.225
100.000 20.000 36.330
105.000 20.000 35.640
110.000 20.000 36.064
115.000 20.000 36.938
37.500 25.000 35.274
42.500 25.000 34.259
47.500 25.000 35.940
52.500 25.000 37.754
57.500 25.000 37.988
62.500 25.000 36.234
67.500 25.000 37.214
72.500 25.000 37.393
77.500 25.000 36.264
82.500 25.000 37.777
87.500 25.000 40.253
92.500 25.000 41.933
97.500 25.000 41.046
102.500 25.000 41.881
107.500 25.000 41.502
45.000 30.000 40.738
50.000 30.000 41.896
55.000 30.000 41.146
60.000 30.000 40.495
65.000 30.000 41.525
70.000 30.000 41.150
75.000 30.000 41.621
80.000 30.000 45.445
85.000 30.000 43.027
90.000 30.000 44.608
95.000 30.000 45.270
100.000 30.000 45.925
52.500 35.000 47.185
57.500 35.000 44.643
62.500 35.000 44.951
67.500 35.000 45.868
72.500 35.000 43.911
77.500 35.000 46.849
82.500 35.000 47.314
87.500 35.000 47.489
92.500 35.000 47.975
60.000 40.000 47.455
65.000 40.000 49.644
70.000 40.000 49.657
75.000 40.000 45.735
80.000 40.000 51.727
85.000 40.000 51.371
67.500 45.000 53.283
72.500 45.000 54.119
77.500 45.000 54.899
0
0
0
0

**Comment by halbmy** [comment]
The problem is not the apparent resistivity, but the import. For some reason, neither `ert.load()` nor `pb.load` work (which I should fix), but
```
data = ert.importData.importRes2dInv("lintasan1.dat")
```
works and already contains apparent resistivity:
![image](https://github.com/gimli-org/gimli/assets/7136401/0c81a4bc-c5dc-4152-8788-92784f5509f8)

So I suggest using the following script
```
data.remove(data["rhoa"] < 10)
data.createGeometricFactors()
data.estimateError()
mgr = ert.Manager(data)
mgr.invert()
mgr.showResultAndFit()
```

**Comment by kafahabibullah1453** [comment]
thank u sir.. , i tried to run the inversion of data, and this is the result
![1](https://github.com/gimli-org/gimli/assets/128029937/f9f21e06-5c2e-445c-825e-9f51a132f90d)

sorry SIR when I running the data, there are several iterations that occur, can we set the number of iterations according to what we want? Maybe only 3 iterations or 4
<img width="644" alt="1-3" src="https://github.com/gimli-org/gimli/assets/128029937/95898a2e-b221-409a-af8b-07789e0b4581">

**Comment by halbmy** [comment]
The one data point is definitely an outlier that is better removed (see my script above) which leads to a better data quality.

The maximum iteration number can be set by `maxIter=` (https://www.pygimli.org/pygimliapi/_generated/pygimli.frameworks.html#pygimli.frameworks.Inversion)
