### ISSUE TITLE
Export ERT Inversion Result and Inversion Model

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#585]
Excuse Sir,
Is there any other function that can be used to export ERT inversion results to XYZ Resistivity? I have tried your instructions, but it doesn't seem to work. I want the data result as XYZ format from Res2DInv as I attached.
https://github.com/gimli-org/gimli/issues/520#issuecomment-1505384425
[Line3.txt](https://github.com/gimli-org/gimli/files/12642269/Line3.txt)
And is there any way to make my inversion cross section display remain trapezoidal both when no topographic data has been added, and when it has been added?

**Comment by halbmy** [comment]
It is clear that we do not support a proprietary format but you might want to export the resistivity with cell midpoints.

You can combine the solutions in #476 
> `np.savetxt("out.txt", np.column_stack((x, z, resMesh)))  # add fmt, delimiter or header keywords`
and #520 (`mgr.paraDomain`, `mgr.paraModel`) into
```
np.savetxt("out.txt", np.column_stack([pg.x(mgr.paraDomain), pg.y(mgr.paraDomain), mgr.paraModel]))  # add fmt, delimiter or header keywords
```
