### ISSUE TITLE
how to bring up a profile ERT field data with topography?

### ISSUE THREAD

**Issue by kafahabibullah1453** [gimli-org/gimli#586]
I tried to run my ert data with topography, there is some problem I have.
<img width="621" alt="7" src="https://github.com/gimli-org/gimli/assets/128029937/42facec1-c38d-474f-99cc-253b61273a5c">

Exception: field not in data container:  rhoa

appreciate any help

**Comment by halbmy** [comment]
In case of topography, the geometric factors (and therefore apparent resistivity) need to be computed numerically. Please have a look at the example:
https://www.pygimli.org/_examples_auto/3_dc_and_ip/plot_02_ert_field_data.html

**Comment by kafahabibullah1453** [comment]
excuse me sir, sorry. How to get XYZ file from inversion result with pygimli? (ERT data)

**Comment by halbmy** [comment]
Please see https://github.com/gimli-org/gimli/issues/585
