### ISSUE TITLE
Inversion method used in pygimly and pybert

### ISSUE THREAD

**Issue by kafahabibullah1453** [gimli-org/gimli#587]
Excuse me, What is the difference in inversion method between pygimli and pybert? Because I want to create an ERT profile with topographic data using BERT software, apart from that I also want to compare the profile result with topographic between Pygimli and BERT.

Appreciate any help, thanks

**Comment by halbmy** [comment]
The inversion is entirely in pyGIMLi, so there is no difference in the method and also not in the result. For ERT inversion, use the `ERTManager` from the `pygimli.physics.ert` module. BERT just holds methods for spectral IP inversion and command-line automation of ERT (maybe with slightly different defaults), but the method is the same. So a "comparison of pyGIMLi and (py)BERT does not make sense".

**Comment by kafahabibullah1453** [comment]
Excuse me sir, Does the BERT software have its own command or function to create a custom mesh?

**Comment by halbmy** [comment]
I don't quite understand. This is about pyGIMLi. On the website pygimli.org there are plenty of examples how to create custom meshes. For a specific question you would have to describe it explicitly.
