### ISSUE TITLE
Neumann BC outcome

### ISSUE THREAD

**Issue by svdbaan** [gimli-org/gimli#588]
Hello, given the following script, with specified Neuman BC at the right boundary. The solution gradient du/dx at that boundary appears to have value 0.2 (1/a) instead of the specified value 1.0. What is the cause of this?

    import pygimli as pg
    from numpy import linspace

    grid = pg.createGrid(x=linspace(0., 1., 11), y=linspace(0., 1., 11))

    u = pg.solve(grid, a=[0, 5.], bc={'Dirichlet': {1: 0.0}, 'Neumann': {2: 1.0}})

    pg.viewer.show(grid, u)

**Comment by halbmy** [comment]
```
gradU = pg.solver.grad(grid, u)
pg.show(grid, gradU[:, 0])
```
indeed shows a constant gradient of 0.2 in the whole mesh

![image](https://github.com/gimli-org/gimli/assets/7136401/73ff30a5-43fc-4c42-a5ed-b051f85a4e03)

and scales with the conductivity $a$. So it seems like the inhomogeneous Neumann conditions are actually applied to the (flow or current) field `a grad u` and not just `grad u`.
_

**Comment by svdbaan** [comment]
Thanks for your quick reply. Ok, clear.

The doc in https://www.pygimli.org/pygimliapi/_generated/pygimli.solver.html#pygimli.solver.solveFiniteElements says grad u now, so probably needs update.

**Comment by halbmy** [comment]
You're right, either the documentation is wrong or the code. For some applications it makes sense to constrain the pure gradient, for others the current (as this might be measured). Ideally both should be possible by a switch (and well-documented).
