### ISSUE TITLE
2D Rectangular mesh with geometry surface

### ISSUE THREAD

**Issue by lwang19-ai** [gimli-org/gimli#589]
### Problem description

I want to run the forward simulation and inversion of ERT. I want to do it in a 2D scenario with surface geometry info.
I want to make it a rectangular mesh. Is there some way to do it? 
Now I can create the mesh, but I don't know how to add nodes and refine it.

### Your environment

OS | Linux | CPU(s) | 20 | Machine | x86_64 | Architecture | 64bit
-- | -- | -- | -- | -- | -- | -- | --
RAM | 31.0 GiB | Environment | Jupyter | File system | ext4
Python 3.8.17 \| packaged by conda-forge \| (default, Jun 16 2023, 07:06:00) [GCC 11.4.0]
pygimli | 1.4.3 | pgcore | 1.4.0 | numpy | 1.22.4 | matplotlib | 3.7.2
scipy | 1.10.1 | tqdm | 4.66.1 | IPython | 8.12.0 | pyvista | 0.42.0

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python
# %%
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pygimli as pg
import pybert as pb
import multiprocessing as mp
from pygimli import meshtools as mt
from pygimli.viewer import showMesh
import pygimli.physics.ert as ert

plt.style.use("seaborn-notebook")

# Load the data
Kragge_Line1_72 = pd.read_excel('Kragge_ERT_GPS_Lines.xlsx', sheet_name='Line1_72', engine='openpyxl')
elecs = np.zeros((72, 2))
elecs[:, 0] = Kragge_Line1_72['x']
elecs[:, 1] = Kragge_Line1_72['z'] - Kragge_Line1_72['z'].max()

x_new = []
for i in range(len(elecs[:, 0])-1):
    # Append original value
    x_new.append(elecs[:, 0][i])
    
    # Append 1/4 point between i and i+1
    one_fourth = elecs[:, 0][i] + 1/4 * (elecs[:, 0][i+1] - elecs[:, 0][i])
    x_new.append(one_fourth)
    
    two_fourth = elecs[:, 0][i] + 2/4 * (elecs[:, 0][i+1] - elecs[:, 0][i])
    x_new.append(two_fourth)

    # Append 3/4 point between i and i+1
    three_fourths = elecs[:, 0][i] + 3/4 * (elecs[:, 0][i+1] - elecs[:, 0][i])
    x_new.append(three_fourths)

# Add the last element
x_new.append(elecs[:, 0][-1])
x_new = np.array(x_new)
# %%
# Interpolate the top boundary
z_new = np.interp(x_new, elecs[:, 0], elecs[:, 1])

# Create mesh
z_max = max(elecs[:, 1])
z_min = min(elecs[:, 1]) - 16.5
grid = pg.createGrid(x=x_new, y=np.linspace(z_min, z_max, 50))

# Adjust node positions to match the top boundary
for node in grid.nodes():
    idx = int((node.x() - min(x_new)) / (max(x_new) - min(x_new)) * (len(z_new) - 1))
    
    if node.y() > z_new[idx] or node.y() == z_max:
        pos = node.pos()
        pos[1] = z_new[idx]
        node.setPos(pos)
# Visualization
pg.show(grid, showNodes=True, showGrid=True)
plt.show()

x =30
y = x -2* np.random.uniform(10,15)

vel_gradient = []

for node in grid.cells():
    vel_gradient.append( x-y* np.random.randint(0,2))

scheme_dd = ert.createERTData(elecs, schemeName='dd')

for pos in scheme_dd.sensors():
    grid.createNode(pos)
    grid.createNode(pos - [0, 0.1])    

data = ert.simulate(grid, scheme=scheme_dd, res=vel_gradient, noiseLevel=1,
                    noiseAbs=1e-6, returnArray = True)
...
```

### Expected behavior

I want to run the forward simulation. But the added node has no corresponding cells.
![Screenshot_2023-09-26_13-27-38](https://github.com/gimli-org/gimli/assets/57149104/1d3a1521-82e3-4e1a-9d4c-7857f750bf58)

### Actual behavior

GIMLI::Cell* GIMLI::Mesh::findCell(const GIMLI::RVector3&, size_t&, bool) const  no cells for this node. This is a corrupt mesh

```
Paste output here.
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
A grid is a regular mesh where the nodes are already connected by cells. So you cannot just add nodes (like for creating PLCs) that are of couse hanging in the air. So you could either
* make sure the electrodes are already nodes in the grid by the deformation procedure
* treat the grid with nodes as PLC and re-mesh it
* or use a triangular mesh throughout by passing the scheme that already includes the electrodes with heights

**Comment by carsten-forty2** [comment]
"Found Neumann domain. Setting topography=1.
Found Neumann domain. but 2.5D -> neumann: false"

Means that he does not found any boundary conditions (BC) and falls back to homogeneous Neumann BC on all sides of your grid.  Homog. Neumann BC can be interpreted as isolation, e.g. outer surface and needs additional steps to be solved. Usually the left, right and bottom boundary would be marked as inner surface to get so called "Mixed" BC. 

The boundary conditions are choosen regarding the markers of the mesh boundaries. The defaults for ERT are `marker == -1` for outer surface ad `marker == -2` as mixed BC for the subsurface. You can see these markers by adding `boundaryMarkers=True` to `pg.show`.

You can change the boundary marker defaults of `greateGrid` by `worldBoundaryMarker=True`. Note, the Mixed BC assume a homogeneous resistivity distribution and a single electrode positition to assure accurate calculations. Since there are usually heterogeneities for any meaningfull multi electrode ERT simulation you need to set these boundaries 'far' away from the region of interest to keep the accuracy error small. With a factor of 10 of the maximum electrode spacing, you are on the safe side.

**Comment by lwang19-ai** [comment]
I think the weird part is using a rectangular mesh with topography. If I remove the following code, I will get correct simulated value.
```
# Adjust node positions to match the top boundary
for node in grid.nodes():
    if node.x() <= 141 and node.x() >= 0 and node.y()>=-3:
        idxes = np.where(node.x() == x_new)
        idx = int(idxes[0])
        if node.y() > z_new[idx] or node.y() == z_max:
            pos = node.pos()
            pos[1] = z_new[idx]
            node.setPos(pos)
```
My aim is to include the topography info in the mesh so that I can simulate real case measurement. 
I want to use the rectangular cell because it's easier for me to assign resistivity values based on different depth data.

**Comment by halbmy** [comment]
You should create a regular world grid (or mesh by appending a boundary) and interpolate the topography onto it
```
mx = pg.x(grid)
mt = np.interp(mx, xt, yt)
for i, n in enumerate(grid.nodes()):
    n.setPos([n.x(), n.y()+mt[i]])
```
![image](https://github.com/gimli-org/gimli/assets/7136401/ec04daef-df8d-49e3-965d-5462cc8cdc6d)

So you keep

**Comment by lwang19-ai** [comment]
It's interesting! Now I get this mesh and it works.
![image](https://github.com/gimli-org/gimli/assets/57149104/bb45c237-aeb8-44e1-8e72-988da1210761)

- I am curious about why it is necessary to adjust the bottom as well. It seems my former mesh contains some non-parallelogram mesh. Is that the reason for nan simulation results?
- Also,  @carsten-forty2 says 
` you need to set these boundaries 'far' away from the region of interest to keep the accuracy error small.`
If my interest area is the mesh area above, should I add boundaries far away from it like:
![image](https://github.com/gimli-org/gimli/assets/57149104/4ea5a24d-c523-40ce-9cbf-732f978ad122)
![image](https://github.com/gimli-org/gimli/assets/57149104/43de4863-3beb-4948-8073-56b67b5514c2)

Or I can just use the first mesh above?
Thank you a lot! It solves my mesh-generating problem anyway.

**Comment by halbmy** [comment]
The first mesh should work as well. The boundaries should be far enough if the conductivity contrasts are not too large. But in general, the edges do not strictly have to be parallel but it is the easiest way to deform the mesh as a whole.

**Comment by carsten-forty2** [comment]
The first might work or not, there is a lack of a systematic study of the magnitude of the boundary accuracy error. It depends on the conductivity contrast as well as the electrode positions. For performance reasons, BERT only calculates the mixed boundary conditions for one mean electrode position, so the accuracy will be affected more for data with electrodes on the sides. You should try it yourself to found a good compromise.

Also you can give this a try for you meshing:
https://www.pygimli.org/pygimliapi/_generated/pygimli.meshtools.html#pygimli.meshtools.extrudeMesh
(see examples therein)

**Comment by lwang19-ai** [comment]
Thank you all! I think you answered my questions!
