### ISSUE TITLE
module 'pygimli' has no attribute 'asvector'

### ISSUE THREAD

**Issue by kafahabibullah1453** [gimli-org/gimli#590]
Excuse me, sir. When I try to run an example script to make regular_mesh2d,  I had problem
<img width="595" alt="44" src="https://github.com/gimli-org/gimli/assets/128029937/c788a215-47dd-42a9-aefd-6b5fded293b7">

**Comment by halbmy** [comment]
Where did you find this script? It is clearly outdated. You don't need convert numpy arrays to pygimli vectors anymore.

**Comment by kafahabibullah1453** [comment]
> Where did you find this script? It is clearly outdated. You don't need convert numpy arrays to pygimli vectors anymore.

[https://gitlab.com/resistivity-net/bert/-/tree/master/examples/inversion?ref_type=heads](url)
This is source of my script

**Comment by halbmy** [comment]
I couldn't find any occurrence of `pg.asvector` in the BERT examples but anyway the scripts are outdated. Please have a look at the examples on pygimli.org

**Comment by halbmy** [comment]
Closing issue as not relevant for pygimli.org
