### ISSUE TITLE
Inversion error

### ISSUE THREAD

**Issue by question0825** [gimli-org/gimli#593]
How can I run with my data?

Plz look at my error.

![image](https://github.com/gimli-org/gimli/assets/65497262/2d330357-5bf7-4994-a2e6-f537e97f6d5c)

41# Number of sensors
#x	z
0	31.6
10	28.2
20	27.8
30	25.3
40	22
50	22.2
60	18.4
70	15.3
80	15.2
90	11.2
100	5
110	7.4
120	11.6
130	6.4
140	5.4
150	0
160	4.8
170	2.3
180	3.7
190	3.6
200	5.3
210	5.2
220	3.8
230	5.7
240	12.3
250	12.9
260	14.6
270	15.4
280	15.7
290	17.8
300	19.6
310	22.6
320	21.6
330	14.3
340	9.8
350	11.3
360	11.8
370	11.2
380	14.2
390	14.3
400	14.6
66# Number of data
#a	b	m	n	R
1	2	3	4	5.10190E-01
1	2	4	5	2.79956E-01
1	2	5	6	1.06980E-01
1	2	6	7	1.95665E-02
1	2	7	8	1.81925E-02
1	2	8	9	9.30444E-03
1	2	9	10	5.10370E-03
1	2	10	11	3.12242E-03
1	2	11	12	2.47250E-03
1	2	12	13	1.81788E-03
1	2	13	14	1.08193E-03
2	3	4	5	1.83597E+00
2	3	5	6	2.90439E-01
2	3	6	7	4.72624E-02
2	3	7	8	2.62905E-02
2	3	8	9	1.66346E-02
2	3	9	10	3.53424E-04
2	3	10	11	2.28468E-03
2	3	11	12	1.66493E-03
2	3	12	13	1.11530E-03
2	3	13	14	8.80007E-04
3	4	5	6	1.59742E+00
3	4	6	7	1.80710E-01
3	4	7	8	7.72952E-02
3	4	8	9	3.25230E-02
3	4	9	10	9.03799E-03
3	4	10	11	5.19644E-03
3	4	11	12	3.50915E-03
3	4	12	13	2.70948E-03
3	4	13	14	1.60367E-03
4	5	6	7	6.86195E-01
4	5	7	8	2.28700E-01
4	5	8	9	9.67203E-02
4	5	9	10	1.61138E-02
4	5	10	11	1.20833E-02
4	5	11	12	7.58259E-03
4	5	12	13	5.59028E-03
4	5	13	14	2.80147E-03
5	6	7	8	3.79203E-01
5	6	8	9	4.86716E-02
5	6	9	10	8.46409E-02
5	6	10	11	1.08120E-02
5	6	11	12	7.58608E-03
5	6	12	13	5.31151E-03
5	6	13	14	2.54303E-03
6	7	8	9	5.49466E-01
6	7	9	10	3.37636E-02
6	7	10	11	1.88468E-02
6	7	11	12	1.05448E-02
6	7	12	13	6.89453E-03
6	7	13	14	3.17957E-03
7	8	9	10	6.57858E-02
7	8	10	11	3.87470E-02
7	8	11	12	2.24195E-02
7	8	12	13	1.38763E-02
7	8	13	14	6.26940E-03
8	9	10	11	3.11768E-01
8	9	11	12	9.77811E-02
8	9	12	13	3.94959E-02
8	9	13	14	1.62535E-02
9	10	11	12	6.21186E-01
9	10	12	13	1.64383E-01
9	10	13	14	5.73441E-02
10	11	12	13	1.34890E+00
10	11	13	14	2.91518E-01
11	12	13	14	5.69030E-01

**Comment by halbmy** [comment]
Your apparent resistivities are all negative as the geometric factors are also negative. If you exchange the tokens for `m` and `n`, all should work well.

**Comment by halbmy** [comment]
Alternatively you can use a - or `np.abs` to get them positive.
