### ISSUE TITLE
Prior Data does not appear in the inversion Result ert

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#594]
Excuse Me. Sir
Prior Data does not appear in the inversion Result ert

I tried to plot the prior data with the ert inversion results that already had topographic data. But when the inversion result is finished, the prior data does not appear at all. Is there an error in the format or in the script?

This is My Code

```
import matplotlib.pyplot as plt
import numpy as np
import pygimli as pg
from pygimli.physics import ert
from pygimli.frameworks import PriorModelling, JointModelling
from pygimli.viewer.mpl import draw1DColumn

# Define a function to safely convert a string to a float, handling 'None' values
def safe_float(value):
    try:
        return float(value)
    except (ValueError, TypeError):
        return None


data1 = np.genfromtxt("D:/kedaireka/code_ert/pygimli/field_data/E01/X_1.dat", converters={2: safe_float})

# Assuming your data has three columns, unpack them into x, z, and r
x1, z1, r1 = data1[:, 0], data1[:, 1], data1[:, 2]

#%%

ERTdata = ert.load("D:/kedaireka/code_ert/pygimli/field_data/E01/E01.txt", verbose=True)
print(ERTdata)
ax, cb = ert.show(ERTdata)

#%%

ERTdata["k"] = ert.geometricFactors(ERTdata)
ERTdata["err"] = ert.estimateError(ERTdata, relativeError=0.1, absoluteUError=5e-6)
mgr = ert.ERTManager(ERTdata, verbose=True)
mgr.invert(lam=100, verbose=True, paraDepth=70, paraMaxCellSize=100)

# kw = dict(cMin=10, cMax=1000, logScale=True, cMap="Spectral_r",
#           xlabel="x (m)", ylabel="y (m)")
kw = dict(logScale=True, cMap="Spectral_r",
          xlabel="x (m)", ylabel="y (m)")
ax, cb = mgr.showResult(**kw)

zz1 = np.abs(z1)
iz1 = np.argsort(zz1)
thk1 = np.hstack([0, np.diff(zz1[iz1])])
draw1DColumn(ax, x=x1[0], val=r1[iz1], thk=thk1, width=4, **kw)
ax.grid(True)
```
This My Prior Data and ERT Data

[X_1.txt](https://github.com/gimli-org/gimli/files/12760490/X_1.txt)
[E01.txt](https://github.com/gimli-org/gimli/files/12760502/E01.txt)
![WhatsApp Image 2023-09-29 at 13 50 24](https://github.com/gimli-org/gimli/assets/126912836/fe47adeb-4340-417d-b7fa-0e469a3699bb)

**Comment by halbmy** [comment]
For the function `draw1DColumn` (made for 1D models) you specify the thickness vector but the absolute height is gone (and the model moves to below zero). You additionally have to specify the top of the column (topography) by `ztopo=zz1[0]`. Note that your thickness vector has a zero at the beginning, you can directly use `np.diff(zz1[iz1])`.

**Comment by halbmy** [comment]
You should remove the clear outlier by
```
ERTdata.remove(ERTdata["rhoa"] > 3000)
```
and maybe more. You might have to remove two electrodes completely as the pseudosection looks strange
![image](https://github.com/gimli-org/gimli/assets/7136401/899b7042-e2a0-492e-bdba-39890eb2f4a5)

**Comment by tonapawilliam** [comment]
![image](https://github.com/gimli-org/gimli/assets/126912836/bbbc8fbf-141f-428f-bf1f-78ec44682512)
It's work. Thank You Sir

**Comment by halbmy** [comment]
Added a notebook on https://github.com/gimli-org/notebooks/blob/main/issues/594/issue594.ipynb
