### ISSUE TITLE
Fatray Inversion Coverage

### ISSUE THREAD

**Issue by benbpete** [gimli-org/gimli#596]
### Problem description

Issue with "showCoverage" when using fatray. I would just like to confirm that my solution is indeed correct.

### Your environment

--------------------------------------------------------------------------------
  Date: Tue Oct 03 13:46:08 2023 Eastern Daylight Time

                OS : Windows
            CPU(s) : 20
           Machine : AMD64
      Architecture : 64bit
               RAM : 31.7 GiB
       Environment : Jupyter

  Python 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:40:31) [MSC
  v.1929 64 bit (AMD64)]

           pygimli : 1.4.4
            pgcore : 1.4.0
             numpy : 1.21.6
        matplotlib : 3.7.1
             scipy : 1.11.2
           IPython : 8.15.0
           pyvista : 0.42.2
--------------------------------------------------------------------------------

### Steps to reproduce

using the "fatray.ipynb", when you try to display coverage, you receive a ValueError

I would like to display the coverage using the fatray method, similar to Jordi et al, 2016, displaying the column sum of the Jacobian matrix.

### Actual behavior

received the following error:

```
ValueError                                Traceback (most recent call last)
Cell In[25], line 1
----> 1 mgr.showCoverage()

File ~\anaconda3\envs\pg\lib\site-packages\pygimli\physics\traveltime\TravelTimeManager.py:397, in TravelTimeManager.showCoverage(self, ax, name, **kwargs)
    393     fig, ax = pg.plt.subplots()
    395 cov = self.rayCoverage()
    396 return pg.show(self.fop.paraDomain,
--> 397                pg.log10(cov+min(cov[cov > 0])*.5), ax=ax,
    398                coverage=self.standardizedCoverage(), **kwargs)

ValueError: min() arg is an empty sequence
```

To display the column sum of the Jacobian, i added the following code, and received the following output. I would like to confirm that this is indeed correct and I'm not missing any details.  Thank you!

```
jacobian = mgr.fop.J
column_sums = np.array(jacobian).sum(axis=0)
pg.show(mgr.paraDomain, column_sums)
plt.show()
```
![fatray_coverage](https://github.com/gimli-org/gimli/assets/105517351/1c6c96f2-4dc1-4a57-a003-a8083a3a3fb5)

**Comment by halbmy** [comment]
Converting the sparse jacobian matrix into a full numpy matrix can be a problem for large problems. Better multiply with a vector of ones from the left (so that all data are added up). Actually this should be in the code and I will check and correct that.

**Comment by halbmy** [comment]
I just had another look into it now. It seems that something destroys the actual jacobian matrix so that all coverage calls go fail. We need to dig into that.

However, it does not affect th result, and you can still access the matrix by `fop.J` so that you can show the coverage:
```
J = mgr.fop.J
cov = J.transMult(np.ones(J.rows()))
pg.show(mgr.paraDomain, cov)
```
![image](https://github.com/gimli-org/gimli/assets/7136401/4c4332a0-06e8-449a-9707-6e7cfd817464)

**Comment by benbpete** [comment]
Thanks @halbmy , this is helpful and answers my question. I'll leave the thread open in case you wanted to keep it open for addressing calling the coverage directly.

**Comment by halbmy** [comment]
Just came across this bug by accident and (hot)fixed it. Now the coverage works for fatray as for slim ray.
