### ISSUE TITLE
Global Coordinate in Format Data ERT

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#598]
Excuse me Sir, 
Can pygimli read global coordinates in ERT data in res2dinv format? Or maybe in a format that is compatible with Pygimli ERT that can read global coordinates data?
Thank You 
![image](https://github.com/gimli-org/gimli/assets/126912836/3956623e-5cb8-4aaf-b083-5c7475be0995)

**Comment by halbmy** [comment]
No, we do not read global coordinates from res2dinv (https://gitlab.com/resistivity-net/bert/-/issues/47) and won't invest time in that, but if you enhance the code the coordinates could be packed into the header dict. Interpolation of the local inversion results should be very simple with numpy and could make a nice example or notebook.
