### ISSUE TITLE
Constraints in Time-Lapse ERT inversion

### ISSUE THREAD

**Issue by johanneshoppenbrock** [gimli-org/gimli#599]
Hey there! 
I have a question about time-lapse inversion in 4D with MultiFrameModelling(). I have used the example https://github.com/gimli-org/notebooks/blob/main/ERT/timelapse/2dxh/fullTimelapse.ipynb as a guide and it works fine.
My question about this would be: How can I regulate the smoothness in the individual time steps and between the respective time steps? 

### Environment

**Operating system**: Windows
**Python version**: 3.9
**pyGIMLi version**: 1.4.4
**Way of installation**: Conda package

**Comment by halbmy** [comment]
For the spatial constraints, you can set any behaviour by `fop.setRegionProperties()`.

For the constraints along the frames, you can specify a factor by 
```
fop = MultiFrameModelling(ert.ERTModelling, scalef=1.0)
```

A factor of >1 increases the (in this case) temporal constraints, <1 decreases them.

**Comment by johanneshoppenbrock** [comment]
Thank you very much! Do I understand it right that also the regularization parameter lambda which is defined in the `inv.run()` command is multiplied by the scalefactor?

**Comment by halbmy** [comment]
yes. The lambda parameter weights the summed model roughness, but the scalef factor the roughness into the frame direction.

**Comment by johanneshoppenbrock** [comment]
Thank you very much!

**Comment by halbmy** [comment]
Note that the newest version v1.4.5 includes a TimeLapseERT manager able to do different timelapse strategies. Have a look at the example on pygimli.org: https://www.pygimli.org/_examples_auto/3_ert/plot_09_timelapse.html

**Comment by johanneshoppenbrock** [comment]
Thats very helpful, thank you! 

I have another question now: Is it possible to perform a full timelapse inversion also for FDIP (at a single frequency) data? So far, I have been unable to construct a suitable forward operator using `pg.frameworks.MultiFrameModelling()` for this purpose. 
For TDIP data, I attempted to use `pg.frameworks.MultiFrameModelling(ert.ipModelling.DCIPMModelling)` but encountered difficulty in constructing the data vector that includes both resistivities and chargeabilities.

**Comment by halbmy** [comment]
The answer is as usual: Of course it is generally possible, but we are either missing an example or this seems to be the first case. 

For (single-frequency) FDIP, the most rigorous way should be using the fully complex forward operator, but for both FD and TD one could do first a timelapse ERT inversion a timelapse IP inversion using the operators you mention. As there might be details, I guess we need a common code space to work on together before we can share the solution here.
