### ISSUE TITLE
Potential lightweight boost alternative

### ISSUE THREAD

**Issue by florian-wagner** [gimli-org/gimli#60]
https://github.com/pybind/pybind11

**Comment by carsten-forty2** [comment]
interesting .. looks very promising .. 

I need to look at it further .. need to find out if there is need for a special py++ output generator for pybind11 .. or maybe they provide alternative ways to generate the binding code for our whole library

**Comment by carsten-forty2** [comment]
(note for myself)

take a look at swig .. it seems it made some great progress in the last years

**Comment by halbmy** [comment]
We don't see any potential activity here and close the issue.
