### ISSUE TITLE
Question about ERT inversion result.

### ISSUE THREAD

**Issue by shdlovezxm** [gimli-org/gimli#604]
### Problem description

Hello, can you tell me how to represent ERT inversion results in the form of inverted triangles, similar to the results obtained from the Res2Dinv software? Thanks.

It might be similar to the "coverage=mgr.standardizedCoverage()" in refraction inversion.

**Comment by halbmy** [comment]
In pyGIMLi, we represent the subsurface exactly how it is inverted (also by res2dinv!): assuming piece-wise constant resistivity. Whether you choose triangles or quadrangles (like res2dinv) is your choice. 

res2dinv displays the result as an interpolation from the cell midpoints. Of course you can also do that easily using the `pg.viewer.mpl.drawField` function which in turn redirects to matplotlib contourf.

If your question is about the coverage (the res2dinv trapezoid), you can use a coverage threshold by `showResult(..., coverage=mgr.standardizedCoverage(thrsh))`

**Comment by shdlovezxm** [comment]
Yes, my question is about coverage.  How to obtain results similar to the above figure. thanks.


![image](https://github.com/gimli-org/gimli/assets/133296469/3f414342-0843-49a5-a47e-8b89129bd563)
![image](https://github.com/gimli-org/gimli/assets/133296469/b426f982-eab5-4fe7-bbee-3490cf5397c0)

**Comment by halbmy** [comment]
Obviously the coverage does not have a trapezoid shape and depends also on the conductivity, so choose the threshold wisely.

The default model boundary is a box and not a trapezoid, but you can create one by moving the lower two points accordingly.

**Comment by shdlovezxm** [comment]
[NWG-1M.txt](https://github.com/gimli-org/gimli/files/13043219/NWG-1M.txt)

Here is my data and code. Could you please help me with specific modifications? Thank you very much.

import numpy as np
import pygimli as pg
from pygimli.physics import ert

data=ert.load("./NWG-1M.txt")
print(data)

data['k'] = ert.createGeometricFactors(data)
print(data)

k0 = ert.createGeometricFactors(data)

ert.showData(data, vals=k0/data['k'], label='Topography effect')

mgr = ert.ERTManager(sr=False)

mgr.checkData(data)
data.remove(data['rhoa'] < 0)
ert.showData(data)
print(data)

data['err'] = ert.estimateError(data, absoluteUError=5e-5, relativeError=0.03)
print(data)
ert.show(data, data['err']*100)

inv = mgr.invert(data, lam=20, verbose=True, quality=33.6)
#mgr.showResult()
mgr.showResult(cMin=6, cMax=10000, logScale=True, coverage=mgr.standardizedCoverage(-2))

**Comment by halbmy** [comment]
```
plc = mt.createParaMeshPLC(data, boundary=0.5)
pg.show(plc)
plc.positions().array()[:10]
```
![image](https://github.com/gimli-org/gimli/assets/7136401/bd8f7d14-a45d-423c-af67-c758a6708f40)

shows that the lower boundary of the inversion domain are defined by the second and third node, so you can change it
```
plc.node(1).setPos([25, -20])
plc.node(2).setPos([90, -5])
pg.show(plc)
```
![image](https://github.com/gimli-org/gimli/assets/7136401/e2a8237a-b018-4bd7-9379-069764429158)

You also need to set the region marker by `plc.regionMarker(2).setPos([50, 0])`

```
mesh = mt.createMesh(plc, quality=34)
data.estimateError(absoluteUError=5e-5, relativeError=0.03)
mgr = ert.Manager(data)
mgr.invert(mesh=mesh, verbose=True)
mgr.showResult(cMin=20, cMax=3000, coverage=1)
```
![image](https://github.com/gimli-org/gimli/assets/7136401/b72ba2d4-ebfd-4205-91b5-02831cb16678)

**Comment by halbmy** [comment]
Note: We might add this or other styles optionally to `createParaMeshPLC` like with `balanceDepth`.

**Comment by shdlovezxm** [comment]
I understand. Thank you for your patient explanation. Good luck to you.
