### ISSUE TITLE
RuntimeError: There is a requested electrode that does not match the given mesh.

### ISSUE THREAD

**Issue by Abby123455r** [gimli-org/gimli#605]
hi, when i try to run inversion i face the following error.
There is a requested electrode that does not match the given mesh. could you please tell me what is the issue and how can we resolve it

**Comment by halbmy** [comment]
It seems like your electrode position is not in the given mesh. However, I cannot tell anything without knowing what you did.

**Comment by Abby123455r** [comment]
Thanks issue has been resolved.but i want to ask another question that we performed experiment on a bucket and we have have resistivty and IP data.i performed the resistivity inversion through the following steps.which is working well.but i want to include the IP data as well.could u please guied me how i can include it
rBottom = 0.154 / 2
rTop = 0.164 / 2
height = 0.164
plc = mt.createCylinder(radius=rBottom, height=height, nSegments=64)  #unit dimensions
plc.translate([0, 0, height/2])
pg.show(plc)
filename1 = 'Data.udf' #data file with resistance value
data1 = pg.DataContainerERT(filename1)
print(data1)
sens = pg.Mesh(3)
[sens.createNode(sen) for sen in data1.sensors()]
print(sens)
mesh = mt.createMesh(plc) 
data1["err"] = ert.estimateError(data1, relativeError=0.02, absoluteUError=0)
mgr = ert.ERTManager(data1, sr=False)
baseline= mgr.invert(verbose=True,mesh=mesh,lam=20)
Could you please guied me how can we add IP data to see the response .

**Comment by halbmy** [comment]
Please use the `ERTIPManager` instead and make sure the datafile contains a column with ip.

**Comment by Abby123455r** [comment]
when i try this 
mgr = ert.ERTIPManager(data1, sr=False)
it showes following error module 'pygimli.physics.ert' has no attribute 'ERTIPManager

**Comment by halbmy** [comment]
Which version do you have? 

The ERTIPManager was only recently introduced into v1.4.3 in July.

**Comment by Abby123455r** [comment]
i am using 1.2.6 version

**Comment by Abby123455r** [comment]
when i try this 
pip install --upgrade pygimli.. it shows 
Requirement already satisfied: pygimli in c:\programdata\anaconda3\envs\conda_environments1\lib\site-packages (1.2.6)
Note: you may need to restart the kernel to use updated packages.

**Comment by halbmy** [comment]
pyGIMLi cannot be installed (or updated) by pip. See https://www.pygimli.org/installation.html

**Comment by halbmy** [comment]
What about the original problem? Did you find the reason for the error? I cannot reproduce it without `data.udf`.

**Comment by Abby123455r** [comment]
yes it is resolved thank you
