### ISSUE TITLE
Question: How to verify the inverted and observed results accuracy in traveltime inversion?

### ISSUE THREAD

**Issue by makeabhishek** [gimli-org/gimli#606]
Hi,
I was trying crosshole traveltime tomography example, I would like to know how can I check the difference between the observed data and predicted data? Can we plot the two data in a graph showing the observed traveltime and inverted traveltime to see the difference?  
I tried to extract data as 

```
pickTT = np.array(mgr.data('t'))
modTT = np.array(mgr.inv.response)
plt.plot(pickTT)
plt.plot(modTT)
```

Is there other better way to check the accuracy of the model?

Also, Why the pygimli showing 
When I'm trying to allocate error to the data, `error  = mgr.estimateError(data=data,absoluteError=1e-6)` Its giving me error `TypeError: MethodManager.estimateError() got an unexpected keyword argument 'absoluteError'`
> pyGIMLi - ERROR - <class 'pygimli.physics.traveltime.TravelTimeManager.TravelTimeManager'>.checkError(TravelTimeManager.py:97)

**Comment by halbmy** [comment]
Please read the example
https://www.pygimli.org/_examples_auto/2_seismics/plot_04_koenigsee.html
using the following code
```
ax, cbar = mgr.showData(firstPicks=True, linewidth=0)
tt.drawFirstPicks(ax, data, mgr.inv.response, marker=None)
```
which could actually be `mgr.showFit(firstPicks=True)` (otherwise the apparent velocities are shown).

**Comment by halbmy** [comment]
just implemented (#e860be2d) `mgr.showFit(firstPicks=True)` and used it in the mentioned example

**Comment by makeabhishek** [comment]
Thanks, Do i need to update pygimli for this change?
What I was thinking to draw a line plot for a particular shot (x-axis) and all receivers (y-axis) with observed data and inverted data.

**Comment by halbmy** [comment]
you would have to use the latest dev version: https://www.pygimli.org/installation.html#staying-up-to-date

but in your case this is not necessary, as you can just use these two lines
