### ISSUE TITLE
New structure for testdata

### ISSUE THREAD

**Issue by florian-wagner** [gimli-org/gimli#62]
Test data files should not be part of the library. Since they are static, we could provide something like `pg.testing.get_testdata` to download them from a webserver. This approach is used by other packages as well. If they are not too big in size, we could distribute them in a different folder (and install them to `usr/share` for example.).

``` python
=========================================== ERRORS ===========================================
_ ERROR collecting miniconda3/lib/python3.6/site-packages/pygimli/physics/em/fdemexample.py __
miniconda3/lib/python3.6/site-packages/pygimli/physics/em/fdemexample.py:13: in <module>
    fdem = FDEM(datafile)
miniconda3/lib/python3.6/site-packages/pygimli/physics/em/fdem.py:201: in __init__
    self.importMaxminData(filename)
miniconda3/lib/python3.6/site-packages/pygimli/physics/em/fdem.py:325: in importMaxminData
    fid = open(filename)
E   FileNotFoundError: [Errno 2] No such file or directory: '/home/wagner/miniconda3/lib/python3.6/site-packages/pygimli/physics/em/example.xyz'
```

**Comment by halbmy** [comment]
agreed.
It was mainly me who put an example file and a script to work with it to the folder of the class but they should all go to the examples folder (retrieving the files from the web or locally).

**Comment by florian-wagner** [comment]
`pg.getExampleFile` and https://github.com/gimli-org/example-data
