### ISSUE TITLE
How to create a 2D velocity model from a 1D array data?

### ISSUE THREAD

**Issue by makeabhishek** [gimli-org/gimli#620]
### Problem description
I want to create a smooth model from a 1D array for a circular geometry. For example, I have an array consist of velocity data, and now I want to create a circle with concentric smooth circles for this 1D data. 

### Your environment

--------------------------------------------------------------------------------
  Date: Tue Nov 21 15:16:48 2023 MST

                OS : Linux
            CPU(s) : 40
           Machine : x86_64
      Architecture : 64bit
               RAM : 62.5 GiB
       Environment : Jupyter
       File system : ext4

  Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32)
  [GCC 12.3.0]

           pygimli : 1.4.3
            pgcore : 1.4.0
             numpy : 1.23.5
        matplotlib : 3.7.2
             scipy : 1.11.1
              tqdm : 4.66.0
           IPython : 8.14.0
           pyvista : 0.41.1

### Steps to reproduce
```
import numpy as np
import matplotlib.pyplot as plt
import pygimli as pg
import math 
import scipy as sp
from scipy import stats

from pygimli import meshtools as mt
from pygimli.physics import ert
from pygimli.physics import traveltime as tt
from pygimli.physics import TravelTimeManager
from pygimli.physics.petro import transFwdWyllieS as WyllieTrans

rad=149e-3
c1 = mt.createCircle(radius=rad, pos=[0.0, 0.0], nSegments=32,area=0.0025, marker=1)
poly = mt.mergePLC([c1])
poly.addRegionMarker([0.0, 0, 0], 1, area=0.0015)

numberSources = 16
c = mt.createCircle(radius=rad, nSegments=numberSources, start=np.pi, end=np.pi*3)
[poly.createNode(p.pos(), -99) for p in c.nodes()]
mesh = pg.meshtools.createMesh(poly, quality=32.0, area=0.011e-3, smooth=[1, 10])
petro = pg.solver.parseArgToArray([[1, 0.9]],mesh.cellCount(), mesh)
saturation = petro
ax,_ = pg.show(mesh)
#--------------------------%--------------------------#
radius_data = np.arange(0, 50, 0.01)
vel_data = stats.norm.pdf(radius_data, 15, 10)*55500
plt.plot(radius_data, vel_data)
plt.show()
#--------------------------%--------------------------#
# ttTrans = WyllieTrans(vm=4000, vw=1500, phi=0.1)
# vel = 1./ttTrans(saturation)
vel = 1./vel_data
# Sensor positions
sensors = mesh.positions()[mesh.findNodesIdxByMarker(-99)]
#--------------------------%--------------------------#
ax, _ = pg.show(mesh, vel, colorBar=True, logScale=False, label='v [m/s]')
pg.viewer.mpl.drawSensors(ax, sensors, diam=0.02)
#--------------------------%--------------------------#
# Simulate traveltimedata
mgr = TravelTimeManager()

pg.info("Simulate Traveltime")
ttScheme = tt.createRAData(sensors)
ttData = tt.simulate(mesh, scheme=ttScheme, vel=vel,noiseLevel=0.01, noiseAbs=4e-6)
mgr.showData(ttData)

print(ttData)
```

expecting a smooth model which follows 1D profile of `vel_data`. a schematic figure shows below, different colour means different velocity. 

![circle](https://github.com/gimli-org/gimli/assets/47937684/10f48834-b376-4748-be01-54b4240f6d68)

**Comment by halbmy** [comment]
I don't quite understand your problem. If you have many concentric rings, you should use `createCircle` repeatedly. If want to associate values depending on the location, use `pg.x(mesh)` etc. to evaluate the function. 

Try breaking down the problem to a simplistic one, e.g. 3 concentric rings, and focus on the model only. Show what your script generates and what the problem is.

**Comment by makeabhishek** [comment]
I mean to create a smooth model following a distribution given in 1D data?

**Comment by halbmy** [comment]
To point 1: You can either create your mesh directly in mm or you can scale it before plotting by `mesh.scale([1000, 1000])`. But maybe you can also look into matplotlib axis transforms: https://matplotlib.org/stable/users/explain/artists/transforms_tutorial.html

**Comment by halbmy** [comment]
To point 2: You can use a code like this:
```
from scipy.interpolate import interp1d
cc = mesh.cellCenters()
r = np.sqrt(pg.x(cc)**2+pg.y(cc)**2)
f = interp1d(my_radius, my_velocity)
v = f(r)
```

**Comment by makeabhishek** [comment]
> To point 3: The node positions are `pg.x(mesh)` and `pg.y(mesh)` but I don't see points exactly at x=0.

Here I mean to extract all the values for either x=0 or y=0. Say want to extract nodes (x,y-coordinates), for the line passing through the center.

**Comment by halbmy** [comment]
Looking at your irregular triangular mesh, there won't be any node exactly on the x or y axis. If you need them, place lines in the plc before meshing. Otherwise just do interpolation, there are some examples to this point if you search for it.

**Comment by makeabhishek** [comment]
> To point 2: You can use a code like this:
> 
> ```
> from scipy.interpolate import interp1d
> cc = mesh.cellCenters()
> r = np.sqrt(pg.x(cc)**2+pg.y(cc)**2)
> f = interp1d(my_radius, my_velocity)
> v = f(r)
> ```

I tried to implement this but there is error in interpolating the values.

`ValueError: A value (0.1378670175817536) in x_new is above the interpolation range's maximum value (0.071621).`
