### ISSUE TITLE
model refinement 

### ISSUE THREAD

**Issue by Abby123455r** [gimli-org/gimli#621]
what are the possible ways to get high resolution final model? here is my script
```
filename1 = '01_1.udf'
data1 = pg.DataContainerERT(filename1)
sens = pg.Mesh(3)
[sens.createNode(sen) for sen in data1.sensors()]
print(sens)
for s in data1.sensors():   
    plc.createNode(s, marker=-99)  #add the electrodes as nodes with marker -99 to the geometry
    plc.createNode(s - [0.0, 0.0, 1e-3/2])
mesh = mt.createMesh(plc) 
data1["k"] = pg.Vector(data1.size(), 1.0)
out1 = ert.simulate(mesh=mesh, scheme=data1, res=1.0, calcOnly=True)
print(out1)
data1["k"] = 1.0 / out1["u"]
data1["rhoa"] = data1["r"] * data1["k"]
tmp = pg.DataContainerERT(data1)
for i in range(tmp.sensorCount()):
    tmp.setSensor(i, [i, 0, 0])
data1["err"] = ert.estimateError(data1, relativeError=0.02, absoluteUError=0)
mgr = ert.ERTManager(data1, sr=False)
   mgr.invert(verbose=True,mesh=mesh,lam=20)
``` 
could you guied me about the ways through which i can improve the resolution?

**Comment by halbmy** [comment]
In your script, I am missing a box describing the world, I doubt this could run. You should use a function like `createParaMeshPLC3D` or `createWorld` for doing so. Please have a look at the examples.

**Comment by Abby123455r** [comment]
yes you are right i missed some lines.it is working on my system. i want to know the possible ways to improve the resolution of final model .

**Comment by Abby123455r** [comment]
yes you are right few lines are missing from code. i used this meshP = mesh.createP2() to improve resolution.

**Comment by makeabhishek** [comment]
You can define the element size in the mesh using area, which can improve the resolution. 
`mesh = mt.createMesh(plc, area=0.011e-3, smooth=[1, 10])`

**Comment by Abby123455r** [comment]
Thank you. i will try to implement it

**Comment by halbmy** [comment]
Did it work out? The `area` keyword is the maximum cell size, for 3D a volume, this is of course depending on your scale and might therefore take completely different values. You should also ensure high-quality meshes by, e.g., `quality=1.3` in the `createMesh` call.

**Comment by halbmy** [comment]
closing due to missing response
