### ISSUE TITLE
New structure for examples on website

### ISSUE THREAD

**Issue by florian-wagner** [gimli-org/gimli#63]
I suggest to leave the structure for the tutorials as it is (Modeling and Inversion), while structuring the Examples by methods. This way, we can extract all the little test_refraction.py etc. from the library tree and add some documenting text on how to use the respective method manager.

**Comment by carsten-forty2** [comment]
agree

**Comment by halbmy** [comment]
Agree. I guess we will focus the examples on the managers, i.e. using them or creating an own one?
Examples should mostly be self-contained scripts, e.g. a synthetic model that is later inverted (without any external files):
1. generate data scheme and initialize manager
2. assume a model and run forward calculation (simulate), followed by adding some noise
3. save the results in a way that any field data could be processed to the same format
4. use the manager to load them, do basic analyses and do inversion
What about pure example on how to use it for real data inversion (e.g. from published data)?
