### ISSUE TITLE
FInite Element Analysis in Pygimli ERT

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#630]
Excuse me Sir, Do You have any publication or something about Finite Element in ERT which use in this Pygimli? I want to learn about basic of Finite Element and I want to know how to use finite element in forward modelling in ERT? Especially about triangular element which use in Mesh and use that in Forward Model of Pygimli ERT. Thank You

**Comment by halbmy** [comment]
The ERT modelling with FEM is described in detail by Rücker et al. (2006) and Rücker & Günther (2011). 

* Rücker, C., Günther, T. & Spitzer, K. (2006): Three-dimensional modeling and inversion of dc resistivity data incorporating topography – I: Modeling. Geophys. J. Int. 166, 495-505doi:10.1111/j.1365-246X.2006.03010.x.
* Rücker, C. & Günther, T. (2011): The simulation of Finite ERT electrodes using the complete electrode model. Geophysics 76(4), F227-238, doi:10.1190/1.3581356.

**Comment by tonapawilliam** [comment]
Thank You Sir
