### ISSUE TITLE
How to improve inversion accuracy?

### ISSUE THREAD

**Issue by lwang19-ai** [gimli-org/gimli#631]
### Problem description

- I did a 2D inversion for ERT data. The result shows a relatively large misfit. 
- The response seems smaller than Data. I changed the lambda value from 10 to 5 for regularization, but there is no obvious improvement.
![image](https://github.com/gimli-org/gimli/assets/57149104/bb149f64-399a-4019-8b8e-ca1006761e81)

![image](https://github.com/gimli-org/gimli/assets/57149104/bd2a2943-c780-407f-83c2-4fe3e3c390c2)

- Finally I changed the lambda to 0. Then I get this result:
![image](https://github.com/gimli-org/gimli/assets/57149104/5b244d50-7824-4890-8724-194f8c75aac3)

So the question is:
- How should I improve the inversion accuracy? It seems the result without regularization is more accurate. How should I evaluate which inversion is better?

**Comment by shdlovezxm** [comment]
Based on this issue, I would like to know how to improve the appearance of the plotted results. In the above figure, the horizontal axis has a length of around 140, while the vertical axis has a length of around 20. The aspect ratio makes the plot results look unappealing. thanks! @halbmy 

mgr.showResult()

**Comment by halbmy** [comment]
As I've told you before, the 20m depth might be too low and you should change this.

But what do you mean with unappealing? Visualization is something you should invest time. pyGIMLi provides useful tools but it is up to the user. The result of the `showResult` function is a matplotlib axes object with which you can improve your figure like aspect ratio, labels etc.

**Comment by lwang19-ai** [comment]
> Something is wrong with your error estimation. You achieve a chi-square < 1 with a relatively large RRMS (and then the inversion stops), so your error estimate is definitely too pessimistic. How did you do that? Moreover, I noticed that your model depth is probably too small.

- First question about the measurement error
Thank you for the response. I checked the error data in the raw file. If I did reciprocal measurement, I used the mean of two error data. If there is only one measurement file, I directly used the err column in syscal pro machine measurement file.
Here is one plot of the err. I removed data with errors larger than 20.
![image](https://github.com/gimli-org/gimli/assets/57149104/da82868d-7a48-4b2a-91a3-8a933c759045)
And this is the apparent rhoa data and relative error:
![image](https://github.com/gimli-org/gimli/assets/57149104/c8aecf64-fd2b-4e07-92aa-75ddd8aebf51)
![image](https://github.com/gimli-org/gimli/assets/57149104/48bb63e1-f68b-411f-9ca3-019055e5cfa7)


- Second question about the depth.
I chose the above depth because this is a measurement for a landfill which is around 150m * 20m. The area below 20m  has different components and is not our interested part. Why do I need to use a larger depth? Is it better for inversion?

**Comment by halbmy** [comment]
looks good. There are a few low apparent resistivity points that cannot be fitted but otherwise good. I guess there won't be much resolution below 25-30m depth. Maybe you can improve things be some `zWeight` < 1.

**Comment by halbmy** [comment]
I don't quite understand. It sounds like it is a rather simple workflow and if you're inverting synthetic data you should be able to find a model fitting the data even though the result may differ from the synthetic model. I guess you should write down some sort of a code. And maybe discuss this in a separate issue.

**Comment by lwang19-ai** [comment]
Yes, you are right. The workflow is correct. I find there was a mistake in my former script. Thank you!
