### ISSUE TITLE
Failed install pygimli from anaconda because dependencies pyplusplus and pygccxml is missing from channel gimli and conda-forge

### ISSUE THREAD

**Issue by yogahariman** [gimli-org/gimli#633]
What's channel for pyplusplus and pygccxml?
i failed install pygimli from anaconda because can't find yplusplus and pygccxml in channel conda-forge and gimli

**Comment by carsten-forty2** [comment]
Don't sure if there is a conda channel for it, but you can install it with pip.

**Comment by yogahariman** [comment]
I have problem when install pygimli like manual because always failed.
When i check all dependencies i found pyplusplus and pygccxml missing from channel gimli and conda-forge.

**Comment by halbmy** [comment]
> Failed install pygimli from anaconda

If you have anaconda, you should install pygimli using the given the conda command. You only need pygccxml and pyplusplus when building pyGIMLi from the source. Then you can just `pip install pygccxml` (and pyplusplus).
We just realized https://www.pygimli.org/compilation.html is broken and will fix this.
