### ISSUE TITLE
Failed to install pygimli on Ubuntu

### ISSUE THREAD

**Issue by yogahariman** [gimli-org/gimli#638]
I try install pygimli on ubuntu but always failed.
And my memory full when unsuccessful solving environtment

![Screenshot from 2024-01-03 10-19-38](https://github.com/gimli-org/gimli/assets/23205270/43b08078-e7e6-4b2e-9739-5aa03eb21255)
![Screenshot from 2024-01-03 10-19-43](https://github.com/gimli-org/gimli/assets/23205270/47b7bf1f-59d7-48e7-95a8-c612dabcd20b)

**Comment by florian-wagner** [comment]
It's a conda solver issue. Please try the recommendation in issue #637.

**Comment by yogahariman** [comment]
Thanks. 
i try on windows default solver is libmamba.
and ubuntu default solver still classic.

**Comment by florian-wagner** [comment]
Happy to hear that it works with the faster solver. It is the default on all platforms since conda 23.10 https://github.com/conda/conda/blob/main/CHANGELOG.md#23100-2023-10-30
