### ISSUE TITLE
Questions on TimelapseERT

### ISSUE THREAD

**Issue by verocordero** [gimli-org/gimli#639]
I am currently working on a surface ERT inversion of a salt tracer test using the class TimelapseERT within the pygimli version 1.4.6. I find it practical to work with large data sets, however I have some questions about it. 
1-	What is the difference between tl.invert() and tl.fullinversion()? Where can I find out more information about the fullinversion? Do you have some literature about it? 
2-	How do I perform a difference inversion?
3-	Can I have every resistivity ratio referenced to the first time step or baseline using tl.generateRatioPDF()?

Thanks

**Comment by halbmy** [comment]
1. `tl.invert()` inverts either a single timestep (if `t` is given as index or datetime), or all available timesteps subsequently doing a classical (step by step) timelapse inversion using the baseline (default) or the preceding (`creep=True`) timestep as reference (or no reference by using `isReference=False`).
2. A *difference inversion*  additionally after Yang & LaBrecque (2001) corrects for the misfit of the first timestep and can be useful if there is systematic effects in all data. Still need to implement this switch.
3. By default, the ratio is computed to the baseline (first time step) but can also be the preceding one with `creep=True`

**Comment by halbmy** [comment]
added some docstrings to clarify this

**Comment by verocordero** [comment]
Thank you for your responses. They were very helpful. I did the third question because in the generated ratio pdf that I am obtaining, the titles state that the division is over the preceding time step, even though I am not using creep=True. Additionally, if I perform the ratio using the following code I get a different result.

[DATA.zip](https://github.com/gimli-org/gimli/files/13962381/DATA.zip)

import pygimli as pg
from pygimli.physics import ert
from glob import glob
import matplotlib.pyplot as plt
from datetime import datetime

DATA = [ert.load(file) for file in glob('G:/Github/Maravilloso-PhD/DATA/Top*')]

tiemposs=['18/10/2023 11:07','18/10/2023 11:15','18/10/2023 13:20','18/10/2023 14:31'
                        ,'18/10/2023 14:53','18/10/2023 15:33','18/10/2023 15:53','18/10/2023 16:15'
                        ,'18/10/2023 16:40']

dates= [str(datetime.strptime(t, "%d/%m/%Y %H:%M")) for t in tiemposs]

tiempos= [datetime.fromisoformat(x) for x in dates]

for data in DATA:
    data['k'] = ert.createGeometricFactors(data, numerical=True)
    data['r'] = data['u'] / data['i']
    data['rhoa'] = data['k']*data['r']
    data['err']= ert.estimateError(data, relativeError=0.01) 
    print(data)

tl = ert.TimelapseERT(DATA, times=tiempos)
 
tl.fullInversion()
tl.generateDataPDF()  # pseudosections
tl.generateModelPDF() # inversions
tl.generateRatioPDF(cMax=1.1)

fig, zx = plt.subplots(3,3,figsize=(10,10) ) 
zx=zx.ravel()
arg= dict( cMap="bwr", cMin=0.9, cMax=1.1) 

for i in range(0,len(DATA)):
    zx[i],col=pg.show(tl.pd,tl.models[i]/tl.models[0], ax=zx[i], label='Res. ratio T%s/T0' %(i) ,pad=0.3, **arg)
    zx[i].text(10, 1, tiemposs[i]  ,fontsize = 8)

### Expected behavior
The resulting plot from the code has consistency with the salt tracer injection test and it looks as follows:
![image](https://github.com/gimli-org/gimli/assets/38502294/15f5ff14-b6dd-4679-87c7-08481bd90bd8)

### Actual behavior
The results shown in the generated PDF (attached) are significantly different.
[new-ratio.pdf](https://github.com/gimli-org/gimli/files/13962392/new-ratio.pdf)

### My environment:
--------------------------------------------------------------------------------
  Date: Wed Jan 17 11:15:00 2024 W. Europe Standard Time

                OS : Windows
            CPU(s) : 6
           Machine : AMD64
      Architecture : 64bit
               RAM : 23.8 GiB
       Environment : IPython

  Python 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:40:31) [MSC
  v.1929 64 bit (AMD64)]

           pygimli : 1.4.6
            pgcore : 1.4.0
             numpy : 1.21.6
        matplotlib : 3.7.1
             scipy : 1.11.2
           IPython : 8.17.2
           pyvista : 0.43.2
--------------------------------------------------------------------------------

Thank you

**Comment by halbmy** [comment]
You're absolutely right! This was a mistake (a wrong index) that I just fixed (2e5cf96).

Thank you for pointing this out.

**Comment by halbmy** [comment]
Closing as this simple fix works for your data 
![image](https://github.com/gimli-org/gimli/assets/7136401/b25d2c43-7197-4854-8188-fc38688c0a33)

Unless this is released in v1.4.7, you will have to use the git version: 
https://www.pygimli.org/installation.html#staying-up-to-date
