### ISSUE TITLE
support for g++ 7.x.x

### ISSUE THREAD

**Issue by frodo4fingers** [gimli-org/gimli#64]
hi

i tried to compile gimli again and it seems that arch linux latest compiler version is the problem. could you fix that? it would be great to work with gimli again.

cheers :-)

**Comment by florian-wagner** [comment]
Hi @frodo4fingers,

it is very likely, that castxml is not yet compatible with the newest gcc version. We have fixed "working versions" for the thirdParty dependencies and this working version probably points to a caster version where gcc7 was not on the table yet. I have Arch linux on my private Laptop and will try to compile with the newest versions again. 

As a hot fix, you could install an older gcc in parallel from the arch repo or compile pygimli within a conda environment: 

``` bash
#------------------------------------------------------
# Build pyGIMLi using Anaconda and pre-compiled castxml
#------------------------------------------------------

NO_OF_CPUS=2 # Speed up compilation

# Assumes that minconda is installed at ~/miniconda3
CONDA_PATH="~/miniconda3"
export PATH=$CONDA_PATH/bin:$PATH

mkdir -p gimli_bert_conda
cd gimli_bert_conda
conda install -y system gcc libgcc cmake python boost openblas numpy "pyqt<=4.11.4" matplotlib pytest

# Remove old versions to avoid conflict
conda uninstall -y pygimli

# Install castxml from binary to avoid any clang/llvm related issues
wget https://midas3.kitware.com/midas/download/item/318227/castxml-linux.tar.gz
tar -xzf castxml-linux.tar.gz
export CASTXML=`pwd`/castxml/bin/castxml
CMAKE_FLAGS="-DCASTER_EXECUTABLE=$CASTXML"

# Install pygimli
mkdir -p gimli
cd gimli
git clone https://github.com/gimli-org/gimli
mkdir -p build
cd build
cmake $CMAKE_FLAGS ../gimli
make -j $NO_OF_CPUS gimli
make pygimli J=$NO_OF_CPUS
cd ../..

# Test installation
export PYTHONPATH=`pwd`/gimli/gimli/python:$PYTHONPATH
python -c "import pygimli; pygimli.test(show=False)"

# Don't forget to set paths permanently in your ~/.bashrc.
```

**Comment by carsten-forty2** [comment]
The problem seems to be a missing header in kdtree++, which fails to compile the core library.
Currently, I only have a log file but not jet any access  to a gcc-v7. 
So it still needs a little time until my distro provide my this compiler.

**Comment by frodo4fingers** [comment]
Hi @florian-wagner 
I tried both solutions you provided but they failed. The parallel installation of an available gcc6 encountered an "unknown error" and put an early end to that approach. The conda script unfortunately also stops.. at cmake:
```bash
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in /home/frodo/github/miniconda3/share/cmake-3.8
CMake Error: Error executing cmake::LoadCache(). Aborting.
```
I think let it rest a few days more until gcc7 comes up in @carsten-forty2 's distro :smile: 

thank you very much for your help!

**Comment by carsten-forty2** [comment]
strange error.

Do you have cmake installed correctly?
Did you checked with an empty build dir?
