### ISSUE TITLE
About Complex-valued electrical modelling 

### ISSUE THREAD

**Issue by CUMT-txz** [gimli-org/gimli#640]
### Problem description

I am using pyGIMLI to do complex valued resistivity modeling and encountered the following error：
Traceback (most recent call last):

  Cell In[20], line 1
    data = ert.simulate(

  File ~\anaconda3\envs\pg\lib\site-packages\pygimli\physics\ert\ert.py:157 in simulate
    scheme.set('k', fop.calcGeometricFactor(scheme))

RuntimeError: ./core/src/bert/dcfemmodelling.cpp:84		GIMLI::CVector GIMLI::getComplexResistivities(const Mesh&)  complex resistivity values expected but non found

### Your environment

Please provide the output of `print(pygimli.Report())` here. If that does not
work, please give provide some additional information on your:

**Operating system**: Windows
**Python version**: 3.9.18
**pyGIMLi version**: 1.4.0
**Way of installation**: e.g. Conda package-spyder

### Steps to reproduce
```
import matplotlib.pyplot as plt
import numpy as np

import pygimli as pg
import pygimli.meshtools as mt
from pygimli.physics import ert

pg.utils.units.quants['vel']['cMap'] = 'inferno_r'
###############################################################################

scheme = ert.createData(elecs=pg.utils.grange(start=0, end=7, dx=1.0),
                        schemeName='dd')
# change the electrodes position
pos = np.array(scheme.sensorPositions())  # get xyz coor for electrodes
# borehole 1
pos[0:4, 0] = 0.001
for i in range(1, 5, 1):
    pos[i-1, 1] = -0.02*i
# borehole 2
pos[4:8, 0] = 0.049
for i in range(1, 5, 1):
    pos[i+3, 1] = -0.02*i

scheme.setSensorPositions(pos)  # reset the position for electrodes

pos_xy = pos[:, 0:2]
read_scheme = np.loadtxt('schemedata.dat')  # created by AGI software
scheme.resize(read_scheme.shape[0])
for i, tok in enumerate(['a', 'b', 'm', 'n']):
    scheme.set(tok, read_scheme[:, i]-1)

scheme.set('valid', pg.Vector(scheme.size(), 1))

# create the mesh for forward

bh_spacing = 0.05
bh_length = 0.1
world = mt.createRectangle(start=[0, -(bh_length)], end=[bh_spacing, 0.0],
                           marker=0)
c0 = mt.createCircle(pos=(0.02,-0.02), radius=0.015, nSegments=25, marker=1)
c1 = mt.createCircle(pos=(0.02,-0.06), radius=0.015, nSegments=25, marker=2)

geom = mt.mergePLC([world, c0, c1])

for sen in pos_xy:
    geom.createNode(sen)  # create new node for electrodes
    
pg.show(geom)
pg.show(geom, marker=True)


mesh = mt.createMesh(geom,quality=34,smooth=[1,10])
pg.show(mesh)


rhomap = [
    [0, pg.utils.complex.toComplex(100, -20 / 1000)],
    [1, pg.utils.complex.toComplex(100, 0 / 1000)],
    # Magnitude: 100 ohm m, Phase: -50 mrad
    [2, pg.utils.complex.toComplex(100, -50 / 1000)],
]

rho = pg.solver.parseArgToArray(rhomap, mesh.cellCount(), mesh)
fig, axes = plt.subplots(2, 2, figsize=(16 / 2.54, 16 / 2.54))
pg.show(mesh, data=np.real(rho), ax=axes[0, 0], label=r"$\rho'$~[$\Omega$m]")
pg.show(mesh, data=np.imag(rho), ax=axes[0, 1], label=r"$\rho''$~[$\Omega$m]")
pg.show(mesh, data=np.abs(rho), ax=axes[1, 0], label=r"$|\rho$|~[$\Omega$m]")
pg.show(
    mesh, data=np.arctan2(np.imag(rho), np.real(rho))*1000,
    ax=axes[1, 1], label=r"$\phi$ [mrad]"
)
fig.tight_layout()
fig.show()


data = ert.simulate(
    mesh,
    res=rhomap,
    scheme=scheme,
    # noiseAbs=0.0,
    # noiseLevel=0.0,
)

rho_a_complex = data['rhoa'].array() * np.exp(1j * data['phia'].array())


fig, axes = plt.subplots(2, 2, figsize=(16 / 2.54, 16 / 2.54))
ert.showERTData(data, vals=data['rhoa'], ax=axes[0, 0])


ert.showERTData(
    data, vals=data['phia'] * 1000, label=r'$\phi$ [mrad]', ax=axes[0, 1])

ert.showERTData(
    data, vals=np.real(rho_a_complex), ax=axes[1, 0],
    label=r"$\rho_a'$~[$\Omega$m]"
)
ert.showERTData(
    data, vals=np.imag(rho_a_complex), ax=axes[1, 1],
    label=r"$\rho_a''$~[$\Omega$m]"
)
fig.tight_layout()
fig.show()
```
########################
schemedata.dat
1	4	2	3
1	4	5	6
1	4	6	7
1	4	7	8
5	8	6	7
5	8	1	2
5	8	2	3
5	8	3	4

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
I guess you're trying to simulate a crosshole case? Your geometry looks like
![image](https://github.com/gimli-org/gimli/assets/7136401/943aae4f-7344-4e75-a105-9918fd76a5b2)

However, as you use `createRectangle` this is a Neumann body (noflow at all boundaries) for which the solution is undefined and requires additional conditions. Better use `createWorld` instead and much larger space around the electrodes, I used 
```
world = mt.createWorld(start=[-0.4, -(bh_length)-0.4], end=[bh_spacing+0.4, 0.0], marker=0)
``` 
and also added
```
scheme['k'] = ert.geometricFactors(scheme)
```
to have correct geometric factors (the ones created by createData are wrong).
Furthermore I recommend using `ert.showData8..., style='A-M')` and the current version v1.4.6.
![image](https://github.com/gimli-org/gimli/assets/7136401/14339315-353e-4469-9d31-e4720f373c13)

**Comment by CUMT-txz** [comment]
Thank you for your response. I will continue my research and if I have any difficulties, I hope to receive your assistance.
