### ISSUE TITLE
error while testing pygimli in WINDOWS system

### ISSUE THREAD

**Issue by makeabhishek** [gimli-org/gimli#644]
### Problem description
I installed Pygimli in windows machine. However when testing, 1 failed operation.

### Your environment

Please provide the output of `print(pygimli.Report())` here. If that does not
work, please give provide some additional information on your:

**Operating system**: e.g. Windows
**Python version**: e.g. 3.9.18
**pyGIMLi version**: 1.4.6
**Way of installation**: conda create -n pg -c gimli -c conda-forge pygimli=1.4.6

### Steps to reproduce

`python -c "import pygimli; pygimli.test(show=False, onlydoctests=True)"`

### Expected behavior

Test should be passed

### Actual behavior
```
```
.43s call     .conda/envs/pg2/Lib/site-packages/pygimli/core/mesh.py::pygimli.core.mesh.__Mesh_cutBoundary__
0.94s call     .conda/envs/pg2/Lib/site-packages/pygimli/viewer/showmesh.py::pygimli.viewer.showmesh.showMesh
=============================================== short test summary info ===============================================
FAILED .conda/envs/pg2/Lib/site-packages/pygimli/meshtools/grid.py::pygimli.meshtools.grid.appendTetrahedronBoundary
============================================ 1 failed, 94 passed in 23.25s ============================================
25/01/24 - 15:16:20 - pyGIMLi - DEBUG - bar debug should be on (1)
25/01/24 - 15:16:20 - pyGIMLi - DEBUG - bar debug should be on (2)
25/01/24 - 15:16:20 - pyGIMLi - VERBOSE - bar verbose should be on (1)
25/01/24 - 15:16:20 - pyGIMLi - VERBOSE - bar verbose should be on (2)
25/01/24 - 15:16:21 - pyGIMLi - WARNING - No data error given, set Fallback set to 1%
25/01/24 - 15:16:21 - pyGIMLi - INFO - Created startmodel from region infos: 2 [1.0, 1.0]
25/01/24 - 15:16:29 - pyGIMLi - INFO - Complex resistivity values found.
25/01/24 - 15:16:35 - pyGIMLi - INFO - Found 1 regions.
25/01/24 - 15:16:35 - pyGIMLi - INFO - Creating forward mesh from region infos.
25/01/24 - 15:16:35 - pyGIMLi - INFO - Creating refined mesh (secnodes: 10) to solve forward task.
25/01/24 - 15:16:36 - pyGIMLi - INFO - Created startmodel from forward operator: 7, min/max=0.500000/42.677304
25/01/24 - 15:16:36 - pyGIMLi - WARNING - Multiprocess Jacobian currently unavailable for Win32 and Mac.
25/01/24 - 15:16:36 - pyGIMLi - WARNING - Multiprocess Jacobian currently unavailable for Win32 and Mac.
25/01/24 - 15:16:36 - pyGIMLi - WARNING - Multiprocess Jacobian currently unavailable for Win32 and Mac.
25/01/24 - 15:16:36 - pyGIMLi - WARNING - Multiprocess Jacobian currently unavailable for Win32 and Mac.
25/01/24 - 15:16:36 - pyGIMLi - WARNING - Multiprocess Jacobian currently unavailable for Win32 and Mac.
25/01/24 - 15:16:36 - pyGIMLi - WARNING - Multiprocess Jacobian currently unavailable for Win32 and Mac.

```

**Comment by florian-wagner** [comment]
Dear @makeabhishek,

it seems that the `tetgen` dependency is missing. We removed it, because it caused problems on Mac M chips. We will make this platform-depdent with pyGIMLi 1.4.7.

Can you try if `conda install -c conda-forge tetgen` fixes your problem?

Thanks and best regards
Florian

**Comment by makeabhishek** [comment]
Thanks @florian-wagner, that works perfectly. All test pass.
By the way I also found that sometime `conda `stuck and does not process, so alternatively it its recommended to use `mamba`. However, I tried following  steps and `conda `can install `pygimli` easily.

```
conda config --remove channels conda-forge
conda config --add channels conda-forge
conda config --set channel_priority strict
```
Thanks
