### ISSUE TITLE
HDF format support

### ISSUE THREAD

**Issue by halbmy** [gimli-org/gimli#65]
HDF seems to be a standard data format that is efficient for storing things like meshes, data containers and so on. Particularly, it can ease the communication between pygimli, tetgen and fenics (which we actually use in LIAG for B-field computations). Therefore loading/saving at least the meshes would be beneficial.

**Comment by carsten-forty2** [comment]
Native hdf-support for core datatypes only make sense if we want to switch the whole IO to hdf but I don't see strong benefits in comparison to to current ascii read/write.
As I understand hdf, its a huge long grown binary container system for all kind of named data.
For the core library we would need a new third party package with all the usual drawbacks. 

Anyhow,  we can for sure use some py-hdf packages to write some optional import export filters for stuff we need to exchange with other packages, if there are clear documentations about hdf specs of fenics or tetgen(??)

**Comment by NicoSkibbe** [comment]
Added new functionality readHDF5Mesh() and convertHDF5Mesh() as well as exportHDF5Mesh() to handle hdf5 datastorages containing 3D tetrahedra meshes (suitable for Fenics syntax). The convertDolfinMesh and exportDolfinXML can handle 2D xml-format Meshes.

There are no drawbacks from the dependancy of the new functions (h5py package), as the working with .h5 meshes already requires these packages.

Concerning the hdf specs of Fenics and their documentation: I have'nt found a real documentation besides some post in the official fenics Forum, but the file itself is very simple and i added a documentation in the docstrings of the new functions.

**Comment by halbmy** [comment]
very nice!
