### ISSUE TITLE
Inversion manager ignoring set background.

### ISSUE THREAD

**Issue by soehag** [gimli-org/gimli#651]
### Problem description

Hello everyone!
I have been trying to run some "simple" ERT inversions with a specific region of interest. To only invert for the specific region, I created a mesh (region of interest) with a triangle boundary around it with associated region markers. When using the ERTmanager and setting the regularisation via manager.inv.setRegularization, the set backgrounds etc. get ignored.

### Your environment

--------------------------------------------------------------------------------
  Date: Fri Feb 16 14:43:27 2024 CET

                OS : Linux
            CPU(s) : 64
           Machine : x86_64
      Architecture : 64bit
               RAM : 251.5 GiB
       Environment : Jupyter
       File system : ext4

  Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37)
  [GCC 12.3.0]

           pygimli : 1.4.4
            pgcore : 1.4.0
             numpy : 1.24.4
        matplotlib : 3.7.2
             scipy : 1.11.3
           IPython : 8.17.2
           pyvista : 0.42.3
--------------------------------------------------------------------------------

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python

import pygimli as pg
import pygimli.meshtools as mt
import numpy as np
import pygimli.physics.ert as ert

## create meshes
mesh_inner_plc = pg.meshtools.createWorld(np.array([10,4]), np.array((20, -4)), worldMarker=True, marker=1)
mesh_inner_plc.setBoundaryMarkers([-2]*4)
mesh_inner = pg.meshtools.createMesh(mesh_inner_plc, quality=32, area=.1, smooth=True)
final_mesh = pg.meshtools.appendTriangleBoundary(mesh_inner, xbound=10, ybound = 2 , quality=32, 
                                                    area=1, isSubSurface=False, smooth=True, addNodes=50, 
                                                    marker = 2)
pg.show(final_mesh, markers=True, showMesh=True)

## create sensors and data
sensorPositions_x = np.linspace(5,15,11)
sensorPositions_top = np.vstack((sensorPositions_x, np.ones_like(sensorPositions_x)*4)).T
sensorPositions_bot = np.vstack((sensorPositions_x, np.ones_like(sensorPositions_x)*(-4))).T

scheme = pg.DataContainerERT()
for pos in sensorPositions_top:
    scheme.createSensor(pos)
for pos in sensorPositions_bot:
    scheme.createSensor(pos)

for sen_top in range(len(sensorPositions_top)):
    for sen_bot in range(len(sensorPositions_top),len(sensorPositions_top)+len(sensorPositions_bot)):
        scheme.addFourPointData(sen_top,-1,sen_bot,-1)
scheme["k"] +=1

res = np.array([h.center().y() for h in final_mesh.cells()])**2+100
pg.show(final_mesh, res)

syn_data = ert.simulate(mesh=final_mesh, scheme=scheme, res=res, noiseLevel=1)
pg.show(final_mesh, markers=True, showMesh=True)

## Invert with background set to marker and additional regularisation constraints

manager = ert.Manager()
manager.setData(np.random.random)
manager.setMesh(final_mesh)

manager.inv.setRegularization(2, background=True)
manager.inv.setRegularization(1, cType=1)

result = manager.invert(
    data=syn_data,
    mesh=final_mesh,
    lam =1e4
)
pg.show(manager.paraDomain, result)
pg.show(final_mesh, res)
```

### Expected behavior

The background should be with marker 2, i.e. the inner box.
### Actual behavior

The background is overwritten by the manager to the lowest marker value.

In addition it would be a nice feature, to have flexibility with the startModel input (e.g. startModel can be define on the full grid even if parts is omitted as background, fixed to a certain value, or treated as homogenous) and model output (retrieve the model on the full mesh, even if background is omitted during inversion). Cheers and thank you!

**Comment by halbmy** [comment]
By default, region 1 (the lowest in case of multiple regions) is set to background, so you will have to deactivate this explicitly:
```
manager.inv.setRegularization(1, cType=1, background=False)
```

**Comment by soehag** [comment]
Hi @halbmy,
thanky you for your answer - that perfectly explains the behaviour.

However I still think, that the intuitive behaviour is to not assign an additional background region, if there is a background region already set in the manager. Especially, if a specific regularisation is set for the region with the lowest marker, overwriting the background property is unintuitive in my opinion.

I have a further question, regarding the background marker. In my understanding, setting background=True should completely remove the cells with the specific marker from the inversion, i.e. that paraDomain. But manually setting background=True doesnt seem to achieve that besides for the marker with the lowest number.

Cheers and have a nice weekend,
Hagen

**Comment by halbmy** [comment]
I agree that this default behaviour is not very intuitive, it just matches the default mesh generation done by the method managers. So we have to place it into other abstraction levels and have to better document this behaviour. 

To your question: setting `background=True` for a specific region excludes it from inversion. In your case, the problem was passing the mesh after setting it
```
manager.setMesh(final_mesh)
manager.inv.setRegularization(2, background=True)
manager.inv.setRegularization(1, cType=1, background=False)
result = manager.invert(data=syn_data, mesh=final_mesh, lam=1e4)
manager.showResult()
```
which will override the regularization set before. If you remove the `mesh` argument from `invert()` all will be well. Except that the inversion fails, but this is due to a wrong geometry since your electrodes are outside of the inversion domain.
![image](https://github.com/gimli-org/gimli/assets/7136401/3223055a-c4f2-4479-8694-577e4d0a1346)

**Comment by soehag** [comment]
Hi,

thank you for your answer! That makes sense - starting the inversion with an adjusted geometry (such that the electrodes are well into the domain) and not passing the mesh to manager.inv() still throws a message, that the region with marker 1 is set to the background. I assume, that this is a "ghost" message?

To add onto the documentation - it would also be great to add at this place, how proper (non homogeneous) starting models can be supplied, when the flag "single=True" is set.

Cheers and thank you
Hagen

**Comment by subenyu** [comment]
> Hi,
> 
> thank you for your answer! That makes sense - starting the inversion with an adjusted geometry (such that the electrodes are well into the domain) and not passing the mesh to manager.inv() still throws a message, that the region with marker 1 is set to the background. I assume, that this is a "ghost" message?
> 
> To add onto the documentation - it would also be great to add at this place, how proper (non homogeneous) starting models can be supplied, when the flag "single=True" is set.
> 
> Cheers and thank you Hagen

Did you get the answer about "how proper (non homogeneous) starting models can be supplied, when the flag "single=True" is set."?
Thank you very much!

**Comment by halbmy** [comment]
If a region is set to single, it represented by only one value that is considered constant (this is what single means: a single parameter for a whole region) as explained in the tutorial
https://www.pygimli.org/_tutorials_auto/3_inversion/plot_8-regionWise.html
So the single region is homogeneous by nature. If you want other (non-single) regions to have a non-homogeneous starting models in presence of a single region, you have to paste all starting models for the individual regions with increasing region number. There is no example for it as it is an edge case. We might add a sentence in the above mentioned tutorial about how the model vector is built.

**Comment by subenyu** [comment]
> If a region is set to single, it represented by only one value that is considered constant (this is what single means: a single parameter for a whole region) as explained in the tutorial https://www.pygimli.org/_tutorials_auto/3_inversion/plot_8-regionWise.html So the single region is homogeneous by nature. If you want other (non-single) regions to have a non-homogeneous starting models in presence of a single region, you have to paste all starting models for the individual regions with increasing region number. There is no example for it as it is an edge case. We might add a sentence in the above mentioned tutorial about how the model vector is built.
Thank you very much, and I try the case as following, but it is ArgumentError. The code:

import matplotlib.pyplot as plt
import pygimli as pg 
import numpy as np
import pygimli.meshtools as mt
from pygimli.physics import ert

top_layer =mt.createWorld(start=[-10, -10, -40], end=[140, 10, 0],marker=1)
middle_layer =mt.createCube(start=[-10,-10,-60],end=[140,10,-40],marker=2)
cube =mt.createCube(start=[40,-5,-10],end=[80,5,-30],marker=3)

start_model= mt.merge([top_layer, middle_layer, cube])

n_sensor = 40
sensor = np.zeros((n_sensor, 3))
sensor[0:, 0] =np.linspace(10,-10, n_sensor)
sensor[0:,2]=-20
print(sensor)
for pos in sensor:
    start_model.createNode(pos)
    start_model.createNode(pos - [0.1,0.1,0.1])

mesh_forward = mt.createMesh(start_model,area=5) 
rhomap=[[1, 300],[2, 100],[3, 10]]

scheme = ert.createData(sensor,schemeName='dd')

data = ert.simulate(mesh_forward, scheme=scheme, res=rhomap, noiseLevel=1,
                    noiseAbs=1e-6, seed=1337
                   )

mgr = ert.ERTManager(data)
mgr.setMesh(mesh_forward)
mgr.inv.setRegularization(3,startModel=10,limits=[10,20])
mgr.inv.setRegularization(2,background=True)
mgr.invert(mesh_forward)（1,background=False）

**Comment by halbmy** [comment]
Can you please paste your error message?

Make sure the error also appears with the recent version of pyGIMLi (v1.5.2).

**Comment by subenyu** [comment]
The same question for me and error message as shown:
ArgumentError                             Traceback (most recent call last)
Cell In[3], line 35
     33 mgr.inv.setRegularization(3,startModel=10,limits=[10,20])
     34 mgr.inv.setRegularization(2,background=True)
---> 35 mgr.invert(mesh_forward)(1,background=False)

File ~\anaconda3\envs\pg\Lib\site-packages\pygimli\frameworks\methodManager.py:822, in MeshMethodManager.invert(self, data, mesh, startModel, **kwargs)
    819 # remove unused keyword argument .. need better kwargfs
    820 self.fop._refineP2 = kwargs.pop('refineP2', False)
--> 822 dataVals = self._ensureData(self.fop.data)
    823 errorVals = self._ensureError(self.fop.data, dataVals)
    825 if self.fop.mesh() is None:

File ~\anaconda3\envs\pg\Lib\site-packages\pygimli\frameworks\methodManager.py:349, in MethodManager._ensureData(self, data)
    346 if vals is None:
    347     pg.critical("There are no data values.")
--> 349 if abs(min(vals)) < 1e-12:
    350     print(min(vals), max(vals))
    351     pg.critical("There are data values equals 0.0")

File ~\anaconda3\envs\pg\Lib\site-packages\pygimli\core\mesh.py:138, in __Mesh_getVal(self, key)
    136 def __Mesh_getVal(self, key):
    137     """Index access to the mesh data"""
--> 138     if self.haveData(key):
    139         return self.data(key)
    140     else:

ArgumentError: Python argument types in
    Mesh.haveData(Mesh, int)
did not match C++ signature:
    haveData(GIMLI::Mesh {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > name)

**Comment by halbmy** [comment]
In the last line
```
mgr.invert(mesh_forward)（1,background=False）
``` 
there is something wrong, you should first state
```
mgr.inv.setRegularization(1,background=False）
```
before calling the inverison. The point is, however, that the first argument of invert is data, so you will have to pass the mesh with the keyword argument `mesh=mesh_forward`. In your case, you don't have to pass it around because you called
```
mgr.setMesh(mesh_forward)
```
so you can just call `mgr.invert()`.
