### ISSUE TITLE
Pass the sgt file

### ISSUE THREAD

**Issue by ZHR0623** [gimli-org/gimli#657]
When I have the forward file and want to invert it, do I have to place the file in a specific location and pass it using the data = pg.getExampleData() function? I don't really want to do that, can there be another way?

**Comment by ZHR0623** [comment]
For example, some methods that use relative paths

**Comment by halbmy** [comment]
The function `pg.getExampleData()` is exclusively for loading data from the repository https://github.com/gimli-org/example-data so that the examples can be run by everyone.

For loading data on your local filesystem, you can use `pg.load(filename)` or in your case `tt.load()`, where `from pygimli.physics import traveltime as tt`, the filename can be global or relative to the path where you run the script or notebook.

**Comment by ZHR0623** [comment]
![反演结果200-2000](https://github.com/gimli-org/gimli/assets/102281587/ba1c68a0-bd99-4d9e-85d8-fe59388037d1)
![模型250-700-1500-2000](https://github.com/gimli-org/gimli/assets/102281587/2ad01210-48aa-45a5-b7cf-4a8667aec97a)
Here's my model and the inversion results. Obviously, the height is too big in the output, how can I change it?
ax, _ = mgr.showResult(cMin=200, cMax=2000, logScale=False)

**Comment by ZHR0623** [comment]
![image](https://github.com/gimli-org/gimli/assets/102281587/f834b757-bb2c-4fc2-be68-6a7432ba7b9a)
Thank you for your reply to my question, it really solved the problem!
This is the result of my rays, in fact, there are too many rays because it shows them all. Is there a function that enables to show only the rays of a certain excitation point or points, not all of them?

**Comment by halbmy** [comment]
It is a good idea to pass a list of source positions to `showRayPaths` in the future. Right now, you can retrieve the ray paths by
```
raypaths = mgr.getRayPaths() 
```
and then pass these to `drawRayPaths`, e.g. `mgr.drawRayPaths(ax, rayPaths=raypaths[5:7])`
```
See https://www.pygimli.org/pygimliapi/_generated/pygimli.physics.traveltime.html#pygimli.physics.traveltime.TravelTimeManager.drawRayPaths

**Comment by ZHR0623** [comment]
Ok, I have solved the problem, thank you!
When setting up the shotpoints and geophones, I noticed that there's only one sensors pass parameter here, instead of the g and s parameters, using
sensors = np.linspace(0.,LineLengthMax, numberGeophones); 
scheme = pg.physics.traveltime.createRAData(sensors);
data = tt.simulate(slowness=1.0 / vp, scheme=scheme, mesh=mesh); 
The created data has the shotpoints in the same position as the  geophones. But I want to describe them separately so that they are in different positions, e.g. low number of shotpoints and high number of geophones, how should I do it?  I have also seen the example plot_03_rays_layered_and_gradient_models that you gave, and unfortunately I can't use the orthographic method (analyticalSolution) in this example, I need to use the method tt.simulate(scheme) that you gave in your library. Please help me when you have time, thanks!

Translated with DeepL.com (free version)

**Comment by halbmy** [comment]
In the pyGIMLi data container, there is only one list of sensors that can, however, flexibly used as shotpoints, geophones or both.

Please have a look at the documentation
https://www.pygimli.org/pygimliapi/_generated/pygimli.physics.traveltime.html#pygimli.physics.traveltime.createRAData

The keyword `shotDistance` defines which sensors (by default every, but if using 5 only every fifth) are used as shotpoints. If you want to be more flexible, you are free to define the `s` and `g` fields.

I would like to close this issue as the original problem is solved and the discussion proceeded. Feel free to open a new issue or discussion with a changed title.
