### ISSUE TITLE
Calculated  Apparent Resistivity

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#660]
Excuse Me Sir,

is there any command or function which can export the calculated apparent resistivity in pygimli? I want to make a statistical comparison about Observed Apparent Resistivity and Calculated Apparent resistivity? Thank You

**Comment by halbmy** [comment]
Please have a look at https://dev.pygimli.org/_tutorials_auto/3_inversion/plot_1-polyfit.html
where several measures are computed by using `inv.response`. If you use the ERT manager, `inv=mgr.inv`, and the data vector is `data['rhoa']`.

**Comment by halbmy** [comment]
The result of `mgr.invert()` is the model vector. As written above, you should use `inv=mgr.inv` to retrieve the inversion class instance and then you can get the model response:
```
model = mgr.invert(...)
misfit = data['rhoa'] - inv.response
```

**Comment by tonapawilliam** [comment]
Thank You Sir
