### ISSUE TITLE
Reference Of Parameter in Forward and Inverse modelling

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#663]
Excuse Sir,

I would like to know the basis of some parameters that I often use in my forward and inversion models. I have been using pygimli by guessing what parameter numbers I need to enter, which makes me probably lack in basic issues. Do you have any reference on each parameter such as: quality, area, zWeight, lam, paraMaxCellSize, paraDepth? 
Especially on Quality why it can't be used when at 40, and why zWeight if it gets smaller then the inversion model to the bottom tends to decrease.
I would be very grateful if you have a link to some research that I can access regarding these parameters. thank you.

**Comment by tonapawilliam** [comment]
Thank you sir, I wish you all the best for the development of pygimli, especially in the explanation of parameters and examples.

**Comment by halbmy** [comment]
I am closing this. The main issue, a more didactic and uncluttered overview on options is part of our upcoming Examples & Tutorial redesign.
