### ISSUE TITLE
Visualizing raw ERT data with gradient protocol

### ISSUE THREAD

**Issue by IsabellaLorenzen** [gimli-org/gimli#664]
### Problem description

I wish to plot the raw data from my ERT survey so i can visualize how many datapoints is removed during filtering. 

In the picture below is the result of the plot and i wonder if it is correctly plotted as there appear some gaps along the sides of the plot and some structured layering, but perhaps this is normal to the type of data? 
The data is from an ERT survey conducted with the gradient protocol. 

<img width="273" alt="Screenshot 2024-03-04 131256" src="https://github.com/gimli-org/gimli/assets/162128671/ac6fb2ad-2117-403a-95db-2cea718c4a1b">

I furthermore receive the following information "pyGIMLi - INFO - could not read unified data format for ERT ... try res2dinv", but i am able to plot the data. Does this information output affect the plotted data?

### Your environment

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 7.8 GiB
       Environment : IPython

  Python 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:29:04) [MSC
  v.1929 64 bit (AMD64)]

           pygimli : 1.4.6
            pgcore : 1.4.0
             numpy : 1.26.4
        matplotlib : 3.7.2
             scipy : 1.11.2
           IPython : 8.15.0

### Steps to reproduce
```
data=pg.physics.ert.load("/Users/Isabe/Desktop/Filtrering af ERT data/0_Gradient XL_2 - No Filter.dat")

data.remove(data['r'] < 0)
data.remove(data['r'] > 50)

ResPlot=pg.physics.ert.showData(data,"r",label="Resistance (Ohm)",ylabel="Depth level")
```

### Expected behavior

Perhaps a profile similar to this:
<img width="317" alt="image" src="https://github.com/gimli-org/gimli/assets/162128671/6aa37e90-c9c0-4ada-8b1f-46ffae956090">

### Actual behavior

<img width="273" alt="Screenshot 2024-03-04 131256" src="https://github.com/gimli-org/gimli/assets/162128671/800261f0-ff61-4f08-bd3a-24dea31df1ae">

```
Paste your script output here.

"pyGIMLi - INFO - could not read unified data format for ERT ... try res2dinv"

```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
The image is totally fine. Please note that a pseudosection is just a coloured table of measurements, typically with increasing spacing on the y axis and some "midpoint" on the x axis (for gradient the midpoint between M and N, for dipole-dipole the midpoint between the dipoles). 

For a dipole-dipole array with fixed AB=MN=a, the y axis is the n factor where n*a is the distance between the dipoles (see DD image). If you increase the dipole lengths, several sections will be created. For the multiple-gradient (kind of skewed Schlumberger, therefore denoted as SL) array, one has the dipole length (1, 2, 4, 6) at the beginning and the skew factor s denoting the distance from A or B.

**Comment by IsabellaLorenzen** [comment]
Thank, very helpful!

**Comment by IsabellaLorenzen** [comment]
Thank, very helpful!
