### ISSUE TITLE
Costumizing the pseudosection figure

### ISSUE THREAD

**Issue by IsabellaLorenzen** [gimli-org/gimli#666]
### Problem description
Hallo!

I have a couple of questions regarding costumizing the pseudosection. 
I would love to find out how to:
1) Make a title for the figue located above the figure
2) Remove the tick lables on the y axis
<img width="321" alt="image" src="https://github.com/gimli-org/gimli/assets/162128671/7e69a88c-92c7-4854-adb3-95b8d580e4de">

### Steps to reproduce

This is what i've got so far:
```
pg.physics.ert.showData(data,"r",label="Resistance (Ohm)",ylabel="Depth level",orientation="vertical",set_title="x",ax=ax)
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
Output of any (2d) show command are
1. a matplotlib axes
2. a colorbar handle
With these you can customize your figure using matplotlib commands, see https://matplotlib.org/, e.g.
```
ax.set_xlabel("profile distance (m)")
ax.set_title("This is my title")
ax.set_aspect(2.0)
cb.set_label("blabla")
...
```
