### ISSUE TITLE
Res2d formate conversion

### ISSUE THREAD

**Issue by Abby123455r** [gimli-org/gimli#670]
### Problem description

I performad farward modeling in pygimli and save the data in .dat file..now i want to import this data in res2d inv software. could you please tell me how i can convert the file into res2dinv formate.

Second i want to ask that in apparent resistivity section we have DD1, DD6. DD11 at depth scale..could you please tell me that why we have disply this instead of depth?

**Comment by halbmy** [comment]
In the `pyBERT` package (see infos on
https://gitlab.com/resistivity-net/bert
), there is a function `exportRes2dInv`:
```
from pybert.importer.exportData import exportRes2dInv
exportRes2dInv(data, "filename.dat")
```
However, I haven't used it for ages. Please, check it out and tell us whether it is working.

**Comment by Abby123455r** [comment]
it is working ..thank you
