### ISSUE TITLE
Filter data points before visualizing the pseudosection

### ISSUE THREAD

**Issue by IsabellaLorenzen** [gimli-org/gimli#676]
### Problem description

Hallo! I wish to visualize my ert data after my filtering steps. When i load my data i have these keys: Data: Sensors: 181 data: 4768, nonzero entries: ['DPID', 'a', 'b', 'ip', 'ip1', 'ip2', 'm', 'n', 'r', 'valid']

I have assigned the DPID according the the coordinates. 

I have a list of DPID of which data points i wish not to show in showData. How do i filter the data points out in the keys so i can visualize the data points which will be filtered before inversion?

### Your environment

OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 7.8 GiB
       Environment : IPython

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
You mean something like this?
```
data.remove(data['DPID'==11]) # or <, <=, >, >=
```

**Comment by IsabellaLorenzen** [comment]
Yes, perfect! Thank you!
