### ISSUE TITLE
Exporting ERT data to RES2DINV format

### ISSUE THREAD

**Issue by IsabellaLorenzen** [gimli-org/gimli#677]
### Problem description
Hallo!

I have just filtered my data and i have used PyGIMLi to visualize the filtered data points.

I have a DataContainer defined where the data has been filtered and I wish to export this data into a Res2DINV file, is there a way to do that?

### Your environment
OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 7.8 GiB
       Environment : IPython

```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
See also last weeks issue https://github.com/gimli-org/gimli/issues/670
using the pyBERT module
```
from pybert.importer.exportData import exportRes2dInv
exportRes2dInv(data, "filename.dat")
```

**Comment by halbmy** [comment]
Closing the issue as being a (solved) duplicate. Reopen in case of problems.
