### ISSUE TITLE
Reference of zWeight 

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#689]
Do you have any literature on zWeight, especially the use of formulas like the one you described for lambda parameter regulation? I have searched several references but I have not found what is the basic formula used to analyze zWeight. Thank you.

**Comment by halbmy** [comment]
The only reference is Coscia et al. (2011) in equation (2):
![image](https://github.com/gimli-org/gimli/assets/7136401/de86eaaf-36f3-4338-bb07-076c64ff8d4f)

Coscia, I., Greenhalgh, S., Linde, N., Doetsch, J. A., Marescot, L., Günther, T., Vogt, T. & Green, A. (2011): 3D crosshole ERT for aquifer characterization and monitoring of infiltrating river water. Geophysics 76(2), G49-G59, doi:10.1190/1.3553003.

**Comment by tonapawilliam** [comment]
Thank You Sir

**Comment by makeabhishek** [comment]
May I ask, which reference you followed for lambda regularization?

**Comment by halbmy** [comment]
Regularization is explained in more detail in the tutorial https://www.pygimli.org/_tutorials_auto/3_inversion/plot_5_Regularization.html

**Comment by makeabhishek** [comment]
Thanks, yes I followed that. Is there any research article specifically explaining the regularization mentioned in the tutorial. Especially the smoothness constraint matrices considered for unstructured mesh.

**Comment by makeabhishek** [comment]
What is the best approach to choose zWeight in inversion?

**Comment by halbmy** [comment]
There is no formal approach. The value expresses the expectation to the subsurface, on how much the resistivity varies in the horizontal and vertical directions. This can be between 1 (or even above in rare cases of vertical structures) and low values like 0.1 or 0.01 for strongly layered structures.

**Comment by makeabhishek** [comment]
What does zWeight corresponds for seismic tomography? How can it be correlated like resistivity?

**Comment by halbmy** [comment]
The parameter controls the regularization, no matter which parameter is inverted. Wasn't this obvious? Please read the tutorials on regularization.

**Comment by makeabhishek** [comment]
Actually, I was trying to find what values can be given. However, document didn't mention or I didn't find it that it should be in between `0 and 1`, not like regularization parameter \lambda. Even while running inversion, giving any value higher than 1 is not throwing any warning or error.
Am I right that `zWeight `need to be in the range of 0 to 1

**Comment by halbmy** [comment]
There is no need to be between 0 and 1. As I explained in my above comment, it can be very reasonably above 1 and of course it can formally also below 0 regarding formula (2) in Coscia et al. (2011). However, if the weight falls below 0, the contribution to the smoothness rises again and there will be a direction with minimum smoothness. So, in fact values below (or even equal to) zero do not make sense although they are possible.
