### ISSUE TITLE
Questions regarding the Res2dInv export format

### ISSUE THREAD

**Issue by IsabellaLorenzen** [gimli-org/gimli#692]
### Problem description

In my original res2dinv .dat file i had 9 IP-windows, but after filtering and exporting the .dat file using the exportRes2dInv(filtered_data, file_location) command, i only have 1 IP-window.

Also it is exported as a mixed array, is this different than my original multigradient array when i invert it? 

If the number of IP-windows and array type influence the inversion, is it possible to specify IP-windows and array type during the export? 

In the pictures below you can see the header for the original .dat file and the exported .dat file respectivly. (The data in the first picture continues horisontally with more IP-windows).
![image](https://github.com/gimli-org/gimli/assets/162128671/208b5f78-c02d-473e-a178-0186872840c0)
![image](https://github.com/gimli-org/gimli/assets/162128671/668b7b93-e268-43e5-a562-475c0008b461)

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
As the `exportRes2dInv` function is part of the pyBERT module, please raise an issue here: https://gitlab.com/resistivity-net/bert
Therefore I am closing it.

The code seems not to support multiple windows yet and I will not find time and motivation to fix this (and I cannot test it as I am not using res2dinv). But I encourage you to have a look into that function, extend it and give it back to the community by providing the code.
