### ISSUE TITLE
Shared colorbar

### ISSUE THREAD

**Issue by IsabellaLorenzen** [gimli-org/gimli#699]
Hallo!

Is there a function to share colorbar between several plotted ERT profiles?

**Comment by halbmy** [comment]
Of course, by using the matplotlib commands.

But you can, e.g., also use `colorBar=False` for some of the plots (using the same `cMin/cMax/cBar` keyword arguments, and maybe one explicit colorbar in a dedicated axis with `pg.viewer.mpl.createColorBarOnly`.
