### ISSUE TITLE
Anisotropic dan Geostatistic in ERT

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#701]
Excuse me sir, I have read some pygimli articles and journals related to Geostatictic and Anisotropic. What exactly is the basic difference between these two and how to do geostatistical and anisotropic? Can you provide a code example that I can use?

**Comment by halbmy** [comment]
Please read the tutorials about regularization and geostatistic operators in particular:
https://www.pygimli.org/_tutorials_auto/3_inversion/plot_5_Regularization.html
https://www.pygimli.org/_tutorials_auto/3_inversion/plot_6-geostatConstraints.html
