### ISSUE TITLE
 Installing pybert on Colab

### ISSUE THREAD

**Issue by mvale095** [gimli-org/gimli#709]
### Installing pybert on Colab

I'm having trouble installing pybert on Colab. I've tried various methods, but Colab always seems to upload the wrong PyBert library.
![Wrong pybert library](https://github.com/gimli-org/gimli/assets/89981957/c262404f-e450-4a98-b13e-e2a67d752014)

Could anyone offer any advice on how to successfully install the correct pybert library? Is it possible to install it in Colab?

Thank you for your time.

Regards,
Miguel

**Comment by halbmy** [comment]
This issue should be directed to https://gitlab.com/resistivity-net/bert as pyBERT is not part of pyGIMLi. pyGIMLi should be easy to install on Google Colab. For pyBERT we still have to generate a PyPI (`pip install`) package.

**Comment by mvale095** [comment]
Thank you for letting me know. Yes, I was able to install pyGIMli on Colab with no issues!

Regards,
Miguel


-------------------------------

Miguel E. Valencia

PhD Candidate Earth Systems Science

Florida International University

GSA Student Advisory Council Past Chair

GSA SE-Section Student Representative

M.S. Geosciences

-------------------------------




________________________________

**Comment by halbmy** [comment]
Closing in favour of https://gitlab.com/resistivity-net/bert/-/issues/324
