### ISSUE TITLE
drawPLC

### ISSUE THREAD

**Issue by frodo4fingers** [gimli-org/gimli#71]
hi,
in my eyes meshview's drawPLC is missing the cmap attribute. when drawModel is called, cmap defaults to None and can't be changed then. nothing really important, but ...

best regards
Friedrich

**Comment by halbmy** [comment]
I see the point. drawPLC gets **kwargs but does not pass them to drawModel so that they are inactive. To make sure that there are no double keywords we should use something like ```kwargs.setdefault('edgecolors', 'k')``` for the already used options

**Comment by halbmy** [comment]
I did this for drawPLC, but we should check this systematically for other functions using **kwargs.
