### ISSUE TITLE
Export Model Mesh to another software

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#710]
Excuse me sir
Can the model in meshtool is exported to another software? I want to export polygon model to another software for comparison result.

**Comment by halbmy** [comment]
> Can the model in meshtool is exported

I guess your asking whether a mesh (including properties like inverted model) can be exported?

A very widespread format, particularly for 3D visualization, is vtk. A mesh can be exported by
```
mesh.exportVTK("mesh.vtk")
```
If you want to include properties, e.g. from an inversion using a manager this might be extended
```
mesh = mgr.paraDomain
mesh["density"] = mgr.model
mesh.exportVTK(...
```
However, most managers have a method `mgr.saveResult()` that includes vtk export.

**Comment by tonapawilliam** [comment]
I want the my model just function in
`pg.viewer.mpl.drawPLC` 
ISo I can make my model in one layer  another software so I can  my model in front of my inversion result.  In pygimli I can do this with function pg.viewer, so I can comparion my inversion model  with my syntetic model.

**Comment by tonapawilliam** [comment]
In case, I just want to export the line of my model:

`world = mt.createWorld (....)
circle= mt.createCircle (..)

model = world ÷ circle
pg.show(model)`

Exported model can be export in xyz or something for comparison inversion result with model in another software modelling

**Comment by halbmy** [comment]
> I want the my model just function in

It is really hard to guess what you mean. 

The variable model (combined by the world and a circle) is a piece-wise linear complex. It does neither have a discretization nor any values associated. It is just structures (points and lines) that can be plotted, e.g. on an inversion result.

**Comment by tonapawilliam** [comment]
Okay, sir, so the structure can be exported to another software or not? If cannot, can the inversion result from Res2Dinv is plotted in pygimli? Or do you have recommendation software for comparison result of res2dinv and pygimli, and the software can plot the strutured model?

**Comment by halbmy** [comment]
Of course, inversion results can be exported or interpolated. To avoid interpolation errors, one should use a regular grid for a comparison. It should be easy to read in a res2dinv model into a grid.

I have no idea what you mean with pg.paraview.
