### ISSUE TITLE
Running inversion multiple times give different result

### ISSUE THREAD

**Issue by makeabhishek** [gimli-org/gimli#712]
### Problem description
1. I'm running traveltime inversion. While running the model 'velInv ' multiple times its generating different results. I'm not sure why? Does the model inverting previous mesh and not initialise the model from zero slowness?
2. How do we check, what is the initial model for the inversion and plot it?
3. Also, calculating misfit is giving error.

### Your environment
           OS : Windows
            CPU(s) : 64
           Machine : AMD64
      Architecture : 64bit
               RAM : 511.9 GiB
       Environment : Jupyter

  Python 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:29:04) [MSC
  v.1929 64 bit (AMD64)]

           pygimli : 1.4.3
            pgcore : 1.4.0
             numpy : 1.25.0
        matplotlib : 3.7.2
             scipy : 1.11.2
           IPython : 8.12.0
           pyvista : 0.43.2

### Steps to reproduce
```
mgr = tt.TravelTimeManager(data=data, verbose=True)
velInv = mgr.invert(data, mesh=mesh, lam=1, useGradient=1, zWeight=15.0, secNodes=5, absoluteError=error,
                    blockyModel = True, robustData = True,
                    lambdaFactor=1,
                    # cType=1,
                    #startModel=1/2200, 
                    isReference=False,
                    showProgress= False,
                    #verbose=True,
                   )
```

```
 # Misfit calculation
misfit = mgr.inv.response / mgr.data['t'] * 100 - 100
pg.show(mgr.data, misfit, cMap="bwr", cMin=-10, cMax=10, label="misfit (%)")

ERROR - None.show(C:\Users\376189\Documents\pyGimli\pygimli\gimli\pygimli\viewer\showmesh.py:159)
Can't interprete obj: Data: Sensors: 16 data: 120, nonzero entries: ['err', 'g', 's', 't', 'valid'] to show.
(None, None)

```

### Expected behavior
Running `velInv` should generate same inverted result every time I run it. But its giving me different results. Seems like inversion is updating the earlier model without clearing the memory.

**Comment by halbmy** [comment]
Thank you for reporting. This behaviour should, of course, not happen. Please make sure it also occurs with the newest version, v1.5.0

Can you, please, specify the full code and all required files so that we can reproduce the problem?

**Comment by makeabhishek** [comment]
1. - Thanks for your reply @halbmy. Updating to latest version (1.4.6) still have the same issue.

2. - In addition to that, plotting figure is also an issue. When I'm plotting results in cell 2, its not generating mesh. However running cell 2 second time, it generate figure. 

3. - How can I assign an initial model during inversion , say for lambda=1. Assume if I run the inversion once and the inverted model to another inversion with different parameters, say for lambda=5.

[gimli.zip](https://github.com/gimli-org/gimli/files/15238776/gimli.zip)

**Comment by halbmy** [comment]
1. The latest version is v1.5.0.
2. estimating the error after initializing the manager and calling invert is useless. Better do it before only once. Apparently the error in the file is taken.
3. Your traveltimes are in the order of 6-50µs. So an absolute error of 1e-3 (1ms) does not make much sense as a homogeneous model is already fitting the data.
4. `zWeight=0` is not recommended as there will be no smoothness in vertical direction.
5. A gradient model does not make much sense for a circular geometry, here a constant model is better.
6. You should use the highest lambda that is able to fit your data. `robustData` only makes sense in case of outliers.
7. When using meaningful parameters, I am getting the same result. No idea where your difference comes from. 
8. You can specify a starting model by `startModel=` either as a float or a vector. 

I don't understand your second point. All works well.

**Comment by makeabhishek** [comment]
I used `conda update -c gimli -c conda-forge pygimli` and it updated my pygimli version from v1.4.3 to v1.4.6. Not sure why it didn't update to v1.5.0.

**Comment by halbmy** [comment]
A core update (1.4 to 1.5) often means some update to other libraries that is sometimes not done unless explicitly written (`pygimli=1.5`), but then it is better just to create a new environment.

**Comment by halbmy** [comment]
`nBounds` is the number of internal boundaries (edged between two triangles) used for defining the smoothness.

**Comment by halbmy** [comment]
`CSLGCDWWtrans` is the inverse solver used, see Günther et al. (2006) or Günther(2004)

**Comment by halbmy** [comment]
The inverse solver just solves the system of equations, but does not determine the solution. Some of the solvers in my PhD thesis do just not apply and others just incorporate additional weightings. If is all explained there. `CGLSCDWWtrans` is the one that is used.

**Comment by halbmy** [comment]
As discussed in the #689, both values of 0 and 10 make much sense. 

Nevertheless, the results of two runs with the same parameters should be identical, at least within numerical accuracy and we don't know where the difference comes from but keep digging. Looking at the ratio between two runs, the lower the impact of regularization is (low lamda or lamdaFactor, blockyModel), i.e. the more we are inverting noise.
