### ISSUE TITLE
1.	How get  j of specify nodes after forward?

### ISSUE THREAD

**Issue by subenyu** [gimli-org/gimli#713]
### Problem description
1.	How get the u and j of specify nodes after forward modeling?
### Your environment
  OS : Windows
        CPU(s) : 64
       Machine : AMD64
  Architecture : 64bit
           RAM : 511.9 GiB
   Environment : Jupyter

Python 3.10 | packaged by conda-forge | (main, Dec 23 2023, 16:29:04) [MSC
v.1929 64 bit (AMD64)]
       pygimli : 1.50
##################################################
import numpy as np
import matplotlib.pyplot as plt
import pygimli as pg
import pygimli.meshtools as mt
import pygimli.physics.ert as ert
from pygimli.viewer.mpl import drawStreams
from pygimli.physics import ert

rhomap = [[1, 100],
          [2, 1000],
          [3, 10],
          ]
shm  = ert.load("data.txt")
layers  = mt.createWorld(start=[-1000, 0], end=[1000, -700], layers=[-500], worldMarker=True)
block = mt.createCircle(pos=[0, -200.], radius=[86, 6], marker=3,
                        boundaryMarker=10, area=50)
for pos in shm.sensorPositions():
    layers.createNode(pos)
geom = layers + block 
mesh = mt.createMesh(geom, quality=34)
scheme = ert.load("data.txt")
shm = scheme
for pos in shm.sensorPositions():
    world.createNode(pos)

mesh = mt.createMesh(geom, area=1000, quality=33, smooth=[1, 10])
# mesh = mt.createMesh(world, area=1000)
pg.show(mesh, data=rhomap , label=pg.unit('res'), showMesh=True, logScale=True)
mesh = mesh.createP2()
pot2 = ert.simulate(mesh=mesh, scheme=shm, res=rhomap, returnFields=1)

E1 = -pg.solver.grad(mesh, pot2[0])
E2 = -pg.solver.grad(mesh, pot2[50])
res = np.array([0.3, 100, 0.00001])
E = abs(E1)+abs(E2)
E = (E1) - (E2)
Eabs = np.linalg.norm(E, axis=1)
j = Eabs / res[mesh.cellMarkers()-1]
print(mesh,j)
pg.show(mesh, np.log10(j))  # Eabs
*******************************************
How get the u and j of specify nodes after forward modeling?
*********************************
Thank you very much.
[data.txt](https://github.com/gimli-org/gimli/files/15229588/data.txt)

**Comment by halbmy** [comment]
> How get j of specify nodes after forward

Can you, please, formulate at least the title in correct sentences?

The potential u is defined on the nodes and solved for by the finite element method. The electric field is the negative gradient of the potential, evaluated for cells using the gradient operator, and the current density is obtained by multiplication with the conductivity. For an example, see, e.g. https://www.pygimli.org/_tutorials_auto/2_modelling/plot_3-mod-fem-BC.html or https://www.pygimli.org/_examples_auto/3_ert/plot_04_ert_2_5d_potential.html
Have a look at the `drawStreams` function where this is computed.
