### ISSUE TITLE
pyvista shows no result graph when I tried to reproduce the example '3D surface ERT inversion' 

### ISSUE THREAD

**Issue by ZhenluRen** [gimli-org/gimli#719]
### Problem description

I am trying to run the sample code '3D surface ERT inversion' , and I have not changed the source code, but when the inversion is completed, the result image didn't been displayed.

The link of this example: https://www.pygimli.org/_examples_auto/3_ert/plot_07_ert_3dsurface.html

The information that showed in the command line is attached. (file name: command info.txt)
[command info.txt](https://github.com/gimli-org/gimli/files/15321966/command.info.txt)

Thanks in advance.

Zhenlu
####################### My environment ######################################################

                OS : Windows
            CPU(s) : 16
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.7 GiB
       Environment : IPython

  Python 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:40:31) [MSC
  v.1929 64 bit (AMD64)]

           pygimli : 1.4.1
            pgcore : 1.4.0
             numpy : 1.21.6
        matplotlib : 3.7.2
             scipy : 1.9.1
              tqdm : 4.66.4
           IPython : 8.16.0
           pyvista : 0.42.2

**Comment by halbmy** [comment]
It may be related to your settings how you run the script and how the output is rendered.

Just to make sure: as pyGIMLi 1.4.1 is almost 1 year old, can you try with the newest version 1.5.0? 

Can you just try one of the pyVista examples, completely independent of pyGIMLi?

**Comment by ZhenluRen** [comment]
Dear Thomas,
It is indeed caused by the outdated version, I updated the pyGIMLi and now it works. Thank you.
Zhenlu
