### ISSUE TITLE
how to fix import pygimli error libcholmod.so.3 on Mybinder

### ISSUE THREAD

**Issue by stefanazzz** [gimli-org/gimli#722]
### Problem description

When trying to run from my Github repository using MyBinder,
import pygimli gives the following error:

"libcholmod.so.3: cannot open shared object file: No such file or directory  (...)"

**This can be fixed** by adding python=3.8 to the yml environment file (see file below)

### Your environment

from environment.yml file on github:

<pre>
channels:
  - conda-forge
  - gimli
  - defaults
dependencies:
  - python=3.8          <-- add this line to make "import pygimli" work correctly
  - pygimli>=1.1.0
</pre>
### Notes

I suppose that 1.1.0 is compatible only with 3.8 not more recent versions. Note that pygimli >=1.5.0 shows the same problem when compiled with the current (May 2024) default mybinder python 3.11.x.  I tried a few combinations but so far only 1.1.0 and 3.8 seem to work on mybinder.

**Comment by halbmy** [comment]
Can you try using `pip install pygimli` instead?

**Comment by stefanazzz** [comment]
Yes Thomas, I will try that too and let you know

**Comment by ruboerner** [comment]
Is https://github.com/gimli-org/gimli/issues/721#issuecomment-2126343717 probably related?

**Comment by stefanazzz** [comment]
yes, using pip in the environment.yml file also works (rather than
downgrading to python 3.8):

channels:
  - conda-forge
  - gimli
  - defaults
dependencies:
  - obspy
  - ipympl
  - pandas
  - shapely
  - pip:
    - pygimli

**Comment by stefanazzz** [comment]
to reply to Ralph-Uwe, possibly related, but I would not know how to
implement the symbolic links on github/mybinder

**Comment by prisae** [comment]
Just to mention it here too: The same happens on Github Actions: While `conda install -c gimli pygimli` does work, loading pygimli results in
```
ImportError: libcholmod.so.3: cannot open shared object file: No such file or directory
```

**Comment by prisae** [comment]
I just got hit by this even on my local machine (Ubuntu 22.04.4) with Python 3.11.

**Comment by carsten-forty2** [comment]
For win and linux and py310, py311 you can try `pip install pygimli` which may help. 
However, the pgcore package which comes with the pip installation is not compatible with the current 'master' and 'dev' branch. If you want to use git sources with the `pgcore` from pip, you need to switch to the `wheel` branch which should not far away from `dev` and will be rebased to the new dev after some more tests.

**Comment by prisae** [comment]
Cool, thanks, that works for now!

**Comment by prisae** [comment]
This was marked as completed, but I keep running into this issue also with pyGIMLi 1.5.2, when using `conda`. When using `pip`, pyGIMLi installs a s..tload of stuff, basically re-building my entire environment, and subsequently fails of dependency issues.

Nothing urgent, but I think something still to keep an eye on...?

**Comment by halbmy** [comment]
You're completely right, we should leave this issue open until it is solved properly and not only a hack mixing conda and pip. As the dependency is with pgcore and not pyGIMLi, we will solve it only with pyGIMLi v1.6, i.e. a core update.

**Comment by prisae** [comment]
This time this suggestion made it possible (thanks @halbmy):
```
conda create -n pg -c gimli -c conda-forge "pygimli>=1.5.0" python=3.10 suitesparse=5
```

**Comment by halbmy** [comment]
v1.5.3 is out, requiring suitesparse 5. Can you try if
```
conda create -n pg -c gimli -c conda-forge pygimli=1.5.3
```
works?

**Comment by prisae** [comment]
Works like a charm, thanks!
