### ISSUE TITLE
Question about geometric factor for an ERT survey with submerged and terrestrial electrodes

### ISSUE THREAD

**Issue by amehriban** [gimli-org/gimli#728]
Dear PyGimli team,

I have a question regarding the geometric factor for an ERT survey with a combination of submerged electrodes (i.e., on the seafloor) and terrestrial electrodes. In RES2DINV, we can indicate that the apparent resistivities that we import are calculated with the normal surface geometric factor. When we import these data into PyGIMLi, does the program also take this into account?

Thank you in advance!

**Comment by halbmy** [comment]
This is actually up to the user to a certain extent. If the geometry is flat (no matter if surface or subsurface electrodes) like in https://www.pygimli.org/_tutorials_auto/3_inversion/plot_8-regionWise.html then one can use the classical geometric factor, which is always using mirror electrodes. If the terrestial part contains topography, it will be computed numerically as in this example https://www.pygimli.org/_examples_auto/3_ert/plot_02_ert_field_data.html

**Comment by halbmy** [comment]
pyGIMLi is either computing the geometric factor
* numerically taking the whole geometry into account, OR
* analytically, but always taking the electrode depths into account by mirror electrode
So as long as there is no topography on land and the water level is zero, the geometric factors are correct.  At the end, it is just a factor to scale the measurements, so even using a wrong geometric factor will not much change the result.

**Comment by amehriban** [comment]
Thank you very much!
