### ISSUE TITLE
Wrong coordinates in tutorial notebook

### ISSUE THREAD

**Issue by mariosgeo** [gimli-org/gimli#731]
### Problem description

The tutorial for the tanked modeled ert, has wrong node coordinates, when it comes to the reference electrode and the calibration electrode.

You have defined the coordinates of the reference to be on te boundary conditions and when you refine the nodes, you add a node outside the domain (-0.501). Could you please fix this?

I think I have asked in the past, but it's not clear how you use the calibration node. Do you add some potential value somewhere?

**Comment by halbmy** [comment]
You are referring to https://www.pygimli.org/_examples_auto/3_ert/plot_modTank3d.html

The model goes from x=0...0.99, y=0...0.5 and z=-1...0 after:
`plc = mt.createCube(size=[0.99, 0.5, 1.0], pos=[0.495, 0.25], boundaryMarker=1)

The reference (current) electrode (-999) is 
`plc.createNode([0.5, 0.5, -0.5], marker=-999)`
at the side opposite to the electrode line.

The calibration node 
`plc.createNode([0.75, 0.25, 0.5], marker=-1000)`
is inside. 

The refinement electrodes obtains z=-0.501 but this is inside. Am I wrong?

**Comment by mariosgeo** [comment]
The box extends from -0.5 to +0.5. I think you need to have it -0.499

**Comment by halbmy** [comment]
Yes, you're right. The `pos` vector should have a ,0 for clarity and the refinement node for the reference is outside. I guess this will mainly affect the accuracy in the vicinity of the reference. Can you check what happens if you move the node up and not down or the reference line to z=0?

**Comment by mariosgeo** [comment]
The forward solution changes slightly solution will slight change (I suppose it's more accurate).
