### ISSUE TITLE
Petrophysical joint inversion: smooth the  output result

### ISSUE THREAD

**Issue by makeabhishek** [gimli-org/gimli#742]
It can be seen in [Petrophysical joint inversion](https://www.pygimli.org/_examples_auto/6_inversion/plot_3_petro_joint_inv.html#sphx-glr-examples-auto-6-inversion-plot-3-petro-joint-inv-py) example, the results are quite coarse. How can we smooth the output result or interpolate to make it smoother, so that we cannot see the triangular mesh features.

**Comment by halbmy** [comment]
If you want a finer mesh, you should specify a higher mesh quality or a maximum cell size. There are plenty of examples on this on pygimli.org

But they triangles represent the underlying discretization, so I see no point in post smoothing a result as this model would not fit the data anymore.

**Comment by makeabhishek** [comment]
Thanks, I meant if a smooth inverted results can be post processed without using finer mesh. Also to avoid seething mesh triangles. May be something like interpolation like in ‘plt.imshow()’Best RegardsAbhishekOn 1 Jul 2024, at 12:29 AM, Thomas Günther ***@***.***> wrote:﻿
If you want a finer mesh, you should specify a higher mesh quality or a maximum cell size. There are plenty of examples on this on pygimli.org
But they triangles represent the underlying discretization, so I see no point in post smoothing a result as this model would not fit the data anymore.

**Comment by florian-wagner** [comment]
Hi @makeabhishek,

you could interpolate the cell values to the nodes. As a consequence, the show function will recognize it as a field and not show the underlying mesh. But in most cases, showing the mesh is more beneficial as it shows the real discretizaiton used. So do not overdo it with interpolating your results just for "smooth visiualization" purposes.

Here a minimal example.

``` python
import pygimli as pg
mesh = pg.createGrid(30,30)
celldata = pg.x(mesh.cellCenters())
pg.show(mesh, pg.meshtools.cellDataToNodeData(mesh, celldata))
```
