### ISSUE TITLE
The resistivity values ​​are inverted after inversion with dipole-dipole array

### ISSUE THREAD

**Issue by ZhenluRen** [gimli-org/gimli#747]
Hello,

I am using pygimli to invert my ERT data. However, it seems that all the resistivity values are inverted after inversion when I use the dipole-dipole array. I also used dipole-dipole array previously but it is the first time I came across this issue. Could you help me look at my code and data to find out where the problem is?

The files are attached. File '03_inversion-topo.py' is to perform the inversion analysis, and the data for inversion are saved in the folder '03_data_gimili_topo'. 

Besides, may I ask the following three more questions:
1. Why is the voltage data negative when I used the dipole-dipole array to measure the data?
2. Why is the scale on the vertical axis marked with "DD" only on the first layer, and "WB" on the following layers on the pseudosection?
3. Why do the points on the pseudo graph become so scattered when I add terrain and make the X-axis data uneven?

Thank you.
Zhenlu

![Lambda_25_1TC_r_51_20240620_dd_1m_L1_all](https://github.com/gimli-org/gimli/assets/80757915/3014e8f4-643f-41ac-8ac5-0d9ed64bc7ab)
![Lambda_25_1TC_r_52_20240620_dd_1m_L2_all](https://github.com/gimli-org/gimli/assets/80757915/94247e8c-be58-427a-9fc6-b3eef9c58480)
[question-data.zip](https://github.com/user-attachments/files/16075755/question-data.zip)

**Comment by ZhenluRen** [comment]
![Uploading Lambda_25_6XL_r_64_20240625_dd_1m_L1_all.jpg…]()

**Comment by halbmy** [comment]
I don't understand what you mean with "resistivity values are inverted".

1. For an ABMN (C1C2P1P2) stay the voltage is always negative like the geometric factor as shown in many textbooks.
2. WB indicates that you have a Wenner beta (dipole length increases with distance) and not dipole-dipole
3. Hard to say. Better use the original data container for plotting data.

**Comment by florian-wagner** [comment]
Dear @ZhenluRen,

as @halbmy correctly said, the geometric factor for ABMN is negative. The problem in your code is that you take its absolute value. This is why the apparent resistivity response looks "inverted".

Try this

``` python
K = pg_ert.geometricFactor(data_orig)
data_orig['k'] = K
data_orig['rhoa'] = K * data_orig["u"] / data_orig["i"]
```

and let us know if this fixes your problem.

Best wishes
Florian

P.S.: You do not need `pybert`, you can also use `data_orig = pg_ert.load(path + '/' + fileN)`.

**Comment by ZhenluRen** [comment]
> 3\. B

Dear Florian,

Thank you for your answers. Now I modified my code as you said and now it can show the correct result.  :)

Best regards,
Zhenlu

**Comment by ZhenluRen** [comment]
> I don't understand what you mean with "resistivity values are inverted".
> 
> 1. For an ABMN (C1C2P1P2) stay the voltage is always negative like the geometric factor as shown in many textbooks.
> 2. WB indicates that you have a Wenner beta (dipole length increases with distance) and not dipole-dipole
> 3. Hard to say. Better use the original data container for plotting data.

Dear Thomas,

Thank you for getting back to me. Now I have understood the first two questions, only the third question I still want to figure out.

The problem is that my electrode spacing is not uniform due to the limitations of the field. My current approach is to change the "X" values ​​in the dataset to the actual electrode spacing. Then the pseudosection of the apparent resistivity values ​​is very discrete. I also don't understand why it is identified as a PP array on the surface since I don't have infinite electrodes.

 I'm wondering if this pattern is normal? If I want to include the true electrode positions correctly, what should I do? Or I better use the original data.

Kind regards,
Zhenlu

The original electrode coordinates: (err_1TC_r_51_20240620_dd_1m_L1-notopo.txt)
60
# x y z
0	0	-0.1
1	0	-0.1
2	0	-0.1
3	0	-0.1
4	0	-0.1
5	0	-0.1
6	0	-0.1
7	0	-0.1
8	0	-0.1
9	0	-0.1
10	0	-0.1
... ...
# a b m n err i ip iperr k r rhoa u valid 
1	2	3	4	3.00000570450656e-02	3.25300000000000e+02	0.00000000000000e+00	0.00000000000000e+00	-1.92891990665923e+01	2.69443590531817e+00	5.19735105498561e+01	-8.76500000000000e+02	1
2	3	4	5	3.00007190106414e-02	3.43920000000000e+02	0.00000000000000e+00	0.00000000000000e+00	-1.92891990665923e+01	2.02198185624564e-01	3.90024105341600e+00	-6.95400000000000e+01	1
3	4	5	6	3.00001353473012e-02	3.33330000000000e+02	0.00000000000000e+00	0.00000000000000e+00	-1.92891990665923e+01	1.10827108271083e+00	2.13776615341570e+01	-3.69420000000000e+02	1
... ...

Then I included the real electrode X-coordinates, so the data changes to: (err_1TC_r_51_20240620_dd_1m_L1.txt)
60
# x y z
0	0	-0.1
1	0	-0.1
**1.7	0	-0.1**
3	0	-0.1
4	0	-0.1
5	0	-0.1
6	0	-0.1
7	0	-0.1
8	0	-0.1
**9.2	0	-0.1**
10	0	-0.1
... ...
# a b m n err i ip iperr k r rhoa u valid 
1	2	3	4	3.00000570450656e-02	3.25300000000000e+02	0.00000000000000e+00	0.00000000000000e+00	-9.68024947089343e+00	2.69443590531817e+00	2.60828117468124e+01	-8.76500000000000e+02	1
2	3	4	5	3.00007190106414e-02	3.43920000000000e+02	0.00000000000000e+00	0.00000000000000e+00	-3.80803966706224e+01	2.02198185624564e-01	7.69978711466354e+00	-6.95400000000000e+01	1
3	4	5	6	3.00001353473012e-02	3.33330000000000e+02	0.00000000000000e+00	0.00000000000000e+00	-1.74378649718281e+01	1.10827108271083e+00	1.93258814924931e+01	-3.69420000000000e+02	1
... ...


![Lambda_25_1TC_r_51_20240620_dd_1m_L1_all](https://github.com/gimli-org/gimli/assets/80757915/998ca7f2-a064-4e04-81c5-35d7ef6e9023)
![Lambda_25_1TC_r_51_20240620_dd_1m_L1-notopo_all](https://github.com/gimli-org/gimli/assets/80757915/16a3b1e9-9ef3-4acf-a55a-e0b5c0501462)
[err_1TC_r_51_20240620_dd_1m_L1.txt](https://github.com/user-attachments/files/16122459/err_1TC_r_51_20240620_dd_1m_L1.txt)
[err_1TC_r_51_20240620_dd_1m_L1-notopo.txt](https://github.com/user-attachments/files/16122460/err_1TC_r_51_20240620_dd_1m_L1-notopo.txt)

**Comment by halbmy** [comment]
The `style` argument (leading to position-independent data displays) was introduced in pyGIMLi v1.5.0 four months ago: https://github.com/gimli-org/gimli/releases/tag/v1.5.0

In the next version, we will introduce a keyword forcing to use electrode numbers instead of positions.

**Comment by ZhenluRen** [comment]
> The `style` argument (leading to position-independent data displays) was introduced in pyGIMLi v1.5.0 four months ago: https://github.com/gimli-org/gimli/releases/tag/v1.5.0
> 
> In the next version, we will introduce a keyword forcing to use electrode numbers instead of positions.

Dear Thomas,

Thank you very much for getting back to me. These are very helpful. I will read the link carefully and look forward to the latest version.

Best regards,
Zhenlu
