### ISSUE TITLE
Examples from published papers

### ISSUE THREAD

**Issue by halbmy** [gimli-org/gimli#75]
Following the idea of reproducible science, we should give readers of published papers an information on how the specific results have been obtained, even if the results are slightly changing with software versions. This holds particularly for synthetic experiments (demonstrating both forward calculation, the noise and the inversion), but also for field data. Whereas the latter might be hold in a separete repository, the first are actually examples and could appear as such. Some are examples for programming a framework or should lead to frameworks and examples of using them.

I am just collecting pyGIMLi-related stuff that is not already covered by the BERT project (for which different documentation exists):

Fitting
- [x] Spectral Induced Polarization data fit using different Cole-Cole type models (Hupfer et al., 2016)
- [ ] Complex Dielectric (permittivity) Spectroscopy using network analyzers based on Debye and Cole-Cole terms (Loewer et al., 2016)
- [ ] Joint SIP and CDS fitting (Loewer et al., 2017)
- [ ] (lab) NMR spectroscopy??

Electromagnetic Soundings
- [x] Vertical Electrical Soundings (Günther & Müller-Petke, 2012): use new VES class
- [ ] FDEM soundings (Günther, 2013) or profiles using LCI framework (hard for synthetic)
- [ ] TEM (no publication yet)
(classic joint inversion could also go here)

Traveltime tomography
- [ ] Heincke et al. (2009): not yet under Python and no synthetic models
- [ ] Hellman et al. (2017): synthetic models 

Joint inversion
- [x] classic joint inversion of VES and FDEM data (Günther, 2013)
- [ ] block joint inversion (Günther & Müller-Petke, 2012)
- [x] 1D joint inversion of MRS and DC/IP soundings (Günther et al., 2010)
- [x] petrophysical joint inversion (Rücker et al., 2017)
- [ ] structurally coupled cooperative inversion (Hellman et al., 2017): better use newly created SCCI framework (COMET project)

Magnetic Resonance Sounding/Tomography
the problem is the missing kernel computation (before done with MRSmatlab, now with the external module COMET), maybe we store 1 or 2 kernels on pygimli.org (like mesh.geo)
- [x] block (joint) inversion with Marquardt-Inversion (Günther & Müller-Petke, 2012)
- [ ] Joint Inversion of VES and MRS data with genetic algorithms (Akca et al., 2014)
- [ ] Inversion of MRS data for water retention parameters (Costabel & Günther, 2014)
- [ ] Laterally constrained inversion of MRS profiles (Costabel et al., 2016)
- [x] 2D SNMR inversion (Dlugosch et al., 2014): work in progress (COMET project)

Special subjects
- [ ] Vertical Radar Profiling (VRP) (Igel et al., 2012)
- [ ] inversion of guided-wave GPR traveltime data (Igel et al., 2016)
- [ ] Optimization of electrode positions (Wagner et al., 2015): actually BERT-related but a general principle
- [ ] inversion of borehole NMR tool data (Dlugosch et al., 2016)
- [x] Fully coupled hydrogeophysical inversion (Rücker et al., 2017): probably no "quick example"

References
Akca, I., Günther, T., Müller-Petke, M., Basokur, A. T. & Yaramanci, U. (2014): Joint parameter estimation from magnetic resonance and vertical electric soundings using a multi-objective genetic algorithm. Geophysical Prospecting, 62(2), 364-376, doi:10.1111/1365-2478.12082.
Costabel, S., Günther, T., 2014. Noninvasive Estimation of Water Retention Parameters by Observing the Capillary Fringe with Magnetic Resonance Sounding. Vadose Zone Journal 13, 14. doi:10.2136/vzj2013.09.0163.
Costabel, S., Günther, T., Dlugosch, R., Müller-Petke, M., 2016. Torus-nuclear magnetic resonance: Quasicontinuous airborne magnetic resonance profiling by using a helium-filled balloon. Geophysics 81, WB119–WB129. doi:10.1190/geo2015-0467.1.
Costabel, S., Siemon, B., Houben, G., Günther, T., 2017. Geophysical investigation of a freshwater lens on the island of Langeoog, Germany – Insights from combined HEM, TEM and MRS data. Journal of Applied Geophysics 136, 231–245. doi:10.1016/j.jappgeo.2016.11.007.
Dlugosch, R., Günther, T., Müller-Petke, M., Yaramanci, U., 2014. Two-dimensional distribution of relaxation time and water content from surface nuclear magnetic resonance. Near Surface Geophysics 12, 231–241. doi:10.3997/1873-0604.2013062.
Dlugosch, R., Günther, T., Lukàcs,T. & Müller-Petke, M. (2016): Localization and identification of thin oil layers using a slim-borehole nuclear magnetic resonance tool. Geophysics 81(4), W109-W118, doi:10.1190/geo2015-0464.1.
Günther, T., 2013. On Inversion of Frequency Domain Electromagnetic Data in Salt Water Problems - Sensitivity and Resolution, in: Ext. Abstr., 19th European Meeting of Environmental and Engineering Geophysics, Bochum, Germany. doi:10.3997/2214-4609.20131387.
Günther, T., Akca, I. & Müller-Petke, M. (2015): Evolutionary Algorithms for MRS Single and Joint Inversion. Ext. Abstr., MRS2015 - 6th International Workshop on Magnetic Resonance, Aarhus, Denmark.
Hupfer, S., Martin, T., Weller, A., Günther, T., Kuhn, K., Ngninjio, V.D.N., Noell, U., 2016. Polarization effects of unconsolidated sulphide-sand-mixtures. Journal of Applied Geophysics 135, 456–465. doi:10.1016/j.jappgeo.2015.12.003.
Igel, J., Günther, T. & Kuntzer, M. (2013): Ground-penetrating radar insight into a coastal aquifer: the freshwater lens of Borkum Island. - Hydrology and Earth System Sciences, 17, 519-531, doi:10.5194/hess-17-519-2013.
Igel, J., Stadler, S., Günther, T., 2016. High-resolution investigation of the capillary transition zone and its influence on GPR signatures, in: Ext. Abstr., SAGEEP, Denver, USA. doi:10.4133/SAGEEP.29-046.
Loewer, M., Igel, J., Wagner, N., 2016. Spectral Decomposition of Soil Electrical and Dielectric Losses and Prediction of In Situ GPR Performance. IEEE J. Sel. Top. Appl. Earth Observations Remote Sensing 9, 212–230. doi:10.1109/jstars.2015.2424152.
Rücker, C., Günther, T., Wagner F.M. (2017): pyGIMLi: An open-source library for modelling and inversion in geophysics, Computers & Geosciences, in Press, doi:10.1016/j.cageo.2017.07.011.

**Comment by halbmy** [comment]
Well, Arnaud used BERT for this very nice article but nothing with heat equation and not explicitly with pyGIMLi. So the paper should appear in the BERT repo under "papers using BERT" but not here where we want to exemply the variety of methods and techniques included in pyGIMLi, mainly by synthetic examples.

**Comment by florian-wagner** [comment]
Well, to be fair, the static heat equation was solved with pygimli in this article:
> Because a marked temperature gradient is expected in the sink-hole, we modelled the 2-D temperature field using the framework of pyGIMLi (Rücker  et  al.,  2017;  www.pygimli.org) [...]

But I totally agree with @halbmy, that it is more a BERT usage and does not demonstrate a particular concept of pygimli. I think @Coastal0 just wanted to add to a general list of pygimli usages (thank you for that), which could (and should) coexist alongside and independent of a section on reproducible paper examples.
