### ISSUE TITLE
pg.show() plotting the depth values with an opposite sign

### ISSUE THREAD

**Issue by amehriban** [gimli-org/gimli#758]
Dear pygimli team,

I have noticed that lately pg.show() is plotting the ERT inversion result with an opposite sign, i.e positive values in the subsurface and negative values above ground level. Example picture attached. Is this a bug?

![image](https://github.com/user-attachments/assets/4b5d2d9c-4cad-4c12-bdff-2af16b96296e)

Thank you in advance!

**Comment by carsten-forty2** [comment]
Its supposed this way .. "depth" should be a positive value. You can avoid this with `pg.show(..., axisLabels=False)`. Then you get the original values and can label the axis yourself.

**Comment by amehriban** [comment]
I see, thank you very much!
