### ISSUE TITLE
Question convertMesh midcell data

### ISSUE THREAD

**Issue by SunnyMonty** [gimli-org/gimli#759]
### Problem description

I want to convert a mesh to midcell data. The binary 'convertMesh' fails and I cannot figure out where I make a mistake...
My data is from a result by an inversion with BERT (yeah, still using it). I have a resistivity.vector and a mesh (bms format).
When I start convertMesh on the command prompt I got error messages.

> sunny@maxwell:result240802_0843 $ **convertMesh -v -m -d resistivity.vector -o data.dat mesh/meshParaDomain.bms** 
> {'verbose': True, 'outVTK': False, 'p2mesh': False, 'outBoundaryVTU': False, 'outBMS': False, 'outBMS2': False, 'outMidCell': True, 'data': ['resistivity.vector'], 'outFileName': 'data.dat', 'rotate': None, 'scale': None, 'translate': None, 'interpolateCoords': None, 'interpolateMesh': None} ['mesh/meshParaDomain.bms']
> 02/08/24 - 09:35:10 - pyGIMLi - INFO - Reading mesh/meshParaDomain.bms (<class 'pygimli.core._pygimli_.Mesh'>)
> mesh/meshParaDomain.bms Mesh: Nodes: 8595 Cells: 15514 Boundaries: 24108
> Traceback (most recent call last):
>   File "/home/serfling/src/gimli/gimli/apps/convertMesh", line 279, in <module>
>     main(sys.argv[1:])
>   File "/home/serfling/src/gimli/gimli/apps/convertMesh", line 211, in main
>     data = parseDataStr(dataStr)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/home/serfling/src/gimli/gimli/apps/convertMesh", line 27, in parseDataStr
>     data = pg.RVector(0)
>            ^^^^^^^^^^
>   File "/home/serfling/src/gimli/gimli/pygimli/core/decorators.py", line 80, in __call__
>     return self.oldgetattr(name)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/home/serfling/src/gimli/gimli/pygimli/core/decorators.py", line 91, in base_getattr
>     raise AttributeError(
> AttributeError: module 'pygimli' has no attribute 'RVector'. Did you mean: 'BVector'?
> sunny@maxwell:result240802_0843 $

 ### Your environment
>>> print(pygimli.Report())

--------------------------------------------------------------------------------
  Date: Fri Aug 02 09:21:39 2024 CEST

                OS : Linux (Gentoo 2.15)
            CPU(s) : 16
           Machine : x86_64
      Architecture : 64bit
               RAM : 62.7 GiB
       Environment : Python
       File system : btrfs

  Python 3.12.3 (main, Jun 21 2024, 07:53:37) [GCC 13.2.1 20240210]

           pygimli : 1.5.1+76.g728ca1d8 (master)
            pgcore : Module not found
             numpy : 1.26.4
        matplotlib : 3.9.1
             scipy : 1.14.0
              tqdm : 4.66.4
           IPython : 8.26.0
            meshio : 5.3.5
           pyvista : 0.44.0
--------------------------------------------------------------------------------

**Operating system**: Linux
**Python version**:  3.12
**pyGIMLi version**: >>> print(pygimli.__version__)
1.5.1+76.g728ca1d8 (master)
>>> 
**Way of installation**:  compilation from source

**Comment by carsten-forty2** [comment]
Thanks for reporting.

Somehow the alias `pg.RVector` vanished. I revived it now.
