### ISSUE TITLE
neighborCellCount incorrect for boundary cells?

### ISSUE THREAD

**Issue by soehag** [gimli-org/gimli#760]
### Problem description

Hello everyone,
I am using the internal meshing utility and need to derive certain quantities from the mesh. I noticed, that the number of neighbours return by cell.neighborCellCount() does not match the number of triangles returned by cell.neighborCell(). For example, for a cell at the boundary of the domain the neighbourCellCount() is 3, whereas cell.neighborCell(2) returns None. Is this behaviour intended?

Best wishes
Hagen

### Your environment

-------------------------------------------------------------------------------
  Date: Fri Aug 02 14:46:31 2024 CEST

                OS : Linux
            CPU(s) : 64
           Machine : x86_64
      Architecture : 64bit
               RAM : 251.5 GiB
       Environment : Jupyter
       File system : ext4

  Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37)
  [GCC 12.3.0]

           pygimli : 1.5.0
            pgcore : 1.5.0
             numpy : 1.24.4
        matplotlib : 3.7.2
             scipy : 1.11.3
           IPython : 8.17.2
           pyvista : 0.42.3
--------------------------------------------------------------------------------

### Steps to reproduce

import pygimli as pg
import matplotlib.pyplot as plt

circle = pg.meshtools.createCircle(
    pos=[0, 0], radius=1, area=0.1, nSegments=100)

mesh = pg.meshtools.createMesh(circle)
fig, ax = plt.subplots(1)
pg.show(mesh, ax=ax)

cell = mesh.findCell([0.0, -0.99])
cell = mesh.findCell([-0.99, 0.1])

ax.plot(cell.center().x(), cell.center().y(), 'ro', markersize=1)
print(f"Neighbor count is: {cell.neighborCellCount()}")
print(f"Boundary count is: {cell.boundaryCount()}")

for cell_number in range(cell.neighborCellCount()):
    try:
        neighbor = cell.neighborCell(cell_number)
        ax.plot(neighbor.center().x(), neighbor.center().y(), 'bo', markersize=1)
    except:
        print(f"Neighbor {cell_number} does not exist")

### Expected behavior

In the case of the second cell, cell.neighborCellCount() should return 2. Neighbour cells should be indexed without interruption from 0 to 1.

### Actual behavior

In the case of the second cell, cell.neighborCellCount() returns 3. Neighbours exist for indices 0 and 2.

```
Neighbor count is: 3
Boundary count is: 3
Neighbor 1 does not exist
```

**Comment by carsten-forty2** [comment]
This behavior is intended.

`boundaryCount` and `neighbourCellCount` are equivalent (badish redundancy) and both show (hard coded) the number of boundaries a cell type have (e.g., 3 for triangle, 4 for quad etc.)

`cell.neighborCell(int)` returns the neighbor cell corresponding to the boundary with starting node i, or `None` if there is no such cell. The reason is that the neighbor cells needs somehow connected to specific nodes for further search capabilities. If we would only return valid neighbors they would be randomly unsorted.

**Comment by soehag** [comment]
Hi there,

thank you for the quick answer. I understand - due to the redundancy, I was expecting them not to show this behaviour.

Have a good weekend,
Hagen
