### ISSUE TITLE
The inversion depth in 2D ERT inversion.

### ISSUE THREAD

**Issue by lwang19-ai** [gimli-org/gimli#767]
### Problem description

I am doing a 2D ERT inversion in a landfill project. The array length is around 140m, the landfill depth is 15m, with a 1m drainage layer underneath. How should I manually consider this information in the inversion process? Should I set the prior resistivity for the drainage layer to an infinite value?

**Comment by halbmy** [comment]
What exactly do you mean with drainage layer? It sounds like there is hydraulic and also electric contact.

If you mean a geomembrane (e.g. an insulating foil), you don't have to discretize beyond that, i.e. creating a polygon with the topography and the geomembrane using Neumann boundary marker. The paper of Audebert et al. (2014) may help you.

Audebert, M., Clément, R., Grossin-Debattista, J., Günther, T., Touze-Foltz, N. & Moreau, S. (2014): Influenceof the geomembrane on time-lapse ERT measurements for leachate injection monitoring. Waste Management 34(4), 780-790, doi:10.1016/j.wasman.2014.01.011.

**Comment by halbmy** [comment]
Closing due to missing response.
