### ISSUE TITLE
Can't import ERT field data 

### ISSUE THREAD

**Issue by AY131313** [gimli-org/gimli#768]
Hi, 
I am trying to conduct an ERT field data inversion using the pygimli. I design the database exactly as it is supposed to (unified format) and it is shown in some cases like lake and etc. I try importing like below:

# Load your dataset
data = ert.load(r"the path\ERTfield.ohm", load=True, verbose=True)
print(data)

The issue is that the data values are not imported and I don't know why. but as the message below, parameters like a,b,m, and n are imported as the electrode positions:

Data: Sensors: 171 data: 0, nonzero entries: ['a', 'b', 'm', 'n']

I do my work in jupyter notebook environment.
I also upload the dataset I wanna import.
[ERTfield2.xlsx](https://github.com/user-attachments/files/16922922/ERTfield2.xlsx)

I have even tried using pybert.importData(), but no data is imported.

data = pb.importData(r"the path to dataset\ERTfield2.ohm", verbose=True)
print(data)

**Comment by halbmy** [comment]
You have (as correctly read) 171 electrodes but you refer to electrodes far above this number:
```
#a	b	m	n	rhoa	error
297	303	298	302	49.18	1.4754
295	305	298	302	61.12	1.8336
293	307	298	302	75.74	2.2722
....
```
The a/b/m/n numbers are indices into the electrode list and should be between 1 and 171. As all are above 171, the number of valid data is 0.

**Comment by AY131313** [comment]
hello again, 
Thanks for providing insight into the subject. 
now I have to make my electrode distances 1 to 171, how should I do it?

**Comment by halbmy** [comment]
Whereas the electrodes have arbitrary (float) positions (x and y) in the upper electrode section, the ABMN of lower section only holds indices (integer) into this list, so a 185 becomes a 1 (the first electrode mentioned), the 200 a 2 and so on. 

Again: those numbers are NOT distances but indices.

**Comment by halbmy** [comment]
I am referring to #796 where also positions are read. If you use only the ABMN part (
[ABMN.xlsx](https://github.com/user-attachments/files/18132004/ABMN.xlsx)) you can read it by
```
data = ert.DataContainer()
for i, row in df.iterrows():
    eID = [data.createSensor([row[se], 0, 0]) for se in 'abmn']
    data.createFourPointData(i, *eID)

data.sortSensorsX()
data['rhoa'] = df['rhoa']
data['err'] = df['error']
print(data)
```
