### ISSUE TITLE
TDEM

### ISSUE THREAD

**Issue by subenyu** [gimli-org/gimli#769]
### Problem description

import pygimli.physics.em; print(dir(pygimli.physics.em)):
['FDEM', 'HEMmodelling', 'TDEM', 'VMDTimeDomainModelling', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'fdem', 'hemmodelling', 'importMaxminData', 'io', 'readusffile', 'rhoafromB', 'rhoafromU', 'tdem', 'vmd']
AttributeError: 
(1)module 'pygimli.physics.em' has no attribute 'TDEMSmoothModelling'

### Your environment

 OS : Windows
            CPU(s) : 32
           Machine : AMD64
      Architecture : 64bit
               RAM : 127.8 GiB
       Environment : Jupyter

  Python 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:40:50) [MSC
  v.1937 64 bit (AMD64)]

           pygimli : 1.5.1
            pgcore : 1.5.0
             numpy : 1.26.4
        matplotlib : 3.8.3
             scipy : 1.11.4
              tqdm : 4.66.4
           IPython : 8.20.0
            meshio : 5.3.5
            tetgen : 0.6.4
           pyvista : 0.43.4

  Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303
  for Intel(R) 64 architecture applications

### Expected behavior
import numpy as np
import matplotlib.pyplot as plt
import pygimli as pg
from pygimli.physics import em
from pygimli.viewer.mpl import drawModel1D

t = np.logspace(-4, -2, 20)
fopkw = dict(times=t, txArea=100**2)
synth = [50, 100, 300, 30, 300]
fopSynth = em.VMDTimeDomainModelling(nLayers=(len(synth)+1)//2, **fopkw)
data = fopSynth(synth)
print(data)
plt.loglog(data, t, "x-")
plt.grid()

thk = np.logspace(0.7, 1.7, 15)
print(sum(thk))
fop = em.TDEMSmoothModelling(thk=thk, **fopkw)
inv = pg.Inversion(fop=fop)
inv.dataTrans = pg.trans.TransLog()
inv.modelTrans = pg.trans.TransLog()
model = inv.run(data, relativeError=0.03, verbose=True)

### Actual behavior
AttributeError: 
(1)module 'pygimli.physics.em' has no attribute 'TDEMSmoothModelling'

**Comment by halbmy** [comment]
Can you update to pyGIMLi v1.5.2 and try again?

**Comment by subenyu** [comment]
pyGIMLi v1.5.2 is ok 
Thank you very much!
