### ISSUE TITLE
Visualize ERT res2dinv file with topography

### ISSUE THREAD

**Issue by Santi-Rebole-Canals** [gimli-org/gimli#770]
### Problem description

Hi!
I am currently working on visualizing the topography from an ERT res2dinv file. In this type of format, the topography is located below the databody, at the bottom of the file. When using pygimli, in the non-zero entries of the data, the 'r' entry (which I think it accounts for topography data for those points) does not appear. I attach the ERT res2dinv file with topography in this issue. 
Also, in my current dataset, I have altitude information for every 30 meters more or less, but not for each individual electrode. Will this affect to the topography representation in pygimli?. 
Is there a method within pygimli to perform linear interpolation of this topographic data to estimate altitudes for each of the electrode positions, considering the total extent of the survey (600 m), and the separation between each electrode (5 m)?
[Nutram_3_s_edited_with_topography.txt](https://github.com/user-attachments/files/16993844/Nutram_3_s_edited_with_topography.txt)

Thank you in advance,

Santi Rebolé

**Comment by halbmy** [comment]
Yes, there is exactly the function `interpolateAlongCurve` (aliased as `tapeMeasureToCoordinates`): https://www.pygimli.org/pygimliapi/_generated/pygimli.meshtools.html#pygimli.meshtools.interpolateAlongCurve

```python
from pygimli.physics import ert
from pygimli.meshtools import interpolateAlongCurve
import matplotlib.pyplot as plt

data = ert.load("Nutram_3_s_edited_with_topography.txt")
xz = data.additionalPoints()[:, :2]
exz = interpolateAlongCurve(xz, pg.x(data))  # try method='spline' or 'harmonic'

plt.plot(xz[:, 0], xz[:, 1], "o-")
plt.plot(exz[:, 0], exz[:, 1], '+')

data.setSensors(exz)
data.save("data.dat")
```
![image](https://github.com/user-attachments/assets/775ab651-0aa4-4e4f-8c64-8ecd8a3738c1)

**Comment by halbmy** [comment]
Does this solve your problem?

**Comment by Santi-Rebole-Canals** [comment]
Hi!

Thanks for the reply.
I can't represent it. Maybe it's because I am working with an older version of pygimli?. The program returns the following error. 
![image](https://github.com/user-attachments/assets/c7f74508-cb2d-4165-9bfa-d049cd53240a)

Also, after representing the topography, how can I visualize the data beneath the surface topography? 

Thanks in advance,

Santi

**Comment by Santi-Rebole-Canals** [comment]
Hello again,
Linking to the previous, I have attempted to use the code you provided with another ERT res2dinv file, but the same problem persists. For your reference, I attach other file, with the same structure but different data, in this comment.
Greetings,

Santi
[pastillo_p6_dip_edited_topography.txt](https://github.com/user-attachments/files/17116650/pastillo_p6_dip_edited_topography.txt)

**Comment by halbmy** [comment]
Well, this code works well on my computer:
```
import matplotlib.pyplot as plt
import pygimli as pg
from pygimli.physics import ert
from pygimli.meshtools import tapeMeasureToCoordinates
from pygimli.meshtools import interpolateAlongCurve

data = ert.load("pastillo_p6_dip_edited_topography.txt")
print(data)

xz = data.additionalPoints()[:, :2]
print(xz)

exz = interpolateAlongCurve(xz, pg.x(data))
plt.plot(xz[:, 0], xz[:, 1], "o-")
plt.plot(exz[:, 0], exz[:, 1], '+')

data.setSensors(exz)
data.save("data.dat")
```
![image](https://github.com/user-attachments/assets/b554a360-c74a-4470-9729-faabec5dade0)
(even though I doubt that this zigzag represents the correct topography)

Anyway, if you then do inversion, the topography will be correctly implemented.
Note that the pseudosection is just a coloured table of measurements, so in my opinion it does not make sense to undulate it along the topography as x and z values are no real coordinates anyway.

**Comment by halbmy** [comment]
So, if you have an older pyGIMLi version, I can only encourage you to create a new environment with the newest version (this will not destroy the old one) and check with this.

**Comment by Santi-Rebole-Canals** [comment]
Hi,
Thank you for the recommendation. I created a new environment and it did work.
However, after applying inversion, the topography remained unrepresented. 
I include the code I used for the inversion to provide with more context.

data['k'] = ert.createGeometricFactors(data, numerical=False) #No topografía--Cálculos numéricos
data['err'] = ert.estimateError(data, absoluteError= 0.001, relativeError=0.1, absoluteUError=None)
mgr = ert.ERTManager()
mod = mgr.invert(data, lam=50, verbose=True, zWeight=0.5, paraMaxCellSize = 15, paraDX = 2.5, paraDepth=100, quality=33.6)
mgr.showResult(mod, cMin=5, cMax=2000, logScale=True)

Thank you.

**Comment by Santi-Rebole-Canals** [comment]
Yes, thank you for the suggestions, it worked.
