### ISSUE TITLE
Resistivity values in ERT error representation.

### ISSUE THREAD

**Issue by Santi-Rebole-Canals** [gimli-org/gimli#771]
Hello,

In the ERT survey I am processing, I have achieved a good representation of the variations (errors) in each quadripole. However, the resistivity values shown in the color scale below the graph do not exhibit any variation. Why?
![Captura](https://github.com/user-attachments/assets/d3a7661f-ca34-4f36-a13b-30767d85373f)

Thanks.

**Comment by Santi-Rebole-Canals** [comment]
Also, there is a way for clipping the bottom corners in PyGIMLi??

**Comment by halbmy** [comment]
I have no idea how you generated this image. Can you please paste the code and attach the file?

**Comment by Santi-Rebole-Canals** [comment]
In the end I could fix it, thanks. It got mistaken between absoluteError and absoluteUError functions. 
By the way, there is a way for clipping the bottom corners?

Thanks

**Comment by halbmy** [comment]
what do you mean with clipping the corners? Like in #684 ?

**Comment by Santi-Rebole-Canals** [comment]
Yes, exactly,
thanks

**Comment by halbmy** [comment]
The above image just shows the pseudosection which is trapezoidal by nature. For a trapezoidal Model domain, see the mentioned issue.
