### ISSUE TITLE
How to create a rotated ellipse?

### ISSUE THREAD

**Issue by ZhenluRen** [gimli-org/gimli#775]
Dear Developer Team,

I am currently working on forward modeling, and I would like to know if it is possible to create a rotated ellipse using code 'mt.createCircle'? 
Thank you very much.

Best regards,
Zhenlu Ren

**Comment by halbmy** [comment]
Of course, you can first create a unit the circle, scale it with the main axes and then rotate it
```
circle = mt.createCircle()
circle.scale([10, 5])
circle.rotate([0, 0, np.pi/6])
```

**Comment by ZhenluRen** [comment]
> Of course, you can first create a unit the circle, scale it with the main axes and then rotate it
> 
> ```
> circle = mt.createCircle()
> circle.scale([10, 5])
> circle.rotate([0, 0, np.pi/6])
> ```

Dear Thomas,

Thank you very much. It works very well.

Best regards,
Zhenlu
