### ISSUE TITLE
pip install collects latest (too new) numpy

### ISSUE THREAD

**Issue by NoteboomM** [gimli-org/gimli#776]
### Problem description

I'm not too familiar with pip, but ```pip install pygimli``` appears to be pulling the wrong numpy - is it possible to change the requirement somewhere? It appears to require ```numpy>=1.25``` which currently downloads/installs numpy v2.1.1 which doesn't work well with pyGIMLi at times. In contrast, ```conda install gimli::pygimli``` downloads/installs numpy v1.26.4

### Your environment
```
--------------------------------------------------------------------------------
  Date: Thu Oct 03 14:22:21 2024 W. Europe Summer Time

                OS : Windows (10 10.0.22631 SP0 Multiprocessor Free)
            CPU(s) : 20
           Machine : AMD64
      Architecture : 64bit
       Environment : Python

  Python 3.10.15 | packaged by conda-forge | (main, Sep 30 2024, 17:41:41)
  [MSC v.1941 64 bit (AMD64)]

           pygimli : 1.5.2
            pgcore : 1.5.0
             numpy : 1.26.4
        matplotlib : 3.9.2
             scipy : 1.14.1
              tqdm : 4.66.5
           IPython : 8.28.0
            meshio : 5.3.5
            tetgen : 0.6.5
           pyvista : 0.44.1
--------------------------------------------------------------------------------
```
If I use the pip install in a new environment, it is the same, but with numpy: 2.1.1

### Steps to reproduce

using pip install instead of a conda install

### Expected behavior

Can the numpy requirement for the pip install be changed to a version range, or fixed to 1.26?

### Actual behavior

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment]
The newest version v1.5.3 should be able to work with numpy 2.x. please give it a try and report back.

**Comment by makeabhishek** [comment]
I'm also getting the same issue. 
I installed pyginli usign conda
`conda create -n pg -c gimli -c conda-forge "pygimli>=1.5.0"`
When trying to update numpy from 1.26 to 2.2. It is still pulling 1.26.

**Comment by carsten-forty2** [comment]
try `pip install pygimli` this is build for numpy >=2.1

**Comment by makeabhishek** [comment]
I tried but it is not working.
```
conda create -n pg -c gimli -c conda-forge
pip install pygimli
```

**Comment by halbmy** [comment]
In both cases you created an environment named pg. Did you activate it before calling `pip install`?

**Comment by makeabhishek** [comment]
Yes, 
I activated those.

**Comment by halbmy** [comment]
> I now installed using condo and looks things are back to work

Honestly, I cannot get any meaning of this sentence. Do you mean things are working?

**Comment by makeabhishek** [comment]
Yes, it's working now. I need to double check which version of numpy it is using. Also don't know when I installed earlier using same procedure it was not working and fetching latest numpy.
