### ISSUE TITLE
Install pygimli on ubuntu encounter the problem

### ISSUE THREAD

**Issue by bigbenbell** [gimli-org/gimli#78]
hello,
When I install pygimli on the platform of ubuntu 16.04 LTS. I use
      "conda install -f pygimli" 
to install pygimli. there is no bugs . I use
       "python -c "import pygimli; pygimli.test()"
to test pygimli.  But the Terminal shows that:

libboost_python3.so.1.64.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/bigbenbell33/miniconda/lib/python3.6/site-packages/pygimli/core/__init__.py", line 33, in <module>
    from . _pygimli_ import *
ImportError: libboost_python3.so.1.64.0: cannot open shared object file: No such file or directory
ERROR: cannot import the library '_pygimli_'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bigbenbell33/miniconda/lib/python3.6/site-packages/pygimli/__init__.py", line 18, in <module>
    from . import core
  File "/home/bigbenbell33/miniconda/lib/python3.6/site-packages/pygimli/core/__init__.py", line 43, in <module>
    _pygimli_.load = None
AttributeError: 'NoneType' object has no attribute 'load'

I don't know how to deal with this problem. If anybody have encounter the same problem, please to help me.

**Comment by halbmy** [comment]
thanks for reporting the problem.
We have a server with exactly the same system, freshly setup.
I will try to see whether we have the same problems tomorrow and report back.
However I am afraid we will have to wait until Florian is back to fix the problem.
In the meanwhile you can try the curl installation.

**Comment by halbmy** [comment]
I followed the instructions on https://www.pygimli.org/installation.html#linux (for some reason the link on the Linux tab does not work) and have exactly the same problem, i.e.
```which python```
makes sure that the miniconda python is used,
```python --version```
indicates that Python 3.6.1 is installed through miniconda. 
Apparently we fail shipping the boost libraries with the conda package. Florian will fix it when he is back. 

However, boost is an available linux package that can be searched by
```sudo apt search boost```
I chose the developer version with all packages and installed it by
```sudo apt install libboost-all-dev```
As a result I have boost but in version 1.58 instead of the required 1.64, according to
```locate libboost```
 installed in /usr/lib/x86_64-linux-gnu/
```ls -l /usr/lib/x86_64-linux-gnu/libboost_python*```
tells us that there is only a Python 2.7 and a Python 3.5 version but not 3.6. The boost version does not matter that much and can be symbolically linked but the Python version is wrong so we cannot use this version. Apparently there are two options:
1. installing miniconda with explicit Python 3.5 and linking the library version from 1.58 to 1.64
2. installing boost by hand which is what I will try now and tell about in the next comment.

**Comment by halbmy** [comment]
You just need to install boost using conda
```conda install boost```
and then it works on my computer. Can you try this please?
We will fix the conda package so that this requirement will be considered automatically. In the meanwhile I will write this on the installing instructions.

**Comment by halbmy** [comment]
I am also adding a reminder for @florian-wagner to fix (or help us fixing) the Tab link on the Installation page.

**Comment by bigbenbell** [comment]
thank you for giving me so many advices. @halbmy "conda install boost" works on my computer. and then I use Curl installation and Mannul installation the pygimli. A anather problem appears.  

bigbenbell@ubuntu:~$ python -c 'import pygimli as pg; print(pg.__version__)'
/home/bigbenbell/anaconda3/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/bigbenbell/src/gimli/gimli/python/pygimli/core/_pygimli_.so)
Traceback (most recent call last):
  File "/home/bigbenbell/src/gimli/gimli/python/pygimli/core/__init__.py", line 33, in <module>
    from . _pygimli_ import *
ImportError: /home/bigbenbell/anaconda3/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/bigbenbell/src/gimli/gimli/python/pygimli/core/_pygimli_.so)
ERROR: cannot import the library '_pygimli_'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bigbenbell/src/gimli/gimli/python/pygimli/__init__.py", line 18, in <module>
    from . import core
  File "/home/bigbenbell/src/gimli/gimli/python/pygimli/core/__init__.py", line 43, in <module>
    _pygimli_.load = None
AttributeError: 'NoneType' object has no attribute 'load'

Maybe the gcc version is too old. I need to update the version of gcc.

**Comment by bigbenbell** [comment]
thank you for giving me so many advices. @halbmy "conda install boost" works on my computer. and then I use Curl installation and Mannul installation the pygimli. A anather problem appears.

bigbenbell@ubuntu:~$ python -c 'import pygimli as pg; print(pg.version)'
/home/bigbenbell/anaconda3/lib/libstdc++.so.6: version CXXABI_1.3.8' not found (required by /home/bigbenbell/src/gimli/gimli/python/pygimli/core/_pygimli_.so) Traceback (most recent call last): File "/home/bigbenbell/src/gimli/gimli/python/pygimli/core/__init__.py", line 33, in <module> from . _pygimli_ import * ImportError: /home/bigbenbell/anaconda3/lib/libstdc++.so.6: versionCXXABI_1.3.8' not found (required by /home/bigbenbell/src/gimli/gimli/python/pygimli/core/pygimli.so)
ERROR: cannot import the library 'pygimli'.
Traceback (most recent call last):
File "", line 1, in 
File "/home/bigbenbell/src/gimli/gimli/python/pygimli/init.py", line 18, in 
from . import core
File "/home/bigbenbell/src/gimli/gimli/python/pygimli/core/init.py", line 43, in 
pygimli.load = None
AttributeError: 'NoneType' object has no attribute 'load'

Maybe the gcc version is too old. I need to update the version of gcc.

**Comment by halbmy** [comment]
Obviously you got me wrong (and I was a bit confusing too).
There are two ways:
1. The conda way, i.e. using conda python and conda boost and conda pygimli
2. Building everything from source with own or system packages, i.e. the Ubuntu python, the ubuntu boost (or self-built) and building pyGIMLi.

Both ways should not be mixed (that's what you did and I guess that's where the error comes from).

Actually, after you did ```conda install boost``` you should be able to import pygimli and you're ready. (Make sure you do not include the self-built gimli/python path in the PYTHONPATH)

**Comment by bigbenbell** [comment]
hello,@halbmy. Because this the first time to use ubuntu. I'm not familiar with the system. I fell very sorry for making you fell confusing.  At first, I use conda to install the pygimli, But I failed. So I try Curl installation and Mannul installation. I still encounter the difficult. So I send message to you for help. Now I have solve the problem use the way that you told me. Thank you.  
   wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
   chmod +x miniconda.sh
   ./miniconda.sh -b -p $HOME/miniconda
   export PATH=$HOME/miniconda/bin:$PATH # Note: Add this to your .bashrc for permanent use
   conda config --add channels gimli --add channels conda-forge
   conda install -f pygimli
   conda install boost  # depndency missing currently
   python -c "import pygimli; pygimli.test()"

**Comment by halbmy** [comment]
Good to hear it is working. This post will help other users with similar problems.

Still keeping this issue open to check the boost dependency in conda.

**Comment by halbmy** [comment]
Good to hear it is working. This post will help other users with similar problems.

Still keeping this issue open to check the boost dependency in conda.

**Comment by florian-wagner** [comment]
The boost dependency has always been in the conda package (https://github.com/gimli-org/conda-recipes/blob/master/pygimli/meta.yaml#L33), but the specific version was likely in conflict with the boost version used by anaconda-navigator. Therefore, we recommend to use miniconda or create a separate environment for pygimli as mentioned here: https://github.com/gimli-org/gimli/issues/67#issuecomment-313689395
