### ISSUE TITLE
ERT forward simulation valid 0 or 1

### ISSUE THREAD

**Issue by HenryWHR** [gimli-org/gimli#780]
Hello,

I just had a question when I do the forward modelling. There is one column ['valid'] in the data file. What does this ['valid'] indicate? What can happen if it's all zero? Should it always be 1?

Thanks in advance for your kind reply!

Best regards,
Henry

**Comment by halbmy** [comment]
Sorry for the late response. Every data point has a `valid` flag (0 or 1) which should be set to 1 in a forward calculation. If this is not done, do it by hand using `data["valid"]=1` (setting all).

**Comment by halbmy** [comment]
`simulate` now sets 1 by default. Thank you for reporting this.

**Comment by halbmy** [comment]
solved by a149879
