### ISSUE TITLE
Traveltime inversion of a velocity model

### ISSUE THREAD

**Issue by makeabhishek** [gimli-org/gimli#785]
Hi,
I'm trying to invert following velocity model. I created the forward model using this velocity values (Figure) But the inversion results are not as expected.

<img width="203" alt="image" src="https://github.com/user-attachments/assets/f8a120e3-c886-406b-abfd-7bfd0c1df78e">

```
modInv = mgr.invert(data, 
                    mesh=pMesh,   
                    lam=250,  
                    secNodes=3, 
                    showProgress= True, 
                    verbose=True,
                    cType=2,
                   )
```
Any suggestions or reasoning why its not able to invert? Is it because the velocity is first increasing from center towards edge and then dropped? So the ray path is not able to bend?

**Comment by halbmy** [comment]
Your velocity model is practically constant considering the color scale of 1101 to 1104 as even modelling errors will be bigger than the differences to a homogeneous model. So of course you won't be able to resolve this in inversion.

**Comment by makeabhishek** [comment]
Thanks for the advise.
