### ISSUE TITLE
Export Nodes and Element Mesh

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#786]
Excuse me, Sir
Can a mesh simulation in Pygimli be exported for each node, element and local coordinates? If it can't be exported, can I see each nodes, elements in the form of images? I want to learn basic forward modelling by looking at the process of calculating calculated values from observed values using finite element.

**Comment by halbmy** [comment]
do you mean something like
```
u = pg.solve(mesh, ...
mesh["u"] = u
mesh.exportVTK("solution.vtk")
```
or do you want to save it as an Ascii file?
```
A = np.column_stack([pg.x(mesh), pg.y(mesh), u])
np.savetxt("out.dat", A)
```

**Comment by tonapawilliam** [comment]
I want to save it as an Ascii file. Can you give example?

**Comment by halbmy** [comment]
Did you try the two lines?

**Comment by halbmy** [comment]
If you cannot male use of IT, you should summarize you Script as it is not yet clear from you general description.

**Comment by tonapawilliam** [comment]
I'm sorry Sir, there is a bit problem when I use it, but now it was fixed.
