### ISSUE TITLE
Make Simulation ERT with Array Modification

### ISSUE THREAD

**Issue by tonapawilliam** [gimli-org/gimli#796]
I tried to create a new ERT simulation with the array I created. Can Pygimli help me with that? In the sense that I have the position of the observation data in a certain order, and also if necessary I have the current and potential electrode numbers. So let's say I create a synthetic model with Pg.Mesh, and I want to simulate that model, can I get the simulated observation resistivity values to match my X and Y position information?

**Comment by tonapawilliam** [comment]
May be this File with ABMN and XY Res can help. I want to make simulation data like this
[E05_ABMNXYR.xlsx](https://github.com/user-attachments/files/18048800/E05_ABMNXYR.xlsx)

**Comment by halbmy** [comment]
In your Excel file, you provide a list of ABMN positions which can be used to create the `DataContainerERT` that is used for simulation. But I have no idea how the X and Y values (some resistivity distribution?) could be connected to the individual quadrupoles.

**Comment by tonapawilliam** [comment]
For XZ is the datum position of the data. Res2DInv has output the depth and lateral position of the observation data based on the ABMN value. That is why there is ABMN as well as the XZ value, because I want the results of the simulated resistivity value to be at the XY point with the influence of the ABMN electrode. Can I make it like that? Or I only need ABMN for this? This the Array Position I want from ABMN File
![Edge Gradien_plot](https://github.com/user-attachments/assets/00ff5f26-2f86-4c4d-aa24-7313a69fd396)
Can you give me example how to use DataContainer? Or maybe I just want to take the simulated resistivity value on my model with the same position as this Configuration.
There is i want to know, Can Pygimli Export the Result of Inverse Each of Iteration? Just like I Want to Know how the resul of Iteration 1, 2 or 10?

**Comment by tonapawilliam** [comment]
OK thank you, I Just need ABMN right? Can you give example how to use Data Container? I try get help from AI (ChatGPT and Claude) but It doesn't work.

**Comment by halbmy** [comment]
If you read the excel file with pandas using
```
import pandas as pd
df = pd.read_excel("E05_ABMNXYR.xlsx")
```
you can create the data container like this
```
data = pg.DataContainerERT()
for i, row in df.iterrows():
    eID = [data.createSensor([row[se], 0, 0]) for se in 'ABMN']
    data.createFourPointData(i, *eID)

data.sortSensorsX()
```
yielding 70 sensors and 6036 data points.

**Comment by halbmy** [comment]
The pseudosection (`data.show(ert.geometricFactors(data))`) looks a bit strange
![image](https://github.com/user-attachments/assets/b4490273-c92d-40d4-a56f-799bef6a919f)

but this might be up to the specific array

**Comment by tonapawilliam** [comment]
OK, thank you. It's work. I want to ask one thing again, Can I output the XY Resistivity value of the Inversion result at each iteration? I want to see how the results of iteration 1 and others.

**Comment by halbmy** [comment]
Yes, we had this before. For exporting cell midpoints along with their resistivities, use
```
A = np.column_stack([pg.x(mgr.paraDomain), pg.y(mgr.paraDomain), mgr.paraModel])
np.savetxt("result.dat", A)
```

**Comment by tonapawilliam** [comment]
Thank You, I just want you to see the result of my question. Name of Array is Edge Gradient. It's made by Geomative Company. I and my Lecturer make some research about this array: 
![Figure_9](https://github.com/user-attachments/assets/9c48b1a1-14fc-4437-b5e2-a7655e55c583)
![Figure_7](https://github.com/user-attachments/assets/c2a56d60-fc64-4260-872c-5492aa72410c)

**Comment by halbmy** [comment]
sounds good! Haven't looked into Edge array. It looks like a Pole-Dipole with a fixed A pole. If you have an algorithm how to create such a scheme for a variable number of electrodes, I would be pleased to add it to the generators.
