### ISSUE TITLE
How does the error calculated for data weighting matrix?

### ISSUE THREAD

**Issue by makeabhishek** [gimli-org/gimli#798]
I'm trying to understand how the error $\epsilon_i$ for $W_d$ data was computed for the traveltime manager. There are two options to provide error to the data if it is not know in priori. `relative error` and `absolute error`. How is it computed? Is it possible to extract these values?

**Comment by halbmy** [comment]
With estimateError you Set the error as sum of absolute and relative Part and then its inverse is used for weighting.

**Comment by makeabhishek** [comment]
Thanks. I dinot understand it quite well.
For example when we do the forward modeling to create suynthetic data, 

```
data = tt.simulate(slowness=1.0 / [vp], scheme=scheme, mesh=mesh,
                   noiseLevel=0.001, noiseAbs=0.001, seed=1337, verbose=True)
```

1. So what is `noiseLevel` and `noiseAbs`.  
2. Whether this absolute noise subtracted or added to the true traveltime?
3. The relative noise is relative to what?

**Comment by halbmy** [comment]
The result of the simulate is the travel time in s. `noiseAbs` is an absolute error in s and `noiseLevel` is a relative error, i.e. 0.1% of the simulated traveltimes. The resulting error vector is used to scale random noise, i.e. it is the standard deviation. Apparently, we need a tutorial to make this clear.

**Comment by makeabhishek** [comment]
Thanks again for the description. I understood that there is absolute error. But this error can be additional to true travel time or we can subtract it from true travel time. So what is followed in Pygimli? 

Same for the relative error.

**Comment by halbmy** [comment]
The error model is the assumed standard deviation of the data misfit. If there is a known systematic error we should subtract it, but we don't know it and can only assume from our experience or from consideration of measuring errors. But we don't know individual errors but only in a statistical sense (e.g. their standard deviation).

In most methods, the error is composed of an absolute and a relative term. In traveltime, the absolute error is expected to dominate, whereas in resistivity methods (where the data cover a wide range of magnitudes) a relative error is more realistic. Maybe this example helps: https://www.pygimli.org/_examples_auto/3_ert/plot_10_reciprocal_analysis.html

**Comment by makeabhishek** [comment]
As discussed in [Regularization tutorial](https://www.pygimli.org/_tutorials_auto/3_inversion/plot_5_Regularization.html) at Pygimli, 

$$\mathbf{W_d} = diag(1/\epsilon_i)$$

![image](https://github.com/user-attachments/assets/67d826d1-4966-41e3-b582-d738f932c532)"Misfit Function"

For a test data, lets assume we have 
```
# Given Traveltime
traveltime = [0.0001063, 0.0001086, 0.0001226, 0.0001301, 0.0001369, 0.0001359, 0.0001293, 0.0001419, 0.0001396, 0.0001404, 0.0001306, 0.0001254, 0.0001309, 0.0001082, 0.0001167]
# Calculate Standard Devaition of given traveltime data
Dstd = np.std(traveltime)
Dmean = np.mean(traveltime)

```
So in order to distribute the error. Do we just randomly allocate absolute error to each traveltime data following the `std`?

**Comment by halbmy** [comment]
No, please read carefully. The error is the expected standard deviation of the noise (which you do not now). And no, we do not randomly allocate errors. In the easiest case, all (absolute) errors are the same, sometimes there can be a relative error accounting for phase picking or dispersion problems at longer offsets.

**Comment by makeabhishek** [comment]
Thanks for the clarification. So as mentioned in above comment (Quoting here)
> The result of the simulate is the travel time in s. `noiseAbs` is an absolute error in s and `noiseLevel` is a relative error, i.e. 0.1% of the simulated traveltimes. The resulting error vector is used to scale random noise, i.e. it is the standard deviation. Apparently, we need a tutorial to make this clear.

Error can be written as a sum of absolute $(\delta_t )$ and relative $(\delta_r)$ part 

$$\epsilon_i = \delta t + \delta r \cdot t_i$$

Example
```
# Given Traveltime (t_i)
t_i = [0.0001063, 0.0001086, 0.0001226, 0.0001301, 0.0001369, 0.0001359, 0.0001293, 0.0001419, 0.0001396, 0.0001404, 0.0001306, 0.0001254, 0.0001309, 0.0001082, 0.0001167]

# Assuming absolute and relative error of 0.1% 
delta_t = 0.001         # Absolute Error
delta_r = 0.001         # Relative Error

epsilon_i = delta_t  + (delta_r * t_i)

W_d =  1/epsilon_i 
```

But in reality, we don't know absolute and relative error, we can only assume from our experience or from consideration of measuring errors. Furthermore, we don't know individual errors but we can estimate only in a statistical sense (e.g. their standard deviation).

So probably we can estimate it 

------------------------------------------------------
In pygimli, we can allocate this error by,
```
data = tt.simulate(slowness=1.0 / [vp], scheme=scheme, mesh=mesh,
                   noiseLevel=0.001, noiseAbs=0.001)
```

So my last question would be, how do we get the standard deviation? Does is also need to assume from the experience?

Also, I did not understand the statement as mentioned above,
> The error model is the assumed standard deviation of the data misfit.).

Does the error change in each iteration?

**Comment by halbmy** [comment]
The noise (actual error realization inside of the data) is of course not known but random.

The error is the expected standard deviation of the noise, this is what the formula is for.

As the data stay the same during the inversion, the errors (and therefore the data weighting) do likewise. Only exception is the L1 norm minimization where the data weight is iteratively adapted based on the misfit.

**Comment by halbmy** [comment]
I guess wer habe discussed this AT sufficient length.

Merry Christ aß!

**Comment by makeabhishek** [comment]
Sorry for jumping here again. i have a follow up question when we are doing the inversion. If we are processing field data and we do not have error column there. But while doing inversion we can specify this error.

- So does it add error of 1e-3 to each travel time as shown in below code.
- How does error get processed while performing inversion?

```
    mgr = tt.TravelTimeManager(data)
    velInv = mgr.invert(data, 
                        mesh=pMesh, lam=150, secNodes=3, absoluteError=1e-3, blockyModel = True,  robustData = True, cType=2 )
```

**Comment by halbmy** [comment]
if specify an error model (by relative and/or absolute error) to the any `simulate()` function, an error vector is generated for every data point (and kept in the data container), then Gaussian normal random noise (mean=1, sd=1) is generated and multiplied with the error vector before added to the data. Assuming a perfect choice of regularization, inversion should result at chi^2=1, i.e. error-weighted misfit is also a Gaussian normal distribution with zero mean and std=1 (i.e. the noise is left over as misfit).
