### ISSUE TITLE
ERT with forward modeling solution sourced from outside pygimli?

### ISSUE THREAD

**Issue by L4student** [gimli-org/gimli#82]
Hello..
I am interested in using pygimli to explore electrical resistivity simulations for CO2 flow in a reservoir. Essentially, I would like to see how electrical resistivity changes when CO2 is present as one of the fluids, besides brine, in a rock. I understand simulating CO2 flow in a reservoir may either not be possible or accurate by using the two PDE types allowed in pygimli, so my question is whether it's possible to source the forward modeling results of CO2 flow from a different code into the pygimli environment and use that to simulate the ERT results for that flow? I have been looking for an open-source code that can provide this capability, but currently, I have not come across any code that could perform ERT simulations on CO2 flow. If that's not possible, I would appreciate your suggestion if CO2 flow can be mimicked within pygimli environment in some approximated form or as using tracer as a proxy for CO2 concentration. I am not familiar with pygimli yet, so your guidance on how to go about this problem would be helpful and appreciated.

Thanks.

**Comment by florian-wagner** [comment]
Hi @L4student,

for a task as complex as CO2 migration, I would definitely recommend to use a benchmarked multi-phase reservoir simulator that offers the appropriate constitutive relations and physical processes that might play a role in the CO2 plume behavior (thermal, mechanical, geochemical). An open-source code that has been successfully applied for CO2 reservoir simulation is http://www.dumux.org/ for example. But there are others as well.

Once you have `x, y, z, time, co2 saturation` data, it is straightforward to use this for electrical resistivity simulations using pygimli. You might also want to have a look at Chapter 4 of my disseration (www.diss.fwagner.info), where CO2 saturations from the commercial ECLIPSE reservoir simulator were transferred to electrical resistivity using a experimentally established petrophysical relation for 3D-ERT simulations with pygimli.

Best wishes
Florian

**Comment by L4student** [comment]
Dear @florian-wagner,
Thanks. I downloaded your dissertation and looked over Chapter 4 as suggested, but it only gives an overview of the capability. Can you post a small example/tutorial that performs the task described in Chapter 4? That will be a great help because without some example/tutorial I am not sure how to implement it. Thanks.

**Comment by Coastal0** [comment]
Hi Florian, 

I am interested to see how you achieved conversion from x,y,z,time,saturation to pygimli for forward modelling too.
