### ISSUE TITLE
conda installation failing

### ISSUE THREAD

**Issue by L4student** [gimli-org/gimli#83]
I used the recommended commands to install pygimli using conda, but the installation fails at the `conda install -f pygimli` step. I get the following error:

```
conda install -f pygimli
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - navigator-updater
  - pygimli -> pyqt ==4.11.4 -> qt 4.8.*
Use "conda info <package>" to see the dependencies for each package.
```

I have following versions of gcc and python:
```
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Python 2.7.13 :: Anaconda 4.4.0 (64-bit)
```

**Comment by florian-wagner** [comment]
Can you try this please: https://github.com/gimli-org/gimli/issues/67#issuecomment-313689395

P.S.: We recommend Python 3: https://www.pygimli.org/faq.html#python-2-or-python-3

**Comment by L4student** [comment]
Thanks, @florian-wagner. That command to create a separate anaconda3 environment for pygimli worked. I had tried deprecating pyqt earlier (before trying your suggestion) to 4.11.4 in my anaconda2 environment, but that didn't work.

**Comment by florian-wagner** [comment]
Closing this in favor of #67.

**Comment by L4student** [comment]
> P.S.: We recommend Python 3: https://www.pygimli.org/faq.html#python-2-or-python-3

To your suggested command in #67 , if you like people to install Python 3 with virtual environment, then I suggest adding `python=3.6` with your command as following:
`conda create -n pg pygimli python=3.6`

`python=3.4` didn't work in above command.
