### ISSUE TITLE
Topography and meshtools 

### ISSUE THREAD

**Issue by carsten-forty2** [gimli-org/gimli#91]
Replace 2D components from polyCreateWorld with meshtools.

- [x] mt.createWorld(topoList=[[x,z]], spline=int)  implement with  mt.createPolygon()
- [x] mt.createParaMeshPLC(**kwargs) (2D, Topo, Spline, balanceDepth, isClosed)
- [x] Examples for mt.createParaMeshPLC(Topo, Spline, balanceDepth, isClosed) 
- [x] 3D cube
- [x] 3D extrude 2D Boundary to 3D body
- [x] 3D facet (2dmesh)
- [x] 3D merge Faces with different markers
- [x] 3D merge PLC with NO intersection but touching allowed (see test_polytools)
- [x] 3D createWorld
- [ ] further Ideas?

**Comment by florian-wagner** [comment]
Spline interpolation could also be a general function of interest to create smooth geological features in the subsurface.

**Comment by halbmy** [comment]
pg.meshtools.appendTriangleBoundary for topography (see closed bert issue https://gitlab.com/resistivity-net/bert/issues/66)
