### ISSUE TITLE
Argument error in cg17/example-2_modelling.py

### ISSUE THREAD

**Issue by L4student** [gimli-org/gimli#95]
I asked this question in another issue on Bert, and @carsten-forty2 suggested that the error for [this](https://github.com/gimli-org/gimli/blob/master/doc/paper/cg17/example-2_modelling.py) example has been rectified in the git repo, but the conda update will be made later. I replied that the last commit on this example was made ~3 months ago, and although I downloaded the git repo very recently, it's still giving the above error. Following that comment, Carsten suggested the following change to rectify the error:

> you can make quick try with:
> 
> vec=vel.T
> 
> in line 60 and 64 in example-2_modelling.py
> 

The above suggestion helped get rid of the error I was getting, which was about wrong velocity field dimension, but now I get a different error on `line 99` about lack of argument as shown:
```
  fop = ERTModelling(verbose=verbose)

  File "anaconda2/envs/pgb/lib/python2.7/site-packages/pygimli/physics/ert/ert.py", line 22, in __init__
    super().__init__()

TypeError: super() takes at least 1 argument (0 given)
```
I am asking this under a separate issue as a follow-up to the suggestion that it may also help other users who have this issue. Thanks.

**Comment by carsten-forty2** [comment]
this problem is related to your python2.7 installation .. if you update your conda to python3.6 this should work.

Using python >=3 is recommended since we will drop the support for python < 3 in the near future.

**Comment by L4student** [comment]
Yes, it works with python 3.6. Thanks for informing that you don't intend to support python < 3.

**Comment by florian-wagner** [comment]
Just as an addition: https://www.pygimli.org/faq.html#python-2-or-python-3
