### ISSUE TITLE
Correct usage of the resample function from harmfit

### ISSUE THREAD

**Issue by Coastal0** [gimli-org/gimli#97]
Hello,

Could I possibly get an example for the correct use of the resample function from pygimli.frameworks.harmfit?

I'm trying to 'fix' some electrode positions that were missed on the GPS file by interpolating the harmfit against the electrode spacing (e.g. 5m).

For example, I have 70 of the 72 electrode positions with GPS information, and I know they're at 5 meter increments. I'd like to estimate the missing points by interpolating along the fitted curve.

[gps.txt](https://github.com/gimli-org/gimli/files/1409442/gps.txt)

```
import numpy as np
import pygimli as pg
import pygimli.frameworks

tt, hh ,xx ,yy = np.loadtxt('gps.txt', unpack = True)

resampVector = np.arange(0,72,1)
x = pygimli.frameworks.harmfit(xx,tt, nc = 10)[0]
y = pygimli.frameworks.harmfit(yy,tt, nc = 10)[0]
z = pygimli.frameworks.harmfit(hh,tt, nc = 10)[0]
t= np.hstack((0.,np.cumsum(np.sqrt(np.diff(x)**2+np.diff(y)**2))))
```

**Comment by halbmy** [comment]
The aim of harmfit is to fit a smooth curve through erroneous points by using harmonic functions that can of course be applied to any abscissa. No idea whether this is what you want:
```
import numpy as np
import matplotlib.pyplot as plt
import pygimli as pg
from pygimli.frameworks import harmfit

tt, hh, xx, yy = np.loadtxt('gps.txt', unpack=True)

resampVector = np.arange(72) * 5.  # force float to make it compatible with RVector
x = harmfit(xx, tt, nc=10, resample=resampVector)[0]
y = harmfit(yy, tt, nc=10, resample=resampVector)[0]
z = harmfit(hh, tt, nc=10, resample=resampVector)[0]
t = np.hstack((0., np.cumsum(np.sqrt(np.diff(x)**2+np.diff(y)**2))))
fig, ax = plt.subplots()
ax.scatter(xx, yy)
ax.plot(x, y)
```
![grafik](https://user-images.githubusercontent.com/7136401/31928862-0161d7c0-b89a-11e7-978b-9125e60dfc42.png)

**Comment by Coastal0** [comment]
Thanks @halbmy - that's exactly what I wanted.

> # force float to make it compatible with RVector

How did you force this to be a float, and do I need to do that for most other vectors in pygimli?

**Comment by halbmy** [comment]
That's a common problem if you create a numpy vector with dtype=int by e.g. `np.arange(nmax)` pygimli core functions throw errors because numpy array is only compatible with RVector if the dtype is float. 

@carsten-forty2 Is there any way to avoid this?

**Comment by carsten-forty2** [comment]
Maybe I can try to add an automatic right value conversion from array of dtype=int to array of dtype=float for such cases but I'm unsure about possible weird side effects. 

btw .. please note that the distances between the new points along the interpolated path are not constant 5m. If you want to use them as new electrode positions with fixed electrode spacing you need a different interpolation approach. We plan to add such a function.
